Пусть (S) - сильно нормальное расширение дифференциального поля $\mathscr{F}$ с полем констант $C$. а) Если $\mathscr{F}_{1}-$ дифференциальное поле такое, что $\mathscr{F} \subset \mathcal{F}_{1} \subset()^{\prime}$ то (\$) сильно нормально над $\mathscr{F}_{1}$, группа Галуа $G\left(\left(\$ / \mathscr{F}_{1}\right)\right.$ является $C$-подгруппой в $G(\$) / \mathscr{F})$ и поле инвариантов группы $G\left(\$ / \mathscr{T}_{1}\right)$ в (\$) совпадает с $\mathscr{F}_{1}$. б) Если $G_{1}$ яв-

![](https://cdn.mathpix.com/cropped/2023_07_08_ed959b64317bcad2e445g-1.jpg?height=35&width=831&top_left_y=367&top_left_x=120)
множество инвариантов группы $G_{1}$ в (\$) то $\mathscr{F}_{1}-$ диф̆ ференциальное поле, $\mathscr{F} \subset \mathscr{F}_{1} \subset(\$)$ и $G\left(\mathfrak{S} / \mathscr{F}_{1}\right) \stackrel{\mathscr{F}}{=} G_{1}$.

Нормальным делителям $G_{1}$ группы $G\left(\$ / F_{1}\right)$ соответствуют при әтом сильно нормальные расширения $\mathscr{F}_{1}$ поля $\mathscr{F}$, п наоборот. Для связных разрепимых групп решена обратная задача Галуа, т. е. вопрос о существовании у поля $\mathscr{T}$ сильно нормального расширения (\$, группа Галуа к-рого $G(\$) / \mathcal{F})$ изоморфна заданной группе. Эта задача сведена к оценке размерности нек-рого векторного пространства над полем констант $C$ поля $\mathscr{F}$ и ранга некоторой абелевой группы. Имеются результаты по теории Галуа бесконечных расширений. Смежными с теорией Галуа вопросами занимается теория интегрирования в конечном виде.

Разрабатывается теория дифференциальных алгебраич. групп, существенно отличающаяся от своего алгебраич. аналога. В частности, дифференциальное кольцо всюду определенных дифференциальных рациональных функций на аффинном дифференциальном алгебраич. множестве не является диффференциальным координатным кольцом, и в общем случае не конечно порождено как диффференциальная алгебра.

Среди результатов о приближении дифференциально алгебраич. функций рациональными может быть отмечен аналог теоремы Лиувилля о приближении алгебраич. чисел рациональными. Однако доказательство аналога теоремы Туә - Зигеля - Рота остается (1978) проблемой.

Развивается теория колец с высшими дифференцированиями. При изучении объектов ненулевой характеристики высшие дифференцирования представляют более сильное средство. Если характеристика дифференциального кольца $A$ равна $p$, то $p$-я степень любого элемента является константой, в то время как для колец с высшими дифференцированиями это не так. Для колец с высшими дифференцированиями получены аналоги многих перечисленных выше результатов, касающихся как теории пересечения идеалов, так и теории Галуа.

Лит.: [1] К а п л а н с к и й И., Введение в дифференциальную алгебру, пер. с англ., M., 1959; [2] R i t t J. F., Difrential algebra and algebraic groups, N. Y.-L., 1973; [4] e $\Gamma$ o ж е, Some problems in differential algebra, в сб.: Тp. международного конгресса математиков. Москва 1966, М., 1968.

А. В. Михалев, Е. В. Панкратъев.

ДИФФЕРЕНЦИАЛЬНАЯ ГЕОМЕТРИЯ - раздел геометрии, в к-ром изучаются геометрич. образы, в первую очередь кривые и поверхности, методами математич. анализа. Обычно в Д. г. изучаются свойства кривых и поверхностей в малом, т. е. свойства сколь угодно малых их кусков. Кроме того, в Д. г. изучаются свойства семейств линий и поверхностей (см., нашр., Конгруэнция, Сеть).

Д. г. возникла и развивалась в тесной связи с математич. анализом, к-рый сам в значительной степени вырос из задач геометрии. Многие геометрич. понятия предшествовали соответствующим понятиям анализа. Так, напр., понятие касательной предшествовало понятию производной, понятие площади и объема понятию интеграла.

Возникновение Д. г. относится к 18 в. и связано с именами Л. Эйлера (L. Euler) и Г. Монжа (G. Monge). Первое сводное сочинение по теории поверхностей написано Г. Монжем (Приложение анализа к геомет- рии, 1795). В 1827 К. Гаусс (C. Gauss) опубликовал работу "Общее исследование о кривых поверхностях", в к-рой заложил основы теории поверхностей в еө современном виде. С тех пор Д. г. перестала быть только приложением анализа и заняла самостоятельное место в математике.

Открытие в 1826 Н. И. Јобачевским неевклидовой геометрии сыграло огромную роль в развитии всей геометрии, в том числе и Д. г. Фактически Н. И. Лобачевским было отвергнуто априорное представление о пространстве, господствовавшее ранее в математике и философии. Он открыл, что возможны пространства, отличные от евклидова. Эта идея Н. И. Лобачевского нашла отражение в различных математич. исследованиях. Так, в 1854 Б. Риман (B. Riemann) своей лекцией «O гипотезах, лежащих в основаниях геометрии» заложил основы римановой геометрии, к-рая в применении к многомерным многообразиям находится в таком же отношении к геометрии $n$-мерного пространства, как внутренняя геомтрия поверхности к евклидовой геометрии на плоскости.

Теоретико-групповая точка зрения Ф. Клейна (F. Klein), изложенная в его «Эрлангенской программе» (1872), т. е.: геометрия - учение об инвариантах групп преобразований, в применении к Д. г. была развита Э. Картаном (E. Cartan), к-рый построил теорию пространств проективной связности и аффинной связности.

В России школу Д. г. создали Ф. Миндинг и К. М. Петерсон. Их исследования посвящены в значительной степени вопросам изгибания поверхностей, т. е. таким непрерывным деформациям поверхностей, при которых внутренняя геометрия все время остается неизменной. Эти исследования были продолжены в работах многих русских и советских геометров.

Т е о ри я к р и вых. В теории кривых обычно рассматривают так наз. ре гул я р ны е к р ив ы е. Это - кривые, допускающие локальное задание уравнениями вида

\[
x=x(t), \quad y=y(t), \quad z=z(t),
\]

где $x(t), y(t), z(t)$ - достаточно регулярные функции параметра $t$. В зависимости от свойств диффференцируемости функций $x(t), y(t), z(t)$, задающих кривую, говорят о степени регулярности кривой. Кривая допускает бесчисленное множество различных способов параметрич. задания уравнениями вида (1). Среди них особое значение имеют так наз. е с т е с т в е н н а я п а р ам е т р и з а ц и я, когда парамет-

![](https://cdn.mathpix.com/cropped/2023_07_08_ed959b64317bcad2e445g-1.jpg?height=176&width=290&top_left_y=1515&top_left_x=1522)

Puc. 1. ром служит длина дуги кривой, отсчитываемая от нек-рой фиксированной точки. Точка кривой наз. о б Ы к н ов е н н о й, если при подходящем выборе прямоугольной декартовой системы координат $x, y, z$ она допускает в окрестности әтой точки задание уравнениями вида

\[
y=y(x), \quad z=z(x),
\]

где $y(x)$ и $z(x)$ - дифференцируемые функции. В противном случае точка наз. о с о б о й (см. Особая точка). В Д. г. основное изучение кривой относится к окрестности обыкновенной точки. Для того чтобы точка кривой, заданной общим уравнением (1), была обыкновенной, достаточно, чтобы в этой точке было

\[
x^{\prime 2}+y^{\prime 2}+z^{\prime 2} \neq 0 .
\]

Ряд основных понятий теории кривых вводится с помощью понятия с о п р и к о с н о в е н и я множеств, к-рое состоит в следующем. Пусть $M$ и $m-$ два множества с общей точкой $О$. Говорят, что множе-