бесшумная Д.

\[
K(x, y)= \begin{cases}p(x)-(1-p(x)) q(y), & x<y, \\ p(x)-q(x), & x=y, \\ -q(y)+(1-q(y)) p(x), & x>y .\end{cases}
\]

Рассматриваются Д., в к-рых противники располагают несколькими выстрелами или же могут расходовать имеющиеся ресурсы непрерывно.

ЛІит.: [1] К а р л и н С., Математические методы в теории игр, программировании и әкономике, пер. с англ., М., 1964.

ДЬёдОННЕ МОДУ ДЬ витта векторов $W(k)$, где $k$ - соверпенное поле характеристики $p>0$, снабженный двумя эндоморфизмами $F_{M}$ и $V_{M}$, удовлетворяющими следующим соотношениям:

\[
\begin{gathered}
F_{M}(\omega m)=\omega^{(p)} F_{M}(m), \\
\omega V_{M}(m)=V_{M}\left(\omega^{(p)} m\right), \\
F_{M}\left(V_{M}(m)\right)=V_{M}\left(F_{M}(m)\right)=p m .
\end{gathered}
\]

Здесь $\quad m \in M, \omega=\left(a_{0}, \ldots, a_{n}, \ldots\right) \in W(k), \omega^{(p)}=\left(a_{0}^{p}\right.$, $\left.\ldots, a_{n}^{p}, \ldots\right)$. Эквивалентное определение состоит в том, что $M$ есть левый модуль над кольцом $D_{k}$ (к о л ьц о м Д ь ё д о н н е), порожденным $W(k)$ и двумя переменными $F$ и $V$ связанными соотношениями

\[
\begin{gathered}
F \omega=\omega^{(p)} F, \quad \omega V=V \omega^{(p)}, \\
F V=V F=p, \quad \omega \in W(k) .
\end{gathered}
\]

Для любого целого $n>0$ существует изоморфизм

\[
D_{k} / D_{k} V^{n} \simeq \operatorname{End}_{k}\left(W_{n k}\right),
\]

где $D_{k} V^{n}$ - левый идеал, порожденный $V^{n}$, а $W_{n k}$ усеченная $k$-схема Витта. Д. м. играют важную роль в классификации унипотентных коммутативных алгебраических групп (см. [1]). Д. м. наз. также левые модули над пополнением $\hat{D}_{k}$ кольца $D_{k}$ относительно топологии, порождаемой степенями двустороннего идеала $(F, V)$ кольца $D_{k}$.

Jum.: [1] D i e u d o n n é J., "Amer. J. Math.", 1957, v. 79, № 2, p. 331-88; [2] D e m a z u r e M., G a b r i e l P., Groupes algébriques, t.1, P.- Amst., 1970; [3] М а н и н Ю. И., "Успехи
матем. наук», 1963, т. 18, в. 6, с. 3-90.

ДЮАМЕЛЯ ИНТЕГРАЛ̆ - представление решения Кощи задачи или смешанной задачи с однородными граничными условиями для неоднородного линейного уравнения с частными производнымі через решение соответствующей задачи для однородного уравнения. Пусть для уравнения

\[
\frac{\partial^{2} u(t, x)}{\partial t^{2}}+L[u(t, x)]=f(t, x) ; \quad t>0, x \in R_{n},
\]

где $L$ - линейный дифференциальный оператор с независящими от $t$ коэфффициентами, содержащий производные по $t$ не выше 1-го порядка, поставлена задача Коши с начальными условиями:

\[
\left.u(t, x)\right|_{t=0}=0,\left.\quad \frac{\partial u(t, x)}{\partial t}\right|_{t=0}=0 .
\]

И пусть достаточно гладкая функция $v(t, x ; \tau), t \geqslant \tau$, $\tau \geqslant 0, x \in R_{n}$, является при $t>\tau$ решением однородного уравнения

\[
\frac{\partial^{2} v(t, x ; \tau)}{\partial t^{2}}+L[v(t, x ; \tau)]=0,
\]

удовлетворяющим при $t=\tau$ начальным условиям:

\[
\left.v(t, x ; \tau)\right|_{t=\tau}=0,\left.\quad \frac{\partial v(t, x ; \tau)}{\partial t}\right|_{t=\tau}=f(\tau, x) .
\]

Тогда решение задачи Коши (1), (2) выражается Д. и.:

\[
u(t, x)=\int_{0}^{t} v(t, x ; \tau) d \tau
\]

Сформулированное утверждение носит название п р и н- ц и п а Д ю а м е л я и является аналогом метода вариации постоянных.

Аналогичное построение можно провести и в случае задачи Коши с однородным начальным условием для уравнения

\[
\frac{\partial u(t, x)}{\partial t}+M[u(t, x)]=f(t, x) ; \quad t>0 ; x \in R_{n},
\]

где $M$ - линейный дифференциальный оператор с независящими от $t$ коэффициентами, содержащий производные только по переменным $x$.

Решение задачи Коши с однородными начальными условиями для неоднородного уравнения теплопроводности выражается Д. и.

$u(t, x)=\int_{0}^{t} \int_{R_{n}}[4 \pi(t-\tau)]^{-\frac{n}{2}} e^{-\frac{|x-\xi|^{2}}{4(t-\tau)}} f(\tau, \xi) d \xi d \tau$, а для волнового уравнения в случае $n=1$

\[
u(t, x)=\int_{0}^{t} \int_{x-(t-\tau)}^{x+(t-\tau)} f(\tau, \xi) d \xi
\]

Д. и. наз. по имени ж. Дюамеля (J. Duhamel).

Jum.: [1] Т и х о н о в А. Н., С а м а р с к и й А. А., Уравнения математической физики, 3 изд., М., 1966; [2] й о н Ф.,
Плоские волны и сферические средние в применении к дифференциальным уравнениям с частными производными, пер. с англ., $\begin{array}{ll}\text { M., } 1958 . & \text { A. К. Гучин. } \\ & \end{array}$

ДЮБУА-РЕПМОНА ЛЕММА, Д ю- Б у аР е й м о н д а л е м м а: если $N(x)$ - непрерывная функция на отрезке $\left[x_{1}, x_{2}\right]$ и если для всех диффференцируемых функций $\eta(x)$, обращающихся в нуль при $x=x_{1}, \quad x=x_{2}$, справедливо соотношение:

\[
\int_{x_{1}}^{x_{2}} \eta^{\prime}(x) N(x) d x=0
\]

то $N(x)=$ const на отрезке $\left[x_{1}, x_{2}\right]$; сформулирована ПI. Дюбуа-Реймоном [1].

Д.-Р. л. применяется в вариационном исчислении для вывода Эйлера уравнения в интегральной форме и при этом позволяет не предполагать заранее, что экстремум функционала достигается на дважды диф̆ференцируемой кривой - достаточно предположения о непрерывной дифференцируемости.

Jum.: [1] D u B o i s - R e y mond $P$, "Math. Ann.», 1879, Bd 15, S. 313; [2] Л а в р е н т в е в М. А., Л ю с т е р-
н и к Л. А., Курс вариационного исчисления, 2 изд., М. - Ј., н и к Л. А., Курс вариационного исчисления, 2 изд., М.- Ј1.,
1950 .
И. Б. Вапнярский.

ДЮБУ А-РЕИМОНА ПРИЗНАК с х о д и м о с т и р яд а: ряд $\sum_{n=1}^{\infty} a_{n} b_{n}$, где $a_{n}$ и $b_{n}$-комплексные числа, сходится, если ряд $\sum_{n=1}^{\infty} b_{n}$ сходится, а ряд $\sum_{n=1}^{\infty}\left(a_{n}-a_{n+1}\right)$ абсолютно сходится. Установлен П. Дюбуа-Реймоном (P. Du Bois Reymond). Л. Д. Кудрлвчев. ДЮБУА-РЕЙОНА ТЕОРЕМА о е д и н с т в е нности разло жения фу нкций в р я д: если сумма всюду сходящегося тригонометрич. ряда интегрируема по Риману, то этот ряд является ее рядом Фурье; доказана П. Дюбуа-Реймоном [1]. Важный частный случай сходимости тригонометрич. ряда к нулю несколько ранее рассмотрел Г. Кантор [2].

Д.-Р. т. обобщалась в различных направлениях. Для интеграла Лебега с условием ограниченности суммы аналогичную теорему доказал А. Лебег (H. Lebesgue), без этого условия - III. Ж. Валле Пуссен (Ch. J. de la Vallée-Poussin) (см. [3], c. 200, 789). Имеются аналоги этой теоремы для интегралов Данжуа (см. [5]).

Другое направление обобщений заключается в ослаблении условия сходимости всюду. У. Юнг (W . Young) доказал, что можно пренебрегать счетным множеством (см. [3], с. 792), Д. Е. Меньшов показал, что нельзя пренебрегать любым множеством меры нуль (см. Меньшова пример нуль-ряда или [3], с. 804). О дальнейших