переменные $x=\left(x_{1}, \ldots, x_{n}\right)$. Всякая система дифференциальных уравнений с частными производными может быть приведена к нек-рой системе Д. у. с ч.П.п.п. Для этого достаточно ввести в качестве новых искомых функций все частные производные от каждой функции $u_{i}(x)$ до порядка $l_{i}-1$ включительно, если хотя бы одна производная порядка $l_{i}$ входит в к.-л. уравнение рассматриваемой системы. При этом систему следует пополнить новыми уравнениями, выражающими равенство различных смешанных производных. Напр., уравнение

\[
F\left(x, y, u, u_{x}, u_{y}, u_{x x}, u_{x y}, u_{y y}\right)=0
\]

после введения вспомогательных искомых функций $v=u_{x}, w=u_{y}$ приводится к следующей системе уравнений 1-го порядка:

\[
\begin{aligned}
& F\left(x, y, u, v, w, v_{x}, v_{y}, w_{y}\right)=0, \\
& u_{x}-v=0 \\
& u_{y}-w=0 \\
& v_{y}-w_{x}=0
\end{aligned}
\]

(последние три уравнения не независимы).

Одно Д. у. с ч. П. П. П. с одной искомой функцией задается соотношением:

\[
F(x, u, p)=0 \text {, }
\]

где $p=\left(p_{1}, p_{2}, \ldots, p_{n}\right)=\left(D_{1} u, D_{2} u, \ldots, D_{n} u\right)$. Всякое решение $u=u(x)$ уравнения (1) при определенных требованиях определяет нек-рую поверхность (и н т ег р а л ь у ю П о в е р х о о т ь) в пространстве $E_{n+1}$ переменных $\left(x_{1}, \ldots, x_{n}, u\right)$, причем $p_{i}$ яв.тяются компонентами вектора нормали к этой поверхности. Поэтому уравнение (1) задает связь между составляющими $p_{i}$ вектора нормали к интегральной поверхности и в каждой точке $(x, u)$ определяет $(n-1)$-параметрич. семейство касательных к интегральной поверхности плоскостей [или несколько таких семейств, соответствующих различным решениям уравнения (1) относительно $p$ ]. Огибающая этого семейства плоскостей наз. к о н у с о м М о н ж а [в данной точке $(x, u)]$, а направления его образующих с т и ч с с к и и н а п р а в л е ни я ми. В каждой точке $(x, u)$ эти направления определяются уравнениями

\[
\frac{d x_{1}}{F_{p_{1}}}=\frac{d x_{2}}{F_{p_{2}}}=\ldots=\frac{d x_{n}}{F_{p_{n}}}=\frac{d u}{\sum_{i=1}^{n} p_{i} F_{p_{i}}},
\]

где $p=\left(p_{1}, p_{2}, \ldots, p_{n}\right)$ - любой вектор, удовлетворяющий уравнению (1). Кривая с непрерывно изменяющейся касательной, имеющая в каждой своей точке характеристич. направление, наз. к р и в о й $\mathrm{M} о$ н ж а, или ф о к а л ь н о й к р и в о й. Фокальная кривая является интегральной кривой системы (2) при произвольно заданном непрерывно диффференцируемом векторе $p=p(x, u)$ таком, что $F(x, u, p)=0$.

Поскольку каждой точке фокальной кривой сопоставлен вектор $p$, определяющий направление плоскости, касательной к кривой в этой точке, то фокальная кривая задается одновременно со своими касательными плоскостями и наз. поэтому фо к а л ь н о й п о л о с о й. Если $\sigma$ - параметр на фокальной кривой, то уравнение

\[
\frac{\partial u}{\partial \sigma}=\sum p_{i} F_{p_{i}}
\]

системы (2) наз. у р а в н е н и е м (или у с ло в и е м) п о л о с ы.

Если фокальная кривая принадлежит интегральной поверхности $u=u(x)$ уравнения (1) и в каждой ее точке выполнены равенства $p_{i}=D_{i} u(x)$, то она наз. $\mathbf{x}$ a $\mathrm{p}$ к т е р и с тиче с ко й к р а к т е р и с т и к о й), а соответствующая фокальная полоса - х а р а к т е р и с тич е с ко й по лос о й. Характеристич. полоса определяется системой уравнений:

\[
\frac{d x_{i}}{F_{p_{i}}}=\frac{d u}{\sum p_{j}{ }^{F} p_{j}}=\frac{d p_{i}}{F_{x_{i}}{ }^{+p_{i} F_{u}}},
\]

к-рая наз. х а р а к т е р и с т и ч е с к о й с и с т ем о й уравнения (1). Функция $F(x, u, p)$ является интегралом системы уравнений (3), поэтому условие $F=0$ выполнено на всей характеристич. кривой, если оно выполнено в к.-л. ее точке. Интегральная поверхность уравнения (1), касаясь в каждой своей точке конуса Монжа, является огибающей семейства конусов Монжа и тем самым - огибающей семейства характеристич. полос. Последнее означает, что интегральная поверхность состоит из характеристич. кривых, так что ее нахождение сводится к интегрированию характеристич. системы (3). Фокальные кривые, не сводящиеся к характеристическим (если они существуют), являются огибаюими последних на интегральной поверхности $u=u(x)$. Их проекции на пространство $\left(x_{1}, x_{2}, \ldots, x_{n}\right)$ состоят из точек сингулярности решения $u(x)$.

Уравнение (1) наз. к в а 3 и л и н й н ы м, если

\[
F(x, u, p)=\sum_{i=1}^{n} f_{i}(x, u) p_{i}+f_{n+1}(x, u) .
\]

Уравнения (2) в этом случае имеют вид:

\[
\frac{d x_{i}}{f_{i}(x, u)}=-\frac{d u}{f_{n+1}(x, u)}
\]

и не содержат $p$; конус Монжа вырождается в прямую (о с ь М о н ж а), и все фокальные кривые являются характеристическими.

3 а д а ч а К о ші и для уравнения (1) состоит в нахождении интегральной поверхности, проходящей через заданное $(n-1)$-мерное (начальное) многообразие:

\[
x_{i}=x_{i}^{0}\left(\lambda_{1}, \ldots, \lambda_{n-1}\right), \quad u=u^{0}\left(\lambda_{1}, \ldots, \lambda_{n-1}\right) .
\]

Эта интегральная поверхность состоит из характеристич. кривых, проведенных через точки начального многообразия. В случае квазилинейного уравнения последние получаются интегрированием характеристич. системы (4) с начальными условиями (5). В общем случае для построения характеристич. кривых условия (5) нужно дополнить заданием начальных значений $p_{i}=p_{i}^{0}\left(\lambda_{1}, \ldots, \lambda_{n-1}\right)$, к-рые определяются из уравнений:

\[
\frac{\partial u^{0}}{\partial \lambda_{j}}=\sum p_{i}^{0} \frac{\partial x_{i}^{0}}{\partial \lambda_{j}}, j=1, \ldots, n-1,
\]

получающихся дифференцированием условий (5), и уравнения

\[
F\left(x^{0}, u^{0}, p^{0}\right)=0 .
\]

Ввиду нелинейности, уравнения (6) и (7) определяют $p_{i}^{0}(\lambda)$ и, соответственно, решение задачи Коши (1), (5), вообще говоря, неоднозначно. Пусть

\[
x_{i}=X_{i}\left(\sigma, \lambda_{1}, \ldots, \lambda_{n-1}\right), \quad u=U\left(\sigma, \lambda_{1}, \ldots, \lambda_{n-1}\right)
\]

- уравнения характеристич. кривых, проходящих через точки начального многообразия. Если начальное многообразие (5) не является характеристическим (см. Характеристическое многообразие), то эти уравнения - параметрические уравнения искомой интегральной поверхности, они определяют решение $u=u(x)$ задачи Коши, если эта поверхность однозначно проектируется на пространство независимых переменных