1) Действительная функция $y=f(x)$ действительного переменного наз. Д й ф্ фе е е н ци и у е м о й в точке $x$, если она определена в нек-рой окрестности этой точки и если существует такое число $A$, что приращение

\[
\Delta y=f(x+\Delta x)-f(x)
\]

(при условии, что точка $x+\Delta x$ лежит в упомяпутой окрестности) может быть представлено в виде

\[
\Delta y=A \Delta x+\alpha,
\]

где $\alpha / \Delta x \rightarrow 0$ при $\Delta x \rightarrow 0$. При этом $A \Delta x$ обозначается через $d y$ и наз. д и фф е рен ци а лом ф у нк ци и $f(x)$ в точке $x$. Д. $d y$ при фиксированном $x$ пропорционален $\Delta x$, т. е. является ли н е й но й ф у н к ц и е й от $\Delta x$. Дополнительный член $\alpha$ при $\Delta x \rightarrow 0$ является, в силу определения, бесконечно малой более высокого порядка по сравнению с $\Delta x$ (и по сравнению с $d y$, есліг $A \neq 0$ ). Именно в этом смысле Д. и наз. г л а вн о й частью приращения функции.

Для функции, дифференцируемой в точке $x, \Delta y \rightarrow 0$ при $\Delta x \rightarrow 0$, т. е. функция, дифференцируемая в некоторой точке, непрерывна в ней. Функция $f(x)$ дифференцируема в точке $x$ в том и только в том случае, если она имеет в этой точке конечную производную

\[
f^{\prime}(x)=\lim _{\Delta x \rightarrow 0} \frac{\Delta y}{\Delta x}=A
\]

при этом

\[
d y=f^{\prime}(x) \Delta x
\]

Существуют непрерывные, но не диффференцируемые функции.

Кроме обозначения $d y$ исгользуется обозначение $d f(x)$; тогда предыдущее равенство принимает вид

\[
d f(x)=f^{\prime}(x) \Delta x .
\]

Приращение аргумента $\Delta x$ обозначается также через $d x$ и наз. д и фф е р е нц и а л о м н е з а в и с имо г п е р е м н н о го. Поэтому можно писать

\[
d y=f^{\prime}(x) d x .
\]

Отсюда $f^{\prime}(x)=d y / d x$, т. е. производная равна отношению Д. $d y$ и $d x$. Если $A=0$, то $\Delta y / d y \rightarrow 1$ при $\Delta x \rightarrow 0$, т. е. $\Delta y$ іг $d y$ при $\Delta x \rightarrow 0$ являются в случае $A \neq 0$ эквівалентными бесконечно малыми; этим, равно как II простой структурой Д. (линейностью по $\Delta x$ ), часто пользуются в приблшженных вычислениях, полагая $\Delta y \approx d y$ при малых $\Delta x$. Если хотят, напр., вычислить $f(x+\Delta x)$, зная $f(x)(\Delta x$ мало), то полагают

\[
f(x+\Delta x) \approx f(x)+d y
\]

Конечно, такое рассуждение имеет ценность, если можно оценить соответствующую погрешность.

![](https://cdn.mathpix.com/cropped/2023_07_08_96275bc28453dd99cc03g-1.jpg?height=373&width=367&top_left_y=1828&top_left_x=134)

Рис. 1. $\Gamma$ е о мет ричес к о е истолкован и е Д. Уравнение касательной графику функции $y=f(x)$ в точке $M\left(x_{0}, y_{0}\right)$ имеет вид $y-y_{0}=f^{\prime}\left(x_{0}\right)\left(x-x_{0}\right)$. Ecли положить $x=x_{0}+\Delta x$, то $y-y_{0}=f^{\prime}\left(x_{0}\right) \Delta x . \quad$ Правая часть есть значение Д. функции $f(x)$ в точке $x_{0}$, отвечающее рассматриваемому значению $\Delta x$. Таким образом, Д. совпадает с соответствующим приращением ординаты касательной к кривой $y=f(x)$ (см. отрезок $N T$ на рис. 1). При этом $\alpha=\Delta y-d y$, т. е. значение $|\alpha|$ совпадает с длиной отрезка $T S$.

2) Определение диффференцируемости и Д. естественным образом обобщается на действительные функции от $n$ действительных переменных. Напр., в случае $n=2$ действительная функция $z=f(x, y)$ наз. дифференцируемой в точке $(x, y)$ по совокупности переменных $x$ и $y$, если она определена в нек-рой окрестности этой точки и ес п о п о е п р и р а щ е и е

\[
\Delta z=f(x+\Delta x, y+\Delta y)-f(x, y)
\]

может быть представлено в виде

\[
\Delta z=A \Delta x+B \Delta y+\alpha,
\]

где $A$ и $B$ - некоторье числа, $\alpha / \rho \rightarrow 0$ при $\rho \rightarrow 0, \rho=$ $=\sqrt{\Delta x^{2}+\Delta y^{2}}$; предполагается, что точка $(x+\Delta x, y+\Delta y)$ принадлежит упомянутой окрестности (см. рис. 2). При этом вводится обозначение

\[
d z=d f(x, y)=A \Delta x+B \Delta y
\]

и $d z$ наз. по лным дифф е р е нци а ло м, или просто д и ф ф е р е н ц а ло м, функции $f(x, y)$ в точке $(x, y)$ (иногда с добавлением: «по совокупности переменных $x$ и $y$ »). Для фиксированной точки $(x, y)$ Д. $d z$ есть л и н е й н а я функція от $\Delta x$ и $\Delta y ;$ разность $\alpha=\Delta z-d z$ есть бесконечно малая более высокого порядка по сравнению с $\rho$. В этом смысле $d z$ есть г л а в на я ли н е йна я ч а с т в приращения $\Delta z$.

![](https://cdn.mathpix.com/cropped/2023_07_08_96275bc28453dd99cc03g-1.jpg?height=216&width=230&top_left_y=770&top_left_x=1577)

Рис. 2.

Если $f(x, y)$ диффференцируема в точіє $(x, y)$, то она непрерывна в этой точке и имест в ней конечные частные производные

Таким образом

\[
f_{x}^{\prime}(x, y)=A, \quad f_{y}^{\prime}(x, y)=B
\]

\[
d z=d f(x, y)=f_{x}^{\prime}(x, y) \Delta x+f_{y}^{\prime}(x, y) \Delta y .
\]

Приращения $\Delta x$ и $\Delta y$ независимых переменных, как и в случае одного переменного, обозначаются $d x$ и $d y$. По этой причине можно написать

\[
d z=d f(x, y)=f_{x}^{\prime}(x, y) d x+f_{y}^{\prime}(x, y) d y .
\]

Существованıе конечных частных производных, вообще говоря, не влечет диффференцируемости функции (даже если предполагать заранее ее непрерывность) здесь нарушается аналогия с функциями одного переменного.

Если функция $f(x, y)$ имеет в точке $(x, y)$ частную производную по $x$, то произведение $f_{x}^{\prime}(x, y) d x$ наз. ее ч а с т ным д иф ф е р е н ц и а ло п по $x$; аналогично, $f_{y}^{\prime}(x, y) d y$ есть частный Д. по $y$. Если функция

![](https://cdn.mathpix.com/cropped/2023_07_08_96275bc28453dd99cc03g-1.jpg?height=371&width=386&top_left_y=1730&top_left_x=988)
диффференцируема, то ее полный Д. равен сумме частных Д. $\Gamma$ е о ме т р и ч ес к и полный Д. $d f\left(x_{0}, y_{0}\right)$ есть приращение аппликаты касательной плоскости гк поверхности $z=f(x, y)$ в точке $\left(x_{0}, y_{0}, z_{0}\right)$, где $z_{0}=f\left(x_{0}, y_{0}\right)$ (см. рис. 3).

Д остат очны й призн а к диффференцируемости функции: если в нексторой окрестности точки $\left(x_{0}, y_{0}\right)$ функция $f(x, y)$ имеет частную производную $f_{x}^{\prime}$, непрерывную в точке $\left(x_{0}, y_{0}\right)$, и, кроме того, имеет в точке $\left(x_{0}, y_{\theta}\right)$ частнуг производную $f_{y}^{\prime}$, то $f(x, y)$ диффференцируема в этой точке.

Если функция $f(x, y)$ диффференцируема в каждой точке открытой области $D$, то в любой точке этой области

\[
d z=A(x, y) d x+B(x, y) d y
\]