![](https://cdn.mathpix.com/cropped/2023_07_08_64ce9cbc2045861dfe6ag-1.jpg?height=67&width=836&top_left_y=186&top_left_x=119)
$(m$ - неотрицательное целое), если для любого $x \in R$
отображение $D_{x}: \quad N \rightarrow M, \quad$ определяемое формулой

\[
D_{x}(n)=D(x n)-x D(n)
\]

является Д. о. порядка $\leqslant m-1$. При этом Д. о. п ор я д к а 0 наз. гомоморфизм $R$-модулей $N \rightarrow M$. Множество всех таких Д. о. образует подмодуль $\operatorname{Diff}_{S}^{m}(N, M)$ $R$-модуля всех гомоморфизмов $S$-модулей $\operatorname{Hom}_{S}(N, M)$. В частности,

![](https://cdn.mathpix.com/cropped/2023_07_08_64ce9cbc2045861dfe6ag-1.jpg?height=58&width=471&top_left_y=487&top_left_x=308)

a фактормодуль

$\operatorname{Diff}_{S}^{1}(N, M) /$ Diff $\stackrel{0}{S}_{(N, M)}$

изоморфен модулю $S$-дифференцирований $\operatorname{Der}_{S}(R, M)$ кольца $R$ со значениями в $M$. Объединение $\operatorname{Diff}_{S}(M)$ возрастающего семейства подмодулей

Diff $\stackrel{0}{S}(M, M) \subset \operatorname{Diff} \stackrel{1}{S}(M, M) \subset \ldots$

является фильтрованным ассоциативным кольцом относительно операции композиции отображений. Это кольцо наз. ко л ь I о м д и фф ф е р е нц и а л ьных о п е р а т о р о в $\boldsymbol{R}$-модуля $M$ над подкольцом $S$, а соответствующее градуированное кольцо

\[
\operatorname{Symb}_{S}(M)=\oplus_{i} \geqslant 0 \operatorname{Symb}_{S}^{i}(M),
\]

где

\[
\operatorname{Symb}_{S}^{i}(M)=\operatorname{Diff}_{S}^{i}(M, M) / \operatorname{Diff}_{S}^{i-1}(M, M),
\]

наз. ко л ь цо м с и м в ло о. Образ Д. о. $D \in$ $\in \operatorname{Diff}_{S}^{i}(M, M)$ в кольце $\operatorname{Symb}_{S}^{i}(M)$ наз. с и м в о л о м Д. 0.

Если $R$ является алгеброй над полем рациональных чисел и модуль дифференциалов $\Omega_{R / S}^{1}$ проективен, то существует изоморфизм $S$-алrебры $\operatorname{Diff}_{S}(R)$ и обертывающей алгебры алгебры Ли $S$-дифференцирований $\operatorname{Der}_{S}(R, R)$. В этом случае кольцо $\operatorname{Symb}_{S}(R)$ изоморфно симметрич. алгебре $R$-модуля $\operatorname{Der}(R, R)$.

Напр., пусть $R=k[T]$ - кольцо многочленов над полем $k$; отображения $\partial / \partial T^{i}: \quad R \rightarrow R, \quad$ определяемые формулой

\[
\frac{\partial}{\partial T^{i}}\left(T^{r}\right)=\left(\begin{array}{c}
r \\
i
\end{array}\right) T^{r-i}
\]

являются Д. о. кольца $R$ над $k$ порядка $i$. Кольцо Д. о. $\operatorname{Diff}_{k}(R)$ - свободный модуль над $R$ с базой $\partial / \partial T^{0}$, $\partial / \partial T^{1}, \ldots, \partial / \partial T^{i}$. Умножение задается формулой

\[
\frac{\partial}{\partial T^{i}} \circ \frac{\partial}{\partial T^{j}}=\left(\begin{array}{c}
i+j \\
i
\end{array}\right) \frac{\partial}{\partial T^{i+j}} .
\]

В частности,

\[
\left(\frac{\partial}{\partial T^{1}}\right)^{n}=n ! \frac{\partial}{\partial T^{n}}
\]

(фо р м у л а Т е й ло ра), что в случае, когда характеристика поля $k$ равна 0 , дает

\[
\operatorname{Diff}_{k}(R) \cong R\left[\frac{\partial}{\partial T^{1}}\right] .
\]

Если $\operatorname{Spec}(R)$ является аффинной групповой $S$ схемой, то можно рассматривать также инвариантные Д. о. кольца $R$ (см. [2]).

И. Лum.: [1] В и ног р а д о в А. М., К р а с и л ь щ и к о в И. C., "Успехи матем. наук», 1975, т. 30, в. 1, c. 173-98; P., 1967, ch. 4; [3] D e m a z u r e M., G a b r ie l P., Groupes algébriques, t.1, P. Amst, 1970 ; [4] B j ö r k J.-E., sInvent.

ДИФФЕРЕНЦИАЈБНБІઁ ПАРАМЕТР, д и фф ер е н ц и а т о р,- совместный дифференциальны й инвариант одной или нескольких функций и метрич. тензора $g_{i j}$ римановой геометрии. Д. П. 1 - г о п о р я д к а (п е р в ый Д. п.) функции $V$ есть квадрат ее градиента:

\[
\Delta_{1} V=g^{i j} V_{i} V_{j}
\]

С м е ші а н н ы й Д. п. 1-го порядка функций $V$ и $W$ есть скалярное произведение градиентов этих функций

\[
\Delta_{1}(V, W)=g^{i j} V_{i} W_{j}
\]

В трехмерном евклидовом пространстве в декартовой прямоугольной системе координат эти Д. П. выражаются формулами:

\[
\begin{gathered}
\Delta_{1}(V)=\left(\frac{\partial V}{\partial x}\right)^{2}+\left(\frac{\partial V}{\partial y}\right)^{2}+\left(\frac{\partial V}{\partial z}\right)^{2}, \\
\Delta_{1}(V, W)=\frac{\partial V}{\partial x} \frac{\partial W}{\partial x}+\frac{\partial V}{\partial y} \frac{\partial W}{\partial y}+\frac{\partial V}{\partial z} \frac{\partial W}{\partial z} .
\end{gathered}
\]

Д. П. 2 - го по р я д к а (в т о р о й Д. п.) функции есть дивергенция ее градиента:

\[
\Delta_{2}(V)=g^{i j} \nabla_{i} V_{j}=\frac{1}{V \bar{g}} \frac{\partial}{\partial x^{i}}\left(\sqrt{ } g g^{i j} V_{j}\right),
\]

где $g-$ определитель матрицы $\left\|g_{i j}\right\|_{.}$В трехмерном евклидовом пространстве в декартовой прямоугольной системе координат второй Д. п. выражается формулой

\[
\Delta_{2}(V)=\frac{\partial^{2} V}{\partial x^{2}}+\frac{\partial^{2} V}{\partial y^{2}}+\frac{\partial^{2} V}{\partial z^{2}} .
\]

Первоначально Д. п. были введены Г. Ламе [1] в евклидовой геометрии. Обобщение этого понятия для римановой геометрии принадлежит Э. Бельтрами [2]. Поэтому Д. п. иногда наз. д и фф ф е р е и ши и л ь н ыми па раметрам Л аме, или диффе ренциальными параметрами Бельтрами. Jum: : [1] L a m é G, Leçons sur les coordonnées curvilignes Ricerche di analisi applicata alla geometria, «G. mat. Battag-

![](https://cdn.mathpix.com/cropped/2023_07_08_64ce9cbc2045861dfe6ag-1.jpg?height=50&width=831&top_left_y=1201&top_left_x=989)
ории поверхностей в тензорном изложении, ч. $1-2$, М.- J., $1947-48 ;$ [4] Ш у ли к о в с к и й В. И., Классическая дифференциальная геометрия в тензорном изложении, М., 1963.

В. Н. Шіликовский. ДИФФЕРЕНЦИРОВАНИЕ - операция, к-рая относит функции ее производную или дифференциал. При этом речь может идти о производной или дифференциале в точке или на нек-ром множестве, о частных производных, о производной по направлению, о частных и полных дифференциалах, а сами функции могут быть не только числовыми, но и функциями более общей природы.

ДИФФЕРЕНЦИРОВАНИЕ к о л ь ц а - отображение $\partial$ кольца $R$ в себя, являющееся эндоморфизмом аддитивной группы кольца $R$ и удовлетворяющее соотношению

\[
\partial(x \cdot y)=x \partial(y)+\partial(x) y .
\]

Пусть $M$ - левый $R$-модуль. Д и фф е р е н и р о-

![](https://cdn.mathpix.com/cropped/2023_07_08_64ce9cbc2045861dfe6ag-1.jpg?height=42&width=829&top_left_y=1750&top_left_x=992)
наз. гомоморфизм соответствующих аддитивных групп, удовлетворяющий условию

\[
\partial(x \cdot y)=x \partial(y)+y \partial(x)
\]

для всех $x, y$ из $R$. Для любого элемента $c$ из центра $C$ кольца $R$ отображение $x \rightarrow c \partial(x)$, где $\partial-$ диффференцирование, является Д. Сумма двух дифференцирований также является Д. Это определяет на множестве всех Д. кольца $R$ со значениями в $M$ структуру $C$-модуля, обозначаемого $\operatorname{Der}(R, M)$. Если $S$ подкольцо в $R$, то Д. $\partial$ такое, что $\partial(s)=0$ для всех $s \in S$ наз. $S$-диф̆ференцированием. Множество всех $S$-диффференцирований образует подмодуль в $\operatorname{Der}(R, M)$, обозначаемый $\operatorname{Der}_{S}(R, M)$. Операция

\[
\left[\partial, \partial^{\prime}\right]=\partial \circ \partial^{\prime}-\partial^{\prime} \circ \partial
\]

определяет в $S$-модуле $\operatorname{Der}_{S}(R, M)$ структуру $S$-ал-

![](https://cdn.mathpix.com/cropped/2023_07_08_64ce9cbc2045861dfe6ag-1.jpg?height=45&width=826&top_left_y=2280&top_left_x=986)