$\left(S_{p}\right.$ наз. т р е у г о л ь н о й ч а с т и ч но й с у мм о й Д. р. (1)), то Д. р. (1) наз. сходящимся, если последовательность $\left\{S_{p}\right\}$ сходится; ее предел

\[
S=\lim _{p \rightarrow \infty} S_{p}
\]

наз. треугольной суммой ряда (1).

Если положить

\[
S_{r}=\sum_{m^{2}+n^{2} \leqslant r^{2}} u_{m n}, \quad r>0
\]

( $S_{r}$ наз. к р у г о в о й ч а с т и ч н о й с у м мо й), то Д. р. (1) наз. сходящимся, если функция $S_{r}$ параметра $r$ имеет предел при $r \rightarrow+\infty$, этот предел

\[
S=\lim _{r \rightarrow+\infty} S_{r}
\]

наз. круговой суммой ряда (1).

Если через $\mathfrak{R}$ обозначить произвольное конечное множество пар индексов $(m, n)$ и положить

\[
S_{\Re}=\sum_{(m, n) \in \mathfrak{\Re} n} u_{m}
\]

то число $S$ наз. с у м м о й ряда (1), если для любого $\varepsilon>0$ существует такое конечное множество $\Re_{\varepsilon}$ пар индексов $(m, n)$, что для любого $\mathfrak{l} \supset \mathfrak{\Re}$ выполняется неравенство $\left|S-S_{\mathfrak{\Re}}\right|<\varepsilon$. Если такое число $S$ существует, то ряд (1) наз. сходящимся.

Все эти определения сходимости Д. р. (1) не эквивалентны между собой. Однако, если члены Д. р. неотрıцательны, то из сходимости в одном из указанных смыслов следует сходимость во всех остальных, причем все значения сумм Д. р. (1) в этом случае совпадают. Имеются и другие определения сходимости Д. р. Для Д. р. существуют различные методы суммирования. Понятие Д. р. обобщается на случай, когда его члены являются не числами, а, напр., элементами линейного нормированного пространства.

Jlum.: [1] P r ings h e i m A., "Münchener Sitzungsber. der Math.", 1897, Bd 27, S. 101-53; [2] e r o w e, "Math. Ann.", 1900, Bd 53, S. 289-321; [3] e г o ж e, Vorlesungen über Zahlenlehre, Bd 2, Lpz.-- B., 1923; [4] B r o m w i c h T. J., Theory of infinite series, 2 ed,' L. 1926; [5] С а л е х о в $\Gamma$. C., Вычи.-Нение курс современного анализа, пер. с англ., 2 2 изд., т. 1. Д.,-Н., Курс современного анализа, пер. с англ., 2 изд., т. 1,

ДВОЙНЫЕ И ДУАЛЬНЫЕ ЧИСЛА - әиперкомплексные числа вида $a+b e$, где $a$ и $b$ - действительные числа, и для двойных чисел $e^{2}=+1$, а для дуальных чисел $e^{2}=0$. Сложение Д. и д. ч. определяется формулой

\[
\left(a_{1}+b_{1} e\right)+\left(a_{2}+b_{2} e\right)=\left(a_{1}+a_{2}\right)+\left(b_{1}+b_{2}\right) e .
\]

Умножение двойных чисел производится по формуле

\[
\left(a_{1}+b_{1} e\right)\left(a_{2}+b_{2} e\right)=\left(a_{1} a_{2}+b_{1} b_{2}\right)+\left(a_{1} b_{2}+a_{2} b_{1}\right) e,
\]

а дуальных чисел - по формуле

\[
\left(a_{1}+b_{1} e\right)\left(a_{2}+b_{2} e\right)=a_{1} a_{2}+\left(a_{1} b_{2}+a_{2} b_{1}\right) e .
\]

Һомплексные числа, двойные числа и дуальные числа наз. также к о мп л е к с ны м и ч и с л а ми ги пер болического, эл липтиче ского и п а р а б л и ч е с к о г о т и По в соответственно. Иногда при помощи этих чисел изображают движения трехмерных пространств Лобачевского, Римана и Евклида (см., напр., Винтовое исчисление).

Как двойные, так и дуальные числа образуют двумерные (с базой 1 и $e$ ) ассоциативно-коммутативные алгебры над полем действительных чисел. В отличие от поля комплексных чисел эти алгебры содержат делители нуля, причем в алгебре двойных чисел все делители нуля имеют вид $a \neq a e$. Алгебра двойных чисел может быть разложена в прямую сумму двух полей действительных чисел. С этим свойством связано еще одно название двойных чисел - р а с щ е п л я е м ы е к о п п е к с ны е ч и сла. Встречается и другое наименование двойных чисел - п а р а к о м п л е к сны е ч и с л а. Алгебра дуальных чисел рассматривается не только над полем $\mathbb{R}$ действительных чисел, но и над произвольным полем или коммутативным кольцом. Пусть $A$ - коммутативное кольцо с единицей и $M$ есть $A$-модуль. Прямая сумма $A$-модулей $A \oplus M$ относительно умножения

\[
(a, m)\left(a^{\prime}, m^{\prime}\right)=\left(a a^{\prime}, a m^{\prime}+a^{\prime} m\right)
\]

является коммутативной $A$-алгеброй и обозначается $I_{A}(M)$. Она наз. а л г е б р о й д у а л ь н ы х чис е л о т но с и т е ль но мо д у л я $M$. $A$-модуль $M$ отождествляется с идеалом алгебры $I_{A}(M)$, служащим ядром пополняющего гомоморфизма

\[
\varepsilon: I_{A}(M) \longrightarrow A \quad((a, m) \longrightarrow a)
\]

При этом квадрат $M^{2}$ данного идеала равен нулю, а $I_{A}(M) / M \simeq A$. Если $A$ - регулярное кольцо, то верно и обратное: если $B$ есть $A$-алгебра и $M$ - идеал в $B$ такой, что $M^{2}=0$ и $B / M \simeq A$, то $B \simeq I_{A}(M)$, где $M$ pacсматривается как $A$-модуль (см. [4]).

При $M=A$ алгебра $I_{A}(M)$ (обозначаемая в этом случае $I_{A}$ ) изоморфіна факторалгебре алгебры многочленов $A(T)$ по идеалу $T^{2}$. Многие свойства $A$-модуля $M$ можно переформулировать как свойства алгебры $I_{A}(M)$, что позволяет сводить многие вопросы об $A$ модулях к соответствующим вопросам в теории колец (см. [2])

Если $B$ - произвольная $A$-алгебра, $\varphi: B \rightarrow A-$ гомоморфизм и $\partial: \quad B \rightarrow M-$ - дифференцирование $B$ со значением в $A$-модуле $M$, рассматриваемом как $B$ модуль относительно гомоморфизма $\varphi$, то отображение $\bar{\partial}: B \rightarrow I_{A}(M)(b \rightarrow(\varphi(b), \partial(b)))$ является гомоморфизмом $A$-алгебры. Обратно, для любого гомоморфизма $A$-алгебр $f: B \rightarrow I_{A}(M)$ композиция $\varepsilon^{\prime} \circ f: B \rightarrow M, \quad$ где $\varepsilon^{\prime}: I_{A}(M) \rightarrow M$ - проекция $A$ на $M$, является $A$-дифференцированием $B$ со значением в $M$, рассматриваемом как $B$-модуль относительно гомоморфизма $\varepsilon \circ f: B \rightarrow A$. Әто свойство Д. ІІ Д. ч. используется для определения касательного пространства к произвольному функтору на категории схем [1], [3].

Лum.: [1] м а м ф о р д Д., Лекции о кривых на алгебраической поверхности, пер. с англ., М., 1968; [2] F o s s u m R., Trivial extensions of abelian categories, B., 1975; [3] $\mathrm{S} \mathrm{c} \mathrm{h} \mathrm{é} \mathrm{m}$ a s en groupes, I, B., 1970; [4] L i c h t e n b a u m S., S c h l e ss i n g e r M., "Trans. Amer. Math. Soc.", 1967, v. 128, № 1 p. 41-70. И. В. Долгачев.

ДВОЙТВЕННАЯ КАТЕГОРИЯ, д у а л ь н а я к а т е г о р и я, к категории $C-$ категория $C^{\circ}$ с теми же объектами, что и $C$ и с множествами морфизмов $\operatorname{Hom}_{C^{\circ}}(A, B)=\operatorname{Hom}_{C}(B, A)$ («обращение стрелок»). Композиция морфизмов $u$ с $v$ в категории $C^{\circ}$ определяется как композиция $v$ с $u$ в $C$. Понятия и утверждения, относящиеся к категории $C$, заменяются двойственными понятиями и утверждениями в $C^{\circ}$. Так, понятие эпиморфизма двойственно понятию мономорфизма, понятие проективного объекта - понятию инъективного объекта, прямое произведение - прямой сумме и т. Д. Контравариантный функтор на $C$ становится ковариантным на $C^{\circ}$.

Иногда д в о й с т в е н на я к а т е гория имеет непосредственную реализацию: так, категория дискретных абелевых групп эквивалентна Д. к. к категории компактных абелевых групп (Понтрягина двойственность), а категория афинных схем эквивалентна Д. к. к категории коммутативных колец с единицей.

ДВОИСТВЕННОСТИ ПРИНЦИП - 1) Д. П. Данилов. т е ма ти ч е с ко й ло г и к е-теорема $о$ взаимозаменяемости в определенном смысле логич. операций в формулах формальных логических и логико-пред-