предел ее интегральных сумм (2) при стремлении к нулю максимальной из разностей $y_{i}-y_{i-1}$, т. е. если существует такое число $I$, что для любого $\varepsilon>0$ найдется $\delta>0$ такое, что при единственном условии $\max \left(y_{i}\right.$ $\left.-y_{i-1}\right)<\delta$ справедливо неравенство $|\sigma-I|<\varepsilon$. При этом указанный предел $I$ наз. о п р е д е ле н ны м и нт е г р а л о м Л е б е г а от функции $f(x)$ по отрезку $[a, b]$.

Вместо отрезка $[a, b]$ можно рассматривать произвольное множество, измеримое относительно некоторой неотрицательной полной счетно аддитивной меры. Возможно и другое введение интеграла Лебега, когда әтот И. первоначально определяют на множестве так наз. П р о с т ы х ф у н к ц и й (т. е. измеримых функдий, принимающих не более счетного множества значений), а затем с помощью операции предельного перехода вводят для произвольной функции, представляющей собой предел равномерно сходящейся последовательности простых функций (см. Лебега интеграл).

Каждая интегрируемая в смысле Римана функция является интегрируемой и в смысле Лебега. Обратное неверно, ибо существуют разрывные на множестве положительной меры и вместе с тем интегрируемые в смысле Лебега функции (напр., функция Дирихле).

Для интегрируемости по Лебегу ограниченной функции необходимо и достаточно, чтобы эта функция принадлежала классу измеримых функций. Функции, встречающиеся в математич. анализе, как правило, измеримы. Это означает, что интеграл Лебега обладает общностью, исчерпывающей потребности анализа.

Интеграл Лебега охватывает и все случаи абсолютно сходящихся несобственных интегралов.

Общность, достигнутая определением И. в смысле Лебега, весьма существенна во многих вопросах современного математич. анализа (теория обобщенных функций, определение обобщенных решений дифференциальных уравнений, изоморфизм гильбертовых пространств $L_{2}$ и $l_{2}$, эквивалентный так наз. теореме Рисса - Фишера в теории тригонометрических или произвольных ортогональных рядов, - все эти теории оказались возможными только при понимании И. в смысле Лебега).

Первообразную в смысле Лебега естественно определить с помощью равенства (1), в к-ром И. понимается в смысле Лебега. При таком понимании соотношение $F^{\prime}(x)=f(x)$ будет справедливо всюду, кроме, может быть, множества, имеющего меру, равную нулю.

Другие обобщения понятия интеграла. В 1894 T. Стилтьесом (T. Stieltjes) было дано другое важное для приложений обобщение интеграла Римана (получивігее название интеграла Стилтьеса), в к-ром рассматривается интегрируемость одной функции $f(x)$, определенной на некотором отрезке $[a, b]$, относительно другой функции, определенной на том же отрезке. Ин т е г р а л С т и л т ь е с а функции $f(x)$ относительно функции $U(x)$ обозначают символом

\[
I=\int_{a}^{b} f(x) d U(x)
\]

Если $U(x)$ имеет ограниченную и интегрируемую в смысле Римана производную $U^{\prime}(x)$, то интеграл Стилтьеса сводится к интегралу Рімана по формуле

\[
\int_{a}^{b} f(x) d U(x)=\int_{a}^{b} f(x) U^{\prime}(x) d x
\]

в частности при $u(x)=x+C$ интеграл Стилтьеса (3) является интегралом Римана $\int f(x) d x$.

Однако для приложений интересен случай, когда интегрирующая функция $U(x)$ не имеет производной. Примером может служить рассмотрение в качестве $U(x)$ спектральной меры при изучении спектральных разложений. Криволинейный интеграл

\[
\int_{\Gamma} f(x, y) d x
\]

вдоль кривой $\Gamma$, определяемой уравнениями $x=\varphi(t)$, $y=\psi(t), \quad a \leqslant t \leqslant b$, представляет собой частный случай интеграла Стилтьеса, так как может быть записан в виде

\[
\int_{a}^{b} f[\varphi(t), \psi(t)] d \varphi(t) .
\]

Дальнейшим обобщением понятия И. послужило интегрирование по произвольному множеству в пространстве любого числа измерений. В самом общем случае удобно рассматривать И. как функцию от того множества $M$, по к-рому производится интегрирование (см. Функции множеств) вида

\[
F(M)=\int_{M} f(x) d U(x)
\]

где $U$ - также некоторая функция множества $M$ (в частном случае его мера), а точка принадлежит множеству $M$, по к-рому идет интегрирование. Частными случаями такого рассмотрения являются кратные интегралы и поверхностные интегралы.

Другим обобщением понятия И. является понятие несобственного интеграла.

В 1912 A. Данжуа (A. Denjoy) ввел понятие И. (см. Данжуа интеграл), применимое ко всякой функции $f(x)$, являющейся производной нек-рой функции $F(x)$. Это позволило привести конструктивное определение И. к такой степени общности, при к-рой оно целиком отвечает задаче разыскания неопределенного И., понимаемого в смысле первообразной.

Лum.: [1] Ильи и В. А., Поз н я к Э. Г., Основы математического анализа, ч. 1-2, М., 1971-73; [2] К К л м оФункционального анализа, 4 изд., М., 1976; [3] K у д р я в« е в Л. Д., Математический анализ, т. 1-2, 2 изд., М., 1973; [4] Н и к о л ь с к и й С. М., Курс математического анализа, тематики, т. 5, М., 1959; [6] ЈI е б е г А., Интегрирование и отыскание примитивных функций, пер. с франц., М. Ильи., $\boldsymbol{A}$-ИНТЕГРАЛ - одно из обобщений интеграла Јебега, данное Е. Титчмаршем [1] для интегрирования функций, сопряженных к суммируемым. Измеримую функцию $f(x)$ наз. $\boldsymbol{A}$ - и н т е г р и р у е м о й на $[a, b]$, если

\[
m\{x,|f(x)|>n\}=o\left(\frac{1}{n}\right)
\]

и существует предел

\[
I=\lim _{n \rightarrow \infty} \int_{a}^{b}[f(x)]_{n} d x
\]

где

\[
[f(x)]_{n}=\left\{\begin{array}{cl}
f(x), & |f(x)| \leqslant n \\
0, & |f(x)|>n .
\end{array}\right.
\]

Число $I$ наз. $A$-и н т е г р а л о м обозначают

\[
\text { (A) } \int_{a}^{b} f(x) d x
\]

Jum.: [1] T i t o h m a r s h E. G., "Proc. London Math. Soc.", 1929 , № 29, c. 49-80; [2] В и н о г p a д о в a И. A. С к в о р Ч о В В. А., В кн.: Итоги науки. Математический
анализ. 1970, М., 1971, с. 65-107.

ИНТЕГРАЛ ВЕРОЯТНОСТИ, и н т е г р а л б о к,- функция

\[
\operatorname{erf}(x)=\frac{2}{V \bar{\pi}} \int_{0}^{x} e^{-t^{2}} d t, \quad|x|<\infty .
\]

В теории вероятностей используется не И. в., а функция нормального распределения:

\[
\Phi(x)=\frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{x} e^{-t^{2} / 2} d t=\frac{1}{2}\left[1+\operatorname{erf}\left(\frac{x}{\sqrt{2}}\right)\right]
\]