Для введения инвариантной меры предварительно ищут такую функцию от координат точки в пространстве, интеграл от к-рой по некоторой области пространства не изменялся бы после непрерывного преобразования координат пространства, составляющих определенную группу Ли. Это требует отыскания интегрального инварианта заданной группы Ли. Последний находится как решение системы диффференциальных уравнений в частных производных

\[
\sum_{i=1}^{n} \frac{\partial}{\partial x_{i}}\left[\xi_{h}^{i}(x) F(x)\right]=0, \quad h=1, \ldots, r,
\]

где $F(x)$ - искомый интегральный инвариант, $x-$ точка $n$-мерного пространства, $\xi_{h}^{i}-$ коэфффициент инфинитезимального преобразования группы, $r$ - количество параметров преобразования. Важное значение в И. г. имеют измеримые группы Ли, т. е. такие группы, к-рые допускают существование одного и только одного (с точностью до постоянного множителя) инварианта. Последними, в частности, являются простые транзитивные группы.

Следующая задача И. г. состоит в установлении меры множества многообразий, которые сохраняют свой тип после нек-рой группы непрерывных преобразований. Мера устанавливается равной интегралу

\[
\int_{A_{\alpha}}\left|F\left(\alpha^{1}, \ldots, \alpha^{q}\right)\right| d \alpha^{1} \wedge \ldots \wedge d \alpha^{q}
\]

где $A_{\alpha}$ - множество точек в пространстве параметров группы Ли, $F$ - интегральный инвариант группы, определяемый уравнением (1), или плотность меры. Подинтегральное выражение в (2) наз. также э л е м е н т а р н о й м е р о й множества многообразий. Определенный выбор этой меры полностью устанавливает соответствие с основной задачей учения о геометрич. вероятностях. Фактически под геометрич. вероятностью множества многообразий со свойством $A_{1}$ понимается относительная доля этого множества, рассматриваемого как подмножество многообразий множества многообразий, имеющих более общее свойство $A$. Задача сводится к установлению мер множества многообразий со свойством $A$, подмножества со свойством $A_{1}$ и их отношения. Последнее и есть геометрич. вероятность.

В случае однородного многомерного пространства мера множества многообразий (напр., точек, прямых, гиперплоскостей, пар гиперплоскостей, гиперсфер, гиперповерхностей 2-го порядка) однозначно (с точностью до постоянного множителя) определяется интегралом

\[
\int_{X} d H=\left[\omega_{1}, \omega_{2}, \ldots, \omega_{h}\right]
\]

где $\left\{\omega_{i}\right\}$ суть относительные компоненты $(i=1, \ldots, h)$ заданной транзитивной группы Ли $G_{2}$. Линейные комби-

![](https://cdn.mathpix.com/cropped/2023_07_08_56d8213d3d5cde34c8d0g-1.jpg?height=328&width=439&top_left_y=1771&top_left_x=120)

Рис. 1. нации $c$ постоянными коэфффициентами этих относительных компонент представляют собой левые части уравнений системы Пфафффа, соответствующей рассматриваемому множеству многообразий. Меpa (3) наз. к ин е м а т и ч е с к о й м е р о й в однородном пространстве с заданной в нем группой преобразований. Она представляет собой обобщение так наз. к и н е м а т и ч е ск о й м е р ы П у а п к а р е. (Далее все меры указываются с точностью до постоянного множителя.)

И. г. н а е в клидо в о й П ло ск о с т и $E^{2}$ обычно рассматривает лишь одно непрерывное преобразо- вание - группу движений (без отражений). Для множества точек интегральный инвариант - единица, для множества прямых - тоже единица, если в качестве параметров прямых выбраны параметры ее нормального уравнения $p$ и $\varphi$. Длина произвольной кривой равна $\frac{1}{2} \int n d p d \varphi$, где $n$ - число пересечений прямых с кривой, а интегрирование ведется по множеству прямых, пересекающих кривую. Мера множества прямых, пересекающих две выпуклые фигуры (овалы), равна разности длин перекрестно охватывающей овалы кривой и внешней охватывающей кривой (см. рис. 1). Мера множества прямых, разделяющих два овала, равна длине перекрестно охватывающей кривой без суммы длин контуров овалов. Мера множества пар точек определяется как

\[
\int\left|t_{2}-t_{1}\right| d p \wedge d \varphi \wedge d t_{1} \wedge d t_{2}
\]

где $p, \varphi$ - параметры нормального уравнения прямой, проходящей через точки, а $t_{1}$ и $t_{2}$ суть расстояния по этой прямой от точек до точки пересечения прямой и перпендикуляра к прямой, проведенного из начала координат (см. рис. 2). Мера множества пар прямых равна

\[
\int\left|\sin \left(\alpha_{1}-\alpha_{2}\right)\right| d x \wedge d y \wedge d \alpha_{1} \wedge d \alpha_{2},
\]

где $x$ и $y$ - координаты точки пересечения пары прямых, а $\alpha_{1}$ и $\alpha_{2}$ - углы, к-рые составляют эти прямые с

![](https://cdn.mathpix.com/cropped/2023_07_08_56d8213d3d5cde34c8d0g-1.jpg?height=307&width=446&top_left_y=1067&top_left_x=985)

Рис. 2.

![](https://cdn.mathpix.com/cropped/2023_07_08_56d8213d3d5cde34c8d0g-1.jpg?height=305&width=419&top_left_y=1068&top_left_x=1408)

Pис. 3 . одной из координатных осей (см. рис. 3). Мера множества пар кривых, пересекающих овал, равна половине квадрата длины кривой, ограничивающей овал, без площади овала, умноженной на л (ф о р м у л а К р офт о на). Применение кинематич. меры к множеству конгруэнтных овалов, пересекающих заданный овал, позволяет получить одно из изопериметрич. неравенств, а именно классическое Боннезена неравенство. Если $I_{n}=\int_{G} \sigma^{n} d p d \varphi, J_{n}=\int_{H} r^{n}\left|t_{2}-t_{1}\right| d p \wedge d \varphi \wedge d t_{1} \wedge d t_{2}$, где $\sigma$ - длина хорды овала $H, G-$ множество пересекающих овал прямых, $r$ - расстояние между двумя точками внутренней области овала, то

\[
J_{n}=2 I_{n+3} /(n+2)(n+3),
\]

что позволяет просто определить среднее расстояние между двумя точками внутри овала. Кинематич. мера множества фигур есть мера множества фигур, конгруэнтных данной. Она равна

\[
\int_{X} d x \wedge d y \wedge d \varphi
\]

где $X$ - множество точек фигуры, $x, y-$ координаты ее фиксированной точки, $\varphi$ - угол, определяющий поворот фигуры. Кинематич. мера может трактоваться как мера множества подвижных систем координат. Если неподвижную систему координат сделать подвижной, а подвижную - неподвижной, то для одного и того же множества преобразований кинематич. мера оста-