функции выигрыша к-рых имеют разрыв на диагонали квадрата, возрастают по первой переменной и убывают по второй. В таких играх существуют значение игры II оптимальные стратегии у обоих игроков. При нек-рых дополнительных предположениях решение таких игр сводится к решению интегральных уравнений. Другим классом И. с в. м. в. являются дуэли - антагонистич. игры, в к-рых действия игроков направлены на уничтожение противника, так что в дуэли возможны четыре различных исхода. Для дуэлей существуют аналитич.

![](https://cdn.mathpix.com/cropped/2023_07_08_c374e407e6339903637ag-1.jpg?height=30&width=826&top_left_y=489&top_left_x=123)
стратегий игроков. Теория дуэлей имеет как военное, так и экономич. приложения (конкурентная борьба за рынки, рекламная кампания и т. П.).

Лuт.: [1] К а р л и н С., Математические методы в теории игр, программировании, экономике, пер. с англ., М., 1964.

ИГРА С ИЕРАРХИЧЕСКОЙ СТРУКТУРОЙ - модель конфликтной ситуации при фиксированной последовательности ходов и обмена информацией участников. Основным объектом исследования в теории И. с и. с. является задача об отыскании напбольшего гарантированного результата и оптимальной стратегии выделенного игрока. Пусть игроки I, II стремятся к увеличению, соответственно, функций выигрыша $f_{1}\left(x_{1}, x_{2}\right)$ и $f_{2}\left(x_{1}, x_{2}\right)$, непрерывных на произведении компактов $X_{1}, X_{2} ; x_{1} \in X_{1}, x_{2} \in X_{2}$. В зависимости от характера информации и порядка ходов могут быть сформулированы следующие различные игры.

И г р а $\Gamma_{1}$. Игрок I выбирает $x_{1} \in X_{1}$ и сообщает свой выбор игроку II. Пусть

\[
P\left(x_{1}\right)=\left\{x_{2} \mid f_{2}\left(x_{1}, x_{2}\right)=\max _{y \in X_{2}} f_{2}\left(x_{1}, y\right)\right\}
\]

- множество оптимальных выборов игрока II. Тогда наибольший гарантированный результат игрока I равен

\[
G_{1}=\sup _{x_{1} \in X_{1}} \min _{x_{2} \in P\left(x_{1}\right)} f_{1}\left(x_{1}, x_{2}\right) .
\]

И г р a $\Gamma_{2}$. Игрок I рассчитывает иметь и действительно будет иметь информацию о выборах игрока II; сообщает свою стратегию - функцию $\tilde{x}_{1}=x_{1}\left(x_{2}\right)$, где $\tilde{x}_{1} \in \tilde{X}_{1}-$ множество всех отображений из $X_{2}$ в $X_{1}$, игроку II. Наибольший гарантированный результат игрока I равен

\[
G_{2}=\sup _{\tilde{x}_{1} \in \tilde{X}_{1} x_{2} \in P_{2}\left(\tilde{x}_{1}\right)} f_{1}\left(\tilde{x}_{1}, x_{2}\right),
\]

где множество оптимальных выборов игрока Il есть

\[
\boldsymbol{P}_{2}\left(\tilde{x_{1}}\right)=\left\{x_{2} \mid f_{2}\left(\tilde{x_{1}}, x_{2}\right)=\sup _{y \in X_{2}} f_{2}\left(x_{1}(y), y\right)-\delta\left(\tilde{x}_{1}\right)\right\},
\]

$\delta\left(\tilde{x}_{1}\right) \geqslant 0$, при этом $\delta\left(\tilde{x}_{1}\right)=0$ тогда и только тогда, когда достигается $\max _{y \in X_{2}}\left(x_{1}(y), y\right)$.

И г р а $\Gamma_{3}$. Игрок I рассчитывает иметь и действительно будет иметь информацию о выборах игрока II вида $\tilde{x}_{2}=x_{2}\left(x_{1}\right)$, где $\tilde{x}_{2} \in \tilde{X}_{2}-$ множество всех отображений из $X_{1}$ в $X_{2}$; сообщает игроку II свою стра-

![](https://cdn.mathpix.com/cropped/2023_07_08_c374e407e6339903637ag-1.jpg?height=52&width=836&top_left_y=1993&top_left_x=118)
бражений из $\tilde{X}_{2}$ в $X_{1}$. Наибольший гарантированный результат игрока I равен

\[
G_{3}=\sup _{\tilde{\tilde{x}}_{1} \in \tilde{\tilde{X}}_{1} \tilde{x}_{2} \in P_{3}\left(\tilde{\tilde{x}}_{1}\right)} f_{1}\left(\tilde{\tilde{x}}_{1}, \tilde{x}_{2}\right)
\]

где

$P_{3}\left(\tilde{\tilde{x_{1}}}\right)=\left\{\tilde{x_{2}} \mid f_{2}\left(\tilde{\tilde{x}_{1}}, \tilde{x_{2}}\right)=\sup _{y \in \tilde{X}_{2}} f_{2}\left(x_{1}(y), y\right)-\delta\left(\tilde{\tilde{x}_{1}}\right)\right\}$, $\delta\left(\tilde{\tilde{x}}_{1}\right) \geqslant 0$, при этом $\delta\left(\tilde{\tilde{x}}_{1}\right)=0$ тогда и толыко тогда, когда достигается $\max f_{2}\left(x_{1}(y), y\right)$.

\[
y \in \bar{X}_{2}
\]

Соотношение между результатами в этих играх определяет для игрока I значимость информации 0 действиях игрока II: $G_{1} \leqslant G_{3} \leqslant G_{2}$. Пользуясь указанной схемой в построении стратегий игроков, можно формулировать игры с произвольной глубиной рекурсии. Имеет место утверждение: в играх $\Gamma_{2 m}, m>1$, наибольший гарантированный результат игрока I равен $G_{2}$; в играх $\Gamma_{2 m+1}, m>1$, наибольший гарантированный результат равен $G_{3}$. Задача отыскания $G_{1}$ относится к классу задач на максимин со связанными ограничениями.

Развиты методы решения игры $\Gamma_{1}$, использующие штрафные функции, необходимые условія оптимальности, приближение исходной игры игрой с однозначными ответами игрока II. Полностью репены частные классы игр: с близкими интересами, биматричные, билинейные и др. Задача отыскания $G_{1}$ некорректна относительно изменения функции $f_{2}\left(x_{1}, x_{2}\right)$ в равномерной метрике и множеств $X_{1}, X_{2}$ в метрике Х аусдорфа. Предложен общий метод регуляризации решения игры $\Gamma_{1}$; регуляризация задачи по функции выггрыша игрока II осуществляется за счет введения искусственной неточности определения $\max _{x_{2} \in X_{2}} f_{2}\left(x_{1}, x_{2}\right)$. Отыскание величины $G_{2}$ сводится к решению ряда задач математического программирования.

Пусть для любого $\varepsilon>0$ определены функции, множества и велитины:

\[
\begin{aligned}
& f_{2}\left(x_{1}^{H}\left(x_{2}\right), x_{2}\right)=\min _{x_{1} \in X_{1}} f_{2}\left(x_{1}, x_{2}\right) \\
& L_{2}=\max _{x_{2} \in X_{2}} f_{2}\left(x_{1}^{H}\left(x_{2}\right), x_{2}\right)=\max _{x_{2} \in X_{2}} \min _{x_{1} \in X_{1}} f_{2}\left(x_{1}, x_{2}\right) \text {, } \\
& E_{2}=\left\{x_{2} \in X_{2} \mid f_{2}\left(x_{1}^{H}\left(x_{2}\right), x_{2}\right)=L_{2}\right\}, \\
& K=\left\{\begin{array}{cl}
\sup _{\left(x_{1}, x_{2}\right) \in D} f_{1}\left(x_{1}, x_{2}\right), & \text { если } D \neq \varnothing, \\
-\infty, & \text { если } D=\varnothing,
\end{array}\right. \\
& f_{1}\left(x_{1}^{\varepsilon}, x_{2}^{\varepsilon}\right) \geqslant K-\varepsilon, \quad\left(x_{1}^{\varepsilon}, x_{2}^{\varepsilon}\right) \in D \neq \varnothing, \\
& M=\inf _{x_{2} \in E_{2}} \sup _{x_{1} \in X_{1}} f_{1}\left(x_{1}, x_{2}\right) \text {, } \\
& D=\left\{\left(x_{1}, x_{2}\right) \mid f_{2}\left(x_{1}, x_{2}\right)>L_{2}\right\}, \\
& f_{1}\left(x_{1}^{a \varepsilon}\left(x_{2}\right), x_{2}\right) \geqslant \sup _{x_{1} \in X_{1}} f_{1}\left(x_{1}, x_{2}\right)-\varepsilon .
\end{aligned}
\]

В указанных условиях $G_{2}=\max [K, M]$ и стратегия

\[
\tilde{x}_{1}^{\varepsilon}=\left\{\begin{array}{cl}
x_{1}^{\varepsilon}, & \text { если } x_{2}=x_{2}^{\varepsilon}, K>M, \\
x_{1}^{a \varepsilon}\left(x_{2}\right), & \text { если } x_{2} \in E_{2}, K \leqslant M, \\
x_{1}^{H}\left(x_{2}\right) & \text { в остальшых случаях }
\end{array}\right.
\]

гарантирует игроку I при достаточно малых $\varepsilon$ получение $\max [K, M]-\varepsilon$. Как видно из определения, оптимальная стратегия состоит из нескольких ветвей, последняя играет роль с т р а т е г и и на к а $\mathbf{a}$ а н и.

Если $L_{2}<f_{2}\left(x_{1}, x_{2}\right)$ и у функции $f_{2}\left(x_{1}, x_{2}\right)$ нет локальных максимумов со значением $L_{2}$ на $X_{1} \times X_{2}$, то $K \geqslant M$ и оптимальная стратегия имеет простой вид:

\[
\tilde{x}_{1}^{\varepsilon}= \begin{cases}x_{1}^{\varepsilon}, & \text { если } x_{2}=x_{2}^{\varepsilon}, \\ x_{1}^{H}\left(x_{2}\right), & \text { если } x_{2} \neq x_{2}^{\varepsilon} .\end{cases}
\]

Аналогичным образом может быть найдено решение игры $\Gamma_{3}$, оно также сводится к решению ряда задач математич. программирования.

При введении в И. с и. с. побочных платежей со стороны игрока I, как функций от выборов игрока II,