\title{
भi
}

ЖАНЕ ТЕОРЕМА: во всяком аналитическом римановом многообразии размерности $n$ с отмеченной точкой существует окрестность этой точки, допускающая изометрическое аналитич. вложение в евклидово пространство $E^{s_{n}}$, где размерность $s_{n}=n(n+1) / 2$. Ж. т. сохраняет силу при замене пространства $E^{\mathcal{S}_{n}}$ произвольным аналитическим римановым многообразием размерности $s_{n}$ с отмеченной точкой (в к-рую должна переходить отмеченная точка вкладываемого многообразия). Ж. т. справедлива в случае псевдоримановых многообразий при условиях

\[
q \geqslant s_{n}, \quad q_{+} \geqslant n_{+}, \quad q_{-} \geqslant n_{-},
\]

где $n_{+}$и $n_{-}=n-n_{+}-$размерности положительной и отрицательной частей метрического тензора на погружаемом многообразии, $q_{+}$и $q_{-}=q-q_{+}-$соответствующие размерности объемлющего многообразия (см. [3]). Ж. т.- первая общая теорема вложения в римановой геометрии (см. Изометрическое погружение).

Ж. т. впервые была высказана как гипотеза Ј. ІІефли [1], доказана М. Жане [2].

Jum.: [1] S c h l ä $f$ l i L., "Ann. mat. pura ed appl.», 1873, ser. 2, t. 5, p. 178 93; [2] J a n e t M., "Ann. polon. math.", 1926, t. 5, s. 38-43; [3] Ф p и д м а н А., в сб.: Гравитация и топология, М., 1966 , с. $182-88$. А. Б. Иванов.

ЖЕГАЛКИНА АЛГЕБРА - специальная алгебра $\boldsymbol{A}=\langle A, \Omega\rangle$, где

\[
A=\{0,1\}, \quad \Omega=\{x \cdot y, x+y(\bmod 2), 0,1\},
\]

$x \cdot y$ - операция умножения. Интерес представляет клон $F$ действия $\Omega$ на $A$. Каждая операция из $F$ представляется в виде полинома по $\bmod 2$, к-рый наз. п ол и н о м о м Ж е г а л к и н а по имени И. И. Жегалкина, начавшего изучение этого клона [1]. Им было показано, что всякая конечноместная операция на $A$ содержится в $F$. Таким образом, изучение свойств клона $F$ включает в себя, в частности, изучение всех алгебр $\boldsymbol{A}=\left\langle A, \Omega^{\prime}\right\rangle$ при произвольном $\Omega^{\prime}$.

Лит.: [1] Же г а л к и н И. И., «Матем. сб.», 1927, т. 34, $\mathrm{N}_{2} 1$, с. $9 \frac{28}{} ;$; [2] K о н П., Универсальная алгебра, пер. с англ., М., 1968; [3] Я б л о нс к и й С. В., Г а в р и л о в Г. П.. Поста, M., 1966 .

ЖЕЗЛ - плоская трансцендентная кривая, уравнение к-рой в полярных координатах имеет вид:

\[
\rho=a / \sqrt{\varphi}
\]

Каждому значению $\varphi$ соответствуют два значения $\rho-$ положительное и отрицательное. Кривая состоит из двух ветвей, каждая из к-рых асимптотически приближается к полюсу (см. рис.). Прямая $\varphi=0$, $\varphi=\pi$ при $\rho= \pm \infty$ является асимптотой, $(1 / 2, \quad a \sqrt{2})$ и $(-1 / 2$, $-a \sqrt{2})$ - точки перегиба. Ж. относится к так наз. алгебраич. спиралям.

Лит.: [1] С а в е л о в А. А., Плоские кривые, М., 1960.

ЖЕЛОБ - двусвязная поверхность $S$ типа кольца, содержащая внутри себя плоскую замкнутую кривую $L$, плоскость $P$ к-рой во всех точках $L$ касается $S$. Вдоль $L$ гауссова кривизна $K \% . S$ обращается в нуль.

Если при этом $L$ разделяет Ж. $S$ на две части, на каж- дой из к-рых $K$ знакопостоянна, то соответствующие части $S$ наз. положительным и отрицательным полужелобами. Примером Ж. является узкая полоска тора вдоль одной из его замкнутых параболических параллелей.

Ж. занимает промежуточное положение между объектами геометрии «в целом» и геометрии «в малом», так как он, заключая в себе определенную замкнутую кривую $L$, не может быть сколь угодно малым, и в то же время размеры его в трансверсальных к $L$ направлениях могут быть сколь угодно малыми. Интерес к изучению Ж. вызывается тем, что достаточно узкая полоска поверхностей знакопеременной кривизны вдоль замкнутой параболич. линии часто представляет собой Ж., и поэтому знание свойств \%. при различных деформациях позволяет иногда получать информацию о соответствующих свойствах всей поверхности «в целом».

Наиболее подробно исследованы так наз. плоский Ж. (для к-рого кривая $L$ является выпуклой, а сам Ж. $S$ располагается по одну сторону от $P$, имея с $P$ касание 1-го порядка) и ЗК. вращения (когда $L$ является параллелью поверхности вращения). Для аналитич. плоских Ж. доказана их жесткость относительно аналитических бесконечно малых изгибаний 2-го порядка, а для Ж. вращения изучение их бесконечно малых изгибаний 1-го и 2-го порядков распространено до класса регулярности $C^{\mathbf{1}}$ [3]. С точки зрения диффференциальных уравнений исследование Ж. сводится к изучению уравнений смешанного типа.

Лит.: [1] Е Ф и м о в Н. В., "Успехи матем. наук", т. 3, в. 2,1948 , с. $47-158$; [2] К о н- Ф о с с е н C. Ф., Некоторые вопросы дифференциальной геометрии в целом, М., 1959; [3] 1976, т. 99, № 1, с. $49-57$.

ЖЕРГОННА ТОЧКАточка пересечения прямых, соединяющих вершины треугольника с точками касания вписанной окружности с противоположными этим верпиннам сторонами. Назва-

![](https://cdn.mathpix.com/cropped/2023_07_08_9263da126bf48fa16d0bg-1.jpg?height=245&width=424&top_left_y=1475&top_left_x=1398)
(J п Gergonne, 19 в.).

А. Б. Иванов.

ЖЕСТКАЯ ДИФФЕРЕНЦИАЛЬНАЯ СИСТЕМА система обыкновенных дифференциальных уравнений, при численном решении к-рой явными методами типа Рунге - Кутта или Адамса, несмотря на медленное изменение искомых переменных, шаг интегрирования обязан оставаться малым. Попытки уменьшить время вычисления решения Ж. д. с. за счет увеличения шага интегрирования приводят к резкому возрастанию погрешности (взрыв погрешности).

Автономная система обыкновенных диффференциальных уравнений

\[
\frac{d z(t)}{d t}=f(z(t)), \quad f(z) \in C^{p}(G), \quad G \subset R^{m},
\]

наз. Ж. д. с., если для любых начальных значений $z(0)=z^{\circ} \in G$ на заданном отрезке $[0, T]$, принадлежащем интервалу существования решения (1), выполнены условия: