№ 4, с. 907-15; [14] E фи м о в Н. В., «Матем. сб.», 1964, т. 64, № 2, c. 286-320; [15] П о з н я к Э. Г., «Укр. геометр. с0.", 1966 , в. 3, с. 78-92; [16] П о г о р е л о в А. В., "Докл. АН СССР", 1971 , т. $198,2 N_{0} 1$, с. $42-43 ;$ [17] П о 3 н я к Э. Г.,
"Успехи матем. наук", 1973 , т. 28 , в. 4, с. $47-76 ;$ [18] Б у р аго Ю. Д., 3 а лг а л л е p В. А., "Вестн. Ленингр. ун-та.

![](https://cdn.mathpix.com/cropped/2023_07_08_7a063894034ed48d66a7g-1.jpg?height=50&width=811&top_left_y=320&top_left_x=127)

ИЗОМЕТРИЧНЫЕ ПОВЕРХНОСТИ - Поверхности в евклидовом или римановом пространстве такие, что между ними можно установить взаимно однозначное точечное соответствие, при к-ром каждая спрямляемая кривая одной пз поверхностей имеет своим образом тоже спрямляемую кривую и той же длины. Другими словами, И. П. характеризуются (попарным) изометрич. соответствием - пзометрией (см. Изометрическое отображение) относительно внутренних метрик, индуцированных на них метрикой объемлющего пространства. Важнейший пример И. п.- совокупность поверхностей, полученных изаибанием данной поверхности.

Если изометрия поверхностей влечет их равенство, точнее, если для любой поверхности $F$ из нек-рого класса $K$, изометричной поверхности $F_{0}$, пространственные расстояния между соответствующими по изометрии точками $F$ и $F_{0}$ равны, то $F_{0}$ наз. о д но з на ч но о п р е д е л е н н о й, или для $F_{0}$ имеет место одназначная определенность (внутренней метрикой) в классе $K$.

Понятие И. П. обобщается на более общие категории метрич. пространств и их подмножеств.

![](https://cdn.mathpix.com/cropped/2023_07_08_7a063894034ed48d66a7g-1.jpg?height=35&width=779&top_left_y=992&top_left_x=161)
объектами или системами объектов, выражающее в некотором смысле тождество их строения. И. в произволыной категории есть обратимый морфизм, т. е. морфизм ф, для к-рого существует такой морфизм $\varphi^{-1}$, что произведение $\varphi^{-1} \varphi=\varphi \varphi^{-1}=\varepsilon-$ единичный морфизм.

Понятие И. возникло в математике применительно к конкретным алгебраич. системам (прежде всего к группам) и было естественным образом распространено на более широкий класс математич. структур. Классич. примером изоморфных, «одинаково устроенных» систем могут служить множество $R$ всех действительных чисел с определенной на нем операцией сложения и множество $P$ положительных действительных чисел с заданной на нем операцией умножения.

Пусть $\boldsymbol{A}$ и $\boldsymbol{A}^{\prime}$ произвольные однотипные алгебраические системы, записанные в сигнатуре

\[
\left\{F_{i}: i \in I\right\} \cup\left\{P_{j}, j \in J\right\}
\]

с функциональными символами $F_{i}, i \in I$ и предикатными символами $P_{i}, j \in J$ :

\[
\begin{aligned}
\boldsymbol{A} & =\left\langle A ;\left\{F_{i}: i \in I\right\},\left\{P_{j}: j \in J\right\}\right\rangle, \\
\boldsymbol{A}^{\prime} & =\left\langle\boldsymbol{A}^{\prime} ;\left\{F_{i}: i \in I\right\},\left\{P_{j}: j \in J\right\}\right\rangle
\end{aligned}
\]

И з о м о р ф и м о м, или изоморфным отображением, системы $\boldsymbol{A}$ на систему $\boldsymbol{A}^{\prime}$ наз. взаимно однозначное отображение $\varphi$ множества $A$ на множество $A^{\prime}$, обладающее свойствами:

\[
\begin{gathered}
\varphi\left(F_{i}\left(a_{1}, \ldots, a_{n_{i}}\right)\right)=F_{i}\left(\varphi\left(a_{1}\right), \ldots, \varphi\left(a_{n_{i}}\right)\right), \\
P_{j}\left(a_{1}, \ldots, a_{m_{j}}\right) \Leftrightarrow P_{j}\left(\varphi\left(a_{1}\right), \ldots, \varphi\left(a_{m_{j}}\right)\right)
\end{gathered}
\]

для всех элементов $a_{1}, a_{2}, \ldots$ из $A$ и всех $i \in I, j \in J$. Таким образом, во всякой категории алгебраич. систем И. есть гомоморфизм, являющийся биекцией. И. алгебраич. системы на себя наз. автоморфизмом.

Отношение И. обладает свойствами рефолексивности, симметричности и транзитивности, т. е. является отношением әквивалентности, разбивающим любое множество, на к-ром оно определено, на непересекающиеся классы эквивалентности - классы попарно изоморфных систем. Класс алгебраич. систем, содержащий вместе со всякой системой все ей изоморфные, наз. а бс т р а к т ны м к ла с с о м.

О. А. Иванова, Д. М. Смирнов. ИЗОМОРФИЗМА ПРОБЛЕМА - задача отыскания слгоритма, позволяющего по любой паре эфффективно заданных алгебраических систем из данного класса установить, изоморфны они или нет. Ч а с т н а я И. П. для фиксированной алгебраич. системы $A$ состоит в отыскании алгоритма, распознающего по әфффективному заданию алгебраич. системы из рассматриваемого класса, изоморфіна она системе $A$ или нет. Положительное решение (частной) И. П. состоит в указании искомого алгоритма (И. п. разрешима), отрицательное - в доказательстве того, что искомого алгоритма нет (И. П. неразрешима). Обычно И. П. ставится для алгебр, задаваемых образующими и определяющими соотношениями.

Для многих важных классов алгебр И. п. неразрешима. Доказана неразрешимость частной И. п. для произвольной конечно определенной полугруппы в классе всех конечно определенных полугрупп [2] и частной И. п. для произвольной конечно определенной группы в классе всех конечно определенных групп [1]. В классе всех групп из многообразия $n$-ступенно разрешимых групп, задаваемых в этом многообразии конечным числом образующих и определяющих соотношений, при $n \geqslant 7$ И. п. также неразрешима [3].

И. п. разрешима в классе всех конечных конечно определенных алгебр фиксированной сигнатуры, в классе абелевых групп.

Открытыми остаются пока (к 1978) И. п. для нильпотентных групп ступени 2 , групп с одним определяющим соотношением. И. п. для групп связана с алгоритмич. проблемами топологии.

Jum.: [1] А д я н С. И., «Тр. Моск. матем. об-ва», 1957, т. 6, c. $231-98 ;[2]$ M a p к о в A. А., Теория алгорифмов, ки н ск и й А. С., Ре ме с ле н ник о в В. Н., «Матем. заметки», 1975, т. 18, Nㅜ 3, с. $437-43$.

ИЗООПТИЧЕСКАЯ КРИВАЯ - плоская кривая, представляющая собой траекторию вершины данного угла $\gamma$, к-рый перемещается в плоскости так, что стороны его при любом положении угла касаются заданной кривой. Если $\gamma=\pi / 2$, то И. к. наз. о р т о о п т ич е с ко й к р и в о й. Напр., ортооптич. кривая әллипса - окружность.

Лum.: [1] С а в е л о в А. А., Плоские кривые, М., 1960.

ИЗОПЕРИМЕТРИЧЕСКАЯ ЗАДАЧА - одНа ИЗ основных задач классического вариационного исчисления. И. з. состоит в минимизации функционала:

\[
J_{0}(y)=\int_{x_{1}}^{x_{2}} f_{0}\left(x, y, y^{\prime}\right) d x
\]

при ограничениях вида

\[
\begin{gathered}
J_{i}(y)=\int_{x_{1}}^{x_{2}} f_{i}\left(x, y, y^{\prime}\right) d x=c_{i} ; f_{i}: \mathbb{R} \times \mathbb{R}{ }^{n} \times \mathbb{R} n \longrightarrow \mathbb{R}, \\
i=1, \ldots, m,
\end{gathered}
\]

и нек-рых краевых условиях.

И. 3. приводится к Лагранжа задаче при помощи введения новых переменных $z_{i}$, удовлетворяющих дифференциальным уравнениям

\[
\dot{z}_{i}=f_{i}\left(x, y, y^{\prime}\right), i=1, \ldots, m,
\]

и граничным условиям

\[
z_{i}\left(x_{1}\right)=0, z_{i}\left(x_{2}\right)=c_{i}, i=1, \ldots, m .
\]

Необходимые условия оптимальности И. з. имеют тот же вид, что и для простейшей задачи вариационного исчисления относительно Лагранжа функции:

\[
L\left(x, y, y^{\prime}, \lambda_{0}, \ldots, \lambda_{m}\right)=\sum_{i=0}^{m} \lambda_{i} f_{i}\left(x, y, y^{\prime}\right) .
\]

Название «И. з.» происходит от следующей классической задачи: среди всех замкнутых линий на плоскости с заданным периметром найти линию, к-рая ограничивает наибольшую площадь.