странствами этой группы; неприводимые непрерывные унитарные представления разрепимых связных групп Ји типа I описаны в терминах голоморфно И. п. [7]. Операция И. п. допускает обобщение на случай неунитарных представлений локально компактных групп, а также топологич. групп, не являющихся локально компактными. Изучен [6] аналог И. п. для $C^{*}$-алгебр.

Лum.: [1] К и р и л л о А. А., Элементы теории представлений, М., 1972; [2] Н а й м а р к М. А., Теория представлений групп, М., 1976; [3] С е p p Ж.-П., Јинейные М а к к и $\Gamma$. Д ж., «Математика», 1962, т. $6, ., 2$, с. $57-103$ [5] S c h m i d W., "Ann. of Math.", 1976, v. 103, p. 375-94: [6] R i e f fe l M., "Advances in Math.", 1974, v. 13, № 2, p.

![](https://cdn.mathpix.com/cropped/2023_07_08_4d4ff348275b8e2a7e3ag-1.jpg?height=34&width=821&top_left_y=566&top_left_x=130)
Ге льф а нд и. М., Г р а е в м. И., "Успехи матем. наук»,

![](https://cdn.mathpix.com/cropped/2023_07_08_4d4ff348275b8e2a7e3ag-1.jpg?height=40&width=821&top_left_y=608&top_left_x=128)
цированных представлений. Пространство - время и концепция частиц, М., $1976 . \quad$ A. К. Шітерн. ИНДУЦИРӦВАННОЕ РАССЛОЕНИЕ - расслоение $f^{*}(\pi): X^{\prime} \rightarrow B^{\prime}$, индуцированное отображением $f: B^{\prime} \rightarrow B$ и расслоением $\pi: X \rightarrow B$, где $X^{\prime}-$ подпространство прямого произведения $B^{\prime} \times X$, состоящее из пар $\left(b^{\prime}, x\right)$, для которых $f\left(b^{\prime}\right)=\pi(x)$, а $f^{*}(\pi)$ - отображение, определяемое соответствием $\left(b^{\prime}, x\right) \rightarrow b^{\prime}$ Отображение $F: f^{*}(X) \rightarrow X$ И. р. в исходное расслоение, определенное формулой $F\left(b^{\prime}, x\right)=x$, является морфизмом расслоений, накрывающим $f$. Для каждой точки $b^{\prime} \in B$ ограничения

\[
F_{b^{\prime}}:\left(f^{*}(\pi)\right)^{-1}\left(b^{\prime}\right) \rightarrow \pi^{-1}\left(\mathrm{f}\left(\mathrm{b}^{\prime}\right)\right)
\]

являются гомеоморфизмами. Кроме того, для любого расслоения $\eta: Y \rightarrow B^{\prime}$ и морфизма $H: \eta \rightarrow \pi$, накрывающего $f$, существует один и только один $B^{\prime}$-морфизм $K: \eta \rightarrow f^{*}(\pi)$, удовлетворяющий соотнопениям $F K=H$, $f^{*}(\pi) K=\eta$, так что имеет место коммутативная диаграмма:

![](https://cdn.mathpix.com/cropped/2023_07_08_4d4ff348275b8e2a7e3ag-1.jpg?height=261&width=388&top_left_y=1234&top_left_x=131)

Расслоения, индуцированные изоморфными расслоениями, изоморфны, расслоение, индуцированное постоянным отображением, изоморфно тривиальному. Для любого сечения $s$ расслоения $\pi$ отображение $\sigma: B^{\prime} \rightarrow f^{*}(x)$, определенное формулой $\sigma\left(b^{\prime}\right)=\left(b^{\prime}, s f\left(b^{\prime}\right)\right)$,

является сечением И. р. $f^{*}(\pi)$ и удовлетворяет соотношению $F \sigma=s f$. Напр., отображение $\pi: X \rightarrow B$ индуцирует расслоение $\pi^{2}$ с пространством $\pi^{*}(x)$ и базой $X$ - квадрат расслоения $\pi$, оно обладает единственным сечением $s(x)=(x, x)$.

Лuт.: [1] $\Gamma$ о д б и й о н К., Дифференциальная геометрия и аналитическая механика, пер. с франц., М., 1973; [2] С т и н p o Д Н., Топология косых произведений, пер. с англ., пер. с англ., М., 1970. М. И. Войцеховский.

ИНЕРТНОЕ ПРОСТОЕ ЧИСЛО в р а с ІІ и р е н и и $K / \mathbb{Q}$ - такое простое число $p$, для к-рого главный идеал, порожденный $p$, остается простым в $K / \mathbb{Q}$, где $K-$ конечное распирение поля рациональных чисел $\mathbb{Q}$; другими словами, идеал $(p)$ прост в $B$, где $B$ - кольцо целых чисел поля $K$. В этом случае говорят также, что $p \quad$ о с т а е т с я ин е р т н м в распирении $K / \mathbb{Q}$. Аналогично, говорят, что простой идеал $\mathfrak{\mathbb { R }}$ дедекиндова кольца $A$ о с т а е т с я ине р т ны м при расширении $K / k$, где $k$ - поле частных кольца $A$ и $K-$ некоторое конечное распирение $k$, если идеал $\Omega B$, где $B$ - целое замыкание кольца $A$ в $K$, прост.

Если $K / k$ - распирение Галуа с группой Галуа $G$, то для любого идеала $\Re$ кольца $B \subset K$ определена подгруппа $T_{\mathfrak{p}}$ в группе $G_{\mathfrak{p}}$ разложения идеала $\mathfrak{\Re}$, наз. по д г р У П п о й и н е р ци и (см. Критический идеал). Распирение $K^{\tau \Re} / K^{G}$ - это максимальное промежу- точное подрасширение в $K / k$, в к-ром идеал $\Re \cap K^{G}$ остается инертным.

В циклических растирениях полей алгебраич. чисел всегда существует бесконечно много инертных простых идеалов.

![](https://cdn.mathpix.com/cropped/2023_07_08_4d4ff348275b8e2a7e3ag-1.jpg?height=53&width=824&top_left_y=358&top_left_x=1000)
с англ., М., 1947; [3] Алгебраическая теория чисел, пер. с англ. М., 1969 .

ИНЕРЦИАЛЬНАЯ СИСТЕМА ОТСЧЕТА - система отсчета в классической механике и в специальной теории относительности, в к-рой справедлив первый закон Ньютона. Понятие И. с. о.- абстракция, однако в весьма широком классе физич. явлений (в их круг невходит описание сильных гравитационных полей) существуют системы отсчета с высокой точностью, близкие к И. с. о. В том случае, когда в целом И. с. о. не существует (напр., в общей теории относительности), в каждой точке можно построить такую систему отсчета, к-рая в малой окрестности этой точки является приближенно инерциальной. В случае общей теории относительности такие системы отсчета наз. локально гали ле е выми с и с т е м а и о т с ч т а. Существование локально галилеевой системы отсчета означает то, что касательное пространство в данной точке аппроксимирует искривленное пространствовремя.

Всякая система отсчета, к-рая движется относительно И. с. о. прямолинейно и равномерно, является И. с. о. Различные И. с. о. в классич. механике связаны преобразованиями из неоднородной группы Галилея преобразований; в специальной теорпи относітельности - преобразованиями из группы Пуанкаре (см. Лоренца преобразование). Законы классич. механики и законы специальной теории относительности инвариантны относительно, соответственно, неоднородной групшы Галилея и группы Пуанкаре (см. Относительности принцип). Следствием принципов относительности являются различные законы сохранения (энергии, импульса, момента импульса), к-рые имеют место лишь в И. с. о. В специальной теории относительности И. с. о. обычно задаются галилеевой системой координат, в классической механике - декартовой системой координат.

Лuт.: [1] Ф о к В. А., Теория пространства, времени и тяготения, 2 изд., М., 1971. Д. Д. Соколов.

ИНЕРЦИИ ЗАКОН к в а д $\mathrm{p}$ а т и ч н Ы $\mathbf{ф}$ о $\mathrm{p}$ мтеорема, утверждающая, что при любом способе приведения квадратичной формы

\[
\sum_{i, j=1}^{s} a_{i j} x_{i} x_{j}
\]

с действительными коэфффициентами к сумме квадратов

\[
\sum_{i=1}^{s} b_{i} y_{i}^{2}
\]

посредством линейной замены переменных

\[
\left(x_{1}, \ldots, x_{s}\right)=\left(y_{1}, \ldots, y_{s}\right) Q,
\]

где $Q$ - невырожденная матрица с действительными коэфффициентами, число $p$ (соответственно $n$ ) таких индексов $i$, что $b_{i}>0$ (соответственно $b_{i}<0$ ), остается неизменным. В этой классич. форме И. з. установлен Дж. Дж. Сильвестром (J . J. Sylvester). Әто утверждение иногда называют также те о р е м й Й и л bв е с т p a.

В современной форме И. з.- это следующее утверждение о свойствах симметрических билинейных форм над упорядоченными полями. Пусть $E-$ конечномерное векторное пространство над упорядоченным полем $k$, снабженное невырожденной симметрич. билинейной формой $f$. Тогда существует такое целое число $p \geqslant 0$,