имеот горизонтальную касательную. $k$-изоклина уравнения (*) является одновременно решением этого уравнения тогда и только тогда, когда она представляет собой прямую с угловым коэфффициентом $k$.

Приближенное качественное представление о картине поведения пнтегральных кривых уравнения (*) можно составить, если построить И. данного уравнения для достаточно частого набора значений параметра $k$ II отметіть на каждой И. соответствующий наклон интегральных кривых (м е т о д и з о к ли н). Полезно также построить $\infty$-изоклину, определяемую уравнением $1 / f(x, y)=0 ;$ в точках $\infty$-изоклины интегральные кривые уравнения (*) имеют вертикальную касательную. Точки (локального) экстремума решений уравнения (*) могут лежать только на 0-изоклине, а точки перегиба решений - только на линии

\[
\frac{\partial f(x, y)}{\partial x}+f(x, y) \frac{\partial f(x, y)}{\partial y}=0 .
\]

Для уравнения 1-го порядка, не разрешенного относітельно производной

\[
F\left(x, y, y^{\prime}\right)=0
\]

$k$-изоклина определяется как множество

\[
\{(x, y) \mid F(x, y, k)=0\} .
\]

В случае автономной системы 2-го порядка

\[
\dot{x}=f(x, y), \dot{y}=g(x, y)
\]

совокупность точек фазовой плоскости, в к-рых векторы фазовой скорости коллинеарны, есть И. уравнения

\[
\frac{d y}{d x}=\frac{g(x, y)}{j(x, y)} .
\]
$\begin{array}{rrr}\text { Лит.: [1] } & \text { С т е па н о в } & \text { В. В., Курс дифференциальных } \\ \text { уравнений, } 9 \text { изд., М., } 1966 .\end{array}$

ИЗОЛИРОВАННАЯ ОСОБАЯ ТОЧКА д л я э л еме н т а а на лит ич е ск о й фу ункции $f(z)-$ точка $a$ комплексной плоскости $z$, относительно к-рой выполняются условия: 1) этот элемент функции $f(z)$ не допускает аналитического продолжения по какому-либо пути в точку $a ; 2)$ существует такое число $R>0$, что в проколотой окрестности $U=\{z \in \mathbb{C}: 0<|z-a|<R\}$ точки $a$ аналитіч. продолжение элемента $f(z)$ возможно по любому путіг.

Есліг прі аналитич. продолжении $f(z)$ вдоль замкнутого путі, расположенного в $U$ и окружающего $a$, напр. вдоль окружности $|z-a|=\rho, 0<\rho<R$, получается новый әлемент, отличный от исходного, то $a$ наз. ветвления точкой, или И. о. т. м но гознач но го х а р а к т е р а. В противном случае әлемент $f(z)$ определяет однозначную аналитич. функцию в $U$ II $a$ наз. И. о. т. одн о 3 на ч н о го х а р а к т е р а. В проколотой окрестности $U$ II. о. т. а однозначного характера функция $f(z)$ разлагается в Лорана ряд:

\[
f(z)=\sum_{k=-\infty}^{+\infty} c_{k}(z-a)^{k}
\]

с правильной частью $f_{1}(z)=\sum_{k=0}^{+\infty} c_{k}(z-a)^{k}$ и главной частью $f_{2}(z)=\sum_{k=-\infty}^{-1} c_{k}(z-a)^{k}$. Поведение аналитич. функциі $f(z)$ в проколотой окрестности $l$ И. о. т. однозначного характера определяется в основном главной частью ряда Лорана. Если все коэфффициенты главной часті равны нулю, то, полагая $f(a)=c_{0}$, получим однозначную аналітич. функцию в полной окрестности $a$. Әтот случай фактического отсутствия особенності характеризуется также тем, что $f(z)$ ограничена в проколотой окрестности $U$, или тем, что существует конечный предел $\lim _{z \rightarrow \infty} f(z)=c_{0}, z \in U$.

Если среди козфффициентов главной части имеется лишь конечное число отличных от нуля и наименьший номер среди них пмеет $c_{-m} \neq 0$, то $a$ есть полюс по- рядка $m$. Полюс $a$ характеризуется также тем, что

\[
\lim _{z \rightarrow a} f(z)=\infty, z \in U
\]

Наконец, если среди коэффициентов главной части имеется бесконечное множество отличных от нуля, то a- существенно особая точка. В этом случае не существует конечного или бесконечного предела

\[
\lim _{z \rightarrow a} f(z), z \in U
\]

Для бесконечно удаленной И. о. т. $a=\infty$ элемента $f(z)$ проколотая окрестность имеет вид $U=\{z \in \mathbb{C}: r<$ $<|z|<\infty\}$, а ряд Лорана -

\[
f(z)=\sum_{k=-\infty}^{+\infty} c_{k} z^{k}
\]

Здесь правильная часть $f_{1}(z)=\sum_{k=-\infty}^{0} c_{k} z^{k}$, а главная часть $f_{2}(z)=\sum_{k=1}^{+\infty} c_{k} z^{k}$. С этими условиями описанные выше классификация и признаки типов И. о. т. без дальнейших изменений переносятся на случай $a=\infty$ (см. также Bычет). Следует отметить, что элементы различных ветвей полной аналитической бункции $f(z)$ в одной и той же точке $a \in \mathbb{C}$ могут иметь особенности совершенно различных типов.

Голоморфные функции $f(z)$ многих комплексных переменных,$z=\left(z_{1}, z_{2}, \ldots, z_{n}\right)$, при $n \geqslant 2$ не могут иметь И. о. т. При $n \geqslant 2$ особыө точкІ составляют бесконечныө множества особенностей.

Лит.: [1] М а р к у ш е в и ч А. И., Теория аналитических Функций, 2 изд., т. 1, M., 1967; [2] III а б а т Б. В., Введение

ИЗОЛИРОВАННАЯ ПОДГРУППА - подгрупиа $A$ групшы $G$ такая, что из $g^{n} \in A, g^{n} \neq 1$, следует $g \in A$; другими словами, если уравнение $x^{n}=a$ (где $\left.1 \neq a \in A\right)$ разрешимо в $G$, то его решение принадлежит $A$. Подгруппа $A$ наз. с и л ь н о из о ли р о в а н н о й, если из $a \in A$ следует, что централизатор элемента $a$ во всей группе лежит в подгруппе $A$. И з о л я т о р о м м н о ж е с т в а $M$ элементов группы наз. минимальная И. п., содержащая $M$.

В $R$-группах (т. е. арупnax $c$ однозначны.м извлечением корня) понятие И. П. соответствует понятию сервантной подаруппы абелевой группы. Пересечение изолированных подгрупп в $R$-группе - И. ш. Нормальный делитель $H R$-группы $G$ изолирован тогда и только тогда, когда факторгруппа $G / H$ является группой без кручения. Центр $R$-группы изолирован.

В отличие от общей теории групп, в теории упорядоченных групп И. П. называют иногда выnуклые подapynnbl. O. А. Иванова.

ИЗОЛИРОВАННАЯ ТОЧКА подпространства $A$ топологического пространства $X$ - такая точка $a \in A$, что пересечение нек-рой ее окрестности с $A$ состоит из единственной точки $a$. A. A. малъчев.

ИЗОЛЬ - рекурсивной эквивалентности тип изолированного (т. е. конечного или иммунного) множества натуральных чисел. Множество всех И. континуально и является полукольцом относительно операций сложения и умножения, определяемых для произвольных типов рекурсівной эквивалентности. Это полукольцо наз. арифметıкой И. Последняя обладает рядом свойств арифметики натуральных чисел, в частности в ней выполнены все уншверсальные хорновские формулы, элементарные подформулы к-рых представляют собой равенство так наз. комбинаторных функций. Примером такой. формулы является закон сокращения: $X+Z=$ $=Y+Z \Rightarrow X=Y$. И. рассматриваются как рекурсивные аналоги мощностей к о н е ч н х п о Д е д е к и нд у м н о е с т в, т. е. множеств, не равномощных никакому своему собственному подмножеству.