- так наз. ин т е г р а л в е р о т ности с а. Для случайной величины $X$, имеющей нормальное распределение с математич. ожиданием 0 и дисперсией

![](https://cdn.mathpix.com/cropped/2023_07_08_10c45a2f388c504976acg-1.jpg?height=330&width=464&top_left_y=277&top_left_x=115)
$\sigma^{2}$, вероятность неравенства $|X| \leqslant t \quad$ равна $\operatorname{erf}(t / \sqrt{2})$. Для действительного $x$ И. в. принимает действительные значения, в частности $\operatorname{erf}(0)=0, \lim _{x \rightarrow+\infty} \operatorname{erf}(x)=1$

График И. в. и его производной см. на рис. Рассматриваемый и как функция комплексного переменного $z$, И. в. $\operatorname{erf}(z)$ есть целая функция от $z$.

Асимптотич. представление при больших $z, \operatorname{Re} z>0$ :

$1-\operatorname{erf}(z) \sim \frac{e^{-z^{2}}}{\sqrt{\bar{\pi} z}}\left(1+\sum_{k=1}^{\infty}(-1)^{k} \frac{1 \cdot 3 \cdot \ldots \cdot(2 k-1)}{2 \cdot k} \frac{1}{z^{2 k}}\right)$.

В окрестности $z=0$ И. в. представляется в виде ряда $\operatorname{erf}(z)=\frac{2}{\sqrt{\pi}}\left(z-\frac{z^{3}}{1 ! 3}+\ldots+\frac{(-1)^{k}}{k !(2 k+1)} z^{2 k+1}+\ldots\right)$.

С Френеля интегралами $C(z)$ и $S(z)$ И. в. связан соотнопениями:

\[
\begin{aligned}
& \frac{1+i}{2} \operatorname{erf}\left(\frac{1-i}{\sqrt{2}} z\right)=C(z)+i S(z), \\
& \frac{1-i}{2} \operatorname{erf}\left(\frac{1+i}{\sqrt{2}} z\right)=C(z)-i S(z) .
\end{aligned}
\]

Производная И. в.:

\[
[\operatorname{erf}(z)]^{\prime}=\frac{2}{V \bar{\pi}} e^{-z^{2}} .
\]

Иногда используются следующие обозначения:

\[
\Theta(x)=H(x)=\Phi(x)=\operatorname{erf}(x),
\]

\[
\operatorname{Erf}(x)=\frac{V \bar{\pi}}{2} \operatorname{erf}(x)
\]

$\operatorname{Erfi}(x)=-i \frac{\sqrt{\pi}}{2} \operatorname{erf}(i x)=\int_{0}^{x} e^{t^{2}} d t$,

$\operatorname{Erfc}(x)=\frac{\sqrt{\pi}}{2}-\operatorname{Erf} x=\int_{x}^{\infty} e^{-t^{2}} d t$,

\[
\alpha(x)=\frac{2}{V \bar{\pi}} \int_{-\infty}^{x} e^{-t^{2 / 2}} d t-1=\frac{2}{\pi} \operatorname{Erf}\left(\frac{x}{V \overline{2}}\right) .
\]

Лum.: [1] Б е й т м е н Г., Э р д е й и А., Высшие трансцендентные Функции. Функции Бесселя, Функции параболического цилиндра, ортогональные многочлены, пер. с англ., 2 изд., M., 1974; [2] Я н к е E., Э м д е Ф., Л ё ші Ф., Специальные функции. Формулы, графики, таблицы, пер. с нем., 2 изд., М., кции, пер. с нем., м., 1963; [4] Л е б е д е в Н. Н., Специальные функции и их приложения, 2 изд. М. 1963. А. Б. Иванов.

ИНТЕГРАЛ ДИФФЕРЕНЦИАЛЬНОГО УРАВНЕНИЯ - решение дифференциального уравнения. И. д. у. наз. преимущественно соотнопение вида $\Phi(x, y)=0$, определяющее решение $y$ обыкновенного диффференциального уравнения

\[
F\left(x, y, y^{\prime}, \ldots, y^{(n)}\right)=0
\]

как неявную функцию независимой переменной $x$. В этом случае говорят также о ч а с т н о м и н т е гр а л е в противоположность о б щ е м у и т т г р ал у уравнения (1), т. е. соотношению

\[
\Phi\left(x, y, C_{1}, \ldots, C_{n}\right)=0,
\]

из к-рого при соответствующем выборе постоянных $C_{1}, \ldots, C_{n}$ получается любая интегральная кривая уравнения (1), проходящая в рассматриваемой области $G$ плоскости $(x, y)$. Если из соотнопения (2) и из $n$ соот- ношений, получающихся из него последовательным дифференцированием по $x$ (причем $y$ рассматривается как функция $x$ ), исключить произвольные постоянные $C_{1}, \ldots, C_{n}$, то в результате приходят к уравнению (1). Возникающее в процессе интегрирования уравнения (1) соотношение вида

\[
\Phi\left(x, y, y^{\prime}, \ldots, y^{(k)}, C_{1}, \ldots, C_{n-k}\right)=0,
\]

содержащее производные до $k$-го порядка, $1 \leqslant k<n$, и $n-k$ произвольных постоянных, иногда наз. п $\mathrm{p}$ ом е ж у т о ч н ы м и н т е г р а л о м уравнения (1). Знание промежуточного интеграла (3) сводит решение уравнения (1) порядка $n$ к решению уравнения (3) порядка $k$. Если соотношение (3) содержит лишь одну произвольную постоянную, т. е. $k=n-1$, то оно наз. пе р в ы м и н те г р а л о м уравнения (1). Это уравнение имеет ровно $n$ независимых первых интегралов; знание $n$ таких интегралов позволяет получить общее решение уравнения (1) путем исключения из них величин $y^{\prime}, \ldots, y^{(n-1)}$

Если рассматривается система обыкновенных дифференциальных уравнений

\[
\frac{d x_{i}}{d t}=f_{i}\left(t, x_{1}, \ldots, x_{n}\right), \quad i=1, \ldots, n,
\]

то под ее общим интегралом имеют в виду совокупность соотнопений

\[
\Phi_{i}\left(t, x_{1}, \ldots, x_{n}\right)=C_{i}, \quad i=1, \ldots, n,
\]

где $C_{i}$ - произвольные постоянные, в неявном виде описывающую все решения системы (4) в нек-рой области $G$ пространства $\left(t, x_{1}, \ldots, x_{n}\right)$. Каждое из соотношений (5) в отдельности наз. первым интегралом системы (4). Чаще под пе р вым и н те г р а лом системы (4) понимают функцию $u\left(t, x_{1}, \ldots, x_{n}\right)$, обладающую тем свойством, что она принимает постоянное значение вдоль любого решіения системы (4) в области $G$. Система (4) имеет ровно $n$ независимых первых интегралов, знание к-рых дает возможность найти общее решение без интегрирования системы; знание $k$ независимых первых интегралов позволяет свести решение системы (4) порядка $n$ к решению системы порядка $n-k$. Гладкая функция $u\left(t, x_{1}, \ldots, x_{n}\right)$ является первым интегралом системы (4) с гладкой правой частью тогда и только тогда, когда она удовлетворяет уравнению

\[
\frac{\partial u}{\partial t}+\sum_{i=1}^{n} f_{i}\left(t, x_{1}, \ldots, x_{n}\right) \frac{\partial u}{\partial x_{i}}=0 .
\]

Аналогичная терминология иногда употребляется в теории диффференциальных уравнений с частными производными 1-го порядка. Так, под И. д. у.

\[
F\left(x, y, z, \frac{\partial z}{\partial x}, \frac{\partial z}{\partial y}\right)=0,
\]

или под его ч а с т ны м и н т е г р а л о м, понимают решение этого уравнения (интегральную поверхность). П о л ны м ин т е г р а л о м уравнения (6) наз. семейство решений $\Phi(x, y, z, a, b)=0$, зависящее от двух произвольных постоянных. О б щ и й и н т е гр а л уравнения (6) - соотношение, содержащее одну произвольную функцию и при каждом выборе этой функции дающее решение уравнения.

Лит.: [1] С т е П а н о в В. В., Курс дифференциальных
уравнений, 8 изд., М., 1959.

ИНТЕГРАЛ ПО ТРАЕКТОРИЯМ, к о н т и н У а л ьны й ин т е г р а л, фун цци оналы ны й и н т е г р а л,- интеграл, областью интегрирования к-рого служит то или иное функциональное пространство. Чаще всего И. по т. определяется как обычный интеграл Лебега от функционала, заданного на пространстве функций (возможно, обобщенных) по нек-рой мере (быть может, комплексной) в этом пространстве.