последняя в случае $n=2$ дает формулу Дирихле для числа классов.

Формулы, аналогичные (3), имеют место и для неопределенных К. ф. и форм с целыми алгебраич. коэфффициентами (см. [17], [18]).

Приложение теории модулярных форм к исследованию мультипликативных свойств количества представлений чисел положительными К. ф. с четным числом переменных было дано Э. Хекке (E. Hecke, [10]). Теория модулярных форм позволяет получать формулы для $\boldsymbol{R}(q, b)$ (см. обзор [5]).

К вопросу о представлении чисел К. ф. от четырех и более переменных применяется круговой метод (см. [4]). Если $q$ - положительно определенная К. ф. над $\mathbb{Z}$, то применение кругового метода приводит для $n \geqslant 4$ к асимптотич. формуле

\[
\boldsymbol{R}(q, b)=\frac{\pi^{n / 2} b^{n / 2-1}}{\Gamma\left(\frac{n}{2}\right) d(q)} H(q, b)+O\left(b^{\frac{n}{4}-\frac{1}{4}+\varepsilon}\right) .
\]

Подобные асимптотич. формулы могут быть получены круговым методом и для неопределенных К. ф. при $n \geqslant$ $\geqslant 4$.

Для исследования $\boldsymbol{R}(q, b)$ в случае $n=3$ применяется дискретный әргодический метод Линника (см. [3], [4]). Он заключается в том, что на нек-ром множестве представлений чисел тернарными К. ф. устраивается эргодический поток представлений, управляемый оператором, связанным с задачей представления чисел кватернарными К. Ф. Эргодический метод приводит (при выполнении необходимых условий) к оценке типа

\[
\boldsymbol{R}(q, b)>\operatorname{ch}(-\Delta b), \quad c=c(q)>0
\]

в ряде случаев получены и асимптотич. формулы.

Для исследования таких вопросов теории К. ф., как теория приведения, автоморфизмы, арифметич. минимумы К. ф., III. Эрмитом (Ch. Hermite) был развит метод непрерывных параметров, превратившийся затем в обширный раздел теории К. ф.- г е о м е т р и ч е с к у ю т е о р и ю К. ф., или г е о ме т р и ю К. ф. (к-рую можно рассматривать и как часть Геометрии чисел). Идея метода состоит в следующем. Заданной $n$-мерной точечной решетке $\Lambda$ ставится в соответствие та или иная арифметич. величина $a=a(\Lambda)$ и рассматривается поведение функции $a(\Lambda)$ при малых изменениях параметров решетки $\Lambda$. Характерной чертой геометрии К. Ф. является систематич. использование $n(n+1) / 2$-мерного пространства коэфффициентов (параметров), в к-ром решетка $\Lambda$ изображается точкой. Пусть

\[
f=\sum_{i, j=1}^{n} a_{i j} x_{i} x_{j}
\]

— К. ф. с действительными коэфффициентами $a_{i j}=a_{j i}$ $(i, j=1, \ldots, n)$. Форме $f$ ставится в соответствие точка $\tilde{f}=\left(a_{11}, \ldots, a_{n n}, a_{12}, \ldots, a_{n-1}, n\right)$ в $N$-мерном евклидовом пространстве. $N=n(n+1) / 2$, называемом п р о с тр а н с т в о м к о э ф ф и ц и е н т о в. Положительно определенным формам $f$ при этом отвечает открытый выпуклый конус $\mathfrak{F}$ с вершиной в начале координат, называемый к о н у с о м п о ло ж и т е ль н о с т и. Рeшетке $\Lambda$ соотносится класс эквивалентных $n$-арных положительно определенных К. ф.; при базисе $\left[\bar{a}_{1}, \ldots\right.$, $\left.\bar{a}_{n}\right]$ решетки $\Lambda$ ей ставится в соответствие форма

\[
f=\sum_{i, j=1}^{n}\left(\bar{a}_{i} \bar{a}_{j}\right) x_{i} x_{j}
\]

Тем самым решетке $\Lambda$ соответствует бесконечное дискретное множество точек конуса положительности $\mathfrak{B}$. Если выбрать точную область приведения $\mathfrak{F} \subset \mathfrak{B}$ положительно определенных К. ф., то каждой решетке будет взаимно однозначно соответствовать точка $\tilde{f} \in \mathcal{F}$ пространства коэфффициентов. Малым изменениям параметров решетки $\Lambda$ отвечают малые изменения точки $\tilde{f}$. Геометрическая теория К. ф. распадается на ряд достаточно самостоятельных теорий, связанных единым методом исследования. Фундаментом ее является теория приведения положительных $К$. ф., к-рая, изучая области приведения $\mathfrak{F}$, решает проблему эквивалентности положительных К. Ф.- одну из центральных задач арифметич. теории К. Ф. (см. Квадратичных борм приведение).

Существенную роль играет теория Вороного типов решетки. Она имеет важные приложения в теории параллелоэдров. Теория типов получила применение в репіении задач об әкономнейшем решеточном покрытии $n-$ мерного пространства шарами.

Другой традиционный раздел геометрич. теории К. ф.- теория совершенных форм, также созданная Г. Ф. Вороным. Әта теория позволила решить Әрмита проблему арифметич. минимумов положительных К. ф., равнозначную задаче о плотнейшей репетчатой упаковке паров в $n$-мерном пространстве. Задача о плотнейшей решетчатой упакоове шаров и задача об экономнейшем решетчатом покрытии шарами - наиболее известные примеры экстремальных задач, составляющих значительную часть К. Ф. геометрии.

К геометрической теории К. ф. можно также отнести нек-рые обобщения алгоритма цепных дробей, напр. алгоритм Вороного вычисления единиц кубического поля, теорию фундаментальных областей автоморфизмов неопределенных К. ф.

.Iит.: [1] Б о р е в и ч 3. И., ІІІ а ф а р е в и ч И. Р., Теория чисел, 2 изд., М., 1972; [2] ' Д е л о н е Б. Н., "Успехи матем. наук», 1937 , в. 3, с. 16-62; 1938, в. 4, с. 102-64; [3] Л и н н и к Ю. В., Эргодические свойства алгебраических полей, Ј1,, 1967; [4] М а лы ыш е в А. В., О представлении целых [5] е г о ж е, в кн.: Актуальные проблемы аналитической теории чисел, Минск, 1974, с. 119-37; [6] С e p p Ж. - П., Kypc

![](https://cdn.mathpix.com/cropped/2023_07_08_9b601c195a6aca2d899eg-1.jpg?height=45&width=826&top_left_y=1203&top_left_x=992)
Quadratische Formen und orthogonale Gruppen, 2 Aufl., B., 1974; [9] H a s s e H., "J. reine und angew. Math.", 1923, Bd 152, S. $129-48,205-24 ; 1924$, Bd 153, S. 12-43, 76-93, 113-30, $158-62,186-207 ;[10] \quad \mathrm{H} \mathrm{e} \mathrm{c} \mathrm{k} \mathrm{e} \mathrm{E.,} \mathrm{Mathematische} \mathrm{Werke,}$ Gött. 1959; [11] J on es B. W., The arithmatic theory of
quadratic forms, N. Y., $1950 ;[12]$ L a m T. Y., The algebraic quadratic forms, N. Y., 1950;[12] L a m T. Y ., The algebraic Gesammelte Abhandlungen, Bd $1-2$, Lpz. - B., $1911 ;$ [14] O'M e a r a O. T., Introduction to quadratic forms, B., 1963; [15] P a l l G., "Canad. J. Math.", 1949 , v. 1, p. 344-64; [16 P f i s t e r A., "Arch. Math.", 1965, Bd 16, S. 363-70; [17] forms, 3 ed., Gött., 1963; [18] e $\Gamma_{0} \mathrm{~T}_{\mathrm{e}} \mathrm{e}$ Gesammelte Abhan-

![](https://cdn.mathpix.com/cropped/2023_07_08_9b601c195a6aca2d899eg-1.jpg?height=47&width=834&top_left_y=1515&top_left_x=987)
collected mathematical papers, v. 1-2, Oxf., 1894; [20] W a ts o n G. L., Integral quadratic forms, Camb., 1960; [21] Ф о м е н к о О. М., Итоги науки и техники. Алгебра. Тополо-

КВАДРАТИЧНОЕ ОТКЛОНЕНИЕ, к в а д р а т И чно е уклонени е, с танда т тное от к лон ен и е величин $x_{1}, x_{2}, \ldots, x_{n}$ от $a$ - квадратный корень из выражения

\[
\frac{\left(x_{1}-a\right)^{2}+\left(x_{2}-a\right)^{2}+\ldots+\left(x_{n}-a\right)^{2}}{n} \text {. }
\]

Наименьшее значение К. о. имеет при $a=\bar{x}$, где $\bar{x}-$ среднее арифметическое величин $x_{1}, x_{2}, \ldots, x_{n}$ :

\[
\bar{x}=\frac{x_{1}+x_{2}+\ldots+x_{n}}{n} .
\]

В этом случае К. о. может служить мерой рассеяния системы величин $x_{1}, x_{2}, \ldots, x_{n}$. Употребляют также более общее понятие в з в е ші е н о г о К. $о$.

\[
\sqrt{\left[p_{1}\left(x_{1}-a\right)^{2}+\ldots+p_{n}\left(x_{n}-a\right)^{2}\right] /\left(p_{1}+\ldots+p_{n}\right)},
\]

числа $p_{1}, \ldots, p_{n}$ наз. при этом в е с а м и, соответствующими величинам $x_{1}, \ldots, x_{n}$. Взвешенное достигает наименьшего значения при $a$, равном взвешенному среднему:

\[
\left(p_{1} x_{1}+\ldots+p_{n} x_{n}\right) /\left(p_{1}+\ldots+p_{n}\right) \text {. }
\]