шим вектором, причем соответствующие ему числовые отметки - неотрицательные целые числа; два конечномерных неприводимых представления эквивалентны тогда и только тогда, когда соответствующие старшие веса совпадают и любой набор неотрицательных целых чисел является набором числовых отметок старшего веса нек-рого конечномерного комплексного неприводимого представления.

Jum.: [1] C a r t a n E., "Bull. Sci. math.", 1925, t. 49, p. 130-52; [2] Д ж е к о б с о н Н., Алгебры Ји, пер. с англ., с франц., М., 1962; [4] Ж е л о б е н ко П. П., Компактные группы Ји и их представления, М., 1970 ; [5] D i x m i e r J., Algèbres enveloppantes, P., 1974; [6] Семинар по алгебраическим группам, пер. с англ., М., $1973 . \quad$ В. Л. Попов.

2) К. т. в т е о р й ф ункци й мн о гих ком п лексных п е р е ме н ных-так наз. теоремы А и В о когерентных аналитич. пучках на многообразиях Штейна, впервые доказанные А. Картаном (H. Cartan, [1]). Пусть 6 - пучок ростков голоморфных функций на комплексном многообразии $X$. Пучок $6-$ модулей $\mathscr{\varphi}$ на $X$ наз. к о г е р е н т н ы м а н а л и тич еским, если в окрестности каждой точки $x \in X$ существует точная последовательность пучков

\[
\hat{G}^{p} \longrightarrow G^{q} \longrightarrow \mathscr{S} \longrightarrow 0
\]

для нек-рых натуральных $p, q$. Такими являются, например, все локально конечно порожденные подпучки в $6^{p}$.

Те о р е м а А. Пусть $\mathscr{S}-$ когерентный аналитич. пучок на многообразии Штейна $X$. Тогда для каждой точки $x \in X$ найдется конечное число глобальных сечений $s_{1}, \ldots, s_{N}$ пучка $\mathscr{S}$ таких, что любой әлемент $s$ слоя $\mathscr{S}_{x}$ представляется в виде

\[
s=h_{1}\left(s_{1}\right)_{x}+\ldots+h_{N}\left(s_{N}\right)_{x},
\]

где все $h_{j} \in G_{x}$. (Другими словами, пучок $\mathscr{S}$ локально конечно порожден над 6 своими глобальными сечениями.)

Т е о р е м а В. Пусть $\mathscr{S}-$ когерентный аналитич. пучок на многообразии IIтейна $X$. Тогда все группы когомологий порядка $p \geqslant 1$ многообразия $X$ с коэффициентами в пучке $\mathscr{S}$ тривиальны:

\[
H^{p}(X, \mathscr{S})=0 \quad \text { при } \quad p \geqslant 1 .
\]

К. т. имеют много приложений. Из теоремы А получаются различные теоремы существования глобальных аналитич. объектов на многообразиях Штейна. Основным следствием теоремы В является разрешимость $\bar{\partial}$ проблемы: на многообразии Шітейна уравнение $\bar{\partial} f=g$ с условием согласования $\bar{\partial} g=0$ всегда разрешимо. Схема применения теоремы В такова: если

\[
0 \longrightarrow \mathscr{S} \longrightarrow F \longrightarrow G \longrightarrow 0
\]

- точная последовательность пучков на $X$, то последовательность

$\ldots \longrightarrow H^{p}(X, \mathscr{S}) \longrightarrow H^{p}(X, F) \stackrel{\varphi_{p}}{\longrightarrow} H^{p}(X, G) \longrightarrow$ $\longrightarrow H^{p+1}(X, \mathscr{S}) \longrightarrow \ldots$

тоже точна. Если $X-$ многообразие Штейна, то $H^{p}(X, \mathscr{S})=0, \quad p \geqslant 1$,

и, значит, $\varphi_{0}$ есть отображение на, а $\varphi_{p}, p \geqslant 1$,- изоморфизмы.

Теорема В точна: если на комплексном многообразии $X$ группы $H^{\mathbf{1}}(X, \mathscr{S})=0$ для любого когерентного аналитич. пучка $\mathscr{S}$, то $X$ - многообразие Шітейна. Теоремы А и В вместе с их многочисленными следствиями составляют т. наз. т е о р и ю $\mathrm{O}$ к а- К а многообразия шимость на многообразиях ІІейна всех классич. проблем многомерного комплексного анализа - проблема Кузена, Леви, Пуанкаре и др. Теоремы А и В и их следствия допускают дословное обобщение на пространства Штейна.

Лит.: [1] К а р т а н А., в кн.: Расслоенные пространства и их приложения, M., 1958, с. 352-62; [2] Г а н н и н г P., переменных, пер. с англ., М., 1969; [3] Х ё р м а н д е р Л., Введение в теорию функций нескольких комплексных переменных, пер. с англ., М., 1968 .

КАРТАНА - ВЕИЛЯ БАЗИС к о н е ч н о м е р н о й полу простой комплексной ал ге бры Ли $\mathfrak{g}$ - базис $\mathfrak{g}$, составленный из элементов Картана подалгебры алгебры я и корневых векторов $X_{\alpha}, \alpha \in \Delta$, где $\Delta$ - система всех ненулевых корней алгебры $\mathfrak{g}$ относительно $\tau$. К.- В. б. выбирается неоднозначно. Корень $\alpha(h), h \in \tau$, как линейная форма над $\tau$, отождествляется с вектором $h_{\alpha}^{\prime} \in \tau$, для которого $\alpha(h)=\left(h_{\alpha}^{\prime}, h\right)$, где $(x, y)$ - Киллинга борма в алгебре g. При этом

\[
\left[h, X_{\alpha}\right]=\left(h_{\alpha}^{\prime}, h\right) X_{\alpha}
\]

для всякого $h \in \tau$. Если $\alpha \in \Delta$, то - $\alpha \in \Delta$, причем можно выбрать $X_{\alpha}$ так, чтобы выполнялось равенство $\left[X_{\alpha}, X_{-\alpha}\right]=h_{\alpha}^{\prime}$. Если $\alpha+\beta \in \Delta$, то

\[
\left[X_{\alpha}, X_{\beta}\right]=N_{\alpha \beta} X_{\alpha+\beta},
\]

где $N_{\alpha \beta \neq 0}$. Если $\alpha, \beta, \gamma \in \Delta, \alpha+\beta+\gamma=0$, то $N_{\alpha \beta}=$ $\stackrel{=}{=} N_{\rho} \stackrel{2}{=} N_{\gamma \alpha}$. Существует нормировка векторов $X_{\alpha}$, при которой $N_{\alpha \beta}=-N_{-\alpha,-\beta}$, причем числа $N_{\alpha \beta}$ получаются рациональными. Существует нормировка векторов $X_{\alpha}$, при которой все $N_{\alpha \beta}$ - целые (см. IIIевалле әруппа). Определение К.- В. б. (введенное Г. Вейлем в [1]), а также все сказанное выше о векторах $X_{\alpha}, h_{\alpha}^{\prime}$ и числах $N_{\alpha \beta}$ дословно переносится на случай произвольной конечномерной полупростой расщепляемой алгебры Ли над полем нулевой характеристики и ее корневого разложения относительно расщепляющей подалгебры Картана.

[2] Jum.: L1] W e y l H., "Math. Z.", 1924, Bd 23, S. 271-304; [2] Теория алгебр Ли. Тополог ия групп Ли, пер. с франц., М., Терия алгебр Ли. Топология групп Ли, пер. с франц.,
д. П. भелобенко.
1962.

КАРТЕРА ПОДГРУППА - максимальная нильпотентная подгруппа группы, совпадающая со своим нормализатором. Введена Р. Картером [1]. Любая конечная разрешимая группа $G$ обладает К. п., причем все К. П. в группе $G$ сопряжены (т е о р е м а $K$ а р т е p a).

Jum.: [1] C a r t e r R. W., "Math. Z.", 1961, Bd 75, № 2, S. $136-39$; [2] Итоги науки. Алгебра. 1964, м., 1966, с. 23-24.
H. Н. Вилълис.

КАРТОГРАФИИ МАТЕМАТИЧЕСКИЕ ЗАДАЧИ задачи, возникающие при построении математич. основы географических и специальных карт, именно, при разработке теории картограбических проекций, исследовании их свойств, преобразований, методов изысканий и др. Поверхность Земли при этом принимают либо за сфферу, либо за эллипсоид вращения.

Основным объектом изучения в математич. картографии является картографич. проекция: отображение на плоскости всей поверхности земного эллипсоида (шара) или какой-либо ее части:

\[
x=f_{1}(u, v), y=f_{2}(u, v),
\]

где $u$ - широта, $v$ - долгота точкі $P \in \Delta(\Delta-$ односвязная область эллипсоида); $x, y$ определяют на плоскости точку $Q-$ изображение точки $P, Q \in D$, $D$ - область изображения $\Delta$. Функции $f_{1}$ и $f_{2}$ удовлетворяют следующим условиям: они однозначные, дважды непрерывно дифференцируемые, имеют якобиан $h=$ $=\partial(x, y) / \partial(u, v) \neq 0$ (для сохраняющих ориентацию отображений, используемых в геодезии и картографии, $h>0)$. Больпинство фактов математич. картографий относится не только к отображениям әллипсоида на плоскость, но и к отображениям произвольных поверх-