непрерывно из заданного функционального пространства $E$ в нек-рое другое функциональное пространство $E_{1}$. В этом случае сам оператор (2) наз. и н т е г р а л ьным о пе раторов Фред гольм а из $E$ в $E_{1}$.

Линейные И. о. часто рассматриваются в функциональных пространствах: $C(D)$-непрерывных на ограниченном замкнутом множестве $D$ функций и $L_{p}(D)-$ суммируемых на $D$ со степенью $p$ функций. В этом случае оператор (2)-оператор Фредгольма в $C(D)$ (т. е. из $C(D)$ в $C(D)$ ), если $K$ непрерывно на $D \times D$ (такое ядро наз. н е п р е р ы в ны м). Он является оператором Фредгольма в $L_{2}(D)\left(\right.$ из $L_{2}(D)$ в $\left.L_{2}(D)\right)$, если ядро $K$ измеримо на $D \times D$ и

\[
\int_{D} \int_{D}|K(t, \tau)|^{2} d t d \tau<\infty .
\]

Такое ядро наз. $L_{2}$-я д р о м.

С о п р я ж е н ны й о п е р а т о р к оператору (2) в комплексном функциональном пространстве $L_{2}(D)$ с ядром, удовлетворяющим условию (3), есть И. о.

\[
A^{*} \varphi(t)=\int_{D} \overline{K(\tau, t)} \varphi(\tau) d \tau, \quad t \in D,
\]

где черта означает переход к комплексно сопряженному значению. Если ядро $K$ эрмитово (симметрично) (то есть $\overline{K(\tau, t})=K(t, \tau)$ ), то соответствующий оператор Фредгольма (2) совпадает со своим сопряженным (4). Операторы, обладающие этим свойством, наз. с а м ос о п р я же н ны м и. Оператор Фредгольма с симметричным ядром наз. и н те г р а л ь ны м о п е р атором Гильберта-Ші и т та.

Пусть $|t-\tau|$ обозначает расстояние между точками $t$ и $\tau$-мерного евклидова пространства, $B(t, \tau)$ - ограниченная измеримая функция на $D \times D$, тогда ядро вида

\[
K(t, \tau)=\frac{B(t, \tau)}{|t-\tau|^{m}}, \quad 0<m<n,
\]

наз. я д ром ти па потенци ал а, а И. о. (2) с таким ядром - И. о. т и п а по т е нц и а л а; ядро (5) наз. также п о л я р н ы м я д р о м, или яд р о м с о с л а бой о с о бе н н ост ь ю, а соответствующий оператор (2) -И. о. с о с л а б о й о с о б е н н ос т ь ю.

Если функция $B(t, \tau)$ непрерывна на $D \times D$, то И. о. со слабой особенностью вполне непрерывен в пространстве $C(D)$, а если $B(t, \tau)$ - измеримая ограниченная функция на $D \times D$, то он вполне непрерывен в пространстве $L_{2}(D)$.

Если ядро $K$ и $m$-мерное множество $D$ таковы, что интеграл (2) не существует в смысле Лебега, но существует в смысле главного значения по Коши, то он наз. m-ме рным сингеля риы м инте г рал о м. Оператор, к-рый им порождается, наз. $m$-м е рным с ингуля я ным И. о., или о дноме рны м (при $m=1)$ и м но го ме р ны м (при $m>1)$ с ин гуля я ны м И. о.

Если линия $D$ лежит на плоскости комплексного переменного $t$, то равенство

\[
A \varphi(t)=\int_{D} \frac{\varphi(\tau)}{\tau-t} d \tau, \quad t \in D,
\]

где интеграл понимается в смысле главного значения по Коши, порождает непрерывный И. о. $\varphi \rightarrow A \varphi$ в пространстве функций, удовлетворяющих условию Гёльдера, если $D$ - простая замкнутая гладкая линия; и в пространстве $L_{p}(D), 1<p<\infty$, если $D$ - ляпуновская линия. Оператор (6) наз. с и н г у л я р ны м о п е р ат о $\mathrm{p}$ о м K о пा и.

Пусть на действительной оси заданы две измеримые по Лебегу функции $\varphi$ и $g$. Если для почти всех $t \in]-\infty, \infty[$ существует интеграл

\[
\int_{-\infty}^{\infty}|\varphi(\tau)||g(\tau-t)| d \tau
\]

то можно огределить функцию

\[
(g * \varphi)(t)=\int_{-\infty}^{\infty} g(\tau-t) \varphi(\tau) d \tau,
\]

которая наз. с в е р т к о й $g$ и $\varphi$. Если зафиксировать Функцию $g$, то интеграл (7) определяет оператор

\[
T \varphi(t)=(g * \varphi)(t),
\]

который наз. И. о. (или и н т е г р а л ь ны м п р еоб ра зо в а н е м) с ве е тк и с ядром g. Если $g \in L_{r}(-\infty, \infty), 1 \leqslant p, q, r \leqslant \infty$ и $\frac{1}{p}-\frac{1}{q}=\frac{1}{r}-1$, то оператор (8) непрерывен из $L_{q}(-\infty, \infty)$ в $L_{p}(-\infty, \infty)$. При соответствующих предположениях И. о. свертки применяется как на полупрямой, так и на конечном отрезке.

Кроме указанных выше И. о., исследованы конкретные классы И. о., напр. интегральные преобразования Фурье, Лапласа, Бесселя, Меллина, Гильберта и др.

Л. вочная матем. б-ка); [3] К р а с н о с е ль с к и й м. А. и п р. Интегральные операторы в пространствах суммируемых функций, М., 1966; [4] Д и т к и н В. А., П р у д н и к о в А. П., Интегральные преобразования и операционное исчисление, M., 1961 (Справочная матем. б-ка); [5] м у с х л л ш в и ли
Н. И., Сингуляные интегральные уравнения..., 3 изд., H. И., Сингулярные интегральные уравнения..., 3 изд.,
М., $1968 ; \quad$ [6] М и х и н С. Г., Многомерные сингулярные интегралы и интегральные уравнения, М., 1962; [7] Т и т чм а p шI Э. Ч., Введение в теорию интегралов Фурье, пер. с англ., М.- Ј., 1948, [8] Э д в а р д с Р., Функциональный анализ. Теория и приложения, пер. с англ., М., 1969.

ИНТЕГРАЛЬНЫЙ СИНУС - специальная функция, определяемая для действительного $x>0$ равенством

\[
\mathrm{Si}(x)=\int_{0}^{x} \frac{\sin t}{t} d t=\frac{\pi}{2}-\int_{x}^{\infty} \frac{\sin t}{t} d t .
\]

График И. с. см. на рис. при ст. Интегральный косинус. Иногда используют обозначение

\[
\operatorname{si}(x)=-\int_{x}^{\infty} \frac{\sin t}{t} d t \equiv \operatorname{Si}(x)-\frac{\pi}{2} .
\]

Частные значения:

\[
\operatorname{Si}(0)=0, \quad \operatorname{Si}(\infty)=\frac{\pi}{2}, \quad \text { si }(\infty)=0 .
\]

Основные соотношения:

$\operatorname{Si}(-x)=-\operatorname{Si}(x) ; \quad$ si $(x)+\operatorname{si}(-x)=-\pi ;$

$\int_{0}^{\infty} \sin ^{2}(t) d t=\frac{\pi}{2} ; \quad \int_{0}^{\infty} e^{-p t} \operatorname{si}(q t) d t=-\frac{1}{p} \operatorname{arctg} \frac{p}{q}$; $\int_{0}^{\infty} \sin t \operatorname{si}(t) d t=-\frac{\pi}{4} ; \quad \int_{0}^{\infty} \operatorname{Ci}(t) \operatorname{si}(t) d t=-\ln 2$, где $\operatorname{Ci}(t)$ - интегральныц̆ косинус. При малых $x$ : $\mathrm{Si}(x) \approx x$.

Асимптотич. представление при больших $x$ :

\[
\mathrm{Si}(x)=\frac{\pi}{2}-\frac{\cos x}{x} P(x)-\frac{\sin x}{x} Q(x),
\]

где

\[
\begin{gathered}
P(x) \sim \sum_{k=0}^{\infty} \frac{(-1)^{k}(2 k) !}{x^{2 k}}, \\
Q(x) \sim \sum_{k=0}^{\infty} \frac{(-1)^{k}(2 k+1) !}{x^{2 k+1}} .
\end{gathered}
\]

И. с. представляется в виде ряда

\[
\text { Si }(x)=x-\frac{x^{3}}{3 ! 3}+\ldots+(-1)^{k} \frac{x^{2 k+1}}{(2 k+1) !(2 k+1)}+\ldots
\]