в декартовых прямоугольных координатах:

\[
\left(x^{2}+y^{2}+2 r x\right)^{2}=4 r^{2}\left(x^{2}+y^{2}\right) .
\]

Длина дуги от точки возврата:

Радиус кривизны:

\[
l=16 r \sin ^{2} \frac{\varphi}{4} .
\]

\[
r_{k}=\frac{8 r}{3} \sin \frac{\varphi}{2} .
\]

Площадь, ограниченная кривой: $S=6 \pi r^{2}$. Дпина кривой: $16 r$. К. является конхоидой окружности, частным случаем Паскаля улитки и синусоидальных спиралей.

Лит.: [1] С а в е ло в А. А., Плоские кривые, М., 1960.

КАРЛЕМАНА ГРАНИЧНАЯ ЗАДАЧА Д. граничная задача аналитич. функций со сдвигом, изменяющим направление обхода контура на обратное; впервые рассмотрена Т. Карлеманом [1]. Пусть $L$ - простая замкнутая кривая Јяпунова на плоскости комплексного переменного $z, D$ - конечная область, ограниченная кривой $L$. Пусть диффференцируемая комплексная функція $\alpha(t)$, заданная на $L$, осуществляет взаимно однозначное отображение контура $L$ самого на себя с изменением направления обхода $L$ на обратное и удовлетворяет дополнительному у с л о в и К а р л м а н a:

\[
\alpha[\alpha(t)]=t, \quad t \in L,
\]

(предполагается еще, что производная $\alpha^{\prime}(t)$ удовлетворяет условию Гёльдера). К. г. з. состоит в нахождении аналитической в $D$, за исключением конечного числа полюсов, и непрерывной в $D \cup L$ функции $\Phi(z)$ по граничному условию

\[
\Phi[\alpha(t)]=G(t) \Phi(t)+g(t), t \in L,
\]

тде заданные на $L$ функции $G(t)$ и $g(t)$ удовлетворяют условию Гёльдера и $G(t) \neq 0$ на $L$.

Изучалась также К. г. 3. с условием $\alpha^{m}(t)=t, \alpha^{1}(t)=\alpha(t), \alpha^{k}(t)=\alpha\left(\alpha^{k-1}(t)\right), k=2,3, \ldots, m$, более общим, чем (*), іг К. г. з. для нескольких неизвестных функций (см. [2], [3]).

Jum.: [1] C a r l e m a n T., B co.: Verhandlungen des Inter-

![](https://cdn.mathpix.com/cropped/2023_07_08_4b02fedc5fdd7d886e0ag-1.jpg?height=39&width=826&top_left_y=1407&top_left_x=124)
S. $138-51 ;$ [2] м у с х е л и ш в и ли и, и., Сингулярные интегральные уравнения, 3 изд., М., 1968; [3] В е к у а Н. П., Системы сингулярных интегральных уравнений и некоторые
граничные задачи, 2 изд., М., 1970.
. Д. Соломенцев.

КАРЛЕМАНА НЕРАВЕНСТВО - неравенство для произвольных неотршцательных чисел $a_{n} \geqslant 0$

\[
\sum_{n=1}^{\infty}\left(a_{1} a_{2} \ldots a_{n}\right)^{1 / n}<e \sum_{n=1}^{\infty} a_{n}
\]

найдено Т. Карлеманом [1]. Константу $e$ здесь уменьшить нельзя. Аналог К. н. для интегралов имеет вид:

\[
\int_{0}^{\infty} \exp \left\{\frac{1}{x} \int_{0}^{x} \ln f(t) d t\right\}<e \int_{0}^{\infty} f(x) d x, \quad f(x) \geqslant 0 .
\]

Имеются и другие обобщения К. н. [3].

Jum.: [1] C a r l e m a n T., в кн.: Wissenschaftliche Vorträge gehalten auf dem fünften Kongress der skandinavischen Mathematiker, Hels., 1923, S. 181-96; [2] X а p д и Г., ЈI и т т л b* в у д Д., П о л и а Г., Неравенства, пер. с англ., М., 1948.

Е. Д. Соломенцев.

КАРЛЕМАНА ТЕОРЕМА - 1) К. т. о к в а $\boldsymbol{3}$ и-

![](https://cdn.mathpix.com/cropped/2023_07_08_4b02fedc5fdd7d886e0ag-1.jpg?height=35&width=833&top_left_y=1970&top_left_x=122)
необходимое и достаточное условие квазианалитичности в смысле Адамара, найденное Т. Карлеманом [1] (cм. также [5]). Класс $K$ действительных функций $f(x)$, бесконечно дифференцируемых на отрезке $[a, b]$, наз. к в а зи а н а литическия в смысле А д ам а р а, еслі из равенств $f^{n}(c)=0, n=0,1, \ldots$, в какойлибо точке $c, a<c<b$, следует, что $f(x) \equiv 0$. Формулировка теоремы: класс $K$ квазианалитический тогда и только тогда, когда

\[
\sqrt[n]{M_{n}(f)}<A(f) a_{n}, \quad n=0,1, \ldots,
\]

где

\[
M_{n}(f)=\max _{a \leqslant x \leqslant b}\left|f^{(n)}(x)\right|,
\]

$A(f)$ - константа, а последовательность $\left\{a_{n}\right\}$ удовлетворяет одному из равносильных условий:

\[
\begin{aligned}
& \int_{1}^{\infty} \frac{\ln T(r) d r}{r^{2}}=+\infty, \\
& \sum_{n=1}^{\infty}\left(\inf _{k \geqslant n}^{k} \sqrt{a_{k}}\right)^{-1}=+\infty,
\end{aligned}
\]

где

\[
T(r)=\sup _{n \geqslant 1}\left(r^{n} / a_{n}\right)
\]

В теории квазианалитич. классов функций это один из первых законченных результатов. Квазианалитич. классы, определяемые условиями (1), (2), часто наз. кл а с с а м и

2) К. т. о б условия х о пре деленн ос т и п р о бле мы м о ме н т о в: если последовательность положительных чисел $s_{n}, n=0,1, \ldots$, удовлетворяет условію

\[
\sum_{n=1}^{\infty} \frac{1}{\sqrt[2 n]{s_{2 n}}}=+\infty,
\]

то проблема моментов

\[
s_{k}=\int_{-\infty}^{\infty} t^{k} d \sigma(t), \quad k=0,1, \ldots,
\]

является определенной. Это означает, что существует неубывающая функция $\sigma(t),-\infty<t<+\infty$, для к-рой выполняются равенства (3), единственная с точностью до прибавления любой функции, постоянной в окрестности каждой точки ее непрерывности. Теорема установлена Т. Карлеманом (см. [1], [2]).

3) К. т. о р а вноме рном при ближении це лым и ф у н к ц и ми: если $f(x)$ - любая непрерывная функция на действительной оси, а $\varepsilon(r)$, $0<r<+\infty,-$ положительная непрерывная функция, сколь угодно быстро убывающая при $r \rightarrow+\infty$, то существует целая функция $g(z)$ комплексного переменного $z=x+i y$ такая, что

\[
|f(x)-g(x)|<\varepsilon(|x|),-\infty<x<+\infty .
\]

Эта теорема, установленная Т. Карлеманом [3], явилась исходным пунктом исследований по приближениям целыми функциями. В частности, континуум $E$ на плоскости $z$ наз. к о н т и н у у м о м м а н а, если для любой непрерывной на $E$ комплексной функции $f(z)$ и произвольно быстро убывающей при $r \rightarrow \infty$ положительной функции $\varepsilon(r)$, нижняя грань к-рой на любом конечном интервале положительна, существует целая функция $g(z)$, удовлетворяющая неравенству

\[
|f(z)-g(z)|<\varepsilon(|z|), z \in E .
\]

Необходимые и достаточные условия, при к-рых замкнутое множество $E$ является континуумом Карлемана, получены в теореме Келдыша - Лаврентьева (см. [6]). Напр., континуумом Карлемана является замкнутое множество, составленное из лучей вида

\[
\arg z=\text { const, }|z|>c>0 \text {. }
\]

4) К. т. о п р и ближении аналитиче ских функций полиномами в с оеднем по п л о ш а д и о л а с т и: пусть $D$ - конечная область на плоскости комплексного переменного $z=$ $=x+i y$, ограниченная жордановой кривой $\Gamma$, и пусть $f(z)$ - регулярная аналитич. Функция в $D$ такая, что

\[
\iint_{D}|f(z)|^{p} d x d y<\infty, p>0
\]