тельность чисел $\left\{y_{k}\right\}_{k=0}^{\infty}$. Спрашивается, как по имеющимся данным

\[
f(x) \in K ; f\left(x_{k}\right)=y_{k}, k=0,1,2, \ldots,
\]

восстановіть $f(x)$ ? Поставленная задача в общем случае далеко не всегда разрешима и требует ряда уточнений, но это будет сделано несколько позже, а сейчас укажем только ао́ріс одного весьма естественного и важного подхода к решению проблемы (Б). Обычно вначале решается "усеченная" задача (A):

\[
f\left(x_{k_{j}}\right)=y_{k_{j}}, j=1,2, \ldots, n+1,
\]

в классе $\pi_{n}$. Пусть $L_{n}^{f}(x)$ - интерполяционный полином, являющийся решением этой усеченной задачи и записанный, например, в виде многочлена Лагранжа. Затем рассматривается возможность осуществления в том или ином смысле предельного перехода $L_{n}^{f}(x) \rightarrow f(x)$ при $n \rightarrow \infty$ (что равносильно, в частности, исследованию вопроса о стремлении к нулю остаточного члена $R_{n}^{f}(x)$ при $n \rightarrow \infty$ в рассматриваемом смысле). Приведенный эскиз схемы решения задачи (Б) лежит в основе теории сходимості (и расходимости) интерполячионных nроцессов; он является одним из основных методов решения задач интерполирования и имеет приложения не только в различных разделах чистой математики (напр., в теориі чисел, см. [3]), но и в методах вычислений (см. Интерполирование в вычіслительной математике, а также [1]).

В последующем, наряду с интерполяционными задачами рассмотренного здесь вида, определяемыми простейшими функционалами $f\left(x_{k}\right)$, стали исследоваться и другие, в к-рых, напр., задаются значения производных $f^{(m)}\left(x_{k}\right), m=0,1, \ldots, n_{k}$, или иные более сложные функционалы. При их решении стали применяться интерполяционные процессы, в к-рых в роли отправного интерполирующего класса вместо класса $\pi_{n}$ используются другие множества функций, напр. классы $T_{n}$ тригонометріч. полиномов степени $\leqslant n$, классы рациональных функций $\pi_{m, n}=p_{m} / q_{n}$, где $p_{m} \in \pi_{m}$, a $q_{n} \in \pi_{n}$ II $q_{n} \neq 0$, классы целых функций специального вида и т. д. См. также интерполячионная бормула.

Проблема ІІ. в своей общей постановке заключается в следующем. Пусть $X$ и $Y$ - два непустых множества; задано семеӥство отображений $\left\{f_{\alpha}\right\}_{\alpha \in \mathfrak{H}}, f_{\alpha}: X \rightarrow Y$, $\forall \alpha, \alpha \in \mathfrak{H}$. Если $\left\{y_{\alpha}\right\}, \alpha \in \mathfrak{A},-$ некоторый заданный набор элементов (не обязательно различных) множества $Y$, то естественно возникает задача об отыскании множества всех $x \in X$, удовлетворяющих следующей системе равенств

\[
\left(f_{\alpha}\right)(x)=y_{\alpha}, \quad \forall \alpha, \alpha \in \mathfrak{A} .
\]

Вообще говоря, не для всякого априори заданного набора элементов $\left\{y_{\alpha}\right\}, \alpha \in \mathfrak{H}$, задача (В) обязана иметь решения $x, x \in X$. Поэтому сформулированная проблема требует ряда уточнений своей постановки. Эти уточнения состоят в следующем.

I. Выяснить, каково множество $E=E\left(X ; f_{\alpha}\right)$ всех наборов $\left\{y_{\alpha}\right\}, \alpha \in \mathfrak{Y}$, для к-рых система уравнений (B) (быть может, бесконечная) имеет хотя бы одно решение $x, x \in X$. Другими словами, требуется дать конструктивное описание множества $E$ всех допустимых наборов $\left\{y_{\alpha}\right\}, \alpha \in \mathfrak{Y}$, для заданного фиксированного семейства отображений $\left\{f_{\alpha}\right\}, x \in \mathfrak{P}$, для к-рых система (В) непротиворечива в $X$.

II. Пусть $\left\{y_{\alpha}\right\}, \alpha \in \mathfrak{A},-$ фиксированный допустимый набор элементов из $Y$ (т. е. принадлежащий множеству $E$ из пункта I) задачи (B); требуется найти множество всех решений $x, x \in X$, системы (B).

При решении задач I и II особое значение имеют ответы на следующие вопросы более частного характера.

III. Каково подмножество $X_{1}, X \subset X$, на к-ром система уравнений (В) имеет единственное решение $x, x \in X_{1}$, для каждого допустимого для $X_{1}$ набора $\left\{y_{\alpha}\right\},\left\{y_{\alpha}\right\} \in E$ $\left\{f_{\alpha} ; X_{1}\right\}$ ?

IV. Пусть $E_{1}$ - некоторое подмножество $E$, определяемое обычно заданием лишь некоего ограничительного свойства. Требуется дать конструктивную характеристику множества решений $x, x \in X$, системы (B) при условии, что правые части в (В) «пробегают» все $E_{1}$. Задание множества $X, Y$ и семейства отображений $\left\{f_{\alpha}\right\}, \alpha \in \mathfrak{Y}\left(f_{\alpha}: X \rightarrow Y\right.$ при $\left.\forall \alpha, \alpha \in \mathfrak{H}\right)$ в совокупности с сформулированными вопросами I и II (и обычно присоединяемым к ним III, а иногда и IV) определяют интерполяционную задачу (В). Класс задач описанного вида иногда наз. классом п р я мы х з а д а ч и н т е рпо л и р о в а ни я.

Каждый в отдельности из перечисленных выше пунктов I, I I, I II и IV представляет и сам по себе научный интерес. Пункт I имеет «пограничный характер»: им занимаются теория чисел, функциональный анализ, теория функций и др. Пусть, напр., $x$ является действительным числом, $x \in \mathbb{R}, \quad$ и $\{x\}$ - его дробная часть. Семейство отображений $f_{n}: X \rightarrow Y, n \in N$, задается следующим образом: $\quad X \subset \mathbb{R}, Y=[0,1), \quad f_{n}(x)=\left\{x^{n}\right\}, \quad n=$ $=1,2, \ldots$, и рассматривается следующая конкретизация интерполяционной задачи (B):

\[
\left(f_{n}\right)(x)=\left\{x^{n}\right\}=y_{n}, \quad n=1,2, \ldots
\]

Для нек-рых подмножеств $X, X \subset \mathbb{R}$, пункт I задачи (2) в какой-то мере исследован, но в целом проблема (2) трудна: до сих пор (1978), напр., нет ответа на вопрос о распределении дробных долей $\left\{e^{n}\right\}$ степени числа $e$ что является весьма частным подвопросом пункта I задачи (2). Связь между вопросом I и проблемами базисности системы әлементов в различных функциональных пространствах отмечались, напр., в [9].

Вопрос II самый старый в теории И., он лежит у истоков всей теории И. и связан с именами И. Ньютона (I. Newton), Ж. Лагранжа (J. Lagrange), Н. Абеля (N. Abel), III. Эрмита (Ch. Hermite) и др. До 20 в. задачи I, II и IV почти не рассматривались, а решение задачи II, как правило, носило формальный характер.

Пункт III тесно примыкает к пункту II, но представляет интерес еще и потому, что во многих задачах он эквивалентен проблеме полноты, а иногда и базисности различных систем элементов $\left\{f_{\alpha}\right\}, \alpha \in \mathfrak{H}$, в соответствующих функциональных пространствах (полнота обычно устанавливается с помощью критерия С. Банаха (S. Banach), в к-ром доказана эквивалентность проблемы полноты нек-рой задаче единственности).

Важным примером исследований, относящихся к пункту IV, являются задачи, посвященные изучению классов функций, принимающих целые значения на заданном множестве точек (напр., $F(n)$ или $F\left(q^{n}\right), n=$ $=0,1,2, \ldots$, являются целыми числами). Эта область особенно бурно развивалась после получения Д. Пойа (G. Polya) следующего результата: если целая функция $F(z)$ әкспоненциального типа $\sigma, \sigma<\ln 2$, такова, что ее значения $F(n), \forall n, n=0,1,2, \ldots$, являются целыми числами, то $F(z)$ - полином. Константа $\ln 2$ в приведенной теореме точная, ибо функция $F(z)=2^{z=}=e^{z \ln 2}$ является целой экспоненциального типа $\sigma=\ln 2$, отлична от многочлена и принимает в точках $n=0,1,2, \ldots$ целые значения (см., напр., [5], [10]).

В том случае, когда в задаче (B) множество X является топологич. пространством и редуцированная в каком-то смысле задача (В) имеет сравнительно простое решение $x^{*}$, одним из методов ее решения является интерполяционный процесс, при к-ром исследуется сходимость решений $x^{*} \kappa$ решению $x$ системы (В). О частном виде подобного рода процессов упоминалось выше. Однако во многих случаях задачи типа (В) әфффективно решаются функциональными методами (см., напр., [10]).