нейных операторов слабых типов $\left(A_{i}, \psi_{i}\right)$, то оно будет иметь место и для квазиаддитивных операторов (со свойством $|T(x+y)(t)| \leqslant b(|T x(t)|+|T y(t)|)$ слабых типов $\left(\boldsymbol{A}_{i}, \psi_{i}\right), i=0,1$. Многие важные операторы анализа (напр., сингулярный оператор Гильберта) имеют слабый тип в естественных пространствах и поэтому соответствующие интерполяционные теоремы получили многочисленные применения.

Jum.: [1] B u tz e r P., B e r e n s H., Semi-groups of Operators and Approximation, В., 1967; [2] 3 и Г М у н д А., Тригонометрические ряды, пер. с англ., М., 1965; [3] К р е й н т. Г., П е т у ни н Ю. И., "У спехи матем. наук", 1966, Неоднородные граничные задачи и их приложения, пер. с франц., M., 1971; [5] M a д ж е н е с Э., "Успехи матем. наук", 1966, в гармонический анализ на евклидовых пространствах, пер. с англ., М., 1974; [7] Функциональный анализ, [Справочная математическая библиотека], 2 изд., м., $1972 ;$; [8] $\mathbf{B}$ e r g h

ИНТЕРПОЛЯЦИОННАЯ ФОРМУЛА - Формула для приближенного вычисления значений функции $f(x)$, основанного на замене приближаемой функции $f(x)$ более простой в каком-то смысле функцией

\[
g(x) \equiv g\left(x ; a_{0}, a_{1}, \ldots, a_{n}\right)
\]

наперед заданного класса, причем параметры $a_{i}$, $i=0,1, \ldots, n$, выбираются таким образом, чтобы значения $g(x)$ совпадали с известными заранее значениями $f(x)$ для данного множества $n+1$ попарно различных значений аргумента:

\[
g\left(x_{k}\right)=f\left(x_{k}\right), \quad k=0,1, \ldots, n .
\]

Такой способ приближенного представления функций наз. интерполированием, или и н те р по ля я и е й, a точки $x_{k}$, для к-рых должны выполняться условия (1), - у з л а м и и н те р п о л я ци и. Вместо простейших условий (1) могут быть заданы значения каких-либо иных величин, связанных с $f(x)$, напр. значения производных функции $f(x)$ в узлах интерполяции.

Среди методов гнтерполирования самым распространенным является ли и е й н о е ин те р п о л ир о в а н и е, когда приближение ищется в классе (обобщенных) полиномов

\[
g\left(x ; a_{0}, a_{1}, \ldots, a_{n}\right)=\sum_{i=0}^{n} a_{i} \varphi_{i}(x)
\]

по некоторой системе функций $\varphi_{0}(x), \varphi_{1}(x), \ldots, \varphi_{n}(x)$. Для того, чтобы для любой функции $f(x)$, определенной на отрезке $[a, b]$, и для любого набора $n+1$ узлов $x_{0}, x_{1}, \ldots, x_{n}, x_{i} \in[a, b], x_{i} \neq x_{j}$ при $i \neq j$ существовал ин те р по ляц ио н ны й По лин о м (2), необходимо и достаточно, чтобы система функций $\left\{\varphi_{i}(x)\right\}$ являлась Чебышева системой на отрезке $[a, b]$. При этом интерполяционный полином будет единственным и его коэффициенты $a_{i}$ можно найти непосредственным решением системы (1).

Чаще всего в качестве $\left\{\varphi_{i}(x)\right\}$ берут последовательность степеней $x$ :

\[
1, x, x^{2}, \ldots, x^{n}, \ldots,
\]

последовательность тригонометрических функций:

$1, \sin x, \cos x, \sin 2 x, \cos 2 x, \ldots$,

или последовательность показательных функций

\[
1, e^{\alpha_{1} x}, e^{\alpha_{2} x}, \ldots,
\]

где $\left\{\alpha_{i}\right\}$ - некоторая подпоследовательность попарно различных действительных чисел.

В случае интерполирования алгебраич. многочленами

\[
\sum_{i=0}^{n} a_{i} x^{i}
\]

система функций $\left\{\varphi_{i}(x)\right\}$ такова:

\[
\varphi_{i}(x)=x^{i}, \quad i=0,1, \ldots, n,
\]

а система уравнений (1) имеет вид

\[
\sum_{i=0}^{n} a_{i} x_{k}^{i}=f\left(x_{k}\right), \quad k=0,1, \ldots, n .
\]

Система (4) является системой Чебышева, что обеспечивает существование и единственность интерполяционного многочлена вида (3). Особенностью системы (4) является возможность получения явного представления интерполяционного многочлена (3), не прибегая к непосредственному решению системы (5). Одну из явных форм интерполяционного многочлена (3):

\[
g_{n}(x)=L_{n}(x)=\sum_{i=0}^{n} f\left(x_{i}\right) \prod_{j \neq i} \frac{x-x_{j}}{x_{i}-x_{j}}
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_92374291ac446e37c50ag-1.jpg?height=38&width=821&top_left_y=698&top_left_x=989)
Л а г р а н ж. В предположении непрерывности производной $f^{n+1}(x)$ остаточный член интерполяционного многочлена (6) может быть записан в форме

\[
\begin{gathered}
f(x)-g_{n}(x)=\frac{f^{(n+1)}(\xi)}{(n+1) !} \omega_{n}(x), \\
\xi \in\left[y_{1}, y_{2}\right], \quad \omega_{n}(x)=\prod_{i=0}^{n}\left(x-x_{i}\right) ;
\end{gathered}
\]

здесь $y_{1}=\min \left(x_{0}, x_{1}, \ldots, x_{n}, x\right), y_{2}=\max \left(x_{0}, x_{1}, \ldots, x_{n}, x\right)$. Величина остаточного члена (7) зависит, в частности, от значения многочлена $\omega_{n}(x)$. Представляет интерес такой выбор узлов интерполяции, при к-ром $\sup _{[a, b]}\left|\omega_{n}(x)\right|$ был наименьшим. Распределение узлов будет оптимальным в указанном смысле, если в качестве узлов интерполяции взяты корни

$x_{k}=\frac{1}{2}(b+a)+\frac{1}{2}(b-a) \cos \frac{2 k+1}{2 n+2} \pi, k=0,1, \ldots, n$, наименее уклоняющегося от нуля на отрезке $[a, b]$ многочлена

\[
\bar{T}_{n+1}^{[a, b]}(x)=(b-a)^{n+1} 2^{-1-2 n} T_{n+1}\left(\frac{2 x-(b+a)}{b-a}\right),
\]

где $T_{n+1}(z)$ - Чебышева многочлен степени $n+1$.

Существует ряд других явных представлений интерполяционного алгебраич. многочлена (3), более приспособленных для решения тех или иных практпч. задач интерполяции (см., напр., Бесселя интерполяционная бормула, Гаусса интерполяционная формула, Ньютона интерполячионная форжула, Стирлинга интерполяционная формула, Стеффенсена интерполяционная бормула, Эверетта интерполяционная бормула). Если заранее трудно оценить степень интерполяционного многочлена, требуемую для достижения заданной точности (напр., при интерполировании таблиц), то прибегают к использованию Эйткена схемы, по к-рой интерполяционные многочлены все более высокой степени строятся последовательно, что позволяет контролировать точность в процессе вычислений. Другой подход к построенію И. Ф. см. в ст. Фрезера диаграмма.

Решение задачи алгебраич. интерполирования по значениям функции и ее производных в узлах интерполяции дается Эрмита интерполяционной бормулой.

Лит.: [1] Б е р е з и н И. С., Ж йд о о в Н. П., Методы вычислений, 3 изд., т. 1, М., 1966; [2] Б а х в а л о в Н. С.,
Численные методы, 2 изд., М., 1975.
М. К. Самарин.

ИНТЕРПОЛЯЦИОННЫЙ ПРОЦЕСС - процесс получения последовательности интерполирующих функцій $\left\{f_{n}(z)\right\}$ при неограниченном возрастании числа $n$ условий интерполирования. Если интерполирующие функции $f_{n}(z)$ представлены в виде частных сумм некоторого функционального ряда, то последний иногданаз.