сываемое в явном виде). Пусть $F \subset \mathfrak{F}$ - область приведения положительных к. ф. Форма $q$ наз. приведенной, если $\Phi(q) \cap F$ не пусто.

Число классов целочисленных неопределенных к. ф. от $n$ переменных с данным определителем $d$ конечно (это верно и для положительных к. ф.). Число приведенных форм в данном классе также конечно. Если две целочисленные к. ф. $q_{1}$ и $q_{2}$ эквивалентны, то найдется целочисленная подстановка $S$, абсолютные величины әлементов к-рой ограничены постоянной, зависящей только от $n$ и $d$, переводящая $q_{1}$ в $q_{2}$. Тем самым проблема установления эквивалентности или неэквивалентности двух неопределенных целочисленных к. Ф. решается в конечное число шагов.

в) А в том орфизмы не оп пед е ленных к. Ф. Проблема описания всех автоморфизмов неопределенной целочисленной к. ф. имеет два аспекта: 1) построить фундаментальную область группы автоморфизмов и 2) описать общий вид автоморфизмов (подобно описанию автоморфизмов через уравнение Пелля).

Общий вид автоморфизмов к. ф. был описан III. Эрмитом (Ch. Hermite) для $n=3$ и А. Кэли (A. Cayley) для произвольного $n$ (см. [10]).

Построена фундаментальная область группы автоморфизмов неопределенной целочисленной к. ф. $q(x)$ в многообразии $\Phi(q)$, ограниченная конечным числом алгебраич. поверхностей, и вычислен ее объем [13]. В случае $t=1$ в $n$-мерном пространстве переменных построена фундаментальная область группы автоморфизмов к. Ф. $q(x)$ в виде бесконечной пирамиды с конечным числом плоских граней [2], [4].

Построена теория приведения к. Ф. в алгебраич. числовых полях (см. [11]).

Лum.: [1] В е н к о в Б. А., Элементарная теория чисел, M.- Л., 1937; [2] е г о ж е, "Изв. АН СССР. Сер. матем.",
1937 , т. 1, с. $139-70$; [3] е г о ж е, там же, 1940 , т. 4, с. $37-52$; [4] е г о ж е, "Тр. Матем. ин-та АН СССР", 1951, т. 38 , с. $30-$ 41; [5] Д е ло н е Б. Н., "У спехи матем. наук", 1937, в. 3, у ли н Р. В., Іі т о р г и н М. И., в кн.: Современные проблемы математики, т. 2, М., 1973 , с. $119-254 ;[7]$ Ј е ж ен Д̆ и р и х л е П. Г., Лекции по теории чисел, пер. с нем., м.1973 , т. 33 , с. $37-64 ;$ [9] Т а м м е л а П. П., там же, 1975, T. 50 , c. $6-96 ; 1977$, т. 67 , c. $108-43 ;[10]$ B a c h m a n n P., Die Arithmetik der quadratischen Formen, Abt. 1-2, Lpz., 1923-25;
[11] H u m e r t P.. "Comment. math. helv.», 1949, t. 23, p. 50$63 ;$ [12] M i n k o w s k i H., "J. reine und angew. Math.», 1905 , Bd 129 , S. $220-74 ;$ [13] S i e g e l C. L., "Abh. Math. Semin. Univ. Hamburg", 1940, Bd 13, S. 209-39; [14] e r o ж е, "Nachr. Akad. Wiss. Göttingen. Math.-phys. Kl.", 1972, S. 21-46; [15] V a n d e r W a e r d e n B. L., "Acta math.", 1956, v. 96,
p. $265-309$.
A. В. Малычев. КВАДРАТНОГО КОРНЯ МЕТОД - метод решенІя системы линейных алгебраич. уравнений $A x=b$ с эрмитовой невырожденной матрицей $A$. Среди прямых методов он наиболее эфффективен при реализации на ЭВМ.

Вычислительная схема метода в общем случае основана на факторизации эрмитовой матрицы $A$ в виде

\[
A=S^{*} D S
\]

где $S$ - правая треугольная матрица с действительными положительными диагональными элементами, $D-$ диагональная матрица с элементами 1 или -1 на диагонали. Из (1) непосредственно получаются рекуррентные соотношения для вычисления элементов $s_{i j}$ II $d_{i i}$ матриц $S$ и $D$ :

\[
\begin{gathered}
d_{i i}=\operatorname{sign}\left(a_{i i}-\sum_{k=1}^{i-1}\left|s_{k i}\right|^{2} d_{k k}\right) \\
s_{i i}=\left.\left.\left|a_{i i}-\sum_{k=1}^{i-1}\right| s_{k i}\right|^{2} d_{k k}\right|^{1 / 2} \\
s_{i j}=\left(a_{i j}-\sum_{k=1}^{i-1} \bar{s}_{k i} s_{k j} d_{k k}\right) / s_{i i} d_{i i}, \quad j>i
\end{gathered}
\]

После того как факторизация (1) выполнена, решение Іісходной системы сводится к последовательному решению двух систем $S^{*} D y=b$ и $S x=y$ с треугольными мат- рицами. В этой части К. к. М. совпадает с обратным ходом большинства прямых методов решения систем (см. Гаусса метод).

В действительном случае, когда $A$ - симметрич. матрица, схема (2) соответствует разложению $A=S^{\prime} D S$ с действительной матрицей $S$ и несколько упрощается. Существенное упрощение схемы (2) происходит, когда $A$ - положительно определенная матрица. В этом случае $D=E, A=S^{*} S$.

Известны схемы К. к. м. для неположительно определенных матриц, основанные на факторизации вида $A=S * S$. Для вычисления элементов $S$ имеют место рекуррентные соотношения, аналогичные (2). Однако эта факторизация не эффективна для реализации на ЭВМ в случае, когда $A$ - действительная матрица, так как при вычисленіи матрицы $S$ возможен выход в комплексную арифметику.

Из характерістик К. к. м. важны следующие.

1) Среді прямых методов решения систем, основанных на факторизации матрицы, К. к. м. обладает самым высоким быстродействнем (в два раза выше, чем у метода Гаусса).

2) Для факторизации матрıцы поо К. к. м. достаточно задавать компактную информацию о матрице в виде элементов ее треугольной половины. Ііроме того, схема (2) позволяет записывать в память ЭВМ матрицу $S$ на месте исходной информациі об $A$. Это существенно увеличивает порядок решаемых систем.

3) Вычислительная схема К. К. м. допугкает сегментированную обработку исходной матрицы участками из нескольких последовательных строк. Использование внешней памяти при этом позволяет решать системы высокого порядка.

4) К. к. м. сохраняет ленточную структуру матрицы, т. е. матрица $S$ будет иметь тот же вид, что и верхняя половина исходной матрицы.

5) Особенно эффективен К. к. м. для систем с положительно определенными матрицами. В данном случае нет роста элементов матрицы $\mathbf{3}$ процессе вычислений. Это свойство обеспечивает устойчивость вычислительного процесса к ошибкам округления. Мажорантная оценка точности вычисленного решения в этом случае - минимальная в классе прямых методов. Понижению общего уровня ошибок способствует и возможность вычисления скалярного произведения векторов в схеме (2) в режиме накопления с удвоенной точностыо.

Отсутствие роста әлементов в процессе вычислений делает удобным реализацию К. к. м. на ЭВМ, работающих в арифметике с фиксірованной запятой.

6) Разложение (1) по К. к. м. может быть использовано для вычисления определітеля матрпцы, обращепия матрицы.

Лuт.: [1] В о е в о д и н В. В., Численные методы алгебры, М., 1966; у2 - Б а х в а л о в Н. С., Численные методы, М., собственных значений, пер. с англ., М., 1970; [4] В о е в о д II н В. В., Вычислительные основы линейной алгебры, М., 1977.

КВАДРАТНОЕ УРАВНЕНИЕ - алгебраическое уравнение 2-й степени. Общий вид К. у.

\[
a x^{2}+b x+c=0, \quad a \neq 0 .
\]

В поле комплексных чисел К. у. имеет два решения, выражающиеся в радикалах через коэфффициенты этого уравнения:

\[
x_{1,2}=\frac{-b \pm \sqrt{b^{2}-4 a c}}{2 a} .
\]

При $b^{2}>4 a c$ оба решения К. У. действительные и различные, при $b^{2}<4 a c$ решения - комплексные (комплексно сопряженные) числа, при $b^{2}=4 a c$ уравнение имеет кратный корень $x_{1}=x_{2}=-b / 2 a$.