интерполяционным полиномом и последующим интегрированием. В частности, таким образом получены формулы Адамса для уравнения 1-го порядка (7) формулы Стёрмера для уравнений 2-го порядка и т. д.

Такой подход позволяет строить вычислительные алгоритмы для широкого класса дифференциальных уравнений в том числе и для уравнений в частных производных. Исследование разрешимости, точности и устойчивости решения возникающих конечно разностных уравнений представляет собой основную и наиболее трудную часть теории численного решения дифференциальных уравнений.

Интерполирование операторов и некото р ы р о е и ю ч и с ле н ных ме то д о в. Построение численных методов решения математич. задач, записанных в виде $y=A x$, где элементы $x$ и $y$ принадлежат нек-рым множествам $X$ и $Y$, а $A$ - заданный оператор, состоит в замене множеств $X$ и $Y$ и оператора $A$ или только нек-рых из этих трех объектов другими, удобными для вычислительных целей. При этом замена должна быть сделана так, чтобы решение новой задачи

\[
\tilde{y}=\tilde{A} \tilde{x}
\]

состоящей в нахождении $\tilde{y}$ или $\tilde{x}$, было в каком-то смысле близко к решению первоначальной задачи. Один из способов замены оператора $A$ его приближением $\tilde{A}$ состоит в использовании интерполирования операторов. Имеются различные формулировки задачи И. операторов. Линейный интерполяционный оператор $L_{\mathbf{1}}(F ; x)$ для данного оператора записывается в виде

\[
L_{1}(F ; x)=F\left(x_{0}\right)+F\left(x_{0}, x_{1}\right)\left(x-x_{0}\right),
\]

где $x_{0}$ и $x_{1}$ - узлы И., $F\left(x_{0}, x_{1}\right)$ - оператор разделенной разности 1-го порядка, определяемый как линейный оператор, удовлетворяющий условию

\[
F\left(x_{0}, x_{1}\right)\left(x_{0}-x_{1}\right)=F\left(x_{0}\right)-F\left(x_{1}\right) .
\]

Данное определение оператора разделенной разности в ряде случаев конкретизируется. С использованием линейного И. (8) «метод секущих» для уравнения $F(x)=0$ записывается в виде

\[
x_{n+1}=x_{n}-F^{-1}\left(x_{n-1}, x_{n}\right) F\left(x_{n}\right) \text {, }
\]

тде $F^{-1}\left(x_{n-1}, x_{n}\right)$ - оператор, обратный к $F\left(x_{n-1}, x_{n}\right)$.

Постановка задачи И. функционалов, представляющая интерес для теории приближенных методов такова. Пусть $\left\{\psi_{i}(x)\right\}, i=0,1, \ldots, n,-$ некоторые фиксированные функционалы или классы функционалов, определенные на $X$. Функционал $L_{n}[F ; x]$ наз. и н т е рполяци онным ф ункци о а льны м мног о ч л е н о м для данного функционала $F(x)$ и системы точек $\left\{x_{k}\right\}$ из $X$, если выполняются соотношения

\[
\begin{gathered}
L_{n}\left[F ; x_{k}\right]=F\left(x_{k}\right), \quad L_{n}\left[\psi_{i} ; x\right] \equiv \psi_{i}(x), \\
i=0,1, \ldots, n .
\end{gathered}
\]

И. функционалов используется при построении приближенных методов вычисления континуальных интегралов, для нахождения әкстремальных значений функционалов и ряда других задач.

Напр., приближенные интерполяционные формулы для вычисления континуальных интегралов имеют вид

\[
\int_{X} F(x) d \mu(x) \approx \int_{X} L_{n}[F ; x] d \mu(x),
\]

при этом интеграл от интерполяционного полинома $L_{n}[F ; x]$ для нек-рых мер $\mu$ может вычисляться точно или сводиться к конечномерным интегралам. Интерполяционный полином $L_{1}[F ; x]$, когда $X$ есть пространство непрерывных на отрезке $[a, b]$ функций $C[a, b]$,

\[
\begin{aligned}
& \text { представляется в виде интеграла Стилтьеса } \\
& \qquad L_{1}[F ; x]=F\left(x_{0}\right)+ \\
& +\int_{a}^{b} \frac{x(\tau)-x_{0}(\tau)}{x_{1}(\tau)-x_{0}(\tau)} d_{\tau} F\left[x_{0}(\cdot)+\chi(\cdot, \tau)\left(x_{1}(\cdot)-x(\cdot)\right)\right],
\end{aligned}
\]

где $x_{0}(t)$ и $x_{1}(t)$ - узлы И., а функция

\[
\chi(t, \tau)= \begin{cases}1, & \tau>t, \\ 0, & \tau \leqslant t .\end{cases}
\]

Если $F(x)$ - постоянный или линейный функционал, то $L_{1}[F ; x] \equiv F(x)$.

Применение И. к нахождению экстремальных значений функционалов может быть проиллюстрировано двумя интерполяционными аналогами метода градиента для нахождения локальной точки безусловного минимума функционала $F(x)$, определенного на нек-ром гильбертовом пространстве. Первый из этих методов получается, если в градиентном методе заменить grad $F\left(x_{n}\right)$ на $F\left(x_{n-1}, x_{n}\right)$, т. е.

\[
x_{n+1}=x_{n}+\varepsilon_{n} F\left(x_{n-1}, x_{n}\right), \quad \varepsilon_{n}>0, \quad n=1,2, \ldots
\]

Второй метод использует градиент интерполяционного полинома. По приближениям $x_{n-2}, x_{n-1}, x_{n}$ к экстремальной точке $x^{*}$ функционала $F(x)$ строится квадратичный интерполяционный функционал

\[
\begin{aligned}
& L_{2}[F ; x]=F\left(x_{n}\right)+F\left(x_{n-1}, x_{n}\right)\left(x-x_{n}\right)+ \\
& +F\left(x_{n-2}, x_{n-1}, x_{n}\right)\left(x-x_{n-1}\right)\left(x-x_{n}\right),
\end{aligned}
\]

где $F\left(x_{n-2}, x_{n-1}, x_{n}\right)$ - разделенная разность 2-го порядка функционала $F(x)$ относительно узлов $x_{n-2}, x_{n-1}$, $x_{n}$, и новое приближение $x_{n+1}$ находится по формуле

\[
\begin{gathered}
x_{n+1}=x_{n}-\varepsilon_{n} \operatorname{grad} L_{2}\left[F ; x_{n}\right], \\
\varepsilon_{n}>0, \quad n=2,3, \ldots
\end{gathered}
\]

Итерационные методы (9) и (10) используют соответственно два и три начальных приближения.

Применение И. функционалов и операторов для построения вычислительных алгоритмов решения конкретных задач основано на использовании интерполяционных формул с малой величиной погрешности. Такого рода формулы должны строиться для отдельных классов функционалов и операторов с учетом специфики этих классов.

.Тит.: [1] Г о н ч а р о в В. Л., Теория интерполирования и приближения функций, 2 изд., М., 1954; [2] Б е р е 3 и н

![](https://cdn.mathpix.com/cropped/2023_07_08_4ccadecdfc7427e833efg-1.jpg?height=44&width=821&top_left_y=1556&top_left_x=990)
2 изд., М., 1975; [4] Кр Ы Ло в В. И., Б о б к о в В. В.,

![](https://cdn.mathpix.com/cropped/2023_07_08_4ccadecdfc7427e833efg-1.jpg?height=47&width=821&top_left_y=1614&top_left_x=989)
Сплайны в вычислительной математике, М., 1976; [6] С а м а. с к и й А. А., Введение в теорию разностных схем, м., 1971; интегралов по гауссовым мерам, Минск, 1976. Л.А. Янович.

ИНТЕРПОЛИРОВАНИЕ ОПЕРАТОРОВ - получение из известных свойств оператора в двух или нөскольких пространствах выводов 0 свойствах этого оператора в нек-рых в определенном смысле промежуточных пространствах. Б а н а х о в о й п а $\mathrm{p}$ о й $A, B$ наз. два банаховых пространства, алгебраически и непрерывно вложенные в отделимое линейное топологич. пространство $\mathfrak{A}$. На пересечении $A \cap B$ вводится норма

\[
\|x\|_{A \cap_{B}}=\max \left\{\|x\|_{A},\|x\|_{B}\right\}
\]

на арифометич. сумме $A+B$ - норма

\[
\|x\|_{A+B}=\inf _{x=u+v}\left\{\|u\|_{A}+\|v\|_{B}\right\} .
\]

Пространства $A \cap B$ и $A+B$ банаховы. Банахово пространство $E$ наз. п р о м е у т о ч ны м для пары $A, B$, если $A \cap B \subset E \subset A+B$.

Линейное отображение $T$, действующее из $A+B$ в $C+D$, наз. о г р а ничен ны м о пе р а то р ом