К. н. - частный случай неравенств, связанных с вложением классов дифференцируемых функций (см. Вложения теоремы).

Лит.: [1] К о л м о г о р о в А. Н., "Ученые зап. Моск. ун-та, математика", 1939, в. 30, кн. 3, с. 3-16; [2] С т е ч[3] Т а й к о в Л. В., “Матем. заметки", 1968 , т. 4 , в. 2, с. $233-$ $238 ;$ [4] A p е с т о в B. B., "Acta Sci. Math.", 1972, v. 33, p. $243-67$.

2) К. н. в те ории вероятносте й-неравенство для максимума сумм независимых случайных величин - обобщение классического Чебыщева неравенства. Пусть $X_{1}, X_{2}, \ldots, X_{n}, \ldots-$ независимые случайные величины с конечными математич. ожиданиями $a_{n}=\mathrm{E} X_{n}$ и дисперсиями $\sigma_{n}^{2}=\mathrm{D} X_{n}$. Тогда для любого $\varepsilon>0$ $\mathrm{P}\left\{\max _{1 \leqslant m \leqslant n}\left|\sum_{k=1}^{m}\left(X_{k}-a_{k}\right)\right| \geqslant \varepsilon\right\} \leqslant \frac{1}{\varepsilon^{2}} \sum_{k=1}^{n} \sigma_{k}^{2}$, п если величины ограничены $\left(\left|X_{i}\right| \leqslant c \quad\right.$ с вероятностью 1), то

\[
1-\frac{(\varepsilon+2 c)^{2}}{\sum_{k=1}^{n} \sigma_{k}^{2}} \leqslant P\left\{\max _{1 \leqslant m \leqslant n}\left|\sum_{k=1}^{m}\left(X_{k}-a_{k}\right)\right| \geqslant \varepsilon\right\} .
\]

К. н. установлено А. Н. Колмогоровым [1]. К. н. замечательно как доказательством - способ рассуждений был новым в теории вероятностей, так и самим результатом - оценка для максимума сумм такова же, что и для последней суммы в неравенстве Чебышева.

При доказательстве К. н. существенно используются вытекающие из взаимной независимости $X_{k}$ свойства условных математич. ожиданий функций от сумм $S_{k+p}$ при условии, что $X_{1}, \ldots, X_{k}$ фиксированы.

К. н. допускает многочисленные обобщения, из которых можно отметить следующие:

1) K. н. остается справедливым, если условие взаимной независимости величин $X_{n}$ заменить условием, что $\left\{X_{n}\right\}$ есть абсолютно беспристрастная последовательность, т. е. что последовательность сумм $S_{n}=$ $=\sum_{k=1}^{n} X_{k}$ образует мартингал.

$\mathrm{Eg}\left(\left|S_{n}\right|\right)<\infty$, To

\[
P\left\{\max _{1 \leqslant m \leqslant n}\left|S_{m}\right| \geqslant \varepsilon\right\} \leqslant \operatorname{Eg}\left(\left|S_{n}\right|\right) \frac{1}{g(\varepsilon)} .
\]

3) Если $X_{k}, k=1, \ldots, n$, симметричны относительно вачала координат, то

\[
P\left\{\max _{\{1 \leqslant m \leqslant n}\left|S_{m}\right| \geqslant \varepsilon\right\} \leqslant 2 P\left\{\left|S_{n}\right| \geqslant \varepsilon\right\},
\]

см. Леви неравенство.

4) Для произвольных независимых случайных величив $X_{1}, X_{2}, \ldots, X_{n}, \ldots$

$P\left\{\max _{1 \leqslant m \leqslant n}\left|S_{m}\right|>\delta+\varepsilon\right\} \leqslant \frac{1}{1-p} P\left\{\left|S_{n}\right|>\varepsilon\right\}$,

если только числа $\delta>0$ и $0<p<1$ выбраны так, что $\mathbf{P}\left\{\left|S_{m}\right|>\delta\right\} \leqslant p$ при всех $m, 1 \leqslant m \leqslant n$.

Во всех вариантах К. н. можно увидеть следующее свойство сумм независимых величин - «размах" максимальной суммы имеет тот же порядок, что и "размах" последней суммы.

Как неравенство Чебышева применяется при выводе больших чисел закона, так и К. н. применяется при доказательстве больших чисел усиленного закона (критерий Колмогорова сходимости $S_{n} / n \rightarrow 0$ почти всюду). На использовании К. н. основано доказательство теорем о сходимости рядов из случайных величин.

![](https://cdn.mathpix.com/cropped/2023_07_08_ab36c0bb9fc299a322adg-1.jpg?height=50&width=799&top_left_y=2225&top_left_x=156)
99, S. 309-19; 1929 , Bd 102, S. 484-88; [2] е г о Ж е, Основные Теория вероятностей, пер. с англ., М., 1962. А. В. Прохоров. КОЛМОГОРОВА ПРОСТРАНСТВО - топологическое пространство, удовлетворяющее Колмогорова аксиоме.

КОЛМОГОРОВА УРАВНЕНИЕ - уравнение вида

\[
\frac{\partial f}{\partial s}=-A_{s} f
\]

(обратное, или первое, уравнение; $s<t$ )

или вида

\[
\frac{\partial f}{\partial t}=A_{t}^{*} f
\]

(прямое, или второе, уравнение; $t>s$ ) для переходной функции $[f=P(s, x ; t, \Gamma), 0 \leqslant s \leqslant t<\infty$, $x \in E, \quad \Gamma \in \mathfrak{B},(E, \mathfrak{B})$ - измеримое пространство] или ее плотности $[f=p(s, x ; t, \Gamma)$, если она существует], к уравнению (1) для переходной функции $P(s, x ; t, \Gamma)$ присоединяется условие

\[
\lim _{s \uparrow t} P(s, x ; t, \Gamma)=I_{\Gamma}(x),
\]

а к уравнению (2) - условие

\[
\lim _{t \downarrow s} P(s, x ; t, \Gamma)=I_{\Gamma}(x),
\]

где $I_{\Gamma}(x)$ - индикатор множества $\Gamma ;$ в этом случае оператор $A_{s}$ - оператор, действующий в пространстве функций, а $A_{t}^{*}$ - в пространстве обобщенных мер.

Для марковских процессов со счетным множеством состояний переходная функция полностью определяется вероятностями перехода $p_{i j}(s, t)=P(s, i ; t,\{j\})$ (из состояния $i$ в момент $s$ в состояние $j$ в момент $t$ ), для к-рой обратное и прямое уравнения Колмогорова имеют (при некоторых дополнительных предположениях) следующий вид:

\[
\begin{aligned}
\frac{\partial p_{i j}(s, t)}{\partial s} & =\sum_{k} \alpha_{i k}(s) p_{k j}(s, t), \quad s<t, \\
\frac{\partial p_{i j}(s, t)}{\partial t} & =\sum_{k} p_{i k}(s, t) \alpha_{k j}(t), \quad t>s, \\
\alpha_{i j}(s) & =\lim _{s_{1} \uparrow s, s_{2} \uparrow s} \frac{p_{i j}\left(s_{1}, s_{2}\right)-\delta_{i j}}{s_{2}-s_{1}} .
\end{aligned}
\]

гце

В случае конечного числа состояний уравнения (3), (4) справедливы, если только предположить существование пределов в (5).

Другой важный класс процессов, для к-рых детально изучен вопрос о справедливости уравнений (1) и (2), - это процессы диффузионного типа, определяемые тем, что их переходная функция $P(s, x ; t, \Gamma)$, $x \in \mathbb{R}, \quad \Gamma \in \mathfrak{B}(\mathbb{R})$ удовлетворяет следующим условиям:

a) для всякого $x \in \mathbb{R}$ и $\varepsilon>0$ равномерно по $s, s<t$,

\[
\int_{|x-y|>\varepsilon} P(s, x ; t, d y)=o(t-s),
\]

б) существуют функции $a(s, x)$ и $b(s, x)$ такие, что для всякого $x$ и $\varepsilon>0$ равномерно по $s, s<t$,

$\int_{|x-y| \leqslant \varepsilon}(y-x) P(s, x ; t, d y)=a(s, x)(t-s)+o(t-s)$, $\int_{|x-y| \leqslant \varepsilon}(y-x)^{2} P(s, x ; t, d y)=b(s, x)(t-s)+o(t-s)$.

Тогда, если существует плотность $p=p(s, x ; t, y)$, то (при некоторых дополнительных предположения справедливо (по $t>s$ и $y \in \mathbb{R}$ ) прямое уравнение

\[
\frac{\partial p}{\partial t}=-\frac{\partial}{\partial y}(a p)+\frac{1}{2} \frac{\partial^{2}}{\partial y^{2}}(b p)
\]

(называемое также уравнением Фоккера - Планка), а обратное уравнение (по $s<t$ и $x \in \mathbb{R}$ ) имеет следующий вид

\[
-\frac{\partial p}{\partial s}=a \frac{\partial p}{\partial x}+\frac{1}{2} b^{2} \frac{\partial^{2} p}{\partial x^{2}}
\]