ловия относительно решения $u(x, t)$ могут быть как линейными, так и нелинейными. В нек-рых случаях при соблюдении специальных условий удается проверить корректность постановки задач указанного типа.

Для сильно нелинейной системы (6) в случае $k=2$ исследована следующая задача: пусть $\Gamma_{1}-$ кривая выходящая из начала координатной системы и заданная уравнением $x=x(t)$, кривая $\Gamma_{1}$ предполагается характеристической, имеющей непрерывную касательную. Следует определить решение системы (6) в нек-рой области, ограниченной характеристикой $\Gamma_{1}$ и еще одной кривой $\Gamma_{2}$, выходящей тоже из начала координат, если известно решение $u(x, t)$ на $\Gamma_{1}$ при дополнительном условии, что одна из компонент вектора $u(x, t)$ имеет определенную особенность в точке пересечения граничных кривых. Известна разрешимость подобных задач при $t \leqslant \delta$ для достаточно малых $\delta$.

Среди задач, поставленных для квазилинейных гиперболич. систем 1-го порядка, имеется ряд важных прикладных задач: задача 0 распаде произвольного взрыва, задача хроматографии, задача фильтрации и др.

Изложенные выше результаты носят локальный характер, касаются только регулярных решений. Если же решения не являются диффференцируемыми или даже непрерывными функциями, вводятся понятия так наз. слабых решений, определяемых различными способами, для к-рых доказываются теоремы единственности и существования решения задачи Коши глобально. Как правило, эти решения определяются в довольно широких классах функций (ограниченные измеримые функции, локально суммируемые функции и др.). Они удовлетворяют уравнению или системе в каком-нибудь смысле, напр. в смысле теории обобщенных функций, или подчинены вполне определенным интегральным соотношениям. Слабое решение в нек-рых случаях принято наз. решением задачи Коши, если разность решения и начальных данных слабо стремится к нулю при стремлении точки к носителю начальных данных.

Известно несколько путей построения глобальных слабых решений задачи Коши для законов сохранения в случае многих переменных с начальными данными довольно общего вида. Напр., метод сглаживания, конечно разностные схемы решения задач с начальными даннымі.

Общие нелинейные гиперболич. уравнения и системы путем диффференци рования по независимым переменным сводятся к квазилинейным гиперболич. системам 1-го порялка. Любое гиперболич. уравнение 2-го порядка редуцируется к симметрической гиперболич. системе 1-го порядка, и факты, относящиеся к гиперболич. системам 1-го порядка, остаются в силе и для одного гиперболич. уравнения 2-го порядка.

Теорема существования решения задачи Коши для одного гиперболич. уравнения высшего порядка была получена при требовании достаточно высокой гладкости коэффициентов уравнения (см. [9]).

Задача Коши для гиперболических квазилинейных уравнений высшего порядка была исследована при помощи редукции к аналогичной задаче для квазилинейных систем 1-го порядка. Для уравнений 2-го порядка, кроме этого, используется и другой метод, заключающийся в введении характеристич. системы координат $(\alpha, \beta)$. Получается система уравнений относительно $x, t$ функции $u$ и ее производных 1-го и 2-го порядков, к-рые рассматриваются как функции характеристич. переменных. Система эта состоит из шести уравнений 1-го порядка относительно функций

$x=x(\alpha, \beta), \quad y=y(\alpha, \beta), \quad u=u(\alpha, \beta), p=u_{x}(\alpha, \beta)$, $q=u_{y}(\alpha, \beta)$

одно из к-рых является следствием всех остальных. Можно рассматривать определенную систему из пяти квазилинейных уравнений с пятью неизвестными функциями. Для подобных систем и, следовательно, для квазилинейных уравнений имеются теоремы существования и единственности решения задачи Коши. Этот метод без существенных изменений применяется и для квазилинейных систем уравнений 2-го порядка

\[
a u_{x x}^{j}+b u_{x t}^{j}+c u_{t t}^{j}+d^{j}=0, i=1,2, \ldots, k,
\]

где коэффициенты зависят от $x, t$ и функций $u^{j}$.

Jum.: [1] G 1 i m m J., "Comm. pure and appl. Math.», 1965, № 18, p. 697-715; [2]' D o u g l i s A., "Ann. Inst. Fourier", 1972, t. 22, p. 141-227; [3] K p y ж k o в C. Н., "Докл.

![](https://cdn.mathpix.com/cropped/2023_07_08_4845d925561a74969b05g-1.jpg?height=35&width=826&top_left_y=538&top_left_x=991)
r a n $t$ ' R., L a x P., "Comm. pure and appl. Math.", 1949, v. 2, p. 255-73; [6] C o n w a y E., S m o l l e r J., "Comm. pure and appl. Math.", 1966, v. 19, p. 95-105; [7] L a x P., "Comm. pure and appl. Math.", 1953, v. 6, p. 231 58 ; [8] L e w y H.,
"Math. Ann.", 1927, Bd 98, p. 179-91; [9] L e v i E., "Rend. reale accad. Lincei", 1908 , ser. 5 , v. 17 , p. $331-39$; [10] L e r a y J., Hyperbolic differential equations, Prinston, 1953; 1964 Le e a e t s in, Y u w en - t z u, "Scientia sinica", матем. наук», 1957 , т. 12 , в. 3, с. 3-73; [13] П е т р., "у с к и й И. Г., "Матем. сб,", 1937 , т. 2 , в. 5 , c. $815-66$; [14] Р о Ж д е с т в е н с и й Б. Л., Я не н ко Н. Н., Системы квазилинейных уравнений, M.,, 1968; [15] F r i e d r i c h s K.,
"Amer. J. Math.", 1948, v. 70, p. $555-89 ;$ [16] H a r t m a n P., "Amer. J. Math.", 1948, v. 70, p. 555-89; [16] H a r t m a n P., [17] S c h a u d e r J., "Comment." math. helv.", 1936 , v. 9 , p. 263-283. Д. К. Гвазава.

КВАЗИМНОГООБРАЗИЕ - см. Алгебрачческих систем квазимногообразие.

КВАЗИНОРМА - неотрицательная функция $\|x\|$, определенная на линейном пространстве $R$ и удовлетворяющая тем же аксиомам, что и норма, кроме аксиомы

![](https://cdn.mathpix.com/cropped/2023_07_08_4845d925561a74969b05g-1.jpg?height=37&width=819&top_left_y=1098&top_left_x=990)
слабым требованием: существует постоянная $c>0$ такая, что для всех $x \in R$ и $y \in R$ выполняется неравенство $\|x+y\| \leqslant c(\|x\|+\|y\|)$. Л. Д. Кудрлвчсв.

КВАЗИНОРМАЛЬНОЕ ПРОСТРАНСТВО - регулярное пространство, в к-ром два непересекающихся $\pi-л н о-$ жества имеют непересекающиеся окрестности. Всякое $T_{\lambda}$-пространство, в к-ром любые два непересекающихся $\pi$-множества имеют непересекаюциеся окрестности, является К. П. Для К. П. и только для такого пространства Стоуна - Чеха бикомпактное расширение $\beta X$ совпадает с $\omega_{x} X$-пространством. Болыной запас ненормальных $К$. П. дает теорема: произведение любого числа метрических пространств есть К. П.

Лum.: [1] 3 а й ц е в В. И., "Тр. Моск. матем. об-ва»,

![](https://cdn.mathpix.com/cropped/2023_07_08_4845d925561a74969b05g-1.jpg?height=52&width=826&top_left_y=1532&top_left_x=986)

КВАЗИНОРМИРОВАННОЕ ПРОСТРАНСТВО - ЛИнейное пространство, в к-ром задана квазинорма. Примерами К. п., не являющихся нормированными, служат Лебега пространства $L_{p}(E)$ при $0<p<1$, в к-рых квазинормой является выражение

\[
\|f\|=\left[\int_{E}|f(x)|^{p} d x\right]^{1 / p}, \quad f \in L_{p}(E) .
\]

Л. Д. Кудрявчев.

КВАЗИПЕРИОДИЧЕСКАЯ ФУНКЦИЯ с периодами $\omega_{1}, \omega_{2}, \ldots, \omega_{n}-$ функция $f(t)$ такая, что $f(t)=$ $\underset{F}{=} F(t, t, \ldots, t)$ для нек-рой непрерывной функции $F\left(t_{1}, t_{2}, \ldots, t_{n}\right)$ от $n$ переменных, периодической по $t_{1}, t_{2}, \ldots, t_{n}$ с периодами $\omega_{1}, \omega_{2}, \ldots, \omega_{n}$ соответственно. Все $\omega_{1}, \omega_{2}, \ldots, \omega_{n}$ строго положительны, и их обратные величины $p_{1}, p_{2}, \ldots, p_{n}$ являются рационально линейно независимыми.

Если $f_{1}(t)$ и $f_{2}(t)$ - непрерывные периодич. функции с периодами $\omega_{1}$ и $\omega_{2}$ соответственно, причем отношение $\omega_{1} / \omega_{2}$ иррационально, то $g(t)=f_{1}(t)+f_{2}(t)$ и $h(t)=$ $=\max \left\{f_{1}(t), f_{2}(t)\right\}$ суть К. ф.

Теория К. ф. послужила основой для создания теории почти периодических бункций. В случае непрерывных функший К. Ф. являются обобпением периодич. функций, но частным случаем почти периодических.