Если система (9) имеет специальное «разрывное» периодическое решение, то и (8) в ряде случаев располагает при малых $\mu$ истинным периодич. решением (см. [12]).

В приложениях весьма часто встречаются системы дифференциальных уравнений, в к-рых нельзя выделить никаких малостей. Здесь сталкиваются с нелокальными проблемами К. т. При исследовании нелокальных проблем возникают весьма серьезные трудности. Однако в ряде частных, но важных для приложений, случаев удается провести полное исследование соответствующей системы или получить достаточно существенную информацию о поведении ее решений. Напр., для уравнения

\[
\ddot{x}+f(x) \dot{x}+g(x)=0,
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_38e108d638bcbdfdcd33g-1.jpg?height=39&width=833&top_left_y=638&top_left_x=122)
нения, Н. Јевинсон и О. Смит [15] доказали существование, устойчивость и единственность предельного цикла. П̈ри доказательстве существенно использовался тот факт, что уравнение (10) есть уравнение 2-го порядка. В дальнейшем было доказано существование периодич. решения у нелинейного уравнения 3-го порядка и различных автономных систем высших порядков.

При исследовании периодических неавтономных систем, т. е. систем вида (4), у к-рых $X(x, t+\omega)=X(x, t)$, с системой связывают ее преобразование Пуанкаре $T$, вводимое формулой $T x_{0}=x\left(\omega, 0, x_{0}\right)$, где $x\left(t, t_{0}, x_{0}\right)-$ решение системы (4) такое, что $x\left(t_{0}, t_{0}, x_{0}\right)=x_{0}$. Если $x^{*}$ есть неподвижная точка преобразования $T$, то решение $x\left(t, 0, x^{*}\right)$ имеет период $\omega$ по $t$. Это дает возможность для доказательства существования периодич. решений применять различные теоремы о существовании неподвижной точки (см. [8], [9]).

В теории нелинейных колебаний важную роль играют диссипативные системы (это такие системы вида (4), у к-рых все решения при достаточно больших $t$ остаются в фиксированном шаре) и системы с конвергенцией (у таких систем все решения сходятся к одному устойчивому); разработаны достаточно надежные методы доказательства конвергентности и диссипативности конкретных систем [8].

Поведение решений диссипативной периодич. системы во многом определяется структурой нек-рого асимптотически устойчивого интегрального множества этой системы. Поэтому для теории нелинейных колебаний существенно исследование структуры таких множеств. В случае, если заданная система имеет лишь конечное число периодич. решений, такое множество удается охарактеризовать достаточно полно [13]. Если же система имеет бесконечно много периодич. решений, то в этом случае оказывается, что асимптотически устойчивые интегральные множества имеют чрезвычайно сложную структуру [13]. Исследование таких систем связано, как правило, с преодолением значительных трудностей, и его удается провести лишь в исключительных случаях. Пример такого исследования дан М. Картрайт и Дж. Литлвудом [16] при исследовании уравнения Ван дер Поля с вынуждением:

\[
\ddot{x}+k\left(x^{2}-1\right) \dot{x}+x=k b \sin t \text {. }
\]

В частности, они показали, что это уравнение при соответствующем выборе параметров $b$ и $k$ имеет бесконечно много периодич. решений.

Лит.: [1] Л я п у н о в А. М., Общая задача об устойчквости движения, Хар., 1892; [2] P o i n c a r e H., Les méthodes nouvelles de la mécanique celeste, t. 1, P., 1892; [3] א р ы л о в H. М., Б о г о л ю 6 о в Н. Н., Новые методы нелинейной механики, М.-Ј., 1934; [4] Н е м ы ц к и й В. В., С т е п а н о в В. В., Качественная теория дифференциальных уравнений, М.-Л.,
$1949 ;[5]$ м а л к и н и. Г., Некоторые задачи теории нелиней1949; [5] М а л к и н И. Г;, Некоторые задачи теории нелинейных колебаний, М.-Л., 1956; [6] Б о г о л ю б о в Н. Н., М и тнейных колебаний, 3 изд., М., 1963; [7] Е р уг и н Н. П., Линейные системы обыкновенных дифференциальных уравнений с периодическими и квазипериодическими коәффициентами, Минск, 1963; [8] П л и с с В. А., Нелокальные пробллемы теории колебаний, М.- Л., 1964; [9] К р а с н о с е л ь с к и й М. А., Оператор сдвига по траекториям дифференциальных уравнений,

![](https://cdn.mathpix.com/cropped/2023_07_08_38e108d638bcbdfdcd33g-1.jpg?height=48&width=839&top_left_y=281&top_left_x=985)
Линейные дифференциальные уравнения с периодическими Л ы к о а О. Б., Интегральные многообразия в нелинейной механике, 1973; [12] $\mathbf{M}$ и щ е н к о Е. Ф., Р о з о в Н. Х.. Дифференциальные уравнения с малым параметром и релаксационные колебания, М., 1975; [13] П ли с с В. А., Интегральные множества периодических систем дифференциальных уравнений, М.,
$1977 ;$ [14] А р н о л ь д В. И., «Успехи матем. наук», 1963, т. 18, B. 6, c. 91-192; [15] L e v in so n N., S m i t O. K., "Duke "Acta math.", 1957, v. 97, № 3-4, p.267-308. B. A. Плиcc.

КОЛЕБЛЮЩЕЕСЯ РЕІЕНИЕ - решение $x(t)$ диффференциального уравнения

\[
x^{(n)}=f\left(t, x, x^{\prime}, \ldots, x^{(n-1)}\right), \quad t \in\left[t_{0}, \infty\right),
\]

обладающее свойством: для любого $t_{1} \geqslant t_{0}$ найдется точка $t_{2}>t_{1}$, при переходе через к-рую функция $x(t)$ меняет знак. Во многих прикладных задачах возникает вопрос о существовании $\mathfrak{K}$. р. или о колеблемости всех решений уравнения (*). Известно много достаточных условий, при к-рых уравнение (*) имеет К. р. (см. [1] - [3]). Напр., любое нетривиальное решение уравнения $x^{\prime \prime}+2 \delta x^{\prime}+\omega^{2} x=0$ с постоянными коэфффициентами колеблется, если $\delta^{2}<\omega^{2}$; любое нетривиальное решение уравнения

\[
x^{\prime \prime}+p(t) x^{\prime}+q(t) x=0
\]

с $\omega$-периодическими коэффициентами колеблется, если

\[
\begin{aligned}
& \int_{0}^{\omega} d t \int_{t}^{t+\omega} q(s) \exp \left(-\int_{s}^{t} p(r) d r\right) d s \geqslant \\
& \geqslant-\frac{1}{2}\left(1-\exp \int_{0}^{\omega} p(t) d t\right) \int_{0}^{\omega} p(t) d t
\end{aligned}
\]

и $q(t) \neq 0$ на $[0, \omega]$.

В ряде приложений возникает вопрос о К. р. (в определенном смысле) системы обыкновенных дифференциальных уравнений. Напр., в теории регулирования изучают колеблемость относительно заданной гиперплоскости $\sum_{i=1}^{{ }^{n}} c i x_{i}=0$ решений $x(t)=\left(x_{1}(t), \ldots, x_{n}(t)\right)$ системы уравнений $x^{\prime}=f(t, x)$, т. е. вопрос о колеблемости функции $\sigma(t)=\sum_{i=1}^{n} c_{i} x_{i}(t)$. Изучают также

![](https://cdn.mathpix.com/cropped/2023_07_08_38e108d638bcbdfdcd33g-1.jpg?height=42&width=826&top_left_y=1492&top_left_x=996)
решение $x(t)$ системы $x^{\prime}=f(t, x)$ наз. [ $\left.\alpha, \beta\right]-к$ о л е б л ющ и м с я, если функция $\sigma(t)$ колеблется и для любого $t_{1} \geqslant t_{0}$ найдутся точки $t_{2}$ и $t_{3}$ такие, что $t_{1}<t_{2}<t_{3}$, $\sigma\left(t_{2}\right)<\alpha, \quad \sigma\left(t_{3}\right)>\beta$, причем $\alpha<0<\beta$. Для системы (2) существуют и др. определения колеблемости решений.

Лит.: [1] X а т м а н Ф., Обынновенные дифференциальные уравнения, пер. с англ., M., 1970; [2] S w a n s o n C. A., Comparison and oscillation theory of linear differential equations,
$\mathrm{N}$. Y. L., 1968; [3] К и $\Gamma$ у p a д з $\mathrm{e}$. Т., Некоторые сингулярные краевые; задачи для обыкновенных дифференциальных уравнений, Тб., 1975 .

КОЛЕЦ МНОГООБРАЗИЕ - класс колец $\mathfrak{M}$, удовлетворяющих заданной системе полиномиальных тождеств. К. м. можно определить аксиоматически, как наследственный класс алгебр, замкнутый относительно взятия гомоморфных образов и полных прямых сумм (см. Алгебраических систем многообразие). Так как совокупность полиномиальных тождеств, выполнимых в данном кольце, образует вполне характеристич.

![](https://cdn.mathpix.com/cropped/2023_07_08_38e108d638bcbdfdcd33g-1.jpg?height=38&width=829&top_left_y=2055&top_left_x=992)
взаимно однозначное соответствие между многообразиями колец и $T$-идеалами счетно порожденного свободного кольца. Если для $\mathfrak{K}$. м. имеет место включение $\mathfrak{N} \subseteq \mathfrak{M}$, то говорят, что $\mathfrak{N}$ является подмногообразием в $\mathfrak{W}$. Многообразие, соответствующее $T$-идеалу тождеств кольца $A$, наз. многообразием, порожденным кольцом $\boldsymbol{A}$. Каждое многообразие колец порождается своим «универсальным объектом»- свободным коль-