Эти результаты имеют многочисленные применения в топологии трехмерных многообразий и, в частности, в теории узлов. Так, если $K$ - узел, то $\pi_{1}\left(S^{3} \backslash K\right)$ изоморфно $\mathbb{Z}$ тогда и только тогда, когда $K$ - тривиальный узел. Для $n$-компонентного зацепления $L$ в $S^{3}$ следующие условия равносильны: 1) $\pi_{2}\left(S^{3} \backslash L\right) \neq 0$; 2) $\pi_{1}\left(S^{3} \backslash L\right)$ есть свободное произведение двух нетривиальных групп; 3) в $S^{3} \backslash L$ существует такое подмногообразие $N$, гомеоморфное двумерной сфере, что обе компоненты $S^{3} \backslash N$ содержат точки из $L$. В частности, если $L-$ узел (т. е. $n=1$ ), то $\pi_{2}\left(S^{3} \backslash L\right)=0$ (т е о р е м а о б а с ф е р ич н о с т и у з ло в).

Jum.: [1] D e h n M., "Math. Ann.", 1910, Bd 69, S. 137168; [2] П а п а к и р ь я ко п у л о с С. Д., "Математика", 1958, т. 2, N 4, с. 23-47; [3] М а с с и у., С т о л Л и н г с

![](https://cdn.mathpix.com/cropped/2023_07_08_cbc34f3acff5f953cb85g-1.jpg?height=42&width=829&top_left_y=625&top_left_x=119)

ДЕНДРИТ - локально связный континуум, не содержащий простых замкнутых кривых. Континуум, каждая точка к-рого имеет окрестность, являющуюся Д., наз. ло ка ль ным денд ри т ом.

ДEHOTAT А. А. Мальцев. нием к-рого является это имя.

ДЕНУМЕРАНТ - число $D\left(n ; a_{1}, a_{2}, \ldots, a_{m}\right)$ разбиений целого числа $n$ на части, равные $a_{1}, a_{2}, \ldots$, $a_{m}$, т. е. число репений в целых неотрицательных числах уравнения

\[
a_{1} x_{1}+a_{2} x_{2}+\ldots+a_{m} x_{m}=n .
\]

Производящая функция для Д. имеет ви д:

$D\left(t ; a_{1}, a_{2}, \ldots, a_{m}\right)=\sum D\left(n ; a_{1}, a_{2}, \ldots, a_{m}\right) t^{n}=$ $=1 /\left(1-t^{a_{1}}\right)\left(1-t^{a_{2}}\right) \ldots\left(1-t^{a_{m}}\right)$.

Наиболее просто Д. вычисляется по р е к у р р е н тном у с о о т но іI е ни ю Э й ле ра.

$D(n ; 1,2, \ldots, k)-D(n-k ; 1,2, \ldots, k)=$ $=D(n ; 1,2, \ldots, k-1)$.

Формулы в явном виде для нек-рых Д. могут быть получены из следующей теоремы: если $a$ является наименьшим общим кратным чисел $a_{1}, a_{2}, \ldots, a_{m}$, то Д.\[
D\left(a n+b ; a_{1}, a_{2}, \ldots, a_{m}\right),
\]\[
b=0,1, \ldots, a-1 \text {, }
\]

оказывается многочленом степени $m-1$ относительно $n$.

Лит.: [1] Р и о р д а н Д ж., Введение в комбинаторный анализ, пер. с англ., М., 1963.

ДЕ РАМА КОГОМОЛОГИИ - см. Рама когомологии.

ДЕ РАМА КРУЧЕНИЕ - см. Рама кручение.

ДЕ РАМА ТЕОРЕМА - см. Рама теорема.

ДЕРЕВО в т е о р и и $г$ р а ф о в-связный неориентированный грая $G$, не содержащий циклов. Д. не имеет кратных ребер и петель. Являясь простейпими связными графами, Д. служат хоропими моделями для рассмотрения различных вопросов теории графов. Јюбое Д. с $n$ верпинами содержит $n-1$ ребер. Число различных Д., к-рые можно построить на $n$ нумерованных вершинах, равно $n^{n-2}$. Д. с одной выделенной вершиной наз. к о р н е в ы м д е р е в о м.

Перечисляющий ряд

\[
T(x)=\sum_{n=1}^{\infty} T_{n} x^{n}
\]

для числа $T_{n}$ неизоморфных корневых Д. с $n$ вершинами удовлетворяет функциональному уравнению

\[
T(x)=x \exp \sum_{r=1}^{\infty} \frac{1}{r} T\left(x^{r}\right) .
\]

Перечисляющий ряд

\[
t(x)=\sum_{n=1}^{\infty} t_{n} x^{n}
\]

для числа $t_{n}$ неизоморфных Д. с $n$ вершинами можно представить с помощью перечисляющего ряда для корневых Д.:

\[
t(x)=T(x)-\frac{1}{2}\left[T^{2}(x)-T\left(x^{2}\right)\right] .
\]

Функциональные уравнения для $T(x)$ и $t(x)$ позволяют вычислять значения $T_{n}$ и $t_{n}$ для конкретных значений $n$ (см., напр., [1]).

Доказано, что при $n \rightarrow \infty$

\[
t_{n} \sim C \alpha^{n} / n^{5 / 2}
\]

где $C=0,534948 \ldots, \alpha=2,95576 \ldots$ (см. [2]). Задачи перечисления Д. определенного вида возникают, напр., в химии при изучении изомеров.

Д. можно достаточно просто кодировать наборами из нулей и единиц. Рассмотрим, напр., к.-л. правильную (без пересечения ребер) укладку Д. $D$ на плоскости (см. Графа укладка). Начиная с к.-л. вершины, будем двигаться по ребрам Д. $D$, сворачивая в каждой вершине на ближайшее справа ребро и поворачивая назад в концевых вершинах Д. Проходя по нек-рому ребру, записываем 0 при движении по ребру в первый раз и 1 при движении по ребру второй раз (в обратном направлении). Если $m$ - число ребер Д. $D$, то через $2 m$ шагов мы вернемся в исходную вершину, пройдя по каждому ребру дважды. Полученная при этом последовательность из 0 и 1 (код Д.) длины $2 m$ позволяет однозначно восстанавливать не только само Д. $D$, но и его укладку на плоскости. Произвольному Д. соответствуют несколько кодов. Из этого способа кодирования вытекает оценка: $t_{n}<T_{n}<4^{n}$.

Д. $G$ с $n$ вершинами однозначно восстанавливается (с точностью до изоморфизма) по набору всех его $(n-1)$ верпинных подграфов $G-v$, получаемых из $G$ удалением каждой из его вершин $v$.

Любое Д. однозначно определяется также расстояниями (длиной наименьшей цепи) между его концевыми (степени 1) вершинами.

О с т о в н о е д е р е в о (о с т о в) - это подграф данного графа, содержащий все его вершины и являющийся Д. Число остовных Д. произвольного связного графа $G$ без петель и кратных ребер можно вычислить следующим образом. Пусть $M$ - матрица, полученная из матрицы смежности граф̆а $G$ изменением знаков всех әлементов на противоположный и заменой $i$-го әлемента главной диагонали степенью вершины $v_{i}$. Тогда алгебраич. дополнения всех элементов главной диагонали матрицы $M$ равны между собой и их общее значение есть число остовов графа $G$. Остовные Д. используются, напр., для нахождения независимых циклов в әлектрич. схеме.

Важное значение для приложений имеет задача нахождения в связном графе, ребрам к-рого приписаны веса, остовного Д. с наименьшей суммой весов ребер. Такая задача возникает, напр., при проектировании коммуникационных сетей. Известен алгоритм для решения этой 3 а д а ч и о к р а т ч а й пI е м с в я зы в а ю щ е м д е р е в е (см. [3]). Д., растущим (или выходящим) из вершины $v_{0}$, наз. ориентированный граф, к-рый является (без учета ориентации) корневым Д. с корнем $v_{0}$ И в к-ром для любой вершины $v_{1}$ (единственная) цепь, соединяющая $v_{0}$ с $v_{1}$, является ориентированным путем из $v_{0}$ в $v_{1}$. Такие Д. используются, напр., для описания детерминированных функций, для представления информации в информационно-поисковых системах и т. Д.

Обобщением понятия «Д.» является понятие «леса»; л е с - это граф̆ без циклов (не обязательно связный).

![](https://cdn.mathpix.com/cropped/2023_07_08_cbc34f3acff5f953cb85g-1.jpg?height=50&width=824&top_left_y=2225&top_left_x=990)
№3, p. 583-99; [3] П р и м Р.'. К., "Кибернетический сборник», 1961. в. 2, с. 95-107. В. Б. Алексеев.