системы (1), если на нек-рой гладкой $n$-мерной гиперповерхности П, определенной уравнением

\[
\varphi(x)=0,|D \varphi| \neq 0,
\]

известны значения вектора-функции $u(x)$ и ее частных производных по какому-нибудь нетангенциальному к $\Pi$ направлению до порядка $m-1$ включительно. Если такое решение всегда можно найти, то гиперповерхность $\Pi$ наз. с в о б о д н о й относительно оператора $L$. Если коэфффициенты системы (1) и условия Коши, заданные на аналитической свободной гиперповерхности $\Pi$, аналитичны, то аналитическое в окрестности $\Pi$ решение единственно; если, помимо этого, условия Кoши определяют на П все производные до порядка $m-1$, то, согласно теореме Коши - Ковалевской, в достаточно малой окрестности любой точки поверхности П аналитич. решение отсутствует. Эта теорема применима ко всем аналитич. уравнениям и системам независимо от того, какому типу они принадлежат. При неаналитических же данных теорема не дает ответа о существовании таких решений.

Если никакая часть гиперповерхности П не свободна, то ее наз. $\mathbf{x}$ a $\mathrm{p}$ а к т е $\mathrm{p}$ и с т и ч е с к о й п о в е p $\mathbf{x}-$ н о с т ь ю относительно оператора $L$. Чтобы гиперповерхность П была характеристической относительно оператора $L$, необходимо и достаточно выполнение условия

\[
Q(\xi)=0,
\]

где $\xi=\left(\xi_{0}, \ldots, \xi_{n}\right)$ - нормаль к поверхности П. Характеристич. матрица, характеристич. форма и характеристич. поверхность инвариантны относительно неособых преобразований. Характеристич. поверхности играют важную роль при исследовании многих задач для уравнений и систем вида (1).

Многие задачи математич. физики сводятся к симметрическим гиперболич. уравнениям и системам. Квазилинейная система 1-го порядка

\[
L[u] \equiv \sum_{i=0}^{n} a^{i} u_{x_{i}}+b u=f
\]

наз. с и м м е т р и ч е с к о й, если все матрицы $a^{i}$ симметричны. Симметрич. система (1') наз. г и п е рбо лич е с ко й с и мме т р и ч е с кой системой в точке $P$, если одна из матриц $a^{i}$ или какая-либо линейная комбинация $\xi^{i} a^{i}$ знакоопределенна. Одно уравнение или система уравнений выспего порядка наз. симмет рическими ги пер болическим и, если они әквивалентны какой-нибудь симметрической гиперболич. системе 1-го порядка. Систему (1') при положительно определенном коэффициенте $a^{0} \mathrm{c}$ помощью линейного преобразования можно привести к виду

\[
u_{t}+M[u]=f, \quad t \equiv x_{0}
\]

с симметрич. оператором $M$. При помощи әнергетических неравенств и метода итераций доказывается существование решения задачи Коши для квазилинейных систем 2-го порядка и для одного нелинейного уравнения произвольного порядка.

Так как характеристики и бихарактеристики для гиперболич. уравнений и систем, как линейных, так и квазилинейных, определяются одинаково, известные факты о распределении разрывов младших производных решений линейных уравнений и систем относятся и к случаю квазилинейных уравнений. Распространение разрывов решения $u(x)$ гиперболич. систем рассмотрено для з а к о н о в с о х р а н е н и, т. е. для систем 1-го порядка, имеющих следующий вид:

\[
\sum_{i=0}^{n} \frac{\partial}{\partial x_{i}} F^{i j}(x, u)=0, j=1,2, \ldots, k,
\]

при условии, что поверхность ударной волны является нехарактеристической.

Много работ посвящено исследованию К. г. у. и с. в случае двух пространственных переменных $x$ и $t$. Ваљк ную часть этих исследований составляют квазилинейные системы 1-го порядка, к-рые имеют вид:

\[
L[u] \equiv A u_{x}+B u_{t}=C,
\]

где $A$ и $B$ - квадратные матрицы порядка $k$, вектор $C$ зависят от переменных $x, t$ и от вектора $u(x, t)=\left\{u_{1}(x, t)\right.$, $\left.\ldots, u_{k}(x, t)\right\}$. Если от искомой вектор-функции $u$ $(x, t)$ зависит только правая часть $C,(5)$ наз. п о ч т и ли н е й н о й с и с т е м о й. Почти линсйные системы 1-го порядка эквивалентно сводятся к симметрич. системам линейными преобразованиями. Квазілинейная система (5) при предположении $\operatorname{det} B \neq 0$ имеет следующий вид:

\[
u_{t}+A u_{x}=C .
\]

Матрицу $A$ можно преобразовать к диагональному віду с әлементами $x_{i}$, где векторы $\left(x_{i}, 1\right)$ определяют характеристич. направления; эта запись наз. нормальной формой системы (5). Для систем вида (6) справедлива теорема единственности, независимо от того, зависят их характеристики от решения $u(x, t)$ или нет.

Если коэфффициенты $A, C$ и начальные значения решения $u(x, t)$ при $t=0$ имеют первые производные по всем аргументам и эти производные удовлетворяют Липщица условию, то можно указать окрестность $0 \leqslant t \leqslant h$ отрезка оси $t=0$, в к-рой существует единственнос решение задачи Коши с первыми производными, удовлетворяюпцими условию Липшица. При этом вводятся векторфункции $v(x, t)$, к-рые при $t=0$ совпадают с заданными начальными данными, а их первые производные удовлетворяют условию Липшица. После подстановки $v(x, t)$ в коәфффициенты $A$ и $C$ решается задача Коши с заданными начальными данными для линейного уравнения. Каждой функции $v(x, t)$ ставится в соответствие решение $u(x, t)$ и решение задачи для системы $(6)$ выводится как неподвижный элемент преобразования $u=\mathfrak{Y}[v]$, или как предел равномерно сходящейся последовательности $\left\{u_{n}\right\}_{n-1,2 \ldots}$, полученный в результате итераціонного процесса

\[
u_{n+1} \equiv \mathfrak{U}\left[u_{n}\right]
\]

Аналогичный результат получается при достаточно гладких коаффициентах $A, C$ и начальных данных путем редукции задачи к системе интегральных уравнений, разрешимость к-рой доказывается на основе сжатых отображений принципа.

К вазилинейная система 1-го порядка (5) наз. с л а б о н е ли н ей н о й с и с те м о й, если соответствующая ей нормальная форма

\[
u_{t}+A u_{x}=C
\]

такова, что для каждого элемента $a^{i i}$ диагональной матрицы выполняется условие:

\[
\frac{\partial}{\partial u_{i}} a^{i i}\left(x, t, u_{1}, \ldots, u_{k}\right)=0, i=1,2, \ldots, k .
\]

В других случаях (5) наз. с и л ь н о н е ли н е ӥ н о й с и с т е м о й. Если решение слабо нелинейной системы при $k=2$ ограничено, то задача Iடоши всегда разрешима в области определенности.

Кроме задачи с началыными данными, для квазілинейных систем 1-го порядка поставлены и исследованы и другие задачи. Напр., так наз. смепанные задачи, заключающиеся в нахождении решения $u(x, t)$ сістемы (7), к-рое наряду с начальными условиями $u(x, 0)=$ $=\psi(x)$ при $t=0, \alpha \leqslant x \leqslant \beta$ удовлетворяет краевым условиям на нек-рых гладких кривых $\Gamma_{1}$ и $\Gamma_{2}$, выходящих из точек $(\alpha, 0)$ и $(\beta, 0)$ соответственно. Эти краевые ус-