щими собственный $L$-гомоморфизм, т. е. гомоморфизм решеток подгрупп на нек-рую решетку $L$, не являющийся изоморфизмом.

Иногда термин «К. г.» используется для обозначения различных подгрупп мультипликативной группы алгебры кватернионов и соответствующих топологич. групп.

Лит.: [1] Х о л л М., Теория групп, пер. с англ., М., 1962.

![](https://cdn.mathpix.com/cropped/2023_07_08_16c7cb65abfcc544ceedg-1.jpg?height=42&width=797&top_left_y=429&top_left_x=156)
ществует абсолютная постоянная $K>0$ (п о с т о я нн а я $\mathrm{K}$ ё б е) такая, что если $f \in S$ ( $S$ - класс функций $f(z)=z+\ldots$, регулярных и однолистных в $|z|<1)$, то множество значений функции $w=f(z)$ при $|z|<1$ заполняет круг $|w|<K$, причем $K$ - наибольшее из чисел, для к-рых это справедливо. J. Бибербах (L. Bieberbach, 1916) доказал, что $K=1 / 4$ и что на окружности $|w|=1 / 4$ только в том случае имеются точки, не принадлежащие образу круга $|z|<1$ при отображении $w=f(z)$, если

\[
f(z)=z\left(1+e^{i \alpha} z\right)^{-2}
\]

где $\alpha$ - действительное число. К. т. покрытия иногда формулируют так: если функция $w=f(z), f(0)=0$, регулярна и однолистна в $|z|<1$ и отображает круг $|z|<1$ на область, не содержащую точку $c$, то $\left|f^{\prime}(0)\right| \leqslant 4 c$.

2) К. т. и с к а ж е н и я. а) Существуют такие положительные числа $m_{1}(r), M_{1}(r)$, зависящие только от $r$, что для $f \in S,|z|=r$ имеют место неравенства:

\[
m_{\mathbf{1}}(r) \leqslant|f(z)| \leqslant M_{\mathbf{1}}(r) .
\]

б) Существует число $M(r)$, зависящее только от $r$ и такое, что для $f \in S,\left|z_{1}\right| \leqslant r,\left|z_{2}\right| \leqslant r$ справедливы неравенства:

\[
\frac{1}{M(r)} \leqslant\left|\frac{f^{\prime}\left(z_{1}\right)}{f^{\prime}\left(z_{2}\right)}\right| \leqslant M(r) .
\]

Эту теорему можно также сформулировать следующим образом: существуют положительные числа $m_{2}(r)$, $M_{2}(r)$, зависящие только от $r$ и такие, что для $f \in S$, $|z| \leqslant r$

\[
m_{2}(r) \leqslant\left|f^{\prime}(z)\right| \leqslant M_{2}(r) .
\]

Л. Бибербах показал, что наилучшие границы в К. т. искажения таковы:

\[
\begin{aligned}
& m_{1}(r)=\frac{r}{(1+r)^{2}}, \quad M_{1}(r)=\frac{r}{(1-r)^{2}}, \\
& m_{2}(r)=\frac{1-r}{(1+r)^{3}}, \quad M_{2}(r)=\frac{1+r}{(1-r)^{3}} .
\end{aligned}
\]

3) К. т. об отоб ражении конечно с в я з ных областей на канонически е о б л а с т и. а) Всякую $n$-связную область $B$ плоскости $z$ можно однолистно отобразить на к р у г о в у ю о б л а с т ь (т. е. на область, ограниченную конечным числом полных окружностей без общих точек, причем нек-рые из них могут вырождаться в точки) плоскости $\zeta$. Среди этих отображений существует только одно нормированное отображение, переводящее заданную точку $z=a \in B$ в $\zeta=\infty$ и такое, что разложение отображающей функции в окрестности $z=a$ имеет вид

\[
\frac{1}{z-a}+\alpha_{1}(z-a)+\ldots \text { или } z+\frac{\alpha_{1}}{z}+\ldots,
\]

смотря по тому, конечно $a$ или нет.

б) Всякую $n$-связную область $B$ плоскости $z$ с граничными континуумами $K_{1}, \ldots, K_{n}$ можно однолистно отобразить на плоскость $\zeta$ с $n$ разрезами по дугам логарифмич. спиралей соответственно наклонов $\theta_{1}, \ldots$, $\theta_{n}, 0 \leqslant \theta_{v} \leqslant \pi / 2, v=1, \ldots, n$, к радиальным направлениям и притом так, что континуумы $K_{v}, v=1, \ldots, n$, переходят соответственно в дуги наклонов $\theta_{v}$, заданные точки $a, b \in B$ переходят в 0 и $\infty$ и разложение отображающей функции в окрестности $z=b$ имеет вид

\[
\frac{1}{z-b}+\alpha_{0}+\alpha_{1}(z-b)+\ldots \text { или } z+\alpha_{0}+\frac{\alpha_{1}}{z}+\ldots,
\]

смотря по тому, конечно $b$ или нет. Отображение единственно.

Теоремы 1) - 3) установлены П. Кёбе (см.[1] - [4]). Jum.: [1] K o e b e P., "Nachr. Kgl. Ges. Wiss. Gött., Math.Phys. Kl.», 1907, Bd 2, S. 191-210; 1909, Bd 4, S. 68-76; [2] е г o ж e, "Math. Ann.", 1910, Bd 69, S. 1-81; [3] е г o ж e, "Acta Math.", 1918, V. 41, p. 305-44; [4] е г о ж е, "Math. Z.",
1918, Bd 2, S. 198-236; [5] Г о л у з и н Г. М., "Успехи матем. наук", 1939 , в. 6 , с. $26-89$; [6] е г о ж е, Геометрическая теория функций комплексного переменного, 2 изд., М., 1966 ; [7] Джен к и н с Д ж., Однолистные функции и конформные

КЁБЕ ФУ НКЦИЯ - функция

$w=f(z)=f_{\theta}(z)=z\left(1-e^{i \theta} z\right)^{-2}=z+\sum_{n=2}^{\infty} n e^{i(n-1) \theta_{z^{n}}}$, где $\theta \in[0,2 \pi)$. Эта функция была впервые изучена П. Кёбе [1]. К. ф. отображает круг $|z|<1$ на плоскость $w$ с разрезом по лучу, исходящему из точки $-\frac{1}{4} e^{-i \theta}$ и содержащему на своем продолжении точку $w=0$. К. ф. является экстремальной функцией ряда задач теории однолистных функций.

JIum.: [1] K o e b e P., "Math. Ann.», 1910, Bd 69, S. 1-81; [2] H a y m a n W. K., "J. London Math. Soc.», 1965, v. 40, № 3, p. 385-406; [3]' Го лу зин теория функций комплексного переменного, 2 изд., М., 1966.

КЕЛДЫІІА ТЕОРЕМА - 1) К. т. о п р и б л Иже ни и н е п р е р ы в ы гоч л е н а м и: пусть функция $f(z)$ комплексного переменного $z$ голоморфна в области $G$ и непрерывна в замкнутой области $\bar{G}$; тогда, для того чтобы при любом $\varepsilon>0$ существовал многочлен $P(z)$ такой, что

\[
|f(z)-P(z)|<\varepsilon, \quad z \in \bar{G},
\]

необходимо и достаточно, чтобы дополнение $C \bar{G}$ состояло из одной единственной области $G^{*}$, содержащей бесконечно удаленную точку. Установлена М. В. Іелдышем [1]. Эта теорема является одним из основных результатов теории равномерных приближений функций многочленами в комплексной области (см. [2]).

2) К. т. в те о ри и по т е нци а ла - теоремы о разрешимости и устойчивости Дирихле задачи, установленные М. В. Келдышем в 1938-41.

a) Пусть $D$ - ограниченная область евклидова пространства $\mathbb{R} n, n \geqslant 2$, с границей $\Gamma=\partial D$. Тогда на $\Gamma$ существует счетное множество иррегулярных граничных точек $\left\{y_{k}\right\}, k=1,2, \ldots$, такое, что для разрешимости задачи Дирихле в области $D$ с непрерывной граничной функцией $f(y)$ на $\Gamma$ необходимо и достаточно, чтобы эта задача была разрешима в точках $y_{k}, k=1,2, \ldots$, т. е. чтобы

\[
\lim _{x \rightarrow y_{k^{\prime}} x \in D} u(x)=f\left(y_{k}\right), k=1,2, \ldots,
\]

где $u(x)$ - обобщенное в смысле Винера - Перрона решение задачи Дирихле (см. Перрона метод, а также $[3],[4])$

б) Пусть оператор $A$ действует из пространства $C(\Gamma)$ непрерывных функций на $\Gamma$ в пространство ограниченных гармонических в $D$ функций и удовлетворяет следующим условиям: (a) $A(\alpha f+\beta g)=\alpha A(f)+\beta A(g)$, $f, g \in C(\Gamma)$, где $\alpha, \beta$ - действительные числа, т. е. оператор $A$ линейный; (б) если $f(y) \geqslant 0, f \in C(\Gamma)$, то $A(f)(x) \geqslant$ $\geqslant 0$; (в) если для функции $f \in C(\Gamma)$ задача Дирихле разрешима, то $\boldsymbol{A}(f)$ дает решение этой задачи. При әтих условиях оператор $\boldsymbol{A}$ единственный и $\boldsymbol{A}(f)$ для всех $f \in C(\Gamma)$ дает обобщенное в смысле Винера Перрона решение задачи Дирихле (см. [5]-[7]).