где пижняя грань берется по всем окрестностям точки $Q$. Если $Q \in E$, то для непрерывности $f$ в точке $Q$ по множеству $E$ необходимо и достаточно, чтобы $\omega_{Q, E}(f)=0$.

КОЛЕБАНИЙ ТЕОРИЯ - раздел прикладной теории дифференциальных уравнений, связанный с изучением колебательных явлений в естествознании и техніке. Основные проблемы существованія и фактич. отыскании колебательных (першодических, почти периодических и др.) движений - решений заданной системы, и исследовании поведения остальных решений по отношению к данным колебательным. Различают теорию линейных колебаний и теорию нелинейных колебаний.

В те о рии лине й ных коле б а нй дело сводится $\mathrm{K}$ изучению линейных систем диффференциальных уравнений, это обычно бывает связано с тем, что рассматриваемые величины (искомые функции системы дифференциальных уравнений) столь малы, что оказывается возможным пренебречь нелинейными членами в правых частях системы. Рассматриваются линейные системы диффференциальных уравнений:

\[
\frac{d x}{d t}=P(t) x+f(t),
\]

где $x(t)$ и $f(t)$ суть $n$-мерные векторы, а $P(t)$ - квадратная матрица порядка $n$, причем $P(t)$ и $f(t)$ чаще всего являются периодич. или почти периодич. функциями. Основные проблемы теории линейных колебаний: построение периодич. и почти периодич. решений системы (1) и исследование свойств их устойчивости. Наиболее детально с этих точек зрения изучены случаи, когда заданная система близка к системе уже изученной, иными словами, те случаи, когда удается ввести малый параметр следующим образом:

\[
\frac{d x}{d t}=(P(t)+\mu Q(t, \mu)) x+f(t)
\]

в предположении, что система

\[
\frac{d x}{d t}=P(t) x
\]

полностью исследована, а $\mu$ - малый параметр. Для таких систем в большинстве случаев удается исследовать вопрос о существовании периодических (соответственно почти периодических) решений и фактически построить их. При весьма широких предположениях относительно матриц $P$ и $Q$ дается представление характеристич. показателей системы (3) в виде функций параметра (см. [7], [10]), в частности исследовано интересное явление параметрич. резонанса в линейных системах [5].

В теори и нелин ейных коле бан ий как по постановке задач, так и по методам исследования существенным образом различаются так наз. локальные и нелокальные проблемы. $\mathcal{K}$ первым из них относятся такие задачи, в к-рых удается выделить какиелибо «малости» (напр., малы сами исследуемые величины, или в системе имеются малые параметры).

Если в исследуемой задаче искомые функции можно считать малыми, то дело сводится к исследованию окрестности состояния равновесия для системы диф̆ференциальных уравнений

\[
\frac{d x}{d t}=X(x, t)
\]

где $x(t)$ п $X(x, t)$ суть $n$-мерные векторы и $X(0, t) \equiv 0$. Здесь широко применяются методы локальной качественной теории диффференциальных уравнений [4] и методы теории устойчивости движения в смысле Ляпунова [1]. Весьма важный результат для теории нелинейных колебаний был получен А. Н. Колмогоровым и его последователями (см. [4]): было доказано сущест- вование квазипериодич. решений в окрестности состояния равновесия $x=0$ для системы (4).

Часто в заданные системы дифференциальных уравнений входят малые параметры, т. е. рассматриваются системы вида

\[
\frac{d x}{d t}=X(x, t)+\mu R(x, t, \mu),
\]

где $\mu$ - малый параметр. С такого рода системами связывают следующую проблему: наряду с системой (5) рассматривают так наз. «порождающую» систему ту, в к-рую обращается система (5) при $\mu=0$, т. е. систему вида (4). Предполагается, что «порождающая" система обладает нек-рым свойством; ставится вопрос: не будет ли и система (5) обладать тем же свойством при малых, но отличных от нуля $\mu$. Напр., пусть система (4) имеет периодич. или почти периодич. решение $x=\psi(t)$, будет ли при этом система (5) обладать периодич. или почти периодич. решением $x=\varphi(t, \mu)$ таким, что

\[
\lim _{\mu \rightarrow 0} \varphi(t, \mu)=\psi(t) ?
\]

Еще А. Пуанкаре [2] разработал мощные методы для решения такого рода проблем. В ряде случаев им было не только доказано существование периодич. решения, но и указан алгоритм для его построения (см., напр.,[5]).

Н. М. Крылов, Н. Н. Боголюбов и их ученики (см. [3], [6], [11]) развивали для систем вида (5) асимптотич. методы. Среди этих методов особо важную роль играет метод осреднения, к-рый состоит в следующем. Рассматривается так наз. стандартная система:

\[
\frac{d x}{d t}=\mu X(x, t, \mu)
\]

Оказывается, что к такой системе могут быть сведены многие системы теории нелинейных колебаний. Наряду с системой (6) рассматривается «осредненная» система

\[
\frac{d y}{d t}=\mu Y(y)
\]

где

\[
Y=\lim _{t \rightarrow \infty} \frac{1}{t} \int_{0}^{t} X(x, \tau, 0) d \tau .
\]

Н. М. Крылов и Н. Н. Боголюбов показали, что система (7) приближает систему (6) с точностью до величин порядка $\mu^{2}$. С помощью дальнейших осреднений можно избавиться от зависимости от $t$ в членах сколь угодно высокого порядка малости по $\mu$. Однако этот процесс, как правило, расходится, так что описанный метод является по существу асимптотическим.

Весьма важную роль в теории нелинейных колебаний играет метод интегральных поверхностей. Основы этого метода были заложены А. М. Ляпуновым [1]. При весьма общих предположениях было доказано (см. [3], [6], [11]), что если «порождающая» система (4) имеет интегральную поверхность с определенными свойствами, то и система (5) обладает такой же интегральной поверхностью.

С описанным кругом проблем тесно связана теория релаксационных колебаний. Эти колебания описываются системами диффференциальных уравнений с малыми параметрами при производных:

\[
\frac{d x}{d t}=X(x, y, t, \mu), \mu \frac{d y}{d t}=Y(x, y, t, \mu),
\]

где $x$ и $X$ - n-мерные векторы, $y$ и $Y$ - $m$-мерные векторы, а $\mu$ - малый параметр. Наряду с системой (8) рассматривается вырожденная система:

\[
\frac{d x}{d t}=X(x, y, t, 0), \quad Y(x, y, t, 0)=0 .
\]