разии $X$, причем $X / G$ - диффференцируемое многообразие, известен аналог $\left\{E_{r}\right\}$ спектральной последовательности накрытия [3]. Последовательность $\left\{\tilde{E}_{\boldsymbol{r}}\right\}$ сходится к когомологиям комплекса $G$-инвариантных дифференциальных форм на $X$ и $\tilde{E}_{2}^{p, q}=$ $=H^{p}\left(G, H^{q}(X, \mathbb{R})\right)$, где когомологии группы $G$ вычисляются при помощи коцепей класса $C^{\infty}$.

См. также Когомологии групn, Эквивариантные когомологии.

Лит.: [1] г р о т е н д и к А., О некоторых вопросах гомологической алгебры, пер. с франц., М., 1961; [2] К а р т а н А., Э йле н б е р г С., Гомологическая алгебра, пер. с англ., М., $1960 ;$ [3] v a n E s t W. T., "Proc. Nederl. Akad. Wetensch.
Ser. A», 1958, v. 61, p. 399-413.

КОГОМОЛОГИИ АЛГЕБР - группы

\[
H^{n}(R, A)=\operatorname{Ext}_{R}^{n}(K, A), \quad n \geqslant 0,
\]

(см. Функтор Ext), где $R$ - ассоциативная алгебра над коммутативным кольцом $K$ с фиксированным гомоморфизмом $K$-алгебр $\boldsymbol{\varepsilon}: \boldsymbol{R} \rightarrow K$, позволяющим рассматривать кольцо $K$ как $R$-модуль, а $A$ есть $R$-модуль. Это определение охватывает наиболее распространенные теории когомологий нек-рых типов (универсальных) алгебр.

Впервые группы когомологий групп во всех размерностях были введены С. Эйленбергом и С. Маклейном [3] в связи с топологич. исследованиями и Д. К. Фаддеевым [5] - с чисто алгебраич. точки зрения - как группы классов обобщенных систем факторов, в 40-х гг. 20 в. Ранее изучались в той или иной форме когомологии групп в малых размерностях (см. [1], [2], [4]).

П р и е р ы груп п когом ологий.1) Если $K=\mathbb{Z}$ - кольцо целых чисел, $G-$ группа, $\quad \boldsymbol{R}=\mathbb{Z} \boldsymbol{G}-$ групповая алгебра группы $G$ над $\mathbb{Z}$,

\[
\varepsilon\left(\sum n_{i} g_{i}\right)=\sum n_{i}, \quad n_{i} \in \mathbb{Z}, \quad g_{i} \in G,
\]

то группы $H^{n}(R, A)$ наз. $\mathbf{r}$ р у п а м и к о г о мол о г и й г р у п п ы $G$ с коэфффициентами (или со значениями) в $R$-модуле $A$ и обозначаются $H^{n}(G, A)$. Можно вместо группы $G$ рассмотреть моноид $G$ и аналогично получить г р у п П ы кого мо ло г и й $H^{n}(G, A)$ мо н о и д а $\left.G .2\right)$ Если $S-$ ассоциативная $K$-алгебра, $S^{0}$ - антиизоморфная ей $K$-алгебра,

\[
R=S \otimes_{K} S^{0}, \varepsilon\left(\sum s_{i} \otimes t_{i}\right)=\sum s_{i} t_{i}
\]

то группы $H^{n}(R, A)$ наз. г р у п п а и ко гомологи й а с социат ивн ой а лге бры $S$ сооэффициентами в $S$-бимодуле $A$ (т. е. в $R$-модуле $A$ ) и обозначаются $H^{n}(S, A)$. Если $K$ - поле, то группы

![](https://cdn.mathpix.com/cropped/2023_07_08_532da3896e366e870c24g-1.jpg?height=39&width=833&top_left_y=1650&top_left_x=122)
Х о хши л ь д а $K-\mathbf{л а г е б р ы ~} S$.

3) Если $S$-алгебра Ли над полем $K, R=U_{S}-$ ее универсальная обертывающая алгебра с пополнением $\varepsilon: R \rightarrow K$, то группы $H^{n}(R, A)$ наз. г р у П П а м и ко гомоло гий а л ге б ры Л и $S$ с коэфффициентами в $U_{S}$-модуле $A$ (т. е. в лиевом $S$-модуле $A$ ) и обозначаются $\boldsymbol{H}^{n}(S, \boldsymbol{A})$.

При $n=0,1,2$ группы когомологий в ряде случаев допускают простую интерпретацию.

a) Если $G$ - группа, то группа $H^{0}(G, A)$ изоморфна групіе

\[
A^{G}=\{a \in A \mid g a=a, \quad \forall g \in G\}
\]

инвариантных әлементов; группа $H^{1}(G, A)$ изоморфона факторгруппе $\operatorname{Der}(G, A) / \mathrm{Ider}(G, A)$, где

$\operatorname{Der}(G, A)=\{f: G \longrightarrow A \mid f(x y)=x f(y)+f(x), \forall x, y \in G\}$ - группа диффференцирований (или скрещенных гомоморфизмов),

$\operatorname{Ider}(G, A)=\{f: G \longrightarrow A \mid \exists a \in A, f(x)=x a-a, \forall x \in G\}$

- группа внутренних диффференцирований (или глав- ных скрещенных гомоморфизмов), при этом точна последовательность

\[
0 \longrightarrow A^{G} \longrightarrow A \longrightarrow \operatorname{Der}(G, A) \rightarrow H^{1}(G, A) \rightarrow 0
\]

для абелевой группы $G$ группа $H^{2}(G, A)$ изоморфна группе расширений группы $A$ с помощью группы $G$ (см. Бәра умножение); третья группа когомологий группы $G$ связана с препятствиями для расширений (см. [9], гл. IV).

б) Если $S$ - ассоциативная $K$-алгебра, то группа $H^{0}(S, A)$ изоморфна группе

\[
\{a \in A \mid x a=a x, \quad \forall x \in S\}
\]

группа $H^{\mathbf{1}}(S, A)$ изоморфна факторгруппе

$\operatorname{Der}(S, A) / \operatorname{Ider}(S, A)$,

где

$\operatorname{Der}(S, A)=\left\{f: S \bigotimes_{K} S^{0} \longrightarrow A \mid f(x y)=x f(y)+f(x) y\right.$, $\left.\forall x, y \in S \otimes_{K} S^{0}\right\}$ $\operatorname{Ider}(S, A)=\left\{f: S \otimes_{K} S^{0} \longrightarrow A \mid \exists a \in A, f(x)=x a-a x\right.$,

группа $H^{2}(S, A)$ описывает сингулярные расширения $S$-бимодуля $A$ с помощью кольца $S$ (см. [14]).

в) Если $S$ - алгебра Ли, то группа $H^{0}(S, A)$ изоморфна $K$-модулю $\{a \in A \mid x a=0, \forall x \in S\} ; \operatorname{rpуппа~} H^{\mathbf{1}}(S, A)$ изоморфна факторгруппе

\[
\operatorname{Der}(S, A) / \operatorname{Ider}(S, A) \text {, }
\]

где

$\operatorname{Der}(S, \boldsymbol{A})=\{f: S \longrightarrow A \mid f([x, y])=x f(y)-y f(x)$,

\[
\forall x, y \in S\}
\]

$\operatorname{Ider}(S, A)=\{f: S \longrightarrow A \mid \exists a \in A, f(x)=x a, \forall x \in S\}$;

двумерная группа когомологий $H^{2}(S, A)$ алгебры Ли соответствуют $K$-расщепляющимся расширениям алгебр Ли (см. [6], гл. XVI); в нек-рых случаях әлементы группы $\boldsymbol{H}^{\mathbf{3}}(S, \boldsymbol{A})$ являются препятствиями в задаче о расширении.

Группы когомологий находят широкое применение в различных областях алгебры. Так, напр., если $G-$ группа и $H^{2}(G, A)=0$ для всех $\mathbb{Z} G$-модулей $A$, то $G-$ свободная группа (т е о р е м а С т о л л и н г с а, см. Гомологическая размерность). Если $G-$ группа, $\mathbb{C}^{*}-$ мультипликативная группа поля комплексных чисел, то группа $M(G)=H^{2}\left(G, \mathbb{C}^{*}\right)$ наз. м у л ь т и п ли к а т ор о м III у р а группы $G$. Она играет важную роль при изучении центральных расширений групп и в теории проективных представлений конечных групп [1]. Если $G$ - группа, $A-\mathbb{Z} G$-модуль и $p A=0$ для простого числа $p$, то

\[
\mathrm{Ext}_{\mathbb{Z} \mathrm{G}}^{n}(\mathbb{Z}, A) \cong \mathrm{Ext}_{k G}^{n}(k, A),
\]

где $k=G F(p)$ - поле из $p$ әлементов. Если $G$ - конечная $p$-группа, то $d(G)=\operatorname{dim}_{k} H^{1}(G, k)$ - минимальное число образующих группы $G, r(G)=\operatorname{dim}_{k} H^{2}(G, k)-$ минимальное число определяющих соотношений для $G$, рассматриваемой как про-p-группа, $r(G) \leqslant R(G)$, где $\boldsymbol{R}(\boldsymbol{G})$ - минимальное число соотношений дискретной группы $G$. Тот факт, что $r(G)-d(G)$ стремится к бесконечности при $d(G) \rightarrow \infty$, приводит к отрицательному решению проблемы башни полей, проблемы Куроша о нильалгебрах и общей проблемы Бернсайда [10].

Если $G$ - про-p-группа, $\left\{U_{i}, i \in I\right\}$ - семейство всех ее открытых нормальных делителей, то группа

\[
\stackrel{\lim }{\longrightarrow} H^{n}\left(G / U_{i}, A^{U_{i}}\right)
\]

наз. $n$-й $\mathbf{⿴ 囗} \mathrm{y}$ п по й ко гом о ло г и й п $\mathrm{p} о-p-$ г р у п І ы $G$ с коэфффициентами в $\mathbb{Z} G$-модуле $A$ и обозначается $H^{n}(G, A)$. Если $E$ - расширение Галуа