числения неэквивалентных конфигураций $\sigma$ таких, что

\[
[\sigma]=\left[a_{1}^{\alpha_{1}} \ldots a_{n}^{\alpha_{n}}\right]
\]

$\alpha_{i} \in \Lambda_{i} \subseteq N_{0}=\{0,1, \ldots\}, \quad \Lambda=\left(\Lambda_{1}, \ldots, \Lambda_{n}\right)$,

имеет вид:

\[
\Phi\left(t ; x_{1}, \ldots, x_{n} ; \Lambda\right)=\prod_{j=1}^{n} \sum_{\alpha_{j} \in \Lambda_{j}}\left(t x_{j}\right)^{\alpha_{j}} .
\]

2. Неноммутативный несимметричны й с луч а й: $G=E, H=E$. Моделирует схемы размещений, заполнений различимых предметов в различные ячейки и др. Производящая функция для перечисления неәквивалентных конфигураций $\sigma$ таких, что

\[
[\sigma]=\left[a_{1}^{\alpha_{1}} \ldots a_{n}^{\alpha_{n}}\right], \alpha_{i} \in \Lambda_{i}, \Lambda=\left(\Lambda_{1}, \ldots, \Lambda_{n}\right),
\]

имеет вид:

\[
\tilde{\Phi}\left(t ; x_{1}, \ldots, x_{n} ; \Lambda\right)=\prod_{j=1}^{n} \sum_{\alpha_{j} \in \Lambda_{j}} \frac{t^{\alpha_{j}}}{\alpha_{j} !} x_{j j}^{\alpha} .
\]

3. Коммутативный симмет ричный с л у ч а й: $G=S_{m}, H=S_{n}$. Моделирует схемы заполнения одинаковых предметов в одинаковые ячейки, перечисления разбиений натуральных чисел и др. Перечисление конфигураций $\sigma$ таких, что

\[
[[\sigma]]=\left[\left[0^{\beta_{01} \beta_{1}} \ldots m^{\beta_{m}}\right] \mid \cdot \beta_{j} \in \Lambda_{j}, \Lambda=\left(\Lambda_{1}, \Lambda_{2}, \ldots\right),\right.
\]

основано на использовании производящей функции вида:

\[
\Psi\left(t ; x_{1}, \ldots ; \Lambda\right)=\prod_{j=1}^{\infty} \sum_{\beta_{j} \in \Lambda_{j}}\left(x_{j} t^{j}\right)^{\beta} .
\]

4. Н е комм ут ат и вны й симметричный с л у ч а й: $G=E, H=S_{n}$. Моделирует схемы разбиений конечных множеств на блоки, заполнения разлпчимых предметов в одинаковые ячейки и др. Перечисление конфигураций $\sigma$ таких, что

\[
[[\sigma]]=\left[\left[0^{\beta_{01} \beta_{1}} \ldots m^{\beta} m\right], \beta_{j} \in \Lambda_{j}, \Lambda=\left(\Lambda_{1}, \Lambda_{2}, \ldots\right),\right.
\]

основано на использовании производящей функции вида:

\[
\tilde{\Psi}\left(t ; x_{1}, \ldots ; \Lambda\right)=\coprod_{j=1}^{\infty} \sum_{\beta_{j} \in \Lambda_{j}}\left(\frac{x_{j} t^{j}}{j !}\right)^{\beta_{j}} \frac{1}{\beta_{j} !} .
\]

Значительное место в $\mathcal{K}$. а. занимают асимптотические методы. Они применяются как для упрощения сложных конечных выражений при больших значениях входящих в них параметров, так и при получении приближенных формул обходными путями, когда точные формулы неизвестны. Комбинаторную задачу перечислительного характера иногда удобно сформулировать как задачу отыскания характеристик распределения нек-рой случайной величины. Такая интерпретация дает возможность применять развитый аппарат теории вероятностей, а для отыскания асимптотик - предельные теоремы. Детальному исследованию с этих позицій подвергнута классическая схема случайных размещений предметов в ячейки, случайные разбиения множеств, цикловая структура случайных подстановок, а также различные классы случайных графов, включая графы отображений (см. [8], [9]).

Вероятностный подход применяется при изучении комбинаторных свойств симметрических групп и полугрупп. Исследовано предельное распределение порядка случайного элемента симметрической группы $S_{n}$ при $n \rightarrow \infty$, а также асимптотика вероятности порождения ее случайными элементами. Для нек-рых классов случайных неотрицательных матриц изучались распределения числа нулевых линий в матрице и перманентов, даны оценки вероятности примитивности таких матриц. Для доказательства существования комбинаторных конфигураций без их конструирования иногда используется нек-рый специфический вероятностный прием. Сущность этого приема заключается в установлении существования конфигурации без ее конструирования с помощью оценки вероятности нек-рого события (см. [7]).

Лит.: [1] Р и о р д а н П ж., Введение в комбинаторный анализ, пер. с англ., М., 1963; [2] Р а й з е p Г.-Д ж., Комбинаторная математика, пер. с англ., M., 1966 ; [3] Х о л л M.,
Комбинаторика, пер. с англ., М., 1970; [4] Прикладная комбиКомбинаторика, пер. с англ., М., 1970; [4] Прикладная комби-
наторная математика, сб. статей, пер. с англ., M. 1968; [5] X а p a p и Ф., Теория графов, пер. с англ., М., 1973; [6] X ap a p и Ф. П а л м е p Э., Перечисление графов, пер. с англ., методы в комбинаторике, пер. с англ., М., 1976; [8] К о л ч и н В. Ф., Ч и с т я к о в В. П., В кн.: Итоги науки и техники. Теория вероятностей. Математическая статистика. Тео-
ретическая кибернетика, т. 11, М., 1974, с. $5-45 ;$ [9] С а чретическая кибернетика, т. 11, М., 1974, с. 5-45; [9] С a ч-
к о в В. Н., в кн.: Вопросы кибернетики. Тр. семинара по комбинаторной математике, М., 1973, с. 146-64; [10] е г о ж е, Комбинаторные методы дискретной математики, М., 1977.'

КОМИТАНТ, к о н к о ми т ан т, группы $G$, действующей на множествах $X$ и $Y$,- такое отображение $\varphi: X \rightarrow Y$, что

\[
g(\varphi(x))=\varphi(g(x))
\]

для любых $g \in G, x \in X$. В әтом случае говорят также, что $\varphi$ коммутирует с действием $G$, или, что $\varphi-$ ә к в ив а р и а тное отоб р а е ни е. Если $G$ действует на каждом множестве семейства $\left\{X_{i}, i \in I\right\}$, то $\mathrm{K}$. $\prod_{i \in I} X_{i} \rightarrow Y$ наз. с о в ме с т н ы м (или о д н о в р емен ным) К. группы $G$.

Понятие К. происходит из классической инвариантов теории, в к-рой, однако, К. понимается в более узком смысле: $G$ - полная линейная группа нек-рого конечномерного линейного пространства $U, X$ и $Y-$ пространства тензоров на $U$ определенного (вообще говоря, различного) типа, на к-рых $G$ действует естественным образом, а $\varphi$ - эквивариантное полиномиальное отображение $X$ в $Y$. Если, кроме того, $Y$ есть пространство ковариантных тензоров, то К. наз. к ов а р и а н т о м группы $G$, а если $Y$ - пространство контравариантных тензоров, то К. наз. ко н т р а в ари ан т ом группы $G$.

П р и ме р. Пусть $f$ - бинарная кубическая форма от переменных $x$ in $y$ :

\[
f=a_{0} x^{3}+3 a_{1} x^{2} y+3 a_{2} x y^{2}+a_{3} y^{3}
\]

Ее коэффициенты являются координатами ковариаптного симметрического тензора. Коэфффициенты гессиана формы $f$, т. е. формы

\[
\begin{gathered}
H=\frac{1}{36}\left|\begin{array}{cc}
\frac{\partial^{2} f}{\partial x^{2}} & \frac{\partial^{2} f}{\partial x \partial y} \\
\frac{\partial^{2} f}{\partial x \partial y} & \frac{\partial^{2} f}{\partial y^{2}}
\end{array}\right|= \\
=\left(a_{0} a_{2}-a_{1}^{2}\right) x^{2}+\left(a_{0} a_{3}-a_{1} a_{2}\right) x y+\left(a_{1} a_{3}-a_{2}^{2}\right) y^{2}
\end{gathered}
\]

также являются координатами ковариантного симметрического тензора и отображение

\[
\left(a_{0}, a_{1}, a_{2}, a_{3}\right) \longmapsto\left(a_{0} a_{2}-a_{1}^{2}, \frac{1}{2}\left(a_{0} a_{3}-a_{1} a_{2}\right), a_{1} a_{3}-a_{2}^{2}\right)
\]

соответствующих пространств тензоров есть К. (так наз. К. формы $f$ ). Аналогично можно определить гессиан произвольной формы, к-рый также дает пример К. (см. Ковариант).

В современной геометрич. теории инвариантов под $\mathrm{K}$. часто понимают любой эквивариантный морфизм $X \rightarrow Y$, где $X$ и $Y$ - алгебраич. многообразия, снабженные регулярным действием алгебраич. группы $G$. Если $X$ и $Y$ аффинны, то $К$. определяет гомоморфизм (и сам определяется им) $k[Y] \rightarrow k[X] G$-модулей регулярных функций на многообразиях $Y$ и $X$ соответственно ( $k$ - основное поле).