$a<0$ и $a^{\prime}=-a$, то нижнее $a_{n}$ и верхнее $\overline{a_{n}}$ Д. п. порядка $n$ числа $a$ определяются равенствами

\[
\underline{a_{n}}=-\bar{a}_{n}^{\prime}, \quad \bar{a}_{n}=-\underline{u}_{n}^{\prime} .
\]

Для Д. п. действительного числа выполняются следующие соотношения:

\[
\begin{gathered}
\underline{a}_{n} \leqslant \underline{a}_{n+1} \leqslant a \leqslant \bar{a}_{n+1} \leqslant \bar{a}_{n}, \\
\bar{a}_{n}-\underline{a}_{n}=10^{-n} .
\end{gathered}
\]

Из них следует, что

\[
\lim _{n \rightarrow \infty}\left(\underline{a}_{n} \pm \underline{b}_{n}\right)=a \pm b, \quad \lim _{n \rightarrow \infty} a_{n} \underline{b}_{n}=a b
\]

a если $b \neq 0$, то $\lim _{n \rightarrow \infty} \underline{a}_{n} / \underline{b}_{n}=a / b$, при әтом вместо нижних Д. п. можно брать верхние.

Д. П. используются на практике для приближенных вычислений. В качестве приближенных значений сумм $a+b$, разностей $a-b$, произведений $a b$ и частных $a / b$ берутся, соответственно, $\underline{a}_{n}+\underline{b}_{n}, \underline{a}_{n}-\underline{b}_{n}, \quad\left(\underline{a}_{n} \underline{b}_{n}\right)_{n}$ и $\left(a_{n} / b_{n}\right)_{n}$. В результате указанных действий вадд конечными десятичными дробями $\underline{a}_{n}$ и $\underline{b}_{n}$, имеющими не более $n$ значащих цифр после зачятой, получаются снова десятичные дроби с не более чем $n$ значащими цифрами после запятой. С помощью этих дробей искомый результат можно получить с любой степенью точности. Л. Д. Кудрявчев. ДЕТЕРМИНАНТ - то же, что определитель.

ДЕТЕРМИНАНТНОЕ МНОГООБРАЗИЕ - мНоЖествО матриц $D_{t}(d, n)$ порядка $d \times n$ и ранга меньше $t$, снабженное структурой алгебраич. многообразия. Пусть $J_{t}(d, n)$ - идеал кольца многочленов

\[
k\left[\begin{array}{rl}
\left(T_{i j}\right)_{1} & \leqslant i \leqslant d \\
1 & \leqslant i \leqslant n
\end{array}\right]
\]

с коэффициентами в поле $k$, порожденный минорами порядка $t$ матрицы порядка $d \times n$, составленной из переменных $T_{i j}$ (д е т е р м и нан т ны й и д е а л). Множество нулей идеала $J_{t}(d, n)$ в аффинном пространстве $A^{d n}=\operatorname{Spec}\left(k\left[\left(T_{i j}\right)\right]\right)$ наз. де т е р м и на нтным мн ого о б р а з и е м и обозначается $D_{t}(d, n)$. Для любой коммутативной $k$-алгебры $k^{\prime}$ множество $k^{\prime}$-точек Д. м. $D_{t}(d, n)$ естественным образом отождествляется с множеством матриц порядка $d \times n$ и ранга $<t$ с коәффициентами в $k^{\prime}$.

Частные случаи Д. м.: $D_{d}(d, d)$ есть гиперповерхность в $A^{d^{2}}$, задаваемая обращением в нуль определителя квадратной матрицы порядка $d$, составленной из независимых переменных (д е т е р м и н а н т н а я г и п е р п о в е р х нос т ь); $D_{2}(d, n)$ есть аффинный конус для образа вложения Сегре

\[
P^{d-1} \times P^{n-1} \longrightarrow P^{d n-1}
\]

произведения проективных пространств [2].

Д. м. обладают следующими свойствами: $D_{t}(d, n)$ неприводимо, приведено (т. е. идеал $J_{t}(d, n)$ прост), является многообразием Коэна - Маколея (см. Коэна Маколея кольчо), нормально, и размерность $D_{t}(d, n)$ равна $(t-1)(n+d-1)$ (см. [1], [2]). Прй $t=1$ или $d=n$ (и только в этих случаях) $D_{t}(d, n)$ является схемой Горенштейва (см. Горенштейна кольцо) [5]. Д. м. тесно связаны с подмногообразиями Шуберта грассманова многообразия (см. III уберта многообразие).

Jum.: [1] H o c h s t e r M., E a g o n J., "Amer. J. Math.", 1971 , v. 93, № 4, p. 1020-58; '[2] K l e i m a n S., L a n d o lf i J., "Compositio math.", 1971, v. 23, p. $407-34 ;$ [3] L a k s o v
D., "Comp. math.", 1975, v. 30, p. $273-92 ;[4]$ M u i l i C., "J. Indian Math. Soc.", 1974, v. 38, p. 131-45; [5] S v a n e s T., "Advances Math.", 1974, v. 14, p. 369-453. И. В. Долаачев.

ДЕФЕКТ, д е ф е т то е ч и с л о о п е р а т ор a,- pазмерность $\operatorname{dim} D_{\lambda}$ дебектного подпространства линейного оператора. Иногда, в более широком смысле,

![](https://cdn.mathpix.com/cropped/2023_07_08_173b595f29e04aa093c8g-1.jpg?height=39&width=834&top_left_y=221&top_left_x=987)
гильбертова пространства наз. размерность ортогонального дополнения этого многообразия. В. И. Соболев.

ДЕФЕКТ т р е у г о л ь н и к а - недостаток до двух прямых углов суммы внутренних углов треугольника на плоскости Лобачевского. Д. треугольника пропорционален площади треугольника. Максимальное значение Д. треугольника равно двум прямым углам, когда все вершины треугольника являются бесконечно удаленными точками.

А. Б. Иванов

ДЕФЕКТНОЕ ЗНАЧЕНИЕ м е р о мо р ф н о й ф у н к ц и и $f$ - комплексное число $a$ (конечное или бесконечное), дөфект к-рого (см. ниже) $\delta(a, f)$ положителен. Функция $f$ определена в круге $|z|<R \leqslant \infty$ комплексной плоскости $\mathbb{C}$. Д е ф е т значения $a:$

\[
\delta(a, f)=1-\varlimsup_{r \rightarrow R} \frac{N(r, a, f)}{T(r, f)},
\]

где $T(r, f)-\mathbf{x}$ а р а к т е р и с т и ч е ск а я ф у нкция Н е в а н ли н ны, отражающая рост $f$ при $r \rightarrow R$, и

\[
N(r, a, f)=\int_{0}^{r}[n(t, a)-n(0, a)] d \ln t+n(0, a) \ln r
\]

- считающая функция; здесь $n(t, a)$ - число репений уравнения $f(z)=a$ в круге $|z| \leqslant t$ (с учетом кратностей). Если $T(r) \rightarrow \infty$ при $r \rightarrow R$, то $0 \leqslant \delta(a, f) \leqslant 1$ для всех $a \in \mathbb{C} \cup\{\infty\}$. Если $f(z) \neq a$ ни для какого $z$, то $\delta(a, f)=1$ п $a$ есть Д. з.; это равенство возможно и в более общем случае (напр., $f(z)=z e^{z}, R=\infty$ и $\boldsymbol{a}=0$ ).

Если

\[
\overline{\lim } \frac{T(r, f)}{\ln (1 /(R-r))}=\infty
\]

(или $f \not \neq$ const мероморфна во всей плоскости), то $\sum_{a} \delta(a, f) \leqslant 2($ с о о т но шा е ни е д е ф е к т о в $)$, и число Д. з. для такой $f$ не более чем счетно. В остальном множество Д. з. может быть произвольным; напр., для любых последовательностей $\left\{a_{v}\right\} \subset \mathbb{C}$ и $\left\{\delta_{v}\right\} \subset \mathbb{R}+$, $\sum_{v} \delta_{v} \leqslant 1$, найдется целая функция $f$ такая, что $\delta\left(a_{v}, f\right)=\delta_{v}$ для всех $v$ и других Д. з. у $f$ нет. Ограничения на рост $f$ влекут за собой ограничения на Д. з. и их дефекты. Напр., мероморфная функция нулевого порядка или целая функция порядка $<1 / 2$ не могут иметь более одного Д. $\mathbf{3}$.

Число

\[
\Delta(a, f)=1-\lim _{r \rightarrow \infty} \frac{N(r, a, f)}{T(r, f)}
\]

$(f$ мероморфіна в $\mathbb{C})$ наз. д е ф е к т о м в с м ы с л е В а л и р о на. Множество чисел $a$, для к-рых $\Delta(a, f)>0$, может иметь мощность континуума, но всегда имеет нулевую логариф্фич. емкость.

См. также Исключительное значение, Распределения значений теория.

Лum.: [1] Н е в а н ли н н а $\mathbf{P}$. Однозначные аналитические функции, пер. с нем., М.-Л., 1941; [2] Х е ей м а н У.,

![](https://cdn.mathpix.com/cropped/2023_07_08_173b595f29e04aa093c8g-1.jpg?height=67&width=834&top_left_y=1894&top_left_x=987)
ДЕФЕКТНОЕ ФОДПРОС'ТРАНСТВО о п. е р а т ор а - ортогональное дополнение $D \lambda$ области значений $T_{\lambda}=\left\{y=(A-\lambda I) x, x \in D_{A}\right\}$ оператора $A_{\lambda}=A-\lambda I$, где $A$ - линейный оператор, определенный на линейном многообразии $D_{A}$ гильбертова пространства $H$, a $\lambda-$ регулярное значение (регулярная точка) оператора $A$. При этом под ре гуля р ным зн а ч ен и е м о п е р а т о р а $A$ понимается такое значение параметpa $\lambda$, при к-ром уравнение $(A-\lambda I) x=y$ имеет единственное решение для любого $y$, а оператор $(A-\lambda I)^{-1}$ ограничен, т. е. резольвента оператора $A$ ограничена. При изменении $\lambda$ Д. п. $D \lambda$ меняется, но его размер-