В 1939 К. Гёдель (К. Gödel) установил недоказуемость отрпцанпя обобщенной К.-г. (а следовательно, II недоказуемость отрицания К.-г.) в системе $\mathrm{ZF}$ с аксиомой выбора (системе ZFC), в предположении, что $\mathrm{ZF}$ непротиворечива (см. Конструктивное по Гёделю множество) . В 1963 П. Коэн (P. Cohen) показал невыводимость К.-г. (а следовательно, и невыводимость обобщенной К.-г.) из аксиом ZFC при условии непротіворечівості $\mathrm{ZF}$ (см. Вынуждения метод).

Являются ли эти результаты окончательными в проблеме континуума? Ответ на этот вопрос зависит от отношения к посылке о непротиворечивости $\mathrm{ZF}$ и, что более существенно, к тому экспериментальному факту, что всякое содержательное математич. доказательство (традиционной классич. математіки), после того как оно найдено, может быть адекватным образом формализовано в системе ZFC. Факт этот нельзя не только доказать, но даже точно сформулировать, поскольку всякое уточненше поднимает аналогичный вопрос об адекватности уточнения уточняемому.

На теоретико-модельном языке К. Гёдель и П. Коэн построили моделі для ZFC, в к-рых

\[
2^{k}=\left\{\begin{array}{l}
m, \text { если } k<m, \\
k^{+}, \text {если } k \geqslant m,
\end{array}\right.
\]

где $m$ - пропзвольный, наперед заданный несчетный регулярный кардинал, а $k^{+}$- первое кардинальное число, большее $k$. Каково возможное поведение функции $2^{k}$ в различных моделях ZFC?

Известно, что на регулярных кардиналах $k$ функция эта может вести себя как угодно, подчиняясь лишь условиям

\[
k \leqslant k^{\prime} \longrightarrow 2^{k} \leqslant 2^{k^{\prime}}, \quad k<c f\left(2^{k}\right),
\]

где $c f(m)$ - напменьший кардинал конфинальный $m$ (см. Кардинальное число). Для сингулярных (т. е. не регулярных) $k$ значение функции $2^{k}$ может зависеть от ее поведения на меньших кардинальных числах. Так, напр., если равенство (1) имеет место для всех $\alpha<\omega_{1}$, то оно имеет место и для $\alpha=\omega_{1}$.

Iит.: [1] К о ә н П. Д ж., Теория множеств и континуумгипотеза, пер. с англ., М., $1969 ;$ [2] B a u m g a r t n e r J. E., P r i k r y K., "Amer. Math. Monthly», 1977, v. 84, № 2, p. 108-
113. КОНТОРОВИЧА - ЛЕБЕДЕВА ПРЕОБРАЗОВАНИЕ - иІтегральное преобразование вида

\[
F(\tau)=\int_{0}^{\infty} K_{i \tau}(x) f(x) d x
\]

где $K_{v}(x)$ - Макдональда функция.

Если функция $f(x)$ имеет ограниченное пзменение в окрестності точкі $x=x_{0}>0$ II

\[
f(x) \ln x \in L\left(0, \frac{1}{2}\right), f(x) \sqrt{x} \in L\left(\frac{1}{2}, \infty\right),
\]

то справедлива формула обращения

\[
\begin{gathered}
\frac{f\left(x_{0}+0\right)+f\left(x_{0}-0\right)}{2}= \\
=\frac{2}{\pi^{2} x_{0}} \int_{0}^{\infty} K_{i \tau}\left(x_{0}\right) \tau \operatorname{sh} \pi \tau F(\tau) d \tau .
\end{gathered}
\]

Пусть $f_{i}(x), \quad i=1,2,-$ действительные функции, прічем

\[
f_{i}(x) x^{-3 / 4} \in L(0, \infty), f_{i}(x) \in L_{2}(0, \infty) ;
\]

\[
F_{i}(\tau)=\int_{0}^{\infty} \frac{\sqrt{2 \tau \operatorname{sh} \pi \tau}}{\pi} \frac{K_{i \tau}(x)}{\sqrt{x}} f_{i}(x) d x .
\]

Тогда

\[
\int_{0}^{\infty} F_{1}(\tau) F_{2}(\tau) d \tau=\int_{0}^{\infty} f_{1}(x) f_{2}(x) d x
\]

(равенство Парсеваля). Конечное К.- Л. П. имеет вид

\[
\begin{gathered}
F(\tau)=\frac{2 \tau \operatorname{sh} \pi \tau}{\pi^{2}\left|I_{i \alpha}(\alpha)\right|^{2}} \times \\
\times \int_{0}^{\alpha}\left[K_{i \tau}(\alpha) I_{i \tau}(x)-I_{i \tau}(\alpha) K_{i \tau}(x)\right] f(x) \frac{d x}{x},
\end{gathered}
\]

$\tau>0, \quad I_{v}(x)$ - модифицированная функция Бесселя (см. [3]).

Исследование таких преобразований было начато М. И. Конторовичем и Н. Н. Лебедевым (см. [1], [2]). Jum.: [1] К о н т о р о в и ч м. И., Л е б е де в H. Н.,

![](https://cdn.mathpix.com/cropped/2023_07_08_e13f26e113f59176e715g-1.jpg?height=42&width=806&top_left_y=548&top_left_x=995)
с. 395-98; [3] у ф л я н д Я. С., Ю ш к о в а Е. А., там же,

![](https://cdn.mathpix.com/cropped/2023_07_08_e13f26e113f59176e715g-1.jpg?height=42&width=819&top_left_y=604&top_left_x=992)
к о в А. П., Интегральные преобразования и операционное

счисление, 2 изд., М., 1974. Ю. А.Брычков, А. П. Прудников. элемента векторного пространства $E$ в ситуации, когда наряду с $E$ рассматривается сопряженное ему пространство $E^{*}$. Элементы пространства $E^{*}$ наз. тогда ковариантными векторами. М. И. Войчеховский.

КОНТРАВАРИАНТНЫЙ ТЕНЗОР в а л е н т н ос т п $\quad r \geqslant 1$ - тензор типа $(r, 0)$, элемент тензорного произведения

\[
T^{r}(E)=E \otimes \ldots \otimes E
\]

$r$ экземпляров векторного пространства $E$ над полем $K$. Относительно операции сложения $K$. т. одной и той же валентности и умножения их на скаляр $\operatorname{Tr}(E)$ является векторным пространством над $K$. Пусть $E$ - конечномерно и пусть $e_{1}, \ldots, e_{n}-$ базис в $E$. Тогда размерность $\operatorname{Tr}^{r}(E)$ равна $n^{r}$; базис в $T^{r}(E)$ сөстоит из всевозможных $\kappa$. т. вида

\[
e_{i_{1}} \otimes \ldots \otimes e_{i_{r}}, \quad 1 \leqslant i_{1}, \ldots, i_{r} \leqslant n .
\]

Любой К. т. $t \in \operatorname{Tr}(E)$ представляется в виде

\[
t=t^{i_{1} \ldots i_{r}} e_{i_{1}} \otimes \ldots \otimes e_{i_{r}} .
\]

Числа $t^{i_{1} \ldots i_{r}}$ наз. к о о р д и на т а ми, или ко мп о н е н т а м и, К. т. $t$ относительно базиса $e_{1}, \ldots, e_{n}$ в $E$. При переходе в $E$ к новому базису по формулам

\[
e_{i^{\prime}}=a_{i}^{i}, e_{i}
\]

координаты К. т. $t$ пзменяются по так наз. контравариантному закону

\[
t^{i_{1}^{\prime} \ldots i_{r}^{\prime}}=b_{i_{1}}^{i_{1}^{\prime}} \ldots b_{i_{r}^{\prime}}^{i_{r}^{\prime}} t^{i_{1} \ldots i_{r}}, a_{i^{\prime}}^{i} b_{i}^{j^{\prime}}=\delta_{i^{\prime}}^{j^{\prime}}
\]

При валентности $r=1$ К. т. совпадает с вектором элементом пространства $E$; при $r \geqslant 2$ К. т. можно инвариантным образом связать с $r$-линейным отображением в $K$ прямого произведения

\[
E^{r^{*}}=E^{*} \times \ldots \times E^{*}
\]

$r$ экземпляров сопряженного к $E$ пространства $E^{*}$. Для этого достаточно принять за координаты If. т. $t$ значения $r$-линейного отображения $\tilde{t}$ на векторах $\left(e^{i_{1}}, \ldots, e^{i} r\right) \in E^{r *}\left(\right.$ где $e^{1}, \ldots, e^{n}-$ элементы базиса в $E^{*}$, сопряженного к $e_{1}, \ldots, e_{n}$, т. е. $\left.e^{i}\left(e_{j}\right)=\delta_{j}^{i}\right)$, и обратно; поэтому пногда $К$. т. сразу определяют как полилинейный функционал на $E^{r *}$ И. $X$. Сабитов,

КОНТРАГРЕДИЕНТНОЕ ПРЕДСТАВЛЕНИЕ К п ред с т а в ле ни ю $\varphi$ г р у п пы $G$ в ли нейн о п п о с т р а с с т е $V$ - представление $\varphi^{*}$ этой же группы $G$ в двойственном к $V$ пространстве $V^{*}$, определяемое правилом:

\[
\varphi^{*}(g)=\varphi\left(g^{-1}\right)^{*}
\]