те о рема кон е ч нос т II р a [1]: есліI $X$ - компактное комплексное пространство І $\mathscr{T}-$ когерентный аналитич. пучок на $X$, то пространства когомологий $H^{k}(X, \mathscr{F})$ конечномерны и отделимы для всех $k \geqslant 0$. Обобщение этой теоремы на случай выпукло-вогнутых пространств [2], [3] утверждает: есліг $X$ - сгльно ( $p, q)$-выпукло-вогнутое пространство (см. Псевдовыпуклость и псевдовогнутость) и हf - когерентный аналітігч. пучок на $X$, то $H^{k}(X, \mathcal{F})$ конечномерны прі $p \leqslant k \leqslant \operatorname{prof} \mathscr{T}-q-1$ и отделимы при $p \leqslant k \leqslant \operatorname{prof} \mathscr{F}-q$, a $H_{c}^{k}(X, \mathscr{F})$ конечномерны при $q+1 \leqslant$ $\leqslant k \leqslant$ prof $\mathcal{F}-p$ п отделимы прі $q+1 \leqslant k \leqslant \operatorname{prof} \mathscr{F}-p+1$.

K K. т. относят также обобџения указанных выше теорем на относітельный случаї, т. е. крітеріпі когерентності прямых образов когерентных аналігтич. пучков прıг аналитіч. отображеніях. Обобщением теоремы Кіартана - Серра является следующая т е о р е м а $\Gamma$ р а у ә р т а [4], [5]: если $\pi: X \rightarrow Y-$ собственное аналитич. отображенıе комплексных пространств и $F$ - когерентный аналітігч. пучок на $X$, то прямые образы $R^{k} \pi_{*} \mathcal{F}$ когерентны пріг всех $k \geqslant 0$. Это свойство оказывается II достаточным для собственностіг отображения л. Аналогічные К. т. доказаны для сільно $p$ выпуклых й сільно q-вогнутых отображений (см. [6]). Аналог теоремы Грауэрта доказан также для жестких аналитических пространств над полем с неархимедовым нормированием [7].

C K. т. тесно связаны теоремы об оценке степени трансцендентностіг поля мероморфных функций на разлічных классах комплексных пространств (см. Зигеля пеорема). Простым следствіем теоремы Грауэрта является следуюлцая т е о р м а Р е м м е р т а [4]: есліг $\pi: X \rightarrow Y$ - собственное аналітич. отображение комплексных пространств іI $Z$ - аналитічч. множество в $X$, то множество $\pi(Z)$ аналітично в $Y$. Эта теорема переносится І на случай жестких пространств [7].

Лum.: [1] C a r t a n H., S e r r e J.-P., "C. r. Acad. sci.",

![](https://cdn.mathpix.com/cropped/2023_07_08_43a9da4d46c1d7c8440bg-1.jpg?height=32&width=821&top_left_y=1274&top_left_x=125)
в кн.: Комплексные пространства, М., 1965, с. 105-89, пер. c франц.; [3] R a m i s J. P., "Ann. Scuola norm. super.' Pisa. Sci. fis. e mat.", 1973 , ser. 3 , t. "27, N 4, p. 933-97: [4] $\Gamma$ p a yр р т Г., в кн.: Комплексные пространства, М., 1965 , с. $205 \frac{1}{2}$

![](https://cdn.mathpix.com/cropped/2023_07_08_43a9da4d46c1d7c8440bg-1.jpg?height=42&width=831&top_left_y=1378&top_left_x=120)
algebrice in teoria globală a spaţilor complexe, Buc., 1974; [6i] Итоги науки. Алгебра. Топология. Геометрия, т. 15 , M., $197 \overline{1}$, c. 93-171; [7] K i e h l R., "Invent. math.", 1967 , Bd 2 , КОНЕЧНОСТРОЧНЫИ МЕТОД СУММИРОВАНИЯ - матричный метод суммирования, определенный конечнострочной матрıцей - матрıцей, каждая строка к-рой содержит только конечное число отличных от нуля элементов. Важным частным случаем IR. м. с. являются треугольные методы су.ммирования.

Для любого регулярного матрічного метода суммирования последовательностей можно построить К. м. с. равносільныї и совместныї̈ (см. Включение методов суммирования іI Совместность методов суммирования) с нгм на множестве огрангченных последовательностей (см. [3]). Однако существуют регулярыы матричные методы суммированія, для к-рых нет равносильных ફ.. м. с. на множестве всех последовательностей (пример см. [4]).

лит.: [1] $\mathbf{x}$ а $\mathbf{p}$ д и Г., Расходящиеся ряды, пер. с англ., м., 1951 ; [2] К у к P., Бесконечные матрицы и пространства последовательностей, пер. с англ., М., 1960; [3] Б р у д н о А. Л., " i a n G., "Proc. Amer. Math. Soc.", 1950, v. 1, p. 397-401.

КОНЕЧНЫХ ПРИРАЩЕНИЙ ФОРМУЛА, Ф 0 рм у ла к о н е ч ны ж а,- формула, выражающая пргращение функции через значение пропзводной в промежуточной точке. ЕслIг функция $f$ непрерывна на отрезке $[a, b]$ числовой оси І диффференцируема в его внутренних точках, тогда

\[
f(b)-f(a)=f^{\prime}(\xi)(b-a), \quad a<\xi<b .
\]

F. п. ф. записывают также в виде

\[
f(x+\Delta x)-f(x)=f^{\prime}(x+\theta \Delta x) \Delta x, \quad a<\theta<1 .
\]

Геометрич. смысл К. П. ф.: для хорды графика функциІ $f$ с концамі в точках $(a, f(a)),(b, f(b))$ существует такая точка $\xi, a<\xi<b$, что касательная к графику функциІ в точке $(\xi, f(\xi))$ параллельна указанной хорде (см. pic.).

K. п. ф. обобщается на функцігі многих переменных: если функция $f$ діфференцируема в каждой точке вы-

![](https://cdn.mathpix.com/cropped/2023_07_08_43a9da4d46c1d7c8440bg-1.jpg?height=486&width=541&top_left_y=496&top_left_x=1131)

пуклої областіг $G$-мерного евклидова пространства, то для каждой пары точек $x=\left(x_{1}, \ldots, x_{n}\right) \in G, x+\Delta x=$ $=\left(x_{1}+\Delta x_{1}, \ldots, x_{n}+\Delta x_{n}\right) \in G$ существует такая точка $\xi=\left(\xi_{1}, \ldots, \xi_{n}\right)$, лежащая на отрезке с концами в точках $x$ II $x+\Delta x$, что

\[
f(x+\Delta x)-f(x)=\sum_{i=1}^{n} \frac{\partial f(\xi)}{\partial x_{i}} \Delta x_{i}
\]

Л. Д. Кудрявчев.

КОНЕЧНЫХ РАЗНОСТЕИ ИСЧИСЛЕНИЕ - раЗдел математикі, в к-ром изучаются функции при дігскретном изменении аргумента, в отличие от діюфференциального и интегрального исчислений, где аргумент изменяется непрерывно. Пусть функция $y=f(x)$ задана в точках $x_{k}=x_{0}+k h(h-$ постоянная, $k-$ целое). Torдa

\[
\Delta y_{k}=\Delta f_{k}=f\left(x_{k+1}\right)-f\left(x_{k}\right)
\]

- (коне чны е) р а 3 ност пи первого по рядк $\mathbf{a}$,

$\Delta^{2} y_{k}=\Delta^{2} f_{k}=\Delta f_{k+1}-\Delta f_{k}=f\left(x_{k+2}\right)-2 f\left(x_{k+1}\right) \div f\left(x_{k}\right)$

- разност ї второго порядка, ...,

\[
\Delta^{n} y_{k}=\Delta^{n} f_{k}=\Delta^{n-1} f_{k+1}-\Delta^{n-1} f_{k}
\]

- р а з о с т и $n-\mathrm{r} о$ по р я д к а. Разностіг удобно располагать в таблицу:

\begin{tabular}{c|c|c|c|c|c}
\hline$x$ & $y$ & $\Delta y$ & $\Delta^{2} y$ & $\Delta^{3} y$ & $\cdots$ \\
\hline$x_{0}$ & $y_{0}$ & $\Delta y_{0}$ & & & \\
$x_{1}$ & $y_{1}$ & $\Delta y_{1}$ & $\Delta^{2} y_{0}$ & & \\
$x_{2}$ & $y_{2}$ & $\Delta y_{2}$ & $\Delta^{2} y_{1}$ & $\Delta^{3} y_{0}$ & \\
$x_{3}$ & $y_{3}$ & $\Delta y_{3}$ & $\Delta^{2} y_{2}$ & $\Delta^{3} y_{1}$ & \\
$x_{4}$ & $y_{4}$ & & & & \\
$\cdots$ & & & & & \\
\hline
\end{tabular}

Разность $n$-го порядка через величины $y_{0}, y_{1}, \ldots$ выражается формулой:

$\Delta^{n} y_{n}=y_{k+n}-C_{n}^{1} y_{k+n-1}+C_{n}^{2} y_{k+n-2}-\ldots+(-1)^{n} y_{k}$.

Наряду с р а зоостя м и п п ре д $\Delta y_{k}$ употребляются р а 3 н о с т и на $\mathbf{3}$ а д:

$\nabla y_{k}=f\left(x_{k}\right)-f\left(x_{k-1}\right)$.

А33 Математическая әнц., т. 2