группы $D(A) / F(A)=C(A)$ и $J(A) / F(A)=\operatorname{Pic}(A)$ наз. соответственно классов дивизоров әруппой и П икара әруппой кольца $A$.

Лит.: [1] В а н д е р В а р д е н Б. Л., Алгебра, пер. с нем., М., 1976: [2] Б у р б а к и Н., Коммутативная алгебра, пер. с франц., М., 1971. В. И. Данилов.

ДИЕЗНАЯ НОРМА в п р о с т р а н с т в е $r$-м е рных поли э д р а льных це пе й $C_{r}\left(E^{n}\right)-$ наибольшая из полунорм $|\cdot|^{\prime}$, удовлетворяющих для любой клетки $\sigma^{r}$ объема $|\sigma r|$ неравенствам:

\[
\begin{gathered}
\left|\sigma^{r}\right|^{\prime} \leqslant\left|\sigma^{r}\right|, \\
\left|\partial \sigma^{r+1}\right|^{\prime} \leqslant\left|\sigma^{r+1}\right|, \\
\left|T_{v} \sigma^{r}-\sigma^{r}\right|^{\prime} \leqslant \frac{\left|\sigma^{r}\right| v \mid}{r+1},
\end{gathered}
\]

где $T_{v} \sigma^{r}-$ клетка, полученная сдвигом на вектор $v$ длины $|v|$.

Если $A=\Sigma a_{i} \sigma_{i}^{r}$, то Д. н. $|A|^{*}$ выражается так:

\[
|A|^{\#}=\inf \left\{\frac{\sum\left|a_{i}\right|\left|\sigma_{i}^{r}\right|\left|v_{i}\right|}{r+1}+\left|\sum a_{i} T v_{i} \sigma_{i}^{r}\right|^{b}\right\} \text {, }
\]

где $|C|^{b}$ - бемольная норма цепи $C$.

Имеет место:

\[
\begin{gathered}
|\boldsymbol{a} A|^{\#}=|\boldsymbol{a}||\boldsymbol{A}|^{\#,}, \\
|A+B|^{\#} \leqslant|A|^{\#}+|B|^{\#}, \\
|A|^{\#}=0 \Leftrightarrow A=0, \\
|A|^{\#} \leqslant|A|^{b} ;
\end{gathered}
\]

если $r=0$, то $|A|^{\#}=|A|^{b}$.

Пополнение пространства $C_{r}\left(E^{n}\right)$ является сепарабельным банаховым пространством $C_{r}^{\#}\left(E^{n}\right)$, элементы к-роrо наз. $r$-мерными д и е з ны м и це п я м и. Для любой $r$-мерной полиэдральной цепи $A$ и любого вектора $v$ имеет место

\[
\left|T_{v} A-A\right|^{\#} \leqslant \frac{|A||v|}{r+1},
\]

где $T_{v} A$ - цепь, полученная сдвигом $A$ на вектор $v$

![](https://cdn.mathpix.com/cropped/2023_07_08_c08fcc45e358ea5ba739g-1.jpg?height=29&width=831&top_left_y=1464&top_left_x=120)
является диезной цепью; вообе любую бемольную цепь можно рассматривать и как диезную цепь в таком смысле: если $A=\lim ^{b} A_{i}$, где $A_{i}$ - полиэдральные цепи, и $\psi A=\lim ^{\#} A_{i}$, где $\psi-$ линейное биективное отображение пространства $C_{r}^{b}\left(E^{n}\right)$ в пространство $C_{r}^{\#}\left(E^{n}\right)$, и $\psi C_{r}^{b}$ плотно в $C_{r}^{\#}$ при Д. н.

Дать корректное определение границы $\partial A$ диезной цепи невозможно (см. [1], с. 242 , пример $(c)$ ); r-мерная д и е з н а я к о ц е п ь $X=X A$ есть элемент пространства $C^{\sharp r}\left(E^{n}\right)$, сопряженного к $C_{r}^{\#}\left(E^{n}\right)$, она является б е мо льн ой к о ц п п ю, причем

\[
|X| \leqslant|X| b \leqslant|X|^{\#}
\]

где $|X|$ - к о м а с с а $X$, а диезная конорма $|X|^{\#}$ определяется аналогично бемольной норме $|X|^{b}$. Кограница $d X$ диезной коцепи не обязана быть диезной ([1], с. 241 , пример $(a))$, однако

\[
|d X| \leqslant|X|^{b} \leqslant|X|^{\#} \text {. }
\]

If о н с т а н т а Л и пш и ц а $\mathscr{L}(X)$ коцепи $X$ определяется следующим образом:

\[
\mathscr{L}(X)=\sup \left\{\frac{\left|X \cdot\left(T_{v} A-A\right)\right|}{|A||v|}\right\}
\]

где $A$ - полиэдральные цепи. Для диезных коцепей эта верхняя грань конечна и

\[
(r+1) \mathscr{L}(X) \leqslant|X|^{\#} \text {. }
\]

Любая бемольная коцепь с конечной константой Липшица является диезной, причем

\[
|X|^{\#}=\sup \left\{|X|^{b},(r+1) \mathscr{L}(X)\right\}
\]

и, кроме того,

\[
|d X| \leqslant(r+1) \mathscr{L}(X) .
\]

Аналогичные понятия вводятся для $r$-мерных полиэдральных цепей в открытых подмножествах $R \subset E^{n}$. См. также Диезная форма.

Д и е з н а н о р м а в пространстве аддитивных функций $\gamma$, значениями к-рых являются $r-$ в е к т op ы, - наибольшая из полунорм $|\cdot|^{\prime}$, удовлетворяющих условиям:

$|\gamma|^{\prime} \leqslant|\gamma|$, где $|\gamma|$ - полная в а р и а ция $\gamma$;

\[
\left|T_{v} \gamma-\gamma\right|^{\prime} \leqslant \frac{|v||\gamma|}{r+1}
\]

где $T_{v} \gamma(Q)=\gamma T_{-v}(Q)-$ с д в и г функции $\gamma$ на вектор $v$ длины $|v|:$

\[
T_{-v}(Q)=\left\{q-v, q \in Q \subset E^{n}\right\}
\]

для каждой точки $p$ и любого $\varepsilon$ существует $\eta>0$ такое, что $|\gamma|^{\prime} \leqslant \varepsilon|\gamma|$, если носитель $\operatorname{sp} t \gamma \subset U_{\eta}(p)$ и $\gamma\left(E^{n}\right)=0$.

Д. н. $|\gamma|$ имеет представление

\[
|\gamma|^{\#}=\sup _{\omega} \int_{E^{n}} \omega d \gamma,
\]

где $\omega-r$-мерные диезные формы, для к-рых $\mid \omega^{\mid \sharp} \leqslant 1$.

Лит. см. при статье Бемолъная норма.

ДИЕЗНАЯ ФОРМА - r-мерная øорма $\omega$ в открытом подмножестве $R \subset E^{n}$ такая, что конечны комасса $|\omega|_{0}$ и к о м а с с о в а я ко н с т а н т а Л и п Ії и ц а

\[
\mathscr{L}_{0}(\omega)=\sup \frac{|\omega(p)-\omega(q)|}{|p-q|},
\]

где $p, q \in R$ и $|p-q|$ - длина вектора $p-q$. Д и е з н о й н $о \mathrm{p}$ м о й фо р м ы $\omega$ наз. число

\[
|\omega|^{\#}=\sup \left\{|\omega|_{0},(r+1) \mathscr{L}_{0}(\omega)\right\} \text {. }
\]

Т е о р е м а У и т н и. Каждой $r$-мерной д и е зн о й код е п и $X$ в $R$ соответствует единственная $r$-мерная Д. ф. $\omega_{X}$, для которой

\[
X \sigma^{r}=\int_{\sigma^{r}} \omega_{X}
\]

для всех $r$-мерных ориентированных симплексов $\sigma^{r}$; $\omega_{X}(p)$ определяется формулой

\[
\omega_{X}(p)=\lim \frac{X \sigma_{i}}{\left|\sigma_{i}\right|}
\]

где $\sigma_{1}, \sigma_{2}, \ldots-$ последовательность расположенных в одной и той же плоскости симплексов, содержащих точку $p$, диаметры к-рых $\rightarrow 0$. Это соответствие является взаимно однозначным линейным отображением пространства коцепей $C^{\# r}(R)$ в пространство $\Omega^{\# r}$ Д. ф., причем:

\[
\left|\omega_{X}\right|_{0}=|X|, \text { т. е. комассе } X
\]

$\mathscr{L}_{0}\left(\omega_{X}\right)=\mathscr{L}(X)$, т. е. константе Липшица $X$; $\left.\mid \omega_{X}\right)^{\#}=|X|^{\#}$, т. е. диезной норме $X$;

$\Omega^{\sharp r}$ является банаховым пространством.