если справедлива гипотеза Линделёфа, то

\[
N(\sigma, T)=O\left(T^{2(1-\sigma)+\varepsilon}\right) \text {. }
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_4b9d80b989d680856d96g-1.jpg?height=45&width=816&top_left_y=268&top_left_x=133)
$\sigma=1 / 2$. По гипотезе Римана, все нетривиальные нули Д.-ф. лежат на прямой $\sigma=1 / 2$. Тот факт, что на этой прямой Д.-ф. имеет бесконечно много нулей, впервые был доказан Х. Харди в 1914 (см. [4]) на основе ф о рму лы Р а мануд жа н а

\[
\int_{0}^{\infty} \frac{\Xi(t)}{t^{2}+\frac{1}{2}} \cos x t d t=\frac{\pi}{2}\left[e^{\frac{x}{2}}-e^{-\frac{x}{2}} \theta\left(e^{-2 x}\right)\right] .
\]

Последний результат принадлежит А. Сельбергу (A. Selberg, 1942; см. [4]): число $N_{0}(T)$ нулей $\zeta(s)$, имеющих вид $1 / 2+i t$, удовлетворяет неравенству

\[
N_{0}(T)>A T \ln T, A>0 .
\]

Это означает, что число нулей Д.-ф. на прямой $\sigma=1 / 2$ имеет тот же порядок роста, что и число всех ее нетривиальных нулей:

\[
N(T) \sim \frac{1}{2 \pi} T \ln T .
\]

Относительно нулей Д.-ф. на этой прямой известны и другого рода результаты. Приближенное функциональное уравнение позволяет фактически вычислить (с нек-рой степенью точности) значения ближайших к действительной оси нулей $\zeta(s)$. На основе этого метода на ЭВМ вычислены нули $\zeta(s)$ в прямоугольнике $0 \leqslant \sigma \leqslant 1,0 \leqslant t \leqslant 1,6 \cdot 10^{6}$. Их число равно $3,5 \cdot 10^{6}$, и все они лежат на прямой $\sigma=1 / 2$. Ординаты первых шести нулей с точностью до второго десятичного знака равны 14,$13 ; 21,02 ; 25,01 ; 30,42 ; 32,93 ; 37,58$.

Вообще, расстояние между соседними нулями $\zeta(s)$ оценивается т е о р е м о й Л и т л в у д а (1924): для любого достаточно большого $T$ функция $\zeta(s)$ имеет такой нуль $\beta+i \gamma$, что

\[
|\gamma-T|<A / \ln \ln \ln T \text {. }
\]

Обобщенная дзет а - у унция определяется для $0<a<1$ рядом

\[
\zeta(s, a)=\sum_{n=1}^{\infty}(n+a)^{-s} .
\]

При $a=1$ она обращается в дзета-функцию Римана. Аналитическое продолжение на всю плоскость осуществляется формулой

\[
\zeta(s, a)=\frac{e^{-\pi i s} \Gamma(1-s)}{2 \pi i} \int_{L} \frac{z^{s-1} e^{-a z}}{1-e^{-z}} d z,
\]

где интеграл берется по контуру $L$, представляющему собой путь из бесконечности по верхнему краю разреза положительной действительной оси до нек-рого фиксированного $0<r<2 \pi$, затем вдоль окружности радиуса $r$ против часовой стрелки и снова в бесконечность по нижнему краю разреза. Функция $\zeta(s, a)$ регулярна всюду, кроме точки $s=1$, где она имеет простой полюс с вычетом, равным 1. Она играет важную роль в теории L-функций Дирихле (см. [9], [10]).

Д з е т а - фу кци я Д е д е ки нд а - аналог дзета-функции Римана для полей алгебраич. чисел, введенный Р. Дедекиндом (см. [11]).

Пусть $K$ - поле алгебраических чисел степени $n=r_{1}+2 r_{2}>1$, где $r_{1}$ - число действительных, $r_{2}-$ число пар комплексно сопряженных полей в $k$; пусть далее $\Delta$ - дискриминант, $h$ - число классов дивизоров, $\boldsymbol{R}$-регулятор поля $k, g$ - число содержащихся в $k$ корней из 1.

Дзета-функция Дедекинда $\zeta_{k}(s)$ поля $k$ определяется рядом

\[
\zeta_{k}(s)=\sum_{\mathfrak{n}} \frac{1}{N \mathfrak{A}^{s}},
\]

где $\mathfrak{A}$ пробегает все целые отличные от нуля дивизоры поля $k, N \mathfrak{A}$ - норма дивизора $\mathfrak{U}$. Этот ряд абсолютно и равномерно сходится при $\sigma \geqslant 1+\delta, \delta>0$, определяя аналитич. функцию, регулярную в полуплоскости $\sigma>1$.

При $\sigma>1$ будет

\[
\zeta_{k}(s)=\sum_{m=1}^{\infty} \frac{f(m)}{m^{s}},
\]

где $f(m)$ - число целых дивизоров поля $k$ с нормой $m$, $f(m) \leqslant \tau_{n}(m), \tau_{n}(m)$ - число представлений $m$ в виде $n$ натуральных сомножителей.

При $\sigma>1$ имеет место тождество Эйлера

\[
\zeta_{k}(s)=\prod_{\Re}\left(1-\frac{1}{N \Re^{s}}\right)^{-1},
\]

где $\mathfrak{B}$ пробегает все простые дивизоры поля $k$.

О сновны е с в ой с т в а д 3 е т а-функции Д е д е к и н д а (см. [11]).

1) $\zeta_{k}(s)$ регулярна на всей комплексной плоскости, кроме точки $s=1$, где она имеет простой полюс с вычетом

\[
2 r_{1}+r_{2} \pi^{r_{2}} h R / g \sqrt{\Delta}
\]

2) $\zeta_{k}(s)$ удовлетворяет функциональному уравнению

\[
\xi_{k}(s)=\xi_{k}(1-s),
\]

где

\[
\xi_{k}(s)=\left(\frac{|\Delta|}{4^{r_{2}} \pi^{n}}\right)^{s} \Gamma^{r} 1\left(\frac{s}{2}\right) \Gamma^{r_{2}}(s) \zeta_{k}(s) .
\]

3) При $r=r_{1}+r_{2}-1>0$ в точке $s=0$ функция $\zeta_{k}(s)$ имеет нуль порядка $r ; \zeta_{k}(0) \neq 0$ при $r=0 ;$ в точках $s=-2 v, v=1,2, \ldots$, дзета-функция Дедекинда $\zeta_{k}(s)$ имеет нули порядка $r+1$, в точках $s=-2 v-1$ при $r_{2}>0$ - нули порядка $r_{2}$, а при $r_{2}=0$ не равна нулю. Это - тривиальные нули функции $\zeta_{k}(s)$.

4) Все остальные нули функции $\zeta_{k}(s)$ лежат в критич. полосе $0 \leqslant \sigma \leqslant 1$.

Основная гипотеза состоит в том, что все нетривиальные нули функции $\zeta_{k}(s)$ находятся на прямой $\sigma=1 / 2$. Установлено, что $\zeta_{k}(s)$ не имеет нулей на прямой $\sigma=1$. Более того, существует абсолютная положительная постоянная $A$ и зависящая от параметров поля $k$ постоянная $\lambda$, обладающие тем свойством, что

\[
\zeta_{k}(s) \neq 0 \text { при } \sigma \geqslant 1-\frac{A}{n \ln |t|},|t|>\lambda .
\]

Вообще, в случае фиксированных параметров поля $k$ для $\zeta_{k}(s)$ имеют место многие результаты, аналогичные результатам для дзета-функции Римана. Однако в общем случае теория дзета-функции Дедекинда сложнее, поскольку она включает в себя и теорию Дирихлө

![](https://cdn.mathpix.com/cropped/2023_07_08_4b9d80b989d680856d96g-1.jpg?height=32&width=826&top_left_y=1760&top_left_x=996)
функции Дедекинда действительные нули между 0 и 1. Точная зависимость между дзета-функцией Дедекинда и $L$-рядами рационального поля имеет следуюций вид. Пусть $k^{*}$ - минимальное поле Галуа, к-рому принадлежит $k, Q$ - группа Галуа поля $k^{*}, h$ - число классов группы $Q, \chi_{i}$ - простые характеры группы $Q$, $1 \leqslant i \leqslant h$. Тогда

\[
\zeta_{k}(s)=\zeta(s) \prod_{i=2}^{n} L^{c_{i}}\left(s ; \chi_{i}, k^{*}\right),
\]

где $\zeta(s)$ - дзета-функция Римана, $L$ суть $L$-ряды Артина, $c_{i}=c_{i}(k)$ - целые положительные числа, к-рые определяются свойствами относительной группы Галуа поля $k^{*}$. В частности, если $k$ - круговое расширение, то $k^{*}=k, h=\varphi(n), c_{i}=1$, и $L$-ряды Артина становятся обычыми $L$-рядами Дирихле.

Наряду с дзета-функцией Дедекинда $\zeta_{k}(s)$ рассмат-

![](https://cdn.mathpix.com/cropped/2023_07_08_4b9d80b989d680856d96g-1.jpg?height=37&width=831&top_left_y=2289&top_left_x=989)