существует, то $x \perp y$. Для Д. э. упрощается ряд структурных соотношений; напр., если $x \perp y$, то

\[
\begin{gathered}
|x+y|=|x|+|y| \\
(x+y) \wedge z=x \wedge z+y \wedge z
\end{gathered}
\]

для $z>0$, и т. д.

Понятие Д. э. может быть введено и в более общих частично упорядоченных множествах, напр. в булевых алгебрах.

Лum.: [1] К а н тор о в и ч Л. В., В у ли х Б. З., Пи нс к е р А. Г., Функциональный анализ в полуупорядоченных пространствах, М.-Ј., 1950; [2] В у л и х Б. З., Введение в теори полупорядоченных пространств, М., 1961; [3] Б у рс а к и Н., Интегрирование. Меры, интегрирование мер, пер.
с франц., М., 1967.
В. Соболев.

ДиЗЫЮНкцИЯ - логическая операция, служащая для образования высказывания « $A$ или $B$ » из высказываний $A$ и $B$. В формализованных языках Д. высказываний $A$ и $B$ обозначается посредством $A \vee B$. Высказывания $A$ и $B$ наз. д и з ью нк т и в ны ми чл е на м и высказывания $A \vee B$. Употреблению Д. в математич. логике соответствует следующая истинностная таблица:

\begin{tabular}{c|c|c}
$A$ & $B$ & $A \vee B$ \\
\hline$H$ & $И$ & $H$ \\
$H$ & $J$ & $H$ \\
$J$ & $U$ & $И$ \\
$J$ & $\boldsymbol{I}$ & $\boldsymbol{I}$ \\
\hline
\end{tabular}

ДИКАЯ СФЕРА - замкнутое многообразие в евклидовом пространстве $E^{3}$, получающееся диким вложением

![](https://cdn.mathpix.com/cropped/2023_07_08_dcfc0bf0e5ae711b2450g-1.jpg?height=295&width=338&top_left_y=994&top_left_x=136)

Рис. 1. сферы $S^{2}$ в $E^{3}$. Так, Д. с. является сумма двух дисков с общим краем, являющимся диким узлом. Первый пример Д. с. - так наз. "рогатая сфера", или с ф е р а А л е кс а нд е р а (рис. 1), - orpaничивает область, не гомеоморфнню $E^{3}$ (на рис. это внутренность цилиндра без всех зацепленных ручек и предельных точек к ним). На рис. 2 изображена Д. с., у к-рой только внешняя область не гомеоморфна $E^{3}$.

![](https://cdn.mathpix.com/cropped/2023_07_08_dcfc0bf0e5ae711b2450g-1.jpg?height=456&width=613&top_left_y=1407&top_left_x=229)

Рис. 2.

Лum.: [1] К е л д ы II Л. В., Топологические вложения в евклидово пространство, М., 1966 (Тр. Матем. ин-та АН СССР, $\begin{array}{ll}\text { т. 81). } & \text { M. И. Войцеховский, }\end{array}$

ДИКИХ УЗЕЛ - узел $L$ в евклидовом пространстве $E^{3}$ такой, что не существует гомеоморфизма $E^{3}$ на себя, при к-ром $L$ переходит в замкнутую ломаную линию, состоящую из конечного числа отрезков.

![](https://cdn.mathpix.com/cropped/2023_07_08_dcfc0bf0e5ae711b2450g-1.jpg?height=162&width=839&top_left_y=2117&top_left_x=119)

Рис. 1. Так, дикими являются узлы, содержащие так наз. д у г и Ф о к с а - А р т и н а - некоторые простые дуги, полученные диким вложением в $E^{3}$. Напр., для дуги $L_{1}$ (рис. 1) фундаментальная группа $\pi_{1}\left(E^{3} \backslash L\right)$ не-

![](https://cdn.mathpix.com/cropped/2023_07_08_dcfc0bf0e5ae711b2450g-1.jpg?height=184&width=824&top_left_y=317&top_left_x=990)

Pис. 2.

тривиальна, для дуги $L_{2}$ (рис. 2) группа $\pi_{1}\left(E^{3} \backslash L\right)$ тривиальна, но само $E^{3} \backslash L$ не гомеоморфно дополнению в $E^{3}$ к точке.

Лит. см. при ст. Дикая сфера. М. И. Войцеховский. ДИКОЕ ВЛОЖЕНИЕ топологического пространства $X$ в топологическое пространство $Y$ - вложение, к-рое топологически не эквивалентно вложению из нек-рого класса выделенных вложений, наз. п р а в и л ь н ы м и, или р учными, в л о ж е и я ми. Наиболее употребительными являются следующие случаи; в качестве $Y$ в них берется $n$-мерное евклидово пространстBo $\mathbb{R}^{n}$.

1) Пусть $M$ есть $k$-мерное топологич. многообразие. Топологич. вложение $g: M \rightarrow \mathbb{R}^{n}$ наз. д и к и м, если не существует гомеоморфизма $\mathbb{R}^{n}$ на себя, переводящего $g(M)$ в локально плоское подмногообразие $\mathbb{R}^{n}$.

2) Пусть $P$ есть $k$-мерный полиэдр. Топологич. вложение $g: P \rightarrow \mathbb{R}^{n}$ наз. д и к и м, если не существует гомеоморфизма $\mathbb{R}^{n}$ на себя, переводящего $g(\dot{P})$ в полиэдр (т. е. в тело нек-рой триангуляции) $\mathbb{R}^{n}$.

3) Пусть $K$ есть $k$-мерное локально компактное пространство. Топологич. вложение $g: K \rightarrow \mathbb{R}^{n}$ наз. д ик и м, если не существует гомеоморфизма $\mathbb{R}^{n}$ на себя, переводящего $g(K)$ в подмножество $k$-мерного Менгера компакта $M_{n}^{k}$.

Если размерность $k \leqslant n-3$ и $n \geqslant 5$, то введенные свойства во всех трех случаях характеризуются локально гомотопич. свойством: вложение является диким тогда и только тогда, когда $g(X)$ не удовлетворяет свойству 1-ULC (см. Tопология вложений). Положенге вещей для коразмерностей $n-k=1$ и 2 значительно сложнее: вопрос решен здесь для многообразий коразмерности 1 при $n \geqslant 6$ и не решен полностью для вложений коразмерности 2 как для многообразий, так и для полиэдров. Все сказанное имеет смысл и тогда, когда в качестве $Y$ берется $n$-мерное многообразие, топологическое или кусочно линейное. М. А. Штанъко.

ДиКсоНА ГРУППА - группа экспоненциальных автоморфизмов классической простой алгебры Ли типа $G_{2}$ над конечным полем $F$. Если порядок $F$ равен $q$, то порядок Д. г. равен $q^{6}\left(q^{2}-1\right)\left(q^{6}-1\right)$. При $q>2$ Д. г. является простой группой. Д. г. были открыты Л. Диксоном [1]. После этого в течение 50 лет не было найдено ни одной новой конечной простой группы, пока в 1955 К. IIIевалле (C. Chevalley) не указал общий способ получения простых групп как групп автоморфизмов простых алrебр Ли (см. [2]). Метод Шевалле позволяет получить, в частности, и Д. г. (см. [3]).

Лum.: [1] D i c k s o n L. E., "Math. Ann.", 1905, Bd 60, S. $137-50 ;$ [2] III е в а л л е K., "Математика", 1958, т. 2, 3-47. В-5, Д. Мазуров.

ДИКСОНА ИНВАРИАНТ - конструкция, используемая при изучении квадратичных форм над полями характеристики 2 , позволяющая, в частности, вводить аналоги специальной ортогональной группы над такими полями. А именно, Д. и. есть элемент $D(u)$ произволь-