непрерывная функция $F(x)$ на $[a, b]$, что ее annроксимативная производная почти всюду равна $f(x)$ и каково бы ни было совершенное множество $P$, существует порция $P$, на к-рой $F(x)$ абсолютно непрерывна; при этом

\[
\text { (D) } \int_{a}^{b} f(x) d x=F(b)-F(a) \text {. }
\]

Введен независимо и почти одновременно А. Данжуа [2] и А. Я. Хинчиным [3], [4]. Интеграл $D$ восстанавливает непрерывную функцию по ее точной конечной аппроксимативной производной.

3) Т о т а л и з а ц и я $\left(T_{2 s}\right)_{0}$ представляет собой конструктивно определенный интеграл для решения задачи построения такого обобщения интеграла Лебега, к-рое позволило бы всякий всюду сходящийся тригонометрич. ряд рассматривать в качестве ряда Фурье (по этому интегралу). Введена А. Данжуа [5].

4) Т о т а л и 3 а ц и я $\left(T_{2 s}\right)$ отличается от тотализации $\left(T_{2 s}\right)_{0}$ тем, что при определении тотализации $\left(T_{2 s}\right)_{0}$ обычный предел заменен на аппроксимативный. Для тотализации $\left(T_{2 s}\right)$ А. Данжуа [5] дал и дескриптивное определение.

О взаимосвязях тотализаций $\left(T_{2 s}\right)_{0}$ и $\left(T_{2 s}\right)$ с другими интегралами см. [6].

Jum.: [1] D e n jo y A., "C. r. Acad.sci.", 1912, t. 154, p.

![](https://cdn.mathpix.com/cropped/2023_07_08_407d899796794b0d39f4g-1.jpg?height=39&width=824&top_left_y=958&top_left_x=131)
$80 ;$ [3] K h i n t c h i n e А., там же, 1916, t. 162, p 287-91; De n j o y A., Lecons' sur le calcul' des coefficients d'une série trigonométrique, pt $1-4$, P., $1941-49 ;[6]$ В и н о г p а д о в a И. А., С к в о р ц о в В. А., в кн.: Итоги науки. Математический анализ. 1970, М., 1971, с. 65-107; [7] С а к с С., Теория
интеграла, пер. с англ., М., 1949.
Т. П. Лукашенко.

ДАНЖУ А ТЕОРЕМА о п р о и 3 в о д н Ы $\mathbf{x}$ ч и сл а х: производные числа каждой конечной функции $F(x)$ почти в каждой точке $x$ удовлетворяют одному из следующих соотношений:

\[
\begin{gathered}
\bar{F}+(x)=\bar{F}-(x)=+\infty, \quad \underline{F}+(x)=\underline{F}-(x)=-\infty ; \\
\bar{F}+(x)=\bar{F}-(x) \neq \infty, \quad \underline{F}+(x)=-\infty, \bar{F}-(x)=+\infty ; \\
F+(x)=\bar{F}-(x) \neq \infty, \bar{F}+(x)=+\infty, \quad \underline{F}-(x)=-\infty ; \\
\bar{F}+(x)=F+(x)=\bar{F}-(x)=\underline{F}-(x) \neq \infty .
\end{gathered}
\]

Доказана для непрерывных функций А. Данжуа [1]. Обобщением утверждения Данжуа является теорема [2]: для почти каждого $x$ контингенция графика $F(x)$ в точке $(x, F(x))$ является одной из следующих фигур: плоскость, полуплоскость (с невертикальной граничной прямой), прямая (невертикальная).

Jum.: [1] D e n J o y A., "J. math. pures et appl.», 1915, Ser. 7, t. 1, p. 105-240; [2] C а к с С., Теория интеграла, пер.
с англ., М., 1949.

ДАНЖУА - ЛУЗИНА ТЕОРЕМА об абсолютно сходящихся тригонометрич. рядах: если тригонометрич. ряд

\[
\frac{a_{0}}{2}+\sum_{n=1}^{\infty} a_{n} \cos n x+b_{n} \sin n x
\]

сходится на множестве положительной меры Лебега, то ряд, составленный из абсолютных величин его коэффицииентов

\[
\frac{\left|a_{0}\right|}{2}+\sum_{n=1}^{\infty}\left|a_{n}\right|+\left|b_{n}\right|
\]

сходится и, следовательно, исходный ряд (1) сходится абсолютно и равномерно на всей числовой оси. Свойство положительности меры множества сходимости ряда (1), будучи, согласно Д.- Л. т., цостаточным для сходимости ряда (2), не является, однако, необходимым. Существуют, напр., совершенные множества меры нуль, из сходимости на к-рых ряда (1) следует сходимость ряда (2). Теорема установлена независимо А. Данжуа [1] и Н. Н. Лузиным [2]; имеются различные ее обобщения (см. [3]).

Jum.: [1] D e n j o y A., "C. r. Acad. sci.", 1912, t. 155,

![](https://cdn.mathpix.com/cropped/2023_07_08_407d899796794b0d39f4g-1.jpg?height=55&width=821&top_left_y=300&top_left_x=994)
1961 .

ДАНИЕЛЯ ИНТЕГРАЛ - расширение понятия интеграла, предложенное П. Даниелем [1]. Схема построения этого интеграла наз. с х е м о й Д а н и е л я, представляет собой продолжение на более широкий класс функций интеграла, определенного первоначально для нек-рой совокупности функций, называемых элементарными функциями. При сохранении способа продолжения изменение объема исходной совокупности элементарных функций приводит $\kappa$ разным расширениям понятия интеграла. В этой схеме аксиоматизируется понятие элементарного интеграла, в отличие от схемы Лебега (см. Лебега интеграл), аксиоматизирующей понятие меры.

Пусть $X$ - произвольное множество и $L_{0}$ - некоторая совокупность определенных на $X$ действительных ограниченных функций; эти функции наз. э л е м е нт а р н ы и. Предполагается, что $L_{0}-$ в е к т о р н а я ре іш е тка, т. е. из $f, g \in L_{0}$ и $\alpha, \beta \in \mathbb{R} \Rightarrow \alpha f+\beta g \in L_{0}$,

\[
f, g \in L_{0} \Rightarrow \sup (f, g) \quad \text { и } \inf (f, g) \in L_{0} \text {. }
\]

Пусть на $L_{0}$ определен функционал $I(f)$, принимающий действительные значения и такой, что

\[
I(\alpha f+\beta g)=\alpha I(f)+\beta I(g) \text { (дистрибутивность); }
\]\[
f(x) \geqslant 0 \Rightarrow I(f) \geqslant 0 \text { (неотрицательность); }
\]

если $f_{n}(x) \downarrow 0$ для любого $x$, то $I\left(f_{n}\right) \rightarrow 0$ (непрерывность относительно монотонной сходимости).

Такой функционал наз. и н т е г р а л о м о т э л емент а рных ф ункций, или элеме н т а рны м и н т е г р а ло м. Множество $M \subset X$ наз. м н ож е с т в о м м е р ы н у л ь, если для любого $\varepsilon>0$ найдется такая неубывающая последовательность $\left\{g_{n}\right\} \subset L_{0}$, что $\sup _{n} g_{n}(x) \geqslant \chi_{M}(x)$, где $\chi_{M}(x)-$ характеристич. функция множества $M$ :

\[
\sup I\left(g_{n}\right) \leqslant \varepsilon .
\]

Функция $f(x)$, определенная на $X$, п р и на д л еж и т к л а с с у $L^{+}$, если существует такая последовательность $\left\{f_{n}\right\} \subset L_{0}$, что $f_{n}(x) \uparrow f(x)$ почти всюду и $I\left(f_{n}\right) \leqslant c<+\infty$. Число

\[
I(f)=\lim _{n} I\left(f_{n}\right)
\]

наз. и н т е г р а л о м о т $f$. Интеграл $I(f)$ не зависит от выбора аппроксимирующей последовательности $\left\{f_{n}\right\}$.

К л а с с о м $L$ наз. совокупность функций $f$, оПределенных на $X$ и представимых в виде $f=f_{1}-f_{2}$, где $f_{1}, f_{2} \in L^{+}$. Функции класса $L$ наз. с у м м и р уе м ы м и, а число

\[
I(f)=I\left(f_{1}\right)-I\left(f_{2}\right)
\]

-интег р а лом Даниеля от функции $f$.

Класс $L$ с точностью до множества меры нуль является векторной решеткой конечных функций, замкнутой относительно сходимости почти всюду с ограниченными интегралами, и Д. и. от суммируемых функций обладает свойствами дистрибутивности, неотрицательности, непрерывности (относительно сходимости почти всюду), мажорированной суммируемой функцией (теорема Лебега о переходе к пределу под знаком интеграла), а также рядом других естественных свойств интеграла.

В том случае, когда $X=[a, b]$ и $L_{0}$ есть совокупность ступенчатых функций

$f(x)=c_{i}, a_{i} \leqslant x<b_{i}, \quad \bigcup_{i=1}^{n}\left[a_{i}, b_{i}\right)=[a, b), b_{i}=a_{i+1}$,