где $C_{1}-$ абсолютная постоянная для $d \leqslant(\ln x)^{1-\nu}$ пр и нек-ром фиксировании $\gamma>0$ и $C_{1}=C_{1}(N)$ - «неәффективная» постоянная для $d \leqslant(\ln d)^{N}$ при любом фииксированном $N>1-\gamma$.

Эти результаты являются лучшими в проблеме равномерного распределения простых чисел в арифметич. прогрессиях растущей разности $d$. Для фиксированных значений $d$ известно несколько больше. В таком случае теория Д. $L-\not$. при $t \neq 0$ во многом аналогична теории дзета-функции Римана (см. [5]) и последняя граница нулей $L(s, \chi)$, полученная по Виноградова методу оценки тригонометрич. сумм, имеет вид:

\[
\begin{gathered}
L(s, \chi) \neq 0 \\
\text { для } \sigma>1-C / \ln ^{2 / 3}(|t|+2) \ln ^{1 / 3} \ln (|t|+2),
\end{gathered}
\]

где $C$ - положительная постоянная, зависящая от $d$.

Этой границе нетривиальных нулей Д. $L-ф$. фиксированного $\bmod d$ отвечает лучший (1977) остаточный член в асимптотич. формуле для $\psi(x ; d, l)$ в виде:

\[
\ll x \exp \left[-C \ln ^{3 / 5} x \mid \ln ^{1 / 5} \ln x\right] \text {. }
\]

Все формулы относительно асимптотики функции $\psi(x ; d, l)$ имеют аналоги для функции $\pi(x ; d, l)-$ числа простых чисел $p \leqslant x, p \equiv l(\bmod d)$, с главным членом li $x / \varphi(d)$ вместо $x / \varphi(d)$ и остаточным членом, меньшим на множитель $\ln x$.

К числу основных направлений исследований в современной теории Д. $L-\not$. относятся также исследования плотности распределения нетривиальных нулей Д. $L-ф$., содержание к-рых составляют оценки величин:

\[
\begin{gathered}
N(\sigma, T, \chi), \sum_{\chi \bmod d} N(\sigma, T, \chi), \\
\sum_{d \leqslant D} \sum_{\chi * \bmod d} N(\sigma, T, \chi),
\end{gathered}
\]

где $N(\sigma, T, \chi)$ обозначает число нулей $L(s, \chi)$ в прямоугольнике $0<\alpha \leqslant \sigma<1, \quad|t|<T, \quad \chi^{*}-$ примитивный характер $\bmod d$.

Лит.: [1] Д и р и х л е П. Г. Л., Лекции по теории чисел, пер. с нем., м.-Ј., 1936; [2] Д ә в е н п о р т Г., Мультипли-
кативная теория чисел, пер. с англ., М., 1971; [3] П р х х р кативная теория чисел, пер. с англ., М., 1971; [3] П р а х a p к., Распределение простых чисел, пер. с нем., М., 1967; [4]
ч у д а к о в Н.., Введение в теории L-функций Дирихле, M. J., 1947; [5] W a l f i s z A., Weylsche Exponentialsummen in der neueren Zahlentheorie, B., 1963; [6] M o н т г o M e p и $\Gamma$., Мультипликативная теория чисел, пер. с англ., 1974; [7] Л а в-
р и к А. Ф., «Матем. заметки», 1975, т. 17, в. 5, с. 809-17. ДИРИХЛЕ ХАРАКТЕР $(\bmod k)-$ функіия $\chi(n)=$ $=\chi(n ; k)$ на множестве целых чисел, удовлетворяющая условиям:

\[
\begin{gathered}
\chi(n) \neq 0, \\
\chi(n) \chi(l)=\chi(n l), \\
\chi(n)=\chi(n+k) .
\end{gathered}
\]

Иными словами, Д. х. $(\bmod k)$ - это арифмметич. функции, к-рые не равны тождественно нулю, вполне мультипликативны и периодичны с периодом $k$.

Понятие Д. х. ввел П. Дирихле (Р. Dirichlet, см. [1]) в связи с изучением закона распределения простых чисел в арифметич. прогрессиях. Он же разработал основы теории Д. х. (см. [2] - [8]), исходя из прямого конструктивного построения их.

Пусть

\[
k=2^{\alpha} p_{1}^{\alpha_{1}} \ldots p_{r}^{\alpha_{r}}
\]

- канонич. разложение $k, n$ - целое взаимно простое с $k,(n, k)=1 ; C=C_{0}=1$, если $\alpha=0$ или $\alpha=1 ; C=2$, $C_{0}=2^{\alpha-2}$, если $\alpha \geqslant 2 ; C_{1}=\varphi\left(p_{1}^{\alpha_{1}}\right), \ldots, C_{r}=\varphi\left(p_{r}^{\alpha_{r}}\right)$, где $\varphi$ - Функция Эйлера. Пусть, далее, $\gamma, \gamma_{0}, \gamma_{1}, \ldots, \gamma_{r}-$
система индексов числа $n$ по $\bmod k$, т. е. система наи- меньших неотрицательных целых чисел, удовлетворяющих сравнениям

![](https://cdn.mathpix.com/cropped/2023_07_08_ca7596eb44cbc8c74dfcg-1.jpg?height=57&width=797&top_left_y=254&top_left_x=986)
где $g_{j}$-наименьший первообразный корень по $\bmod p_{j}^{\alpha_{j}}$; $\varepsilon, \varepsilon_{0}, \varepsilon_{1}, \ldots, \varepsilon_{r}-$ система каких-либо корней из 1 соответственно порядков $C, C_{0}, C_{1}, \ldots, C_{r}$. Функция

![](https://cdn.mathpix.com/cropped/2023_07_08_ca7596eb44cbc8c74dfcg-1.jpg?height=95&width=586&top_left_y=434&top_left_x=1111)

определенная на множестве всех натуральных чисел, наз. х а р а к е р о м Ди ри х л $\mathrm{e}(\bmod k)$. Перебирая все возможные значения $\varepsilon, \varepsilon_{0}, \varepsilon_{1}, \ldots, \varepsilon_{r}$ получают

\[
\varphi\left(2^{\alpha}\right) \varphi\left(p_{1}^{\alpha_{1}}\right) \ldots \varphi\left(p_{r}^{\alpha_{r}}\right)=\varphi(k)
\]

различных функций $\chi-$ Д. х. $\bmod k$. Характер с $\varepsilon=\varepsilon_{0}=\varepsilon_{1}=\ldots=\varepsilon_{r}=1$ наз. г ла в ны м х а р а т ер о м; он обозначается $\chi_{0}$ :

\[
\chi_{0}(n)= \begin{cases}1, \text { если } & (n, k)=1, \\ 0, \text { если } & (n, k) \neq 1 .\end{cases}
\]

Для любых натуральных чисел $n, l$ и $k$ :

\[
\begin{gathered}
\chi(n) \chi(l)=\chi(n l) ; \\
\chi(n)=\chi(l), \text { если } n \equiv l(\bmod k) ; \\
\chi(1)=1, \\
\chi(n, k)=\chi\left(n ; 2^{\alpha}\right) \chi\left(n, p_{1}^{\alpha_{1}}\right) \ldots \chi\left(n ; p_{r}^{\alpha}\right) ;
\end{gathered}
\]

если $\chi(n)-$ Д. х. $(\bmod k)$, то комплексно сопряженная функция $\bar{\chi}(n)$ - также Д. х. $(\bmod k)$;

\[
\chi^{\varphi(k)}(n)=\chi_{0}(n)
\]

Наименьшее из чисел $v$, удовлетворяющее равенству $\chi^{v}(n)=\chi_{0}(n)$ наз. с т е п е н ь ю Д. х. Для $v=1$ существует один такой характер $\chi_{0} \cdot$ Если $v=2$, то $\chi(n)$ может принимать лишь значения 0 ; \pm 1 ; такие Д. х. наз. дей с тви те ль ным и, илик вад ратичными. Если $v \geqslant 3$, до Д. х. наз. к о м п л е к с н ы м. $\chi(n)$ наз. ч е т ным или не ч е т ным соответственно тому, будет $\chi(-1)=1$ или $\chi(-1)=-1$. Главные свойства сумм Д. х. выражаются формулами

\[
\begin{aligned}
& \sum_{n \bmod k} \chi(n)=\left\{\begin{array}{c}
\varphi(k), \text { если } \chi=\chi_{0}, \\
0, \text { если } \chi \neq \chi_{0} ;
\end{array}\right. \\
& \sum_{\chi \bmod k} \chi(l)=\left\{\begin{array}{c}
\varphi(k), \text { если } l \equiv 1(\bmod k), \\
0, \text { если } l \neq 1(\bmod k),
\end{array}\right.
\end{aligned}
\]

где в 1-й формуле $n$ пробегает полную систему вычетов $(\bmod k)$, а $\chi$ во 2-й формуле - все $\varphi(k)$ характеров $(\bmod k)$.

При $(l, k)=1$ справедлива формула $\frac{1}{\varphi(k)} \sum_{\chi \bmod k} \chi(n) \chi(l)=\left\{\begin{array}{l}1, \text { если } n \equiv l(\bmod k), \\ 0, \text { если } n \neq l(\bmod k),\end{array}\right.$

наз. с в о й с т в о м о р т огональнос т и Д. Она является одной из основных формул Д. х., применяемых в разного рода исследованиях арифметич. прогрессий: $k v+l, v=0,1,2, \ldots$ В теории и приложениях Д. х. важны также понятия ведущего модуля характера и примитивного характера. Пусть $\chi(n ; k)$ произвольный неглавный характер $(\bmod k)$. Если для значений $n$, удовлетворяющих условию $(n, k)=1$, число $k$ является наименьшим периодом $\chi(n ; k)$, то $k$ наз. в е д у щ и м, или о с н о вны м, мо д у ле м характера $\chi$, а сам характер $\chi-$ п р и м и т и в ным, или пе р в о о б р а з н ы м, характером $(\bmod k)$. В противном случае существуют единственные число