$k_{1}>1$, делящее $k, k_{1}<k$ и примитивный характер $\chi_{1}\left(\bmod k_{1}\right)$ такие, что

\[
\chi(n ; k)=\left\{\begin{array}{cl}
\chi_{1}\left(n ; k_{1}\right), & \text { если }(n, k)=1, \\
0, & \text { если }(n, k) \neq 1 .
\end{array}\right.
\]

В этом случае $\chi(n ; k)$ наз. н е п р и м и т и в ны м, или производным, ха ракте ром $\chi(\bmod d)$ и говорят, что $\chi_{1}$ индуцирует $\chi$. Тем самым многие вопросы о характерах сводятся к таковым для примитивных характеров.

Характер $\chi(n ; k)$ является примитивным тогда и только тогда, когда для любого $d$, делящего $k, d<k$, существует а с условиями:

\[
a \equiv 1(\bmod d), \quad \chi(a ; k) \neq 0 ; 1 .
\]

В аналитич. теории широко используются с ум м ы Г а у с с а, определяемые для $\chi(\bmod k)$ равенством

\[
\tau(\chi)=\sum_{m=1}^{k} \chi(m) e^{2 \pi i m / k}
\]

Для примитивного характера $\chi \bmod k$

\[
|\tau(\chi)|=k^{1 / 2}
\]

При этом справедливо разложение $\chi(n)$ в виде:

\[
\chi(n)=\frac{1}{\tau(\bar{\chi})} \sum_{m=1}^{k} \bar{\chi}(m) e^{2 \pi i n m / k} .
\]

Одной из основных проблем в теории Д. х. является проблема оценки сумм Д. х. $\chi(\bmod k), \chi \neq \chi_{0}$ :

\[
S(N ; M)=\sum_{M<n \leqslant N} \chi(n) .
\]

Имеет место о цен к а В и н о г р а д о в а:

\[
S(N ; M) \ll \sqrt{k} \ln k .
\]

Установлено [7], что

$S(N ; M) \ll k^{(r+1) / 4 r^{2}}(N-M)^{1-(1 / r)} \ln k, r=1,2, \ldots$,

$k$ - простое число. При $M=1, N=k / 2$ существует (см. [8]) бесконечная последовательность чисел $k$, являющихся модулями примитивного действительного характера $\chi$, для к-рой

\[
|S(N ; M)| \sim \frac{2 e \gamma}{\pi} \sqrt{k} \ln \ln k,
\]

$\gamma$ - Эйлера постоянная. Это асимптотич. равенство показывает, что предыдущие оценки, вообще говоря, существенно усилить нельзя. Однако существует г ипо те з а В и ноград о в а, согласно к-рой для любого $\varepsilon>0,1 \leqslant M<N$,

\[
|S(N ; M)| \ll k^{\varepsilon}(N-M)^{1 / 2} .
\]

Доказательство этой гипотезы позволило бы решить ряд крупных проблем теории чисел.

Теория Д. х. лежит в основе теории Дирихле L-функций и является частным случаем общей теории характеров абелевых групп.

Лит.: [1] Д и р и х л е П. Г. Л., Лекции по теории чисел, пер. с нем., М. Л., $1936 ;$ [2] В и н о г р а д о в И. М., Избр: тр., М., 1952; [3] К а p а ц у 6 a А. А., Основы аналитической теории чисел, М., $1975 ;$ [4] П р а х а p К., Распределение простых чисел, пер. с нем., М., 1967; [5] ч у д а ко в Н. Г., Введение в теорию L-функций Дирихле, М., 1947 ; [6] Д ә в е нПо р т Г., мультипликативная теория чисел, пер. с англ., M., 1971; [7] B u r ge s s D. A., "Tp. Матем. ин-та", 1973 ,

![](https://cdn.mathpix.com/cropped/2023_07_08_23e7bf431f18990a3050g-1.jpg?height=47&width=831&top_left_y=2110&top_left_x=118)

ДИРИХЛЕ ЯДРО - выражение

\[
D_{n}(x)=\frac{1}{2}+\sum_{k=1}^{n} \cos k x=\frac{\sin \left(n+\frac{1}{2}\right) x}{2 \sin \frac{x}{2}} .
\]

П. Дирихле [1] доказал, что частная сумма $S_{n}(x)$ ряда Фурье функции $f(x)$ выражается через Д. я.:

\[
\begin{aligned}
S_{n}(x) & =\frac{a_{0}}{2}+\sum_{k=1}^{n} a_{k} \cos k x+b_{k} \sin k x= \\
& =\frac{1}{\pi} \int_{-\pi}^{\pi} f(t) D_{n}(t-x) d t ;
\end{aligned}
\]

интеграл справа наз. с и н г у ля р н ы м ин т е г р ало м Д и р и х ле.

По аналогии с Д. я. (см. [3]) выражение

\[
\bar{D}_{n}(x)=\sum_{k=1}^{n} \sin k x=\frac{\cos \frac{x}{2}-\cos \left(n+\frac{1}{2}\right) x}{2 \sin \frac{x}{2}}
\]

наз. с о п р я же н ным ядром Ди рихле. Частная сумма ряда, сопряженного к ряду Фурье функции $f(x)$, выражается через сопряжен ное Д. я.:

\[
\begin{gathered}
\bar{S}_{n}(x)=\sum_{k=1}^{n} b_{k} \cos k x-a_{k} \sin k x= \\
=-\frac{1}{\pi} \int_{-\pi}^{\pi} f(t) \bar{D}_{n}(t-x) d t .
\end{gathered}
\]

Jum.: [1] D i r i c h l e t P., "J. für Math.", 1829, Bd 4, S. 157-69; [2] e r o w e, Werke, Bd 1, B., 1889; [3] T a ub e r A., "Monatsh. Math.", 1891, Bd 2, S. 79-118; [4] Б а p и
H. K., Тригонометрические ряды, М., 1961; [5] 3 и г м у н д А., Тригонометрические ряды, т. 1-2, пер. с англ., М., 1965 .

Т. П. Лукашенко.

ДИСК в т о п о л о г и и - поверхность, гомеоморфная кругу, т. е. ориентируемое двумерное многообразие рода 0 с одной компонентой края. Локально связный континуум без локально разбивающих точек в точности тогда гомеоморфен Д., когда любая окружность вне нек-рой точки этого континуума разбивает его и имеется окружность, к-рая его не разбивает. А. В. Чернавский.

ДИСКРЕПАНС последовательности точек $\omega=$ $=\left(x_{1}, \ldots, x_{N}\right)$ из единичного $s$-мерного куба $K_{s}=$ $=\left\{x: 0 \leqslant x_{v} \leqslant 1, v=\overline{1, s}\right\}-$ норма функціонала

\[
\varphi(\boldsymbol{\alpha}, \omega)=v-\frac{N(V)}{N}
\]

вычисленная в той или иной метрике. Здесь $v$ и $N(V)$ coответственно объем области $V=\left\{x: 0 \leqslant x_{v} \leqslant \alpha_{v} \leqslant 1\right.$, $v=\overline{1, s}\}$ и число точек последовательности $\omega$, принадлежащих области $V$. Если рассматривается распределение точек последовательности $\omega$ по областям вида $V=$ $=\left\{x: 0 \leqslant \alpha_{v} \leqslant x_{v} \leqslant \beta_{v} \leqslant 1, v=\overline{1, s}\right\}$, то в (1) принято вместо $\varphi(\boldsymbol{\alpha}, \omega)$ писать $\varphi(\boldsymbol{\alpha}, \boldsymbol{\beta}, \omega)$.

Наиболее употребительны нормы функционала (1):

\[
\begin{gathered}
D_{N}(\omega)=\sup _{\boldsymbol{\alpha} \in K_{s}, \boldsymbol{\beta} \in K_{s}}|\varphi(\boldsymbol{\alpha}, \boldsymbol{\beta}, \omega)|, \\
D_{N}^{*}(\omega)=\sup _{\boldsymbol{\alpha} \in K_{s}}|\varphi(\boldsymbol{\alpha}, \omega)|, \\
D_{N}\left(\omega, L_{p}\right)=\left(\int_{0}^{1} \cdots \int_{0}^{1}|\varphi(\boldsymbol{\alpha}, \omega)|^{p} d \alpha_{1}, \ldots, d \alpha_{s}\right)^{1 / p} .
\end{gathered}
\]

Последовательность точек $\omega=\left(x_{1}, \ldots, x_{N}, \ldots\right)$ из единичного $s$-мерного куба $K_{s}$ равномерно распределена тогда и только тогда, когда (см. [1]):

\[
\lim _{N \rightarrow \infty} D_{N}(\omega)=0
\]

Для любой бесконечной последовательности одномерных точек $\omega=\left\{x_{n}: 0 \leqslant x_{n} \leqslant 1, n=\overline{1, \infty}\right\}$ справедлива теорема (см. [3]):

\[
\varlimsup_{\lim } N D_{N}(\omega)=\infty
\]

А7 Математическая энц., т. 2