вовал интеграл $D(u)$, то вариационный метод применим лишь для таких функций $\varphi$, к-рые являются следамі на $\Gamma$ функций $F$, заданных в $\bar{D}$, и таких, что $D(F)$ существует и ограничен.

В методе потенциалов решение Д. з. ищется в виде потенциала двойного слоя с неизвестной плотностью, определенной на $Г$. При помощи формул скачка относительно этой плотности получается интегральное уравнение Фредгольма, из к-рого следует существование решения Д. з. с учетом того, что едінственность этого решения следует из принципа максимума. Предполагается, что $\Gamma \in A^{(1, \lambda)}$.

В альтернирующем методе Шварца рассматриваются две области $D_{1}$ и $D_{2}$ с непустым пересечением $D_{0}$ такие, что для $D_{1}$ и $D_{2}$ в отдельности известен способ реішения Д. З. Затем строится процесс, позволяющий найти решіение Д. 3. для области $D=D_{1} \bigcup D_{2}$. Границы $\Gamma_{1}$ и $\Gamma_{2}$ областей $D_{1}$ и $D_{2}$ предполагаются кусочно гладкими, причем во всех точках пересечения $\Gamma_{1}$ с $\Gamma_{2}$ как $\Gamma_{1}$, так и $\Gamma_{2}$ являются гладкими и пересекаются под ненулевым углом. Строятся последовательности регулярных в областях $D_{1}$ и $D_{2}$ гармонич. функций, удовлетворяющих специальным граничным условиям. Затем доказывается, что эти последовательности равномерно сходятся и в $D_{0}$ их пределы совпадают. Предельная гармонич. функция регулярна в $D$ и является искомым решением Д. з. Метод ІІварца можно применять для объединения или пересечения любого конечного числа областей.

Метод выметания в той форме, в к-рой он первоначально был введен А. Пуанкаре (H. Poincaré, 1890), применяется к таким областям, к-рые допускают исчерпание счетным множеством шаров. Исходным в этом методе является построение ньютонова потенциала, принимающего на границе $\Gamma$ заданные значения $\varphi$, а задача затем сводится к замене этого потенциала потенциалом масс, расположенных на $Г$, без изменения значений $\varphi$ на $\Gamma$, т. е. к выметанию масс. При помощи формулы Пуассона такой процесс выметания для шара $D$ легко осуществить в явном виде. Счетное число выметаний из шаров, объединение к-рых исчерпывает область $D$ общего вида, приводит к нек-рому потенциалу масс, расположенных на границе $\Gamma$, к-рый и дает решение Д. $з$.

Близким к методу выметания является Перрона метод (или метод верхних и нижних функций), применимый к областям $D$ весьма общего вида. В этом методе строятся последовательности верхних (супергармонических) и нижних (субгармонических) функций, общим пределом к-рых является искомое решение Д. з. Для того чтобы это решение принимало заданное значение в точке $Q \in \Gamma$, необходимо и достаточно существование локального барьера $\omega_{Q}$. Функция $\omega_{Q}$ непрерывна, супергармонична в пересечении $\bar{D} \cap \Sigma$ ( $\Sigma$ - шар с центром в точке $Q) ; \omega_{Q}>0$ всюду в $\bar{D} \cap \Sigma$, кроме точки $Q$, где она обращается в нуль.

Точки $\Gamma$, для к-рых существует локальный барьер, наз. регулярными точками. Если $\Gamma$ состоит только из регулярных точек, то полученное решение Д. з. непрерывно в $D$ и принимает заданные значения на $\Gamma$. Однако на $\Gamma$ могут существовать и иррегулярные точки. Напр., в $\mathbb{R}^{2}$ иррегулярными являются изолированные точки $\Gamma$, а в $\mathbb{R}^{3}$ иррегулярной будет вершина достаточно тонкого острия, входящего внутрь $D$. Наличие иррегулярных точек приводит к тому, что Д. з. не является разрешимой для всех непрерывных на $\Gamma$ функций $\varphi$, либо же решение является неустойчивым по отношению к изменению граничных данных (см. [6]).

Обобщенное решение Д. з., введенное Н. Винером (N. Wiener, 1924), удовлетворяет условиям: a) оно применимо для любых областей; б) оно приводит к классич. решению Д. з., если таковое существует. Пусть область $D$ - предел монотонно возрастающей последовательности регулярных областей $\left\{D_{n}\right\}$ такой, что $D_{n} \subset D_{n+1} \subset D$, и любой компакт $K \subset D$ содержится в $D_{n}$ при $n>n(K)$. Обобщенное решение Д. з. $u$ получается как предел последовательности $\left\{u_{n}\right\}$ решений Д. з. для областей $D_{n}$ и непрерывно продолженной граничной функции $\varphi$ внутрь $D$. Решение $u$ не зависит ни от выбора исчерпывающей последовательности $\left\{D_{n}\right\}$, ни от способа непрерывного продолжения $\varphi$ внутрь $D$.

Имеется трактовка обобщенного решения Д. з. на основе метода Перрона. Пусть $\bar{H}_{\varphi}$ - нижняя огибающая семейства всех верхних супергармонич. функций $v$, удовлетворяющих на $\Gamma$ условию

$\lim \inf v(x) \geqslant \varphi\left(x_{0}\right), \quad x \in D, x \rightarrow x_{0} ; \underline{H}_{\varphi}=\bar{H}_{-\varphi^{\circ}}$

Для любых области $D$ и функции $\varphi$ имеет место неравенство $\underline{H}_{\varphi} \leqslant \bar{H}_{\varphi}$. В случае равенства $\underline{H}_{\varphi}=\bar{H}=u$ эта функция $u$ является гармонической. Она наз. обобщенным решением Д. з., а граничная функция $\varphi$ - разрешимой. Любая непрерывная функция $\varphi$ разрешима, поведение же обобщенного решения $u$ в точке $x_{0} \in \Gamma$ определяется регулярностью или иррегулярностью $x_{0}$.

Для обобщенного по Винеру решения Д. з. справедливо интегральное представление в виде ф о р м улы Валле П у с с ен а

\[
u(x)=\int_{\Gamma} \varphi\left(x_{0}\right) d \omega\left(x, D \mid x_{0}\right),
\]

являющейся обобщением формулы (1). Здесь $d \omega(x, E)-$ гармонич. мера множества $E \subset \Gamma$ в точке $x_{0}$ (cм. [5]).

Отсюда возникает возможность рассмотрения обобщенной Д. з. для произвольных граничных функций $\varphi$, при этом можно требовать удовлетворения граничного условия лишь в нөк-рой ослабленной форме. Напр., если $D$ - область $\mathbb{R}^{2}$ с достаточно гладкой границей $\Gamma$, a граничная функция $\varphi$ имеет только точки разрыва 1-го рода, то можно требовать удовлетворения граничного условия лишь в точках непрерывности $\varphi$, для обеспечения единственности решения в точках разрыва требуется ограниченность решения. В постановке Н. Н. Лузина обобщенная Д. з. ставится для произвольной измеримой и конечной Почти всюду на Г граничной функции $\varphi$. Граничное условие может состоять в том, чтобы граничные значения решения по нормали к существовали и совпадали с $\varphi$ почти всюду на $\Gamma$.

Для общего эллиптич. уравнения 2-го порядка

$\sum_{i, j=0}^{n} a_{i j}(X) \frac{\partial^{2} u}{\partial x_{i} \partial x_{j}}+\sum_{i=0}^{n} b_{i}(X) \frac{\partial u}{\partial x_{i}}-c(X) u=f(X)$

Д. з. фредгольмова. При этом ищется регулярное в области решение, принимающее на границе наперед заданные значения. Приведенные выше методы исследования Д. з. для гармонич. функций обобщаются и на уравнение (3).

Для равномерно эллиптич. систем Д. з. может оказаться не только нефрецгольмовой, но даже иметь бесконечно много линейно независимых решений (см. [8]).

Д. 3. рассматривается и для нек-рых неәллиптич. уравнений или вырождающихся уравнений. В этих случаях Д. з. иногда оказывается некорректной.

Jum.: [1] Di r i c h l e t P. G. L. "Abh. der Königlich. Preus. Acad. der Wiss.», 1850, S. 99-і16; [2] M и p a н д a K., пер. с итал., М., 1957; [3] К у р а н т Р., Принцип Дирихле, конформные отображения и минимальные поверхности, пер. с англ., М., 1953; [4] е г о ж е, Уравнения с частными производческой теории потенциала, пер. с франц., М., 1964; [6] к К е л-

![](https://cdn.mathpix.com/cropped/2023_07_08_6e188be744bf0006d521g-1.jpg?height=47&width=826&top_left_y=2213&top_left_x=985)
[7] е г о ж'е, "Докл. AН СССР», 1951, т. 77, с. 181-83; [8] ний второго порядка, М., 1966 .