пространстве $Y$. В этом случае всякая слабо аналитич. функция $f(z)$ в области $D$ плоскости комплексного переменного $\mathbb{C}$ является А. Ф. а. Можно также сказать, что функция $f(z)$ будет А. ф. а. в области $D \subset \mathbb{C}$ тогда и только тогда, когда $f(z)$ непрерывна в $D$ и для любого простого замкнутого спрямляемого контура $L \subset D$ интеграл $\int_{L} f(z) d z$ обращается в нуль. Для А. ф. а. $f(z)$ комплексного переменного $z$ справедлива интегральная формула Коши (см. Коши интеграл).

Пусть $f(x)$ - слабо аналитич. функция в области $D$ банахова пространства $X$. Тогда $f(x+\xi h)$, как функция комплексного переменного $\xi$, имеет производные всех порядков в области $\tilde{D=}\{\xi ; x+\xi h \in D\}, h \in X$, причем эти производные суть А. ф. а. из $\tilde{D}$ в $Y$. Если множество $\{x+\xi h ;|\xi| \leqslant 1\}$ принадлежит $D$, то

\[
f(x+h)=\sum_{n=0}^{\infty} \frac{1}{n !} \delta^{n} f(x, h),
\]

где ряд сходится по норме и

\[
\begin{aligned}
& \delta^{n} f(x, h)=\left.\frac{d}{d \xi^{n}} f(x+\xi h)\right|_{\xi=0}= \\
& =\frac{1}{2 \pi i} \int_{|\xi|=1} f(x+\xi h) \xi^{-n-1} d \xi .
\end{aligned}
\]

Функция $y=P(x)$ из $X$ в $Y$ наз. п о ли но мо м относительно переменного $x$ степени не выше $m$, если для всех $x, h \in X$ и для всех комплексных $\xi$

\[
P(x+\xi h)=\sum_{v=0}^{m} P_{v}(x, h) \xi^{v},
\]

где функции $P_{v}(x, h)$ не зависят от $\boldsymbol{\xi}$. Степень $P(x)$ точно равна $m$, если $P_{m}(x, h) \neq 0$. С т е п е н н ы м р я д о м наз. ряд вида $\sum_{n=0}^{\infty} P_{n}(x)$, где $P_{n}(x)-$ однородные полиномы степени $n$ такие, что $P_{n}(\alpha x)=$ $=\alpha^{n} P_{n}(x), \quad x \in X$, для всех комплексных $\alpha$. Всякий слабо сходящийся степенной ряд $\sum_{n=0}^{\infty} P_{n}(x)$ в области $D$ сходится и по норме к нек-рой слабо аналитической функции $f(x)$ в $D$, причем $P_{n}(x)=\delta^{n} f(0, x) / n !, 0 \in D$. Функция $f(x)$ является А. ф. а. в $D$ тогда и только тогда, когда в окрестности каждой точки $a \in D$ она разлагается в степенной ряд

\[
f(a+h)=\sum_{n=0}^{\infty} P_{n}(h)
\]

где все $P_{n}(h)$ непрерывны в $X$.

На А. ф. а. переносятся с соответственными изменениями многие основные результаты классич. теории аналитіч. функций такие, как максимума модуля принцип, теоремы единственности, Витали теорема, Лиувилля теорема и др. Множество всех А. Ф. а. в области $D$ образует линейное пространство.

Понятие А. ф. а. обобщается и на более широкие классы пространств $X$ и $Y$, напр. на локально выпуклые топологич. пространства, банаховы пространства над произвольным полным нормированным полем и т.Д.

Лum.: [1] Х и л л е Э., Ф и л л и п с Р., Функциональный анализ и полугруппы, пер. с англ., 2 изд., М., $1962 ;[2]$ д в а p д с Р.-Ә., Функциональный анализ. Теория и приложеангі., т. 2, М., 1972. $А$. А. Данилевич, Е. Д. Соломенчев.

АНАЛИТИЧЕСКИИ ВЕКТОР В п р о с т p а н с т-

![](https://cdn.mathpix.com/cropped/2023_07_08_3915f5ca29beb99872e2g-1.jpg?height=43&width=821&top_left_y=1988&top_left_x=135)
вектор $\xi \in V$, для к-рого отображение $g \rightarrow T(g) \xi$ является вещественно аналитич. вектор-функцией на $G$ со значениями в $V$ (см. Представлений теория). Если $T$ - слабо непрерывное представление группы Љи $G$ в банаховом пространстве $V$, то множество $V^{\omega}$ аналитич. векторов плотно в $V$ (см. $[1],[2]$, [3]). Существует обобщение этой теоремы на широкий класс представлений в локально выпуклых пространствах [5]. Было доказано [6], что представление связной группы Ји $G$ в банаховом пространстве $V$ однозначно восстанавли- вается по соответствующему представлению алгебры Ли группы $G$ в пространстве $V^{\omega}$.

А налитический векторд д л н не г г р ан иче нн о го о пе р а т о р а $A$ в банаховом пространстве $V$ с областью определения $D(A)$ определяется как вектор

\[
\xi \in \bigcap_{n=1}^{\infty} D\left(A^{n}\right)
\]

для к-рого ряд

\[
\sum \frac{x^{n}}{n !} \| A^{n \xi \|}
\]

имеет положительный радиус сходимости. Это понятие, введенное в [2], является частным случаем общего понятия А. в.- здесь в качестве группы Ли $G$ выступает множество точек действительной прямой с операцией сложения. Оно оказалось полезным в теории операторов в банаховых пространствах и в теории эллиптич. дифференциальных операторов.

Jum.: [1] C a r t i e r P P $\quad$ D i x m i e r J., "Amer. J. Math.", 1958, v. 80, p. 131-45; [2] H е л c o н Э., "Математика", $1962,6: 3$, с. 89 131; [3] Г о р д и н Г Л., "Математика", 1965, 9 : 5, c. 78-94; [4] C a r t i e r P , Vecteurs analytiques. Sémi-
naire Bourbaki, Mai $1959 ;$ [5] M o o r e R. T., «Memoirs Amer. naire Bourbaki, Mai 1959; [5] M o o r e R. T., "Memoirs Amer.
Math. Soc.", 1968, v.78; [6] H a r i s h-C h a n d r a, "Trans. Amer. Math. Soc.», 1953, v. 75, p. 185-243. A. A. Кириллов.

АНАЛИТИЧЕСКИЙ ДИФФ ЕРЕНЦИАЛ - см. Д $и \phi-$ ференциал на римановой поверхности.

АНАЛИТИЧЕСКИЙ ЛАНДІІАФТ, $а$ н а л и т и ч ес к и й р е ль е ф, по в е р х ность мо д уля,一 геометрич. изображение модуля $|f(z)|$ аналитич. функции $f(z), \quad \boldsymbol{z}=x+i y$. А н а ли т и ч е с ки м л а ндш а ф т о ф функции $f(z)$ наз. поверхность над плоскостью $(x, y)$, имеющая аппликатой значение $|f(z)|$. А. л. позволяет иногда составить наглядное представление о поведении нек-рых конкретных функций. А. л. основных функций см. в [2].

Лит.: [1] III а б а т Б. В., Введение в комплексный анализ, 2 изд., ч. 1, М., 1976; [2] Я'н к е E., Э м д е Ф., Таблицы функций с формулами и кривыми, пер. с нем., 3 изд., М., 1959.

АНАЛИТИЧЕСКИЙ ОБРАЗ - расширение понятия полной аналитической функции, получающееся при рассмотрении всех возможных элементов аналитич. функции в виде обобщенных степенных рядов (р я д о в П юи $а$ ё)

\[
\sum_{v=m}^{\infty} a_{v}\left(z-z_{0}\right)^{v / n}, \quad \sum_{v=m}^{\infty} a_{v} z^{-v / n}
\]

где $z=$ комплексное переменное, $m$ - целое, а $n$ натуральное числа, сходящихся соответственно в областях $\left|z-z_{0}\right|<r,|z|>r>0$. А. о. можно отождествить с классом всех әлементов вида $(*)$, получающихся друг из друга посредством аналитического продолжения. А. о. отличается от полной аналитич. функции присоединением всех разветвленных элементов вида (*) с $n>1$, получающихся при аналитич. продолжении ее регулярных элементов с $n=1$. После введения соответствующей топологии А. о. превращается в риманову поверхность данной функции.

Лum.: [1] м а р к у ї е в и ч А. К., Теория аналитических функций, т. 2, М., 1968 , гл. 8. А. М., Теот. Д. Соломенчев.

АНАЈИТИЧЕСКИЙ ОПЕРАТОР в т о ч к е $x_{0}$ оператор $A$, действующий из одного банахова пространства в другое и допускающий представление вида

\[
\boldsymbol{A}\left(x_{0}+h\right)-A x_{0}=\sum_{k=1}^{\infty} C_{k} h
\]

где $C_{k}=$ форма порядка $k$, а ряд сходится равномерно в нек-ром шаре $\|h\|<r$. Оператор наз. а н а л и т и ч ес к и м в о бл а с ти $G$, если он является А. о. в каждой точке этой области. А. о. бесконечно дифференцируемы; в случае комплексных пространств аналитичность в области есть следствие дифференцируемости (по Гато) в каждой точке этой области. Примерами А. о. могут служить интегро-степенные ряды Ляпунова, операторы Гаммерштейна и Урысона с глад-