наз. э к в и а фф и н н о й д у г о й. Дифференциальный инвариант

\[
k=\left(\frac{d^{2} \boldsymbol{r}}{d s^{2}}, \frac{d^{3} \boldsymbol{r}}{d s^{3}}\right)
\]

наз. э к в и а ф ф п н о й к р И в И кривой. Постоянство эквиаффинной кривизны характеризует кривые 2-го порядка. Натуральное уравнение $k=f(s)$ определяет кривую с точностью до эквиаффинного преобразования. Вектор $n=d^{2} \boldsymbol{r} / d s^{2}$ направлен по аффинной нормали к плоской кривой; аффинная нормаль в точке $M, k \neq 0$, касается геометрич. места середин хорд кривой, параллельных касательной в точке $M$ и совпадает с диаметром параболы, имеющей в точке $M$ соприкосновение 3-го порядка с кривой.

При переходе к общей аффинной группе у кривой рассматривают два более сложных инварианта: аффинную дугу $\sigma$ п аффинную кривизну $\varkappa$. Они могут быть выражены через введенные выше инварианты $s$ и $k$ :

\[
\sigma=\int k^{1 / 2} d s, x=\frac{1}{k^{3 / 2}} \cdot \frac{d k}{d s}
\]

(в эквиаффинной геометрии сами величины $s$ и $k$ для краткости наз. аффинной дугой и аффинной кривизной). Подобным же образом строятся центроаффинная дуга, центроаффинная кривизна, эквицентроаффинная дуга и эквицентроаффинная кривизна плоской кривой.

В э к и а фф ф п но м п р о с т р а н с т в каждым трем векторам $\alpha, b, c$ может быть отнесен инвариант $(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})$ - объем ориентированного параллелепипеда, определяемого әтими векторами. Натуральный параметр (эквиаффинная дуга) кривой $\boldsymbol{r}=\boldsymbol{r}(t)\left(\boldsymbol{r} \in C^{3}\right)$ определяется формулой

\[
s=\int_{t_{0}}^{t}|(\dot{\boldsymbol{r}}, \ddot{r}, \ddot{\boldsymbol{r}})|^{1 / 6} d t
\]

Дифференциальные инварианты $x=\left(\boldsymbol{r}^{\prime}, \boldsymbol{r}^{\prime \prime \prime}, \boldsymbol{r}^{\mathrm{IV}}\right), \tau=$ $\stackrel{=}{=}\left(\boldsymbol{r}^{\prime \prime}, \boldsymbol{r}^{\prime \prime}, \boldsymbol{r}^{\mathrm{IV}}\right)$, где штрихи означают дифференцирование по натуральному параметру, наз. соответственно э к ви а фф Ин но й к ри визно й И аффинны м к р у ч е и е м пространственной кривой. Изучение кривой сводится к выбору того или иного сопровождающего репера; особую роль играет репер, образованный векторами

\[
\left\{\dot{r}, \quad \ddot{r}, \quad \ddot{r}+x \frac{\dot{r}}{4}\right\}
\]

и определяемый дифференциальной окрестностью 4-го порядка рассматриваемой кривой. Разработана также центроаффинная теория пространственных кривых (см. [5]).

Для П о в е р х н о с т п $\boldsymbol{r}=\boldsymbol{r}\left(u^{1}, u^{2}\right)$ в эквиаффинном пространстве, отличной от развертывающейся поверхности, строится тензор

\[
g_{i j}=\frac{a_{i j}}{|a|^{1 / 4}}
\]

где $a_{i j}=\left(r_{1}, r_{2}, r_{i j}\right), a=\operatorname{det}\left(a_{i j}\right), r_{i}=\partial_{i} \boldsymbol{r}, r_{i j}=\partial_{i j} \boldsymbol{r}$. Вектор

\[
\boldsymbol{N}=\frac{1}{2} g^{k s} \nabla_{k} r_{s}
\]

где $\nabla_{k}$ - символ ковариантной производной в связности с метрич. тензором $g_{i j}$, задает направление афффинной нормали к поверхности. Аффинная нормаль проходит через центр соприкасающейся квадрики Ли. Деривационные уравнения

\[
\partial_{j} r_{i}=\stackrel{1}{\Gamma}_{i j} s_{s}+g_{i j} N
\]

определяют внутреннюю связность 1-го рода $\stackrel{1}{\Gamma_{i j}^{k}}$ поверхности. Наряду с ней возникает внутренняя свявность 2-го рода $\Gamma_{i j}^{k}$, определяемая деривационными уравнениями

\[
\partial_{j} v_{i}=\stackrel{2}{\Gamma}_{i j} s v_{s}+A_{i j} v_{2}
\]

где $v$ - ковариантный вектор, определяющий касательную плоскость к поверхности И подчиненный условию нормировки $N v=1$. Связности $\Gamma_{i j}^{k}$ и $\Gamma_{i j}^{2}$ являются сопряженными относительно тензора $g_{i j}$ в смысле А. ПI. Нордена (см. [3]). Тензор

\[
T_{i j}^{k}=\frac{1}{2}\left(\stackrel{1}{\Gamma}_{i j}^{k}-\stackrel{2}{\Gamma}_{i j}^{k}\right)
\]

играющий также основную роль в проективной дифђеренциальной геометрии, позволяет построить симметрич. ковариантный тензор

\[
\begin{aligned}
& T_{i j k}=g_{k s} T_{i j}
\end{aligned}
\]

Строятся также две основные формы поверхности: к в а д р а тичная фо р м а

\[
\varphi=g_{i j} d u^{i} d u^{j}
\]

икубическая фо рма Фубини-П ика $\psi=T_{i j k} d u^{i} d u^{j} d u^{k}$.

Эти формы связаны у с л о в и е м а по л я р н о с ти $g^{i j} T_{i j k}=0$.

Две такие формы, удовлетворяющие дополнительным дифференциальным условиям, определяют поверхность с точностью до эквиаффинных преобразований. Все эти положения обобщаются на многомерный случай.

В аффинном и эквиаффинном пространствах выделяется много специфич. классов поверхностей: аффинные сферы (у к-рых аффинные нормали образуют связку), афффиные поверхности вращения (аффинные нормали пересекают одну собственную или несобственную прямую), аффинные минимальные поверхности и др.

Помимо кривых и поверхностей, изучаются также иные геометрич. образы әквиаффинного пространства, напр. конгруэнции и комплексы прямых, векторные поля и др.

Наряду с эквиаффинной дифференциальной геометрией разрабатывается дифференциальная геометрия общей аффинной группы и других ее подгрупп как в трехмерном, так и в многомерном пространствах (центроаффинном, эквицентроаффинном, аффинно-симплектическом, биаффинном и т. д.) .

Jum.: [1] B l a s c h ke W., Affine Differentialgeometrie, B., 1923; [2] Sal k o w s k i E., Affine Differentialgeometrie, связности, M. J., 1950; [4] Итоги науки. Геометрия. 1963 , M., 1965, c. 3-64; [5] III и р о к о в П.. А., III и ро к о в А.' П., Аффинная дифференциальная геометрия, М., 1959.

АФФИННАЯ КРИВИЗНА - дифференциальный инвариант плоской кривой в геометрии общей афббинной аруппы или ее подгруппы. Обычно под А. к. понимают дифференциальный инвариант кривой в геометрии аффинной унимодулярной (или эквиаффинной) группы. В этой геометрии А.к. (точнее, эквиафффинная кривизна) плоской кривой $y=y(x)$ вычисляется по формуле

\[
k=-\frac{1}{2}\left[\left(y^{\prime \prime}\right)^{-2 / 3}\right]^{\prime \prime}
\]

а аффинная (точнее, әквиаффинная) длина дуги кривой равна

\[
s=\int\left(y^{\prime \prime}\right)^{1 / 3} d x
\]

Имеется геометрич. истолкование А. к. в точке $M_{0}$ кривой: если $M$ - близкая к $M_{0}$ точка кривой, $s$ - аффинная длина дуги $M_{0} M$, а $\sigma-$ афффинная длина дуги параболы, касающейся данной кривой в точках $M_{0}$ И $M$, то А. к. в точке $M_{0}$ равна

\[
k_{0}= \pm \lim _{M \rightarrow M_{0}} \sqrt{\frac{720(\sigma-s)}{s^{5}}}
\]

В аффинной теории пространственных кривых и поверхностей также существуют понятия А. к., напоминаю-