АНТИПодЫ - диаметрально противоположные точки сферы. Имеются следующие т е о р е м ы Б о р с ук а [1] о б А. 1) При любом отображении сферы $S^{n}$ в евклидово пространство $E^{n}$ найдутся А. с общим образом. 2) Каждое отображение сферы $S^{n}$ в себя, при к-ром образы А. являются А., есть существенное отображение.

Jum.: [1] B ors u k K., "Fundam. math.", 1933, t. 20, АНТИІІРИЗМА - noлynpaвильный многогранник, у которого две параллельные грани - равные между собой правильные $n$-угольники, а остальные $2 n$ граней - правильные треугольники (см.

![](https://cdn.mathpix.com/cropped/2023_07_08_bcab05acc73bc35aecffg-1.jpg?height=275&width=361&top_left_y=408&top_left_x=596)
рис.). А. Б. Иванов.

АНТИСИММЕТРИЧНЫЙ ТЕНЗОР - см. Тензорное исчисление.

АНТИТОННОЕ ОТОБРАЯЕНИЕ ч а с т И ч н о у по р я д о ч ен ны х мн о же с т в - отображение $\varphi$ частично упорядоченного множества $A$ в частично упорядоченное множество $B$ такое, что из $a \leqslant b(a, b \in A)$ следует, $a \varphi \geqslant b \varphi$. Дуальное понятие к А. о.- изотонное отображение.

О. А. Иванова.

АНТЬЕ, ц е л а я ч а с т ь (д е й с т в и т е л ьн о г о) ч и с л а $x,-$ наибольшее целое число, не превосходящее $x$. Обозначение $[x]$ или $E(x)$. Из определения А. следует, что $[x] \leqslant x<[x]+1$. Если $x-$ целое, то $[x]=x$. Примеры: $[3,6]=3,\left\lfloor\frac{1}{3}\right\rfloor=0,\left|-4 \frac{1}{3}\right|=-5$. При помощи А. получают, напр., разложение на простые множители числа $n !=1 \cdot 2 \cdot \ldots \cdot n$, а именно,

\[
n !=\prod_{p \leqslant n^{p^{\alpha(p)}}}
\]

где произведение составлено из всех простых чисел $p$, не превосходящих $n$, a

\[
\alpha(p)=\left[\frac{n}{p}\right]+\left[\frac{n}{p^{2}}\right]+\ldots .
\]

Функция $y=[x]$ переменного $x$ есть кусочно непрерывная (ступенчатая) функция со скачками в целых точках. Посредством А. определяется д р о б н а я ч а с т ь ч и с л а $x$, обозначаемая символом $\{x\}$ и равная разности

\[
x-[x] ; \quad 0 \leqslant\{x\}<1
\]

Функция $y=\{x\}$ - периодическая кусочно непрерывная функция.

Лит.: [1] В и н о г р а д о в И. М., Основы теории чисел, М., 8 изд., 1972 .

АНЬЕЗИ ЈОК уравнение к-рой в декартовой прямоугольной системе координат имеет вид

\[
y\left(a^{2}+x^{2}\right)=a^{3}, a>0 .
\]

Если $a$ есть диаметр окружности с центром в точкө $(0, a / 2), O A$ - секущая, $C B$ и $A M$ параллельны оси

![](https://cdn.mathpix.com/cropped/2023_07_08_bcab05acc73bc35aecffg-1.jpg?height=312&width=389&top_left_y=1831&top_left_x=133)
$O x$, а $B M$ параллельна оси Oy (см. рис.), то А. л. есть геометрич. место точек $M$. Если центр образующей окружности и касательная $C B$ смещены по оси $O y$, то кривая, получаемая аналогичным построением, наз. a r в и н е й н а и является обобщением А. л. Названа по имени М.

Аньези (M. Agnesi), изучавшей эту кривую (1748). Лum.: [1] С а в е ло в А. А., Плоские кривые, М., 1960. АПЕРИОДИЧЕСКИЙ АВТОМОРФИЗМ $А$ р о с тран с т в а с м е р о й - такой автоморфизм $T$ пространства с мерой, периодич. точки к-рого (т. е. точки $x$, для к-рых $T^{k} x=x$ при нек-ром $k>0$ ) образуют множество меры нуль. В ведение специального названия для таких преобразований вызвано тем, что в нек-рых теоремах эргодической теории автоморфизмы, имеюшие «слишком много" периодич. точек, играют роль тривиальных исключений (см. [1]).

Лuт.: [1] Р ох ли н В. А., «Успехи матем. наук», 1949,
Д. №2 2 (30), с. $57-128$.

АІОЈЛОНИЯ ЗАДАЧА - задача о построениИ на плоскости окружности, касающейся трех заданных окружностей. Решается методом инверсий. Окружность, являющаяся решением А. з., наз. о к р у ж н о с т ь ю А по л ло ни я. А. 3. названа по имени Аполлония Пергского (3 в. до н. э.).

Лит.: [1] Энциклопедия әлементарной математики, кн. 4, ееометрия, М., 1963. А. Б. Иванов.

АПОЈЈОНИЯ ТЕОРЕМА - 1) Сумма квадратов длин сопряженных полудиаметров эллипса есть величина постоянная, равная сумме квадратов длин его полуосей. 2) Площадь описанного вокруг эллипса параллелограмма, стороны к-рого цмеют сопряженные направления, постоянна и равіа произведению длин его диаметров.

А. Б. Иванов.

АПОЛЯРНЫЕ СЕТИ - две сети, заданные в одной и той же области $G$ двумерного многообразия и обладающие тем свойством, что в каждой точке $x \in G$ касательные направления одной из этих сетей гармонически разделяют касательные направления другой. Например, на поверхности в евклидовом пространстве асиљптотическая сеть аполярна кривизны линий сети.

В. Т. Баэылев. АІІОСТЕРИОРНАЯ ВЕРОЯТНОСТЬ (в е р о я тно с т ь a posteriori) к а к о го-ли бо с о б т ия - условная вероятность события при нек-ром условии, рассматриваемая в противоположность его безусловной или априорной вероятности. Никакого принципиального различия между терминами «условная" и «апостериорная" нет. В применениях первый термин используют, когда самое уєловие носит предположительный характер и в ходе опытов непосредственно не наблюдается. Второй термин используют, когда желают подчеркнуть, что условие, о к-ром идет речь, фактически наблюдено. А. в. связана с априорной вероятностью Бейеса бормулой. Ю. В. Прохоров.

АІОСТЕРИОРНОЕ РАСПРЕДЕЛЕНИЕ - условное распределение вероятностей какой-либо случайной величины при нек-ром условии, рассматриваемо в противоположность ее безусловному или априорному распределению.

Если $\Theta$ - случайный параметр с априорной плотностью $p(\theta), X$ - случайный результат наблюдений и $p(x \mid \theta)$ - условная плотность $X$ при условии $\Theta=\theta$, то А. p. $\Theta$ при данном $X$ согласно Бейеса бормуле имеет плотность

\[
p(\theta \mid x)=\frac{p(\theta) p(x \mid \theta)}{\int_{-\infty}^{+\infty} p(\theta) p(x \mid \theta) d \theta} \cdot
\]

Если $T(x)$ - достаточная статистика для семейства распределений с плотностями $p(x \mid \theta)$, то А. р. зависит не от самого $x$, а от $T(x)$. Асимптотич. поведение при $n \rightarrow \infty$ A. p. $p\left(\theta \mid x_{1}, \ldots, x_{n}\right)$, где $x_{j}$ суть результаты независимых наблюдений с плотностью $p\left(x \mid \theta_{0}\right)$, оказывается «Почти независящим» от априорного распределения $\theta$.

О роли А. р. в теории статистич. решений см. Вейесовский подход.

Лит.: [1] Б е р н ш т е й н С. Н., Теория вероятностей, 4 изд., М.-Л., $1946 . \quad$ Ю.. В. П рохоров.

АIIФЕМА П р а в И ль н о ғ о м н о г о у г о л н и к а - отрезок (а также его длина) перпендикуляра, опущенного из центра правильного многоугольника