В бесконечном промежутке его заменяет интеграл Фурье-Бесселя

\[
\begin{gathered}
f(x)=\int_{0}^{\infty} c_{\lambda} J_{v}(\lambda x) d \lambda, \quad c_{\lambda}=\int_{0}^{\infty} f(x) J_{v}(\lambda x) x d x, \\
0<x<\infty .
\end{gathered}
\]

Важную роль в теории Б. Ф. и их применений играют: 1) интегральное представление

\[
J_{n}(z)=\frac{1}{\pi} \int_{0}^{\pi} \cos (z \sin \varphi-n \varphi) d \varphi,
\]

2) производящая функция

\[
e^{\frac{z}{2}\left(\xi-\frac{1}{\xi}\right)}=\sum_{n=-\infty}^{\infty} J_{n}(z) \xi^{n},
\]

3) теорема сложения для Б. ф. нулевого индекса $J_{0}\left(\sqrt{a^{2}+b^{2}-2 a b \cos \varphi}\right)=$

\[
=J_{0}(a) J_{0}(b)+2 \sum_{k=1}^{\infty} J_{k}(a) J_{k}(b) \cos k \varphi,
\]

4) рекуррентные формулы

\[
\begin{gathered}
J_{p-1}(z)+J_{p+1}(z)=\frac{2 p}{z} J_{p}(z) \\
{\left[J_{p}(z)\right]^{\prime}=\frac{1}{2}\left[J_{p-1}(z)-J_{p+1}(z)\right] .}
\end{gathered}
\]

Лит. см. при статье Цилиндрические бункчии.

П. И. Лизоркин. БЕТА-РАСПРЕДЕЛЕНИЕ - непрерывное сосредоностью

\[
\beta_{m, n}(x)=\frac{1}{\mathrm{~B}(m, n)} x^{m-1}(1-x)^{n-1},
\]

где параметры $m, n$ неотрицательны и нормирующий множитель $\mathrm{B}(m, n)$ есть бета-функция Эйлера

\[
\mathrm{B}(m, n)=\int_{0}^{1} x^{m-1}(1-x)^{n-1} d x=\frac{\Gamma(m) \Gamma(n)}{\Gamma(m+n)}
\]

(Г (n)-гамма-функция). Функция распределения выражается через неполную бета-функцию

\[
\mathrm{B}_{m, n}(x)=\frac{1}{\mathrm{~B}(m, n)} \int_{0}^{x} y^{m-1}(1-y)^{n-1} d y, \quad 0<x<1
\]

(эта функция табулирована, см. [1], [2] ). Моменты Б.-р. выражаются формулой

\[
m_{k}=\frac{\mathrm{B}(m+k, n)}{\mathrm{B}(m, n)}, \quad k=1,2, \ldots ;
\]

в частности, математич. ожидание и дисперсия равны $m /(m+n)$ и $m n /(m+n)^{2}(m+n+1)$, соответственно. Если $m>1$ и $n>1$, то кривая плотности $\beta_{m, n}(x)$ имеет единственную точку максимума $x=(m-1) /(m+n-2)$ и обращается в нуль на концах интервала. Если $m<1$ или $n<1$, то одна из крайних ординат графика бесконечна, а если и $m<1$, и $n<1$, то обе ординаты на концах интервала бесконечны и кривая имеет U-образную форму. При $m=1$ и $n=1$ Б.-р. превращается в равномерное распределение в интервале $(0,1)$. Другим частным случаем Б.-р. является так наз. арксинуса распределение

\[
\beta_{1 / 2}, 1 / 2(x)=\frac{1}{\pi \sqrt{x(1-x)}} .
\]

При замене в (1) $x=1 /(1+t)$ получается распределение с плотностью

\[
\beta_{m, n}^{\prime}(t)=\frac{1}{\mathrm{~B}(m, n)} \cdot \frac{t^{m-1}}{(1+t)^{m+n-2}}, \quad 0<t<\infty .
\]

Это распределение наз. Б.-р. в то р о го р о д а, в отличие от Б.-р. (1). Распределения (1) и (2) соответствуют распределениям «типа I»и «типа VI» в системе Пирсона кривых. Один из важных случаев возникновения Б.-р. таков: если $X_{1}$ и $X_{2}$ независимы и имеют гамма-распределения с параметрами $m$ и $n$ соответственно, то случайная величина $X_{1} /\left(X_{1}+X_{2}\right)$ имеет Б.-р. с плотностью $\beta_{m, n}(x)$. Этот факт в большой степени объясняет ту роль; к-рую Б.-р. играет в приложениях, в частности в математич. статистике: распределения многих важнейших статистик сводятся к Б.-р. Напр., функция распределения $F$-отношения

\[
F_{m, n}=\frac{n \chi_{m}^{2}}{m \chi_{n}^{2}}
\]

(случайная величина $\chi_{k}^{2}$ имеет $\chi^{2}$-распределение с $k$ степенями свободы) выражается формулой

\[
\mathrm{P}\left(F_{m, n}<x\right)=\mathrm{B}_{\frac{m}{2}, \frac{n}{2}}\left(\frac{m x}{n+m x}\right)
\]

(обычно значения $F$-распределения вычисляются с помощью таблиц Б.-р.). Функция Б.-р. позволяет также вычислять значения функций биномиального распределения, ввиду соотношения

\[
\mathrm{B}_{n-\boldsymbol{m}, \boldsymbol{m + 1}}(1-p)=\sum_{k=0}^{m} C_{n}^{k} p^{k}(1-p)^{n-k} .
\]

Б.-p. находит применение не только в математич. статистике, так, напр., плотность Б.-р. является весовой функцией для системы ортогональных Якоби многочленов.

Лum.: [1] Б о л ь ші е в Л. Н., С м и рн о в Н. В., Таблицы математической статистики, 2 изд., М., 1968 ; [2] П и р-

![](https://cdn.mathpix.com/cropped/2023_07_08_40ef115d9061c0836707g-1.jpg?height=52&width=838&top_left_y=1035&top_left_x=985)

БЕТА-ФУНКЦИЯ, В - ф у н к ц и я, В - ф у н кция Эй л е р а, әйле ров ин те г р а л 1-го р о д а,- функция двух переменных $p$ и $q$, определяемая при $p>0, q>0$ равенством

\[
\mathrm{B}(p, q)=\int_{0}^{1} x^{p-1}(1-x)^{q-1} d x .
\]

Значения Б.-ф. при различных значеніях параметров $p$ и $q$ связаны между собой следующими соотношениями

\[
\begin{gathered}
\mathrm{B}(p, q)=\mathrm{B}(q, p), \\
\mathrm{B}(p, q)=\frac{q-1}{p+q-1} \mathrm{~B}(p, q-1), \quad q>1 .
\end{gathered}
\]

Справедлива формула

\[
\mathrm{B}(p, 1-p)=\frac{\pi}{\sin p \pi}, \quad 0<p<1 .
\]

В случае комплексных $p$ и $q$ интеграл (*) сходится, когда $\operatorname{Re} p>0$ и $\operatorname{Re} q>0$. Б.-ф. выражается через гаммабункцию:

\[
\mathbf{B}(p, q)=\frac{\Gamma(p) \Gamma(q)}{\Gamma(p+q)} .
\]

В. И. Битючков.

БЕТТИ ГРУПІА - в широком смысле то же, что и гомологии гр уппа; в узком смысле Б. г. является свободной частью группы гомологий с областью коәффициентов - группой $\mathbb{Z}$ целых чисел в случае, если эта группа конечно порождена. Названа по пмени Э. Бетти (E. Betti).

Лum.: [1] 3 е й ф е р т гия, пер. с нем., М.- Ј., 1938; [2] А ле к с а н д р о в П. С., $\begin{array}{ll}\text { Введение в гомологическую теорию размерности и общую ком- } \\ \text { бинаторную топологию, М., 1975. } & \text { М. И. Войцеховский. }\end{array}$

БЕТТИ ЧИСЈО, $r$-м е р н о е ч и с л о Б е т т и $p^{r}$ к о м п ле к с а $K,-$ ранг $r$-мерной Бетmu әр упnы с целыми коәффициентами. Для каждого $r$ Б. ч. $p^{r-}$ топологич. инвариант полиэдра, реализующего комплекс $K$, указывающий число попарно негомологичных (над рациональными числами) циклов в нем.Например, для сферы $S^{n}$ :

\[
p^{0}=1, p^{1}=\ldots=p^{n-1}=0, \quad p^{n}=1 ;
\]