БЕЗГРАНИЧНО ДЕЛИМОЕ РАСПРЕДЕЛЕНИЕ распределение вероятностей, к-рое при любом $n=2,3$, 4, . . . может быть представлено как композиция (свертка) $n$ одинаковых распределений вероятностей. Определение Б. Д. р. в равной степени применимо к распределениям на прямой, в конечномерных евклидовых пространствах и в нек-рых еще более общих случаях. Ниже рассматривается одномерный случай.

Характеристич. Функции $f(t)$ Б. д. р. наз. б е з г p aни ч н о д л и мы м п. Каждая такая функция при любом $n$ может быть представлена как $n$-я степень некоторой другой характеристич. функции:

\[
f(t)=\left(f_{n}(t)\right)^{n} \text {. }
\]

Примерами Б. Д. р. могут служить нормальное распределение, Пуассона распределение, Коши распределение, «xи-квадрат» распределение. Проверять свойство безграничной делимости проще всего с помощью характеристич. Функций. Композиция Б. д. р. и предел слабо сходящейся последовательности Б. Д. р. суть снова Б. д. p.

Случайную величину, определенную на нек-ром вероятностном пространстве, наз. бе з $\mathbf{p} \mathrm{p}$ а ни ч н о д е л и м о й, если при любом $n$ она может быть представлена в виде суммы $n$ независимых одинаково распределенных случайных величин, определенных на том же пространстве. Распределение каждой такой величины - Б. д. р. Обратное не всегда верно. Так, если взять дискретное вероятностное пространство, образованное неотрицательными целыми числами $m=0,1,2$, ... с приписанными им пуассоновскими вероятностями

\[
\mathrm{P}(m)=\frac{\lambda^{m}}{m !} e^{-\lambda},
\]

то случайная величина $X(m)=m$ не будет безгранично делимой, хотя ее распределение вероятностей (распределение Пуассона) есть Б. Д.р.

Б. д. р. впервые появились в связи с изучением стохастически непрерывных однородных случайных процессов с независимыми пр иращениями (см. [1], [2], [3]). Так называют процессы $X(\tau), \tau \geqslant 0$, удовлетворяющие требованиям: 1) $X(0)=0$; 2) распределение вероятностей приращения $X\left(\tau_{2}\right)-X\left(\tau_{1}\right), \tau_{2}>\tau_{1}$, зависит только от $\left.\tau_{2}-\tau_{1} ; 3\right)$ при $\tau_{1} \leqslant \tau_{2} \leqslant \ldots \leqslant \tau_{k}$ разности

$X\left(\tau_{2}\right)-X\left(\tau_{1}\right), X\left(\tau_{3}\right)-X\left(\tau_{2}\right), \ldots, X\left(\tau_{k}\right)-X\left(\tau_{k-1}\right)$ являются взаимно независимыми случайными величинами; 4) для любого $\varepsilon>0$

\[
P(|X(\tau)|>\varepsilon) \longrightarrow 0
\]

при $\tau \rightarrow 0$. Для такого процесса значение $X(\tau)$ при любом $\tau$ будет иметь Б. д. р. и соответствующая характеристич. функция удовлетворяет соотношению:

\[
f_{\tau}(t)=\left(f_{1}(t)\right)^{\tau}
\]

Общий вид $f_{\tau}(t)$ для таких процессов в предположении конечности дисперсий $\mathrm{DX}(\tau)$ был найден А. Н. Колмогоровым [2] (частный случай приводимого ниже общего канонич. представления Б. д. р.).

Характеристич. функция Б. Д. р. нигде не обращается в нуль, и ее логарифм (в смысле главного значения) допускает представление вида:

\[
\ln f(\tau)=i \gamma t+\int_{-\infty}^{+\infty} L(u, t) \frac{1+u^{2}}{u^{2}} d G(u)
\]

(так наз. к а н о ич е с к о е п ред с т а в ле ни е Л е ви - Х ин чин а), где

\[
L(u, t)=e^{i t u}-1-\frac{i t u}{1+u^{2}}
\]

$\gamma$ - нек-рая действительная постоянная, $G(u)-$ неубывающая функция ограниченной вариации с $G(-\infty)=0$. Подинтегральное выражение при $u=0$ принимают равным $-t^{2} / 2$. При любом выборе постоянной $\gamma$ и функции $G(x)$ с указанными выше свойствами формула (*) определяет логарифм характеристич. функции нек-рого Б. Д. р. Соответствие между Б. Д. р. и парами $(\gamma, G)$ взаимно однозначно И в з а и мн о н е п р е ры вн о. Последнее означает, что Б. Д. р. слабо сходятся к предельному Б. Д. р. тогда и только тогда, когда $\gamma_{n} \rightarrow \gamma$ и $G_{n}(x)$ слабо сходятся к $G(x)$ при $n \rightarrow \infty$.

$\Pi$ р и м е р ы. Пусть $U(x)=0, x \leqslant 0, U(x)=1, x>0$. Тогда для нормального распределения с математич. ожиданием $a$ и дисперсией $\sigma^{2}$ в формуле (*) следует положить

\[
\gamma=a, \quad G(x)=\frac{\sigma^{2}}{2} U(x) .
\]

Для распределения Пуассона с параметром $\lambda$ имеем

\[
\gamma=\frac{\lambda}{2}, G(x)=\frac{\lambda}{2} U(x-1) .
\]

Для распределения Коши с плотностью

\[
p(x)=\frac{1}{\pi\left(1+x^{2}\right)}
\]

имеем $\gamma=0$

\[
G(x)=\frac{1}{\pi} \operatorname{arctg} x+\frac{1}{2} .
\]

Канонич. представление (*) удобно с чисто «технической» точки зрения (благодаря тому, что $G$ имеет ограниченную вариацию), однако функция $G$ не имеет прямого вероятностного истолкования. Поэтому используют и другую форму представления Б. д. р., допускающую непосредственную вероятностную интерпретацию. Пусть функции $M(u)$ и $N(u)$ определены при $u<0$ и $u>0$, соответственно, формулами:

\[
\begin{aligned}
& d M(u)=\frac{1+u^{2}}{u^{2}} d G(u), \\
& d N(u)=\frac{1+u^{2}}{u^{2}} d G(u), \\
& M(-\infty)=N(\infty)=0 .
\end{aligned}
\]

Эти функции неубывающие, $M(u) \geqslant 0$ при $u<0$ и $N(u) \leqslant$ $\leqslant 0$ при $u>0$; в окрестности нуля функции могут неограниченно возрастать. Обозначая дополнительно через $\sigma^{2}$ скачок функции $G$ в нуле, формулу (*) можно переписать в виде:

\[
\begin{gathered}
\ln f(t)=i \gamma t-\frac{1}{2} \sigma^{2} t^{2}+\int_{-\infty}^{-0} L(u, t) d M(u)+ \\
+\int_{+0}^{\infty} L(u, t) d N(u)
\end{gathered}
\]

(к а но ич е ско е п р е д с т а в лени е Л ев и). Функции $M$ и $N$ описывают, грубо говоря, частоту скачков различного размера в однородном процессе $X(\tau)$ с независимыми приращениями, для к-рого

\[
\ln f_{\tau}(t)=\tau \ln f(t)
\]

Важная роль Б. д. р. в предельных теоремах теории вероятностей связана с тем, что эти и только эти распределения могут быть предельными для сумм независимых случайных величин, подчиненных требованию асимптотической пренебрегаемости. При этом рассматривают последовательность серий $X_{n 1}, \ldots, X_{n k_{n}}$, $n=1,2, \ldots$, взаимно независимых случайных величин и затем подбирают взаимно независимые случайные величины $Y_{n 1}, \ldots, Y_{n k_{n}}$, имеющие Б. Д. р. (так наз. с о п р о в ж д а ю щ е Б. д. р.); характеристич. функция $g_{n k}(t)$ величины $Y_{n k}$ определяется по характеристич. функции $f_{n k}(t)$ величины $X_{n k}$ так, чтобы выполнялось следующее основное свойство: распределения сумм

\[
\sum_{k=1}^{k} X_{n k}-A_{n}
\]

сходятся к предельному распределению (при нек-ром