но существованию несобственного интеграла от самой функции.

Пусть значения функции $f(x)$ принадлежат нек-рому банахову пространству с нормой $\|\cdot\|$. Тогда функция $f(x)$ наз. абсолютно интегрируемой на измеримом множестве $E$, если существует интеграл

\[
\int_{E}\|f(x)\| d x
\]

при этом, если функция $f(x)$ интегрируема на $E$, то

\[
\left\|\int_{E} f(x) d x\right\| \leqslant \int_{E}\|f(x)\| d x .
\]

Лит.: [1] И ль и н В. А., П о з н я К. Г., Основы математического анализа, ч. 1, 3 изд., М., 1971; [2] К у д р я вц е в Л. Д., Математический анализ, т. 1, 2 изд., М., 1973; 2 1975; [4] ш в р ц Л., Анализ, пер. с франц., т. 1, і., 1972. 1975, [4]

АБСОЛЮТНО ПЛОСКОЕ КОЛЬЦО - кольцо, над к-рым любой модуль (правый или левый) является плоским модулем. Этот класс колец совпадает с классом регулярных колец в смысле фон Неймана.

АБСОЛЮТНО СХОДЯІЦИЙСЯ НЕСОБСТВЕННЫЙ ИНТЕГРАЛ - несобственный интеграл, для к-рого интеграл от абсолютной величины подинтегральной функции сходится. Если несобственный интеграл абсолютно сходится, то он и просто сходится. Пусть дан (для определенности) несобственный интегралі вида:

\[
\int_{a}^{b} f(x) d x=\lim _{\eta \rightarrow b} \int_{a}^{\eta} f(x) d x, \quad-\infty<a<b \leqslant+\infty,(*)
\]

где функция $f(x)$ интегрируема по Риману (или по Лебегу) на любом отрезке $[a, \eta], a \leqslant \eta<b$.

Для абсолютной сходимости интеграла (*) необходимо и достаточно (к р и т е р и й К ош и абсолютной сходимости несобственного интеграла), чтобы для любого $\varepsilon>0$ существовало такое $\eta_{\varepsilon}, a \leqslant \eta_{\varepsilon}<b$, что для всех $\eta^{\prime}$ и $\eta^{\prime \prime}, \eta_{\varepsilon} \leqslant \eta^{\prime}<b, \eta_{\varepsilon} \leqslant \eta^{\prime \prime}<b$, выполнялось неравенство

\[
\left|\int_{\eta^{\prime}}^{\eta^{\prime \prime}}\right| f(x)|d x|<\varepsilon
\]

Если несобственный интеграл абсолютно сходится, то он равен интегралу Лебега от рассматриваемой функции. Существуют несобственные интегралы, сходящиеся, но не абсолютно сходящиеся, напр.

\[
\int_{0}^{+\infty} \frac{\sin x d x}{x}
\]

Чтобы определить сходится или нет заданный интеграл абсолютно, полезно использовать признаки сходимости несобственных интегралов от неотрицательных функций; напр., с помощью сравнения признака устанавливается абсолютная сходимость интеграла

![](https://cdn.mathpix.com/cropped/2023_07_08_860e6232aed7e8296033g-1.jpg?height=82&width=231&top_left_y=1802&top_left_x=425)

Для кратных несобственных интегралов (в большей части имеющихся определений) связь сходимости и абсолютной сходимости интегралов другая. Пусть на открытом множестве $G$-мерного евклидова пространства определена функция $f(x)$. Если для любой последовательности кубируемых областей $G_{k}, k=1,2, \ldots$, монотонно исчерпываюей область $G$ (т. е. $G_{k} \subset \bar{G}_{k} \subset$ $\left.\subset G_{k+1}\right)$ и

\[
\bigcup_{k=1}^{\infty} G_{k}=G
\]

существует при $k \rightarrow \infty$ предел интегралов Римана

\[
\int G_{k} f(x) d x
\]

И этот предел не зависит от выбора указанной последовательности областей, то он обычно и наз. несобственным интегралом

\[
\int_{G} f(x) d x
\]

Так определенный интеграл сходится тогда и только тогда, когда он абсолютно сходится. Существуют и другие определения несобственных кратных интегралов. Напр., для функции $f(x)$, определенной на всем пространстве $E^{n}$ и интегрируемой по Риману на любом $n$-мерном шаре $Q_{r}$ радиуса $r<+\infty$, можно определить несобственный интеграл по $E^{n}$ равенством

\[
\int_{E^{n}} f(x) d x=\lim _{r \rightarrow \infty} \int Q_{r} f(x) d x .
\]

В этом случае из абсолютной сходимосіи интеграла снова следует просто сходимость, но обратное неверно.

Лит.: [1] И л ь и н В. А., П о з н я к Э. Г., Основы математического анализа, ч. 2, М., 1973; [2] К у д р я в ц е в Л. Д., Математический анализ, т. 1,2 изд., М., 1973; 2 н и к о льс к и й С. М., Курс математического анализа, Д. изд., т. 1,
М., 1975.

АБСОЛютНо СХОДЯЩИЙСЯ РЯД - ряд

\[
\sum_{n=1}^{\infty} u_{n}
\]

c (вообще говоря) комплексными членами, для к-рого сходится ряд

\[
\sum_{n=1}^{\infty}\left|u_{n}\right|
\]

Для абсолютной сходимости ряда (1) необходимо и достаточно (к р и т е р и й К о ш и абсолютной сходимости ряда), чтобы для любого $\varepsilon>0$ существовал такой номер $n_{\varepsilon}$, что для всех номеров $n>n_{\varepsilon}$ и всех целых $p \geqslant 0$ выполнялось неравенство

\[
\sum_{k=n}^{n+p}\left|u_{k}\right|<\varepsilon
\]

Если ряд абсолютно сходится, то он сходится. Ряд

\[
\sum_{n=1}^{\infty} \frac{i^{n}}{n^{2}}
\]

абсолютно сходитсл $(i=\sqrt{-1})$, а ряд

\[
\sum_{n=1}^{\infty} \frac{(-1)^{n}}{n}
\]

сходится, но не абсолютно. Пусть

\[
\sum_{m=1}^{\infty} u_{m}^{*}
\]

- ряд, составленный из тех же членов, что и ряд (1), но взятых, вообще говоря, в другом порядке. Из абсолютной сходимости ряда (1) следует и абсолютная сходимость ряда (3), и ряд(3) имеет ту же самую сумму, что и ряд (1). Если ряды

\[
\sum_{n=1}^{\infty} u_{n} \quad \text { и } \sum_{n=1}^{\infty} v_{n}
\]

абсолютно сходятся, то: любая их линейная комбинация

\[
\sum_{n=1}^{\infty} \lambda u_{n}+\mu v_{n}
\]

также абсолютно сходится; ряд, полученный из всевозможных попарных произведений $u_{m} v_{n}$ членов этих рядов, расположенных в произвольном порядке, также абсолютно сходится и его сумма равна произведению сумм данных рядов. Перечисленные свойства абсолютно сходящихся рядов переносятся и на кратные ряды

\[
\sum_{\left(n_{1}, n_{2}, \ldots, n_{k}\right)} u_{n_{1}, n_{2}, \ldots, n_{k}} .
\]