Отношение степени многочлена $P_{n}(f ; x)$ к числу точек, в к-рых $P_{n}(f ; x)$ совпадает с $f(x)$, равно $(n-1) /(n-q)$, которое пріІ $n \rightarrow \infty$ стремится к $2 l /(2 l-1)$; при $l$ достаточно большом этот предел сколь угодно близок к единице. Б. ІІ. п. указан С. Н. Бернштейном в 1931 (см. [1]).

![](https://cdn.mathpix.com/cropped/2023_07_08_090272fb00e093dfa604g-1.jpg?height=57&width=826&top_left_y=355&top_left_x=127)

![](https://cdn.mathpix.com/cropped/2023_07_08_090272fb00e093dfa604g-1.jpg?height=40&width=792&top_left_y=402&top_left_x=156)
т е л ьны $\mathbf{x}$ ф ун к ц й й,- метод, применяемый в теории линейных и нелинейных дифференциалыных уравнений с частными производными. Б. м. состоит в введении нек-рых новых (вспомогательных) функций, зависящих от искомого решения и позволяющих устанавливать для этого решения априорные оценки максимума модуля производных требуемого порядка.

Простым примером применения Б. м. является априорная оценка модуля производных решения задачи Дирихле для нелинейного (квазилинейного) эллиптич. уравнения

\[
\left.\begin{array}{c}
\frac{\partial^{2} z}{\partial x^{2}}+\frac{\partial^{2} z}{\partial y^{2}}=f\left(x, y, z, \frac{\partial z}{\partial x}, \frac{\partial z}{\partial y}\right) \equiv \\
\equiv a\left(\frac{\partial z}{\partial x}\right)^{2}+2 b \frac{\partial z}{\partial x} \frac{\partial z}{\partial y}+c\left(\frac{\partial z}{\partial y}\right)^{2}+ \\
\quad+2 d \frac{\partial z}{\partial x}+2 e \frac{\partial z}{\partial y}+g \text { в круге } D
\end{array}\right\}
\]

где $a, b, c, d, e, g$ - гладкие функции от $x, y, z ;$ $C$ - окружность, граница круга $D$ с радиусом $R$ (предположение о том, что $D-$ круг, а $\left.z\right|_{C}=0$, не существенно, ибо общий случай произвольной односвязной области и неоднородного граничного условия легко приводятся к рассматриваемому случаю с помощью замены функции и конформного преобразования области).

Если $f_{z}^{\prime} \geqslant 0$, то оценка максимума модуля $n$

\[
n=\max _{(x, y) \in D+C}|z(x, y)|
\]

решения задачи (*) сразу получается из принципа максимума.

Для доказательства существования регулярного рещения задачи (*) достаточно иметь априорные оценки максимума модуля производных решения до 3-го порядка (см. Продолжения по параметру метод). Для оценки $\max _{C}\left|\frac{\partial z}{\partial x}\right|$ и $\max _{C}\left|\frac{\partial z}{\partial y}\right|$ достаточно оценить $\max _{C} \frac{\partial z}{\partial \rho} \quad$ (т. к. $\left.\left.z\right|_{C}=0\right), \quad \rho, \theta$ - полярные координаты в круге $D$. Пусть введена новая (вспомогательная) функция $u$ по формуле

\[
z=\varphi_{1}(u)=-n-\alpha+\alpha \ln u,
\]

где $\alpha>0$ будет выбрано позже. Функция $u=u(x, y)$ изменяется от $e$ до $e^{(2 n+\alpha) / \alpha}$ и в том же направлении, чтө и $z(x, y)(-n \leqslant z \leqslant n)$. Так как

\[
\begin{gathered}
\frac{\partial z}{\partial x}=\frac{\alpha}{u} \frac{\partial u}{\partial x}, \\
\frac{\partial^{i} z}{\partial x^{2}}=\frac{\alpha}{u} \frac{\partial^{2} u}{\partial x^{2}}-\frac{\alpha}{u^{2}}\left(\frac{\partial u}{\partial x}\right)^{2},
\end{gathered}
\]

И аналогично для производных по $y$, то $u$ удовлетворяет уравнению:

\[
\begin{gathered}
\frac{\partial^{2} u}{\partial x^{2}}+\frac{\partial^{2} u}{\partial y^{2}}=\frac{1}{u}\left[\left(\frac{\partial u}{\partial x}\right)^{2}+\left(\frac{\partial u}{\partial y}\right)^{2}\right]+ \\
+\frac{\alpha}{u}\left[a\left(\frac{\partial u}{\partial x}\right)^{2}+2 b \frac{\partial u}{\partial x} \frac{\partial u}{\partial y}+c\left(\frac{\partial u}{\partial y}\right)^{2}\right]+ \\
+2 d \frac{\partial u}{\partial x}+2 e \frac{\partial u}{\partial y}+g \frac{u}{\alpha} \equiv Q
\end{gathered}
\]

Пусть $M$ - верхняя грань $|a|,|b|,|c|$ в $D$, а $\alpha=1 / 8 M$. Если рассматривать $\frac{\partial u}{\partial x}$ и $\frac{\partial u}{\partial y}$ как текущие координаты на плоскости, а $x, y, z$ как параметры, то уравнение $Q=0$ есть уравнегие эллипса, т. к. определитель $a_{1} c_{1}-b_{1}^{2}>3 / 4 u^{2}$, где

$a_{1}=\frac{1}{u}\left(1+\frac{a}{8 M}\right), \quad b_{1}=\frac{b}{8 M u}, \quad c_{1}=\frac{1}{u}\left(1+\frac{c}{8 M}\right)$.

Таким образом, $Q$ при любых $\frac{\partial u}{\partial x}$ и $\frac{\partial u}{\partial y}$ не меньше нек-рого отрицательного числа $-P, Q \geqslant-P$ (число $P$ легко указать в явном виде). Если ввести функцию $u_{1}$ по формуле

\[
u_{1}=u+\frac{P}{4}\left(x^{2}+y^{2}\right)
\]

TO

\[
\frac{\partial^{2} u_{1}}{\partial x^{2}}+\frac{\partial^{2} u_{1}}{\partial y^{2}}=Q+P \geqslant 0
\]

и $u_{1}$ достигает максимума на границе $C$ области $D$, a так как $u_{1}$ постоянна на $C$, то

\[
\frac{\partial u_{1}}{\partial \rho} \geqslant 0 \quad \text { и } \quad \frac{\partial u}{\partial \rho} \geqslant-\frac{1}{2} P R,
\]

$R$ - радиус окружности $C$. Отсюда может быть найдена отрицательная нижняя грань для $\frac{\partial z}{\partial \rho}:$

\[
\frac{\partial z}{\partial \rho}=\frac{\alpha}{u} \frac{\partial u}{\partial \rho} \geqslant-\frac{\alpha P R}{2 e^{(n+\alpha) / \alpha}} .
\]

Применение тех же рассуждений к другой вспомогательной функции $u$

\[
z=\varphi_{2}(u)=-n-\alpha+\alpha \ln \frac{1}{1-u}
\]

позволяет получить оценку сверху

\[
\frac{\partial z}{\partial \rho} \leqslant \frac{\alpha P_{1} R}{2} e^{(n+\alpha) / 2}
\]

Таким образом, оценивается $\underset{C}{\max }\left|\frac{\partial z}{\partial \rho}\right|$, а значит, и $\max _{C}\left|\frac{\partial z}{\partial x}\right|$ и $\max _{C}\left|\frac{\partial z}{\partial y}\right|$. Оценка максимума модуля первых производных внутри области $D$ проводится аналогично: вводится вспомогательная функция $u$ по формуле

\[
z=\varphi_{3}(u)=-n+\alpha \ln \ln u .
\]

Функция $u$ изменяется в том же направлении, что и $z$, от $e$ до $e^{e^{2 n / \alpha}}$. Для $и$ из (*) следует

$\frac{\partial^{2} u}{\partial x^{2}}+\frac{\partial^{2} u}{\partial y^{2}}=\frac{1}{u \ln u}\left[(1+\ln u+\alpha a)\left(\frac{\partial u}{\partial x}\right)^{2}+2 \alpha b \frac{\partial u}{\partial x} \frac{\partial u}{\partial y}+\right.$

$\left.+(1+\ln u+\alpha c)\left(\frac{\partial u}{\partial y}\right)^{2}\right]+2 d \frac{\partial u}{\partial x}+2 e \frac{\partial u}{\partial y}+g \frac{u \ln u}{\alpha} \equiv Q_{1}$.

Рассуждения, подобные приведенным, показывают, что если функция

\[
w=\left(\frac{\partial u}{\partial x}\right)^{2}+\left(\frac{\partial u}{\partial y}\right)^{2}
\]

достигает максимума в области $D$, то этот максимум не превосходит некоторого числа, зависящего лишь от $n$ и $M$. Это дает требуемую оценку $\underset{D}{\max }\left|\frac{\partial z}{\partial x}\right|$ и $\max _{D}\left|\frac{\partial z}{\partial y}\right|$

Б. м. позволяет аналогичным образом оценить и максимум модуля в области $D+C$ всех старших производных решения (при этом дополнительно надо лишь дифференцировать исходное уравнение (\%)).

Б. м. впервые был применен С. Н. Бернштейном [1]. В дальнейшем Б. м. развивался и систематически употреблялся при изучении различных задач для әллипти-