индуцирует на множестве классов эквивалентных центральных простых конечномерных алгебр структуру абелевой группы, к-рая и наз. Б. г. поля $k$ и обозначается Brk. Нулевым элементом этой группы служит класс полных матричных алгебр, а обратным элементом к классу алгебры $A$ - класс ее инверсной алгебры. Каждый ненулевой класс содержит ровно одну, с точностью до изоморфизма, $k$-алгебру с делением (т. е. тело над $k$ ).

Б. г. была определена и изучалась в серии работ P. Брауэра (R. Brauer), Э. Нётер (E. Noether), A. Алберта (A. Albert), X. Xacce (H. Hasse) и др. начиная с 20-х гг. 20 в. (см., напр., [6]). Наиболее законченные результаты, вплоть до полного вычисления Б. г., были получены для числовых полей в связи с развитием полей классов теории. В терминах Б. г. формулируется общая форма закона взаимности.

Б. г. равна 0 для любого сепарабельно замкнутого поля и любого конечного поля. Для поля действительшых чисел Б. г. есть циклич. группа 2-го порядка и ее ненулевой элемент - класс алгебры кватернионов. Если $k$ - поле $p$-адических чисел или любое полное дискретно нормированное локально компактное поле, то его Б. г. изоморфна $\mathrm{Q} / \mathrm{Z}$ (здесь $\mathrm{Q}$ - аддитивная группа рациональных чисел, $Z$ - аддитивная группа целых чисел). Этот факт занимает важное место в локальной теории полей классов.

Пусть $k$ - поле алгебраич. чисел конечной степени или поле алгебраич. функций от одной переменной с конечным полем констант. Тогда имеет место точная последовательность групп:

\[
0 \longrightarrow \operatorname{Br} k \stackrel{\operatorname{inv}}{\longrightarrow} \sum v \operatorname{Br} k_{v} \stackrel{\Sigma}{\longrightarrow} \mathrm{Q} / \mathrm{Z} \longrightarrow 0
\]

где $v$ пробегает всевозможные нормирования поля $k$, $k_{\nu}$ - соответствующие пополнения поля $k$, гомоморфизм inv индуцируется естественными вложениями $k \rightarrow k_{v}$. Образ элемента из $\mathrm{Br} k$ в $\mathrm{Br} k_{v}$ наз. ло к а л ь ны м и н в а р и а н т о м, гомоморфизм $\Sigma$ является суммированием локальных инвариантов. Этот факт устанавливается в глобальной теории полей классов. Если $k-$ поле алгебраич. функций от одной переменной над алгебраически замкнутым полем констант, то его Б. г. нулевая (т е о р е м а Т з е н а). Случай произвольного поля констант разобран в [4] и [7].

Б. г. функториально зависит от $k$, т. е. если $K-$ расширение поля $k$, то определен гомоморфизм $\mathrm{Br} k \rightarrow$ $\rightarrow \mathrm{Br} K$. Его ядро, обозначаемое $\operatorname{Br}(K / k)$, состоит из классов алгебр, распадающихся над $K$.

Конструкции скрещенных произведений с помощью систем факторов (см. [5]) приводят к когомологич. интерпретации Б. г. Для любого нормального расширения $K / k$ имеет место изоморфизм

\[
\mathrm{Br}(K / k) \cong H^{2}\left(K, K^{*}\right),
\]

где $H^{2}\left(K, K^{*}\right)-$ группа двумерных когомологий Галуа с коэффициентами в мультипликативной группе $K^{*}$ поля $K$. Более того, группа $\mathrm{Br} k$ изоморфна $H^{2}\left(\bar{k}, \bar{k}^{*}\right)$, где $\bar{k}$ - сепарабельное замыкание поля $k$. Сопоставление центральной простой алгебре ее класса в Б. г. осуществляется при помощи кограничного оператора

\[
\delta: H^{1}(K, \quad \operatorname{PGL}(n, K)) \rightarrow H^{2}\left(K, \quad K^{*}\right)
\]

в когомологич. последовательности, соответствующей точной последовательности групп

\[
1 \rightarrow K^{*} \rightarrow \mathrm{GL}(n, \quad K) \rightarrow \operatorname{PGL}(n, K) \rightarrow 1,
\]

где $\mathrm{GL}(n, K)$ и $\mathrm{PGL}(n, K)$ - линейная п проективная группы матриц порядка $n \times n$. Здесь группа $H^{1}(K$, PGL $(n, K)$ ) интерпретируется как множество классов с точностью до $k$-изоморфизма центральных простых алгебр ранга $n^{2}$ над полем $k$, распадающихся над $k$, или как множество классов $k$-изоморфных Брауэра -

-18 Математичсская энц., т. 1 Севери многообразий размерности $n-1$, имеющих $K$ точку.

Б. г. всегда является периодической группой. Порядок любого ее элемента делит число $n$, где $n^{2}-$ ранг тела, представляющего этот әлемент.

Когомологич. интерпретация Б. г. позволяет рассматривать ее как группу классов центральных расширений группы Галуа сепарабельного замыкания $\bar{k} / k$ при помощи группы $\bar{k}^{*}$.

Обобщением понятия Б. г. является г р у п п а Б р ау ә р а - Г р о т е д и к а, определяемая аналогично Б. г. с заменой центральных простых алгебр на алгебры Адзумая (см. [7]).

Лит.: [1] Алгебраическая теория чисел, пер. с англ., М., 1969; [2] Б у р б а к и Н., Алгебра. Модули, кольца, формы, пер. с франц., М., 1966; [3] С е p p Ж.-П., Когомологии Галуа, пер. с франц., М., 1968; [4] Ф а д д е е в Д. К. «Вестник Ленингр. ун-та", 1957, № 7, в. 2, c. 45-51; [5] Ч е б о т a p e в M., «Älgebren», 2 Aufl., B., 1968, Bd 4; [7] Ğ ro t h e n d i e c k A., B KH.: Dix exposés sur la cohomologie des schémax, Amst., 1968, p. 46-188. B. A. Исковских.

![](https://cdn.mathpix.com/cropped/2023_07_08_528d476d66d9d67349f2g-1.jpg?height=35&width=794&top_left_y=789&top_left_x=1027)
Б р а у ә а а лге б р a, - дистрибутивная решет$\kappa a$, в к-рой для каждой пары әлементов $a, b$ существует элемент, наз. П с е в д о р а 3 н о с т ь ю (часто обозначаемый через $a$ * $b$ ), являющийся наименышим среди элементов $c$ со свойством $b+c \geqslant a$. Возможно эквивалентное описание Б. р. как многообразия универсальных алгебр с тремя бинарными операциями $\cup, \cap$ и , удовлетворяющими нек-рым аксиомам. Термин «Брауәра алгебра» был введен ввиду наличия связи Б. р. с интуиционистской логикой Брауэра (L. E. J . Brouwer). Чаще вместо Б. р. используются так наз. п с е в д обуле вы ал ге б ры, теория к-рых двойственна теории Б. р. Любая Б. р. превращается в псевдобулеву алгебру при введении нового порядка $\left(a \leqslant{ }^{\prime} b\right) \rightleftarrows(b \leqslant a)$, новых объединений п пересечений по формулам

$\left(a \bigcup^{\prime} b\right) \rightleftarrows(a \bigcap b), \quad\left(a \bigcap^{\prime} b\right) \rightleftarrows(a \bigcup b)$

иоперации относительного псевдод о по л не ния $a \Rightarrow b$, совпадающей с псевдоразностью $a$ * $b$. Обратно, любая псевдобулева алгебра может быть рассматриваема как Б. р. Иногда термин «Б. р." используется для псевдобулевых алгебр (см., напр., [2]).

Jum.: [1] M a c K i n s e y J. C. C., T a r s k i A., "Ann. Math.", 1944, v. 45, p. 141-91; [2] Б и р к г о ф Г.. Теория
структур, пер. с англ., M., 1952. БРАУӘРА ТЕОРЕМА - 1) Б. Т. н е П о д в И Жн о й то ч к е: при непрерывном отображении $f: S \rightarrow$ $\rightarrow S$ n-мерного симплекса $S$ в себя существует по крайней мере одна точка $x \in S$ такая, что $f(x)=x$; доказана Л. Брауэром [1]. Эквивалентное утверждение было несколько ранее доказано П. Г. Болем [2]. Б. т. распространяется на непрерывные отображения замкнутых выпуклых тел $n$-мерного топологического векторного пространства и имеет широкие применения в доказательствах теорем существования решений различных уравнений. Б. т. обобщается на бесконечномерные топологич. векторные пространства.

Jum.: [1] B r o u w e r L. E. J., "Math. Ann.», 1910, Bd 69, S. 176-80; [2] B o h l P. G., "J. reine u. angew. Math.", 1904,

![](https://cdn.mathpix.com/cropped/2023_07_08_528d476d66d9d67349f2g-1.jpg?height=49&width=811&top_left_y=1990&top_left_x=999)
при всяком гомеоморфном отображении подмножества $A$ евклидова пространства $E^{n}$ на подмножество $B$ того же пространства любая внутренняя точка $A$ (относительно $E^{n}$ ) переходит во внутреннюю точку $B$ (относительно $E^{n}$, а любая невнутренняя точка переходит в невнутреннюю. Доказана Л. Брауэром [1].

Jum.: [1] B r o u w e r L. E. J., "Math. Ann.», 1912, Bd 71, 97-115.

БРАУУРА - СЕВЕРИ МНОГООБРАВИЕ - алгеб $p a-$ ическое многообразие над полем $k$, которое, если его