Born), Дж. Грин (G. Green), Дж. Кирквуд (J. G. Kirkwood), Дж. Ивон (J. Yvon) - цепочка уравнений (иерархия) для одночастичных, двухчастичных и т. д. функций распределения классической статистич. системы. Эти функции определяются как

\[
\begin{gathered}
F_{s}\left(t, \boldsymbol{r}_{1}, \ldots, \boldsymbol{r}_{s}, \boldsymbol{p}_{1}, \ldots, \boldsymbol{p}_{s}\right)= \\
=V^{s} \int w_{N} d \boldsymbol{r}_{s+1} \ldots . d \boldsymbol{r}_{N} d \boldsymbol{p}_{s+1} \ldots d \boldsymbol{p}_{N}
\end{gathered}
\]

где $s=1,2, \ldots, V$ - объем системы, а $w_{N}$ есть $N$-частичная нормированная на единицу функция распределения, удовлетворяющая Лиувилля уравнению

\[
\frac{\partial w_{N}}{\partial t}=\left\{H, w_{N}\right\}
\]

где фигурные скобки - Пуассона скобки, а $H$ есть гамильтониан системы. Б. ц. У. в предельном статистич. случае $V \rightarrow \infty, V / N=v=$ const имеет вид уравнения для $F_{s}$ со специфич. «зацеплением» с функцией $F_{s+1}$ более высокого ранга:

\[
\begin{gathered}
\frac{\partial F_{s}}{\partial t}-\left\{H_{s}, F_{s}\right\}= \\
=\frac{1}{v} \int\left\{\sum_{1 \leqslant i \leqslant s} \Phi\left(\left|\boldsymbol{r}_{i}-\boldsymbol{r}_{s+1}\right|\right), F_{s+1}\right\} d \boldsymbol{r}_{s+1} d \boldsymbol{p}_{s+1},
\end{gathered}
\]

где $\Phi\left(\left|\boldsymbol{r}_{i}-\boldsymbol{r}_{s+1}\right|\right)$ - потенциал взаимодействия $i$-й и $(s+1)$-й частиц, а $H_{s}$ - гамильтониан $s$ частиц системы.

В термодинамически равновесном случае, когда распределение по импульсам каждой частицы является Максвелла распределением, рассматриваются $s$-частичные функции распределения по координатам частиц, к-рые определяются соотношениями типа (1) через $N$-частичную функцию

\[
w_{N}\left(\boldsymbol{r}_{1}, \ldots, \boldsymbol{r}_{N}\right)=\frac{1}{Q} \exp \left(-\frac{H_{1}}{\theta}\right),
\]

где $H_{1}=H-H_{0}$, причем $H_{0}$ есть сумма кинетич. энергий частиц системы, а конфигурационный интеграл $Q$ определяется из условия нормировки (4). Б. ц. у. для этих функций имеет вид:

\[
\begin{gathered}
\frac{\partial F_{s}}{\partial x_{1}}+\frac{1}{\theta} \frac{\partial U_{s}}{\partial x_{1}} F_{s}+ \\
+\frac{1}{\theta} \frac{1}{v} \int \frac{\partial \Phi\left(\left|r_{1}-r_{s+1}\right|\right)}{\partial x_{1}} F_{s+1} d r_{s+1}=0,
\end{gathered}
\]

где $U_{s}-$ потенциальная энергия взаимодействия $s$ частиц системы.

При помощи функций распределения, гл. обр. $F_{1}$ и $F_{2}$, могут быть выражены все специфические характеристики статистич. систем. Основные трудности исследования Б. ц. у. (3) или (5) связаны с проблемами замыкания системы (расцепление Б. ц. у.) и решения замкнутой системы со специальными предельными условиями для функций $F_{s}$. Это исследование специфично для физич. систем различного типа и наиболее разработано для случаев короткодействия, когда $r_{0}^{3} / v \ll 1$, где $r_{0}$ - эффективный радиус взаимодействия частиц друг с другом, и для случаев дальнодействия, когда $r_{0}^{3} / v \gg 1$, в частности для системы с кулоновским взаимодействием. Во временной теории это приводит непосредственно к кинетич. Больцмана уравнению для одночастичной функции $F_{1}$ или к Власова кинетическому уравнению, а в равновесной теории - к вириальному разложению для термодинамич. потенциала или к специфическим кулоновским поправкам.

При рассмотрении квантовых статистич. систем Б. ц. У. составляется для $s$-частичных статистич. квантовых операторов $\left\langle x_{1}, \ldots, x_{s}\left|F_{s}\right| x_{1}^{\prime}, \ldots, x_{s}^{\prime}\right\rangle$, являющихся следами по переменным $s+1, \ldots, N$ частиц общего $N$-частичного оператора - матрицы плотности. Эти уравнения имеют вид, аналогичный уравнениям (3), в к-рых классич. скобки Пуассона заменены квантовыми скобками.

Лит.: [1] Б о г о лю б о в Н. Н., Избр. тр., т. 2, К., 1970, c. $99-196 ;[2]$ е г о же, там же, с. $227-493 ;$ [3] у л е н 6 е к с англ., М., 1965 ., Лекции по статистической механике, пер.

БОЗЕ - ӘЙНIIITEИНА СТАТИСТИКА, Б $о$ в е с т ат и с т и к а,- квантовая статистика, применяемая к системам тождественных частиц с целым спином $(0,1,2$, .... в единицах $\hbar=1,05 \cdot 10^{-27}$ әрг.сек). Предложена III. Бозе (S. Bose) и А. Эйнштейном (A. Einstein) в 1924. Согласно этой статистике, в каждом квантовом состоянии может находиться произвольное число частиц. B. Паули (W. Pauli) доказал, что тип квантовой статистики однозначно связан со спином частиц, так как совокупности частиц с целым спином подчиняются Б. - Э. с., а с полуцелым спином - Ферми - Дирака статистике.

Состояние системы многих частиц в квантовой механике определяется волновой функцией, к-рая в случае тождественных частиц может быть либо симметричной по отношению к перестановкам любой пары частиц (для частиц с целым спином), либо антисимметричной (для частиц с полуцелым спином). Для системы частиц, подчиняющихся Б.-Э. с., состояния описываются симметричными волновыми функциями, что является другой, эквивалентной формулировкой Б.-Э. с. Системы из большого числа частиц, подчиняющихся Б. - . с., наз. с и с т е м а м и Бо о е, например газом Бозе.

Для идеального квантового газа, т. е. для системы тождественных частиц с массой $m$ без взаимодействия, находящихся в кубе объема $V=L^{3}$, квантовые одночастичные уровни энергии равны

\[
\varepsilon_{p}=p^{2} / 2 m
\]

где $p$ - собственные значения импульса отдельной частицы: $p=2 \pi \hbar n / L, n$ - вектор с целочисленными (положительными, отрицательными или равными нулю) компонентами.

Квантовое состояние идеального газа определяется заданием совокупности чисел заполнения уровней $\left\{n_{p}\right\}$, где каждое $n_{p}$ указывает число частиц в одночастичном состоянии $p$. Для систем Бозе $n_{p}=0,1,2, \ldots$

Для больших систем уровни энергии расположены очень плотно и стремятся к непрерывному спектру при $V \rightarrow \infty$. Пусть уровни сгруппированы по малым ячейкам, содержащим $G_{i}$ уровней в ячейке. Каждой ячейке соответствует средняя энергия $\varepsilon_{i}$, число $G_{i}$ предполагается очень большим. Состояние системы определяется набоғом $\left\{N_{i}\right\}$, где $N_{i}$ есть сумма $n_{p}$ по уровням ячейки. С т а т и с т и ч е с к и й в е с, т. е. число различных распределений частиц по ячейкам, равен

\[
W\left\{N_{i}\right\}=\prod_{i} \frac{\left(G_{i}+N_{i}-1\right) !}{N_{i} !\left(G_{i}-1\right) !}
\]

И определяет вероятность распределения частиц по ячейкам, характеризуемым числами заполнения $n_{1}, n_{2}$. щее заданной энергии $E$ и числу частиц $N$ :

\[
E=\sum_{i} \varepsilon_{i} N_{i}, \quad N=\sum_{i} N_{i}
\]

находится из экстремума (1) при дополнительных условиях (2). Соответствующие средние числа заполнения равны

\[
\bar{n}_{i}=\frac{\bar{N}}{G_{i}}=\frac{1}{e^{\beta\left(\varepsilon_{i}-\mu\right)-1}},
\]

где $\mu-$ химич. потенциал $\beta=1 / k T, k-$ постоянная Больцмана (универсальная постоянная $k=1,38 \cdot 10^{-16}$ эра/ әрад), $T$ - абсолютная температура. Величины $\beta$ и $\mu$ находятся из условий (2).

17 Математическая әнц., т. 1