входному каналу в каждый тактовый момент в устройство поступают сігналы - буквы входного алфавита. В те же моменты по выходному каналу устройство выдает сигна.ты - буквы выходного алфавита. С соответствующей точки зрения, к таким устройствам могут быть отнесены бормальные системы, реальные автоматы, живые організмы і т. П.

Существуют различные подходы к определению понятия А. к. При м а к р о по д х о д е, т. е. когда интересуются только внешним поведением устройств, определение А. к. может быть дано в виде совокупности функций, лшбо в виде конечного ориентированного графа, либо в алгеб́раич. форме - в виде конечной алгебры с унарнымі операциями (см. А втоматов способы задания). При м ІІ к р о П о д х о д е А. к. задается множеством элементов и схемой их соединения, т. е. в этом случае кроме функционирования описывается и строение автомата, в связи с чем это понятие обычно наз. с т р ук т у р ным, а сами А. к.- с т р ук т у рными а т то ат ами, или автоматным и с е т я м іI.

Макроподход. А. к.- это система $(A, S, B, \varphi, \psi)$, где $A, S, B$ - конечные, как правило непустые, аліфавиты, наз., соответственно, в х о д ны м а л ф а в и то м, множеством состоянийивыходным алфавн т о м; $\uparrow-ф$ ункц и я п е р е х о д о в, отображающая множество $S \times A$ в $S ; \psi-ф$ у н ц и я в ы х од о в, отобразкающая $S \times A$ в $B$. Такие А. к. иногда называются а в т о а т а м и М и ли. В случае, когда функция выходов $\psi$ отображает $S$ в $B$ (т. е. не зависит от букв входного алфавита), А. к. называют а втом а т о м М у ра. Всякий автомат Мура является автоматом МиліІ.

Важнейшей характеристикой А. к. является его поведение (см. Автолата поведение), к-рое может быть определено по-разному. В зависимости от того, какой тІп поведения рассматривается, А. к. подразделяются на преобразователіг, акцепторы (распознаватели), генераторы и др. Чтобы определить основные виды поведения А. к., функциІ $\varphi$ и $\psi$ распространяют на множество $S \times A$ * (где $A$ * - множество всех слов в алфавите $A$, включая пустое слово $\wedge)$ :

$\varphi(s, \wedge)=s, \quad \varphi(s, \alpha a)=\varphi(\varphi(s, \alpha), a)$, $\psi(s, \wedge)=\wedge, \quad \psi(s, \alpha a)=\psi(\varphi(s, \alpha), a)$

(здесь $s \in S, \alpha \in A^{*}, a \in A$, а запись $\alpha a$ обозначает слово, получаемое путем приписывания буквы $a$ к слову $\alpha$ ). Таким образом распространенные функции $\varphi(s, \alpha)$, $\psi(s, \alpha)$ для произвольных $s$ и $\alpha$ описывают соответственно состояніг, в к-рое переходит автомат из состояния $s$ под действіем входного слова $\alpha$, и выходную букву, Һ-рая выдается автоматом в момент поступления последней буквы входного слова $\alpha$. Пусть $\alpha$ ] обозначает начало длины $n$ слова $\alpha$ и $\bar{\varphi}(s, \alpha), \bar{\psi}(s, \alpha)-$ слова в алфавитах $S$ и $B$, определяемые следующим образом: $\bar{\varphi}(s, \alpha)=\varphi(s, \alpha]) \varphi(s, \alpha]) \ldots \varphi(s, \alpha)$, $\bar{\psi}(s, \alpha)=\psi(s, \alpha]) \psi(s, \alpha]) \ldots \psi(s, \alpha)$.

Функции $\bar{\psi}(s, \alpha), \bar{\psi}(s, \alpha)$ описывают уже последовательность всех состояниї, в к-рых находился автомат при поступлении в него букв слова $\alpha$, а также выходное слов0, т. е. последовательность букв выходного алфавита, выдаваемых автоматом под воздействием входного слова $\alpha$. Тернарное отношение

\[
F=\left\{(\alpha, \bar{\varphi}(s, \alpha), \bar{\psi}(s, \alpha)): \alpha \in A^{*}, s \in S\right\}
\]

наз. ф у н к ц і о н II р о в ан и е м А. к. $\mathfrak{U}=(A, S$, $B, \varphi, \psi)$. Функціп $\bar{\varphi}$ І $\bar{\psi}$ естественно распространяются І на бесконечные последовательности (с в е р х с л о- в а) в алфавите $A$. Поэтому под функционированием А. к. иногда понимают отношение вида $F$, в к-ром $\alpha-$ произвольное сверхслово. В этом случае значение функции $\varphi(s, \alpha)$ определяется как множество всех тех и только тех состояний, к-рые встречаются в последовательности $\bar{\varphi}(s, \alpha)$ бесконечное число раз.

А. к. с выделенным начальным состоянием $s_{1}$ наз. и ни ци а ль ным и обозначается $\mathfrak{A}_{s_{1}}$. П о в е д ени е м ин и ц и а ль но г о А. к. $\mathfrak{A}_{s_{1}}$ наз. обычно одно из следующих трех отношений.

1) Функция $f(\alpha)=\bar{\psi}\left(s_{1}, \alpha\right)$, отображающая $A^{*}$ в $B^{*}$ (или $A^{\infty}$ в $B^{\infty}$, где $A^{\infty}, B^{\infty}$ - множества всех сверхслов в алфавитах $A$ и $B$ соответственно). Эта функция наз. функцией вычислимой, или реализуемой, инициальным А. к. $\mathfrak{A}_{s_{1}}$.

2) Множество $\stackrel{L_{S}}{ } \subseteq A^{*}$, определяемое для выделенного множества $S^{\prime} \subseteq S$ з а л ю ч и т е л ь ны х с о ст о я н и й так:

\[
L_{S^{\prime}}=\left\{\alpha \in A^{*}: \varphi\left(s_{1}, \alpha\right) \in S^{\prime}\right\}
\]

Множество $L S^{\prime}$ наз. с о б ы т и е м, п р е д с т а в им ы м А. к. $\mathfrak{A}_{s_{1}}$ с множеством $S^{\prime}$ заключительных состояний.

3) Множество значений функции $f(\alpha)=\bar{\psi}\left(s_{1}, \alpha\right)$ для всевозможных $\alpha$ из $A$ *, называемое множеством, перечислимым данным А.К. $\mathfrak{A}_{s_{1}}$.

4) Множество $M_{\gamma} \sqsubseteq A^{\infty}$, определяемое для системы $\gamma$ подмножеств множества $S$ следующим образом:

\[
M_{\gamma}=\left\{\alpha \in A^{\infty}: \varphi\left(s_{1}, \alpha\right) \in \gamma\right\} .
\]

Множество $M_{\gamma}$ наз. сверхсобытием, представимым А. к. $\mathfrak{U}_{s}$ с системой $\gamma$ заключительных подмножеств состояний. А. к. с поведением типа 1) наз. к о н е ч ны м п р е о б р а о в а т е ле м, а с поведением типа 2) коне чным рас познав а те лем, или а кц е П т о р о м.

Если в качестве входного и выходного алфавитов взять декартовы произведения $A_{1} \times \ldots \times A_{m}$ и $B_{1} \times \ldots \times$ $\times B_{n}$, соответственно, то поведением типа 1) будет набор из $n$ функций от $m$ аргументов. В этом случае говорят, что автомат имеет $m$ входов и $n$ выходов, причем алфавиты $A_{1}, \ldots, A_{m}, B_{1}, \ldots, B_{n}$ наз., соответственно, в такого автомата. Класс событий, представимых А. к., и класс функций, вычислимых А. к., могут быть описаны различными математич. средствами. Основной результат состоит в том, что события, представимые А. к., совпадают с так наз. регулярными событиями, а функции, вычислимые А. к., совпадают с ограниченно-детерминированными бункциями. Кроме того, класс множеств, перечислимых А. к., совпадает с классом событий, представимых А. к.

Относительно поведений 2), 3) и 4) автоматы Мура эквивалентны автоматам Мили в том смысле, что для всякого автомата Мили найдется әквивалентный ему, т. е. имеющий то же самое поведение, автомат Мура, и обратно. Для поведения 1) это неверно. Однако, еслі в автоматах Мура вместо $\bar{\psi}$ брать функции вида

\[
\bar{\psi}(s, \alpha)=\psi(\varphi(s, \alpha])) \psi(\varphi(s, \alpha])) \ldots \psi(\varphi(s, \alpha)),
\]

то автоматы Мура будут эквивалентны автоматам Мили.

Автомат мура $\mathfrak{A}=(A, S, B, \varphi, \psi)$ наз. а в т о н о мны м а в тома том, или ге не р а торо м, если функция переходов не зависит от букв входного алфавита. Под по в е де ни е м иници а льного а вт о но м но го а в то м а т а $\mathfrak{A}_{s_{1}}$ принято понимать сверхслово

\[
\psi\left(s_{1}\right) \psi\left(\varphi\left(s_{1}\right)\right) \psi\left(\varphi^{2}\left(s_{1}\right)\right) \ldots,
\]