Функции входят в первый Бәра класс. Имеет место более сильное утверждение: полунепрерывная сверху (снизу) функция, не принимающая значение $+\infty(-\infty)$, есть предел монотонно невозрастающей (неубывающей) последовательности непрерывных функций.

Лит.: [1] Б ә p P., Теория разрывных функций, пер. с фрранц., М.- Л., 1932; [2] Н а т а н с о н И. П., Теория функций вещественной переменной, 2 изд., М., 1957.

БРРА УМНОЖЕЕНИЕ - бинарная отера. Виноградова жестве классов эквивалентных расширений модулей; предложена Р. Бәром [1]. Пусть $A$ и $B$-произвольные модули. Р а с ши р е ни е м $A$ с ядром $B$ наз. точная последовательность:

\[
O \rightarrow B \rightarrow X \rightarrow A \rightarrow O
\]

Расширение (1) наз. эквивалентным расширению $O \rightarrow B \rightarrow X_{1} \rightarrow A \rightarrow O$

если существует гомоморфизм $\alpha: X \rightarrow X_{1}$, включаемый в коммутативную диаграмму:

![](https://cdn.mathpix.com/cropped/2023_07_08_695f9f49f754f06692dfg-1.jpg?height=179&width=367&top_left_y=774&top_left_x=355)

Множество классов эквивалентных расширений обозначается $\operatorname{Ext}(A, B)$. Б. у. на $\operatorname{Ext}(A, B)$ индуцируется следующим образом определенной операцией произведения расширений. Пусть

\[
\begin{aligned}
& 0 \longrightarrow B \stackrel{\beta}{\longrightarrow} X \stackrel{\alpha}{\longrightarrow} A \longrightarrow 0, \\
& 0 \longrightarrow B \stackrel{\boldsymbol{\beta}_{1}}{\longrightarrow} Y \stackrel{\alpha_{1}}{\longrightarrow} A \longrightarrow 0
\end{aligned}
\]

два расширения. В прямой сумме $X \bigoplus Y$ выбираются подмодули

\[
C=\{(x, y) \mid \alpha(x)=\alpha(y)\}
\]

и

\[
D=\left\{(-x, y) \mid x=\beta(b), y=\beta_{1}(b)\right\}
\]

Ясно, что $D \subset C$, так что определен фактормодуль $Z=$ $=C / D$. П р о и в е д е н и е Б э р а расширений (2) и (3) наз. расширение

\[
0 \longrightarrow B \stackrel{\beta_{2}}{\longrightarrow} Z \stackrel{\alpha_{2}}{\longrightarrow} A \longrightarrow 0
\]

где

$\mathbf{a}$

\[
\beta_{2}(b)=[\beta(b), 0]=\left[0, \beta^{\prime}(b)\right]
\]

\[
\alpha_{2}[x, y]=\alpha(x)=\alpha_{1}(y) .
\]

Jum.: [1] B a e r R., "Math. Z.", 1934, Bd 38, S. 374-416; [2] К а р т а н А., Э Й л е н б е р г С., Гомологическая алгебра,

БӘРРИ - ӘССЕЕНА НЕРАВЕНСТВО - неравенство, дающее оценку отклонения функции распределения суммы независимых случайных величин от нормальной функции распределения. Пусть $X_{1}, \ldots, X_{n}$ - независимые одинаково распределенные случайные величины такие, что

\[
\mathrm{E} X_{j}=0, \quad \mathrm{E} X_{j}^{2}=\sigma^{2}>0, \quad \mathrm{E}\left|X_{j}\right|^{3}<\infty .
\]

Пусть

\[
\rho=\frac{E\left|X_{j}\right|^{3}}{\sigma^{3}}
\]

$\mathbf{\Pi}$

\[
\Phi(x)=\frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{x} e^{-t^{2} / 2} d t
\]

тогда для любого $n$

\[
\sup _{x}\left|\mathrm{P}\left\{\frac{1}{\sigma \sqrt{n}} \sum_{j=1}^{n} X_{j} \leqslant x\right\}-\Phi(x)\right| \leqslant A \frac{\rho}{V \bar{n}},
\]

где $A$ - абсолютная положительная постоянная. Этот результат был получен А. Бэрри [1] и независимо от него К.-Г. Эссееном [2].

Jum.: [1] B e r r y A. C., "Trans. Amer. Math. Soc.", 1941 v. 49, № 1, p. 122-36; [2] E s s e e n C.-G., "Ark. Mat., Astr. och Fysik», 1942, Bd 28A, №29, p. 1-19; [3] П е т p o в B. B., Суммы независимых случайных величин, М., $\underset{B}{1972 .}$

БЮДАНА - ФУРБЕ ТЕОРЕМА: чИсло корней алгеб раич. уравнения

\[
f(x)=0,
\]

заключенных в интервале $(a, b), a<b$, равно или на четное число меньше, чем $\tau=t_{1}-t_{2}$, где $t_{1}$ - число перемен знака в ряду производных многочлена $f(x)$ в точке $a$, т. е. в ряду

\[
f(a), f^{\prime}(a), f^{\prime \prime}(a), \ldots, f^{(n)}(a),
\]

a $t_{2}$ - число перемен знака в этом ряду в точке $b$. При этом каждый кратный корень считается за столько корней, какова его кратность. Установлена Ф. Бюданом (F. Budan, 1822) и Ж. Фурье (J. Fourier, 1820).

Лит.: [1] Энциклопедия элементарной математики, кн.
2 - Алгебра, м.- Л., 1951, с. 331.

БЮРМАНА - ЈАГРАНКА РЯД, р я д $Л$ а г p а нж а,- степенной ряд, полностью решающий задачу локального обращения голоморфных функций. Именно, пусть функция $w=g(z)$ комплексного переменного $z$ регулярна в окрестности точки $z=a$, причем $g(a)=b$ и $g^{\prime}(a) \neq 0$. Тогда в нек-рой окрестности точки $w=b$ плоскости $w$ определена регулярная функция $z=h(w)$, обратная по отношению $\mathrm{k} g(z)$ и такая, что $h(b)=a$; при этом, если $f(z)$ - любая регулярная в окрестности точки $z=a$ функция, то сложная функция $F(w)=f[h(w)]$ разлагается в окрестности точки $w=b$ в р я д Б ю р м ана - Л а г р ан ж а

\[
F(w)=f(a)+
\]

$+\sum_{n=1}^{\infty} \frac{1}{n !}\left\{\frac{d^{n-1}}{d z^{n-1}}\left[f^{\prime}(z)\left(\frac{z-a}{g(z)-b}\right)^{n}\right]\right\}_{z=a}(w-b)^{n} . \quad(*)$ Случай непосредственного обращения функции $w=g(z)$ получается при $f(z) \equiv z$.

Разложение (*) вытекает из т е о р е м ы Б ю р м ан a [1]: при указанных выше предположениях относительно голоморфных функций $g(z)$ и $f(z)$ последняя в нек-рой области на плоскости $z$, содержащей точку $a$, может быть представлена в виде:

\[
f(z)=f(a)+
\]

$+\sum_{n=1}^{m-1} \frac{[g(z)-b]^{n}}{n !}\left\{\frac{d^{n-1}}{d z^{n-1}}\left[f^{\prime}(z)\left(\frac{z-a}{g(z)-b}\right)^{n}\right]\right\}_{z=a}+R_{m}$ где

\[
R_{m}=\frac{1}{2 \pi i} \int_{a}^{z} \int_{\gamma}\left[\frac{g(z)-b}{g(t)-b}\right]^{m-1} \frac{f^{\prime}(t) g^{\prime}(z) d t d z}{g(t)-g(z)},
\]

$\gamma$ - контур на плоскости $t$, содержащий внутри точки $a$ и $z$ и такой, что если $\zeta-$ какая-либо точка внутри $\gamma$, то уравнение $g(t)=g(\zeta)$ не имеет ни на $\gamma$, ни внутри $\gamma$ иных корней, кроме простого корня $t=\zeta$.

Разложенив (*) для случая $b=0$ было получено Ж. Лагранжем [2].

В случае, когда производная $g^{\prime}(t)$ имеет в точке $z=a$ нуль порядка $r-1$, Б.-Л. p. для многозначной обратной функции допускает следующее обобщение (cм.[3]):

\[
F(w)=f(a)+
\]

\[
+\sum_{n=1}^{\infty} \frac{1}{n !}\left\{\frac{d^{n-1}}{d z^{n-1}}\left[f^{\prime}(z)\left(\frac{z-a}{g(z)-b}\right)^{n}\right]\right\}_{z=a}(w-b)^{n / r}
\]

Другое обобщение (см., напр., [4]) относится к функциям $g(z)$, регулярным в кольце; оно приводит вместо ряда $(*)$ к ряду по положительным и отрицательным степеням разности $w-b$.

Jum.: [1] B u r m a n n H., "Mem. de l'Inst. national des sci.