әлементов, инцидентных блоку $B_{j}$, обозначается обычно через $k_{j}$, а число блоков, инцидентных элементу $a_{i}$,через $r_{i}$. Через $\lambda_{i l}$ обозначается число

\[
\left|\left\{B_{j}: a_{i} \in B_{j}, a_{l} \in B_{j}\right\}\right| .
\]

Числа $v, b, r_{i}, k_{j}, \lambda_{i l}(i, l=1, \ldots, v, j=1, \ldots, b)$ наз. п а р а ме т р а м и Б.-с. Если $r_{i}=r$ для всех $i=1, \ldots, v$, $k_{j}=k$ для всех $j=1, \ldots, b$, а $\lambda_{i l}=\lambda$, то $(V, B)$ есть ура вно в ешенная не полна я Б.-с., или BIB - с х е м а (от английского balanced incomplete block design) с параметрами $v, b, r, k, \lambda$. Слово "уравновешенный» характеризует одинаковую частоту появлений элементов и пар әлементов в блоках, а слово «неполный» служит для указания того, что, вообще говоря, не все $k$-элементные подмножества входят в $B$.

Пусть среди чисел $\lambda_{i l}, i, l=1, \ldots, v$, встречается ровно $m$ различных: $\lambda_{1}, \lambda_{2}, \ldots, \lambda_{m}$, и пусть на элементах множества $V$ введено $m$ симметрічных о т н о ш е н и й с в я з а в в о с т и так, что выполнены следующие условия:

a) множество $V^{2}$ всех пар элементов множества $V$ разбивается на $m$ непересекающихся подмножеств $V_{1}^{2}$, $V_{2}^{2}, \ldots, V_{m}^{2}$, причем если $\left(a, a^{\prime}\right) \in V_{j}^{2}$, то говорят, что әлементы $a$ и $a^{\prime}$ j-связаны;

б) $\left|\left\{B_{j}: a \in B_{j}, a^{\prime} \in B_{j},\left(a, a^{\prime}\right) \in V_{i}^{2}\right\}\right|=\lambda_{i}$, $i=1, \ldots, m, j=1, \ldots, b$;

в) $\left|\left\{a: \exists a^{\prime}\left(a, a^{\prime}\right) \in V_{i}^{2}\right\}\right|=n_{i}, i=1, \ldots, m$;

г) $\left|\left\{a^{\prime \prime}:\left(a^{\prime \prime}, a\right) \in V_{j}^{2},\left(a^{\prime \prime}, a^{\prime}\right) \in V_{k}^{2},\left(a, a^{\prime}\right) \in V_{i}^{2}\right\}\right|=p_{j k}^{i}$, причем в силу симметричности $p_{j}^{i}=p_{k j}^{i}, i, j, k=1, \ldots, m$. Б.-с. со свойствами $a)-$ г) наз. ч а с т и ч н о у р а вно в е ше ен о й Б.-с. с $m$ тй п ми с в я 3 е й, или $\operatorname{PBIB}(m)-c \mathbf{x}$ е м о і̆ (от английского partially balanced incomplete block design). Правило, задающее отношение связанности, наз. с х е м о й с в я з а н н ост и. ВІВ-схема является РВІВ (1)-схемой. Примером РВІВ (2)-схемы является Б.-с., к-рую можно представить в виде таблицы

\[
\begin{array}{rrrrrrrrr}
1 & 1 & 1 & 2 & 2 & 2 & 3 & 3 & 3 \\
4 & 5 & 6 & 4 & 5 & 6 & 4 & 5 & 6 \\
7 & 8 & 9 & 9 & 8 & 9 & 7 \\
10 & 11 & 12 & 11 & 12 & 10 & 12 & 10 & 11
\end{array}
\]

где любые два числа из одного столбца 1-связаны, а любые два числа, не принадлежащие одному столбцу,2-связаны. Здесь $v=12, b=9, r=3, k=4, \lambda_{1}=1, \lambda_{2}=0$, $n_{1}=9, n_{2}=2$,

\[
P^{1}=\left\|p_{j k}^{1}\right\|=\left\|\begin{array}{cc}
0 & 2 \\
2 & 6
\end{array}\right\|, \quad P^{2}=\left\|p_{j k}^{2}\right\|=\left\|\begin{array}{cc}
1 & 0 \\
0 & 9
\end{array}\right\| .
\]

Всякой Б.-с. с $v$ элементами и $b$ блоками соответствует м а т риц а и нци де н тн о с ти $A=\left\|c_{i j}\right\|$, где $c_{i j}=1$, если $a_{i} \in B_{j}$, и $c_{i j}=0$ в противном случае, $i=1$, $\ldots, v, j=1, \ldots, b$. В теории Б.-с. рассматриваются вопросы существования, классификации и вопросы, связанные с построением Б.-с. с заданными параметрами. Параметры Б.-с. связаны определенными соотношениями. Для ВІВ-схем справедливы равенства:

\[
\begin{gathered}
v r=k b, \\
\lambda(v-1)=r(k-1) .
\end{gathered}
\]

Для параметров РВІВ $(m)$-схем справедливы равенство (1) и следующие соотношения:

\[
\begin{gathered}
\sum_{i=1}^{m} n_{i}=v-1, \\
\sum_{i=1}^{m} \lambda_{i} n_{i}=r(k-1), \\
\sum_{k=1}^{m} p_{j k}^{i}=\left\{\begin{array}{l}
n_{j}, \text { еслІІ } i \neq j, \\
n_{j}-1, \text { если } i=j, i, j=1, \ldots, m,
\end{array}\right. \\
n_{i} p_{j k}^{i}=n_{j} p_{i k}^{j}=n_{k} p_{i j}^{k}, i, j, k=1, \ldots, m .
\end{gathered}
\]

Матрица инцидентности ВІВ-схемы удовлетворяет о с-

![](https://cdn.mathpix.com/cropped/2023_07_08_9626a57e071f2794abb4g-1.jpg?height=37&width=816&top_left_y=220&top_left_x=991)

\[
A A^{T}=(r-\lambda) E+\lambda J,
\]

где $E$ - единичная матрица порядка $v$, а $J$ - матрица порядка $v$, составленная сплошь из единиц. Существование $(0,1)$-матрицы, удовлетворяющей условию (2), является достаточным условием существования ВІВ-схемы с заданными параметрами. Из (2) вытекает неравенство $b \geqslant v$. ВІВ-схема, для к-рой $b=v$ (и значит $r=k$ ), наз. с и м м е т р и ч н о й г у р а ц и е й. Для симметричных ВІВ-схем справедлива теорема: если существует симметричная ВІВ-схема с параметрами $v, k, \lambda$, то: а) при $v$ четном $k-\lambda$ есть квадрат, б) при $v$ нечетном уравнение

\[
z^{2}=(k-\lambda) x^{2}+(-1)^{\frac{v-1}{2}} \lambda y^{2}
\]

имеет решение в целых числах $x, y, z$, не равных одновременно нулю. Условия этой теоремы достаточны для существования рациональной матрицы $A$, удовлетворяющей (2).

Специальный круг вопросов, относящихся к существованию ВІВ-схем, возникает в связи с задачей: даны $b$ блоков; каковы условия того, чтобы эти блоки можно было дополнить до ВІВ-схемы? В напболее общем виде эти условия выражаются как требования положительной определенностіг нек-рой квадратичной формы $Q$, а также возможности представить $Q$ в виде суммы квадратов линейных форм с неотрицательными коэффициентами.

Среди ВІВ-схем различают как наиболее пзученные следующие подклассы: с и с т е м ы Ш т е й н е р а (ВIВ-схемы с $\lambda=1$ ), в частности с и с те м ы тр о е к III т е йн е р а $(k=3) ;$ а д а м а р о в ы к о нф й г ур а ц и и $(v=b=4 t-1, r=k=2 t-1, \lambda=t-1, t \geqslant 2)$, матрица инцидентности к-рых получается из Адамара матрицы; аффинные конечные геометрии и проективные конечные геометрии (см. [1]). В классе РВIB-схем наиболее изучены РВІВ (2)-схемы, среди к-рых по виду схемы связанности выделяют так наз. Б.-с. с де л й м о с т ь ю н а г р у п пы, т реу го льны е Б.-с., Б.-с. типа латинского к в а д ра та, циклич ес к и е Б.-с. іл т. д. (см. [3]).

Методы построения Б.-с. принято разделять на п р ямы е и р е к у р с и в ны е. Рекурсивные методы позволяют стропть с помощью схем с меньшими значениями параметров схемы с большими значениями параметров. В прямых методах обычно используются свойства конечных полей или какие-либо геометрические свойства.

Помимо планирования экспериментов, Б.-с. применяются также в теоріии игр, теории графов и при построении кодов, исправляющих ошибки.

Лит.: [1] $\mathrm{P}$ a й з е $\mathrm{p} \Gamma$. Дж., Комбинаторная математика, пер. с англ., М., $1966 ;[2] \mathrm{X}$ ол л М., Комбинаторика, пер.

![](https://cdn.mathpix.com/cropped/2023_07_08_9626a57e071f2794abb4g-1.jpg?height=60&width=824&top_left_y=1837&top_left_x=986)

БлОТТО ИГРЫ - класс антагонистических игр в нормальной форме, в к-рых чистыми стратегиями игроков являются распределения ограниченных ресурсов (неделимых или делимых) по нескольким объектам, а выигрыш равен сумме выигрышей на отдельных объектах. Название получили по имени вымышленного лица - полковника Блотто - участника одной из первых игр такого типа.

Лит.: [1] К а р л и н С., Математические методы в теории игр, программировании и әкономике, пер. с англ., М., 1964.

БЛОХА КОНСТАНТА - абсолютная константа, существование к-рой устанавливается следующей т е оре м о й Б ло о а. Пусть $H-$ класс всех голоморфных функций $f(z)$ в круге $|z|<1$ таких, что $f^{\prime}(0)=1$.