антный функтор $X \rightarrow H^{*}(X)$ из категории многообразий в категорию конечномерных градуированных антикоммутативных $K$-алгебр, удовлетворяющий следующим условиям:

1) Если $n=\operatorname{dim} X$, то $H^{2 n}(X)$ изоморфно $K$, и отображение

\[
H^{i}(X) \times H^{2 n-i}(X) \longrightarrow H^{2 n}(X)
\]

определенное умножением в $H^{*}(X)$, невырождено при всех $i$

2) $H^{*}(X) \bigotimes_{k} H^{*}(Y) \approx H^{*}(X \times Y)$ (фо р м у ла $\quad$ ю нн е т a);

3) Отображение циклов. Существует функториальный гомоморфизм $\gamma_{X}$ группы $C p(X)$ алгебраич. циклов $X$ коразмерности $p$ в $H^{2} p(X)$, переводящий прямое проиэведение циклов в тензорное произведение, и нетривиальный в том смысле, что (для точки $P$ ) $\gamma_{P}$ превращается в канонич. вложение $\mathbb{Z}$ в $K$.

\[
b_{i}(X)=\operatorname{dim}_{K} H^{i}(X)
\]

наз. $i$ чч ислом Бе т тимногообразия $X$.

П р и м е р ы. Если $k=\mathbb{C}$, то классические когомологии комплексных многообразий с коәффициентами в $\mathbb{C}$ являются В. к. Если $l-$ простое число, отличное от характеристики поля $k$, то әтальные $l$-адические когомологии

\[
X \mapsto\left[\lim _{v} H_{\mathrm{et}}^{*}(X, \mathbb{Z} / l v \mathbb{Z}] \otimes_{\mathbb{Z}_{l}} Q_{l}\right.
\]

являются В.к. с коэффициентами в поле $Q_{l}$. Для В.к. верна ф о р м у ла Л е фш е ц а

\[
\langle u \cdot \Delta\rangle=\sum_{i=0}^{2 n}(-1)^{i} \operatorname{Tr}\left(u_{i}\right)
\]

где $\langle u \cdot \Delta\rangle$ - индекс пересечения в $X \times X$ графика $\Gamma$ морфизма $u$ с диагональю $\Delta \subset X \times X$, интерпретируемый также как число неподвижных точек эндоморфизма $u$, a $\operatorname{Tr}\left(u_{i}\right)$ - след әндоморфизма $u_{i}$, являющегося ограничением $u$ на $H^{i}(X)$. Более того, эта формула верна также для с о о т в е т с т в и й, т. е. элементов $u \in H^{2 n}(X \times X)$

Jum.: [1] W e i l A., "Bull. Amer. Math. Soc.», 1949, v. 55, p. $497-508 ;$ [2] Dix exposes sur la cohomologie des schemas,
P., 1968 , p. 359-86. Д. Данилов.

ВЕЙЛЯ КРИТЕРИЙ - основной критерий, с помощью к-рого для бесконечной последовательности $\left(x_{n}\right)$ любых действительных чисел $x_{n}$ решается вопрос о ее равномерном распределении по $\bmod 1$, т. е. устанавливается существование предела:

\[
\lim _{N \rightarrow \infty}\left(\sum_{n \leqslant N, \alpha \leqslant\left\{x_{n}\right\}<\beta} \frac{1}{N}\right)=\beta-\alpha,
\]

где $0 \leqslant \alpha<\beta \leqslant 1,\left\{x_{n}\right\}-$ дробная часть $x_{n}$. По В. к. последовательность $\left\{x_{n}\right\}$ тогда и только тогда равномерно распределена по $\bmod 1$, когда

\[
\lim _{N \rightarrow \infty} \frac{1}{N} \sum_{n=1}^{N} \exp \left(2 \pi i m x_{n}\right)=0
\]

для всех целых $m \neq 0$. В. к. доказан $\Gamma$. Вейлем (H. Weyl, 1916). См. Вейля метод.

Лum.: [1] К а с с е л с Д ж. В. С., Введение в теорию диофантовых приближений, пер. с англ., М.. 1961 .

ВЕ М. Б. М.Бредихин.

ВЕЙЛ МЕТОД в т е о р и и ч и с е л- метод для получения нетривиальных оценок тригонометрич. сумм вида

\[
S(f)=\sum_{1 \leqslant x \leqslant P} e^{2 \pi i f(x)},
\]

где

\[
f(x)=\alpha_{n} x^{n}+\ldots+\alpha_{1} x
\]

a $\alpha_{n}, \ldots, \alpha_{1}$ - любые действительные числа. В. м. был разработан Г. Вейлем [1] для установления критериев равномерного распределения (см. Вейля криmepuŭ).

Сущность В. м. заключается в следующем. Сумма (1) возвышается в степень $\rho_{0}=2^{n-1}$ путем последова- тельных возвышений в квадрат с целью понижения степени многочлена $f(x)$. Напр., на первом шаге

\[
S^{2}(f)=\sum_{\lambda_{1} \neq 0} \sum_{x} e^{2 \pi i\left(f\left(x+\lambda_{1}\right)-f(x)\right)}+O(P)
\]

где суммирования производятся по интервалам длины $\ll P$,

\[
f\left(x+\lambda_{1}\right)-f(x)=n \alpha_{n} \lambda_{1} x^{n-1}+\ldots
\]

является многочленом степени $n-1$ относительно $x$ (символы $O(P), \ll P$ обозначают величины порядка $P$ ). На $(n-1)-м$ шаге приходят к внутренней сумме

\[
S(\alpha)=\sum_{x=a+1}^{a+P_{1}} e^{2 \pi i \alpha x}
\]

где $P_{1} \leqslant P, \quad \alpha=n ! \lambda_{1} \lambda_{2} \ldots \lambda_{n-1} \alpha_{n}, \quad \lambda_{i} \neq 0$. Суммы вида (2) оцениваются $\mathrm{c}$ помощью неравенства:

\[
|S(\alpha)| \leqslant \min \left(P_{1}, \frac{1}{|\sin \pi \alpha|}\right) .
\]

В результате получается оценка:

\[
\begin{gathered}
|S(f)|^{\rho_{0}} \leqslant P^{\rho_{0}-1}+ \\
+P^{\rho_{0}-n+\varepsilon} \sum_{0<y \leqslant P^{n-1}} \min \left(P_{1}, \frac{1}{\left|\sin \pi y \alpha_{n}\right|}\right) .
\end{gathered}
\]

Из неравенства (3) выводятся различные оценки суммы (1) в случае, когда $\frac{1}{\left|\sin \pi y \alpha_{n}\right|}$ будет величиной малой по сравнению с $P$. Эти оценки зависят от точности, с к-рой коэффициент $\alpha_{n}$ многочлена $f(x)$ аппроксимируется рациональными дробями.

П р и м е р. Пусть

\[
\left|\alpha_{n}-\frac{p}{q}\right| \leqslant \frac{1}{q^{2}}, \quad(a, q)=1
\]

Тогда имеет место неравенство

\[
|S(f)| \ll P^{1+\varepsilon} q^{\varepsilon}\left(\frac{1}{P}+\frac{1}{q}+\frac{q}{P^{n}}\right)^{\rho_{0}} .
\]

В частности, если

\[
P \leqslant q \leqslant P^{n-1},
\]

TO

\[
|S(f)| \ll P^{1-\rho_{0}+\varepsilon}
\]

В. м. позволил решить в первом приближении ряд важных проблем теории чисел. С помощью оценки (3) и ее следствий было исследовано распределение дробных долей многочлена $f(x)$. Решение Варинга проблемы, данное в 1919 Г. Х. Харди (G. H. Hardy) и Дж. И. Литлвудом (J. E. Littlewood), опиралось на оценки сумм (1) c помощью В. м. При этом им удалось оценить значения $r=r(k)$, для к-рых уравнение

\[
N=x_{1}^{k}+\ldots+x_{r}^{k}
\]

$\left(N>0\right.$ - целое, $x_{i}-$ целые) разрешимо или даже имеет асимптотику для числа решений. Обобщение оценки (3) на случай функций $f(x)$, не являющихся многочленами, но в известном смысле близких к ним, привело к улучшению нек-рых теорем в теории расnределения простых чисел (оценка разности соседних простых чисел, оценка остаточного члена в асимптотич. формуле для числа $\pi(N)$ простых чисел, не превосходящих $N$ ).

Недостаточная сила оценок, получаемых с помощью В. м., объясняется высокой степенью $\rho_{0}$, в к-рую возвышается сумма $S(f)$. Нек-рое усовершенствование оценок сумм (1) дал И. ван дер Корпют (J. van der Corput). С помощью Виноградова метода получается весьма точная оценка сверху для интеграла

\[
\int_{0}^{1} \ldots \int_{0}^{1}|S(f)|^{2 b} d \alpha_{n} \ldots d \alpha_{1}
\]

уже при $b \geqslant c n^{2} \quad(c>0$ - константа, $n \geqslant 2)$. Из этой