наз. одинаково ориентированными. Ниже тройка векторов базиса $i, j, k$ считается правой.

Пусть на плоскости задано направление положительного вращения (от $\boldsymbol{i} \boldsymbol{k} \boldsymbol{j})$. П с е в д о с к а л я рны м п р о и з в е д е н и м м $\boldsymbol{a} \vee \boldsymbol{b}$ ненулевых векторов $\boldsymbol{a}$ и $\boldsymbol{b}$ наз. произведение их модулей на синус угла $\varphi$ положительного вращения от $\boldsymbol{a} \boldsymbol{k} \boldsymbol{b}$ :

\[
\boldsymbol{a} \vee \boldsymbol{b}=|\boldsymbol{a} \| \boldsymbol{b}| \sin \varphi
\]

Псевдоскалярное произведение нулевых векторов полагают равным нулю. Псевдоскалярное произведение обладает свойствами:

$\boldsymbol{a} \vee \boldsymbol{b}=-\boldsymbol{b} \vee \boldsymbol{a}$ (антикоммутативность),

$\boldsymbol{a} \vee(\boldsymbol{b}+\boldsymbol{c})=\boldsymbol{a} \vee \boldsymbol{b}+\boldsymbol{a} \vee \boldsymbol{c}$ (дистрибутивность относительно сложения векторов),

$\lambda(r \vee b)=\lambda a \vee b$ (сочетательность относительно умножения на число),

$\boldsymbol{a} \vee \boldsymbol{b}=0$, лишь если $\boldsymbol{a}=\mathbf{0}$ или (и) $\boldsymbol{b}=\mathbf{0}$ или $\boldsymbol{a}$ и $\boldsymbol{b}$ коллинеарны.

Есліг в ортонормированном базисе векторы $\boldsymbol{a}$ и $\boldsymbol{b}$ имеют координаты $\left\{a_{1}, a_{2}\right\}$ и $\left\{b_{1}, b_{2}\right\}$, то

\[
\boldsymbol{a} \vee \boldsymbol{b}=a_{1} b_{2}-a_{2} b_{1}
\]

Век торным произведением $[\boldsymbol{a}, b]$ ненулевых и неколлинеарных векторов $\boldsymbol{a}$ и $b$ наз. вектор, модуль к-рого равен произведению их модулей на синус угла $\varphi$ между ними, перпендикулярный $\boldsymbol{a}$ и $\boldsymbol{b}$ и направленный так, что тройка векторов $\boldsymbol{a}, \boldsymbol{b},[\boldsymbol{a}, \boldsymbol{b}]-$ правая:

\[
[\boldsymbol{a}, \boldsymbol{b}]=|\boldsymbol{a} \| \boldsymbol{b}| \sin \varphi
\]

Векторное произведение полагают равным нулю, если $\boldsymbol{a}=\mathbf{0}$ или (и) $\boldsymbol{b}=\mathbf{0}$ или они коллинеарны. Векторное произведение обладает свойствами:

$[\boldsymbol{a}, \boldsymbol{b}]=-[\boldsymbol{b}, \boldsymbol{a}]$ (антикоммутативность),

$\left[\begin{array}{ll}\boldsymbol{a}, \boldsymbol{b}+\boldsymbol{c}\end{array}\right]=\left[\begin{array}{ll}\boldsymbol{a}, \boldsymbol{b}\end{array}\right]+\left[\begin{array}{ll}\boldsymbol{a}, \boldsymbol{c}\end{array}\right]$ (дистрибутивность относительно сложения векторов),

$\lambda[a, b]=[\lambda a, b]=[a, \lambda b]($ сочетательность относительно умножения на число),

$[a, b]=0$, лишь если $a=0$ или(и) $b=0$ или $a$ и $b$ коллинеарны.

Если в ортонормированном базисе векторы $\boldsymbol{a}$ и $\boldsymbol{b}$ имеют координаты $\left\{a_{1}, a_{2}, a_{3}\right\}$ и $\left\{b_{1}, b_{2}, b_{3}\right\}$, то

\[
[\boldsymbol{a}, \boldsymbol{b}]=\left\{\left|\begin{array}{ll}
a_{2} & a_{3} \\
b_{2} & b_{3}
\end{array}\right|,\left|\begin{array}{ll}
a_{3} & a_{1} \\
b_{3} & b_{1}
\end{array}\right|,\left|\begin{array}{ll}
a_{1} & a_{2} \\
b_{1} & b_{2}
\end{array}\right|\right\}
\]

С м е ш а н ным произ в е д ением $(\boldsymbol{a}, \boldsymbol{b}, c)$ векторов $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}$ наз. скалярное произведение вектора $\boldsymbol{a}$ на векторное произведение векторов $\boldsymbol{b}$ и $\boldsymbol{c}$ :

\[
(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})=(\boldsymbol{a},[\boldsymbol{b}, \boldsymbol{c}])
\]

Смешанное произведение обладает свойствами:

$(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})=(\boldsymbol{b}, \boldsymbol{c}, \boldsymbol{a})=(\boldsymbol{c}, \boldsymbol{a}, \boldsymbol{b})=-(\boldsymbol{b}, \boldsymbol{a}, \boldsymbol{c})=$

\[
=-(c, b, a)=-(a, c, b) \text {. }
\]

$(a, b, c)=0$, лишь если $a=0$ или (и) $b=0$ или (и) $\boldsymbol{c}=\mathbf{0}$, или векторы $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}$ компланарны.

$(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})>0$, если тройка векторов $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}-$ правая, $(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})<0$, если $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}-$ тройка левая.

Модуль смешанного произведения равен объему параллелепипеда, построенного на векторах $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}$. Если в ортонормированном базисе векторы $\boldsymbol{a}, \boldsymbol{b}$ и $\boldsymbol{c}$ имеют координаты $\left\{a_{1}, a_{2}, a_{3}\right\},\left\{b_{1}, b_{2}, b_{3}\right\}$ и $\left\{c_{1}, c_{2}, c_{3}\right\}$, то

\[
(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c})=\left|\begin{array}{lll}
a_{1} & a_{2} & a_{3} \\
b_{1} & b_{2} & b_{3} \\
c_{1} & c_{2} & c_{3}
\end{array}\right|
\]

Д войным векторным произвед ение м $[\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}]$ векторов $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}$ наз. векторное произведение $[\boldsymbol{a},[\boldsymbol{b}, \boldsymbol{c}]]$. При вычислении двойного векторного произведения имеют место формулы:

\[
\begin{aligned}
& {[\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}]=[\boldsymbol{b},(\boldsymbol{a}, \boldsymbol{c})]-[\boldsymbol{c},(\boldsymbol{a}, \boldsymbol{b})],} \\
& ([a, b],[c, d])=(a, c)(b, d)-(a, d)(b, c), \\
& {[[a, b],[c, d]]=(a, c, d) b-(b, c, d) a=} \\
& =(\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{d}) \boldsymbol{c}-\left(\begin{array}{ll}
\boldsymbol{a} & \boldsymbol{b}, \boldsymbol{c}
\end{array}\right) \boldsymbol{d} .
\end{aligned}
\]

Лum.: [1] А л е к с а н д р о в П. С., Лекции по аналити-

![](https://cdn.mathpix.com/cropped/2023_07_08_2b6739fd6a7832b0770eg-1.jpg?height=47&width=838&top_left_y=438&top_left_x=985)
курс аналитической геометрии, 9 изд., М., 1967; [3] И л ь и н
В. А., П о в я к Э. Г., Аналитическая ге ометрия, М., 1968;
[4] Пог о р л о в А. В., Аналитическая геометрия, З изд.,

ВЕКТОРНАЯ ГРУПIА — частично упорядоченная әруппа, вложимая в по.лное прямое произведение линейно упорядоченных групп. Группа $G$ тогда и только тогда есть В. г., когда ее частичный порядок есть пересечение линейных порядков $G$. Частично упорядоченная группа тогда и только тогда является В. г., когда ее полугруппа $P$ положительных элементов удовлетворяет условию: для лююого конечного набора элементов $a_{1}, a_{2}, \ldots, a_{n}$ из $G$ пересечение

\[
\cap P S\left(a_{1}^{\varepsilon_{1}}, \ldots, a_{n}^{\varepsilon_{n}}, e\right)=P
\]

Здесь пересечение берется по всем наборам знаков $\varepsilon_{i}= \pm 1$, а $S(x, y, \ldots, z)$ обозначает наименьшую инвариантную подполугруппу группы $G$, содержащую $x$, $y$, ..., z. Доупорядочиваемая группа $G$ есть В. г. тогда и только тогда, когда для любых $g, g_{1}, \ldots, g_{n} \in G$ из

\[
g g_{1}^{-1} g g_{1} \ldots g_{n}^{-1} g g_{n} \in P
\]

следует $g \in P$.

Лum.: [1] Ф у к с Л., Частично упорядоченные алгебраические системы, пер. с англ., М., 1965.

ВЕКТОРНАЯ РЕIIIEКА, в е к т о р н а я с т р у ктура, $K$-л и н е а л,- частично упорядоченное действительное векторное пространство с отношением порядка, определяющим решетку. См. Полуупорядоченное пространство.

ВЕКТОРНАЯ ТРУБКА - замкнутое множество Ф точек области $\Omega$ пространства, в к-рой задано векторное поле $\boldsymbol{a}(M)$, такое, что всюду на его граничной поверхности $S$ вектор нормали $\boldsymbol{n}$ ортогонален $\boldsymbol{a}$. В. т. Ф состоит из ве к т о рны х ли ни й $\Gamma$ поля $a$, т. е. кривых в $\Omega$, в каждой точке к-рых направление касательной совпадает с направлением $a$. Линия $\Gamma$ целиком содержится в $\Phi$, если одна точка $\Gamma$ содержится в $\Phi$. Если $\boldsymbol{a}$ - поле скоростей стационарного потока жидкости, то $\Gamma-$ траектория частицы жидкости, а $\Phi$ часть $\Omega$, к-рую при движении «заметает» фиксированное множество частиц жидкости.

И н т е н с и в нос тью $I$ трубки $\Phi$ в сечении $S$ наз. поток (см. Векторный анализ) поля а через $S^{\prime}$ :

\[
I\left(S^{\prime}\right)=\iint S^{\prime}(\boldsymbol{a}, \boldsymbol{n}) d \sigma
\]

где $\boldsymbol{n}-$ единичный вектор нормали к $S^{\prime}$. Если поле $\boldsymbol{a}-$ соленоидально (div $\boldsymbol{a}=0)$, то выполняется закон сохранения интенсивности В. т.:

\[
I\left(S^{\prime}\right)=I\left(S^{\prime \prime}\right)
\]

Пусть $a_{1}(x, y, z), a_{2}(x, y, z), a_{3}(x, y, z)-$ декартовы прямоугольные координаты вектора $\boldsymbol{a}=\boldsymbol{a}(M) ; x, y, z-$ координаты точки $M$. Тогда локально граница $\Phi$ задается уравнением $F(x, y, z)=$ const, где $F(x, y, z)$ удовлетворяет уравнению с частными производными: $(\boldsymbol{a}, \nabla F)=a_{1}(x, y, z) \frac{\partial F}{\partial x}+a_{2}(x, y, z) \frac{\partial F}{\partial y}+a_{3}(x, y, z) \frac{\partial F}{\partial z}=0$.

Ю. П. Пытвев.

ВЕКТОРНАЯ ФУНКЦИЯ - то же, что векторфункчия.