ски в декартовых прямоугольных координатах $(x, y)$ при помощи формул (начало координат в центре В.):

\[
\begin{aligned}
& \tilde{x}=x \cos \varphi+y \sin \varphi, \\
& \tilde{y}=x \sin \varphi-y \cos \varphi,
\end{aligned}
\]

где $\varphi$ - угол поворота. Несобственное В. на плоскости может быть представлено как произведение собственного В. на осевую симметрию.

В случае n-мерного евклидова пространства В. аналитически выражается с помощью ортогональной матрицы, к-рая приводится к канонич. виду:

![](https://cdn.mathpix.com/cropped/2023_07_08_5167f3de61f16d133169g-1.jpg?height=197&width=420&top_left_y=519&top_left_x=336)

где

\[
u_{i}=\left\|\begin{array}{rr}
\cos \varphi_{i} & \sin \varphi_{i} \\
-\sin \varphi_{i} & \cos \varphi_{i}
\end{array}\right\| .
\]

$\varepsilon_{s}-$ единичная матрица порядка $s(s=p, q)$. Возможны следующие случаи:

1) $p=n-$ тождественное преобразование;

2) $q=n-$ В. является центральной симметрией;

3) $p+q=n-$ В. является симметрией относительно p-плоскости (отражением от $p$-Плоскости);

4) $M$ не содержит подматриц $\varepsilon_{p}$ и $-\varepsilon_{q}-$ В. наз. п о в о р о то м в о к р у $\mathrm{r}$ единственной неподвижной т о ч к и;

5) $M$ содержит подматрицы $u_{i}$ и $\varepsilon_{p}$, но не содержит подматрицу $-\varepsilon_{q}-$ В. наз. П о в о рот о м в о к р у r $p-\Pi$ л о с к о с т и;

6) $M$ содержит подматрицы $u_{i}$ и $-\varepsilon_{q}$, но не содержит подматрицы $\varepsilon_{p}-$ B. наз. П о в о о от ны м о т р аже ни е м о т $(n-q)-\Pi$ ло с ко с т и.

В. евклидова пространства $E_{n}$ вокруг данной точки образует группу относительно операции умножения В., изоморфную группе ортогональных преобразований векторного пространства $R^{n}$ или группе ортогональных матриц порядка $n$ над полем $R$. Группа В. пространства

![](https://cdn.mathpix.com/cropped/2023_07_08_5167f3de61f16d133169g-1.jpg?height=39&width=831&top_left_y=1407&top_left_x=120)
в $E_{n}$ интранзитивно.

Лum.: [1] Р о з е н ф е л ь д Б. А., Многомерные пространства, М. 1966; [2] е г о же, Неевклидовы пространства,

![](https://cdn.mathpix.com/cropped/2023_07_08_5167f3de61f16d133169g-1.jpg?height=42&width=836&top_left_y=1517&top_left_x=118)

ВРАЩЕНИЕ ВЕКТОРНОГО ПОЛЯ н а П л 0 с с т и - одна из его гомотопически инвариантных характеристик. Пусть $X$ - векторное поле в области $G$ евклидовой плоскости $E^{2}, \theta-$ угол между $X$ и нек-рым фиксированным направлением; тогда в р а е н и е м в е кт о р н о г о п о л я $X$ наз. деленное на $2 \pi$ приращение угла $\theta$ при обходе замкнутой ориентированной кривой $L \in E^{2}$, вдоль к-рой $X \neq 0$. Так, напр., если $L-$ гладкая класса $C^{2}$ кривая, то вращение касательного к $L$ (или нормального к $L$ ) поля $\tau$ (или $v$ ) вдоль $L$ равно деленной на $2 \pi$ полной кривизне $L$; если $X-$ векторное поле (с возможными изолированными особыми точками) в $G$ с жордановой границей $\partial G$ то В. в. П. на $\partial G$ равно сумме индексов особых точек $X$ в замыкании $G$. (см. Ocoбой точки индекс). При гомотопной деформации $L$, не проходящей через особые точки $X$, В. В. П. не изменяется.

Обобщением понятия В. в. п., заданного на $n$-мерном многообразии $M$, расположенном в $E^{N}$, является степень отображения его в $(N-n)$-мерную сферу; она связана с эйлеровой характеристикой. См. также Пуанкаре теорема, Кронекера формула. М. И. Войчеховккий.

ВРАЩЕНИЙ ИНДИКАТРИСА, д и а г р а м м а в р а ш е н и й, - одна из 12 Дарбу поверхностей, accoциированная с бесконечно малыл изгибанием поверхности, - множество точек пространства, описываемое ра- диус-вектором $\boldsymbol{y}$, параллельным в е к т о р у в р а щ ен и я (мгновенной угловой скорости), определяемому уравнением $d \boldsymbol{z}=[\boldsymbol{y} d \boldsymbol{x}]$, где $\boldsymbol{z}-$ в е к т ор с к о р о с т и бесконечно малого изгибания поверхности с радиусвектором $\boldsymbol{x}$. Аналогично вектором перемещений $\boldsymbol{s}=$ $=\boldsymbol{z}-[\boldsymbol{y} \boldsymbol{x}]$ определяется и н д и к а т р и с а (д и аг р а м м а) п е р е ме щ е ни й.

Лит.: [1] Е фи м о в Н. В., “Успехи матем. наую", 1948 т. 3, в. 2(24), с. $47-158 ;[2]$ К о н -Ф о с с е н С. Э., Некото-
рые вопросы дифференциальной геометрии в целом, м., 1959 .

М. ІІ. Войчеховский.

ВРАЩЕНИЙ МЕТОД, м е т о д Я к о б и,- метод решения полной проблемы собственных значений әрмитовой матрицы, основанный на подобном преобразовании эрмитовой матрицы к диагональному виду с помощью последовательности плоских вращений. В. м. итерационный метод, он имеет простую вычислительную схему и всегда сходится, причем скорость сходимости асимптотически квадратичная. Наличие кратных и близких собственных значений у матрицы не вызывает осложнений. В. м. позволяет вычислить собственные значения как с нахождением собственных векторов, так и без них. Система собственных векторов, вычисленная по В. м., ортонормирована.

Идеи В. м. предложены в [1]. В современном віге это один из наиболее развитых и эффективных по реализации на ЭВМ методов решения полной проблемы собственных значений матрицы.

Классический В. м. состоит в построении последовагельности матриц $A_{0}, A_{1}, A_{2}, \ldots$, , где $A_{0}=A-$ исходная матрица, $A_{k}=U_{k}^{*} A_{k-1} U_{k}, U_{k}-$ матрица плоского вращения, аннулирующего максимальный по модулю внедиагональный элемент матрицы $A_{k-1}$. При этом, если $A_{k}=\left\|a_{i j}^{(k)}\right\|, \quad\left|a_{p q}^{(k-1)}\right|=\max _{i \neq j}\left|a_{i j}^{(k-1)}\right|$, то матрица $U_{k}=\left\|u_{i j}^{(k)}\right\|$ отличается от единичной лишь әлементами $u_{p p}^{(k)}, u_{q q}^{(k)}, u_{p q}^{(k)}, u_{q p}^{(k)}$. В действительном случае, когда $A$ - симметрическая матрица,

\[
\left.\begin{array}{rl}
u_{p p}^{(k)}= & u_{q q}^{(k)}=\cos \varphi ; \quad u_{p q}^{(k)}=-u_{q p}^{(k)}=\sin \varphi \\
\operatorname{tg} 2 \varphi=\frac{2 a_{p q}^{(k-1)}}{a_{p p}^{(k-1)}-a_{q q}^{(k-1)}},|\varphi| \leqslant \frac{\pi}{4} .
\end{array}\right\}
\]

В комплексном случае соотношения $(*)$ незначительно усложняются.

Последовательность матриц $A_{k}$ сходится к диагональной матрице $\Lambda$, скорость сходимости аспмптотически квадратичная. Диагональные әлементы матрицы $\Lambda$ являются приближенными собственными значениями $A$, а столбцы матрицы $U^{(k)}=U_{1} U_{2} \ldots U_{k}-$ приближенными собственными векторами.

Реализация описанного варианта В. м. требует выбора максимального по модулю внедиагонального элемента матрицы на каждом шаге. Для выполнения этой операции на ЭВМ требуется значительный объем вычислительной работы.

Существуют другие варианты В. м., более әффективные в этом отношении: циклич. В. м., В. м. с барьером, В. м. с выбором оптимального элемента.

В ц и к л и ч е с к о м В. м. пары индексов $(p, q)$ аннулирующего элемента пробегают циклическі все наддиагональные позиции. Недостатком этого процесса является возможность выполнения болышого чісла неәффективных вращений, аннулирующих малые внедиагональные элементы.

Этот недостаток частично устраняется в б а р в е рн о м В. м., в к-ром вводится монотонно убывающая к нулю последовательность чисел $\alpha_{1}, \alpha_{2}, \ldots$, называемых барьерами, и при циклич. просмотре индексов $(p, q)$ аннулируются лишь те внедиагональные элементы, к-рые по модулю меньше $\alpha_{1}$. После того, как все внедиагональные элементы стали меньше $\alpha_{1}$, барьер $\alpha_{1}$