Минимальными полями в задаче являются либо поле $\boldsymbol{P}\left(z_{2}\right)$, либо поле $\boldsymbol{P}\left(z_{4}\right)$. Размерность каждого поля равна единице и понизить ее нельзя (см. [13]).

Пока известен (1977) лишь один метод синтеза законов обратной связи, основанный на использовании функций Ляпунова (см. [13]). При этом существенную роль играет т е о рем а Б а р б а ш н а - K р aс о в с к о г о (см. [6], [10], [15]): для того чтобы невозмущенное движение $y=0$ замкнутой системы

\[
\dot{y}=\varphi(y)
\]

было аспмптотическі устойчиво, достаточно существования знакоопределенной положительной функции $v(y)$, полная производная к-рой, в силу уравнения (14), есть функция $w(y)$, знакопостоянная отрицательная, однако такая, что на многообразии $w(y)=0$ не лежат целые траектории системы (14), кроме $y=0$. Задача выяснения существования і структуры минимальных полей Іиеет важное практич. значение, поскольку эти поля отвечают требованиям $Г К$ о минимуме веса, габаритов, сложности, стоимості системы управления и ее максимальной надежності. Особый научный и практич. интерес эта задача приобретает для бесконечномерных систем, встречающихся в технике, биологии, медицине, экономике іл социологии.

К сожалению, при проектировании систем управленшя невозможно ограничиться решением задачи синтеза законов обратной связи. В большинстве случаев требования ГК касаются обеспечения нек-рых важных специфич. свойств переходного процесса в замкнутой системе. Важность этих требований видна на примере регулірования атомного реактора. В случае, если переходный процесс затягивается долее 5 сек или максимальное уклонение к.-л. его координаты превосходит заданное значение, происходіт атомный взрыв. В связи с этим возникают новые задачи синтеза законов регулированшя, определенных на множестве $M$. Приведем формулировку одной из такіх задач. Рассмотрим две сферы: $\left\|y_{0}\right\|=R, y_{0}=y_{i},\left\|y\left(t_{1}\right)\right\|=\varepsilon, R \gg \varepsilon-$ заданные числа. Обратимся к множеству $M$ всех законов обратной связи. Возьмем любой из ніх и произведем замыкание, получIIм уравнение:

$\dot{y}=A y+B \xi\left(y_{1}, \ldots, y_{r}, t\right)+\varphi\left(y, \xi\left(y_{1}, \ldots, y_{r}, t\right), t\right)$. (15) Рассмотрим все множество решений $y\left(t, y_{0}\right)$ уравнения (15), начинающихся на сфере $R$. Будем называть іх $R$ р е ш е н и я м и. Поскольку система (15) асимптотически устойчива для любого $y_{0}$ на сфере, существует момент времени $t_{1}$, при к-ром соблюдаются условия

\[
\left\|y\left(t_{1}, y_{0}\right)\right\|=\varepsilon,\left\|y\left(t, y_{0}\right)\right\|<\varepsilon
\]

прі любом $t>t_{1}$.

Пусть

\[
t^{*}=\sup _{y_{0}} t_{1}
\]

Из определения $t_{1}$ ясно, что $t^{*}$ существует. Интервал $t^{*}-t_{i}$ наз. в р е мен ем регули р ов а ния (з атухан і я пе р е ходного проц е с с a) в замкнутой системе (15), если любое $R$-решение выходит на сферу $\varepsilon$ при $t_{1} \leqslant t^{*}$ и остается внутри ее при $t>t_{1}$. Очевидно, что время регулирования есть функционал вида $t^{*}=t^{*}(R, \varepsilon, \xi)$. Пусть $T-$ заданное число. Возникает 3 а д ач а с ин т е 3 а б ы с т р о д е й с т в ующ и х р е г у л я т о р о в: дано множество $M$ законов обратной связи, требуется выделить такое его подмножество $M_{1}$, на к-ром время регулирования в замкнутой системе удовлетворяет условию

\[
t^{*}-t_{i} \leqslant T
\]

Аналогично могут быть сформулированы задачи синтеза множеств $M_{2}, \ldots, M_{k}$ законов обратной связи, при к-рых соблюдаются другие $k-1$ требований $\Gamma К$. Главная задача синтеза об удовлетворении всех требований $\Gamma K$ разрешима, если множества $M_{1}, \ldots, M_{k}$ имеют непустое пересечение (см. [13]).

Наиболее детально задача синтеза изучена для случая, в к-ром поле $P$ имеет максимальную размерность $r=n$, а показатель качества системы характеризуется функціоналом

\[
J=\int_{0}^{\infty} w(y, \xi, t) d t
\]

где $w(y, \xi, t)-$ знакоопределенная положительная функция по $y, \xi$. В этом случае задача наз. 3 а д а ч е й

![](https://cdn.mathpix.com/cropped/2023_07_08_0a7e2c25b86b50fdacc7g-1.jpg?height=35&width=819&top_left_y=533&top_left_x=990)
о п т и м а льных р егу ля то ров (см. [14]) и формулируется так. Даны уравнение (11), класс допустимых управлений $\xi(y, t)$, определенных над полем $\boldsymbol{P}(y)$ максимальной размерности, и функционал (16). Требуется найти управление $\boldsymbol{\xi}=\boldsymbol{\xi}(y, t)$, при к-ром функционал (16) достигает минимального значения. Эта задача разрешается теоремой: если уравнение (11) таково, что можно найти знакоопределенную положительную допускающую бесконечно малый высший предел функцию $v^{0}(y, t)$ и функцию $\xi^{0}(y, t)$ такие, что выполняется равенство

\[
\frac{\partial v^{0}}{\partial t}+\frac{\partial v^{0}}{\partial y}\left(A y+B \xi^{0}+\varphi\left(y, \xi^{0}, t\right)\right)=0
\]

II справедливо неравенство

\[
\frac{\partial v^{0}}{\partial t}+\frac{\partial v^{0}}{\partial y}(A y+B \xi+\varphi(y, \xi, t)) \geqslant 0
\]

при любых допустимых $\xi$, то функция $\xi^{0}(y, t)$ разрешает задачу. Прі этом имеет место равенстио

\[
v^{0}\left(t_{0}, y_{0}\right)=\min _{\xi} \int_{0}^{\infty} w(y, \xi, t) d t
\]

Функция $v^{0}(y, t)$ наз. о п т и м а льн о й Ф у н к ц и е й Л я п ун о в а (cм. [15]). Она служит решением уравнения (17) с частными производными типа ГамильтонаЯкоби, удовлетворяющего условию $v(y(\infty), \infty)=0$. Методы эффективного решения такой задачи разработаны для случая, в к-ром функции $w, \varphi$ допускают разложение в целые сходящиеся ряды по $y, \xi$ с коэффициентами, являющимися непрерывными и ограниченными функциями от $t$. При этом прінципиальное значение имеет разрешимость задачи по линейному прио́лижению в уравнении (11) и оптимизации лишь интеграла от квадратичных членов, удерживаемых в разложении $w$. Разрешимость же последней задачи гарантируется соблюдением условия полной управляемости (см. [15]). Лum.: [1] М а к с в е л л Д. К., В ыш н е г р а д с к и й И. А., С т о д о ла А., Теория автоматического регулирования, М., 1949; [2] ч е т а е в Н. Г., Устойчивость движения, 3 изд., М., $1965 ;[3]$ К р ас о в с к и й Н. Н., Теория управ-
ления движением, М., 1968; [4] П о н т р я г и н Л. С. [и др.] Математическая теория оптимальных прогессов, 2 изд., М., 1969 ; [5] Техническая кибернетика, кн. 1-2, М., 1967; [6] Б а рб а ш и Е. А., Введение в теорию устойчивости, М., 1967; [7] 3 у б о в В. И., Математические методы исследования систем автоматического регулирования, Л., 1959; [8] П уг а-
ч е в В. С., Теория случайных функций и ее применение к задачам автоматического управления, 3 изд., М., 1962; [9] Ц ыпК ин Я. З., Основы теории обучающихся систем, М., 1970 ; [10] К р а с о в с к и и Н. Н., Некоторые задачи теории устойП о п о в E. П., теория систем автоматического регулирования, М., 1966; [12] Теория систем с переменной структурой, под ред. С. В. Емепьянова, М., 1970; [13] Л е т о в А. М.,
«Дифференц. уравнения», 1970 , т. 6 , № 4, с. $592-615 ;[14]$ е г о же, Динамика полета и управление, М., 1969; [15] M а лк ин И. Г., Теория устойчивости движения, 2 изд., М., 1965 ,
(дополнение 4 ).
А. М. ІПетов.

АВТОМАТОВ АЛГЕБРАИЧЕСКАЯ ТЕОРИЯ - направление в автоматов теории, характеризующееся использованием алгебраич. средств в пзучении автоматов. А. а. т. основана на том, что автоматы можно рассматривать как нек-рые специальные алгебры или алгебраическіе системы. Кроме того, события, представимые ко-

03 Математическая әнц., т. 1