Если $\mathfrak{M}$ есть множество функций $f$, заданных на $R_{n}$, то задача описания свойств следов этих функций на подпространство $R_{m}(1 \leqslant m<n)$ наз. П р о бл е м о й с л е д о в для класса $\mathfrak{M}$.

Теорема (4) является окончательной в терминах класcoв $W_{p}^{l}(\Omega)$. Дальнейшее ее улучшение возможно лишь путем введения новых классов.

В одномерном случае $n=m=1$, где проблема следов не возникает, теорема (4) принадлежит Г. Харди и Дж. Литлвуду (G. Hardy, J. Littlewood).

Следующим этапом в развитии этой теории являются теоремы вложения С. М. Никольского для обобщенных гёльдеровых классов (см. Гёльдерово пространство) (H-классов). Эти классы образуют шкалу с непрерывно меняющимися параметрами, характеризующими гладкость функций. Они анизотропны в том смысле, что принадлежащие к ним функции обладают, вообще говоря, разными диффференциальными свойствами по разным направлениям. Пусть $\Omega_{\eta}$ есть множество точек $x \in \Omega$, удаленных от границы $\Omega$ больше чем на $\eta>0$, и пусть $\boldsymbol{r}=\left(r_{1}, \ldots, r_{n}\right)$ - положительный вектор $\left(r_{j}>0\right.$; $j=1, \ldots, n), r_{j}=r_{j}^{*}+\alpha_{j}, r_{j}^{*}-$ целое и $0<\alpha_{j} \leqslant 1$.

Функция п р ин а д ле жи т к л а с с у $f \in H_{p}^{r}(\Omega)$, $1 \leqslant p \leqslant \infty$, если $f \in L_{p}(\Omega)$ п для любого $j=1, \ldots, m$ существует обобщенная частная гроизводная

\[
D_{j}^{r_{j}^{*}} f=\frac{\partial^{r_{j}^{*}}}{\partial x_{j}^{r_{j}^{*}}}
\]

удовлетворяющая неравенству

\[
\left\|\Delta_{j h}^{2}\left(D_{j}^{r_{j}^{*}} f\right)\right\| L_{p}\left(\Omega_{2, h j}\right) \leqslant M|h|^{\alpha_{j}},
\]

где $\Delta_{j h}^{2}-$ вторая разность функции по переменной $x_{j}$ с шагом $h$ и $M$ - константа, не зависящая от $h$.

Класс $H_{p}^{r}(\Omega)$ образует банахово пространство, если ввести норму

\[
\|f\|_{H_{p(\Omega)}^{r}}^{\boldsymbol{r}_{(\Omega)}}=\|f\|_{L_{p}(\Omega)}+M_{f}
\]

где $M_{f}$ - наименьшая константа $M$, при к-рой выполняются неравенства (7). Для $r_{1}=\ldots=r_{n}=r$ соответствующий (изотропный) класс обозначается через $H_{p}^{r}$. При целом $l$ класс $H_{p}^{l}$ близок к классу Соболева $W_{p}^{l}$ с точностью до $\varepsilon>0$ в том смысле, что

\[
H_{p}^{l+\varepsilon}\left(R_{n}\right) \longrightarrow W_{p}^{l}\left(R_{n}\right) \longrightarrow H_{p}^{l-\varepsilon}\left(R_{n}\right) .
\]

Справедливы теоремы вложения (С. М. Никольский)

\[
H_{p}^{r}\left(R_{n}\right) \longrightarrow H_{q}^{\rho}\left(R_{m}\right)
\]

где $1 \leqslant p \leqslant q \leqslant \infty, \quad 1 \leqslant m \leqslant n, \quad \boldsymbol{\rho}=\left(\rho_{1}, \ldots, \rho_{m}\right)$,

\[
\rho_{j}=x r_{j} \quad(j=1, \ldots, m) \text {, }
\]\[
x=1-\left(\frac{1}{p}-\frac{1}{q}\right) \sum_{j=1}^{m} \frac{1}{r_{j}}-\frac{1}{p} \sum_{j=m+1}^{n} \frac{1}{r_{j}}>0
\]\[
H_{p}^{r}\left(R_{n}\right) \rightleftarrows H_{p}^{\rho}\left(R_{m}\right) \text {, }
\]

где $1 \leqslant p \leqslant \infty, 1 \leqslant m<n, \rho_{j}=x r_{j}, j=1, \ldots, m$,

\[
x=1-\frac{1}{p} \sum_{j=m+1}^{n} \frac{1}{r_{j}}>0
\]

(cM. [5]).

Теорема (9) является анизотропным аналогом теоремы (4), но имеет то преимущество, что верхние (векторные) индексы $r, \rho$ фигурирующих в ней классов могут изменяться непрерывно. Кроме того, она полностью охватывает случаи $p=1, \infty$. Однако при $x=0$ она, в отличие от (4), неверна. В одном случае $(n=m=1)$ при $r$ и $\rho$ не целых она доказана Г. Харди и Дж. Литлвудом. Частный случай теоремы (9) при $p=q$ записан еще раз в виде вложения (10) с верхней стрелкой. Оно гласит: функция $f \in H_{p}^{r}\left(R_{n}\right)$ имеет след $\left.f\right|_{R_{m}}=\varphi$ на $R_{m}$ и при этом

\[
\|\varphi\|_{H_{p}^{\rho}\left(R_{m}\right)} \leqslant C\|f\|_{H_{p}^{r}\left(R_{n}\right)}
\]

где $C$ не зависит от $f$. Но справедливо и обратное утверждение, выражаемое нижней стрелкой, к-рое надо понимать в следующем смысле: каждая определенная на $R_{m}$ функция $\varphi \in H_{p}^{\rho}\left(R_{m}\right)$ может быть продолжена на все пространство $R_{n}$ так, что полученная функция $f(x)$ (со следом на $R_{m}$, равным $\varphi$ ) принадлежит к $H_{p}^{r}\left(R_{n}\right)$ и выполняется неравенство (обратное к (11)):

\[
\|f\|_{H_{p}^{\boldsymbol{r}}\left(R_{n}\right)} \leqslant C_{1}\|\varphi\|_{H_{p}^{\rho}\left(R_{m}\right)},
\]

где $C_{1}$ не зависит от $\varphi$.

Взаимно обратные вложения (10) полностью решают проблему следов для $H$-классов и при әтом в терминах H-классов.

Теорема (9) носит т р а н з и т и в н ы й характер, заключающийся в том, что переход

\[
H_{p}^{\boldsymbol{r}}\left(R_{n}\right) \longrightarrow H_{p^{\prime}}^{\rho^{\prime}}\left(R_{m}\right) \longrightarrow H_{p^{\prime \prime}}^{\rho^{\prime \prime}}\left(R_{m^{\prime \prime}}\right)
\]

от первого класса в цепи (12) ко второму, а затем от второго к третьему, где параметры $\rho^{\prime}, \rho^{\prime \prime}$ вычисляются по указанным в (9) формулам, может быть заменен одним переходом от первого класса к третьему при непосредственном вычислении $\boldsymbol{\rho}^{\prime \prime}$ по тем же формулам.

В дальнейшем (см. далее [14]) была решена проблема следов для $W$-классов, вообще анизотропных. Это привело к введению нового семейства классов дифференцируемых функций многих переменных $B_{p \theta}^{r}\left(R_{n}\right)$, зависящих от векторного параметра $\boldsymbol{r}$ и двух скалярных параметров $p, \theta$, удовлетворяющих неравенствам $1 \leqslant$ $\leqslant p, \theta \leqslant \infty$. Во всей полноте это семейство определил О. В. Бесов, изучивший также его основные свойства. Функция $f$ п р и над ле жи т к л а с с у $W_{p}^{l}(\Omega)$, где $l=\left(l_{1}, \ldots, l_{n}\right)-$ целый вектор, если для нее имеет смысл конечная норма

\[
\begin{aligned}
& \|f\|_{w_{p(\Omega)}^{l}}=\|f\|_{L_{p}(\Omega)}+\|f\|{ }_{w_{p}(\Omega)}^{l}, \\
& \|f\|_{w_{p}(\Omega)}^{l}=\sum_{j=1}^{n}\left\|D_{j}^{l_{j}}\right\|_{p}(\Omega)^{\circ}
\end{aligned}
\]

Функция $f$ п р и на д л е ж и т к л а с с у $B_{p \theta}^{r}(\Omega)$, где $\boldsymbol{r}=\left(r_{1}, \ldots, r_{n}\right)$ - произвольный, не обязательно целый вектор, $1 \leqslant p \leqslant \infty, 1 \leqslant \theta<\infty, r_{j}>0$, если для нее конечна норма

\[
\begin{gathered}
\|f\|_{B_{p}^{r}(\Omega)}^{r_{0}}=\|f\|_{L_{p}(\Omega)}+\|f\|_{b_{p}(\Omega)}^{\boldsymbol{r}_{(\Omega)}}, \\
\|f\|_{b_{p}^{\boldsymbol{r}(\Omega)}}^{\boldsymbol{r}}= \\
=\sum_{j=1}^{n}\left\{\int_{\theta}^{\infty} t^{-\theta \alpha_{j}-1}\left\|\Delta_{j t}^{2} f_{x_{j}}^{\left(r_{j}^{*}\right)}\right\|_{L_{p}\left(\Omega_{2 t}\right)}^{\theta} d t\right\}^{1 / \theta},
\end{gathered}
\]

где числа $r_{j}^{*}$ и $\alpha_{j}$ определены выше.

Естественно считать, что класс $B_{p \theta}^{r}$ при $\theta=\infty$ совпадает с классом $H_{p}^{\boldsymbol{r}}\left(B_{p \infty}^{r}=H_{p}^{\boldsymbol{r}}\right)$. Обычно пишут еще $\boldsymbol{B}_{p \theta}^{\boldsymbol{r}} \quad$ вместо $\quad \boldsymbol{B}_{p \theta}^{r}$, когда $r_{1}=\ldots=r_{n}=r \quad$ и $\quad \boldsymbol{B}_{p}^{\boldsymbol{r}}=\boldsymbol{B}_{p p}^{\boldsymbol{r}}$, $\boldsymbol{B}_{p}^{\boldsymbol{r}}=\boldsymbol{B}_{p p}^{\boldsymbol{r}}$. Для любых указанных $p, \theta, \boldsymbol{r}$ классы $\boldsymbol{B}_{p \theta}^{\boldsymbol{r}}$ суть банаховы пространства.

Теоремы вложения (9), (10) верны, если в них заменить $H$ на $B$. Имеют место также взаимно обратные вложения

\[
W_{p}^{r}\left(R_{n}\right) \rightleftarrows B_{p}^{\chi r^{m}}\left(R_{m}\right)
\]