где $\boldsymbol{r}$ - целое, $\quad 1<p<\infty, \boldsymbol{r}^{m}=\left(r_{1}, \ldots, r_{m}, 0, \ldots, 0\right)$, $\chi=1-\frac{1}{p} \sum_{j=m+1}^{n} \frac{1}{r_{j}}>0$, полностью решающие проблему следов для $W$-классов, что не мешает выполняться взаимно обратным вложениям, выраженным полностью на языке $B$-классов:

\[
B_{p \theta}^{r}\left(R_{n}\right) \rightleftarrows B_{p \theta}^{\varkappa r m}\left(R_{m}\right) .
\]

Классы $B_{2}^{r}$, соответствующие значениям параметров $p=\theta=2$, принято еще обозначать через $W_{2}^{r}\left(B_{2}^{r}=W_{2}^{r}\right)$. При $p=2$ вложения (14) записываются еще и так

\[
W_{2}^{r}\left(R_{n}\right) \rightleftarrows W_{2}^{x r^{m}}\left(R_{m}\right) .
\]

Естественными продолжениями $W$-классов являются классы, в определении к-рых фигурирует понятие дробной производной по Лиувиллю (см. Дробное интегрирование и дифференцирование).

Употребляя терминологию обобщенных функций, можно задать основной класс $\Lambda$ функций так, что построенный над ним класс $\Lambda^{\prime}$ обобщенных функций будет обладать следующими свойствами: 1) $L_{p}\left(R_{n}\right) \subset \Lambda^{\prime}$ при любом конечном $p \geqslant 0 ; 2)$ при любом $l>0$, не обязательно целом, имеет смысл операция

\[
D_{j}^{l} f=\left(x_{j}^{\widehat{l_{j}} f}, f\right) \in \Lambda^{\prime},
\]

где $\tilde{\psi}, \hat{\psi}$ означают соответственно прямое и обратное Фурье преобразование $\left.\psi \in \Lambda^{\prime} ; 3\right)$ если $l$ - целое и функция $f \in L_{p}\left(R_{n}\right)$ имеет обобщенную по Соболеву производную $D_{j}^{l} f \in L_{p}\left(R_{n}\right)$, то для нее имеет место равенство (17).

При дробных $l$ на бесконечно дифференцируемых финитных функциях операция (17) совпадает с операцией дробного дифференцирования по Лиувиллю. Естественно называть $D_{j}^{l} f$ при нецелом $l$ д р о 6 н о й п р ои 3 в о д н о й от $f$ порядка $l$ по $x_{j}$.

Если теперь задан произвольный вектор $l=\left(l_{1}, \ldots, l_{n}\right)$, то можно ввести пространство $L_{p}^{\boldsymbol{l}}\left(R_{n}\right), 1 \leqslant p<\infty$, совпадающее с $W_{p}^{l}\left(R_{n}\right)$ при целых $l$, заменив в (13) $W$ на $L$.

Если $l=l_{1}=\ldots=l_{n}$, то положим $L_{p}^{l}=L_{p}^{\boldsymbol{l}}$. Семейство классов $L_{p}^{l}\left(R_{n}\right), l>0,1 \leqslant p<\infty$, может рассматриваться как естественное расширение семейства $W_{p}^{\boldsymbol{l}}\left(R_{n}\right)$ на дробное $l$, «естественное» потому, что с точки зрения интересующего нас круга идей классы $L_{p}^{l}$ обладают «всеми достоинствами и недостатками классов $W_{p}^{\boldsymbol{l}}$ ». Если в формуле (4) (где $[k]$ можно заменить на $k$ ), или (8) (где $l$ может быть дробным), или в (14), (16) (где $\boldsymbol{r}$ может быть дробным) заменить $W$ на $L$, то они останутся верными. Верной также останется формула (9), если в ней заменить $H$ на $L$ даже при более широком условии $x \geqslant 0$, однако в предположении, что $1<p<q<\infty$.

В дальнейшем продолжается применение аппарата обобщенных функций, но теперь уже составляющих пространство $S^{\prime}$. Для любого действительного числа $\rho$ имеет смысл операция (Бесселя - Макдональда):

\[
J_{\rho} f=\widehat{\left(1+|x|^{2}\right)^{-\rho / 2} \tilde{f}}, f \in S^{\prime},|x|^{2}=\sum_{j=1}^{n} x_{j}^{2},
\]

обладающая свойствами: $J_{0} f=f, J_{r+\rho}=J_{r} J_{\rho}, J_{-2 l}=$ $=(1-\Delta)^{l}, \quad l=0, \quad 1, \ldots$, где $\Delta=\sum_{j=1}^{n} \frac{\partial^{2}}{\partial x_{j}^{2}}-$ оператор Лапласа.

Изотропный класс $L_{p}^{\rho}=L_{p}^{\rho}\left(R_{n}\right), \quad 1<p<\infty$, может быть определен еще как совокупность функций $f$, представимых в виде $f=J_{\rho} \varphi$, где функции $\varphi$ пробегают пространство $L_{p}=L_{p}\left(R_{n}\right) \quad\left(L_{p}^{\rho}=J_{\rho}\left(L_{p}\right)\right)$, при этом, с точностью до эквивалентности,

\[
\|f\|_{L_{p}^{\rho}}=\|\varphi\|_{L_{p}}
\]

Это определение класса $L_{p}^{\rho}$ годится и для отрицательных $\rho$, но в этом случае $L_{p}^{\rho}$ есть совокупность, вообпе говоря, обобщенных функций $\left(L_{p}^{\rho} \subset S^{\prime}\right)$. В частности, $L_{p}^{0}=L_{p}$.

Операция $J_{\rho}$ может служить средством и для определения классов $B_{p \theta}^{r}\left(B_{p \infty}^{r}=H_{p}^{r}\right)$. Именно, будем называть обобщенную функцию $f$ р е г у л я р н о й в с м ыс сл е $L_{p}$ или принадлежащей к $S_{p}^{\prime}$, если найдется такое $\rho>0$, что $J_{\rho} f \in L_{p}$. Всякую функцию $f \in B_{p \theta}^{r}=B_{p \theta}^{r}\left(R_{n}\right)$, $1<\rho, \theta<\infty, \quad B_{p \infty}^{r}=H_{p}^{r}$, можно определить как регулярную в смысле $L_{p}$ функцию, представимую рядом

\[
f(x)=\sum_{s=0}^{\infty} q_{s}(x)
\]

слабо сходящимся к $f$ (в смысле $\left.S^{\prime}\right)$, где $q_{0}$ имеет спектр (носитель $\tilde{q}_{0}$ ) в $\Delta_{0}$, а $q_{s}$ при $s \geqslant 1$ имеет спектр в $\Delta_{s+1} \backslash \Delta_{s-1}^{\text {и }}=\left\{x ;\left|x_{j}\right| \leqslant 2^{s} ; j=1, \ldots, n\right\}$, и при этом

\[
\Delta_{s}=\left\{x ;\left|x_{j}\right| \leqslant 2^{s} ; j=1, \ldots, n\right\},
\]

\[
\|f\|_{B_{p \theta}^{r}}=\left(\sum_{s=0}^{\infty} 2^{s \theta r}\left\|q_{s}\right\|_{p}^{\theta}\right)^{1 / \theta}<\infty .
\]

В частности,

\[
\|f\|_{H_{p}^{r}}=\|f\|_{B}^{r \infty}=\sup _{s}\left(2^{s r}\left\|q_{s}\right\|_{L_{p}}\right) .
\]

Это определение класса $B_{p \theta}^{r}$ автоматически распространяется на случай $r<0$, и тогда функции $f$, входящие в эти классы, будут, вообще говоря, обобщенными $\left(f \in S^{\prime}\right)$. При этом $J_{r}\left(B_{p}^{0}\right)=B_{p}^{r},-\infty<r<\infty$.

Существуют и другие әквивалентные определения отрицательных классов $B_{p \theta}^{r}$, основанные на принципе интерполяции функциональных пространств. Пріведенное определение носит конструктивный характер каждый заданный параметрами $r, p, \theta$ класс определяется независимо, при этом можно конструктивно определить линейные операции, при помощи к-рых по данной функции $f \in S_{p}^{\prime}$ определяется функция $q_{s}$ (экспоненциального типа $2^{s+1}$ при $s \geqslant 1$ и типа 1 при $s=0)$.

Справедлива теорема вложения:

\[
\Lambda_{p}^{r}\left(R_{n}\right) \longrightarrow \Lambda_{q}^{r-(1 / p-1 / q) n}\left(R_{n}\right)
\]

типа теоремы (4), но с $n=m$, верная при любом действительном $r$ для $\Lambda=L, 1<p<q<\infty$ или для $\Lambda=B, 1<$ $<p<q<\infty, 1<\theta<\infty$ или для $\Lambda=H, 1<p<q \leqslant \infty$.

С другой стороны, при $r-(n-m) / p=0$ произвольная функция $f \in \Lambda_{p}^{r}\left(R_{n}\right)$, вообще говоря, не имеет следа на $\boldsymbol{R}_{m}(m<n)$, если не налагать на нее дополнительных условий.

Выше были сформулированы В. т. для классов функций, определенных на всем $n$-мерном пространстве $R_{n}$ (см. [5]). Но для приложений важно иметь подобные теоремы для возможно общих областей $\Omega \subset R_{n}$. В настоящее время выяснена геометрич. структура областей $\Omega$, для к-рых верны указанные теоремы вложения для $W$-, $B$ - и $H$-классов, где надо заменить $R_{n}, R_{m}$ соответственно на $\Omega, R_{m} \cap \Omega$. Для изотропных классов $W_{p}^{r}(\Omega)$, $B_{p \theta}^{r}(\Omega)$ область $\Omega$ должна удовлетворять условию конуса или, что равносильно, граница ее должна удовлетворять локально условию Липшица. Для анизотропных же классов $W_{p}^{\boldsymbol{r}}(\Omega), B_{p \theta}^{\boldsymbol{r}}(\Omega)$ область $\Omega$ должна удовлетворять условию $\boldsymbol{r}$-рога или изогнутого конуса (конуса