в квадратичном расширении $\mathbb{Q}(\sqrt{d})$ поля рациональных чисел $\mathbb{Q}$ определяется вычетом $p$ по модулю 4|d|.

Закон взаимности Гаусса обобщается на сравнения вида

\[
x^{n} \equiv a(\bmod p), \quad n>2 .
\]

Однако при этом происходит переход от арифметики целых рациональных чисел к арифметике целых чисел расширения $K$ конечной степени $m$ поля рациональных чисел. Кроме того, для обобщения В. з. на вычеты $n$-й степени нужно предполагать, что рассматриваемое расширение содержит примитивный корень $\zeta$ степени $n$ из 1. При таком предположении для простых дивизоров $\mathfrak{B}$ поля $K$, не делящих $n$, имеет место сравнение

\[
N_{\mathfrak{B}} \equiv 1(\bmod n),
\]

где $N_{\Re}-$ норма дивизора $\mathfrak{\Re}$, равная числу классов вычетов максимального порядка этого поля по модулю Аналог символа Лежандра определяется при помощи сравнения

\[
\left(\frac{a}{\aleph^{*}}\right)=\zeta^{k} \equiv a^{\frac{N_{\mathfrak{B}}-1}{n}}(\bmod \mathfrak{P}) .
\]

Символ степенного вычета $\left(\frac{a}{b}\right)$ для пары целых чисел $a$ и $b$, аналогичный символу Якоби, определяется по формуле

\[
\left(\frac{a}{b}\right)=\Pi\left(\frac{a}{\psi_{i}}\right)^{m_{i}},
\]

если $(b)=\Pi \Re_{i}^{m_{i}}-$ разложение главного дивизора $(b)$ на простые сомножители и если $b$ взаимно просто с an. В. з. для $n=4$ в поле $\mathbb{Q}(i)$ был установлен К. Гауссом [2], для $n=3$ в поле $\mathbb{Q}\left(e^{\frac{2 \pi i}{3}}\right)-\Gamma$. Эйзенштейном [3]. Общий В. з. для символа степенного вычета в поле $\mathbb{Q}\left(e^{\frac{2 \pi i}{n}}\right)$ простой степени $n$ был установлен Э. Куммером [4]. Формула Куммера для регулярного простого числа $n$ имеет вид

![](https://cdn.mathpix.com/cropped/2023_07_08_828878dffb7842e6d39dg-1.jpg?height=69&width=804&top_left_y=1429&top_left_x=131)

где $a, b$ - целые числа поля $\mathbb{Q}\left(e^{\frac{2 \pi i}{n}}\right)$,

$a \equiv b \equiv 1(\bmod (\zeta-1))$

\[
l_{i}(a)=\left[\frac{d^{i} \log f\left(e^{u}\right)}{d u^{i}}\right]_{u=0}
\]

и $f(t)$ - многочлен степени $n-1$ такой, что

\[
a=f(\zeta), f(1)=1 .
\]

Следующий этап в изучении общих В. з. связан с работами Д. Гильберта [5], [6], выяснившего их локальный аспект. Д. Гильберт для нек-рых случаев установил В. з. в виде формулы произведения для его символа норменного вычета

\[
\prod_{\mathfrak{B}}\left(\frac{a, b}{*}\right)=1
\]

Он подметил также аналогию этой формулы с теоремой о вычетах алгебраич. функций - простые точки $\mathfrak{B}$ с символом норменного вычета $\neq 1$ соответствуют точкам ветвления на римановой поверхности.

Дальнейший прогресс в изучении В. з. связан с именами Ф. Фуртвенглера [7], Т. Такаги [8], Э. Артина [9], Х. Хассе [10]. Наиболее общая форма В. з. была цолучена И. Р. Шафаревичем [11].

Как и закон взаимности Гаусса, общие В. з. тесно связаны с задачей изучения законов разложения простых дивизоров $\Re$ заданного поля алгебраич. чисел $k$ в его алгебраич. расширения $\mathrm{K} / k$ с абелевой Галуа группой. В частности, теория полей классов, решающая эту задачу, может быть обоснована (см. [12]), исходя из закона взаимности ІІафаревича.

Jum.: [1] G a u s s C. F., Werke, Bd 1 - Disquisitiones

![](https://cdn.mathpix.com/cropped/2023_07_08_828878dffb7842e6d39dg-1.jpg?height=32&width=822&top_left_y=330&top_left_x=987)
biquadraticorum. Commentatio prima et secunda, в кн.: Werke, Bd 2, Gött., 1863, S. 65, 93; [3] E i s e n s t e i n G., "J. Math.", 1844, Bd 27; [4] K u m m e r E., "Ber. K. Akad. Wiss. Berlin", $1850 ;$ [5] H i l b e r t D., "Jahresber. Dtsch. Math.-

![](https://cdn.mathpix.com/cropped/2023_07_08_828878dffb7842e6d39dg-1.jpg?height=45&width=824&top_left_y=449&top_left_x=985)
Ann.», 1909, Bd 67, S. $1-31$; 1912, Bd 72, S. 346-86; 1913, $\mathrm{Bd} 74$, S. 413-29; [8] T a k a g i T., "J. Colloid Science", 1920 , v. 41 , t. 9; [9] A r t i n E., "Abh." Math. Semin. Hamburg Univ.", 1928, Bd 5; [10] H a s's e H., "Math. Ann.", 1933, Bd 107, № 5, s. 731-60; [11] III a Ф а p е в и ч И. Р., "Успехи матем. наук», 1948, т. 3, в. $3(25)$, с. 165; [12] Л а п и н А. И.,
"Изв. АН СССР. Сер. матем.", 1954, т. 18, № 4, с. 335-78; "Изв. АН СССР. Сер. матем.", 1954, т. 18, № 4, c. 335-78; $\Phi$ а д д е е в Д. К., в кн.: Проблемы Гильберта, М., 1969, ВЗАИМНЫЕ ЯДРА - две функции $K(x, s)$ и $K_{1}(x, s)$ действительных переменных $x, s$ (или, вообще, точек $P, Q$ евклидова пространства), определенные на квадрате $[a, b] \times[a, b]$ и удовлетворяющие условию:

\[
\begin{gathered}
K_{1}(x, s)+K(x, s)= \\
=\int_{a}^{b} K(x, t) K_{1}(t, s) d t=\int_{a}^{b} K_{1}(x, t) K(t, s) d t .
\end{gathered}
\]

Взаимное с $K(x, s)$ ядро $K_{1}(x, s)$, когда оно существует, является ядром резольвенты интегрального Фредгольма уравнения:

\[
\varphi(x)-\int_{a}^{b} K(x, s) \varphi(s) d s=f(x) .
\]

ВЗАИМОДЕИСТВИЯ ПРЕДСТАВЛЕНИЕ Бакушинский. основных возможных (наряду с ІІрёдингера представлением и с Гейзенберга представлением) эквивалентных представлений зависимости от времени $t$ операторов $A$ и волновых функций $\psi$ в квантовой механике и квантовой теории поля. Квантовую систему с учетом взаимодействия между ее тастями (в квантовой механике) или составляющими ее различными полями (в квантовой теории поля) можно описать в представлении ІІрёдингера с помощью ІІІрёдингера уравнения:

\[
i \hbar \frac{\partial \psi_{S}(t)}{\partial t}=H \psi_{S}(t)=\left(H_{0}+H_{1}\right) \psi_{S}(t) .
\]

Предполагается, что полный гамильтониан $H$ разделяется на гамильтониан свободных (невзаимодействующих) частей или полей $H_{0}$ и гамильтониан взаимодействия $H_{1}$. Гамильтонианы $H_{0}$ и $H_{1}$ являются некоммутирующими (иначе задача становится тривиальной, так как разбиение гамильтониана $H$ на $H_{0}$ и $H_{1}$ теряет смысл) функциями операторов, соответствующих различным свободным полям и не зависящих от времени $t$ в представлении ІІрёдингера. Унитарное преобразование

\[
\psi_{S}(t)=e^{-i \frac{H_{0}}{\hbar} t} \Phi_{I}(t)
\]

осуществляет переход к В. п., где волновая функция удовлетворяет уравнению:

\[
i \hbar \frac{\partial \Phi_{I}(t)}{\partial t}=H_{1}(t) \Phi_{I}(t)
\]

т. е. зависимость $\Phi_{I}(t)$ от $t$ определяется гамильтонианом взаимодействия в представлении

\[
H_{1}(t)=e^{+i \frac{H_{0}}{\hbar} t} H_{1} e^{-i \frac{H_{0}}{\hbar} t} .
\]

При этом среднее значение оператора $A$ в представлении Шрёдингера

$\bar{A} \equiv \bar{A}_{S}=\psi_{S}^{*}(t) A_{S} \psi_{S}(t)=\Phi_{I}^{*}(t) e^{i \frac{H_{0}}{\hbar} t} A_{S} e^{-i \frac{H_{0}}{\hbar} t} \Phi_{I}(t)(5)$