К. Т., «Успехи матем. наук», 1957, т. 12, в. 4, с. 135-53; [7] Ю д о в ич В. И., "Прикл. матем. и механ.», 1967, т. 31, в. 1, с. $101-11$; [8] Л о г и н о в Б. В. т р е н о г и н В. А., "Докл. АН СCCР", 1971, т. 197, Nㅜ 1; [9] А х м е д о в К. Т.,

![](https://cdn.mathpix.com/cropped/2023_07_08_5cb9b6e493787c4ad64dg-1.jpg?height=45&width=829&top_left_y=285&top_left_x=119)

![](https://cdn.mathpix.com/cropped/2023_07_08_5cb9b6e493787c4ad64dg-1.jpg?height=47&width=749&top_left_y=304&top_left_x=122)

![](https://cdn.mathpix.com/cropped/2023_07_08_5cb9b6e493787c4ad64dg-1.jpg?height=52&width=799&top_left_y=342&top_left_x=154)

ВЕТВЛЕНИЯ ИНДЕКС - сумма $V=\sum(k-1)$ порядков ветвления точек компактной римановой поверхности $S$, рассматриваемой как $n$-листная поверхность наложения над римановой сферой, распространенная на все конечные и бесконечно удаленные точки ветвления $S$. В. и. связан с родом $g$ и числом листов $n$ поверхности $S$ :

\[
V=2(n+g-1)
\]

См. также Риманова поверхность.

Лит.: [1] С п р и н г е р Д ж., Введение в теорию римановых поверхностей, пер. с англ., М., 1960, гл. 10.

ВЕТВЛЕНИЯ ТОчКА, 0 Т 6 а гоз а ч но го х а р а т т р а, - изолированная особая точка а аналитич. функции $f(z)$ одного комплексного переменного $z$ такая, что аналитическое продолжение к.-л. элемента функции $f(z)$ вдоль замкнутого пути, охватывающего $a$, приводит к новым элементам $f(z)$. Точнее, $a$ наз. В. т., если существуют: 1) кольцо $V=\{z ; \quad 0<|z-a|<\rho\}, \quad$ в к-ром $f(z)$ аналитически продолжается по любому пути; 2) точка $z_{1} \in V$ и к.-л. элемент функции $f(z)$, представленный степенным рядом

\[
\Pi\left(z_{1} ; r\right)=\sum_{v=0}^{\infty} c_{v}\left(z-z_{1}\right)^{v}
\]

с центром $z_{1}$ и радиусом сходимости $r>0$, аналитич. продолжение к-рого вдоль окружности $|z-a|=\left|z_{1}-a\right|$, проходимой один раз, напр. в положительном направлении, приводит к новому әлементу $\Pi^{\prime}\left(z_{1} ; r^{\prime}\right)$, отличающемуся от $\Pi\left(z_{1} ; r\right)$. Если после нек-рого минимального числа $k>1$ таких обходов снова получается исходный әлемент $\Pi\left(z_{1} ; r\right)$, то это же самое будет иметь место для всех элементов ветви аналитической функции $f(z)$, определяемой в $V$ элементом $\Pi\left(z_{1} ; r\right)$. В таком случае $a$ является В. т. к о н е ч о го по р я д к а $k-1$ для указанной ветви. В проколотой окрестности $V$ В. т. $a$ конечного порядка эта ветвь представима в виде о б о ря д а П юи и ё:

\[
f(z)=\sum_{v=-\infty}^{+\infty} b_{v}(z-a)^{v / k}, \quad z \in V
\]

Если $a=\infty$ - бесконечно удаленная В. т. конечного порядка, то в нек-рой окрестности $V^{\prime}=\{z ;|z|>\rho\}$ данная ветвь $f(z)$ представима в виде аналога ряда (1):

\[
f(z)=\sum_{v=-\infty}^{+\infty} b v^{-v / k}, \quad z \in V^{\prime}
\]

Поведение римановой поверхности $R$ функции $f(z)$ над В. т. конечного порядка $a$ характеризуется тем, что над $a$ соединяются вместе $k$ листов той ветви $f(z)$, к-рая определяется элементом П $\left(z_{1} ; r\right)$. При этом поведение других ветвей $R$ над $a$ может быть совершенно иным.

Если в ряде (1) или (2) среди коэффициентов $b_{v}$ с отрицательными индексами $v$ имеется лишь конечное число отличных от нуля, то $а$ - алгебраическая точка ветьления, или ал геб р а и ч ская особ ая то ч к а. Такая В. т. конечного порядка характеризуется также тем, что при любом стремлении $z \rightarrow a$ в $V$ или $V^{\prime}$ значения всех элементов ветви, определяемой $\Pi\left(z_{1} ; r\right)$, стремятся к определенному конечному или бесконечному пределу.

П р и м е р: $f(z)=\sqrt[k]{z}, \quad k>1$ - натуральное число, $a=0, \infty$ Если в ряде (1) или (2) имеется бесконечно много ненулевых коэффициентов $b_{v}$ с отрицательными индексами $v$, то В. т. конечного порядка $a$ относится к классу т р а н ц е нд е н т н ы х В. т. Пример: $f(z)=\exp (1 / \sqrt[k]{\sqrt{z}}), k>1$ - натуральное число, $a=0$.

Наконец, если ни при каком числе последовательных обходов нельзя возвратиться к исходному элементу, то а наз. логарифмической точкой ветвления, или В. т. бе с к о е ч но го по р я д к а, и также относится к трансцендентным В. т. Пример: $f(z)=\operatorname{Ln} z, a=0, \infty$. Над логарифмич. В. т. соединяются бесконечно много листов той ветви $f(z)$, к-рая определяется элементом $\Pi\left(z_{1} ; r\right)$

В случае аналитич. функции многих комплексных переменных $f(z), z=\left(z_{1}, z_{2}, \ldots, z_{n}\right), n \geqslant 2$, точка $a$ пространства $\mathbb{C}^{n}$ или $\mathbb{C} P^{n}$ наз. В. т. П о р я д к а $m, 1 \leqslant m \leqslant \infty$, если она является В. т. порядка $m$, вообще говоря, многолистной голоморфности области функции $f(z)$. В отличие от случая $n=1$, при $n \geqslant 2$ В. т., как и другие особые точки аналитических функций многих комплексных переменных, не могут быть изолированными.

Лum.: [1] М а р к у ші е в и ч А. К., Теория аналитических Функций, 2 изд., т. 2 , М., 1968, гл. $8 ;[2] \Phi$ у к с Б. А., Теория аналитических функций многих комплексных переменных,

![](https://cdn.mathpix.com/cropped/2023_07_08_5cb9b6e493787c4ad64dg-1.jpg?height=49&width=818&top_left_y=896&top_left_x=1005)
в е р х о о ти - особая точка минимальной поверхности, в к-рой первая квадратичная форма поверхности обращается в нуль; тем самым фактически В. т. возможна лишь на обобщенной минимальной поверхности. Своим названием эта особая точка обязана тому факту, что в ее окрестности строение обобщенной минимальной поверхности подобно строению римановой поверхности функции $w=z^{n}, n \geqslant 2$, над точкой $z=0$, т. е. там обобщенная минимальная поверхность имеет многолистную ортогональную проекцию на нек-рую плоскую область, в к-рой проекция самой В. т. является внутренней точкой с единственным прообразом. В окрестности В. т. $(u=0, v=0)$ координаты $(x, y, z)$ минимальной поверхности представимы в виде

\[
x+i y=a w^{m}+O\left(|w|^{m+1}\right) \text {, }
\]\[
z=\operatorname{Re}\left(b w^{m+n}\right)+O\left(|w|^{m+n+1}\right), \quad w=u+i v,
\]

где $a \neq 0$ и $b \neq 0$ - две комплексные постоянные, $m \geqslant 2$ и $n \geqslant 1-$ целые числа, соответственно называемые порядком и индексом В. т., $u$ и $v-$ внутренние изотермич. координаты.

На основании этого представления получена теорема: если числа $m+n$ и $m$ - взаимно простые, то минимальная поверхность имеет $(m-1)(m+n)$ различных линий самопересечения, исходящих из В. т. с определенными направлениями, причем все соседние направления образуют между собой равные углы.

Различают два вида В. т. - фальшивые В. т. и истинные (-нефалышивые). Фалышивые В. т. представляют собой особенность отображения, определяющего поверхность, и от нее можно избавиться перепараметризацией (напр., если $r=r(w)$ - регулярная минимальная поверхность, то обобщенная минимальная поверхность $r=r\left(w^{2}\right)$ будет иметь в точке $w=0$ фалышивую В. т.). Истинная В. т. представляет собой реальную особенность самой поверхности, и у нее есть следующее важное свойство: в окрестности истинной В. т. поверхность можно изменить так, что новая поверхность, совпадая с исходной вне деформированной окрестности, будет иметь менышую площадь по сравнению с исходной поверхностью. Теория обобщенных минималыных поверхностей с В. т. послужила основой для общей теории вложений с ветвлениями, развитой для широкого класса двумерных поверхностей в $R^{n}, n \geqslant 3$. И.

ВЕТВЬ АНАЛИТИЧЕСКОИ ФУНКДИИ - резуЛьтат аналитического продолжения данного элемента