Лum.: [1] Я н к е Е., Э м д е Ф., Л е ш Ф., Специалыные функции. Формулы, графики, таблицы, 2 изд., пер. с нем., М.,

ГАРМОНИЗУЕМАЯ ДИНАМИЧЕСКАЯ СИСТЕМА поток, траектории к-рого после нек-рой замены времени становятся почти периодическими. Обычно при әтом еще требуют, чтобы каждая траектория была всюду плотна в фазовом пространстве (так что можно говорить о гармонизуемом минимальном множестве). Д. В. Аносов.

ГАРМОНИЗУЕМЫИИ СЛУЧАЙЫГИ ПРОДЕСС комплекснозначная случайная функция $X=X(t)$ действительного параметра $t$, допускающая представление в виде стохастического интеграла

\[
X(t)=\int_{-\infty}^{\infty} e^{i \lambda t} d \Phi(\lambda)=\lim \sum_{k} e^{i \lambda t} \Delta_{k} \Phi(\lambda)
\]

где $\Phi(\lambda),-\infty<\lambda<\infty,-$ случайный процесс. Приращения $\Delta_{k} \Phi(\lambda)=\Phi\left(\lambda_{k+1}\right)-\Phi\left(\lambda_{k}\right)$ в (*) задают случайные «амплитуду» $A_{k}=\left|\Delta_{k} \Phi(\lambda)\right|$ и «фазу» $\theta_{k}=\arg \Delta_{k} \Phi(\lambda)$ әлементарных колебаний вида

\[
A e^{i(\lambda t+\theta)}=e^{i \lambda t} \Delta_{k} \Phi(\lambda)
\]

частоты $\lambda, \lambda_{k} \leqslant \lambda \leqslant \lambda_{k+1}$, суперпозиция к-рых в пределе дает случайный процесс $X=X(t)$. Переход к пределу (в среднем квадратичном) в представлении (*) осуществляется при все более мелком разбиении прямой $-\infty<$ $<\lambda<\infty$ на интервалы $\Delta_{k}=\left(\lambda_{k}, \lambda_{k+1}\right)$, когда $\max _{k}\left(\lambda_{k+1}-\right.$ $\left.-\lambda_{k}\right) \rightarrow 0$. Обычно предполагают, что

\[
F\left(\Delta_{1} \times \Delta_{2}\right)=\mathrm{E}\left(\Delta_{1} \Phi \cdot \Delta_{1} \bar{\Phi}\right)
\]

как функция множеств $\Delta_{1} \times \Delta_{2}$ на плоскости задает комплексную меру ограниченной вариации; в этом случае соответствующий процесс $\Phi(\lambda),-\infty<\lambda<\infty$ [или точнее, соответствующая случайная мера $d \Phi(\lambda)]$ однозначно оп ределяется самим процессом $X(t),-\infty<t<\infty$ :

\[
\Delta \Phi(\lambda)=\lim _{T \rightarrow \infty} \frac{1}{2 T} \int_{-T}^{T} \frac{e^{-i \lambda_{2} t}-e^{-i \lambda_{1} t}}{-i t} X(t) d t
\]

для любого интервала $\Delta=\left(\lambda_{1}, \lambda_{2}\right)$ такого, что $d \Phi\left(\lambda_{1}\right)=$ $=d \Phi\left(\lambda_{2}\right)=0$ и

\[
\Phi(\lambda)=\lim _{T \rightarrow \infty} \int_{-T}^{T} e^{-i \lambda t} X(t) d t
\]

для любой точки $\lambda,-\infty<\lambda<\infty$. Случайный процесс $X(t),-\infty<t<\infty$, является $\Gamma$. с. П. тогда и только тогда, когда его корреляционная функция представима в виде

\[
B(s, t)=\int_{-\infty}^{\infty} \int_{-\infty}^{\infty} e^{i(\lambda s-\mu t)} F(d \lambda \times d \mu)
\]

П р и м р ы Г. с. П. 1) Стационарный случайный процесс. Если

\[
X_{0}(t)=\int_{-\infty}^{\infty} e^{i \lambda t} d \Phi_{0}(t)
\]

- стационарный случайный процесс, то процесс вида

\[
X(t)=c(t) X_{0}(t)
\]

где $c(t)=\int_{-\infty}^{\infty} e^{i \lambda t} m(d \lambda), m(d \lambda)$ - некоторая мера на прямой, вообще говоря, уже не будет стационарным, но он будет гармонизуемым:

\[
X(t)=\int_{-\infty}^{\infty} e^{i \lambda t} d \Phi(\lambda),
\]

где случайная мера $d \Phi(\lambda)$ определена формулой

\[
\Delta \Phi(\lambda)=\int_{\Delta} m(\Delta-\lambda) d \Phi_{0}(\lambda)
\]

2) Процесс, определяемый с помощью с ко ль з яще г с умми рования

\[
X(t)=\int_{-\infty}^{\infty} c(t-s) d Z(s)
\]

где $d Z(t)$ - нек-рая случайная мера на прямой, а весовая функция $c(t)$ того же типа, что и выше:

\[
c(t)=\int_{-\infty}^{\infty} e^{i \lambda t} m(d \lambda)
\]

в этом случае

\[
X(t)=\int_{-\infty}^{\infty} e^{i \lambda t} d \Phi(\lambda)
\]

где

\[
\Delta \Phi(\lambda)=\int_{\Delta}\left[\int_{-\infty}^{\infty} e^{-i \lambda t} d Z(t)\right] m(d \lambda) .
\]

М., Лит.: [1] Л о ә в М., Теория вероятностей, пер.

ГАРМОНИКА - простейшая периодич. А. Фузанов. вида

\[
A \sin (\omega x+\varphi) \text {. }
\]

Эта функция встречается при рассмотрении многих колебательных процессов. Число $A$ наз. амплитудой, $\omega-$ частотой, $\varphi$ - начальной фазой,$T=2 \pi / \omega-$ периодом колебания. Функции $\sin (2 \omega x+\varphi), \quad \sin (3 \omega x+\varphi), \quad \ldots$ наз. соответственно второй, третьей и т. Д. высшими $\Gamma$. относительно основной $\Gamma$. Помимо самих $\Gamma$., рассматривают их суммы

\[
a_{0}+a_{1} \sin (\omega x+\varphi)+a_{2} \sin (2 \omega x+\varphi)+\ldots,
\]

так как очень широкий класс функций разлагается в ряды вида (*) для изучения различных процессов.

ГАРМОНИчеСКА А. И. Барабанов. применяемый для обозначения емкости множества в евклидовом пространстве $\mathbb{R}^{n}$, получаемой методом классической потенциала теории при помощи ньютонова потенциала при $n \geqslant 3$ или логарифмического потенциала при $n=2$, в отличие от аналитической емкости или емкостей, получаемых при помощи потенциалов других типов.

ГАРМОНИЧЕСКАЯ МАЖОРАНТА, н а и м е н ьIII а я г а р о о и ч е ская ма о о ан та $v(x)$ с е м е й с т в а $\left\{u_{i}\right\},-$ нижняя огибающая семейства

![](https://cdn.mathpix.com/cropped/2023_07_08_1a5ffef57032107040a1g-1.jpg?height=50&width=838&top_left_y=1310&top_left_x=985)
$\left\{u_{i}\right\}$ субгармонич. функций на открытом множестве $D$ евклидова пространства $\mathbb{R}^{n}, n \geqslant 2$, т. е.

\[
v(x)=\inf \left\{v_{k}(x) ; \quad v_{k} \in \mathfrak{B}\right\}, \quad x \in D .
\]

Г. м. $v(x)$ либо является гармонич. функцией, либо $v(x) \equiv+\infty$. В случае семейства, состоящего из одной функции $u$, субгармонической на более широком множестве $D_{0} \sqsupset \bar{D}$, иногда используется также понятие н а и л у чш е й $\Gamma$. м. $v^{*}-$ решения обобщенной задачи Дирихле для $D$ по значениям $u$ на границе $\Gamma=\partial D$. Всегда $v^{*}-v \geqslant 0$, причем справедлива формула [1]

\[
v^{*}(x)-v(x)=-\int_{\Gamma} G(x, y) d \mu(y), \quad x \in D,
\]

где $\mu$ - ассоциированная с $u$ мера, $\mu \leqslant 0, \boldsymbol{G}(x, y)$ (обобенная) функция Грина задачи Дирихле для $D$. Наилучшая и наименьшая $\Gamma$. м. совпадают тогда и только тогда, когда множество всех иррегулярных точек $\Gamma$ имеет $\mu$-меру нуль.

Соответственно, если $\left\{\tilde{u}_{i}\right\}$ - семейство супергармонич. функций на $D$, то на и б о л ь Ії а я $\mathrm{r}$ a pмо ни ч е ск а я мино ра ан т а $w(x)$ с е мейс т в а $\left\{\tilde{u_{i}}\right\}$ определяется как верхняя огибающая сөмейства всех субгармонич. минорант семейства $\left\{\tilde{u}_{i}\right\}$; при этом $-w(x)$ есть наименьшая $\Gamma$. м. для семейства $\left\{-\tilde{u}_{i}\right\}$.

Другую постановку вопроса о Г. м., связанную с задачей Коши для уравнения Лапласа, см. в ст. Гармоническая бункция.

Jum.: [1] F r o s t m a n O., Potentiel d'équilibre et capacité des ensembles avec quelques applications à la théorie des fonctiпотенциала, пер. с франц., М., 1964, гл. 2, 9. Е. Д. Соломенцев.