И наз. обычно г р а д и е н т о м. Понятие Г. r. распространяется на случай, когда $X$ - риманово многообразие (кокечномерное или гильбертово бесконечномерное), a $f$ - гладкая действительная функция на $X$. Направление вдоль Г. г. среди всех направлений, проходящих через точку $x_{0}$, выделяется наибольшим ростом функции $f$.

ГАТО ДИФФЕРЕНЦИАЛ о т о б р а ж е н И я $f(x)$ линейного топологич. пространства $X$ в линейное топологич. пространство $Y$ - функция

\[
h \rightarrow D f\left(x_{0}, h\right)
\]

где предел

\[
D f\left(x_{0}, h\right)=\left.\frac{d}{d t} f\left(x_{0}+t h\right)\right|_{t=0}=\lim _{t \rightarrow 0} \frac{f\left(x_{0}+t h\right)-f\left(x_{0}\right)}{t}
\]

в предположении, что он существует для всех $h \in X$, а сходимость понимается в топологии пространства $Y$. Так определенный Г. Д. однороден, но неаддитивен. Аналогично вводятся $\Gamma$. д. высших порядков. Отображение $h \rightarrow D f\left(x_{0}, h\right)$ наз. иногда $\Gamma$ а т о в а р и а ц и е й, или с л а б ы м д ифф е р е н ц и а л о м (см. также Дифференцирование отображений, Вариация).

Обычно накладывают дополнительное требование линейности п непрерывности. $Г$. Д.: $D f(x, h)=f_{\Gamma}^{\prime}\left(x_{0}\right) h$, $f_{\Gamma}^{\prime}\left(x_{0}\right) \in L(X, Y)$. В этом случае $f_{\Gamma}^{\prime}\left(x_{0}\right)$ наз. Гато производной. Если отображение $(x, h) \rightarrow D f(x, h)$ равномерно непрерывно по $x$ и непрерывно по $h$ в нек-рой области, то в этой области существует Фреше производная $f^{\prime}(x)$ и при этом $f^{\prime}(x) h=D f(x, h)$.

![](https://cdn.mathpix.com/cropped/2023_07_08_bff3d24bad773f64e0feg-1.jpg?height=52&width=794&top_left_y=1051&top_left_x=156)
Элементы функционального анализа, 2 изд., М., 1965; [2] Н о лций и функционального анализа, 4 изд., М., 1976.

ГАТО ПРоиЗводнАЯ, В. М. Тихомиров. н а я,- наиболее распространенная в бесконечномерном анализе, наряду с Фреше производной (с и л ь н о й п р о п в о д н о й), производная функционала или отображения. П р о и з в о д н о й $\Gamma$ а т о в точке $x_{0}$ отображения $f: X \rightarrow Y$ линейного топологич. пространства $X$ в линейное топологич. пространство $Y$ наз. непрерывное линейное отображение $f_{\Gamma}^{\prime}\left(x_{0}\right): X \rightarrow Y$, удовлетворяющее условию

\[
f\left(x_{0}+h\right)=f\left(x_{0}\right)+f_{\Gamma}^{\prime}\left(x_{0}\right) h+\varepsilon(h),
\]

где $\varepsilon(t h) / t \rightarrow 0$ при $t \rightarrow 0$ в топологии пространства $Y$ (см. также Гато вариация). Если отображениө $f$ имеет в точке $x_{0} \Gamma$. п., то оно наз. д и фф е р е нц и р у ем ы м п о Гат о. Для Г. п. теорема о дифференцировании сложной функции, вообще говоря, неверна. См. также Дифференцирование отображений.

Jum.: [1] G a t e a u x R., "C. r. Acad. sci.», 1913, t. 157, p. $325-27 ;$; 2$]$ К о л м о гор о в А. Н., Ф о м и н С. В., Эле1976; [3] Л ю с т е р н и $\mathrm{k}$ Ј. А., С о б о л е в В. И., Элементы Функционального анализа, 2 изд., М., 1965; [4] А в е р б у х
В. И., С м о л я н о в О. Г., «Успехи матем. наук», 1967, т. 22, В. И., С м о л я н о в О. Г., "Успехи матем. наук", 1967, т. 22 ,
в. 6, с. $201-60$

ГАУССА ВАРИАЦИОННАЯ ЗАДАЧА - вариационная задача, исследованная впервые $K$. Гауссом [1] и в современных терминах формулируемая следующим образом. Пусть $\mu$ - положительная мера в евклидовом пространстве $\mathbb{R}^{n}(n \geqslant 3)$, имеющая конечную энергию (см. Энераия мер), п пусть

\[
U^{\mu}=U^{\mu}(x)=\int \frac{1}{|x-y|^{n-2}} d \mu(y)
\]

- ньютонов потенциал меры $\mu$. Требуется среди всех мер $\lambda$ с компактным носителем $K \subset \mathbb{R} n$ найти такую меру $\mu_{0}$, к-рая дает минимум интегралу

\[
\int\left(U^{\lambda}-2 U^{\mu}\right) d \lambda
\]

представляющему собой скалярное произведение $(\lambda-2 \mu, \lambda)$ в предгильбертовом пространстве мер. Значение Г. в. з. определяется тем, что равновесная мера (см. Робена задача) может быть получена как решение Г. в. з. при определенном выборе меры $\mu$; напр., можно принять за $\mu$ равномерное распределение массы на сфере с центром в начале координат, охватывающей множество $K$.

Лum.: [1] G a u s s C. F., Werke, Bd 5, Gött., 1867, S. потенциала, М., 1966 , гл. 2; [3] Б р е л о М., Основы классической теории потенциала, пер. с франц., М., 1964, гл. 11.

ГАУССА $\boldsymbol{B A K O H ~ - ~ у п о т р е б и т е л ь н о е ~ Н . ~ С о л о м е н ц е в . ~}$ нормального распределения. Название связано с той ролью, к-рую это распределение играет в ошибок теории К. Гаусса. Плотности

\[
\frac{h}{\sqrt{ } \pi} e^{-h^{2} x^{2}}, \quad h>0
\]

(именно они первоначально назывались Г. з.) появились у К. Гаусса в соч. «Теория движения небесных тел» (1809). В книге 2, раздел $3, \S 177$ был сформулирован принцип: «Если какая-нибудь величина будет определена из многих непосредственных наблюдений, произведенных при одинаковых обстоятельствах и с одинаковой тщательностью, то среднее арифметическое из всех наблюдавшихся значений окажется наиболее вероятным значением..." [1]. Это положение интерпретируется следующим образом: пусть истинное значение наблюдаемой величины будет $z$ и пусть плотность вероятности получить результат $x$ равна $\varphi(x-z)$. Тогда при любом $n$ и любых $x_{1}, \ldots ., x_{n}$ совместная плотность $\varphi\left(x_{1}-z\right) \ldots$ $\ldots \varphi\left(x_{n}-z\right)$ достигает максимума (как функция $z$ ) при

\[
z=\frac{x_{1}+\ldots+x_{n}}{n}
\]

Отсюда легко получить сначала, что отношение $\varphi^{\prime}(x) / x \varphi(x)$ не зависит от $x$, а затем, что $\varphi(x)$ имеет вид (*). Следует отметить, что указанный выше принцип неоднократно подвергался критике.

Лит.: [1] Г а у с с К. Ф., Избранные геодезические сочинения, пер. с латин. и нем., т. 1 , M., 1957, с. $89-109$ [2] P o i n c a r é H., Calcul des probabilités, 2 éd., P., 1912.

ГАУССА ЗАКОН ВЗАИМНОСТИ - соотношение, связывающее значения Лежандра символов $\left(\frac{p}{q}\right)$ и $\left(\frac{q}{p}\right)$ для различных нечетных простых чисел $p$ и $q$ (см. Кв дратичный закон взаимности). Кроме основного Г. з. в. для квадратичных вычетов, заключающегося в соотношении:

\[
\left(\frac{p}{q}\right)\left(\frac{q}{p}\right)=(-1)^{\frac{p-1}{2} \cdot \frac{q-1}{2}},
\]

имеются еще два дополнения к указанному закону, а именно:

\[
\left(\frac{-1}{p}\right)=(-1)^{\frac{p-1}{2}} \text { и }\left(\frac{2}{p}\right)=(-1)^{\frac{p^{2}-1}{8}} .
\]

Закон взаимности для квадратичных вычетов был впервые высказан Л. Эйлером (L. Euler, 1772). А. Лежандр (A. Legendre, 1785) дал формулировку закона в современной форме и доказал часть этого закона. Первое полное доказательство Г. з. в. было дано К. Гауссом (C. Gauss, 1801) (см. [1]). В течение жизни К. Гаусс дал восемь различных доказательств квадратичного закона взаимности, построенных на различных принципах.

Попытки установить закон взаимности для кубических и биквадратичных вычетов привели К. Гаусса к введению кольца целых комплексных чисел.

Лит.: [1] Г а у с с К. Ф., Труды по теории чисел, пер. с нем. и латин., М., 1959; [2] В ин о г р а д о в И. М., Основы теории чисел, 8 изд., М., 1972; [3] Х а с с е Г., Лекции по теории чисел, пер. с нем., М., 1953.