Jum $:$ [1] B e n d i x s o n I., "Acta Math.", 1901, v, 24, p. 1И. И., М а й е p A. $\boldsymbol{\Gamma}$., Качественная теория динамических систем второго порядка, M., 1966; [3] F r o m m e r M., "Math. Аn а н о в B. В., Качественная теория дифференциальных уравнений, 2 изд., М. МЛ., 1949; [5] Б р ю н о А. Д., «Изв. АН СССР. Сер. матем.», 1965, т. 29, №2, с. 329-64. МЛ. Э. Рейзинъ.

ВЫРОЖДЕННОЕ РАСПРЕДЕЛЕНИЕ в $n$-M е p н о м е в к ли по в о м п р о с т р а с т в е - любое распределение, сосредоточенное с вероятностью 1 на нек-ром линейном многообразии размерности, меньшей $n$, рассматриваемого пространства. В противном случае распределение наз. н е в ы р о ж е н н ы м. В. р. в случае конечных вторых моментов характеризуется тем, что ранг соответствующей матрицы ковариаций (или корреляционной матрицы) $r$ меньше $n$. При этом $r$ совпадает с наименьшей размерностью линейных многообразий, на к-рых сосредоточено данное В. р. Понятие В. р. очевидным образом распространяется на распределения в линейных пространствах. Иногда В. р. наз. не с обственным и рас п р едел ениям и, а невырожденные - с о б с т в ен н ы м и р а сп р е д е л ения и п. А. В. Прохоров.

ВЫРОЖДЕННОЕ УРАВНЕНИЕ С ч а с т Н Ы М И п р о и з в о д ы м и - дифференциальное уравнение с частными производными, тй к-рого вырождается в нек-рых точках области задания уравнения или на ее границе. Тип уравнения или системы уравнений в точке определяется одним или несколькими алгебраич. соотношениями между коэффициентами. Среди этих соотношений имеются, как правило, строгие неравенства. Если в нек-рых точках рассматриваемой области вместо строгих неравенств выполняются нестрогие, то говорят о вырождении типа, а уравнение (система уравнений) наз. в ы р о жд а ю щ и м с я, или в ы р о жд е Н н ы м. Различают вырожденные эллиптические уравнения, вырожденные гиперболические уравнения, вырожденные параболические уравнения (системы уравнений).

П р и м е р ы:

\[
x u_{x^{4}}+u_{y^{4}}+u_{z^{4}}+u_{x}=0
\]

- вырожденное эллиптич. уравнение в полупространстве $x \geqslant 0$;

\[
y^{2} u_{y y}-u_{x x}=0
\]

- вырожденное гиперболич. уравнение во всей плоскости;

\[
-u_{t}+u_{y y}+y u_{x}=0
\]

- вырожденное параболич. уравнение в области $t \geqslant 0$

\[
y u_{x}-v_{y}=0, \quad u_{y}+v_{x}=0
\]

- вырожденная эллиптич. система при $y \geqslant 0$.

В. у. встречаются в теории пограничного слоя, в безмоментной теории оболочек, в теории диффузионных процессов, в частности в теории броуновского движения, и во многих других задачах механики и физики.

Исследования В. у. ведутся по двум тесно связанным между собой направлениям: 1) доказывается разрешимость краевых задач с учетом тех изменений в постановке, к-рые происходят в силу вырождения типа; 2) устанавливаются свойства решений, аналогичные свойствам невырожденных уравнений (гладкость, неравенства Гарнака для эллиптич. и параболич. уравнений и т. П.).

Наиболее полно изучены В. у. 2-го порядка эллиптич. и параболич. типов (строго говоря, параболич. уравнение тоже можно считать вырожденным әллиптич. уравнением, удовлетворяющим дополнительным условиям). В случае, когда вырождение типа имеется не только на границе, но и во внутренних точках (напр., во всех точках рассматриваемой области), такие уравнения называют еще у р а вн е ни я м и с н еот рицательной характе ри с тичес кой фо рмой, эл липтико п а р а болич е скими уравнениями, ульт р а па а аболич е скими у ра внения яи.

Особенностью В. у. является специфич. постановка краевых задач. Граничные условия иногда приходится задавать не на всей границе, а на ее части. М. В. Келдыш впервые обратил внимание на зависимость постановки краевой задачи от характера вырождения эллиптич. уравнения на границе. Для общего эллиптикопараболич. уравнения 2-го порядка

\[
a^{i k}(x) u_{x_{i} x_{k}}+b^{i}(x) u_{x_{i}}+c(x) u=f(x) ; a^{i k} \xi_{i} \xi_{k} \geqslant 0,(*)
\]

первая краевая задача ставится следующим образом. Пусть $\Gamma$ - граница рассматриваемой области $D, n=$ $=\left(n_{1}, n_{2}, \ldots, n_{m}\right)-$ внутренняя нормаль к $\Gamma$, а $\tilde{\Gamma}-$ та часть $\Gamma$, где $a^{i k} n_{i} n_{k}=0 \quad$ и $\left(b^{i}-a_{x}^{i j}\right) n_{i} \geqslant 0$. Требуется найти решение уравнения (*) в области $D$ так, чтобы $\left.u\right|_{\Gamma \backslash \tilde{\Gamma}}=\varphi$. Были доказаны существование и единственность обобщенного решения этой задачи и указаны достаточные условия, при к-рых обобщенное решение будет гладким.

Так как частным случаем В. у. являются уравнения 1-го порядка, то ясно, что решения вырожденных эллиптич. уравнений, вообще говоря, не будут гладкими внутри области, если граничные условия недостаточно гладкие. Однако примеры показывают, что и при бесконечно дифференцируемых граничных условиях и коэффициентах В. у. его решения могут не быть бесконечно дифференцируемыми. Найдено условие гипоэллиптичности для общего вырожденного эллиптич. уравнения 2-го порядка.

Свойства решений вырожденных эллиптич. и параболич. уравнений 2-го порядка изучаются как с помощью геометрич. методов, так и с помощью методов теории вероятностей.

Большинство исследований вырожденных гиперболич. уравнений относится к уравнениям 2-го порядка с двумя независимыми переменными, вырождающимся на границе области. Эти работы стимулировались прежде всего изучением уравнений смешанного типа и связанных с ними задач газовой динамики. Для иллюстрации возникающих здесь вопросов рассмотрим задачу Коши $\left(u(x, 0)=\alpha(x), u_{y}(x, 0)=\beta(x)\right)$ для уравнения с главной частью $u_{y y}-y^{m} u_{x x}$. При $m<2$ эта задача имеет единственное решение, а при $m>2$ задача Коши, вообще говоря, некорректна. Для уравнения с главной частью $y^{m} u_{y y}-u_{x x}$ задача Коши с данными на линии вырождения поставлена корректно при $0<m<1$. Если $m \geqslant 1$, то так же, как и для эллиптич. уравнения, постановка задачи, вообще говоря, видоизменяется. Вместо $u_{y}(x, 0)$ задается $\lim _{y \rightarrow 0} \rho(y) u_{y}(x, y)$, где $\rho(y)$ нек-рая положительная функция, зависящая от коэффициентов уравнения.

Для гиперболич. уравнения с бо́льшим числом пространственных переменных

\[
\begin{aligned}
u_{t t}- & \left(a^{i j}(t, x) u_{x_{i}}\right) x_{j}+b^{i}(t, x) u_{x_{i}}+ \\
& +b^{0}(t, x) u_{t}+c(t, x) u=f,
\end{aligned}
\]

вырождающегося как на начальной плоскости $t=0$, так И внутри области, доказана корректность задачи Коши при выполнении нек-рых условий. Нашболее существенным из этих условий является выполнение неравенства

\[
\alpha t\left(b^{i} \xi_{i}\right)^{2} \leqslant A a^{i j} \xi_{i} \xi_{j}+a_{t}^{i j_{i} \xi_{j}}
\]

где $\alpha$ и $A$ - нек-рые положительные постоянные.