жат к числу систем с инвариантной мерой, изучаемых В эргодической теории.

Лит.: [1] П а р с Л.-А., Аналитическая динамика, пер. с англ., М., 1971; [2] А р н о л ь д В. И., Математические методы классической механики, М., 1974; [3] Л е в и - Ч и в и т а Т., А м а л ь д и У., Курс теоретической механики, пер. с итал.,
М., 1951, т. 2 , ч. $2 ;[4]$ Уи т т е к е р Е. Т., Аналитическая динамика, М.-Л., 1937. Д. В. Аносов.

ГАМИЛЬТОНОВА СИСТЕМА ЛИНЕИНАЯ̆ - система вида

\[
\frac{d p_{j}}{d t}=\frac{\partial H}{\partial q_{i}}, \quad \frac{d g_{j}}{d t^{-}}=-\frac{\partial H}{\partial p_{j}}, \quad j=1, \ldots, k,
\]

где $H-$ квадратичная форма с действительными коәффициентами от переменных $p_{1}, \ldots, p_{k}, q_{1}, \ldots, q_{k}$ с коэффициентами, к-рые могут зависеть от времени $t$. Г. с. л. наз. также лин е й но й к а но ни ч ес к о й с и с т е м о й. Система (1) может быть записана в векторной форме:

\[
J \frac{d x}{d t}=H(t) x
\]

где $\quad x-$ вектор-столбец $\quad\left(p_{1}, \ldots, p_{k}, q_{1}, \ldots, q_{k}\right)$, $H(t)=H(t) *$ — матрица квадратичной формы $2 H_{k}$ и $J=\left\|\begin{array}{rl}0 & I_{k} \\ -I_{k} 0\end{array}\right\|\left(I_{k}-\right.$ единичная $(k \times k)$-матрица). Уравнение (2) с произвольной неособой действительной кососимметрической матрицей $J$ может быть сведено подходящей заменой вида $x=S x_{1}$, где $S$ - неособая действительная матрица, к аналогичному виду:

\[
J_{1} \frac{d x_{1}}{d t}=H_{1}(t) x
\]

здесь $J_{1}$ - любая за ранее заданная действительная неособая кососимметрическая матрица. Ниже предполагается, что в (2) $|H(t)| \in L\left[t_{1}, t_{2}\right], \quad \forall-\infty<t_{1}<t_{2}<+\infty$. К канонич. уравнению (2) сводятся: векторное уравнение 2-го порядка

\[
\frac{d}{d t}\left[R(t) \frac{d y}{d t}\right]+P(t) y=0,
\]

в к-ром $y$ - вектор порядка $k, R(t)=R(t)^{*}, \quad P(t)=$ $=P(t)^{*}-$ действительные $(k \times k)$-матрицы функции, det $\stackrel{R}{R}(t) \neq 0 ;$ ур авнение

\[
\frac{d}{d t}\left[R(t) \frac{d y}{d t}\right]+Q \frac{d y}{d t}+P(t) y=0,
\]

где $Q=-Q^{*}$ - постоянная матрица, $R(t)=R(t)^{*}$, $P(t)=P(t)^{*}$, det $R(t) \neq 0$ (матрицы $P(t), Q, R(t)$ действительные), скалярное уравнение

\[
\sum_{j=0}^{k}(-1)^{j} \frac{d^{j}}{d t^{j}}\left(\varphi_{j}(t) \frac{d^{j} \eta}{d t^{j}}\right)=0
\]

где $\varphi_{j}(t)$ - действительные функции, $\varphi_{k}(t) \neq 0$, и аналогичное векторное уравнение. [Для уравнения (3)

для уравнения (3a)

\[
x=\left\|\begin{array}{l}
y \\
z
\end{array}\right\|, \quad z=R \frac{d y}{d z}
\]

\[
x=\left\|\begin{array}{c}
p \\
q
\end{array}\right\|, \text { где } p=R \frac{d y}{d t}+\frac{1}{2} Q y, q=y ;
\]

для уравнения (4) $x_{j}=\eta^{(j-1)}, j=1, \ldots, k$,

$\left.x_{j+k}=\varphi_{j} x_{j+1}-x_{k+j+1}^{\prime}, j=1, \ldots, k-1, x_{2 k}=\varphi_{k} x_{k}^{\prime}\right]$.

Скалярное уравнение (3) с $R(t)=1$, т. е. уравнение $\frac{d^{2} y}{d t^{2}}+P(t) y=0$, в к-ром $P(t)$-периодич. функция, наз. у р а внение м

Пусть $X(t)-$ м а т р иц ан т у р а вне ния (2) [матрица фундаментальной системы решений уравнения (2), нормированная условием $\left.X(0)=I_{n}\right]$. Введем

![](https://cdn.mathpix.com/cropped/2023_07_08_2ef858c5912b9740e3f5g-1.jpg?height=35&width=833&top_left_y=2161&top_left_x=122)
в е д е ни е $\langle x, y\rangle=i(J x, y)$, где $(x, y)=\sum_{j=0}^{2 k} x_{j} \bar{y}_{j}-$ обычное скалярное произведение. Матрица $U$ (вообще комплексная), у н и т а р н а я в смысле этого произведения, т. е. такая, что $U^{*} J U=J$, наз. $J$-у ни- т а р н о й; действительная $J$-унитарная матрица $X$ наз. с и м п л е к т и ч е с к о й.

Известно (см. Гамильтонова система), что при сдвиге вдоль траектории Г. с. сохраняется интегральный инвариант Пуанкаре - внешняя дифференциальная форма $\sum_{j=1}^{k} d p_{j} \wedge d q_{j}$. В случае Г. с. л. это свойство означает, что для любых решений $x^{(1)}=x^{(1)}(t), x^{(2)}=x^{(2)}(t)$ уравнения (2) выполнено $\left\langle x^{(1)}, \quad x^{(2)}\right\rangle=\left\langle X(t) x^{(1)}(0)\right.$, $\left.X(t) x^{(2)}(0)\right\rangle=\mathrm{const}$, т. е. что матрицант $X(t)-$ симплектическая матрица для любого $t$. Из соотношения

![](https://cdn.mathpix.com/cropped/2023_07_08_2ef858c5912b9740e3f5g-1.jpg?height=38&width=826&top_left_y=502&top_left_x=996)
а н к а р е), что собственные значения симплектической матрицы $X$ (с учетом их кратностей и порядков жордановых ящиков) располагаются симметрично (в смысле инверсии) относительно единичной окружности. Собственные значения симплектических (и $J$-унитарных) матриц, равные по модулю 1, подразделяются на собственные значения 1-го и 2-го рода по следующему правилу. Пусть $\rho-$ собственное значение $J$-унитарной матрицы $U$ и $|\rho|=1$. Тогда форма $\langle x, x\rangle$ на соответствующем корневом подпространстве не вырождается. Пусть $p$ - число положительных и $q-$ число отрицательных ее квадратов; говорят, что в точке $\rho$ совпало $p$ с о б-

![](https://cdn.mathpix.com/cropped/2023_07_08_2ef858c5912b9740e3f5g-1.jpg?height=35&width=826&top_left_y=893&top_left_x=996)
с об с т в е н ных 3 н а ч енй

Аналогично определяется род чисто мнимых собственных значений матриц $K=J-1 L, L *=L$ (для них $\langle K x, y\rangle=-\langle x, K y\rangle, \forall x, y)$. Для $J$-унитарной матрицы $X$ собственные значения $\rho$ при $|\rho| \neq 1$ считаются с о бст в енны ми 3 на ч ения ми 1-г о р од а, если $|\rho|<1$, и 2-г о р о д а, если $|\rho|>1$. Любая симплектическая матрица $X$ имеет (с учетом кратности) ровно $k$ собственных значений $\rho_{1}, \ldots, \rho_{k} 1$-го рода и $k$ значений $\rho_{1}^{-1}, \ldots, \rho_{k}^{-1} 2$-го рода. При соответствующей нумерации $\rho_{1}, \ldots, \rho_{k}$ являются непрерывными функциями матрицы $X$ (см. [2], [3]).

1. О сцилляторные с войст в а p е шен и й Г. с. Л. К изучению осцилляторных свойств решений уравнений (2)-(4) приводит ряд задач вариационного исчисления, оптимального управления, исследование свойств спектра соответствующего дифференциального оператора и др.

Определения. (I) Уравнение (3) наз. к о л е б ат е ль ь м м, если для любого $t_{0}>0$ найдутся числа $t_{2}>t_{1}>t_{0}$ и решение $y(t) \neq 0$ такие, что $y\left(t_{1}\right)=y\left(t_{2}\right)=0$, и не к о л е бате ль ны м-в противном случае. (II) Уравнение (4) наз. к о л е б а т е ль н ы м, если для любого $t_{0}>0$ найдется решение $\eta(t) \not \neq 0$, имеющее по крайней мере два $k$-кратных нуля $t_{2}>t_{1}>t_{0}$, и н е к оле б а т е ль н ы - в противном случае. (III) Уравнение (1) наз. к о л е б а т е л ьны м, еслй на $\left(t_{0}, \infty\right)$ функция

\[
\Delta \operatorname{Arg} X(t)=\sum_{j=1}^{k} \Delta \operatorname{Arg} \rho_{j}(t)
\]

является неограниченной, и н е к о л е б а т е льн ы м в противном случае. [В $(5) \rho_{j}(t)$ суть собственные значения 1-го рода матрицы $X(t)$. ] После сведе́ния уравнения (3) или (4) к уравнению (2) получающееся уравнение (2) будет колебательным в смысле определения (III) тогда и только тогда, когда уравнение (3) [соответственно (4)] колебательно в смысле определения (I) [соответственно (II)]. Определению (III) можно придать следующую геометрич. интерпретацию. Группа $\operatorname{Sp}(k, R)$ симплектических матриц $X$ гомеоморфна произведению связного и односвязного топологич. пространства на окружность. Соответствующее отображение можно выбрать так, что $\psi=\sum_{j=1}^{k} \operatorname{Arg} \rho_{j}$ является проекцией матрицы $X \in \operatorname{Sp}(k, R)$ на окружность (числа $\rho_{j}-$ собственные значения 1-го рода матрицы $X$ ). Таким образом, уравнение (2) колебательно, если при $t \rightarrow \infty$ матрица $X(t)$ неограниченно «закручивается" в