получим явную разностную схему 1-го порядка аппроксимации:

\[
\frac{w_{j}^{n+1}-w_{j}^{n}}{\tau}+\frac{f_{j+1}^{n}-f_{j-1}^{n}}{2 h}=\frac{h^{2}}{2 \tau} \frac{w_{j+1}^{n}-2 \boldsymbol{w}_{j}^{n}+w_{j-1}^{n}}{h^{2}} .
\]

Здесь

\[
\boldsymbol{w}=\left(\begin{array}{c}
u \\
v \\
E
\end{array}\right), \quad \boldsymbol{f}=\left(\begin{array}{c}
p \\
-u \\
u p
\end{array}\right),
\]

$\boldsymbol{f}_{j}^{n}=\boldsymbol{f}\left(\boldsymbol{w}_{j}^{n}\right)$. Указанная схема является условно аппроксимирующей при $\tau / h=$ const (при $\tau / h^{2}=$ const схема аппроксимирует систему уравнений $\left.\frac{\partial w}{\partial t}+\frac{\partial f}{\partial x}=\frac{h^{2}}{2 \tau} \frac{\partial^{2} w}{\partial x^{2}}\right)$, дивергентной и условно устойчивой. Условие устойчивости имеет вид: $c \tau / h \leqslant 1$, где $c-$ скорость звука.

Полагая в формуле (*)

\[
\sum_{j+1 / 2}^{*}=\frac{1}{2}\left(f_{j+1}^{n}+f_{j}^{n}\right)-\frac{\tau}{2 h} A_{j+1 / 2}^{2}\left(w_{j+1}^{n}-w_{j}^{n}\right),
\]

где

\[
A_{j+1 / 2}^{2}=A^{2}\left[\frac{1}{2}\left(w_{j+1}^{n}+w_{j}^{n}\right)\right], \quad A=\frac{d f}{d w},
\]

получим абсолютно аппроксимирующую явную разностную схему 2-го порядка аппроксимации:

\[
\begin{gathered}
\frac{\boldsymbol{w}_{j}^{n+1}-w_{j}^{n}}{\tau}+\frac{f_{j+1}^{n}-f_{j-1}^{n}}{2 h}= \\
=\frac{\tau}{2 h^{2}}\left[A_{j+1 / 2}^{2}\left(w_{j+1}^{n}-w_{j}^{n}\right)-A_{j-1 / 2}^{2}\left(w_{j}^{n}-w_{j-1}^{n}\right)\right] .
\end{gathered}
\]

Это схема - дивергентная и устойчивая при условии $\frac{c \tau}{h} \leqslant 1$

Разностная схема

\[
\begin{gathered}
\frac{u_{j}^{n+1}-u_{j}^{n}}{\tau}+\alpha \frac{p_{j+1 / 2}^{n+1}-p_{j-1 / 2}^{n+1}}{h}+(1-\alpha) \frac{p_{j+1 / 2}^{n}-p_{j-1 / 2}^{n}}{h}=0, \\
\frac{v_{j+1 / 2}^{n+1}-v_{j+1 / 2}^{n}}{\tau}+\alpha \frac{u_{j+1}^{n+1}-u_{j}^{n+1}}{h}+(1-\alpha) \frac{u_{j+1}^{n}-u_{j}^{n}}{h}=0, \\
\left.\frac{\varepsilon_{j+1 / 2}^{n+1}-\varepsilon_{j+1 / 2}^{n}}{\tau}+\mid \alpha p_{j+1 / 2}^{n+1}+(1-\alpha) p_{j+1 / 2}^{n}\right] \times \\
\quad \times\left[\alpha \frac{u_{j+1}^{n+1}-u_{j}^{n+1}}{h}+(1-\alpha) \frac{u_{j+1}^{n}-u_{j}^{n}}{h}\right]=0
\end{gathered}
\]

является явной при $\alpha=0$, неявной при $\alpha \neq 0,0 \leqslant \alpha \leqslant 1$; при $\alpha=1 / 2$ имеет 2 -й порядок аппроксимации, при $\alpha \neq$ $\neq 1 / 2-1-$ й порядок аппроксимации; при $\alpha=1 / 2$ схема полностью консервативная.

Разностная схема

\[
\begin{gathered}
\frac{u_{j}^{n+1 / 2}-u_{j}^{n-1 / 2}}{\tau}+\frac{p_{j+1 / 2}^{n}-p_{j-1 / 2}^{n}}{h}=0, \\
\frac{v_{j+1 / 2}^{n+1}-v_{j+1 / 2}^{n}}{\tau}-\frac{u_{j+1}^{n+1 / 2}-u_{j}^{n+1 / 2}}{h}=0, \\
\frac{\varepsilon_{j+1 / 2}^{n+1}-\varepsilon_{j+1 / 2}^{n}}{\tau}+\frac{p_{j+1 / 2}^{n+1}+\bar{p}_{j+1 / 2}^{n}}{2} \frac{v_{j+1 / 2}^{n+1}-v_{j+1 / 2}^{n}}{\tau}=0
\end{gathered}
\]

имеет 2-й порядок аппроксимации, неявная, абсолютно аппроксимирующая и недивергентная. Здесь

\[
\begin{gathered}
\boldsymbol{p}_{j+1 / 2}^{n}=p_{j+1 / 2}^{n}+\omega_{j+1 / 2}^{n}, \varepsilon_{j+1 / 2}^{n}=\varepsilon\left(p_{j+1 / 2}^{n}, v_{j+1 / 2}^{n}\right), \\
\omega_{j+1 / 2}^{n}=-\mu_{0} h^{2} \frac{1}{v_{j+1 / 2}^{n}} \frac{\left|u_{j+1}^{n-1 / 2}-u_{j}^{n-1 / 2}\right|}{h} \frac{u_{j+1}^{n-1 / 2}-u_{j}^{n-1 / 2}}{h}, \\
\mu_{0}=\text { const. }
\end{gathered}
\]

Успех разностных схем сквозного счета связан с тем обстоятельством, что, хотя аппроксимационная вяз- кость схемы определяет структуру разностного ударного перехода, отличную от физического ударного перехода, консервативная аппроксимация сохраняет скорость ударной волны и воспроизводит условия динамич. совместности.

Однако эти хорошие качества разностных схем сквозного счета теряют свое значение в случаях, когда важно точно передать структуру ударного перехода (задачи радиационной газовой динамики), структуру контактной полосы или пограничного слоя. В случае контактного разрыва хорошая аппроксимация в рамках разностной схемы сквозного счета становится невозможной не только из-за сильного расширения контактной полосы, но и в результате развития неустойчивости Гельмгольца и Тейлора. В этом случае с успехом применяется схема метода частиц в ячейке, к-рая позволяет передать сильные искажения траницы вследствие неустойчивости.

В задачах обтекания вязким газом при достаточно больших числах Рейнольдса эффект аппроксимационной вязкости превосходит әффект физич. вязкости, если разностная сетка недостаточно детальна. Для уменьшения эффекта аппроксимационной вязкости необходимо сильное измельчение сетки вблизи обтекаемого тела. Практически в этом случае отходят от единой трактовки течения, разбивая задачу интегрирования на две: задачу обтекания тела идеальным газом, в к-рой, в частности, определяется скорость $u_{l}$ потока на границе $l$ тела; задачу расчета вязкого течения вблизи тела, где градиенты величин вс зики (так наз. пограничный слой), с краевыми услов.іями на бесконечности, где задаются значения скорости $\boldsymbol{u}_{\infty}=\boldsymbol{u}_{l}$. Постановка задачи в рамках теории пограничного слоя является менее строгой, чем интегрирование уравнений Навье Стокса; однако она является наиболее употребительной в инженерных расчетах при больших числах Рейнольдса.

Особо важный класс задач газовой динамики составляют задачи гидродинамич. неустойчивости и турбулентности. В этом случае необходимо решать задачи на собственные значения для уравнений гидродинамики вязкой жидкости в вариациях (уравнения Орра Зоммерфельда) и строить сложные численные модели для описания нелинейной неустойчивости и турбулентности. Эти задачи принадлежат к классу наиболее трудных задач вычислительной математики и требуют разработки новых моделей и мощных ЭВМ.

Лит.: [1] Р и х т м а й е р Р. Д., М о р тон К., Разностные методы решения краевых задач, М., пер. с англ., 1972; [2] $\Gamma$ одунов С. К., Р я бен нкй В В. С., Разностные схемы, М., 1973; [3] Р ож дественский Б. Ј., Яненко Н. Н., Системы квазилинейных уравнений .., M., 1968; [4] C а м а pС К Й А. А., Введение в теорию разностных схем, М., 1971; [6] X a p л о у $\Phi$. ХХ., в сб.: Вычислительные методы в гидродинамике, М., 1967, 316-42; [7] Д о р о д н и й ны А. А., В кн.: Труды 3 всесоюзного матем. съезда, т. 3, М., 1958, 447-53; решения задач механики сплошной' среды, М., 1969, $101-213$; решения задач механики сплошной среды, М., $1969,101-213 ;$
$[9]$ н е н к о Н. Н., А н уч и н а Н. Н., П е т е н ко В. Е., [1] Я н е н к о Н. Н., А н у ч и н а Н. Н., П е т р е н к о В. к.,
II о и н Ю. И., в сб.: Численные методы механики сплошной среды, Новосибирск, 1970 , т. 1, 40-62; [10] Я н е н к о Н. Н., Метод дробных шагов решения многомерных задач математической физики, Новосибирск, 1967; [11] С а м а р с к и й А. А., [12] $\Gamma$ о д ун о в С. К., 3 а б р о д и н А. В., П р о к о по в

![](https://cdn.mathpix.com/cropped/2023_07_08_42438eb38651fc5a1d2cg-1.jpg?height=44&width=829&top_left_y=2032&top_left_x=992)

ГАЗОВЫХ СТРУЙ ТЕОРИЯ - раздел газовой динамики, в к-ром исследуются течения газа в предположении, что газ частично обтекает встречаемое на пути своего распространения препятствие и стекает с него, образуя за препятствием застойную область. Решение задач о струйном течении газа достигается в предположении, что газ баротропный и движение его плоскопараллельное, потенциальное и установившееся. В этих