решении задач газовой динамики см. ст. Газовой динамики численные методы.

Пuт.: [1] С е р р и н Дж., Математические основы классической механики жидкости, пер. с англ., М., 1963; [2] С ед о в ЈI. И., Механика сплошной среды, т. $1-2$, М., 1970; [3] сред, 2 изд., М., 1954; [4] К о ч и н Н. Е., К и б е л ь И.А., P о з е Н. В., Теоретическая гидромеханика, ч. 1-2, М., 1963; [5] Б р а н о в е p Г. Г., II и н о б е p А. М., Магнитная гидродинамика несжимаемых сред, М., $1970 ;[6]$ Р о ж д е с т в е нс к и й Б. Л., Я н е н ко н. Н., Системы квазилинейных
уравнений и их приложения к газовой динамике, М., 1968.

![](https://cdn.mathpix.com/cropped/2023_07_08_466fd05ea2dac05c0537g-1.jpg?height=64&width=809&top_left_y=464&top_left_x=139)
ГАЗОВОЙ ДИНАМТ Задач газовой динамики на основе вычислительных алгоритмов. Рассмотрим основные аспекты теории численных методов решения задач газовой динамики, записав газовой динамики уравнения в виде законов сохранения в инерциальной ортонормированной системе координат:

Здесь

\[
\frac{\partial w^{i}}{\partial t}+\frac{\partial \sum^{i \alpha}}{\partial x^{\alpha}}=F^{i} .
\]

\[
\begin{aligned}
& \boldsymbol{w}=\left(\begin{array}{l}
w^{0} \\
w^{1} \\
w^{2} \\
w^{3} \\
w^{\mathbf{4}}
\end{array}\right)=\left(\begin{array}{l}
\rho \\
\rho u^{1} \\
\rho u^{2} \\
\rho u^{\mathbf{3}} \\
\rho E
\end{array}\right), \quad \boldsymbol{F}=\left(\begin{array}{l}
0 \\
F^{1} \\
F^{2} \\
F^{3} \\
F^{\alpha} u^{\alpha}
\end{array}\right) \\
& \sum^{i \alpha}=\sum^{1} i \alpha+\sum^{2}+\sum^{3} i \alpha \\
& \sum^{1} i \alpha=\left(\begin{array}{lll}
\rho u^{1} & \rho u^{2} & \rho u^{3} \\
\rho u^{1} u^{1} & \rho u^{1} u^{2} & \rho u^{1} u^{3} \\
\rho u^{2} u^{1} & \rho u^{2} u^{2} & \rho u^{2} u^{3} \\
\rho u^{3} u^{1} & \rho u^{3} u^{2} & \rho u^{3} u^{3} \\
\rho E u^{1} & \rho E u^{2} & \rho E u^{3}
\end{array}\right) \\
& \sum^{2} i \alpha=\left(\begin{array}{ccc}
0 & 0 & 0 \\
p & 0 & 0 \\
0 & p & 0 \\
0 & 0 & p \\
p u^{\mathbf{1}} & p u^{2} & p u^{3}
\end{array}\right) \\
& =\left(\begin{array}{ccc}
\sum^{3} i \alpha= & 0 \\
0 & 0 & -\sigma^{13} \\
-\sigma^{11} & -\sigma^{12} & -\sigma^{23} \\
-\sigma^{21} & -\sigma^{22} & -\sigma^{33} \\
-\sigma^{31} & -x \frac{\partial T}{\partial x^{2}}-\sigma_{\alpha}^{2} u^{\alpha} & -\varkappa \frac{\partial T}{\partial x^{3}}-\sigma_{\alpha}^{3} u^{\alpha}
\end{array}\right) \\
& \sigma^{\beta k}=\frac{1}{2} \lambda d \underset{\gamma}{\psi} \delta^{\beta k}+\mu d^{\beta k} \\
& d^{\beta k}=d_{k}^{\beta}=\frac{1}{2}\left(\frac{\partial u^{\beta}}{\partial x^{k}}+\frac{\partial u^{k}}{\partial x^{\beta}}\right), \\
& i=0,1, \ldots, m+1 ; \alpha, \beta, \gamma, k=1,2, \ldots, m,
\end{aligned}
\]

$m=1$ - одномерный случай, $m=2$ - двумерный случай, $m=3$ - трехмерный случай, $\rho$ - плотность газа, $p$ - давление газа, $\boldsymbol{u}=\left\{u^{1}, u^{2}, u^{3}\right\}-$ скорость газа, $T$ - температура газа, $E=\varepsilon+\frac{1}{2} \boldsymbol{u}^{2}-$ полная энергия массы газа, $\varepsilon-$ удельная внутренняя энергия, $\lambda$ коэффициент вязкости сжатия, $\mu-$ коәффициент вязкости сдвига, $x-$ коәффициент теплопроводности, $\delta^{\beta k}$ - символ Кронекера.

Следует различать два основных класса задач газовой динамики: задача Коши для ограниченной или бесконечной области (нестационарные задачи газовой динамики);

стационарные краевые задачи газовой динамики для конечной пли бесконечной области.

В свою очередь эти задачи могут подразделяться на ряд классов в зависимости от физич. свойств течения газа. По этому принципу можно различать:

течения идеального газа $(\lambda=\mu=x=0)$;

течения вязкого несжимаемого газа $(\lambda \neq 0, \quad \mu \neq 0$, $x=0, \omega=0, \omega-$ коэффициент сжимаемости, $\omega=1 / c^{2}$, $c$ - скорость звука), описываемые уравнениями Навье Стокса;

течения вязкого сжимаемого теплопроводящего газа $(\lambda \neq 0, \mu \neq 0, x \neq 0, \omega \neq 0)$.

Численные методы решения задач газовой динамики развивались исторически почти независимо по указанным классам задач. Ныне создано большое количество разностных схем различного порядка аппроксимации. Наметились общие принципы построения численных методов, приемлемые для всех задач газовой динамики в целом, хотя и не доказанные математически строго. Эти принципы заключаются в следующем.

1) Представления обобщенного решения уравнений идеального газа как предела соответствующих решений с физическими $\left(\sum^{3} i \alpha \neq 0\right)$ или искусственными диссипативными членами при стремлении последних к нулю. Искусственные диссипативные члены могут вводиться непосредственно в уравнения газовой динамики или же неявно определяться самой структурой разностной схемы (аппроксимационная вязкость).

2) Расщепления (декомпозиции) интегральных законов сохранения и самих дифференциальных уравнений геометрически, аналитически и по физич. процессам (метод слабой аппроксимации, см. Дробных шагов метод).

3) Представления стационарного решения как предела решений нестационарных задач (метод установления). При этом в качестве вспомогательных нестационарных задач используются уравнения как гиперболического, так и параболического типов.

4) Аппроксимация уравнений не типа Коши - Ковалевской уравнениями типа Коши - Ковалевской при стремлении соответствующего малого параметра к нулю (уравнения Навье - Стокса, уравнения фильтрации).

5) Построение подвижных разностных сеток как регулярного, так и нерегулярного типов.

6) Разделение в разностной схеме задач аппроксимации во внутренних регулярных и граничных точках.

7) Представление сложной системы линейных или нелинейных алгебраич. уравнений в виде рекуррентных соотношений (метод приближенной или точной факторизации).

8) Метод продолжения краевой задачи за границу и включения ее в краевую задачу с простой областью (метод фиктивных областей).

Совокупность этих представлений п методов позволяет в конечном итоге свести алгоритм решения сложных задач газовой динамики к алгоритмам решений простых задач стандартной структуры (модульный анализ алгоритмов). Такой подход пока строго не обоснован, однако практически он себя оправдал и находит все большее распространение.

Численные методы задач газовой динамики можно разделить на два больших класса: методы с явным выделением особенностей (ударные волны, контактные границы, центрированные волны разрежения) и так наз. методы сквозного счета, в к-рых особенности явно не выделяются.

Методы 1-го класса основаны на представлении обобщенного решения уравнений газовой динамики как совокупности классич. решений, определенных в некоторых областях, покрывающих фазовое пространство