- каноническое произведение Вейерштрасса рода $q \leqslant \rho$, построенное по нулям $\alpha_{k}$ функции $f(z)$. Иначе говоря, А. т. утверждает, что род целой функции не превосходит ее порядка. Эта теорема использовалась Ж. Адамаром при доказательстве асимптотич. закона распределения простых чисел.

Лum.: [1] H a d a m a r d J., "J. math. pures et appl.", ser. 4, 1893, t. 9, p. 171-215; [2] М а р к у ше в и ч А. И.,

![](https://cdn.mathpix.com/cropped/2023_07_08_e8747aa10af514c5d725g-1.jpg?height=39&width=831&top_left_y=427&top_left_x=120)
М., 1956.

3) А. т. о б о п р ед е лит е ля х: пусть $D-$ определитель матрицы с элементами $a_{\mu v}, \mu, v=1, \ldots, n$. Тогда имеет место неравенство

\[
D^{2} \leqslant \sum a_{1 x}^{2} \sum a_{2 x}^{2} \ldots \sum a_{n v}^{2}
\]

Равенство имеет место в том и только в том случае, когда

\[
a_{\mu 1} a_{v 1}+a_{\mu 2} a_{v_{2}}+\ldots+a_{\mu n} a_{v n}=0
\]

для каждой пары различных $\mu, \nu$, или когда хотя бы один множитель в правой части (*) равен нулю. Геометрич. смысл этой теоремы заключается в том, что объем параллелепипеда в $n$-мерном пространстве не превышает произведения длин его ребер, исходящих из одной вершины, и что равенство имеет место, когда эти ребра взаимно перпендикулярны или когда длина одного из ребер равна нулю.

Ж. Адамар в [1] рассматривал эту задачу для определителя с комплексными элементами.

Jum.: [1] H a d a m a r d J., "Bull. sci. math.", 1893, ser. 2, t. 17 , pt. 1, p. $240-6$. 4) А. т. о т р е х к р у г а х: если $f(z)$ - голоморфная функция комплексного переменного $z=r e^{i \varphi}$ в кольце $0<r_{1}<r<r_{2}<\infty$, непрерывная в замкнутом кольце $r_{1} \leqslant r \leqslant r_{2}$, и $M(r)=\max |f(z)|$ при $|z|=r$, то справедливо неравенство

\[
\begin{gathered}
\log M(r) \leqslant \frac{\log \frac{r_{2}}{r}}{\log \frac{r_{2}}{r_{1}}} \log M\left(r_{1}\right)+\frac{\log \frac{r}{r_{1}}}{\log \frac{r_{2}}{r_{1}}} \log M\left(r_{2}\right), \\
r_{1} \leqslant r \leqslant r_{2} .
\end{gathered}
\]

Это неравенство означает, что $\log M(r)$ есть выпуклая бункция от $\log r$. А. т. является частным случаем двух констант теоремы.

А. т. допускает обобщения в различных направлениях, в частности обобщение для других метрик, для гармонич. и субгармонич. функций.

Jum.: [1] H a d a m a r d J., "Bull. Soc. math. Françe», 1896, ser. 2, v. 24, p. $199-220 ;[2]$ M а p к у ш е в и ч А. И.,
Теория аналитических функций, 2 изд., т. 2 , М., 1968, гл. 6 ; [3] Теория аналитических функций, 2 изд., т. 2 , М., 1968, гл. 6; [3]

![](https://cdn.mathpix.com/cropped/2023_07_08_e8747aa10af514c5d725g-1.jpg?height=45&width=831&top_left_y=1672&top_left_x=119)
АрмССР», 1966, т. 42, № 5, с. 274-78. Е. Д. Соломенцев.

5) А. т. мультипли кационная, А. т. об умно же нй о с об енн о стей: если степенные ряды

\[
f(z)=\sum_{n=0}^{\infty} a_{n} z^{n}, \quad g(z)=\sum_{n=0}^{\infty} b_{n} z^{n}
\]

имеют, соответственно, радиусы сходимости $r_{1}>0$ и $r_{2}>$ $>0$, если $S_{1}$ и $S_{2}-$ звезды Миттаг-Леффлера (см. Звезда әлемента функции), соответственно, для $f(z)$ и $g(z)$, и если $\alpha$ - множество особых точек функции $f(z)$ на границе звезды $S_{1}$, а $\beta$ - множество особых точек функции $g(z)$ на границе звезды $S_{2}$, то степенной ряд

\[
P(z)=\sum_{n=0}^{\infty} a_{n} b_{n} z^{n}
\]

имеет радиус сходимости $r \geqslant r_{1} r_{2}$, а его звезда МиттагЛеффлера $S$ содержит звезду-произведение $C\left(C S_{1} \times\right.$ $\times C S_{2}$ ), где $C A$ обозначает дополнение множества $A$ и $A \times B$ - множество всех произведений $p q$ чисел $p \in A$, $q \in B$; кроме того, из угловых и хорошо достижимых точек границы звезды-произведения особыми точками функции $P(z)$ могут быть лишь точкі произведения множеств $\alpha \times \beta$. Первоначальные формулировки теоремы (см. [1], [2]) были несколько отлічны от пріведенной выше, они потребовали уточнений (см. [2]).

Степенной ряд (2) наз. а д а м а р о в с к и м п р оп з в дением, или а д а ма ров ской комп о з и ц и е й, степенных рядов (1). Свойства адамаровского произведения, выявленные этой А. т. и в последующих исследованиях (см. [3]), позволяют использовать его в вопросах аналитич. продолжения степенных рядов, когда по коэффициентам ряда вида (2) оказывается возможным сделать нек-рые заключения об особенностях представляемой им аналітич. функціи.

Если $K$ - произвольное компактное множество, расположенное внутри звезды-произведения $C\left(C S_{1} \times C S_{2}\right)$, то найдется такой замкнутый спрямляемый контур $L$, расположенный внутри $C\left(C S_{1} \times C S_{2}\right)$ и охватывающий $K$, что для всех $z \in K$ справедливо і н т е r p а л ь н о е представление ад а ма ровск ого прои 3 в е д е ния:

\[
P(z)=\frac{1}{2 \pi i} \int_{L} f(t) g\left(\frac{z}{t}\right) \frac{d t}{t} .
\]

Представление (3) также применяется в вопросах аналитич. продолжения.

Jum.: [1] H a d a m a r d J., "Acta math.», 1899, Bd 22 S. 55-63; [2] е г o ж е, "Scientia Phys.-math.", 1901, № 12; M., 1967.

АДАМСА МЕТОД - конечно разностный метод решения задачи Коши для систем дифференциальных уравнений 1-го порядка

\[
y^{\prime}=f(x, y), \quad y\left(x_{0}\right)=y_{0} .
\]

При интегрировании по сетке с постоянным шагом $x_{n}=x_{0}+n h$ расчетные формулы імеют вид: а) экстраполяционные

\[
y_{n+1}=y_{n}+h \sum_{\lambda=0}^{k} u_{-\lambda} f\left(x_{n-\lambda}, y_{n-\lambda}\right),
\]

б) интерполяционные

\[
y_{n+1}=y_{n}+h \sum_{\lambda=-1}^{k-1} v_{-\lambda} f\left(x_{n-\lambda}, y_{n-\lambda}\right)
\]

При одном и том же $k$ формула б) точнее, но требует решения нелинейной системы уравнений для нахождения значения $y_{n+1}$.

На практике находят приближение из а), а затем приводят одно-два уточнения по формуле

$y_{n+1}^{(i+1)}=y_{n}+h \sum_{\lambda=0}^{k-1} v_{-\lambda} f\left(x_{n-\lambda}, y_{n-\lambda}\right)+h v_{1} f\left(x_{n+1}, y_{n+1}^{(i)}\right)$ уточнения сходятся при условии $h\left|v_{1}\right|\|(\partial f / \partial y)\|<1$. Начальные условия $y_{1}, \ldots, y_{k}$ для А. м., необходимые для начала вычислений по формулам а), определяются каким-либо специальным образом. Погрешность решения записывается в виде

\[
\chi_{k+1}\left(\int_{x_{0}}^{x_{n}} \Omega(x, t) y^{(k+2)}(t) d t\right) h^{k+1}+O\left(h^{k+2}\right),
\]

где $\Omega(x, t)$ - решение системы

\[
\frac{d \Omega(x, t)}{d x}=f_{y}(x, y(x)) \Omega(x, t) \quad \text { при } \quad \Omega(t, t)=E .
\]

Структура члена $O\left(h^{k+2}\right)$ такова, что обычно при малых $h$ он равномерно мал по сравнению с главным членом на больших промежутках интегрирования. Это обстоятельство обеспечивает возможность применения А. м. на больших промежутках интегрирования в случае абсолютно устойчивого решения дифференциальной задачи; в частности, в отличие от Милна метода, его можно применять для отыскания устойчивых периодич. решений дифференциальных уравнений. Стандартная программа А. м. интегрирования с автоматич. выбором шага существенно сложнее стандартной программы Рун-