при этом выполняются условия (2), то справедливо о б о б щ е н н о е Г. н. для функционала:

\[
\varphi\left(\left|a_{1}, \ldots, a_{m}\right|\right) \leqslant \prod_{k=1}^{m}\left[\varphi\left(\left|a_{k}\right|^{p_{k}}\right)\right]^{1 / p_{k}} .
\]

Jum.: [1] H ö l d e r O., "Nachr. Ges. Wiss. Göttingen», 1889,

![](https://cdn.mathpix.com/cropped/2023_07_08_27f29eed9f7568cf3fd9g-1.jpg?height=37&width=814&top_left_y=351&top_left_x=134)
к е н б а х Ӭ., Нереллм а н Р., Неравенства, пер. с англ., M., 1965 .

ГЁЛЬДЕРА УСЈІОВИЕ - неравенство, в к-ром приращение функции оценивается через приращение ее аргумента. Функция $f(x)$, определенная в области $E n$-мерного евклидова пространства, удовлетворяет в точке $y \in E \Gamma$. у. с показателем $\alpha$ (порядка $\alpha$ ), где $0<\alpha \leqslant 1$, и коэффициентом $A(y)$, если

\[
|f(x)-f(y)| \leqslant A(y)|x-y|^{\alpha}
\]

для всех $x \in E$, достаточно близких к $y$. Это Г. у. наз. иногда и зот р о п ны м $\Gamma$. у. Говорят, что $f(x)$ удовлетворяет на множестве $E^{\prime} \subset E$ (изотропному) Г. у. с показателем $\alpha$, если Г. у. (1) выполнено для всех $y \in E^{\prime}$. В случае, когда

\[
A=\sup _{y \in E} A(y)<\infty,
\]

$\Gamma$. у. наз. р а вном е рны м н а $E$, а $A-$ коэ фф и ц и ен т о м $\Gamma$ ё ль д е р а функции $f(x)$ на $E$. Г. у. наз. также н е п р е р ы в н о с т ь ю п о Г ёл ьд е р у. Величина

$|f|_{\alpha}=|f, E|_{\alpha}=\sup _{x, y \in E} \frac{|f(x)-f(y)|}{|x-y|^{\alpha}}, 0 \leqslant \alpha \leqslant 1$,

наз. $\alpha-\Pi$ о л ун о р м о й $\Gamma$ ё ль д е р а ограниченной функции на множестве $E$. Полунорма Гёльдера, как функция от $f$, логарифмически выпукла:

\[
|f| \alpha t+\beta(1-t) \leqslant|f|_{\alpha}^{t}|f|_{\beta}^{1-t} \text {. }
\]

Н е и з о т р о п но е $\Gamma$. у. вводится аналогично Г. у. (1) и имеет вид:

\[
|f(x)-f(y)| \leqslant A \sum_{i=1}^{n}\left|\sum_{j=1}^{n} a_{j}^{i}\left(x^{j}-y^{j}\right)\right|^{\alpha_{i}},
\]

где $0<\alpha_{i} \leqslant 1$, a $\operatorname{det}\left(a_{i}^{j}\right) \neq 0$. Функции, удовлетворяющие неизотропному $\Gamma$. у., непрерывны и имеют по направлению ковектора $a^{i}=\left(a_{1}^{i}, a_{2}^{i}, \ldots, a_{n}^{i}\right)$ показатель Гёльдера $\alpha_{i}, 1 \leqslant i \leqslant n$.

Для числовых функций одного действітельного переменного условие вида (1) было введено Р. Липшицем (R. I.ipschitz, 1864) в связи с исследованиями по тригонометрич. рядам. В этом случае Г. у. часто наз. у словие м Липшица поря д ка $а$ п с ко нс т а н т о й Ли Пши ц а $A$. Для числовых функций $n(\geqslant 2)$ действительных переменных $\Gamma$. у. было введено О. Гёльдером (O. Нölder) при исследовании дифференциальных свойств ньютонова потенциала.

$\Gamma$. у. естественным образом переносится на случай отображений метрич. пространств. Говорят, что отображение $f: X \rightarrow E$ метрич. пространства $X$ в метрич. пространство $E$ удовлетворяет в точке $x_{0} \in X \Gamma$. у. с показателем $\alpha$ и коэффициентом $A\left(x_{0}\right)$, если существует такая окрестность $U\left(x_{0}\right) \subset X$ точки $x_{0}$, что для любого $x \in U\left(x_{0}\right)$ выполняется неравенство

\[
\rho_{E}\left(f(x), f\left(x_{0}\right)\right) \leqslant A\left(x_{0}\right) \rho_{X}^{\alpha}\left(x, x_{0}\right) .
\]

Здесь $\rho_{X}$ I $\rho_{E}$-метрики пространств $X$ и $E$. Аналогично вводится $\Gamma$. у. на множестве $X^{\prime} \subset X$, равномерное на $X$ Г. у. и $\alpha-$ полунормы Гёльдера.

Векторные пространства функций, удовлетворяющих тому или иному $\Gamma$. у., образуют Гёльдерово nространство. Л. П. Купчов.

ГЁЈБДЕРОВО ПРОСТРАНСТВО - банахово nространство ограниченных и непрерывных функций $f(x)=f\left(x^{1}, x^{2}, \ldots, x^{n}\right)$, определенных на множестве $E$ n-мерного евклидова пространства іІ удовлетворяющих на $E$ Гёльдера условию.

Г. п. $C_{m}(E), m \geqslant 0$ - целое, состоит из $m$ раз непрерывно дифференцируемых на $E$ функций (непрерывных при $m=0)$.

Г. п. $C_{m+\alpha}(E), 0<\alpha \leqslant 1, m \geqslant 0-$ целое, состоит из функций, $m$ раз непрерывно дифференцируемых (непрерывных при $m=0$ ), все $m-e$ производные к-рых удовлетворяют условию Гёльдера с показателем $\alpha$.

Норма в $C_{m}(E)$ и $C_{m+\alpha}(E)$ вводітся следующим образом:

\[
|f|_{\boldsymbol{m}}=\|f, E\|_{\boldsymbol{m}}=\sum_{\left.\right|_{k \mid=0} ^{m}} \sup _{x \in E}\left|f^{(k)}(x)\right|,
\]

$|f|_{m+\alpha}=\|f, E\|_{m+\alpha}=|f|_{m}+\sum_{k \mid=m}\left\|f^{(k)}, E\right\|_{\alpha}$, где $k=\left(k_{1}, k_{2}, \ldots, k_{n}\right), k_{j} \geqslant 0$ - целые,

\[
|k|=k_{1} \dagger \ldots+k_{n}, f^{(k)}(x)=\frac{\partial^{|k|} f(x)}{\partial x^{1^{k}} \ldots \partial x^{n^{k}}} .
\]

Основные свойства Г. П. для ограниченной связной области $(\bar{E}-$ замыкание $E)$ :

1) $C_{m+\beta}(\bar{E})$ вложено в $C_{k+\alpha}(\bar{E})$, если $0 \leqslant k+\alpha \leqslant$ $\leqslant m+\beta, k, m$ - целые, $0<\alpha \leqslant 1,0 \leqslant \beta \leqslant 1$. При этом

![](https://cdn.mathpix.com/cropped/2023_07_08_27f29eed9f7568cf3fd9g-1.jpg?height=47&width=831&top_left_y=944&top_left_x=989)

2) Единичный шар пространства $C_{m+\beta}(\bar{E})$ компактен в $C_{m+\alpha}(\bar{E})$, если $0<\alpha<\beta$. Следовательно, любое ограниченное множество функций из $C_{m+\beta}(\bar{E})$ содержит последовательность функций, сходящихся в метрике $C_{m+\alpha} \overline{(E)}$ к функции пространства $C_{m+\alpha}(\bar{E})$.

Лum.: [1] М и р а н д а К.,, Уравнения с частными производными эллиптического типа, пер. с итал., М., 1957.

ГЕЛЬМГОЛЬІА УРАВНЕНИЕ - УравНение стными производными вида

\[
\sum_{k=1}^{n} \frac{\partial^{2} u}{\partial x_{k}^{2}}+c u=0
\]

где $c$ - постоянное число. К Г. у. приводит изучение установившихся колебательных процессов. При $c=$ $=0$ Г. у. переходит в Л апласа уравнение. В случае, если в правой части Г. У. стоит функция $f(x)$, это уравнение наз. неоднородным $\Gamma$. $\mathrm{y}$.

Для Г. у., являющегося уравнением эллиптич. типа, в ограниченной области ставятся обычные краевые задачи (Дирихле, Неймана и др.). Те значенія $c$, для к-рых существует не равное тождественно нулю решение однородного Г. у., удовлетворяющее соответствующему однородному краевому условию, наз. собственным значением оператора Лапласа (соответствующей краевой задачи). В частности, для задачи Дирихле все собственные значения положительны, а для задачи Неймана - неотрицательны. Для значений $c$, совпадающих с собственными значениями, решение краевой задачи для Г. у. заведомо неединственно. Если же значения $c$ отличны от собственных, то теорема единственности справедлива.

При решении краевых задач для Г. у. применяются обычные методы теории эллиптич. уравнений (сведение к интегральному уравнению, вариационный метод, метод конечных разностей).

В случае неограниченной области с компактной границей для Г. у. ставятся внешние краевые задачи, к-рые при $c<0$ имеют единственное решение, стремящееся к нулю на бесконечности. При $c>0$ стремящееся к нулю на бесконечности решение $\Gamma$. у., вообще говоря, не является единственным. В этом случае для выделения единственного решения ставят дополнительные условия (см. Внешняя ивнутренняя краевые задачи, Предельного поглощения принцип).