частицы газа, находящейся в момент времени $t$ в точке $x^{1}, x^{2}, x^{3}$. Способ Лагранжа предполагает задание скорости $\boldsymbol{u}$ и термодинамич. величин для каждой частицы как функций времени $t$. Зафиксировав частицу газа с помощью параметров $q^{1}, q^{2}, q^{3}$, получают параметры течения газа как функции от времени $t$ и $q^{1}, q^{2}, q^{3}$ (лагранжевы координаты). Связь между эйлеровыми и лагранжевыми координатами имеет вид:

\[
x^{i}=q^{i}+\int_{0}^{t} u^{i}\left(q^{1}, q^{2}, q^{3}, \tau\right) d \tau, i=1,2,3,
\]

где $x^{i}=x^{i}\left(q^{1}, q^{2}, q^{3}, t\right)$ - эйлеровы координаты частицы, находившейся в момент времени $t=0$ в точке $x^{i}=q^{i}$. В случае одной пространственной переменной при условии, что газодинамич. переменные являются непрерывно дифференцируемыми функциями, уравнения вязкого теплопроводного газа имеют вид:

в эйлеровых координатах

\[
\begin{gathered}
\frac{\partial \rho}{\partial t}+\frac{\partial(\rho u)}{\partial x}=0 \\
\frac{\partial(\rho u)}{\partial t}+\frac{\partial}{\partial x}\left(p+\rho u^{2}-\mu \frac{\partial u}{\partial x}\right)=0, \\
\frac{\partial \rho E}{\partial t}+\frac{\partial}{\partial x}\left[\rho u\left(E+\frac{p}{\rho}\right)-\mu u \frac{\partial u}{\partial x}\right]=\frac{\partial}{\partial x}\left(x \frac{\partial T}{\partial x}\right) ;
\end{gathered}
\]

в лагранжевых координатах

\[
\begin{gathered}
\frac{\partial v}{\partial t}-\frac{\partial u}{\partial q}=0 \\
\frac{\partial u}{\partial t}+\frac{\partial}{\partial q}\left(p-\mu \rho \frac{\partial u}{\partial q}\right)=0, \\
\frac{\partial E}{\partial t}+\frac{\partial}{\partial q}\left[u\left(p-\mu \rho \frac{\partial u}{\partial q}\right)\right]=\rho \frac{\partial}{\partial q}\left(x \frac{\partial T}{\partial q}\right),
\end{gathered}
\]

где $v=\frac{1}{\rho}, \frac{\partial x(q, t)}{\partial t}=u(q, t)$.

Для произвольной подвижной системы координат во многих случаях целесообразно одновременно преобразовывать компоненты скорости по тензорному закону. Если

\[
x^{i}=x^{i}\left(y^{1}, y^{2}, y^{3}, t\right)
\]

есть преобразование пространственных координат, при к-ром временная координата не изменяется, то отображение (5) можно связать с самим течением газа и тогда оно будет определять поле локальных систем координат, зависящих от самого течения. Возможны и более общие преобразования, включающие изменение временной координаты.

Большую роль в теории Г. д. У. и в приложениях играет анализ малых параметров $\lambda, \mu, x, \omega\left(\omega=1 / c^{2}-\right.$ коэффициент сжимаемости), входящих в уравнения (3), Если $\lambda=\mu=x=0$, то (3) - уравнения идеальной газовой динамики; если $\lambda=$ const, $\mu=$ const, $x=\omega=0$, то (3) уравнения Навье - Стокса несжимаемой жидкости. Эти уравнения не принадлежат к типу Коши - Ковалевской. В случае $\lambda=$ const, $\mu=$ const, $x=0, \omega=$ const получается система уравнений типа Коши - Ковалевской параболич. типа, не являющаяся сильно параболической. В теории турбулентности и неньютоновых жидкостей коэффициенты $\lambda, \mu$ могут зависеть от градиентов газодинамич. величин.

Определяющие соотношения (2) и, в частности, уравнения состояния (4) характеризуют тип системы Г. Д. у. (3) и ряд ее качественных особенностей. Так, в случае идеального сжимаемого газа $(\lambda=\mu=x=0)$ система уравнений (3) является гиперболической, если

\[
\left(\frac{\partial p}{\partial \rho}\right)_{S} \geqslant 0
\]

где энтропия $S$ определяется соотношением (второй закон термодинамики)

\[
T d S=p d \frac{1}{\rho}+d \varepsilon
\]

Условие (6) является локальным, зависит от решения и в нек-рых случаях может нарушаться. Так, в случае уравнения состояния Ван-дер-Ваальса условие (6) может нарушаться, уравнения становятся эллиптическими, решение - неустойчивым.

Законы сохранения (1) позволяіот сформулировать обобщенное решение Г. Д. У., к-рое уже не обязательно является непрерывным и не удовлетворяет дифференциальным Г. д. У. (3). Полная теория обобщенных решений $\Gamma$. д. у. не создана, однако хорошо изучены простейшие обобщенные решения, как, напр., ударная волна, центрированная волна разрежения, контактное течение и т. Д. Существует гипотеза, согласно к-рой обобщенное решение уравнений идеального сжимаемого газа есть предел соответствующего решения вязкого газа при $\lambda \rightarrow 0$ и $\mu \rightarrow 0$. Это утверждение строго доказано для одномерных ударных волн и в нек-рых частных случаях для уравнений типа

\[
\frac{\partial u}{\partial t}+u \frac{\partial u}{\partial x}=\mu \frac{\partial^{2} u}{\partial x^{2}} .
\]

Особый интерес представляют собой стационарные Г. д. у., к-рые в основном связаны с задачами стационарного обтекания тел в бесконечном пространстве или стационарных течений в каналах. В этом случае решение системы уравнений (3) не зависит от $t$, и система принимает вид:

\[
\frac{\partial \sum^{i \alpha}}{\partial x^{\alpha}}=F i \text {. }
\]

Для стационарной системы уравнений (7) ставится нек-рая краевая задача, к-рая может быть весьма сложной, а само уравнение (7) может быть как эллиптического, так и смешанного типов. Напр., для задачи обтекания идеального сжимаемого газа в предположении потенциальности течения получается следующее уравнение в двумерном случае:

\[
\begin{gathered}
{\left[\left(\frac{\partial \varphi}{\partial x^{1}}\right)^{2}-c^{2}\right] \frac{\partial^{2} \varphi}{\left(\partial x^{1}\right)^{2}}+2 \frac{\partial \varphi}{\partial x^{1}} \frac{\partial \varphi}{\partial x^{2}} \frac{\partial^{2} \varphi}{\partial x^{1} \partial x^{2}}+} \\
+\left[\left(\frac{\partial \varphi}{\partial x^{2}}\right)^{2}-c^{2}\right] \frac{\partial^{2} \varphi}{\left(\partial x^{2}\right)^{2}}=0,
\end{gathered}
\]

где $u^{1}=\partial \varphi / \partial x^{1}, u^{2}=\partial \varphi / \partial x^{2}, \varphi-$ потенциал скорости, квадрат скорости звука $c^{2}$ может быть определен из интеграла Бернулли:

\[
\frac{1}{2}\left[\left(u^{1}\right)^{2}+\left(u^{2}\right)^{2}\right]+\int c^{2}(\rho) d \ln \rho=\text { const. }
\]

Для уравнения (8) может быть поставлена задача обтекания данного контура $l$ :

\[
u^{1}(\infty)=U_{0}^{1}, \quad u^{2}(\infty)=U_{0}^{2}, \quad u_{n}=\frac{\partial \varphi}{\partial n}=0,
\]

где $u_{n}$ - нормальная составляющая вектора скорости по нормали к контуру $l$. В случае $\left(u^{1}\right)^{2}+\left(u^{2}\right)^{2}-c^{2}>0$ уравнение (8) имеет гиперболич. тіп, в случае $\left(u^{1}\right)^{2}+$ $+\left(u^{2}\right)^{2}-c^{2}<0-$ эллиптич. тип. Возможен переход от эллиптич. типа к гиперболическому (трансзвуковой поток). Можно показать, что краевая задача в случае трансзвукового обтекания является некорректной, так как сколь угодно малое изменение контура может сделать краевую задачу неразрешимой в классе непрерывных функций.

Большой интерес представляют задачII газодинамич. неустойчивости и турбулентности, к-рые описываются, как правило, в рамках теориі несамосопряженных уравнений (уравнение Орра - Зоммерфельда, уравнение Рейнольдса). В связи с практич. пріложениями приобрели болышое значение Г. д. у., описывающие движение более сложных сред (многофазные среды, неньютоновы жидкости, магнитная гидродинамика). Большинство уравнений математич. физики представляют собой результат линеаризации Г. Д. У. О численном