оператора к изучению аналогичных свойств соответствующего интегрального оператора.

Функция Грина для обыкновенных дифференциальных уравнений.

Пусть $L$ - дифференциальный оператор, порожденный дифференциальным полиномом

\[
l[y]=\sum_{k=0}^{n} p_{k}(x) \frac{d^{k} y}{d x^{k}}, \quad a<x<b,
\]

и краевыми условиями $U_{j}[y]=0, j=1,2, \ldots, n$, где

\[
U_{j}[y]=\sum_{k=0}^{n} \alpha_{j k} y^{(k)}(a)+\beta_{j k} y^{(k)}(b)
\]

Г. ф. оператора $L$ наз. функция $G(x, \xi)$, удовлетворяющая условиям:

1) $G(x, \xi)$ непрерывна и имеет непрерывные производные по $x$ до $(n-2)$-го порядка включительно для всех значений $x$ и $\xi$ из сегмента $[a, b]$;

2) при любом фиксированном $\xi$ из интервала $(a, b)$ функция $G(x, \xi)$ имеет равномерно непрерывные производные $n$-го порядка по $x$ в каждом из полусегментов $[a, \xi)$ и $(\xi, b]$, причем производная $(n-1)$-го порядка при $x=\xi$ удовлетворяет условию

\[
\frac{\partial^{n-1}}{\partial x^{n-1}} G(\xi+0, \xi)-\frac{\partial^{n-1}}{\partial x^{n-1}} G(\xi-0, \xi)=\frac{1}{p_{n}(\xi)} ;
\]

3) в каждом из полусегментов $[a, \xi)$ и $(\xi, b]$ функция $G(x, \xi)$, рассматриваемая как функция от $x$, удовлетворяет уравнению $l_{x}[G]=0$ и краевым условиям $U_{j x}[G]=$ $=0, j=1,2, \ldots, n$.

Если краевая задача $L y=0$ имеет лишь тривиальные решения, то оператор $L$ имеет п притом только одну Г. ф. (см. [1]). При этом для любой функции $f(x)$, непрерывной на сегменте $[a, b]$, существует решение краевой задачи $L y=f$, и это решение задается формулой

\[
y(x)=\int_{a}^{b} G(x, \xi) f(\xi) d \xi .
\]

Если оператор $L$ имеет $\Gamma$. ф. $G(x, \xi)$, то сопряженный ошератор $L^{*}$ также имеет $\Gamma$. ф., к-рая равна $\overline{G(\xi, x)}$. Если, в частности, оператор $L$ самосопряженный $\left(L=L^{*}\right)$, то $G(x, \xi)=\overline{G(\xi, x)}$, то есть $\Gamma$. ф. в этом случае является эрмитовым ядром. Напр., Г. Ф. самосопряженного оператора $L$ 2-го порядка, порожденного дифференциальной операцией с действительными коәффйциентами

\[
l[y]=\frac{d}{d x}\left(p \frac{d y}{d x}\right)+q(x) y, \quad a<x<b
\]

п краевыми условиями $y(a)=0, y(b)=0$, имеет вид:

\[
G(x, \xi)=\left\{\begin{array}{lll}
C y_{1}(x) y_{2}(\xi), & \text { если } & x \leqslant \xi, \\
C y_{1}(\xi) y_{2}(x), & \text { если } x>\xi .
\end{array}\right.
\]

Здесь $y_{1}(x)$ и $y_{2}(x)$ - произвольные решения уравнения $l[y]=0$, удовлетворяющие соответственно условиям $y_{1}(a)=0, \quad y_{2}(b)=0 ; C=[p(\xi) W(\xi)]^{-1}, \quad$ где $W-$ определитель Вронского (вронскиан) решений $y_{1}$ и $y_{2}$, причем можно показать, что $C$ не зависит от $\xi$.

Если оператор $L$ имеет $\Gamma$. ф., то краевая задача на собственные значения $L y=\lambda y$ әквивалентна интегральному уравнению $y(x)=\lambda \int_{a}^{b} G(x, \xi) y(\xi) d \xi$, к которому применима теория Фредгольма. Поэтому краевая задача $L y=\lambda y$ может иметь не более счетного числа собственных значений $\lambda_{1}, \lambda_{2}, \ldots$, у которых отсутствуют конечные предельные точки. Сопряженная задача имеет комплексно сопряженные собственные значения той же кратности. Для каждого $\lambda$, не являющегося собственным значением оператора $L$, можно построить $\Gamma$. ф. $G(x, \xi, \lambda)$ оператора $L-\lambda I$, где $I$ - тождественный оператор. Функция $G_{1}(x, \xi, \lambda)$ является мероморфной функцией параметра $\lambda$; ее полюсами могут быть лишь собственные значения оператора $L$. Если крат- ность собственного значения $\lambda_{0}$ равна единице, то

\[
G(x, \xi, \lambda)=\frac{u_{0}(x) \overline{v_{0}(\xi)}}{\lambda-\lambda_{0}}+G_{1}(x, \xi, \lambda)
\]

где $G(x, \xi, \lambda)$ регулярна в окрестности точки $\lambda_{0}$, а $u_{0}(x)$ и $v_{0}(x)$ - собственные функции операторов $L$ и $L^{*}$, отвечающие собственным значениям $\lambda_{0}$ и $\overline{\lambda_{0}}$ и нормированные так, что

\[
\int_{a}^{b} u_{0}(x) \overline{v_{0}(x)} d x=1
\]

Если $G(x, \xi, \lambda)$ имеет бесконечно много полюсов и при том только 1-го порядка, то существует полная биортогональная система

\[
u_{1}(x), u_{2}(x), \ldots ; v_{1}(x), v_{2}(x), \ldots
\]

собственных функций операторов $L$ и $L *$. Если занумеровать собственные значения в порядке возрастания их абсолютных величин, то интеграл

\[
I_{R}(x, f)=\frac{1}{2 \pi i} \int_{|\lambda|-R} d \lambda \int_{a}^{b} G(x, \xi, \lambda) f(\xi) d \xi
\]

равен частичной сумме

\[
S_{k}(x, f)=\sum\left|\lambda_{n}\right|<R_{n} u_{n}(x) \int_{a}^{b} f(\xi) \overline{v_{n}(\xi)} d \xi
\]

разложения функции $f$ по собственным функциям оператора $L$. Положительное число $R$ выбирается так, чтобы на окружности $|\lambda|=R$ функция $G(x, \xi, \lambda)$ была регулярной по $\lambda$. Для регулярной краевой задачи и для любой кусочно гладкой функции $f(x)$ в интервале $a<x<b$ выполняется равенство

\[
\lim _{R \rightarrow \infty} I_{R}(x, f)=\frac{1}{2}[f(x+0)+f(x-0)],
\]

т. е. имеет место разложимость в сходящийся ряд (cM. [1]).

Если $\Gamma$. Ф. $G(x, \xi, \lambda)$ оператора $L-\lambda I$ имеет кратные полюсы, то ее главная часть выражается через канонич. системы собственных и присоединенных функций операторов $L$ и $L^{*}$ (см. [2]).

Выше рассматривался случай, когда краевая задача $L y=0$ не имела нетривиальных решений. Если же эта краевая задача имеет нетривиальные решения, то вводят так наз. о б о б щ е н н у ю $\Gamma$ рин а фу ункц и ю. Пусть, напр., имеется ровно $m$ линейно независимых решений задачи $L y=0$. Тогда существует обобщенная $\Gamma . ф . \tilde{G}(x, \xi)$, к-рая обладает свойствами 1) и 2) обычной $\Gamma$. ф., при $a<\xi<b$ удовлетворяет как функция $x$ краевым условиям и, кроме того, является решением уравнения

\[
l_{x}[y]=-\sum_{k=1}^{m} \varphi_{k}(x) \overline{v_{k}(\xi)}
\]

здесь $\left\{v_{k}(x)\right\}_{k=1}^{m}-$ система линейно независимых решений сопряженной задачи $L^{*} y=0$, а $\left\{\varphi_{k}(x)\right\}_{k=1}^{m}-$ произвольная биортогональная ей система непрерывных функций. Тогда

\[
y(x)=\int_{a}^{b} \tilde{G}(x, \xi) f(\xi) d \xi
\]

есть решение краевой задачи $L y=f$, если функция $f(x)$ непрерывна и удовлетворяет условию разрешимости, т. е. ортогональна всем $v_{k}(x)$.

Если $\tilde{G}_{0}(x, \xi)$ - одна из обобщенных Г. Ф. оператора $L$, то любая другая обобщенная $\Gamma$. ф. может быть представлена в виде

\[
\tilde{G}(x, \xi)=\tilde{G}_{0}(x, \xi)+\sum_{k=1}^{m} u_{k}(x) \psi_{k}(\xi),
\]

где $\left\{u_{k}(x)\right\}-$ полная система линейно независимых решений задачи $L y=0$, а $\psi_{k}(\xi)$ - произвольные непрерывные функции (см. [3]).