бормы, а $L, M$ И $N$ - второй квадратичной формы поверхности, вычисленные в данной точке.

Полусумма Г. к. $k_{1}$ и $k_{2}$ поверхности равна средней кривизне, а произведение - гауссовой кривизне поверхности. Уравнение (*) может быть запцсано в виде

\[
k^{2}-2 H k+K=0,
\]

где $H-$ средняя, $K-$ полная кривизны поверхности в данной точке.

Г. к. $k_{1}$ и $k_{2}$ связаны с нормальной кривизной $\tilde{k}$ в произвольно выбранном направлении ф о р м у ло й Э й л е р а:

\[
\tilde{k}=k_{1} \cos ^{2} \varphi+k_{2} \sin ^{2} \varphi
\]

где $\varphi$ - угол, образуемый выбранным направлением с главным направлением для кривизны $k_{1}$. E. В. Шикин.

ГЛАВНАЯ НОРМАЈІЬ - нормаль к кривой, проходящая через точку $M_{0}$ кривой $L$ и лежащая в соприкасающейся плоскости к $L$ в точке $M_{0}$. Если $\boldsymbol{r}=\boldsymbol{r}(t)-$ параметрич. уравнение кривой и значение параметра $t_{0}$ соответствует точке $M_{0}$, то уравнение $\Gamma$. н. в векторной форме имеет вид:

\[
\boldsymbol{r}=\boldsymbol{r}\left(t_{0}\right)+\lambda \boldsymbol{r}^{\prime \prime}\left(t_{0}\right)
\]
ГЈАВНАЯ ТРАНСЛЯЦИЯ - отображение $\varphi$ aлгебраической системы $\boldsymbol{A}=\langle A, \Omega\rangle$ в себя, имеющее вид $\varphi: x \rightarrow F\left(a_{1}, \ldots, a_{k-1}, x, a_{k+1}, \ldots, a_{n}\right)$,

где $F$ - символ основной операции из $\Omega$ и $a_{1}, \ldots, a_{n}-$ фиксированные элементы множества $A$. Д. М. Смирнов.

ГЈАВНАЯ ЧАСТЬ ДИФФЕРЕНЦИАЛЬНОГО ОПЕPАТОРА - однородный дифференциальный оператор, образуемый из данного отбрасыванием всех членов, не содержащих производных максимального порядка. Для дифференциального оператора

\[
L=\sum_{|\alpha| \leqslant m} a_{\alpha} D^{\alpha},
\]

главная часть есть $\sum_{|\alpha|=m} a_{\alpha} D^{\alpha}$. Иногда $\Gamma$. ч. д. 0. определяется с введением дополнительных весов, приписываемых дифференцированиям по различным аргументам. Например, в дифференциальном операторе $D_{1}-D_{2}^{2}+a D_{2}$ главная часть определяется иногда как $D_{1}-D_{2}^{2}$. A. А. Дезин.

ГЛАВНОГО ТИІА ОПЕРАТОР С ЧАСТНЫМИ ІРОИЗВОДНЫМИ И П о с т о я н ны м и к о әфф иц и е н т а м и - оператор $A(D)$, главная часть к-рого $P(D)$ (см. Главная часть дифференциального оператора) удовлетворяет условию:

\[
\sum_{j=1}^{n}\left|\frac{\partial P(x)}{\partial x_{j}}\right|^{2} \neq 0
\]

для любого вектора $\boldsymbol{x}=\left(x_{1}, \ldots, x_{n}\right) \in \mathbb{R}^{n}$. Другая формулировка условия: всякая действительная характеристическая относительно $P(D)$ плоскость должна быть простой характеристикой. Условие (*) является необходимым и достаточным для доминирования $A(D)$ по отношению к произвольному оператору менышего порядка. Операторы с совпадающей главной частью $P(D)$ имеют одинаковую силу тогда и только тогда, когда выполнено условие (*). В случае переменных коэфффициентов условие принадлежности $A(D)$ к главному типу формулируется обычно с помощью специальных неравенств, оценивающих производные функций с компактным носителем через значения оператора. Поточечное выполнение условия $(*)$ и дополнительное условие на порядок комлутатора $[P(x, D) \bar{P}(x, D)]$ достаточны для принадлежности $A(D)$ к главному типу.

ГЈАВНОЕ АНАЛИТИЧЕСКОЕ РАССЈОЕНИЕ Ае локально тривиальное аналитич. расслоение, на слоях к-рого просто транзитивно и аналитически действует структурная группа Ли; то есть Г. а. р. есть четверка $(P, B, G, \pi)$, где $P, B$ - аналитические пространства над полем $k, \pi: P \rightarrow B$ аналитич. отображение, $G-$ группа Ли над $k$, аналитически действующая справа на $P$, причем для каждого элемента базы $B$ существуют окрестность $U$ и аналитич. изоморфизм

\[
\varphi: U \times G \rightarrow \pi^{-1}(U)
\]

такой, что

\[
\varphi(x, g h)=\varphi(x, g) h, \quad x \in U, g, h \in G .
\]

Каждое векторное аналитическое расслоение $p$ : $V \rightarrow B$ с $n$-мерным слоем определяет $\Gamma$. а. р. с базой $B$ и группой $G L(n, k)$, слоем к-рого над точкой $b \in B$ является многообразие всех базисов слоя $p^{-1}(b)$. Это частный случай взаимно однозначного соответствия между аналитич. расслоениями с заданным слоем и структурной группой $G$ и ассоциированными с ними Г. a.p. Другие примеры $\Gamma$. а. р.: расслоение $H \rightarrow H / G$, слоями к-рого служат левые смежные классы группы Ли $H$ по ее подгруппе Ли $G$; аналитіч. накрытие (здесь структурная группа - групла накрытия).

Г. a. p. можно задать при помощи открытого покрытия $\left\{U_{i}\right\}_{i} \in I$ его базы $B$ и ф ункци й п е р е х о а, т. е. аналитич. отображений

$g_{i j}: U_{i} \cap U_{j} \rightarrow G, \quad i, j \in I, \quad U_{i} \cap U_{j} \neq \varnothing$,

удовлетворяющих условиям

\[
g_{i j}(x) g_{j k}(x)=g_{i k}(x), \quad x \in U_{i} \cap U_{j} \cap U_{k} .
\]

Функции перехода образуют одномерный коцикл со значениями в пучке $\sigma^{G}$ ростков аналитич. отображений $B \rightarrow G$, что дает взаимно однозначное соответствие между множеством $\Gamma$. а. р. с базой $B$ и группой $G$ и множеством когомологий $H^{1}\left(B, G^{G}\right)$. Классификация $\Gamma$. а. р. с базой $B$ и структурной группой $G$ представляет собой (для неабелевой группы $G$ ) проблему, решенную лишь в нек-рых специальных случаях (по поводу соответствующей проблемы локальных модулей см. Дебормация аналитической структуры). Связь между этой классификацией и классификацией топологических главных расслоений выражается естественным отображением

\[
\alpha: H^{1}\left(B, \sigma^{G}\right) \rightarrow H^{1}\left(B, C^{G}\right),
\]

где $C^{G}-$ пучок ростков непрерывных отображений $\stackrel{B \rightarrow}{\rightarrow}$

Пусть $k=\mathbb{C}$, а $B$ - приведенное IIIтейна пространство, тогда отображение $\alpha$ биективно, и проблема классификации сводится к задаче гомотопич. топодогии [4]. В частности, всякое Г. а. р., базой к-рого является некомпактная риманова поверхность, а структурная группа связна, тривиально. Результат работы [4] получен на самом деле для более широкого класса $E$-главных расслоений, в определении к-рых группа $G$ заменяется некоторым аналитическим локально тривиальным расслоением $E \rightarrow B$ на комплексные группы Ли, послойно действующим на $P$. Существует обобщение приведенного результата на случай, когда структурная группа есть банахова комплексная группа Ли [2]. Если же $B$ - компактная риманова поверхность, то $\alpha$ сюръективно, но не инъективно. В общем случае $\alpha$ не обязано быть ни инъективным, ни сюръективным. Для связной разрешимой группы $G$ известны когомологич. достаточные условия инъективности или биективности отображения $\alpha[3]$.

Изучен также случай, когда $B$ - компактная риманова поверхность рода $p$, a $G$ - связная редуктивная алгебраич. группа. Для $p=0$ соответствующая классификация дана в [5], для $p=1$ прІ $G=G L(n, \mathbb{C})-$ в [1]. В случае $p \geqslant 2, G=\operatorname{GL}(n, \mathbb{C})$ (см. Векторное алгебрачческое расслоение) существенную роль играет понятие стабильного векторного расслоения. Это понятие