нормальной подгруппы из $G$ делится на порядок элемента из аддитивной группы кольца $K$. Если $K$ - кольцо без нильидеалов и порядок любого элемента из $G$ не делится на порядок ни одного әлемента из аддитивной группы $K$, то $K G$ без нильидеалов. $Г$. а. $K G$ над полем характеристики 0 полупроста в смысле Джекобсона радикала, если $K$ содержит трансцендентный элемент над полем рациональных чисел.

В лож е н и Г Г. а. в т е л а. Г. а. упорядоченной группы вложима в тело (т е о р е м а Н е й м а н а). Существует предположение, что это же верно для Г. а. всякой правоупорядоченной группы.

Свя з т те оре тико-кольцевых с войств гр у п п вого кольц а $K G$ со ст р о ение м г р уп пы $G$ и ко ль ц а $K$. Напр., $K G$ первично тогда и только тогда, когда кольцо $K$ первично и групиа $G$ не имеет конечных нормальных подгрупп.

П р о блем а и зом о р фи зма: если групповые кольца $K G$ и $K H$ изоморфны как $K$-алгебры, то какая связь существует между строением групп $G$ и $H$, в частности, когда $G$ и $H$ изоморфны? Выяснилось, что однозначно определяет группу групповое кольцо периодической разрешимой группы класса 2 над кольцом целых чисел и групповое кольцо счетной абелевой $p$-группы над кольцом характеристики $p$.

Рассматривались различные обобщения понятия Г. а., напр. понятие скрещенного произведения группы и кольца, для к-рого остаются справедливыми многие свойства $\Gamma$. а.

Jum.: [1] S c h u r I., "Sitzber. Preuss. Akad. Wiss.», 1905, S. 406-32; [2] К әрти с Ч., Р а йне представлений конечных групп и ассоциативных алгеор, пер.
с англ., M., 1969; [31 P a s m a n D. S., Infinite group rings, N. Y.,'197i; [4] Современные проб.темы математики, т. 2, М., 1973, с. 5-118; [ 5 ] Б о в д и А. А., Групповые кольца, Ужгород, 1974 ; см. также лит. при статье Представления групп.

A. А. Бовди.

ГРУППОВАЯ АЛГЕБРА л о к а л ь н о б и к о мп а к т но й г р у п п - топологическая алгебра с инволючией, образованная функциями на группе и такая, что в ней умножение определяется как свертка. Пусть банахово пространство $L^{\mathrm{1}}(G)$ построено с помощью левоинвариантной $X$ аapa меры $d g$ на локально бикомпактной топологич. группе $G$ и пусть в $L^{1}(G)$ умножение определяется как свертка $\left(f_{1}, f_{2}\right) \rightarrow f_{1} * f_{2}$, а инволюция $f \rightarrow f^{*}-$ по формуле $f^{*}(g)=\overline{f\left(g^{-1}\right)} \Delta(g)$, где $\Delta-$ модуль группы $G$. Полученная банахова алгебра с инволюцией наз. $г$ р у $\Pi$ п о в о й а лг е б р о й группы $G$ и обозначается также через $L^{1}(G)$. Если $G$ - конечная группа, то определение Г. а. совпадает с обычным алгебраич. определением Г. а. над полем комплексных чисел.

Понятие Г. а. позволяет применять общие методы теории банаховых алгебр в задачах теории групп и, в частности, в абстрактном гармонич. анализе. Свойства Г. а. как банаховой алгебры отражают свойства топологич. группы: так, Г. а. содержит единичный әлемент тогда и только тогда, когда группа дискретна; Г. а. является прямой суммой (топологической) своих конечномерных минимальных двусторонних идеалов тогда и только тогда, когда группа бикомпактна. Исключительно важную роль играет понятие Г. а. в теории унитарных представлений группы: между непрерывными унитарными представлениями топологич. группы $G$ и невырожденными симметричныли представлениями $\Gamma$. а. $L^{1}(G)$ существует взаимно однозначное соответствие, сопоставляющее непрерывному унитарному представлению $\pi$ группы $G$ в гильбертовом пространстве $H$ представление Г. а. $L^{1}(G)$, огределяемое формулой

\[
f \longrightarrow \int_{G} f(g) \pi(g) d g, \quad f \in L^{1}(G)
\]

Г. а. локально бикомпактных групп обладают рядом общих свойств. Именно, любая Г. а. содержит аппроксимативную единицу (см. Банахова алгебра), образован- ную семейством характеристич. функций окрестностей единичного элемента, упорядоченных по включению (в сторону убывания); поэтому для Г. а. можно установить соответствие между положительными функционалами на $Г$. а. и ее симметричными представлениями. Любая Г. а. является полупростой алгеброй и имеет симметричное точное представление. В частности, представление Г. а., определяемое регулярныл представлением группы, является точным. Замкнутые левые идеалы $L^{1}(G)$ суть замкнутые векторные подпространства $L^{1}(G)$, инвариантные относительно левого сдвига.

Иногда г р у п п о в о й а л г е б р о й наз. банахова алгебра с инволюцией, полученная из $\Gamma$. а. $L^{1}(G)$ присоединением единицы. Существует ряд других алгебр с инволюцией, к-рые иногда наз. г р уп п о в ы м и а лг е б р а м и. К их числу относятся, в частности: алгебра мер $M(G)$ относительно свертки; алгебры относітельно обычного умножения, напр. алгебра $L^{\infty}(G)$ существенно ограниченных измеримых по мере Хаара функций, алгебра $P(G)$ комплексных линейных комбинаций непрерывных положительно определенных функций. Множество $P^{1}(G)=P(G) \cap L^{1}(G)$ и совокупность $K(G)$ непрерывных финитных функций образуют алгебру и относительно свертки, и относительно обычного умножения. Имеет место следующая таблица, в к-рой стрелки означают включения:

![](https://cdn.mathpix.com/cropped/2023_07_08_f30c5422f987be886942g-1.jpg?height=208&width=397&top_left_y=958&top_left_x=1208)

Лит.: [1] H а й м а р к M. А., Нормированные кольца, 2 изд., М., 1968; [2] G u i c h a r d e t A., Analyse harmonique commutative, P., 1968 . А. И. Штери.

ГРУППОВАЯ СКОРОСТЬ - величина, характеризующая скорость распространения волнового процесса в диспергирующих средах. Пусть волновой процесс описывается волновым уравнением с переменным коэффициентом

\[
\frac{1}{c^{2}(z)} u_{t t}-u_{x x}-u_{z z}=0
\]

$0 \leqslant z<\infty,-\infty<x<\infty, c(z)>0$.

Ищутся решения, удовлетворяющие условиям

\[
\left.u\right|_{z=0}=0, \quad u_{z \rightarrow \infty} \longrightarrow 0
\]

и имеющие вид

\[
u=e^{i \omega(k) t-i k x} v(z) .
\]

Функция $v(z)$ должна быть ненулевым решением одномерной краевой задачи

\[
v^{\prime \prime}+\left(k^{2}-\frac{\omega^{2}}{c^{2}(z)}\right) v=0 ;\left.\quad v\right|_{z=0}=0 ; \quad v_{z \rightarrow \infty} \longrightarrow 0 .
\]

Если в нек-ром промежутке изменения $k$ существует конечный набор $\omega_{j}(k), k=1,2, \ldots$, при к-рых эта задача имеет ненулевое решение $v_{j}$, то величины $V=\omega_{j}(k) / k$ и $U=d \omega_{j} / d k$ наз. соответственно фа 3 о в о й и $\Gamma$ р у ПП о в о й с к о р о с т я м и волны

\[
u_{j}=e^{i(\nu(k)-i k x} v_{j}(z) \text {. }
\]

Фазовая скорость и Г. с. связаны следующим соотношением (фо р м у л а Р ә ле я):

\[
U=V-\lambda d V / d \lambda
\]

где $\lambda$ - длина волны.

Лит.: [1] М а н д е л г ші т а м Л. И., Полное собрание трудов, т. 5 , Л.,

![](https://cdn.mathpix.com/cropped/2023_07_08_f30c5422f987be886942g-1.jpg?height=40&width=794&top_left_y=2163&top_left_x=1015)
щение понятия алгебраич. групшы. Пусть (Sch/S) - категория схем над базисной схемой $S$; групповой объект этой категории наз. г р у П П о в о й с $\mathbf{x}$ е м о й н а д с х е м о й $S$ (а также г р у п п о в ой $S$-с хе мо й,