Объединение всех элементов $x$ :

\[
\bigcup x \leftrightharpoons\{z \mid \exists v(z \varepsilon v \wedge v \varepsilon x)\}
\]

Декартово произведение $x$ и $y$ :

$x \times y \leftrightharpoons\{z \mid \exists u v(z=\langle u, v\rangle \wedge u \varepsilon x \wedge v \varepsilon y)\}$.

$w$ есть функция:

$\operatorname{Fnc}(w) \leftrightarrows \exists v(w \sqsubseteq v \times v) \wedge$

$\forall u v_{1} v_{2}\left(\left\langle u, v_{1}\right\rangle \varepsilon w \wedge\left\langle u, v_{2}\right\rangle \varepsilon w \longrightarrow v_{1}=v_{2}\right)$.

Значение функции $w$ на элементе $x$ :

\[
w^{6} x \stackrel{\circlearrowright}{\longrightarrow} y\langle x, y\rangle \varepsilon .
\]

$z$ есть стандартное бесконечное множество:

\[
\operatorname{Inf}(z) \longleftrightarrow \varnothing \varepsilon z \wedge \forall u(u \varepsilon z \longrightarrow u \cup\{u\} \in z)
\]

Следующая аксиоматич. теория А наиболее полно отражает принципы «наивной» теории множеств. Аксиомы А:

A1. аксиом а об ьемности:

\[
\forall x(x \varepsilon y \leftrightarrow x \varepsilon z) \longrightarrow y=z
\]

(«если множества $y$ и $z$ содержат одни и те же элементы, то они равны»);

A2. а к с и о ы с в р тывания:

\[
\exists y \forall x(x \varepsilon y \leftrightarrow A),
\]

где $A$ - произвольная формула, не содержащая в качестве параметра $y$ («существует множество $y$, содержащее те и только те әлементы $x$, для к-рых $A »)$.

Описанная система противоречива. Если в А2 в качестве $A$ взять формулу $7 x \varepsilon x$, то из формулы $\forall x(x \varepsilon y \leftrightarrow$ $\leftrightarrow 7 x \varepsilon x)$ легко выводится $y \varepsilon y \leftrightarrow 7 y \varepsilon y$, что противоречиво.

Аксиоматич. системы теории множеств можно разделить на следующие четыре группы.

a) Построение аксиоматич. систем первой группы направлено на такое ограничение аксиом свертывания, к-рое обеспечивает наиболее естественный способ формализации обычных математич. доказательств и в то же время позволяет избежать известных парадоксов. Первой аксиоматикой такого рода была система Z Цермело (E. Zermelo, 1908). Однако в системе Z невозможно естественным образом формализовать нек-рые разделы математики, и А. Френкель (А. Fraenkel, 1922) предложил пополнить $\mathrm{Z}$ новым принципом, названным им а к с и о м о й п о д с т а н о вки. Полученная система наз. с и с т е м о й Це р м е л о- Френ ке ля и обозначается $\mathrm{ZF}$.

б) Вторую группу составляют системы, аксиомы к-рых выбраны в связи с к.-л. объяснением парадоксов, напр. как следствий непредикативных определений. Сюда относятся: разветвленная теория типов Рассела, простая теория типов T, теории типов с трансфинитными индексами (см. Типов теория).

в) Третья группа характеризуется использованием нестандартных средств логич. вывода, многозначных логик, дополнительных условий на доказательства, бесконечных правил вывода. Системы, относящиеся к этому направлению, наименее развиты.

г) Четвертая группа включает модификации систем первых трех групп, преследующие определенные логич. или математич. цели. Укажем только на системы NBG Неймана - Гёделя - Бернайса (J. Neumann - K. Gödel-P. Bernays, 1925) и NF Куайна (W. Quine, 1937). Построение системы NBG вызвано желанием иметь конечное число аксиом для теории множеств, основанной на системе $\mathrm{ZF}$. B NF реализуется стремление преололеть расслоение понятий, имеющее место в теории типов.

Системы Z, ZF, NF можно формулировать в описанном выше языке. Правила вывода, а также так наз. л о г и- ч е с к и е а к с и о м ы у этих систем совпадают і образуют прикладное исчисление предикатов 1-й ступени с равенством и оператором дескрипции. Укажем только аксиомы для равенства и оператора дескрипции:

\[
x=x, x=y \longrightarrow(A(x) \longrightarrow A(y)),
\]

где $A(x)$ - формула, не содержащая связанной переменной $y$ (т. е. не имеющая вхождений вида $\forall y, \exists y$, เy), и $A(y)$ получается из формулы $A(x)$ заменой нек-рых свободных вхождений переменной $x$ на $y$;

\[
\exists ! x A(x) \longrightarrow A(\llcorner x A(x))
\]

где квантор $\exists$ ! $x$ означает «существует одно и только одно $x$ », а формула $A(\llcorner x A(x))$ получается из формулы $A(x)$ заменой всех свободных вхождений переменной $x$ на терм $1 x A(x)$. Квантор $\exists ! x$ выразим через кванторы $\forall$ и $ヨ$ и равенство.

Нелогически е ак с и омыс исте мы Z:

$\mathrm{Z} 1$. аксиома объемности A1;

Z2. а к с и о м а п а р ы:

$\exists u \forall z(z \varepsilon u \leftrightarrow z=x \vee z=y)$

(«существует множество $\{x, y\}$ );

Z3. а к с и о ма с у м мы:

$\exists y \forall x(x \varepsilon y \leftrightarrow \exists t(t \varepsilon z \wedge x \varepsilon t))$

(«существует множество Uz»);

Z4. а к с и о ма с т е п е н ї:

$\exists y \forall x(x \varepsilon y \leftrightarrow x \subseteq z)$

(«существует множество $P_{z »)}$;

Z5. а к с и о м в ы д е ле ния:

$\exists y \forall x(x \varepsilon y \leftrightarrow x \varepsilon z \wedge A(x))$

(«существует подмножество $z$, состоящее из тех әлементов $x$, для к-рых имеет место $A(x) ») ;$ аксиомы $\mathrm{Z} 2-\mathrm{Z} 5$ являются примерами аксиом свертывания;

Z6. а к с и о м а бес коне чно с ти:

\[
\exists z \operatorname{Inf}(z) \text {; }
\]

Z7. а к си ома вы б о р а:

$\left.\forall z \exists w\left(\operatorname{Fnc}(w) \wedge \forall x(x \varepsilon z \wedge\rceil x=\varnothing \longrightarrow w^{\prime} x \varepsilon x\right)\right)$

(«для всякого множества $z$ существует функция $w$, выбирающая из каждого непустого элемента $x$ множества $z$ единственный элемент $\left.w^{\prime} x »\right)$. $\mathrm{K}$ этим аксиомам добавляют еще ак с и ому фу унд и р о в ани я:

$\mathrm{Z} 8$.

\[
\forall x(T x=\varnothing \longrightarrow \exists y(y \varepsilon x \wedge y \cap x=\varnothing)),
\]

цель к-рой - постулировать, что не существует убывающих цепей $x_{2} \varepsilon x_{1}, x_{3} \varepsilon x_{2}, x_{4} \varepsilon x_{3}, \ldots$ Аксиома Z8 позволяет упростить построения в Z. Добавление әтой аксиомы не вносит противоречия.

В системе $\mathrm{Z}$ можно развивать арифметику, анализ, функциональный анализ, рассматривать кардинальные числа, меньшие $\boldsymbol{N}_{\omega}$. Однако если определить алефы стандартным образом, то доказать в Z существование $\boldsymbol{\$}_{\omega}$ и более высоких кардиналов уже невозможно.

Система $\mathrm{ZF}$ получается из $\mathrm{Z}$ добавлением аксиом подстановки Френкеля, к-рым можно придать вид аксиом свертывания:

ZF9.

\[
\exists y \forall x(x \varepsilon y \leftrightarrow \exists v(v \varepsilon z \wedge x=\imath t A(t, v)))
\]

(«существует множество $y$, состоящее из $x, x=\imath t A(t, v)$, когда $v$ пробегает все элементы множества z»). Иначе говоря, $y$ получается из $z$, если каждый элемент $v$ из $z$ заменить на $\boldsymbol{t} \boldsymbol{A}(t, v)$.

Система ZF является очень сильной теорией. Все обычные математич. теоремы формализуются в $\mathrm{ZF}$.

Система NBG получается из системы ZF добавлением нового типа переменных - классовых переменных $X$,