бое открытое подмножество $U \subset X$ является Г. м.; поэтому использование равенств

\[
\begin{aligned}
H_{p}(U ; G) & =H_{p}(X, X \backslash U ; G), \\
H_{c}^{q}(U ; G) & =H^{q}(X, X \backslash U ; G),
\end{aligned}
\]

из к-рых во втором $U$ имеет компактное замыкание, а индекс $c$ указывает на компактность носителей, позволяет получать как частные случаи двойственности Пуанкаре изоморфизмы

\[
\begin{gathered}
H_{p}(X, X \backslash U ; G)=H^{n-p}\left(U, \mathscr{H}_{n}\right), \\
H_{p}^{c}(U ; G)=H^{n-p}\left(X, X \backslash U ; \mathscr{H}_{n}\right) .
\end{gathered}
\]

Сопоставление точных гомологич. и когомологич. последовательностей соответствующих пар позволяет в качестве частных случаев двойственности Пуанкаре рассматривать также изоморфизмы

\[
H_{p}(X \backslash U ; G)=H^{n-p}\left(X, U ; \mathscr{H}_{n}\right)
\]

и

\[
H_{p}(X, U ; G)=H^{n-p}\left(X \backslash U ; \mathscr{H}_{n}\right),
\]

последний из к-рых является обобщением Александера двойственности. Аналогичные соотношения имеют место для гомологий и когомологий с носителями в нек-ром фиксированном семействе.

Пусть

\[
H_{p}(X ; G)=H_{p+1}(X ; G)=0
\]

и пусть $X$ компактно, а $Y$ - замкнутое или открытое подмножество. Следствием предыдущих изоморфизмов и точности гомологий и когомологий является изоморфизм

\[
H_{p}^{c}(X \backslash Y ; G)=H^{n-p-1}\left(Y ; \mathscr{H}_{n}\right),
\]

представляющий собой Понтрягина двойственность

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=37&width=833&top_left_y=1207&top_left_x=122)
том $Y$. Отсюда и из свойства непрерывности когомологий вытекает, что изоморфизм

\[
H_{p}^{c}(X \backslash Y ; G)=H^{n-p-1}\left(Y ; \mathscr{H}_{n}\right)
\]

имеет место для любого подмножества $Y \subset X$ (д в о йс т в е н но с т ь С и т н и к о в а). В случае некомпактного $X$ вместо гомологий с компактными носителями следует рассматривать гомологии с носителями, замкнутыми во всем $X$. Если $X$ компактно, то при $p=0$ следует использовать приведенные гомологии.

Нетривиальными примерами Г. м. являются «сомножители» обычных многообразий, напр. евклидовых пространств: если для топологич. пространства $X$ существует такое $Y$, что декартово произведение $X \times Y$ есть $\Gamma$. м., то $X$ и $Y$ - тоже $\Gamma$. м. Известны примеры $\Gamma$. м., не являющихся локально евклидовыми ни в одной своей точке. Г. м. играют существенную роль в нек-рых вопросах теории преобразований грynn, где они появляются в качестве пространств орбит или множества неІодвижных точек.

Имеется когомологич. вариант определения обобщенных многообразий. Всякое к о г о м о ло г и ч ес ко е м н о го о б р а 3 и е над кольцом главных идеалов $G$ является $\Gamma$. м. над $G$, а если $G$ не более чем счетно, то верно и обратное.

Jum.: [1] E e c h E., "Ann. Math.", 1933, v. 34, p. 621p. 469-573; [3] А л е к с а н д р о в П.. C., "Ann. Math.", 1935,

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=47&width=834&top_left_y=2031&top_left_x=119)
v. 36, p. 1-35; 4. Acad. sci.", 1936 , t. 202, p. 1327-329; [5]

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=50&width=836&top_left_y=2086&top_left_x=118)
B e g l e E., "Amer. J. Math."1942, v. 64, p. 553-73; [7] A., "Mich. Math. J.", 1957, v. 4, p. 227-39; [9] Y a n g C. T., "Trans. Amer. Math.'Soc.", 1958, v. 87, p 261-83; [10] $\dot{\mathrm{C}}$ o nn e r P. E. F F l o y d E. E., "Mach. Math. J.", 1959, v. 6,

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=54&width=824&top_left_y=2223&top_left_x=129)
"Ann. Math. studies", 1960, № 46, p. 23-33; [14] B r e d o n G. E., "Proc. Nat. Acad. 'Sci. 'USA", 1969, v. 63, № 4, p. 1079-81. ГОМОЛОГИЧЕСКОЕ ОПОЯСЫВАНИЕ - метод, позволяющий характеризовать размерность компакта, лежащего в евклидовом пространстве $\mathbb{R} n$, в терминах метрич. свойств дополнительного пространства. Назовем мерой существенности цикла $z$ компакта $\Phi \subset \mathbb{R}^{n}$ верхнюю грань тех $\varepsilon>0$, для к-рых можно подобрать такой компактный носитель $\Phi_{1} \subsetneq \Phi$ цикла $z$, что цікл не гомологичен нулю в $O\left(\Phi_{1}, \varepsilon\right)$. Назовем $p$-мерным г о м оло гич е с ким п о п е р е ч ни ко м $\alpha_{\Gamma}^{p} z$ цикла $z$ открытого множества $\Gamma=\mathbb{R}^{n} \backslash \Phi$ ншжнюю грань $p$-мерных поперечников тел всех циклов, гомологичных в $\Gamma$ циклу z. Здесь под $p$-м е р ны м п о п е р е ч н и к о м $\alpha^{p} X$ компакта $X \subset \mathbb{R}^{n}$ понимается нижняя грань тех

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=35&width=831&top_left_y=588&top_left_x=989)
пакта $X$ в p-мерный компакт (и потому поліэдр).

Всякий $(n-1)$-мерный цикл открытого множества $\Gamma=\mathbb{R}^{n} \backslash \Phi$, зацепленный с каждой точкой компакта $\Phi$, наз. м е ш к о м в о к р у г к о м п а к т а

Т е о р е м а о ме шк а х. Пусть $r=\operatorname{dim} \Phi \leqslant n-1$. Тогда существует такое $\alpha>0$, что всякий мешок вокруг компакта $\Phi$ имеет $(r-1)$-мерный гомологич. поперечник, больший $\alpha$, тогда как $r$-мерный гомологіч. поперечник любого цикла в $\Gamma$ равен нулю. При этом всегда имеются мешки вокруг Ф со сколь угодно малой мероӥ существенности. Если же $\operatorname{dim} \Phi=n$, то существует такое $\alpha>0$, что для всякого мешка $z^{n-1}$ вокруг Ф выполняется $\mu z^{n-1}>\alpha$ (при этом $\alpha_{\Gamma}^{n-2} z^{n-1}>0$ и $\alpha_{\Gamma}^{n-1} z^{n-1}=0$ для всех мешков $\left.z^{n-1}\right)$.

Теорема о мешках может быть еще более усилена с помощью понятия п о я с а в о к р у г ко мп а к т а.

Т е о ре м а о по я с а х. Пусть $Ф \subset \mathbb{R}^{n}-$ компакт размерности $r$. Существует такое $\gamma>0$, что для любого $k=1,2, \ldots, r+1$ и любого $\varepsilon>0$ в $\Gamma=\mathbb{R} n \backslash \Phi$ имеется $(n-k)$-мерный цикл $v$ (пояс размерности $n-k$ вокруг $\Phi)$, при $k>1$ ограничивающий в $\Gamma$, для к-рого $\beta^{r}-k+1 v<\varepsilon, \tau v<\varepsilon$ и, кроме того, для всякого цікла $w$, гомологичного циклу $v$ в $\gamma$-окрестности последнего относительно $\Gamma$ имеет место $\beta^{r-n+1} x>\gamma$; для всякой цеїі $x$, ограниченной циклом $v$ в $\Gamma$, имеет место $\beta^{r-n+1} x>\gamma$.

С другой стороны, если $s>r$ и $k=1, \ldots, s+1$, то пріг любом $\gamma>0$ всякий $(n-k)$-мерный цікл z в $\Gamma$, для к-рого $\tau z<\gamma$, гомологичен в своей $\gamma$-окрестности (относптельно Г) нек-рому циклу $z^{\prime}$ со сколь угодно малым $\beta s-k z^{\prime}$. Далее, если $s>r$ и $k=2,3, \ldots, s+1$, то при произвольном $\gamma>0$ всякий $(n-k)$-мерный цикл $z$, ограничивагощий в $\Gamma$, для к-рого $\beta^{s-k+1} z<\gamma$ (и $\tau z<\gamma$ прін $s=n-1$ ), ограничивает в $\Gamma$ цепь $x$ с $\beta^{s-n+1} x<\gamma$. Здесь через $\beta^{p} x$, $p \geqslant 0$, обозначена нижняя грань тех $\varepsilon>0$, для к-рых супцествует $\varepsilon-c д в и г$ вершин цепи $x$, посредством к-рого цепь $x$ вырождается до размерності $p$; через $\tau x$ обозначена нижняя грань тех $\varepsilon>0$, для к-рых существует $\varepsilon$-сдвиг вершин $x$, переводящий $x$ в нулевую цепь.

Лит.: [1] А л е к с а н д р о в П. С., Введение в гомологическую теорию размерности и общую комбинаторную топологию, М., 1975. А. А. Малъчев.

ГОМоЛОГИЯ в п р о е к тивн о й г е о ме т рий автоморфизм проективной плоскости, переводящпй все точки нек-рой прямой (о с и Г.) в себя и имеющий точно одну неподвижную точку (ц е н т р Г.). Если центр Г. не лежит на оси $Г$., то Г. наз. н е о с о б е н н о й (или г и п е р б о ли ч е с к о й); есліг центр $\Gamma$. лежіт на

![](https://cdn.mathpix.com/cropped/2023_07_08_e6e66ca01268619ad6e4g-1.jpg?height=35&width=819&top_left_y=2022&top_left_x=990)
с к о й). Обычно Г. задается центром, осью іл парой точек в соответствии Г. Г. аффинной плоскости с собственным (конечным) центром и несобственной (бесконсчно удаленной) осью есть гомотетия; с несобственным центром и собственной осью - растяжение и сжатіг $\mathbf{k}$ оси; с несобственным центром и несобственной осью параллельный перенос; особая Г. с несобственным центром и с собственной осью есть сдвіг.

Лит.: [1] X а р т с х о р н Р., Основы проективной геометрии, пер. с англ., М., 1970.

А. Б. Иванов