К локальному критерію устойчивости примыкает диссипативный критерий устойчивости. Разностная схема наз. диссипативной порядка $v(v-$ четное число), если существ ует такое $\delta>0$, что

\[
\begin{aligned}
& |\rho| \leqslant 1-\delta|\xi|^{\nu}, \\
& |\xi|=|k h| \leqslant \pi,
\end{aligned}
\]

где $\rho$ - максимальное по модулю собственное число матрицы перехода (образ Фурье оператора шага) разностной схемы, $k$ - дуальное переменное. Тогда, если разностная схема имеет порядок аппроксимации $2 r+1$ $(2 r+2), \quad r=0,1,2, \ldots$, и является диссипативной порядка $2 r+2(2 r+4)$, то для гиперболических систем дифференциальных уравнений 1-го порядка с эрмитовыми матрицами разностная схема будет устойчива в $L_{2}$.

При исследовании устойчивости разностных схем для нелинейных гиперболич. уравнений (в частности, уравнений газовой динамики) применяется метод дифференциального приближения, к-рый заменяет анализ разностной схемы анализом ее дифференциального приближения.

Например, дифференциальное приближение разностной схемы (4) для уравнения (2) строится следующим образом: разложение в (4) функции

\[
\begin{aligned}
& u_{j}^{n+1}=u(j h,(n+1) \tau), \\
& u_{j-1}^{n}=u((j-1) h, n \tau)
\end{aligned}
\]

в ряды Тейлора относительно точки $x=j h, t=n \tau$ по параметрам $\tau$ и $h$ приводит к $\Gamma$-форме диффференциального представления разностной схемы:

\[
\begin{gathered}
\frac{\partial u}{\partial t}+\sum_{l=2}^{\infty} \frac{\tau^{l-1}}{l !} \frac{\partial^{l} u}{\partial t^{l}}+ \\
+a \frac{\partial u}{\partial x}+a \sum_{l=2}^{\infty} \frac{(-1)^{l-1} h^{l}}{l !} \frac{\partial^{l} u}{\partial x^{l}}=0
\end{gathered}
\]

Исключение в (7) производных

\[
\frac{\partial^{2} u}{\partial t^{2}}, \quad \frac{\partial^{3} u}{\partial t^{3}}, \cdots
\]

приводит к П-форме дифференциального представления разностной схемы (4):

\[
\frac{\partial u}{\partial t}+a \frac{\partial u}{\partial x}=\sum_{l=2}^{\infty} C_{l} \frac{\partial^{l} u}{\partial x^{l}},
\]

где $C_{l}-$ некоторые коэффициенты, зависящие от $\tau$, $h, a ;$ причем $C_{l}=O\left(\tau^{l-1}, h^{l-1}\right)$. Исключение в (7) и (8) членов порядка $O\left(\tau^{2}, h^{2}\right)$ приводит соответственно к Г-форме первого дифференциального приближения разностной схемы (4):

\[
\frac{\tau}{2} \frac{\partial^{2} u}{\partial t^{2}}+\frac{\partial u}{\partial t}+a \frac{\partial u}{\partial x}-\frac{a h}{2} \frac{\partial^{2} u}{\partial x^{2}}=0
\]

и к П-форме первого дифференциального прибліжения разностной схемы (4):

\[
\begin{gathered}
\frac{\partial u}{\partial t}+a \frac{\partial u}{\partial x}=C_{2} \frac{\partial^{2} u}{\partial x^{2}}, \\
C_{2}=\frac{a h}{2}\left(1-\frac{a \tau}{h}\right) .
\end{gathered}
\]

В лінейном случае для ряда разностных схем показано, что из корректности первого диффференциального приближения следует устойчивость соответствующей разностной схемы. Так, в рассмотренном выше случае разностной схемы (4) корректность уравнения (9) означает, что $C_{2} \geqslant 0$, т. е. выполнено необходимое и достаточное условие $a \tau / h \leqslant 1$ устойчивости схемы (4). Члены с четными производнымі в уравнении (8) ответственны за диссипативные свойства разностной схемы, а с нечетными производнымі - за дисперсионные свойства разностной схемы. Под диссипацией разностной схемы (4) понимается величина

\[
d=1-|\rho|^{2}=1-e^{\sum_{l=1}^{\infty}(-1)^{l} \frac{\tau}{h^{2 l}} c_{2 l} \xi^{2 l}}
\]

\[
\rho=1-\frac{a \tau}{h}\left(1-e^{-i \xi}\right)
\]

- множитель успления схемы; под дисперсией разностной схемы (4) - величина

\[
\chi=x a \xi-\arg \rho=\sum_{l=1}^{\infty}(-1)^{l+1} \frac{\tau}{h^{2 l+1}} C_{2 l+1} \xi^{2 l+1} .
\]

Диссипативные члены в (8) определяют свойства аппроксимационной вязкости схемы (т. е. некоторого механизма сглаживания в разностной схеме). На вид диссипативных членов влияют как искусственные диссипативные члены, вводимые в исходное дифференциальное уравнение, так и структура самой разностной схемы. Первое дифференциальное приближение дает главный член аппроксимационной вязкості. Метод дифференциального приближения широко используется при исследовании разностных схем для нелинейных уравнений и позволяет объяснить эффекты неустойчивости разностных схем, наблюдаемые в конкретных расчетах и не улавливаемые локально методом Фурье.

Основой построения разностных схем в многомерных случаях являются методы расщепления (слабой аппроксимации) и дробных шагов, позволяющие сводить интегрирование исходного многомерного уравненія к интегрированию уравнений более простой структуры (см. Дробных шааго метод).

Получают развитие методы решения гиперболич. уравнений, основанные на методе конечных элементов, к-рый можно рассматривать как разностный метод на специальной нерегулярной сетке.

![](https://cdn.mathpix.com/cropped/2023_07_08_beb009eb897029361baeg-1.jpg?height=52&width=796&top_left_y=1231&top_left_x=1027)
Разностные схемы, М., 1973; [2] Р и х т м а й е р Р., М о p-
т о н К., Разностные методы решения к раевых задач, пер. с англ., М., 1972; [3] Р о ж д е с т в е н с к и й Б. Л., Я н е нк. О Н. Н., Системы квазилинейных уравнений.., М., 1968; [4] С а м а р с к и й А. А.' Г у л и н А. В., Устойчивость

![](https://cdn.mathpix.com/cropped/2023_07_08_beb009eb897029361baeg-1.jpg?height=49&width=831&top_left_y=1392&top_left_x=991)
С е р д ю к о в а С. И., «Докл. АН СССР", 1973, т. 208, № 1,
с. $52-55$.

![](https://cdn.mathpix.com/cropped/2023_07_08_beb009eb897029361baeg-1.jpg?height=37&width=809&top_left_y=1455&top_left_x=1012)
д и н а м и ч е с к о й с іг с т е м ы $\left\{S^{t}\right\}-$ компактное подмножество $F$ фазового многообразія $M$, целиком состоящее из траекторий, в окрестности каждой ІІз к-рых поведение (по отношению к нейі) всех соседних траекторий (включая іл те, к-рые не лежат в $F$ ) напоминает поведение траекторий возле седла. Точнее, Г. м. гладкой динамич. системы $\left\{S^{t}\right\}-$ это такое компактное инвариантное подмножество $F$ фазового многообразия $M$, что в каждой точке $x \in F$ в касательном пространстве $T_{x} M$ к $M$ имеются подпространства $E_{x}^{s}$ II $E_{x}^{u}$, для к-рых выполняются следующие два условия. 1) Действие дифференциалов $\tilde{S}_{x}^{t}: T_{x} M \rightarrow T_{S}{ }_{x} M$ отображений $S^{t}: M \rightarrow M$ в точке $x$ на векторы $\xi \in E_{x}^{S}$, $\eta \in E_{x}^{u}$ удовлетворяет неравенствам (см. Дифференцирование отображений):

\[
\begin{gathered}
\left|\tilde{S}_{x}^{t} \xi\right| \leqslant a|\xi| e^{-c t} \text { пріг } t \geqslant 0, \\
\left|\tilde{S}_{x \xi}^{t}\right| \geqslant b|\xi| e^{-c t} \text { пріг } t \leqslant 0, \\
\left|\tilde{S}_{x}^{t} \eta\right| \leqslant a|\eta| e^{c t} \text { пріп } t \leqslant 0, \\
\left|\tilde{S}_{x}^{t} \eta\right| \geqslant b|\eta| e^{c t} \text { пріг } t \geqslant 0
\end{gathered}
\]

с нек-рыми константами $a, b, c>0$, не зависящими от $x$. 2) Если $\left\{S^{t}\right\}-$ каскад (т. е. время $t$ прингмает целочисленные значения), то

\[
T_{x} M=E_{x}^{s} \oplus E_{x}^{u}
\]