классе $Г$. переходить от одного $\Gamma$. к другому и т. д. Наиболее употребительными одноместными операциями являются: у дал е н и е р е б р а (вершины ребра сохраняются), д о б а в л е н и е $\mathrm{p}$ е б р а междудвумя вершинами Г., уд а л е ни е в е р ши ны вместе с инцидентными ей ребрамі (Г., полученный в результате удаления вершины $v$ из графа $G$, часто обозначают $G-v)$, д о б а в ле н и е в е р ш и н ы (к-рую можно соединить ребрами с нек-рыми вершинами Г.), с т яг и в а н и е р е б р а - отождествление пары смежных вершин, т. е. удаление пары смежных вершин и добавление новой вершины, смежной с теми вершинами Г., к-рые были смежны хотя бы с одной из удаленных вершин; п о д р а 3 б и е н и е р е б р а - удаление ребра и добавление новой вершины, к-рая соединяется ребром с каждой вершиной удаленного ребра.

В ряде задач теории $\Gamma$. используются двуместные операции над $\Gamma$. Пусть $G_{1}=G\left(V_{1}, E_{1}\right)$ и $G_{2}=G\left(V_{2}, E_{2}\right)-$ Г. такие, что $V_{1} \cap V_{2}=\phi$ и $E_{1} \cap E_{2}=\phi$. Объединением графов $G_{1}$ и $G_{2}$ наз. граф $G=G_{1} \cup G_{2}$ с множеством вершин $V=V_{1} \bigcup_{2}$ и множеством ребер $E=E_{1} \cup E_{2}$. Произведением графов $G_{1}$ и $G_{2}$ наз. граф $G=G_{1} \times G_{2}$, множеством вершин к-рого являются элементы декартова произведения $V=V_{1} \times V_{2}$, причем две из этих вершин $\left(u_{1}, u_{2}\right)$ и $\left(v_{1}, v_{2}\right)$ смежны в том и только в том случае, если либо $u_{1}=v_{1}$ и вершина $u_{2}$ смежна с вершиной $v_{2}$, либо $u_{2}=v_{2}$ и вершина $u_{1}$ смежна с вершиной $v_{1}$. Напр., любой Г. является объединением своих компонент связности; $\Gamma$., известный как $n$-мерный единичный куб $Q_{n}$, может быть определен рекуррентно с помощью операции произведения:

\[
Q_{n}=K_{2} \times Q_{n-2},
\]

где $Q_{1}=K_{2}-$ граф, состоящий пз пары вершин, соединенных одним ребром. Эті операции можно определить также для пересекающихся $\Gamma$., в частности для подграфов одного $\Gamma$. С л о же ни е м по м о дулю 2 гр а фо в $G_{1}$ и $G_{2}$ наз. граф $G$ с множеством вершин $V=V_{1} \cup V_{2}$ и множеством ребер $E=\left(E_{1} \cup E_{2}\right) \backslash\left(E_{1} \cap E_{2}\right)$.
![](https://cdn.mathpix.com/cropped/2023_07_08_121ae0eceaaeb3baf285g-1.jpg?height=212&width=496&top_left_y=1350&top_left_x=130)

Употребляются и другие многоместные операции над $\Gamma$. Для некоторых классов $\Gamma$. удается найти простые операции, позволяющие

![](https://cdn.mathpix.com/cropped/2023_07_08_121ae0eceaaeb3baf285g-1.jpg?height=82&width=310&top_left_y=1516&top_left_x=122)
с помощью многократного их приме-

нения перейти от любого $\Gamma$. изучаемого класса к любому другому Г. этого класса. На рис. 1 приведена операция, с помощью к-рой в классе Г. с одинаковым набором степеней можно перейти от одного произвольного Г. к любому другому; на рис. 2 показана операция, позволяющая в классе плоских триангуляций (см. Графf плоский) с одинаковым числом вершин перейти от

![](https://cdn.mathpix.com/cropped/2023_07_08_121ae0eceaaeb3baf285g-1.jpg?height=188&width=459&top_left_y=1836&top_left_x=118)

Рис. 2. произвольной триангуляции к любой другой. Для описания и изучения нек-рых классов Г. отыскиваются такие операции и множества Г., из к-рых с помощью данных операций можно получить любой $\Gamma$. заданного класса. Операции над $Г$. используются также для построения Г. с заданными свойствами, при вычислении графов числовых характеристик и т. Д.

Понятие «Г.» используется в определении таких математич. понятий, как управляющая система, в нек-рых определениях алгоритма, грамматики и др. Изложение ряда математич. теорий становится более наглядным при использовании геометрıч. представления Г., напр. теории марковских цепей. Понятие «Г.» широко используется при создании и описании различных математич. моделей в экономике, биологии и т. д.

Лит.: [1] Б е р ж К., Теория графов и ее применения, пер. с франц., М., 1962; [2] O p е O., Теория графов, пер. с англ., М., 1968; [3] 3 ы к о в А. А.,' Теория конечных графов, [в. 1], Новосиб., 1969; [4] х а р ар и Ф., Теория графов,

ГРАФ ДВУДОЛЬНЫЙ, б и х р о м а т и ч е с к й й г р а ф,- граф, множество вершин к-рого $V$ можно разбить на два непересекающихся подмножества $V^{\prime}$ и $V^{\prime \prime}$ (т. е. $\left.V=V^{\prime} \cup V^{\prime \prime}, V^{\prime} \cap V^{\prime \prime}=\phi\right)$ так, что каждое ребро соединяет нек-рую вершину из $V^{\prime}$ с нек-рой вершиной из $V^{\prime \prime}$. Граф является $\Gamma$. д. тогда и только тогда, когда все его простые циклы имеют четную длину. Под $\Gamma$. д. часто понимают также граф, в к-ром заранее заданы подмножества вершин $V^{\prime}$ и $V^{\prime \prime}$ (д о ли). Г. Д. удобны для представления бинарных отношений между элементами двух разных типов, напр.: взяв элементы данного множества и его подмножества, имеем отношение «вхождение элемента в подмножество»; для исполнителей и видов работ имеем отношение «данный исполнитель может выполнять данную работу» И т. Д.

Среди задач о Г. д. важное место занимает изучение п а р о о о е т ан и й, т. е. семейств попарно несмежных ребер. Такие задачи возцикают, напр., в теории расписаний (разбиение ребер Г. д. на минимальное число непересекающихся паросочетаний), в задаче о назначениях (нахождение максимального паросочетания) и т. Д. Мощность максимального паросочетания в $Г$. Д. равна

\[
\left|V^{\prime}\right|-\max _{A^{\prime} \subseteq V^{\prime}}\left(\left|A^{\prime}\right|-\left|V^{\prime \prime}\left(A^{\prime}\right)\right|\right),
\]

где $V^{\prime \prime}\left(\mathrm{A}^{\prime}\right)$ - число вершин из $V^{\prime \prime}$, смежных хотя бы с одной вершиной из $A^{\prime}$. П о л н ы й $Г$. Д. - это Г. Д., в к-ром любые две вершины из различных подмножеств соединены ребром (напр., граф $K_{3,3}$, см. Граб плоский, рис. 1). Обобщением понятия «Г. Д.» является понятие «k-д о л ь н о г о г р а ф а», т. е. графа, в к-ром вершины разбиты на $k$ подмножеств так, что каждое ребро соединяет вершины из разных подмножеств.

Jum.: [1] O p е О., Теория графов, пер. с англ., М., 1968.

ГРАФ ОРИЕНТИРОВАННБІЙ - граф, каждому ребру к-рого приписана ориентация. Г. о. $G$ задается множеством вершин $V$ и набором $E$ упорядоченных пар вершин, наз. д у г а м и. Говорят, что дуга $(u, v)$ исходит из вершины $u$ и входит в вершину $v$. Число дуг, исходящих из $v$, наз. по л у с т е п е н ь ю и сход а в е р ши ны $v$, а число дуг, входящих в $v$, наз. П о л у с т е пе н ь Чередующаяся последовательность вершин и дуг $v_{0}$, $e_{1}, v_{1}, e_{2}, \ldots, e_{n}, v_{n}$, в к-рой $e_{i}=\left(v_{i-1}, v_{i}\right), i=1,2, \ldots, n$, наз. м а р ш р у т о м (ориентированным). Маршрут наз. з а м к н у ты м, если его первая и последняя вершины совпадают. П у т ь - это маршрут, в к-ром все вершины различны. К о н т у р - это нетривіальный (содержащий хотя бы одну дугу) замкнутый маршрут, у к-рого все вершины различны, кроме первой и последней. Если существует путь из вершины $u$ в вершину $v$, то говорят, что $v$ д о с т и ж и ма из $u$.

Г. о. $G$ с нумерованными вершинами $v_{1}, \ldots, v_{n}$ и дугами $e_{1}, \ldots, e_{m}$ можно задать м а т р и ц е й й ц ид е н тност и, т. е. матрицей $\left\|b_{i j}\right\|$ размера $n \times m$, В к-рой

$b_{i j}=\left\{\begin{array}{c}+1 \text {, если дуга } e_{j} \text { исходит из } v_{i} \\ -1, \text { если дуга } e_{j} \text { заходит в } v_{i}, \\ 0, \text { если дуга } e_{j} \text { не инцидентна } v_{i} .\end{array}\right.$

М а т р и це й с ме ж н о т и $A(G)$ вершин Г. о. $G$ наз. матрица $\left\|a_{i j}\right\|$ размера $n \times n$, в к-рой әлемент $a_{i j}$ равен числу дуг, идущих из $v_{i}$ в $v_{j}$. Суммы элементов