Функция Грина для дифференциальных уравнений с частными производными. 1) Эл ли п т и ч е с к и е у р а в н е ни я. Пусть $A$ - эллиптический дифференциальный оператор порядка $m$, порожденный дифференциальным полиномом

\[
a(x, D)=\sum_{|\alpha| \leqslant m} a_{\alpha}(x) D^{\alpha}
\]

в ограниченной области $\Omega \subset R^{N}$ и однородными краевыми условиями $B_{j} u=0$, где $B_{j}-$ граничные операторы c коэфффицентами, определенными на границе $\partial \Omega$ области $\Omega$, к-рая предполагается достаточно гладкой. Функция $G(x, y)$ наз. $\Gamma$. ф. оператора $A$, если при любом $y \in \Omega$ она удовлетворяет однородным краевым условиям $B_{j x} G(x, y)=0$ и, рассматриваемая как обобщенная функция, удовлетворяет уравнению

\[
a(x, D) G(x, y)=\delta(x-y) .
\]

В случае операторов с гладкими коэффициентами и нормальных граничных условий, обеспечивающих единственность решения однородной краевой задачи, Г. ф. существует и решение краевой задачи $A u=f$ представляется в виде (см. [4])

\[
u(x)=\int_{\Omega} G(x, y) f(y) d y
\]

В этом случае для Г. ф. справедливы равномерные при $x \in \bar{\Omega}, y \in \bar{\Omega}$ оценки

$|G(x, y)| \leqslant C|x-y|^{m-n}$, если $m<n$,

$|G(x, y)| \leqslant C+C|\ln | x-y||$, если $m=n$,

и Г. ф. равномерно ограничена, если $m>n$.

Краевая задача на собственные значения $A u=\lambda u$ эквивалентна интегральному уравнению

\[
u(x)=\lambda \int_{\Omega} G(x, y) u(y) d y,
\]

для к-рого применима теория Фредгольма (см. [5]) При этом Г.ф. сопряженной краевой задачи равна $\overline{G(y, x)}$. Отсюда, в частности, следует, что может существовать не более чем счетное число собственных значений и что они не имеют конечных предельных точек, а сопряженная краевая задача имеет комплексно сопряженные собственные значения той же кратности.

Для уравнений 2-го порядка Г. ф. изучена полнее, поскольку явно выписывается вид особенности фундаментального решения. Так, для оператора Лапласа Г. ф. имеет вид

$G(x, y)=-\frac{\Gamma(n / 2)}{2 \pi^{n / 2}(n-2)}|x-y|^{2-n}+\gamma(x, y)$, при $n>2$, $G(x, y)=+\frac{1}{2 \pi} \ln |x-y|+\gamma(x, y), \quad$ при $\quad n=2$,

где $\gamma(x, y)$ - гармоническая в области $\Omega$ функция, выбранная таким образом, чтобы Г. ф. удовлетворяла краевому условию.

$\Gamma$. ф. $G(x, y)$ первой краевой задачи для эллиптич. оператора 2-го порядка $a(x, D)$ с гладкими коэфффициентами в области $\Omega$ с границей $\partial \Omega$ типа Ляпунова позволяет выразить решение задачи

\[
a(x, D) u(x)=f(x) \quad \text { при } \quad x \in \Omega,\left.u\right|_{\partial \Omega}=\varphi,
\]

в виде

$u(x)=\int_{\Omega} G(x, y) f(y) d y+\int_{\partial \Omega} \frac{\partial}{\partial v_{y}} G(x, y) \varphi(y) d \sigma_{y}$, где $\frac{\partial}{\partial v_{y}}-$ производная по внешней конормали для оператора $a(x, D)$.

В случае, если однородная краевая задача $A u=0$ имеет нетривиальные решения, то, как и для обыкновенных дифференциальных уравнений, вводится обоб- щенная Г. ф. Так, напр., в случае второй краевой задачи для оператора Лапласа существует обобщенная Г. ф., ваз. Неймана бункцией (см. [3]).

2) П а р а б о лич е с ки е у р а внения. Пусть $P$ - параболический дифференциальный оператор порядка $m$, порожденный дифференциальным полиномом

\[
\begin{aligned}
p\left(x, t, D_{x}, \frac{\partial}{\partial t}\right) & =\frac{\partial}{\partial t}-\sum_{|\alpha| \leqslant m} a_{\alpha}(x, t) D_{x}^{\alpha}, \\
x & \in \Omega, \quad t>0,
\end{aligned}
\]

и однородными начальным и краевыми условиями

\[
u(x, 0)=0, \quad B_{j} u(x, t)=0,
\]

где $B_{j}-$ граничные операторы с коэффициентами, определенными при $x \in \partial \Omega$ и $t \geqslant 0$. $\Gamma$. ф. оператора $P$ наз. функция $G(x, t, y, \tau)$, к-рая для любых $t>\tau \geqslant 0$ и $y \in \Omega$ удовлетворяет по $x$ однородным краевым условиям, является при $(x, t) \neq(y, \tau)$ решением уравнения

\[
p\left(x, t, D_{x}, \frac{\partial}{\partial t}\right) G(x, t, y, \tau)=0
\]

и для любой непрерывной функции $\varphi(x)$ удовлетворяет соотношению

\[
\lim _{t \rightarrow \tau+0} \int_{\Omega} G(x, t, y, \tau) \varphi(y) d y=\uparrow(x) .
\]

В случае операторов с гладкими коэффициентами и нормальных граничных условий, обеспечивающих единственность решения задачи $p u=0, \Gamma$. ф. существует, и решение уравнения

\[
p\left(x, t, D_{x}, \frac{\partial}{\partial t}\right) u(x, t)=f(x, t),
\]

удовлетворяющее однородным краевым условиям и начальному условию $u(x, 0)=\varphi(x)$, имеет вид

\[
\begin{aligned}
u(x, t)= & \int_{0}^{t} d \tau \int_{\Omega} G(x, t, y, \tau) f(y, \tau) d y+ \\
& +\int_{\Omega} G(x, t, y, 0) \varphi(y) d y .
\end{aligned}
\]

При изучении эллиптич. или параболич. систем вместо Г. ф. вводится понятие матрицы Грина, к-рая позволяет выразить решения однородных краевых задач для указанных систем в виде интегралов от произведений матрицы Грина на векторы правых частей и начальных условий (см. [7]).

Г. ф. наз. по имени Дж. Грина (G. Green), впервые рассмотревшего один ее частный случай в своем исследовании по теории потенциала (1828).

Лum.: [1] Н а й м а $\mathbf{p}$ к М. А., Линейные дифференциальные операторы, 2 изд., М., 1969; [2] К е л Д Ы Ш М. В., "Д. Л., Уравнения математической физики, 4 изд., М., 1966; [4] Бе р с П., Д жо н Ф., Ше е х е p М., Уравнения с частными производными, пер. с англ., M., 1966; [5] G å r d i n g
L., «Math. scand.», 1953, v. 1, № 1, S. 55-72; [6] Ф p и д м a н A., уравнения с частными производными, параболического типа,

![](https://cdn.mathpix.com/cropped/2023_07_08_96cb8de69b5e7bffa466g-1.jpg?height=52&width=821&top_left_y=1830&top_left_x=994)
Функция Грина в теории функций. В теории функций комплексного переменного под (действительной) Г. ф. понимается Г. Ф. первой краевой задачи для оператора Лапласа, т. е. функция вида

\[
G\left(z, z_{0}\right)=\ln \frac{1}{\left|z-z_{0}\right|}+\gamma\left(z, z_{0}\right), z, \in \Omega,
\]

где $z=x+i y-$ комплексное переменное, $z_{0}=x_{0}+i y_{0}$ полюс $\Gamma$. ф., $z_{0} \in \Omega, \gamma\left(z, z_{0}\right)$ - гармонич. функция $z$, принимающая на границе области $\partial \Omega$ значения $-\ln \left(1 /\left|z-z_{0}\right|\right)$. Пусть область $\Omega$ односвязная и $w=$ $=f\left(z, z_{0}\right)$ - аналитич. функция, реализующая конформное отображение области $\Omega$ на единичный круг в плоскости $w$ так, что точка $z_{0}$ переходит в центр круга, $f\left(z_{0}, z_{0}\right)=0, f^{\prime}\left(z_{0}, z_{0}\right)>0$.