стой тогда и только тогда, когда ранг матрицы Якоби $\left\|\frac{\partial F_{i}}{\partial X_{j}}(x)\right\|$ равен $m-d$, где $d-$ размерность $X$ в точке $x$ (я к о б е в ы й к р и т е р и й). В более общем случае, замкнутая подсхема $X \quad \Gamma$. с. $Y$, задаваемая пучком идеалов $I$, будет $\Gamma$. с. в окрестности точки $x$ в том и только в том случае, если существует система образующих $g_{1}, \ldots, g_{n}$ идеала $I_{x}$ в кольце $O_{X}, x$, удовлетворяющая тому условию, что $d g_{1}, \ldots, d g_{n}$ составляют часть базиса свободного $O_{X, x}$-модуля пучка диффференциалов $\Omega_{X / k, x}$.

Лит.: [1] ШІ а ф а р е в и ч и. Р., Основы алгебраической геометрии, М., 1972; [2] G r o t h e n d i e c k A., "Publ. math. IHES», 1967, t. 32; [3] Z a r is k i O., «Trans. Amer. Math. Soc.», 1947 , v. 62 , № 1, p. $1-52$.

В. К. Данилов, К. В. Долгачев. І мента $x$ функции $f$, при к-ром выполнено условие:

\[
\lim _{|h| \rightarrow 0} \frac{|f(x+h)+f(x-h)-2 f(x)|}{|h|}=0 .
\]

Точка дифференцируемости функции является Г. т., обратное, вообще говоря, не верно. Если в Г. т. существует односторонняя производная, то существует и обычная производная. В. Ф. Емельянов.

ГЛАДКАЯ ФУНКІЦЯ - функция, у к-рой каждое значение аргумента является гладкой точкой. Г. ф. может быть разрывной. Если Г. ф. непрерывна на интервале, то множество точек ее дифференцируемости плотно на нем и имеет мощность континуума. Существуют непрерывные, гладкие на числовой прямой функции, не дифференцируемые почти всюду. Г. ф. имеет производную в каждой точке локального экстремума и, в силу әтого, для гладких непрерывных функций остаются справедливыми основные теоремы диффференциального исчисления - теоремы Ролля, Лагранжа, Коши, Дарбу и др. В. Ф. Емельянов .

ГЈАДКЙ КОНТИНУУМ в т о ч к е $p-$ континуум $X$ такой, что для каждой последовательности $x_{1}$, ..., $x_{n} \ldots$ точек из $X$, сходящейся к точке $x$, и каждого подконтинуума $K \subset X$, содержащего точки $p$ и $x$, существует сходящаяся к $K$ последовательность подконтинуумов $\left\{K_{n}\right\}$ в $X$. Континуум, гладкий в каждой своей точке, наз. г л а д к и м.

A. A. Малъчев.

ГЈАДКИЙ МОРФИЗМ с х е м- обобщение на случай схем понятия семейства неособых алгебраицеских многообразий. В классич. случае морфизма комплексных алгебраич. многообразий это понятие сводится к понятию регулярного отображения (субмерсии) комплексных многообразий. Конечно представленный (локально) морфизм схем $f: X \rightarrow Y$ наз. г л а д к и м м о рф и $з$ м о м, если $f$ есть плоский морфизм и если для любой точки $y \in Y$ слой $f^{-1}(y)$ будет әладкой схемой (над полем $k(y))$. Схема $X$ наз. г л а д к о й с х е м о й на д с х м о й $Y$, или $\mathbf{r}$ л а к о й $Y$-с х е м о ї, если структурный морфизм $f: X \rightarrow Y$ является $\Gamma$. м.

Примером гладкой $Y$-схемы служит аффинное пространство $A_{Y}^{n}$. Частный случай понятия $\Gamma$. м. - этальный морфизм. Обратно, всякий Г. м. $f: X \rightarrow Y$ разлагается локально по $X$ в композицию этального морфизма $X \rightarrow A_{Y}^{n}$ п проекции $A_{Y}^{n} \rightarrow Y$.

Композиция Г. м. снова есть Г. м.; аналогично обстоит дело с произвольной заменой базы. Г. м. характеризуется своим дифференциальным свойством: плоский конечно представленный морфизм $f: X \rightarrow Y$ будет Г. м. тогда и только тогда, когда пучок относительных дифференциалов есть локально свободный пучок ранга $\operatorname{dim}_{x} f$ в точке $x$.

Понятие Г. м. аналогично понятию расслоения в смысле Серра в топологии. Напр., Г. м. комплексных алгебраич. многообразий является локально тривиальным дифференцируемым расслоением. В общем случае выполняется следующий аналог аксиомы о накрывающей гомотопии: Для любой аффинной схемы $Y^{\prime}$, ее замкнутой подсхемы $Y_{0}^{\prime}$, определяемой нилыпотентным идеалом, и любого морфизма $Y^{\prime} \rightarrow Y$ канонич. отображение Hom $\left.\operatorname{Hol}^{\prime}, X\right) \rightarrow \mathrm{Hom}_{Y}\left(Y_{0}^{\prime}, X\right)$ сюръективно.

Если $f: X \rightarrow Y$ есть $\Gamma$. м., а локальное кольцо $\emptyset_{Y, y}$ точки $y \in Y$ является регулярным (соответственно нормальным, приведенным), то таким же будет и локальное

![](https://cdn.mathpix.com/cropped/2023_07_08_0645d441cb0ba7ebe7b3g-1.jpg?height=54&width=642&top_left_y=447&top_left_x=990)

Jum.: [1] G r o t h e n d i e c k A., «Publ. math. IHES», 1967, t. 32; [2] Revêtements etales et groupe fondamental, B.,
1971.

ГЈАДКОЕ ШРОСТРАНСТВО - нормированное пространство $X$, в к-ром для каждой точки $x$ с $\|x\|=1$ существует единственный функционал $f \in X^{*}$ такой, что $f(x)=\|f\|=1$. Пространство $X$ гладко тогда и только тогда, когда его норма обладает Гато диøференциалом в каждой точке $x$ с $\|x\|=1 . \quad$ Л. П. Власов.

ГЈАДКОСТИ МОДУЈБ - модуль непрерывности производной порядка $m \geqslant 1$ функции $f(x)$, определенной на банаховом пространстве $X$, т. е. выражение

$=\sup _{\|h\|_{x} \leqslant \delta ; x}\left\|\sum_{i=0}^{m}(-1)^{\omega_{m}(f, \delta, X)=} C_{m}^{i} f\left(x+(m-2 i) \frac{h}{2}\right)\right\|_{X^{2}}$,

где $(x \pm m h / 2) \subset X$. При $m=1$ Г. м. - обычный непрерывности модуль функции $f(x)$. Основные свойства $\Gamma$. м. (для случая $X=\mathbb{C}-$ пространство непрерывных функЦий):

\[
\omega_{m}(f, 0, \mathbb{C})=0
\]

$\omega_{m}(f, \delta, \mathbb{C})$ не убывает вместе с $\delta$;

если $k-$ целое $\geqslant 1$, то

\[
\omega_{m}(f, k \delta, \mathbb{C}) \leqslant k^{m} \omega_{m}(f, \delta, \mathbb{C})
\]

для любого $\lambda>0$

\[
\omega_{m}(f, \lambda \delta, \mathbb{C}) \leqslant(\lambda+1)^{m} \omega_{m}(f, \delta, \mathbb{C})
\]

если $v>m$, то

\[
\omega_{v}(f, \delta, \mathbb{C}) \leqslant 2^{v-m} \omega_{m}(f, \delta, \mathbb{C})
\]

если $v>m$, то

\[
\begin{gathered}
\omega_{m}(f, \delta, \mathbb{C}) \leqslant \\
\leqslant A_{v, m} \delta^{v} \int_{\delta}^{a}\left(\omega_{m}(f, u, \mathbb{C}) / u^{v+1}\right) d u+O\left(\delta^{v}\right),
\end{gathered}
\]

где $A_{v, m}$ и $a$ - постоянные, не зависящие от $f$.

Нек-рые вопросы теории приближения функций могут получить окончательное решение только в терминах Г. м. порядка $m \geqslant 2$. В теории приближения функций важен класс непрерывных периода 2л функций, Г. м. 2-го порядка к-рых удовлетворяет условию

\[
\omega_{2}\left(f, \delta, C_{2 \pi}\right) \leqslant \delta \text {. }
\]

Модуль непрерывности таких функций удовлетворяет условию

\[
\omega_{1}\left(f, \delta, C_{2 \pi}\right) \leqslant\left[\frac{1}{\ln (\sqrt{2}+1)}\right] \delta \ln \frac{\pi}{\delta}+O(\delta),
\]

$0<\delta \leqslant \pi, \quad$ причм постоянная $1 / \ln (\sqrt{2+1})$ не может быть улучшена (см. [4]).

Лum.: [1] Б е p н ш т е й н C. H., Собр. сочинений, т. 1,
с. 37, М., 1952; [2] M a r c h a d A., "J. math. pures et appl.", 1927, t. 6, p. 337-425; [3] Z y g m u n d A., "Duke Math.

![](https://cdn.mathpix.com/cropped/2023_07_08_0645d441cb0ba7ebe7b3g-1.jpg?height=44&width=824&top_left_y=2010&top_left_x=985)
CCCP. Сер. матем.", 1957, т. 21, № 2, с. 283-88. A. В. Ебимов

ГЈОБАЈЦНАЯ СТРУКТУРА ТРАЕКТОРИЙ к в а дра т и ч о го дифф е р е н ц и л а - описание поведения в целом траекторий положительного квадратичного дифберенциала на конечной ориентированной римановой поверхности. Пусть $R$ - конечная ориентированная риманова поверхность, $Q(z) d z^{2}-$ положительный квадратичный дифференциал на $R ;$ пусть $C$ множество всех нулей и простых полюсов $Q(z) d z^{2}$, а $H$ - множество всех полюсов $Q(z) d z^{2}$ порядка $\geqslant 2$.