где $\chi_{A}$ - характеристич. функция $A$; эти определевия әквивалентны. Если $f \in L(A, \mu)$, то $f \in L\left(A^{\prime}, \mu\right)$ для любого измеримого $A^{\prime} \subset A$. Если

\[
A=\mathrm{U}_{n=1}^{\infty} A_{n}
\]

$A_{n}$ измеримо для каждого $n$, для $n \neq k$

\[
A_{n} \cap A_{k}=\varnothing
\]

и $f \in L(A, \mu)$, то

\[
\int_{A} f d \mu=\sum_{n=1}^{\infty} \int_{A_{n}} f d \mu .
\]

Обратно, если при тех же условиях на $A_{n}$ для каждого $n, f \in L\left(A_{n}, \mu\right)$ и

\[
\sum_{n=1}^{\infty} \int_{A_{n}}|f| d \mu<+\infty,
\]

то $f \in L(A, \mu)$ и верно предыдущее равенство ( $\sigma$-аддитивность Л. и.).

Функция множества $A \subset X$

\[
F(A)=\int_{A} f d \mu
\]

абсолютно непрерывна относительно $\mu$; если $f \geqslant 0$, то $F(A)$ есть неотрицательная абсолютно непрерывная относительно $\mu$ мера. Обратное утверждение представляет Радона - Никодима теорему.

Для функций $f: \mathbb{R}^{n} \rightarrow \mathbb{R}^{\mathbf{1}}$ название "интеграл Лебега" применяется $\boldsymbol{k}$ соответствующему функционалу, если мера $\mu$ есть Лебега мера; при этом множество суммируемых функций обозначается просто $L(X)$ и интеграл

\[
\int_{X} f(x) d x
\]

Для других мер этот функционал наз. Лебега-Стилтьеса интегралом.

Если $f: \mathbb{R}^{1} \rightarrow \mathbb{R}^{1}, f \in L[a, b]$ и $x:[\alpha, \beta] \rightarrow[a, b],-$ неубывающая абсолютно непрерывная функция, то

\[
\int_{a}^{b} f(x) d x=\int_{\alpha}^{\beta} f(x(t)) x^{\prime}(t) d t
\]

Если $f: \mathbb{R}^{1} \rightarrow \mathbb{R}^{1}, f \in L[a, b]$ и $g::[a, b] \rightarrow \mathbb{R}^{1}$, -монотонна на $[a, b]$, то $f g \in L[a, b]$ и существует точка $\xi \in[a, b]$ такая, что

\[
\int_{a}^{b} f(x) g(x) d x=g(a) \int_{a}^{\xi} f(x) d x+g(b) \int_{\xi}^{b} f(x) d x
\]

(в т о р а т е о рем а о с р е д н е м).

А. Лебег дал в 1902 (см. [1]) определение интеграла для $X \subset \mathbb{R}^{1}$ и меры $\mu$, являющейся мерой Лебега. Он строил простые функции, равномерно приближающие почти всюцу на множестве конечной меры $E$ измеримую неотрицательную функцию $f: E \rightarrow R^{\mathbf{1}}$, и доказал существование общего предела (конечного или бесконечного) интегралов әтих простых функций при стремлении их к $f$. Л. и. является базой для различных обобщений понятия интеграла. Как отметил Н. Н. Лузин [2], свойство 2) - т. н. абсоліотная интегрируемость, выделяет Л. и. для $f: \mathbb{R}^{\mathbf{1}} \rightarrow \mathbb{R}^{\mathbf{1}}$ из всевозможных обобщенных интегралов.

Лит.: [1] Л е б е г А., Интегрирование и отыскание примитивных функций, пер. с франц., М.- Л., 1934; [2] Лу у3 и н. Н. Н., Интеграл и тригонометрический ряд, М.- Ј., менты теории функций и функционального анализа, 5 изд., М., менты теории функций и функционального анализ, В иноградова.
И. А. Винге.

ЛЕБЕГА КОНСТАНТЫ - 1) Величины

\[
L_{n}=\frac{1}{\pi} \int_{-\pi}^{\pi}\left|D_{n}(t)\right| d t
\]

\[
D_{n}(t)=\frac{\sin (n+1 / 2) t}{2 \sin ^{t} / 2}
\]

есть Дирихле ядро. Л. к. $L_{n}$ при каждом $n$ является:

1) максимальным значением $\left|S_{n}(f, x)\right|$ для всех $x$ и функций $f(t)$ таких, что $|f(t)| \leqslant 1$ при почти всех $t$;

2) точной верхней гранью $\left|S_{n}(f, x)\right|$ для всех $\boldsymbol{x}$ и всех непрерывных функций $f(t)$ таких, что $|f(t)| \leqslant 1$;

3) точной верхней гранью интегралов

\[
\int_{0}^{2 \pi}\left|S_{n}(f, x)\right| d x
\]

для всех функций $f(t)$ таких, что

\[
\int_{0}^{2 \pi}|f(t)| d t \leqslant 1
\]

Здесь $S_{n}(f, x)$ есть частная сумма ряда Фурье по тригонометрич. системе 2л-периодической функции $f(t)$. Справедлива асимптотич. формула:

\[
L_{n}=\frac{4}{\pi^{2}} \ln n+O(1), n \longrightarrow \infty \text {. }
\]

В частности, $L_{n} \rightarrow \infty$ при $n \rightarrow \infty$, что связано с расходимостью тригонометрич. рядов Фурье нек-рых непрерывных функций. В более широком смысле Л. к. определяются для других ортонормированных систем как величины

![](https://cdn.mathpix.com/cropped/2023_07_08_b402878f3688acf1a437g-1.jpg?height=82&width=450&top_left_y=1048&top_left_x=1179)

где $D_{n}(x, t)$ есть ядро Диріхле для данной ортонормированной на $(a, b)$ системы функций, и играют важную роль в вопросах сходимости рядов Фурье по этим системам. Л. к. введены А. Лебегом (Н. Lebesgue, 1909). См. также Лебега функции.

Лит.: [1] З и г м у н д А., Тригонометрические ряды, пер. с англ., т. 1, М., 1965. К. И. Осколков.

2) Л. к. и н е р поляционного процесс а - числа

\[
\lambda_{n}=\max _{a \leqslant x \leqslant b} \sum_{k=0}^{n}\left|l_{n k}(x)\right|, n=1,2, \ldots,
\]

где

\[
l_{n k}(x)=\prod_{j \neq k} \frac{x-x_{j}}{x_{k}-x_{j}},
\]

$x_{0}, x_{1}, \ldots, x_{n}$ - попарно различные узлы интерполяции, лезкащие на нек-ром отрезке $[a, b]$.

Пусть $C[a, b]$ и $\mathscr{P}_{n}[a, b]-$ соответственно пространства непрерывных на отрезке $[a, b]$ функций и многочленов степени не выше чем $n$, рассматриваемых на том же отрезке, с равномерной метрикой, и пусть $P_{n}(x, f)-$ интерполяционный многочлен степени $n$, принимающий в узлах $x_{k}, k=0,1, . ., n$, те же значения, что и функция $f$. Если через $P_{n}$ обозначить оператор, ставящий в соответствие функции $f(x)$ многотлен $P_{n}(x, f)$, $P_{n}: C[a, b] \rightarrow \mathscr{P}_{n}[a, b]$, то $\left\|P_{n}\right\|=\lambda_{n}$, где слева стоит норма оператора в пространстве линейных ограниченных операторов $\mathscr{L}\left(C[a, b], P_{n}[a, b]\right)$ и

\[
\left\|f(x)-P_{n}(x, f)\right\|_{C[a, b]} \leqslant\left(1+\lambda_{n}\right) E_{n}(f),
\]

где $E_{n}(f)$ - наилучшее пріближение функции $f$ алгебраич. многочленами степени $\leqslant n$.

При любом выборе на отрезке $[a, b]$ узлов интерполяции $\lim _{n \rightarrow \infty} \lambda_{n}=+\infty$. Для равноотстоящих узлов существует такая постоянная $c>0$, что $\lambda_{n} \geqslant c 2^{n} n^{-3 / 2}$. Для узлов, совпацающих с нулями многочлена Чебышева,