наз. матрицей Л. п. $f$ в базисе $e_{1}, e_{2}, \ldots, e_{n}$. В ее столбцах стоят координаты образов базисных векторов. Если

\[
C=\left\|\begin{array}{cccc}
c_{11} & c_{12} & \ldots & c_{1 n} \\
c_{21} & c_{22} & \ldots & c_{2 n} \\
\ldots & \ldots & \ldots & \ldots \\
c_{n 1} & c_{n 2} & \ldots & c_{n n}
\end{array}\right\|
\]

- матрица перехода от базиса $e_{1}, e_{2}, \ldots, e_{n}$ к базису $\boldsymbol{e}_{1}^{\prime}, e_{2}^{\prime}, \ldots, \boldsymbol{e}_{n}^{\prime}:$

\[
\begin{gathered}
\boldsymbol{e}_{1}^{\prime}=c_{11} e_{1}+c_{21} e_{2}+\ldots+c_{n 1} e_{n}, \\
\boldsymbol{e}_{2}^{\prime}=c_{12} e_{1}+c_{22} e_{2}+\ldots+c_{n 2} e_{n}, \\
\cdots \cdot \cdots \cdot \cdots+c_{n n} e_{n},
\end{gathered}
\]

то в базисе $\boldsymbol{e}_{1}^{\prime}, \boldsymbol{e}_{2}^{\prime}, \ldots$, $\boldsymbol{e}_{n}^{\prime}$ матрица $B$ Л. п. $f$ будет $B=$ $=C^{-1} A C$.

С у м м о й двух Л. п. $f$ и $g$ наз. такое преобразование $h$, при к-ром для всякого вектора $x \in V$

\[
h(x)=f(x)+g(x) .
\]

П роизв е дением Л. п. $f$ на чи с ло $\lambda$ наз. преобразование $k$, при к-ром $k(x)=\lambda f(x)$ для всякого вектора $x \in V$.

П р о изв еден и ем Л. п. $f$ на Л. П. $g$ наз. преобразование

\[
l(x)=g(f(x))
\]

Сумма двух Л. П., произведение Л. п. на число, произведение двух Л. П. являются линейными преобразованиями. Л. П. образуют алгебру. В случае, когда конечномерное пространство имеет размерность $n$, алгебра его Л. п. изоморфна алгебре квадратных матриц порядка $n$, элементами к-рых являются әлементы того поля, над к-рым построено векторное пространство.

Л. п. $f$, при к-ром векторное пространство отображается на себя, наз. о б р а т и м ы м, если существует такое преобразование $f^{-1}$, что

\[
f f^{-1}=f^{-1} f=E
\]

где $E$ - тождественное преобразование. Преобразование $f^{-1}$ является Л. п. и наз. о б р а т ны м п р е о бр а з о в а н и е м к преобразованию $f$. Л. П., заданное в конечномерном векторном пространстве, обратимо тогда и только тогда, когда определитель его матрицы в каком-нибудь (и тогда во всяком) базисе отличен от нуля. Если $A$ - матрица обратимого Л. п., то матрица обратного ему Л. п. $f^{-1}$ равна $A^{-1}$. Обратимые Л. п. образуют группу по отношению к операции умножения. В случае векторных пространств конечной размерности $n$ эта группа изоморфна группе невырожденных квадратных матриц порядка $n$.

Подпространство $V^{\prime}$ векторного пространства $V$ наз. ин в а р и антным под п рос т р а н с тв о м относительно Л. п. $f$, если $f(x) \in V^{\prime}$ для всякого вектора $x \in V^{\prime}$. Ненулевой вектор $x \in V$ наз. с о б с тв е н ны м в е к т о р ом Л. П. $f$, соответствующим собственному значению $\lambda$, если $f(x)=\lambda x$. В случае пространства конечной размерности над полем комплексных чисел всякое Л. п. имеет собственный вектор (обладает одномерным инвариантным подпространством). В случае конечномерного пространства над полем действительных чисел у всякого Л. П. имеется одномерное или двумерное инвариантное подпространство.

Л. п. $f$, заданное в конечномерном векторном пространстве, наз. д и а г о н а ли з и р у емым Ј. П., если в пространстве $V$ существует такой базис, в к-ром матрица этого преобразования имеет диагональную форму. Другими словами, Л. п. диагонализируемо, если пространство обладает базисом, состоящим из собствөнных векторов этого Л. П. Однако не всякоө Л. п. даже в пространстве над полем комплексных чисел обладает базисом из собственных векторов этого Л. п., напр. Л. п. двумерного пространства, заданное матрицей

\[
\left\|\begin{array}{ll}
1 & 1 \\
0 & 1
\end{array}\right\|
\]

у к-рой имеется единственное одномерное инвариантное подпространство с базисом $\{1,0\}$.

В конечномерном векторном пространстве над полем комплексных чисел для всякого Л. п. существует такой базис, в к-ром матрица этого преобразования имеет клеточный вид, где по главной диагонали стоят жордановы клетіи, а в остальных местах - нули. Жорданова клетка 1-го порядка состоит из одного числа $\lambda$; жорданова клетка порядка $k$ есть квадратная матрица порядка $k$ вида

\[
\left\|\begin{array}{cccccc}
\lambda & 1 & 0 & \ldots & 0 & 0 \\
0 & \lambda & 1 & \ldots & 0 & 0 \\
0 & 0 & 0 & . & . & . \\
0 & 0 & 0 & \ldots & \lambda & 1 \\
0 & 0 & 0 & \ldots & 0 & \lambda
\end{array}\right\|
\]

Числа $\lambda$ являются собственными значениями матрицы Л. п. Одному и тому же $\lambda$ могут соответствовать как несколько клеток одного и того же порядка, так и клетки различных порядков. Матрица, состоящая из жордановых клеток, наз. н о р м а ль н о й жо р д ан ов о й ф о

Л. п. $f$, заданное в евклидовом (унитарном) пространстве, наз. с а м о с о пр я же н ны м (соответственно э р м и т о в ы м), если для всяких двух векторов $\boldsymbol{x}, \boldsymbol{y} \in V$ имеет место равенство $(\boldsymbol{x}, f(\boldsymbol{y}))=(\boldsymbol{y}, f(\boldsymbol{x}))$ (соответственно $(\boldsymbol{x}, f(\boldsymbol{y}))=\overline{(\boldsymbol{y}, f(\boldsymbol{x})})$.

Л. п., заданное в конечномерном евклидовом (унитарном) пространстве, будет самосопряженным (эрмитовым) тогда и только тогда, когда его матрица $A$ в какомнибудь (а тогда и во всяком) ортонормированном базисе является симметрической (соответственно әрмитовой). Самосопряженное (эрмитово) Л. П., заданное в конечномерном евклидовом (соответственно унитарном) пространстве, обладает ортонормированным базисом, в к-ром его матрица имеет диагональную форму. По главной диагонали стоят (всегда действительные) собственные значения матрицы $A$ Л. П.

Л. п. $f$, заданное в евклидовом (унитарном) пространстве $V$, наз. и з о м е т р и ч е с к и м (соответственно у н и т а р н ы м), если для всякого вектора $x \in V \quad\|f(x)\|=\|x\|$.

Л. п., заданное в конечномерном евклидовом (унитарном) пространстве, изометрично (соответственно унитарно) тогда и только тогда, когда его матрица $A$ в каком-нибудь (а тогда и во всяком) ортонормированном базисе была ортогональной (соответственно унитарной). Для всякого изометрич. Л. П., заданного в конечномерном евклидовом пространстве, существует ортонормированный базис, в к-ром матрица преобразования состоит из клеток 1-го и 2-го порядка, стоящих на ее главной диагонали. Клетки 1-го порядка суть действительные собственные значения матрицы $A$ преобразования, равные +1 и -1 , а клетки 2-го порядка имеют вид

\[
\left\|\begin{array}{rr}
\cos \varphi & -\sin \varphi \\
\sin \varphi & \cos \varphi
\end{array}\right\|
\]

где $\cos \varphi$ и $\sin \varphi-$ действительная часть и коэффициент при $i$ комплексного собственного значения, $\lambda=\cos \varphi+i \sin \varphi$ матрицы $A$, на остальных местах матрицы $A$ стоят нули. Для всякого унитарного пре-