ласти $D$, то и любое решение этого уравнения также аналитично.

Существуют и другие утверждения подобного типа. Напр., если коэффициенты и правая часть уравненшя $L u=f$ непрерывно дифференцируемы до порядка $k$ и их $k$-е производные удовлетворяют условию Гёльдера с показателем $\alpha, 0<\alpha<1$, то любое решение обладает производыыми до порядка $k+m$, удовлетворяющими условию Гёльдера с тем же показателем $\alpha$. Принадлежность к классу Гёльдера здесь существенна. Если коэффициенты и правая часть просто непрерывны, то решения могут не иметь непрерывных производных порядка, равного порядку уравнения. Это верно даже для самого простого л. э. У.- Пуассона уравнения $\Delta u=f$

Вышесказанное относится к классич. решениям, т. е. решениям, имеющим непрерывные производные до порядка, равного порядку уравнения. Существуют различные обобщения понятия решения.

Напр., если коәффициенты $a_{\alpha}(x)$ достаточно гладки, то для оператора (1) можно определить сопряженный по Јагранжу оператор

\[
L^{*} u=\sum_{|\alpha| \leqslant m}(-1)^{|\alpha|} D^{\alpha}\left(a_{\alpha} u\right) .
\]

Локально интегрируемая функция $u(x)$ наз. с л а 6 ы м р е ш е н и е м уравнения $L u=f$, если для всех $\varphi \in C_{0}^{\infty}$ (бесконечно дифференцируемых функций с компактным носителем) выполнено тождество

\[
\int f(x) \varphi(x) d x=\int u(x) L^{*} \varphi(x) d x .
\]

Тогда, есліг коэффициенты и правая часть уравнения $L u=f$ непрерывны по Гёльдеру, то всякое слабое решенпе является классическим.

Для уравнения Лапласа простейшей корректно поставленной задачей является Дирихле задача. В общем случае уравнения с оператором (1) краевая задача состоит в отыскании в области $D$ решения $u(x)$ уравнения $L u=f$, удовтетворяющего $m^{\prime}=m / 2$ гранцчным условиям вида

\[
\begin{gathered}
\left(B_{j} u\right)(x)=\sum_{|\alpha| \leqslant m} b_{\alpha j}(x) D^{\alpha} u(x)=\varphi_{j}(x), \\
x \in \partial D, \quad 1 \leqslant j \leqslant m^{\prime} .
\end{gathered}
\]

Задаче Дирихле отвечают граничные операторы $b_{j}=$ $=\left(\frac{\partial}{\partial v}\right)^{j}$, где $\frac{\partial}{\partial v}$ означает дифференцирование по направленію внешней нормали.

Для того чтобы краевая задача была нётеровой, граничные операторы $B_{j}$ должны удовлетворять у с л овию Л о п а т ин с к о г о (см. [2]) - алгебраич. условию, связывающему многочлены

\[
\sum_{|\alpha|=m_{j}} b_{\alpha j}(x) \xi^{\alpha}, \quad 1 \leqslant j \leqslant m^{\prime}, \sum_{|\alpha|=m} a_{\alpha}(x) \xi^{\alpha}
\]

в точках границы $x \in \partial D$. Граничные операторы задачи Дирихле удовлетворяют этому условию по отношению к любому эллиптич. оператору $L$.

Если коэффициенты дифференциального оператора и решение рассматривать в классе комплексных функций, то эллиптичность оператора $L$ в (1) определяется условием $\omega(x, \xi) \neq 0, \xi \neq 0$. Это определение допускает әллиптич. операторы нечетного порядка, как показывает пример о п е р а т ор а $+i \frac{\partial}{\partial x_{2}}$. Кроме того, меняются свойства операторов чет- | ного порядка. Напр., для Бицадзе уравнения (см. [3]):

\[
\frac{\partial^{2} u}{\partial x^{2}}+2 i \frac{\partial^{2} u}{\partial x \partial y}+\frac{\partial^{2} u}{\partial y^{2}}=0
\]

задача Дирихле не является коррегтно поставленной: если $D-$ единичный круг, то функщии вида $u=$ $=f(z)\left(1-|z|^{2}\right)$ являются решениями однородной задачи Дирихле в области $D$ для любой аналитич. функции $f(z)$.

Этот пример привел к необходимости выделять классы әллиптич. операторов, для к-рых сохраняется нётеровость задачи Дирихле. На әтом пути возникло понятие сильно эллиптич. оператора (cм. [4]). Оператор (1) - с и льн о эл липт иче ский о пер ат $о \mathrm{p}$, если для нек-рой комплексной функции $\gamma(x) \neq 0$ выполнено условие

\[
\operatorname{Re} \gamma(x) \sum_{\alpha \mid=m} a_{\alpha}(x) \xi^{\alpha} \geqslant \delta|\xi|^{m}, \delta>0 .
\]

В частности, порядок $m$ - необходимо четное число.

Следующим более широким понятием явилось понятие собственной (правильной) эллиптичности. Оператор (1) - с об с т ве нн о эл ли п т ически й о п е р а т о р, если его порядок четен и для любой пары линейно независимых векторов $\xi$ и $\xi^{\prime}$ многочлен по $\tau$

\[
\sum_{|\alpha|=m} a_{\alpha}(x)\left(\xi+\tau \xi^{\prime}\right)^{\alpha}
\]

имеет ровно $m^{\prime}=m / 2$ корней с отрицательной мнимой частью и столько же - - положительной. Любой эллиптич. оператор при $n \geqslant 3$ собственно әллиптичен, так что определение по существу относится только к случаю $n=2$.

В теории л. э. у. значительную роль играют априорные оценки норм решений через нормы правых частей уравнения и граничных условий. Эти оценки начали систематически использоваться С. Н. Бернштейном (см. [6]) и свое дальнейшее развитие получили у Ю. Шаудера (см. [7]). Шаудеровские оценки относятся к решениям л. э. у. 2-го порядка в области $D$ с непрерывными по Гёльдеру коэффициентами и бывают двух видов. Оценки первого вида (оценки «внутри») состоят в том, что на любом компакте $K \in D$ производные до 2-го порядка включительно и их гёльдеровские константы оцениваются через sup $|u|$ и через модуль и гёльдеровскую константу правой части уравнения. Оценки второго вида (оценки «вплоть до границы») относятся к краевым задачам. Здесь оценивают те же величины, но уже в замыкании рассматриваемой области, и в оценке фигурируют нормы правых частей граничных условий.

IIаудеровские оценки получили дальнейшее распространение для общих л. ә. у. и краевых задач (см. [7]). Вывод этих оценок основан на теории потенциала. С помощью разбиения единицы им придается локальный характер, и дело сводится к оценке норм сингулярных интегральных операторов, к-рые представляют собой свертку с функциями, связанными с фундаментальными решениями (оценки «внутри») или с функциями Грина соответствующей краевой задачи в нек-рой стандартной области (оценки «вплоть до границы»). Эти оценки, полученные первоначально в метрике пространств Гёльдера $C^{\alpha}$, распространены на пространства Соболева $W_{p}^{l} \quad\left(L_{p}\right.$-оценки) и относятся к обобщенным решениям.

Для сильно эллиптич. операторов существует априорная оценка, наз. неравенством Гёрдинга, к-рая получена другими методами. Она лежит в основе функционального подхода к исследованию краевых задач (методы гильбертовых пространств).