П е р в а я к а е в а я з а д а а, в к-рой уравнение (4) задано в цилиндре

\[
\bar{Q}_{T}=\bar{\Omega} \times[0, T],
\]

где $\Omega$ - нек-рая область пространства $\mathbb{R}^{n}$. Требуется вайти функцию $u$, удовлетворяющую уравнению (4), начальному условию

\[
\left.u\right|_{t=0}=\varphi(x), \quad x \in \Omega,
\]

и краевому условию

\[
\left.u\right|_{x \in \partial \Omega, 0 \leqslant t \leqslant T}=\psi(x, t) .
\]

В торая и третья к р а вы е задачи отличаются от первой лишыь условием (6), к-рое заменяется вторым краевым условием

\[
\left.\frac{\partial u}{\partial N}\right|_{x \in \partial \Omega, \quad 0 \leqslant t \leqslant T} \equiv \sum_{i, j=1}^{n} a_{i j} u_{x_{i}} v_{i}=\psi(x, t)
\]

или соответственно третьим

\[
\left(\frac{\partial u}{\partial N}+\sigma u\right)_{x \in \partial \Omega, \quad 0 \leqslant t \leqslant T}=\psi(x, t),
\]

где $v_{i}, 1 \leqslant i \leqslant n,-$ компоненты внешней нормали.

Классич. постановка указанных задач требует от решения непрерывности в замкнутой области, непрерывности вторых производных внутри и в случае второй и третьей краевых задач непрерывности первых производных вплоть до боковой поверхности цилиндра $\Omega$. Кроме того, для задачи Коши - Дирихле, а в случае неограниченности $\Omega$ и для краевых задач требуется ограниченность репения $u$ при $|x| \rightarrow \infty$ (или, более общо, надлежащим образом заданный рост $|u|)$,

Пусть уравнение (4) равномерно параболическое, коэффициенты уравнения, начальных и краевых условий и граница области достаточно гладки. Тогда решения задачи Коши - Дирихле и первой краевой задачи существуют и единственны. Если $a \leqslant 0, \sigma>0$ и выполнены необходимые условия согласования, то аналогичный результат справедлив и для второй и третьей краевых задач.

Единственность указанных задач следует из принципа максимума. Пусть коәффициенты уравнения (4) вепрерывны в $\bar{Q}_{T}$, область $\Omega$ ограничена,

\[
\Gamma=\partial Q_{T} \backslash\{(x, t) \mid x \in \Omega, t=T\}
\]

$\mathbf{H}$

\[
M=\max _{\bar{Q}_{T}} a, \quad N=\max _{\bar{Q}_{T}}|f| .
\]

Тогда для любого решения

\[
u \in C\left(\bar{Q}_{T}\right) \cap C^{2}\left(\bar{Q}_{T} \backslash \Gamma\right)
\]

уравнения (4) справедлива оценка

\[
|u(x, t)| \leqslant e^{M t}\left(N t+\max _{\Gamma}|u|\right), \quad(x, t) \in Q_{T}
\]

Принцип максимума допускает распространение и на случай неограниченных областей. Кроме того, для параболич. уравнений имеет место аналог принципа Заремба - Жиро о знаке наклонной производной в точке әкстремума, известного в теории әллиптич. уравнений.

В теории параболич. уравнений важную роль играют фундаментальные решения. В случае уравнения теплопроводности (5) им является функция

\[
w(x, t, \xi, \tau)=\frac{1}{2 \sqrt{\pi(t-\tau)}} e^{-\frac{(x-\xi)^{2}}{4(t-\tau)}},
\]

при $t>\tau$ удовлетворяіощая уравнению (5), причем для любой ограниченной непрерывной в $\mathbb{R}^{n}$ функции $\varphi(x)$

\[
\lim _{t \rightarrow \tau+0} \int_{\mathbb{R} n} w(x, t, \xi, \tau) \varphi(\xi) d \xi=\varphi(x)
\]

равномерно на компактных подмножествах точек $x \in \mathbb{R}^{n}$. В частности, при $\tau=0$ получается решение

\[
u(x, t)=\int_{\mathbb{R}^{n}} w(x, t, \xi, 0) \varphi(\xi) d \xi
\]

задачи Коши - Дирихле. На значение решения $u$ в точке $(x, t), t>0$, влияют все значения функции. Это служит выражением того факта, что возмущения задачи Когши - Дирихле распространяются с бесконечной скоростью. В этом существенное отличие параболич. уравнений от гиперболических, где скорость распространения возмущений конечна.

Фундаментальные решения могут быть построены и для общих параболич. уравнений и систем при весьма широких предположениях относительно гладкости коәффициентов.

Лum.: [1] Б и ц а д з е А. В., Уравнения математической физики, М., 1976; [2] Ј а д ы ж е н с к а н О. А., С о ло о нлинейные уравнения параболического типа, М., 1967; [3] Ф м а н A., Уравнения с частными производными параболическом а н А., Уравнения с частными производными параболическо-
го типа, пер. с англ., М., 1968; [4] Э й д е ь м а с С. Д., Параболические системы, М., 1964; [5] И л ь и н А. М., К а л а ш н и к о в А. С., О л е й н ин К О. А., "Успехи ма-
тем. наук", 1962 , т. 17, в. 3., с. З-46. С. Солдатов.

ЛИНЕЙОЕ ПОДПРОСТРАНСТВО, в е к т о р н о е п о д п р о с т р а н с т в о,- непустое подмножество $L$. (линейного) векторного пространства $E$ над полем $K$ такое, что $L$ само является векторным пространством по отношению к определенным в $E$ действиям сложения и умножения на скаляр. Множкество $L+x_{0}$, где $x_{0} \in E$, наз. линейным многообразием. М. И. Войцеховский.

ЛИНЕЙНОЕ ПРЕДСТАВЛЕНИЕ - Гомоморфизм $\pi$ группы (соответственно алгебры, кольца, полугруппы) $\boldsymbol{X}$ в группу всех обратимых линейных операторов в векторном пространстве $E$ (соответственно в алгебру, кольцо, мультипликативную полугруппу всех линейных операторов в $E$ ). Еслі $E$ - топологич. векторное пространство, то Л. П. $X$ в $E$ наз. такое, образ к-рого содержит только непрерывные линейные операторы в $E$. Пространство $E$ наз. П р о с т р а н с т в о м п р е д с т а в ле ни я $\pi$, а операторы $\pi(x), x \in X,-$

![](https://cdn.mathpix.com/cropped/2023_07_08_b00c2c51663e0706bbd8g-1.jpg?height=37&width=734&top_left_y=1465&top_left_x=995)

Лит.: [1] К и р и л л о в А. А., Элементы теории представ-
лений, 2 изд., М., 1978 .

ЛИНЕИНОЕ ПРЕОБРАЗОВАНИЕ - отображенИе векторного пространства в себя, при к-ром образом суммы двух векторов является сумма их образов, а образом произведения вектора на число - произведение образа вектора на это число. Если $V-$ векторное пространство, $f$ - заданное в нем Л. п. и $\boldsymbol{x}, \boldsymbol{y}$ - любые векторы пространства, $\lambda$ - любое число (элемент поля), то

\[
f(\boldsymbol{x}+\boldsymbol{y})=f(\boldsymbol{x})+f(\boldsymbol{y}), \quad f(\lambda x)=\lambda f(\boldsymbol{x}) .
\]

Если вскторное пространство $V$ имеет конечную размерность $n ; e_{1}, e_{2}, . ., e_{n}-$ его базис; $x_{1}, x_{2}, \ldots$, $x_{n}$ - координаты произвольного вектора $x$ в этом базисе и $y_{1}, y_{2}, \ldots, y_{n}-$ координаты его образа $\boldsymbol{y}=f(\boldsymbol{x})$. то координаты вектора $\boldsymbol{\mu}$ выражаются через координаты вектора $\boldsymbol{x}$ линейными однородными функциями

Матрица

\[
\begin{gathered}
y_{1}=a_{11} x_{1}+a_{12} x_{2}+\ldots+a_{1 n} x_{n}, \\
y_{2}=a_{21} x_{1}+a_{22} x_{2}+\ldots+a_{2 n} x_{n}, \\
\cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot a_{n n} x_{n} .
\end{gathered}
\]

\[
A=\left\|\begin{array}{cccc}
a_{11} & a_{12} & \ldots & a_{1 n} \\
a_{21} & a_{22} & \ldots & a_{2 n} \\
\ldots & \ldots & \cdots & \ldots \\
a_{n 1} & a_{n 2} & \ldots & a_{n n}
\end{array}\right\|
\]