их вещественных форм. Наиболее важен здесь факт существования у всякой комплексной полупростой группы $G$ единственной компактной вещественной формы $B$; это означает, что алгебра Ли $L(G)$ изоморфна $L(\vec{B}) \bigotimes_{\mathbb{R}} \mathbb{C}$, т. е. получается комплексификацией алгебры Ли $L(B)$. Основываясь на этом, Э. Картан в 30-х гг. 20 в. получІл полную классификацию вещественных форм комплексных полупростых Ли г. В терминах Галуа когомологий это равносильно описанию множества $H^{1}(\mathbb{R}$, Aut $(G)$ ) (см. также Линейная алгебраическая группа).

Впоследствии метод Киллинга был усовершенствован Э. Картаном и Г. Вейлем, что дало возможность решить ряд других классификационных проблем, $\mathbf{a}$ также развить важную теорию представлений Ли $г$. Получена классификация полупростых подгрупп классич. комплексных простых Ли г. (см. [17]).

Современное развитие и применения. В $50-\mathbf{x}$ гг. 20 в. в теории Ли г. начался новый этап развития, что выразилось, в частности, в создании теории алгебраич. групп (см. Линейная алгебраическая группа). Еше ранее К. Шевалле (С. Chevalley, см. [12]) детально объяснил алгебраич. природу основных результатов теории Ли. Привлечение методов алгебраич. геометрии позволило по-новому осветить эти классич. результаты и открыло новые глубокие связи с теорией функций, теорией чисел и т. д. Значительное развитие получила теория р-адических групп Ли (см. [3], [6]). Ли г. связаны практически со всеми основными разделами математики: с геометрией и топологией - через теорию Лu групn преобразованиц̆, с анализом - через теорию линейных представлений и т. д. Чрезвычайно важны также разнообразные применения Ји г. в физике и механике.

Лum.: [1] П о н т р я г и н Л. С., Непрерывные группы, 3 изд., М., 1973; [2] Бо р е л ь А., Линейные алгебраические группы, пер. с англ., М., 1972; [3] Б у р б а к и Н., Группы и алгебры ЈІи, пер. с франц., [гл. 1-8], М., 1972-78; [4] В е й л ь Г., Классические группы, их инварианты и представления, пер. с англ., М., 1947; [5] Ви гн е р Е., Теория групп и ее приложения к квантомеханической теории атомных спекти ее приложения к квантомеханической теории атомных спект-
ров, пер. с англ., М., 1961; [6] С е р p Ж.- П., Алгебры Ли и ров, пер. с англ., М., 1961; [6] С е р р Ж.- П., Алгебры Ји и
группы Ли, пер. с англ. и франц., М., 1969; [7] С т е й нгруппы Ли, пер. с англ. и франц., М., 1969; [7] С т е й н[8] 'Теория алгебр Ли. Топология групп Ли. Семинар «Софус Ли», пер. с франц., М., 1962; [9] X а м е р м е ші М., Теория групі и ее применение к физическим проблемам, пер. с англ., М., 1966; [10] X е л г а с о н С., Дифференциальная геометрия и симметрические пространства, пер. с англ., М., 1964; [11] ч е б о т ар е в Н. Г., Теория групп Ли, М.- Л., 1940; [12] Ш е в а Лл е к., Теория групп Ји, пер. с англ. и франц., т. 1-3, М., 1948-58; [13] Ho c h s ch i l d G., The Structure of Lie Groups, S. F., 1965; [14] M o n t g o m e r y D., Z i p p i n L., А д о И. Д., «Изв. Физ.-матем. об-ва» (Казань), 1935, т. 7, с. $1-43 ;[16]$ М а л ь ц е в А. И., «Матем. сб.», 1945, т. 16, с. $163-90 ;[17]$ е г о ж е, "изв. Ан СССР. Сер. матем.», 1944, т. 8 , № 4, с. $143-74 ;$ [18] С к л я р е н к о Е., в кн.: Проблемы Т. 8, № 4, с. $143-74 ;$,

ЛИ ГРУППА ПРЕОБРАЗОВАНИЙ - гладкое действие связной группы Ли $G$ на гладком многообразии $M$, т. е. гладкое (класса $C^{\infty}$ ) отображение $A: G \times M \rightarrow M$ такое, что:

(I) $A\left(g^{\prime} g^{\prime \prime}, m\right)=A\left(g^{\prime}, A\left(g^{\prime \prime}, m\right)\right) \quad \forall g^{\prime}, g^{\prime \prime} \in G, m \in M$;

(II) $A(e, m)=m \quad \forall m \in M$

$(e-$ единица группы $G)$.

Ли г. п., удовлетворяющая также условию: (III) если $A(g, m)=m \quad \forall m \in M$, то $g=e$, наз. әфф е к т п н о й.

Прим е р ы Л и г. П. Любое гладкое линейное представление группы Ли $G$ в конечномерном векторном пространстве $M$; действие группы Ћи $G$ на себе с помощью левых или правых сдвигов $A(g, m)=g m$ или $A(g, m)=m g^{-1}$ соответственно $(g, m \in G)$; действие группы Ји $G$ на себе с помошыю внутренних автоморфизмов $A(g, m)=g m g^{-1}(g, m \in G) ;$ однопараметрическая группа преобразований, т. е. гладкое действие группы $\mathbb{R}$ на многообразии $M$. Наряду с определенными выше глобальными Ли г. п. рассматриваются также л о к а л ь ы е Л и г. П., являвшиеся основным объектом классич. теории групп Ли [1]. При этом вместо $G$ рассматривается локальная группа Ли, т. е. окрестность $U$ единицы в нек-рой группе Ли, а вместо $M$ - открытое подмножество $W \subset \mathbb{R}^{n}$.

Если $G$ - Ли г. п. на $M$, то, выбрав подходящие окрестность $U \ni e$ в $G$ и открытое подмножество $W \subset M$, получают локальную Ли г. П. Обратный переход от локальной Ли г. П. к глобальной (г л о б а л и з ац и я) - возможен не всегда. Однако если $\operatorname{dim} M \leqslant 4$ и $W$ достаточно мало, то глобализация возможна (cм. [2]).

Иногда рассматриваются Ли г. П. класса $C^{k}, 1 \leqslant k \leqslant \infty$, или $C^{\omega}$ (аналитические), т. е. предполагается принадлежность отображения $A$ соответствующему классу. Если $A$ непрерывно, то для его принадлежности классу $C^{k}$ или $C^{\omega}$ достаточно, чтобы для любого $g \in G$ преобразование $A_{g}: m \rightarrow A(g, m)$ многообразия $M$ принадлежало этому классу (см. [3]). В частности, задание Ли г. П. $G$ на $M$ эквивалентно заданию непрерывного гомоморфизма $G \rightarrow$ Diff $M$ в группу Diff $M$ диффеоморфизмов многообразия $M$, снабженную естественной топологией.

Любой Ли г. п. соответствует гомоморфизм $A_{*}: \mathfrak{g} \rightarrow$ $\rightarrow \Phi(M)$ алгебры Ли $g$ группы $G$ в алгебру Ли $\Phi(\vec{M})$ гладких векторных полей на $M$, сопоставляющий элементу $X \in \mathfrak{g}$ поле скоростей однопараметрич. группы преобразований

\[
(t, m) \rightarrow A(\exp t X, m)
\]

где $t \in \mathbb{R}, m \in M, \exp : \mathfrak{g} \rightarrow G-$ экспоненциальное отображение (см. [5]). Если $G$ әфффективна, то гомоморфизм $A_{*}$ инъективен. Для связной группы $G$ гомоморфизм $A_{*}$ полностью определяет Ли г. П. Обратно, любому гомоморфизму $\beta: \mathfrak{g} \rightarrow \Phi(M)$ отвечает локальная Ли г. п. [6]. Если все векторные поля из $\beta(\mathfrak{g})$ п о л ны (т. е. их интегральные кривые $x(t)$ определены для всех $t)$, то существует глобальная Ли г. П. $G$ на $M$, для к-рой $\operatorname{Im} A_{*}=\mathfrak{g}$. Достаточно потребовать, чтобы $\beta(\mathfrak{q})$ как алгебра Ли порождалась полными векторными полями; условие полноты автоматически выполнено, если $M$ компактно [4].

Если $G-Л_{1}$ г. П. многообразия $M$, то стационарная подгруппа $G_{m}=\{g \in G \mid A(g, m)=m\}$ для любой точки $m \in M$ является замкнутой подгруппой Ли в $G$; ее называют также с т а 6 и ли з а т о р о м, или по дг р у П По й и зот р о пи и, точки $m$. Соответствующая подалгебра Ли $\mathfrak{g}_{m} \subset \mathfrak{g}$ состоит из всех таких $X \in \mathfrak{g}$, что $A_{*}(X)_{m}=0$. Подалгебра $\mathfrak{q}_{m}$ непрерывно зависит от $m$ в естественной топологии на множестве всех подалгебр в $g[7]$. Орбита $G(m)=\{A(g, m), g \in G\}$ точки $m$ является погруженным подмногообразием в $M$, дифффеоморфным $G / G_{m}$. Если $G$ компактна, то все орбиты являются компактными вложенными подмногообразиями. Примеры невложенных орбит дает действие группы $\mathbb{R}$ на торе

\[
T^{2}=\left\{\left(z_{1}, z_{2}\right)\left|z_{i} \in \mathbb{C}, \quad\right| z_{i} \mid=1, \quad i=1,2\right\},
\]

заданное формулой

\[
A\left(t,\left(z_{1}, z_{2}\right)\right)=\left(e^{i t} z_{1}, e^{i \alpha t_{z_{2}}}\right),
\]

где $\alpha \in \mathbb{R}$ иррационально.

Ли г. п. $A_{i}: G \times M_{i} \rightarrow M_{i}, i=1,2$, наз. по д о б ным и, если существует такой диффеоморфизм $f: M_{1} \rightarrow M_{2}$, что $A_{1}(g, m)=A_{2}(g, f(m)), g \in G, m \in M_{1}$. Важной задачей теории групп преобразований является задача классификации Ли г. П. с точностью до подобия. В настоящее время (1982) она решена лишь в нек-рых частных случаях. Еще С. Ли [1] дал классификацию локальных Ли г. П. в областях пространства $\mathbb{R}^{1}$ и $\mathbb{R}^{\mathbf{2}}$ с