![](https://cdn.mathpix.com/cropped/2023_07_08_ad3d95c005bb772b759eg-1.jpg?height=37&width=814&top_left_y=180&top_left_x=136)
рия, пер. с англ., М., 1973; [6] Б о р е л ь А., Линейные алгебраические группы, пер. с англ., М., 1972; [7] Д в е д о н н е Ж., М а л ь ц е в А. И., Избранные труды, т. 1- Классическая алгебра, М., 1976, с. 58-73,294-313: [9] П л а т о но в В. П., «Изв. АН СССР. Сер. матем.", 1966, т. 30, № 3, c. 573-620 "10] е г о же, там же, 1976, т. 40, № 2, c. 227-61; [11] Cеминар по алгебраическим группам, иер. с англ., М., 1973; [12] С т е й н б е р г Р., Лекции о группах Шевалле, пер. с англ., М., 1975; [13] С уп р у н е н к о Д. А., Группы матриц, М. 1972; [14] Т и т с Ж., "Математика", 1972, т. 16, № 2, с. 47-66; [15] III в а л ле К., там же, p. 119-31; [17] D r a x l P., K n e s e r M., SK von Schief-

![](https://cdn.mathpix.com/cropped/2023_07_08_ad3d95c005bb772b759eg-1.jpg?height=45&width=817&top_left_y=506&top_left_x=131)
Infinite ]inear groups, B.- Hdlb.-- N. Y., 1973; [19| Итоги нау ки. Алгебра. Топология. Геометрия, 1970, М., 1971, с. 75-110.

![](https://cdn.mathpix.com/cropped/2023_07_08_ad3d95c005bb772b759eg-1.jpg?height=33&width=777&top_left_y=595&top_left_x=166)
нейная независимость.

ЛИНЕИНАЯ ИНТЕРПОЛЯЦИЯ - способ приближенного вычисления значения функции $f(x)$, основанный на замене функции $f(x)$ линейной функцией

\[
L(x)=a\left(x-x_{1}\right)+b
\]

параметры $a$ и $b$ к-рой выбираются таким образом, чтобы значения $L(x)$ совпадали со значениями $f(x)$ в заданных точках $x_{1}$ и $x_{2}$ :

\[
L\left(x_{1}\right)=f\left(x_{1}\right), \quad L\left(x_{2}\right)=f\left(x_{2}\right) .
\]

Этим условиям удовлетворяет единственная функция

\[
L(x)=\frac{f\left(x_{2}\right)-f\left(x_{1}\right)}{x_{2}-x_{1}}\left(x-x_{1}\right)+f\left(x_{1}\right),
\]

приближающая заданную функцию $f(x)$ на отрезке $\left[x_{1}, x_{2}\right]$ с погрешностью

\[
f(x)-L(x)=\frac{f^{\prime \prime}(\xi)}{2}\left(x-x_{1}\right)\left(x-x_{2}\right), \quad \xi \in\left[x_{1}, x_{2}\right] .
\]

Вычисления, необходимые для Л. и., легко реализуются при ручном счете, благодаря чему этот способ широко используется при интерполировании табличных данных.

Лum.: [1] Б а х в а л о в Н. С., Численные методы, 2 изд., М., 1975; [2] Бе р е з и н И. С., ЖЖ и д к о в Н. П., Методы
вычислений, 3 изд., т. 1, М., 1966.

ЛИНЕИНАЯ КЈАССИЧЕСКАЯ ГРУІІІА - группа невырожденных линейных преобразований конечномерного векторного пространства $E$ над телом $K$, являющаяся классической әруппой (см. также Линейная әруппа). Важнейшими типами Л. к. г. являются следующие: полная линейная группа $\mathrm{GL}_{n}(K)$, специальная өиейная группа $\mathrm{SL}_{n}(K)$, сияплектическая әруппа $\mathrm{Sp}_{n}(K)$, ортогональная аруппа $\mathrm{O}_{n}(K, f)$, униmарная групna $\mathrm{U}_{n}(K, f)$ (здесь $n=\operatorname{dim} E, f-$ соответствующая полуторалинейная форма на $E)$.

ПИНЕИНА теРА. П. Попов. КРЕАЯ ЗАНАчА - задача определения в нек-рой области $D$ переменных $x=\left(\begin{array}{ll}x_{1}, & x_{2} \text {, }\end{array}\right.$ ..., $x_{n}$ ) решения $u(x)$ линейного дифференциального уравнения

$(L u)(x)=f(x), \quad x \in D$,

удовлетворяющего на границе $S$ этой области (или ее части) линейным краевым условиям

$(B u)(y)=\varphi(y), \quad y \in S$.

См. также Краевая задача.

A. П. Солдатов.

ЛИНЕИНАЯ КРАЕВАЯ ЗАДАЧА; ч и с Л е н Н Ы е ме то д ы р е ше ни я - методы, позволяюшие получить решение Л. к. 3. в виде таблицы его приближенных значений в точках сетки, не используя предварительной информации об ожидаемом виде решшения. Для теории этих методов типично предположение о том, что решение исходной задачи существует и имеет достаточное число производных. Благодаря отсут- ствию других предположений численные методы отличаются своей универсальностью.

Основой численных методов решения Л. к. з. является замена исходной системы уравнений ее сеточной аппроксимацией. В случае интегро-дифференциальных уравнений такая аппроксимация обычно строится с помощью разностных схем и квадратурных формул. При этом возникают следующие проблемы:

1) насколько быстро точное решение сеточной задачи сходится к решению исходной задачи при измельчении сетки;

2) насколько решение сеточной задачи чувствительно к изменениям исходных данных;

3) как найти, хотя бы приближенно, решение сеточной задачи.

При решении первой и второй проблем используется следующий аппарат. Пусть в замкнутой области $D$ задано уравнение

\[
L u=f
\]

а на ее границе $\Gamma$, состоящей из компонент $\Gamma_{i},-$ граничные условия

\[
l_{i} u=\varphi_{i} \text { на } \Gamma_{i}, \quad i=1,2, \ldots, s .
\]

Здесь заданные непрерывные функции $f, \varphi_{i}$ принадлежат нормированным линейным пространствам $F, \Phi_{i}$ соответственно, а линейные операторы $L$ и $l_{i}$ преобразуют нек-рое линейное подмножество $W$ нормированного линейного пространства $U$ функций, непрерывных в $D$, в $F$ и $\Phi_{i}$ соответственно.

Пусть для аппроксимации уравнения (1) выбраны сетки $D_{h}$ и $D_{h}^{0} \subset D$, зависящие от положительного параметра $h$; нормированные линейные пространства $U_{h}$ и $F_{h}$ функций $u_{h}$ и $f_{h}$, определенных в точках сеток $D_{h}$ и $D_{h}^{0}$ соответственно, а также линейный оператор $L_{h}$, преобразующий $U_{h}$ в $F_{h}$. Для аппроксимации граничного условия (2) выбирается сетка $\Gamma_{i h} \subset \Gamma$, нормированное линейное пространство $\Phi_{i h}$ Функций $\varphi_{i h}$, определенных в точках сетки $\Gamma_{i h}$, и линейный оператор $l_{i h}$, преобразующий $U_{h}$ в $\Phi_{i h}$. Кроме того, выбираются линейные операторы $P_{h}$ и $p_{i h}$, преобразующие $F$ и $\Phi_{i}$ в $F_{h}$ и $\Phi_{i h}$ соответственно. В результате получается сеточная а п п р о к и м а ц и я

\[
\begin{gathered}
L_{h} u_{h}=P_{h} f, \\
l_{i h} u_{h}=p_{i h} \varphi_{i} \text { на } \Gamma_{i h}, i=1,2, \ldots, s,
\end{gathered}
\]

исходной задачи (1), (2). Пусть через $[u]_{h},\{f\}_{h},\left\{\varphi_{i}\right\}_{i h}$ обозначены следы функций $u, f, \varphi_{i}$ из пространств $U, F, \Phi_{i}$ на сетках $D_{h}, D_{h}^{0}, \Gamma_{i h}$ соответственно. Исследование сходимости сеточных аппроксимаций $u_{h}$ $\kappa$ решению $u$ исходной задачи при $h \rightarrow 0$ имеет смысл производить лишь в сеточных нормах, согласованных с нормами в пространствах $U, F, \Phi_{i}$, т. е. при условии, что для любых функций $u, f, \varphi_{i}$ выполняются предельные соотношения

\[
\begin{gathered}
\left\|[u]_{h}\right\|_{\mathrm{U}_{h}} \longrightarrow\|u\| \mathrm{U},\left\|\{f\}_{h}\right\|_{F_{h}} \rightarrow\|f\|_{F}, \\
\left\|\left\{\varphi_{i}\right\}_{i h}\right\|_{\Phi_{i h}} \longrightarrow\left\|\varphi_{i}\right\|_{\Phi_{i}}
\end{gathered}
\]

Если $u \in W, f^{*} \in F, \varphi_{i} \in \Phi_{i}$, то величина

\[
\begin{gathered}
z(h)=\left\|L_{h}[u]_{h}-\{L u\}\right\|_{F_{h}}+\left\|P_{h} f-\{f\}_{h}\right\|_{F_{h}}+ \\
+\sum_{i=1}^{s}\left\|l_{i h}[u]_{h}-\left\{l_{i} u\right\}_{h}\right\|_{\Phi_{i h}}+\left\|P_{i h} \varphi_{i}-\left\{\varphi_{i}\right\}_{i h}\right\|_{\Phi_{i h}}
\end{gathered}
\]

наз. п о г р е шн о с т ь ю п п р о к с и а ци и задачи (1), (2) задачей (3), (4). Если $u$ - решение задачи (1), (2), то величина

\[
\rho(h)=\left\|L_{h}[u]_{h}-P_{h} f\right\|_{F_{h}}+\sum_{i=1}^{s}\left\|l_{i h}[u]_{h}-p_{i h} \varphi_{i}\right\|_{P_{i h}}
\]