преобразование усложняет метод. Нестационарные процессы, в частности циклические, используются для ускорения сходимости итерационных процессов (cм. [5], [6]). Среди методов ускорения сходимости особое место занимают методы, использующие многочлены Чебышева (см. [5], [6]) и сопряженные направления (см. [10]).

Выбор матрицы $H$ для стационарного процесса и матриц $H^{(k)}$ для нестационарного может осуцествляться различными способамц. Возможно построение матриц $H^{(k)}$ таким образом, чтобы итерационный процесс сходился к решению и по возможности быстро для широкого класса систем уравнений (см. [5]). Возможен и противоположный подход, когда при построении матриц $H^{(k)}$ максимально используются частные особенности данной системы для получения итерационного процесса с наибольшей скоростью сходимости (см. [6]). Второй способ построения матриц $H^{(k)}$ является наиболее распространенным.

Одним из наиболее распространенных принципов построения итерационных процессов является принцип релаксациі (см. Релаксации методы). В этом случае матрицы $H^{(k)}$ выбираются из заранее описанного класса матриц так, чтобы на каждом шаге процесса уменьшалась какая-либо величина, характеризующая точность решения системы. Среди релаксационных методов наиболее разработаны координатные и градиентные методы. В координатных методах матрицы $H^{(k)}$ подобраны так, что на каждом шаге меняются одна или несколько компонент последовательных приближений. $\mathrm{O}$ точности приближенного решения $x$ чаще всего судят по величине вектора невязки $r=A x-b$.

В случае стационарных итерационных методов главный член погрешности можно оценить также с помощью $\delta^{2}$-процесса (см. [5]).

Среди других итерационных методов можно отметить простой итерации метод, переменных направлений метод, методы полной и неполной релаксации и т. д. (см. [1], [6], [10]). Как правило, итерационные методы удобны для реализации на ЭВМ, однако в отличие от прямых методов они чаще всего обладают весьма ограниченной областью применения. В области же их применения итерационные методы нередко существенно превосходят прямые методы по объему вычислений. Поэтому вопрос сравнения прямых и итерационных методов может быть решен лишь при детальном изучении свойств конкретной системы. Наибольшее распространение нашли итерационные методы для решения систем, возникающих при разностной аппроксимации дифференциальных уравнений (см. [5], [6]).

Итерационные методы решения полной проблемы собственных значений. В итерационных методах собственные значения вычисляются как пределы нек-рых числовых последовательностей без предварительного определения коэффициентов характеристич. многочлена. Как правило, при әтом одновременно находятся и собственные векторы или нек-рые другие векторы, связанные с собственными простыми соотношениями. Большинство итерационных методов менее чувствительны к ошибкам округления, чем прямые, но значительно более трудоемки. Развитие этих методов и их применение в практике вычислений стало возможным лишь после создания ЭВМ.

Среди итерационных методов особое место занимает метод вращений (Якоби метод) решения полной проблемы собственных значений действительной симметричной матрицы. Основан он на построении последовательности матриц, ортогонально подобных исходной матрице $A$ и имеющих монотонно убывающие до нуля суммы квадратов всех внедиагональных элементов.

Метод вращений очень прост, легко реализуется на ЭВМ и всегда сходится. Независимо от расположения собственных значений он обладает асимптотически квадратичной сходимостью. Наличие кратных и близких собственных значений не только не замедляет сходимость метода, но, напротив, приводит к ее ускорению. Метод вращений устойчив к влиянию ошибок округления результатов промежуточных вычислений. Свойства этого метода послужили причиной его распространения на решение полной проблемы матриц более общего вида. Без существенных изменений метод вращений переносится на әрмитовы и косоэрмитовы матріцы. Незначительное его изменение позволяет с успехом решіать полную проблему для матриц $A * A$ и $A A$ * одновременно, не вычисляя сами произведения матриц. Эффективное распространение этого метода на произвольные матрицы простой структуры реализуется обобщенным методом вращениї.

Среди итерационных методов решения полной проблемы собственных значений значительную группу составляют степенные методы. Большинство их вычислительных алгоритмов укладывается в следующие схемы:

\[
\begin{aligned}
& A G=G_{1} S_{1} \quad A=L_{1} R_{1} \\
& \text {. . . . . или . . . . . } \\
& \dot{A} G_{k-1}=\dot{G}_{k} S_{k} \quad \dot{R}_{k-1} \dot{L}_{k-1}=\dot{L}_{k} R_{k}
\end{aligned}
\]

Здесь на каждом шаге матрица, стоящая в левой части равенства, раскладывается в произведение двух матриц. Пусть одна из них треугольная, а вторая унитарная или треугольная другого наименования. Тогда при нек-рых дополнительных предположениях матрицы $G_{k}^{-1} A G_{k}$ и $R_{k} L_{k}$ сходятся к квазитреугольной матрице, подобной матрице $A$. Как правило, порядки диагональных клеток квазитреугольной матрицы невеликі, поэтому полная проблема собственных значений для предельной матрицы решается достаточно просто.

Известно несколько методов такого типа. Одним из лучших среди них является $Q R-a$ л го р і т м (см. [7]). Вычислительные схемы степенных методов во многом совпадают с вычислительными схемами решения систем уравнений прямыми методами.

Исследование и классификация численных методов. Огромное количество численных методов Л. а. ставит актуальной задачей не столько создание новых, сколько исследование и классификацию существующих методов (одна из самых полных классификаций методов с точки зрения их математич. построения содержится в монографии [1]; описанию методов с точки зрения возможности их реализации на ЭВМ посвящены монографии [2], [3], [7]).

Первые фундаментальные работы по анализу устойчивости и ошибок округления в численных методах решенія задач Л. а. появились лишь в 1947-48 и посвящены исследованию обращения матриц и решению систем уравнений методами типа Гаусса. Практич. ценность этих результатов была невелика. Существенный сдвиг в изучении данного вопроса произошел в середине 60-х гг. (см. [3]), когда был сделан решающий шаг к анализу и оценке әквивалентных возмущений. Реально вычисленное решение нек-рой задачи стало рассматриваться как точное решение той же задачи, но с возмущенными входными данными. Это возмущение, наз. эквивалентным, полностью характеризует влияние ошибок округления. Исследовано большое кол-во методов с точки зрения мажорантной оценки нормы эквивалентного возмущения (см. [3], [7]).

При фіксированном вычислительном алгоритме и способе округления вся совокупность ошибок округления является однозначной векторной функцией $\varphi_{t}(A)$, зависящей от числа разрядов $t$, с к-рыми ведется счет, и от входных данных $A$. Главный член