системой $\left(x^{i}\right)$ на $B$ выражаются в виде

\[
\Omega_{\alpha}^{\beta}=\frac{1}{2} R_{\alpha i j}^{\beta} d x^{i} \wedge d x^{j} .
\]

Горизонтальное распределение определяется при этом диффференциальной системой $\omega_{\alpha}^{\beta}=0$ на $P$. 2-формы $\Omega_{\alpha}^{\beta}$ наз. ф о р м а м и к р и в и з ны. Согласно теореме о голономии они определяют группу голономии J. c.

3) Л. с. в р а с слоенн ом прост ранст в е связность, при к-рой касательные векторы горизонтальных крівых с началом в данной точке $y$ расслоенного пространства $E$ образуют векторное подпространство $\Delta_{y}$ в $T_{y}(E)$; Л. с. определяется горизонтальным распределением $\Delta: \quad y \mapsto \Delta y$.

Лит.: [1] Л и х н е p о в и ч А., Теория связностей в целом й группы голономии, пер. с франц., М., 1960; [2] К о b a-

![](https://cdn.mathpix.com/cropped/2023_07_08_65b7d9542852b43e9002g-1.jpg?height=57&width=831&top_left_y=685&top_left_x=117)
ЛИНЕЙАЯ СИСТЕМА - семейство эффективных

![](https://cdn.mathpix.com/cropped/2023_07_08_65b7d9542852b43e9002g-1.jpg?height=32&width=826&top_left_y=763&top_left_x=123)
гообразии,' параметризованное проективным пространством.

Пусть $X$ - неособое алгебраич. многообразие над полем $k, \mathscr{L}$ - обратимый пучок на $X, \Gamma(X$, $\mathscr{L})-$ пространство глобальных сечений пучка $\mathscr{L}$, а $L \subset \Gamma(X, \mathscr{L})$ - некоторое конечномерное подпространство. Если $\operatorname{dim} L>0$, то дивизоры, определяемые нулями сечений из $L$, линейно эквивалентны и әффективны. Л и н е й н о й с и с т е м о й наз. проективное пространство $|L|=\boldsymbol{P}(L)$ одномерных подпространств в $L$, параметризующее эти дивизоры. Если $\operatorname{dim} \Gamma(X, \mathscr{L})<\infty$, то Л. с. $|\Gamma(X, \mathscr{L})|$ наз. п о л н о й; она обозначается также $|L|$.

Пусть $s_{0}, \ldots, s_{n}$ - базис в $L$. Он определяет рациональное отображение $\varphi_{L}: X \rightarrow P^{n}$ по формуле

\[
x \mapsto\left(s_{0}(x), \ldots, s_{n}(x)\right), \quad x \in X .
\]

Обычно говорят, что $\varphi_{L}$ задано Л. с. $|L|$. Образ $\varphi_{L}(X)$ не лежит ни в какой гиперплоскости в $\boldsymbol{P}^{\boldsymbol{n}}$ (см. [2]). Обратно, каждое рациональное отображение $\psi: X \rightarrow$ $\overrightarrow{P^{m}}$, обладающее этим свойством, задается нек-рой J. с.

Н е под ви н о й компоненто й Л. с. $|L|$ наз. такой эффективный дивизор $D^{*}$ на $X$, что $D=D^{\prime}+$ $+D *$ для любого $D \in|L|$, где $D^{\prime}-$ эффективный дивизор. Когда $D$ пробегает Л. с. $|L|$, дивизоры $D^{\prime}$ образуют нек-рую Л. с. $\left|L^{\prime}\right|$ той же размерности, что и J. с. $|L|$. Отображение $\varphi_{L^{\prime}}$ совпадает с $\varphi_{L}$. Поэтому при рассмотрении отображения $\varphi_{L}$ можно предполагать, что Л. с. $|L|$ не имеет неподвижных компонент. В этом случае $\varphi_{L}$ не определено в точности на базисном множестве Л. с. $|L|$.

П р и м е р ы. 1) Пусть $\boldsymbol{X}=\boldsymbol{P}^{2}$ и $\mathscr{L}=\widehat{G} p^{2}(d), d \geqslant 1$, тогда сечения $\Gamma\left(p^{2}, \widehat{G} p^{2}(d)\right)$ отождествляются с формами степени $d$ на $P^{2}$, а полная Л. с. $\left|\oint^{2}(d)\right|-$ с множеством всех кривых степени $d$.

2) Стандартное квадратичное преобразование $\tau$ : $P^{2} \rightarrow P^{2}$ (см. Кремоново преобразование) задается Л. с. коник, проходящих через точки $(0,0,1),(0,1,0)$, $(1,0,0)$

3) Инволюция Гейзера $\alpha: P^{2} \rightarrow P^{2}$ задается Л. с. кривых степени 8 , проходящих с кратностью 3 через 7 точек в общем положении.

4) Инволюция Бертини $\beta: P^{2} \rightarrow P^{2}$ задается Л.с. кривых степени 17, проходящих с кратностью 6 через 8 точек в общем положении.

Лит.: [1] Алгебраические поверхности, М., 1965 (Тр. Матем. ин-та АН CCCP, т. 75); [2] M а м Ф о р д Д., Лекции о

![](https://cdn.mathpix.com/cropped/2023_07_08_65b7d9542852b43e9002g-1.jpg?height=62&width=822&top_left_y=2248&top_left_x=134)

ЛИНЕИНАЯ СИСТЕМА ДИФФЕРЕНЦИАЛЬНЫХ УРАВНЕНИЙ С ПЕРИОДИЧЕСКИМИ КОӘФФИЦИЕНТАМИ - система $n$ линейных диффферендиальных уравнений вида

\[
\begin{aligned}
& \frac{d x_{1}}{d t}=\alpha_{11}(t) x_{1}+\ldots+\alpha_{1 n}(t) x_{n}, \\
& \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \\
& \frac{d x_{n}}{d t}=\alpha_{n 1}(t) x_{1}+\ldots+\alpha_{n n}(t) x_{n},
\end{aligned}
\]

где $t$ - действительная переменная, $\alpha_{j h}(t), x_{h}=x_{h}(t)-$ комплекснозначные функции, причем

\[
\alpha_{j h}(t+T)=\alpha_{j h}(t) \text { для любых } j, h \text {. }
\]

Число $T>0$ наз. пе р и одом к о эфф ици е нт о в системы (1). Систему (1) удобно записывать в виде одного векторного уравнения

\[
\frac{d x}{d t}=A(t) x
\]

где

$x^{T}=\left(x_{1}, \ldots, x_{n}\right), \quad A(t)=\left\|\alpha_{j h}(t)\right\|, \quad j, h=1, \ldots, n$.

Предполагается, что функции $\alpha_{j h}(t)$ определены для $t \in \mathbb{R}$, измеримы и интегрируемы по Лебегу на $[0, T]$ и почти всюду выполнены равенства (2), т. е. $A(t+T)=$ $=A(t)$. Решение уравнения $(3)$ - вектор-функция $x=$ $=x(t)$ с абсолютно непрерывными компонентами такая, что (3) выполнено почти всюду. Пусть $t_{0} \in \mathbb{R}, a-$ заданные (произвольно) число и вектор. Сушествует и определяется единственным образом решение $x(t)$, удовлетворяюшее условию $x\left(t_{0}\right)=a$. Матрица $X(t)$ порядка $n$ с абсолютно непрерывными әлементами наз. м а т р иц а н т о (или ә в о юцион ной ма тр и ц е й, или Коши матрицей) уравнения (3), если почти всюду на $\mathbb{R}$ выполняется равенство

\[
\begin{gathered}
\frac{d X}{d t}=A(t) X \\
X(0)=I,
\end{gathered}
\]

где $I$ - единичная $(n \times n)$-матрица. Матрицант $X(t)$ удовлетворяет соотношению

\[
X(t+T)=X(t) X(T), \quad t \in \mathbb{R} .
\]

Матрица $X(T)$ наз. м а т $\mathbf{p}$ и ц е й м о н о д $\mathbf{0}$ м и и, a eе собственные значения $\rho_{j}-$ м у л ь т и п л и к ат о р а и уравнения (3). Уравнение

\[
\operatorname{det}[X(T)-\rho I]=0
\]

для мультипликаторов $\rho_{j}$ наз. х а р а к т е р и с т ич е с ким у р а в н е и е м уравнения (3) (системы (1)). Каждому собственному вектору $a^{(0)}$ матрицы монодромии с мультипликатором $\rho_{0}$ соответствует решение $x^{(0)}(t)=X(t) a^{(0)}$ уравнения (3), удовлетворяющее условию

\[
x^{(0)}(t+T)=\rho_{0} x^{(0)}(t) .
\]

Имеет место те о р е м а Ф ло к е- Л я п у но в а: матрицант уравнения (3) с $T$-периодической матрицей $A(t)$ представим в виде

\[
X(t)=F(t) e^{t K},
\]

где $K$ - постоянная матрица, $F(t)$ - периодическая с периодом $T$, абсолютно непрерывная неособая для всех $t \in \mathbb{R}$ матрица-функция и $F(0)=I$. Обратно: если $F(t)$ и $K$ - матрицы с указанными свойствами, то матрица (5) является матрицантом нек-рого уравнения (3) с T-периодической матрицей $A(t)$. Матрица $K$, наз. показа тель ло й м а т р ц ц й, и матрица-функция $F(t)$ в представлении (5) определя-