Односвязная Ли р. г. всегда имеет точное конечномерное представление, для неодносвязных это не всегда так. В односвязной Ли р. г. произвольная связная подгруппа замкнута и односвязна [6]. Экспоненциальное отображение exp: $\mathfrak{g} \rightarrow G$ даже для односвязной Ли р. г. не обязано быть ни инъективным, ни сюръективным. Ји р. г., для к-рых $\operatorname{exp-диф-~}$ феоморфизм, наз. ә к с п о не н ц и а л ь н ы м и (см. Ли экспоненциальная группа). Односвязная Ли р. г. यифффеоморфна $\mathbb{R}^{N}$, а произвольная связная Ли р. г.$\mathbb{R}^{n} \times T^{m}$, где $T^{m}$ есть $m$-мерный тор.

Связная линейная Ли р. г. над $\mathbb{R}$ представляется в виде полупрямого произведения $K \cdot S$, где $K-$ комшактная абелева подгруппа, а $S$ - односвязный нормальный делитель. Алгебраическая связная разрешимая группа над любым полем характеристики 0 разлагается в полупрямое произведение нормального делителя, состоящего из унипотентных әлементов, и абелевой подгруппы, состоящей из полупростых әлементов [3]. Для связных Ли р. г. можно определить [4] аналог расщепления Мальцева.

Если алгебра Ли связной группы Ли $G$ треугольна (над $\mathbb{R})$, то $G$ наз. т р е у г о ль н о й. Для треугольных групп Ли справедлив аналог Ли теоремы о разрешимых алгебрах. Максимальные связные треугольные подгруппы в произвольной связной группе Ли сопряжены [5]. Связная треугольная группа Ли изоморфна подгруппе в $T(n, \mathbb{R})$ и является әкспоненциальной группой, если она односвязна.

Лum.: [1] Б у р б а к и Н., Группы и алгебры Ли. Алгеоры Ји, свободные алгебры Ли и группы Ли, пер. с франц., М., 1У76; [2], К а п л а н с к и й И., Введение в дифференциальную алгебру, пер. с англ., М., 1959; [3] Ш е в а л л е К., Теория групп Jи, пер. с франц., т. 3, M., 1958; [4] A u s l a n d e r L.,
«Bull. Amer. Malh. Soc.», 1973, v. 79, p. 227-61; [5] B и н 6 e p г Э. Б., "Докл. АН СССР", 1961, т. 141, c. $270-73$; [6] $\mathbf{M}$ а л ьц е в А. И., Избр. труды, т. 1, М., 1976, с. $177-200$.

ЛИ РЕДУКТИВНАЯ АЛГЕБРА - конечномерная алгебра Ли над полем $k$ характеристики 0 , присоединенное представление к-рой вполне приводимо. Свойство редуктивности алгебры Ли $g$ равносильно любому из следующих свойств:

1) радикал $\mathfrak{r}(g)$ алгебры Ли q совпадает сцентром 子( q);

2) $q=\jmath(g) \frac{i}{i} q_{0}$, где $q_{0}$ - полупростой идеал в п;

3) $\mathfrak{g}=\sum_{i=1}^{k} g_{i}$, где $g_{i}$ - простые идеалы;

4) g допускаст точное вполне приводимое конечномерное линейное представление.

Свойство редуктивности алгебры Ли сохраняется как при расширении, так и при сужении основного поля $k$.

Важный класс Ли р. а. над $k=\mathbb{R}$ составляют компактные алгебры Ли (см. Ли колиактиал әруппа). Группу Ли, алгебра Ли к-рой редуктивна, часто наз. р е д у к т в но й г р у п по й Л и. Если $k$ алгебраически замкнуто, то алгебра Ли над $k$ является редуктивной тогда и только тогда, когда она изоморфна алгебре Ли нек-рой редуктивной алгебраич. группы над $k$.

Обобщением понятия Ли р. а. является следующее понятие. Подалгебра $\mathfrak{h}$ понечномерной алгебры Ли q над $k$ наз. р е д у к т в но й в $q$, если присоединенное представление аd: $\mathfrak{h} \rightarrow \mathfrak{q l}(\mathfrak{q})$ вполне приводимо. В этом случае $\mathfrak{h}$ будет Ли р. а. Если $k$ алгебраически замкнуто, то для редуктивности подалгебры $\mathfrak{h}$ в $\mathfrak{g}$ неободимо и достаточно следующее условие: ad $\mathfrak{r}(\mathfrak{h )}$ состоит из полупростых линейных преобразованІй.

Лum.: [1] С е p p Ж.- П., Алгебры Ли и группы Ли, пер.

![](https://cdn.mathpix.com/cropped/2023_07_08_c7230b92bc7165758617g-1.jpg?height=37&width=831&top_left_y=2213&top_left_x=119)
ЛИ СВОБОДНАЯ АЛГЕБРА н а д к о лі ц о м $R$ - алгебра Ли $L=L(X)$ над $R$, в к-рой выделено свободное порождающее множество $X$, любое отображение к-рого в произвольную алгебру $G$ над $R$ продолжается до гомоморфизма из $L$ в $G$. Мощность множества $X$ вполне определяет $L(X)$ и наз. ее р а н $г$ о м. Ли с. а. есть свободный $R$-модуль (о базисах к-рого см. Базисный коммутатор). Подалгебра $M$ Лі с. а. над полем сама является Ли с. а. (т е о р е м а III и рш о в а [1]). Если же $R=\mathbb{Z}$, то это верно лишь при условии, что $L / M$ - свободная абелева группа [2]. Конечно порожденные подалгебры в Ли с. а. нал полем образуют подрешетку в решетке всех подалгебр [3]. Установлены [4] канонич. связі Ли с. а. со свободными группами и свободными ассоциативными алгебрами.

Лum.: [1] III и p шо в А. И., «Матем. сб.», 1953, т. 33, № 2, c. 441 - 52; [2] W i t t E., "Math. Z.», 1956, Bd 64, S. 195

![](https://cdn.mathpix.com/cropped/2023_07_08_c7230b92bc7165758617g-1.jpg?height=50&width=829&top_left_y=645&top_left_x=992)
1937, Bd 177, S. 105-15. Ю. А. Бахтурин.

ЛИ СКОБКА - коммутатор векторных полей на дифференцируемом многообразии. Если интерпретировать векторные поля класса $C^{\infty}$ на дифференцируемом (класса $C^{\infty}$ ) многообразии $M$ как дифференцирования алгебры $F(M)$ функций класса $C^{\infty}$ на $M$, то Ли с. полей $X$ и $Y$ задается формулой

\[
\left[\begin{array}{ll}
X & Y
\end{array}\right] f=X(Y f)-Y(X f),
\]

где $f \in F(M)$. Совокупность всех векторных полей класса $C^{\infty}$ на $M$ является алгеброй Ли относительно Ли с. А. Л. Онищик.

ЛИ ТЕОРЕМА - 1) Ли т.- одна из трех классич. теорем теории групп Ли, описывающих связь $\pi_{u}$ локальной группы с ее алгеброй Ли. Ли т. составляют фундамент теории, развитой в 19 в. С. Ли (S. Lie) и его школой (см. [1]).

Пусть $G-r$-мерная вешественная әффективная локальная $Л$ и группа преобразований області $\Omega \subset \mathbb{R}^{n}$, $e$ - единица группы $G$ и пусть в локальных координатах в окрестности множества $\{e\} \times \Omega$ в $G \times \Omega$ действие группы $G$ на $\Omega$ задано набором аналитич. функций

\[
y_{i}=f_{i}\left(g_{1}, \ldots, g_{r} ; x_{1}, \ldots, x_{n}\right), i=1, \ldots, n, \quad \text { (1) }
\]

где $g=\left(g_{1}, \ldots, g_{r}\right) \in G, x=\left(x_{1}, \ldots, x_{n}\right) \in \Omega$ и $g(x)=y=$ $=\left(y_{1}, \ldots, y_{n}\right) \in \Omega$. Указанное действие определяет на $\Omega r$ аналитич. векторных полей

\[
X_{i}=\sum_{j=1}^{n} \xi_{i j}(x) \frac{\partial}{\partial x_{j}}, \quad i=1, \ldots, r
\]

где $\xi_{i j}(x)=\frac{\partial f_{j}}{\partial g_{i}}(e, x)$.

![](https://cdn.mathpix.com/cropped/2023_07_08_c7230b92bc7165758617g-1.jpg?height=40&width=787&top_left_y=1689&top_left_x=1033)
функции $f_{j}, j=1, \ldots, \quad n$, определяющие действие группы $G$, сами определяются по нек-рому вспомогательному набору аналитич. функций $\psi_{k i}(g), k, i=1$, . .., $r$, на $G$, удовлетворяющих условию

\[
\psi_{k i}(e)=\delta_{k i} \text {, }
\]

$\delta_{k i}$ - символ Кронекера. Точнее, $\left(\psi_{k i}(g)\right)$ - это матрица дифференциала правого сдвіга на группе $G$ на элемент $g^{-1}$ в точке $g$, а набор функций (1) - это в точности репіение системы уравнений

\[
\begin{gathered}
\frac{\partial f_{j}}{\partial g_{i}}(g, x)=\sum_{k=1}^{r} \xi_{k j}(f(g, x)) \psi_{k i}(g), i=1, \ldots, r ; \\
j=1, \ldots, n,
\end{gathered}
\]

удовлетворяющее начальным условиям $f_{j}(e, x)=x$,

![](https://cdn.mathpix.com/cropped/2023_07_08_c7230b92bc7165758617g-1.jpg?height=62&width=831&top_left_y=2220&top_left_x=990)
функций $\xi_{i j}(x)$ и $\psi_{k i}(g)$. А именно, $\xi_{i j}(x)$ удовлетво-