в точке $x$ есть скорость изменения ее в этой точке, т. е. предел

\[
\lim _{\Delta x \rightarrow 0} \frac{\Delta y}{\Delta x}=\lim _{\Delta x \rightarrow 0} \frac{f(x+\Delta x)-f(x)}{\Delta x}=f^{\prime}(x) .
\]

Если $y$ есть координата точки, движущейся по оси ординат в момент времени $x$, то $f^{\prime}(x)$ есть мгновенная скорость точки в момент времени $x$.

По знаку производной $f^{\prime}(x)$ судят о характере изменения $f(x)$ : если $f^{\prime}(x)>0\left(f^{\prime}(x)<0\right)$ на интервале $(c, d)$, то функция $f$ возрастает (убывает) на этом интервале. Если же функция $f$ в точке $x$ достигает локального экстремума (максимума или минимума) и имеет в этой точке производную, то последняя равна нулю в этой точке $f^{\prime}\left(x_{0}\right)=0$.

Равенство (1) можно заменить эквивалентным равенством

\[
\frac{\Delta y}{\Delta x}=f^{\prime}(x)+\varepsilon(\Delta x), \quad \varepsilon(\Delta x) \rightarrow 0, \quad \Delta x \rightarrow 0,
\]

или

\[
\Delta y=f^{\prime}(x) \Delta x+\Delta x \varepsilon(\Delta x),
\]

где $\varepsilon(\Delta x)$ есть бесконечно малая, когда $\Delta x \rightarrow 0$; т. е. если функция $f$ имеет производную в точке $x$, то приращение ее- в этой точке разлагается на два слагаемых. Из них первое

\[
d y=f^{\prime}(x) \Delta x
\]

есть линейная функция от $\Delta x$ (пропорциональная $\Delta x$ ), второе - стремится к нулю быстрее, чем $\Delta x$.

Величина (2) наз. дифференциалом функции, соответствующим приращению $\Delta x$. При малых $\Delta x$ можно считать $\Delta y$, приближенно равным $d y$ :

\[
\Delta y \approx d y .
\]

Приведенные рассуждения о дифференциале характерны для М. а. Они распространяются на функции многих переменных и на функционалы.

Напр., если функция

\[
z=f\left(x_{1}, x_{2}, \ldots, x_{n}\right)=f(x)
\]

от $n$ переменных имеет непрерывные частные производные в точке $x=\left(x_{1}, \ldots, x_{n}\right)$, то ее приращение $\Delta z$, coответствующее приращениям $\Delta x_{1}, \Delta x_{2}, \ldots, \Delta x_{n}$ независимых переменных, можно записать в виде

\[
\Delta z=\sum_{k=1}^{n} \frac{\partial f}{\partial x_{k}} \Delta x_{k}+\sqrt{\sum_{k=1}^{n} \Delta x_{k}^{2}} \varepsilon(\Delta x),
\]

где $\varepsilon(\Delta x) \rightarrow 0$ при $\Delta x \rightarrow 0$, то есть если все $\Delta x_{k} \rightarrow 0$. Здесь первый член в правой части (3) есть дифференциал $d z$ функции $f$. Он линейно зависит от $\Delta x=\left(\Delta x_{1}, \ldots\right.$, $\left.\Delta x_{n}\right)$, а второй член стремится к нулю при $\Delta x \rightarrow 0$ быстpee, чем $\Delta x$.

Пусть задан функционал (см. ст. Вариационное исчисление)

\[
J(x)=\int_{t_{0}}^{t_{1}} L\left(t, x, x^{\prime}\right) d t
\]

распространенный на классы $\mathfrak{W}$ функций $x(t)$, имеющих на отрезке $\left[t_{0}, t_{1}\right]$ непрерывную производную и удовлетворяющих граничным условиям $x\left(t_{0}\right)=x_{0}$, $x\left(t_{1}\right)=x_{1}$, где $x_{0}, x_{1}$ - данные числа; пусть, далее, $\mathfrak{m}_{0}$ - класс функций $h(t)$, имеющих непрерывную производную на $\left[t_{0}, t_{1}\right]$ и таких, что $h\left(t_{0}\right)=h\left(t_{1}\right)=0$. Очевидно, если $x(t) \in \mathbb{M}$ и $h(t) \in \mathbb{M}_{0}$, то $x(t)+h(t) \in \mathbb{M}$.

В вариационном исчислении доказывается, что при известных условиях на $L$ приращение функционала $\boldsymbol{J}(x)$ может быть записано в виде

$J(x+h)-J(x)=\int_{t_{0}}^{t_{1}}\left(\frac{\partial L}{\partial x}-\frac{d}{d t}\left(\frac{\partial L}{\partial x}\right)\right) h(t) d t+o(\|h\|)$ при $\|h\| \rightarrow 0$, где

\[
\|h\|=\max _{t_{0} \leqslant t \leqslant t_{1}}|h(t)|+\max _{t_{0} \leqslant t \leqslant t_{1}}\left|h^{\prime}(t)\right|,
\]

и, таким образом, второй член правой части (4) стремится к нулю быстрее, чем $\|h\|$, а первый член линейно зависит от $h \in \mathbb{M}_{0}$. Первый член в (4) наз. вариацией функционала и обозначается $\delta J(x, h)$.

Интеграл. Наряду с производной интеграл имеѐт фундаментальное значение в М. а. Различают неопределенный и определенный интегралы.

Неопределенный интеграл тесно связан с первообразной функцией. Функцию $F(x)$ наз. п е р в о о бр а 3 н о й от функции $f$ на интервале $(a, b)$, если на әтом интервале $F^{\prime}(x)=f(x)$.

Определенный интеграл (Римана) от функции $f$ на отрезке $[a, b]$ есть предел

\[
\lim \sum_{j=0}^{N-1} f\left(\xi_{j}\right)\left(x_{j+1}-x_{j}\right)=\int_{a}^{b} f(x) d x
\]

при $\max \left(x_{j+1}-x_{j}\right) \rightarrow 0$; здесь $a=x_{0}<x_{1}<\ldots<x_{N-1}<$ $<x_{N}=b$.

Если функция $f$ положительна и непрерывна на отрезке $[a, b]$, то интеграл от нее на этом отрезке равен площади фигуры, ограниченной кривой $y=f(x)$, осью $O x$ и прямыми $x=a, x=b$.

Класс интегрируемых по Риману функций содержит все непрерывные на $[a, b]$ функции и нек-рые разрывные функции. Но все они необходимо ограничены. Для неограниченных функций, растущих не очень быстро, а также для нек-рых функций, заданных на бесконечных интервалах, вводят так наз. несобственные интегралы, требующие для своего определения двойного перехода к пределу.

Понятие интеграла Римана для функции одного переменного распространяется на функции многих переменных (см. К ратный интеграл).

С другой стороны, потребности М. а. привели к обобщению интеграла совсем в другом направлении, имеется в виду Лебега интеграл или более общий ЛебегаCтилтьеса интеграл. Существенным в определении этих интегралов является введение для нек-рых множеств, называемых измеримыми, понятия их меры и на этом основании - понятия измеримой функции. Для измеримых функций и вводится интеграл ЛебегаСтилтьеса. При этом рассматривается широкий диапазон разных мер и соответствующих им классов измеримых множеств и функций. Это дает возможность приспособить тот или иной интеграл к определенной конкретной задаче.

Формула Ньютона - Лейбница. Между производной и интегралом имеется связь, выражаемая фо р м у-

![](https://cdn.mathpix.com/cropped/2023_07_08_c7c4bf62705bd1752148g-1.jpg?height=40&width=831&top_left_y=1729&top_left_x=989)

\[
\int_{a}^{b} f(x) d x=F(b)-F(a) .
\]

Здесь $f(x)$ непрерывная ніа $[a, b]$ функция, а $F(x)-\mathrm{ee}$ первообразная.

Формула и ряд Тейлора. Наряду с производной и интегралом важнейшим понятием (орудием исследования) в М. а. являются Тейлора борлула и Тейлора ряд. Если функция $f(x), a<x<b$, имеет в окрестности точки $x_{0}$ непрерывные производные до порядка $n$ включительно, то ее можно приблизить в әтой окрестности многочленом

$P_{n}(x)=f\left(x_{0}\right)+\frac{f^{\prime}\left(x_{0}\right)}{1 !}\left(x-x_{0}\right)+\ldots+\frac{f^{(n)}\left(x_{0}\right)}{n !}\left(x-x_{0}\right)^{n}$, наз. ее м н о г ч лен о м Т ейл о р а (степени $n$ ) по степеням $x-x_{0}$ :

\[
f(x) \approx P_{n}(x)
\]