$\mathscr{E}_{t}=\sigma\{\omega: X(s), s \leqslant t\}$. Тогда случайные величины $\tau(\omega)=\inf \{t \geqslant 0: X(t): \in B\}$

и

\[
\sigma(\omega)=\inf \{t>0: X(t) \in B\},
\]

т. е. моменты (первого и первого после +0 ) достижения (борелевского) множества $B$, являются М. м. (в случае $\{\cdot\}=\varnothing$ полагают $\inf \varnothing=\infty)$.

2) Если $W(t), \quad t \geqslant 0,-$ стандартный винеровский процесс, то М. м.

\[
\tau=\inf \{t \geqslant 0: W(t) \geqslant a\}, \quad a>0,
\]

имеет плотность распределения вероятностей

\[
p(t)=\frac{a}{\sqrt{2 \pi} t^{3 / 2}} e^{-a^{2} / 2 t} .
\]

При этом $P\{\tau<\infty\}=1$, но $E \tau=\infty$.

3) Случайная величина

\[
\gamma=\inf \{t>0: X(s) \in B, \quad s \geqslant t\}
\]

являющаяся первым моментом, после к-рого процесс $X_{t}$ оетается в множестве $B$, является примером немарковского момента (случайной величины, зависящей от «будущего»).

С помощью понятия М. м. формулируется строго марковское свойство марковских процессов. М. М. и мом о ты ост а нов к и (т. е. конечные М. м.) играют важную роль в общей теории случайных процессов и статистическом последовательном анализе.

Лит.: [1] Г их ма а И. И., С к о р о х о д А. В., Теория случайных процессов, т. 2, М., 1973. A. Н. Ширяев.

МАРКОВСКИЙ ПРОЦЕСС, П р о ц е с с б е 3 п ос л е д е й с т в и я,- случайный процесс, әволюция к-рого после любого заданного значения временного параметра $t$ не зависит от эволюции, предшествовавшей $t$, при условии, что значение процесса в этот момент фиксировано (короче: "будущее» и «прошлое» процесса не зависят друг от друга при известном "настоящем»).

Определяющее М. п. свойство принято наз. м а рк о в с к и м; впервые оно было сформулировано А. А. Марковым [1]. Однако уже в работе Л. Башелье [2] можно усмотреть попытку трактовать броуновское движение как М. п., попытку, получившую обоснование после исследований Н. Винера (N. Wiener, 1923). Основы общей теории М. п. с непрерывным временем были заложены А. Н. Колмогоровым [3].

Марковское свойство. Имеются существенно отличающиеся друг от друга определения М. п. Одним из наиболее распространенных является следующее. Пусть на вероятностном пространстве $(\Omega, F, \mathrm{P})$ задан случайный процесс $X(t), t \in T$, со значениями из измеримого пространства ( $E, \mathscr{B})$, где $T$ - подмножество действительной оси $\mathbb{R}$. Пусть $N_{t}$ (соответственно $N^{t}$ ) есть $\sigma$-алгебра в $\Omega$, порожденная величинами $\boldsymbol{X}(s)$ при $s \leqslant t(s \geqslant t)$, где $s \in T$. Другими словами, $N_{t}$ (соответственно $N^{t}$ ) - это совокупность событий, связанных с әволюцией процесса до момента $t$ (начиная с $t$ ). Процесс $X(t)$ наз. м а р к о в с к и м п роц е с с о м, если (почти наверное) для всех $t \in T, \Lambda_{1} \in N_{t}$ и $\Lambda_{2} \in N^{t}$ выполняется м а р к о в с к о е с в ой с т в о :

\[
\mathrm{P}\left\{\Lambda_{1} \Lambda_{2} \mid X(t)\right\}=\mathrm{P}\left\{\Lambda_{1} \mid X(t)\right\} \mathrm{P}\left\{\Lambda_{2} \mid X(t)\right\}
\]

или, что то же самое, если для любых $t \in T$ и $\Lambda \in N^{t}$

\[
\mathrm{P}\left\{\Lambda \mid N_{t}\right\}=\mathbf{P}\{\Lambda \mid X(t)\} .
\]

М. п., для к-рого $T$ содержится в множестве натуральных чисел, наз. Маркова цепью (впрочем, последний термин чаще всего ассоциируется со случаем не более qем счетного $E$ ). Если $T$ является интервалом в $\mathbb{R}$, а $E$ не более чем счетно, М. П. наз. це п ь ю М а рко в а с н е п ре рывным времен е м. Примеры М. п. с непрерывным временем доставляются дифффузионными процессами і процессами с независимыми приращениями, в том числе пуассоновским и винеровским.

В дальнейшем для определенности речь будет идти только о случае $T=[0, \infty)$. Формулы (1) и (2) дают ясную интерпретацию принципа независимостіл «Iрошлого" и «будущего" при известном «настоящем», но основанное на них определение М. п. оказалось недостаточно гібким в тех многочисленных сітуациях, когда приходится рассматривать не одно, а набор условий типа (1) или (2), отвечающих различным, хотя и согласованным определенным образом, мерам P. Такого рода соображения привели к принятіпо следующего определения (см. [9], [11]).

Пусть заданы:

a) измеримое пространство $(E, \mathscr{B})$, где $\sigma$-алгебра $\mathscr{B}$ содержит все одноточечные множества в $E$;

б) измеримое пространство $(\Omega, F)$, снабженное семейством $\sigma$-алгебр $F_{t}^{s} \subset F, 0 \leqslant s \leqslant t \leqslant \infty$, таких, что $F_{t}^{s} \subset F_{v}^{u}$, если $[s, t] \subset[u, v]$

в) функция («траектория») $x_{t}=x_{t}(\omega)$, определяющая при любых $t \in[0, \infty)$ и $v \in[0, t]$ измеримое отображение $\left(\Omega, F_{t}^{v}\right)$ в $(E, \mathscr{B})$;

г) для каждых $s \geqslant 0$ и $x \in E$ вероятностная мера $\mathrm{P}_{s, x}$ на $\sigma$-алгебре $F_{\infty}^{s}$ такая, что функция $\boldsymbol{P}(s, \ldots ; t, B)=$ $=\mathrm{P}_{s,} .\left\{x_{t} \in B\right\}$ измерима относительно $\mathscr{B}$, если $s \in[0, t]$ и $B \in \mathscr{B}$.

Набор $X(t)=\left(x_{t}, F_{t}^{s}, \mathrm{P}_{s, x}\right)$ наз. (н $\mathbf{e}$ о б $\mathrm{p}$ ы в а ющи м с я) м а р ко в скй проце с с о м, заданным в $(E, \mathscr{B})$, если $\mathrm{P}_{s,} x^{- \text {почти наверное }}$

\[
\mathrm{P}_{s, x}\left\{\Lambda \mid F_{t}^{s}\right\}=\mathrm{P}_{t, x_{t}}\{\Lambda\}
\]

каковы бы ни были $0 \leqslant s \leqslant t$ и $\Lambda \in N^{t}$. Здесь $\Omega-$ пространство элементарных событий, $(E$, $\mathscr{B})-$ фазовое пространство или пространство состояний, $\boldsymbol{P}(s, x, t$, $B)$ - переходная буунция или вероятность перехода процесса $X(t)$. Если $E$ наделено топологией, а $\mathscr{B}-$ совокупность борелевских множеств в $E$, то принято говорить, что М. п. задан в $E$. Обычно в определение М. П. включают требование, чтобы $\boldsymbol{P}(s, x ; s,\{x\}) \equiv 1$, и тогда $\mathrm{P}_{s, x}\{\Lambda\}$ с $\Lambda \in F_{\infty}^{s}$ истолковывается как вероятность $\Lambda$ При условии, что $x_{s}=x$.

Возникает вопрос: всякую ли марковскую переходную функцию $\boldsymbol{P}(s, x ; t, B)$, заданную в измеримом пространстве $(E$, $\mathscr{B})$, можно рассматривать как переходную функцию нек-рого М. п. Ответ положителен, если, напр., $E$ является сепарабельным локально компактным пространством, а $\mathscr{B}-$ совокупностью борелевских множеств в $E$. Более того, пусть $E-$ полное метрич. пространство и пусть

\[
\lim _{h \downarrow 0} \alpha_{\mathcal{E}}(h)=0
\]

для любого $\varepsilon>0$, где

$\alpha_{\mathcal{E}}(h)=\sup \left\{P\left(s, x ; t t V_{\mathcal{E}}(x): x \in E, \quad 0<t-s<h\right\}\right.$,

a $V_{\varepsilon}(x)$ - дополнение $\varepsilon$-окрестности точкі $x$. Тогда соответствующий М. п. можно считать непрерывным справа и имеющим пределы слева (т. е. таковыми можно выбрать его траектории). Существование же непрерывного М. п. обеспечивается условием $\alpha_{\varepsilon}(h)=$ $=o(h)$ при $h \downarrow 0$ (см. [9], [11]).

В теории М. П. основное внимание уделяется однородным (по времени) процессам. Соответствующее определение предполагает заданной систему объектов a) - г) с той разницей, что для фигурировавших в