Лum.: [1] Л я п у н о в А. М., Собр. соч., т. 2, М.- ЈI., 1956, с. 7-263; [2] Б ы ло в Б. Ф., В ин о г р а д Р. Э.,
Г ро б м а н Д. М., Н е м ы ц к и й В. В., Теория показателей Ляпунова и ее приложения к вопросам устойчивости, М., 1966; [3] Итоги науки и техники. Математический анализ, т. 12, М., 1974, с. 71-146. B. М. Миллионщиков. ЛНПУНОВА - IIМДТА УРАВНЕНИЕ - нелинейное интегральное уравнение вида

\[
\begin{gathered}
u(x)-\int_{\Omega} K(x, s) u(s) d s=U_{01}\left(\begin{array}{l}
x \\
v
\end{array}\right)+ \\
+\sum_{m+n \geqslant 2} U_{m n}\left(\begin{array}{c}
x \\
u, v
\end{array}\right), \quad x \in \Omega,
\end{gathered}
\]

где

\[
\begin{aligned}
U_{01}\left(\begin{array}{l}
x \\
v
\end{array}\right) & =K_{0}(x) v(x)+\int_{\Omega} K_{1}(x, s) v(s) d s, \\
U_{m n}\left(\begin{array}{c}
x \\
u, v
\end{array}\right) & =\sum_{v=1}^{n_{i}} \int_{\Omega} \ldots \int_{\Omega} K^{(v)}\left(x, s_{1}, \ldots, s_{i}\right) \times
\end{aligned}
\]\[
\times u^{\alpha_{0}}(x) u^{\alpha_{1}}\left(s_{1}\right) \ldots u^{\alpha_{i}}\left(s_{i}\right) v^{\beta_{0}}(x) v^{\beta_{1}}\left(s_{1}\right) \ldots v^{\beta_{i}}\left(s_{i}\right) d s_{1} \ldots d s_{i} \text {, }
\]\[
\alpha_{0}, \alpha_{1}, \ldots, \alpha_{i}, \beta_{0}, \beta_{1}, \ldots, \beta_{i} \text { - неотрицательные це- }
\]
лые числа,

\[
\alpha_{0}+\alpha_{1}+\ldots+\alpha_{i}=m, \quad \beta_{0}+\beta_{1}+\ldots+\beta_{i}=n,
\]

$\Omega$ - ограниченное замкнутое множество конечномерного евклидова пространства, $v$ и функции $K$ - заданные вепрерывные функции своих аргументов $x, s, s_{1}$, ..., $s_{i} \in \Omega, u$ - искомая функция. Сумма, входящая в правую часть равенства (1), может быть конечной или представлять бесконечный ряд. В последнем случае ряд наз. ин т е г p о-с т е пе н ны м р я д о м от двух функциональных аргументсв. Предполагается, что әтот ряд сходится абсолютно и равномерно.

Если единица не является характеристич. числом ядра $K(x, s)$, то уравнение (1) при достаточно малом $|v(x)|$ в классе непрерывных функций имеет единственное малое решение, представимое в виде интегро-степенного ряда. Случай, когда единица есть характеристич. число ядра $K$, является более сложным. В этом случае строится нек-рая система уравнений - у р а вне ни е р а в в е т в ления:

\[
\omega_{k}\left(\xi_{1}, \xi_{2}, \ldots, \xi_{n}, v\right)=0, k=1, \ldots, n,
\]

где $\omega_{k}$ - известные степенные ряды, $n$-кратность характеристич. числа 1. Система (2) в общем случае имеет неединственное решение. Какова бы ни была фиксированная достаточно малая функция $v$, каждому малому непрерывному решению системы (2) (непрерывное решение системы (2) наз. малым, если $\left.\xi_{i}(0)=0\right)$ соответствует малое решение уравнения (1), представимое в виде интегро-степенного ряда.

Уравнение типа (1) впервые было рассмотрено А. М. Ляпуновым в 1906 , а позднее - в более общем виде - Э. ШІмидтом (Е. Schmidt, 1908).

Лum.: [1] В а й н б е р г M. М., Т р е н о г и н В. А., Теория ветвления решений нелинейных уравнений, М., 1969; [2] $\begin{array}{ll}\text { С м и р н о в Н. С., Введение в теорию нелинейных интеграль- } \\ \text { ных уравнений, Ј.- М., 1936. } & \text { Б. В. Хведелидзе. }\end{array}$