Другие варианты Л. м. связаны с рассмотрением разрывных уравнений: во многих ситуациях разрывы описываются с помощью нестационарного варианта Л. м. и распространяются вдоль лучей. На нестационарном аналоге Л. м. основан т. н. метод Адамара исследования задачи Коши линейных гиперболич. уравнений 2-го порядка и его обобщения на системы линейных гиперболических дифференциальных и псевдолифференциальных уравнений.

Лum.: [1] Б а б и ч B. М., Б у л ды р е в B. С., Асимптотические методы в задачах дифракции коротких волн, М., 1972; англ., М., 1977; [3] Б'о р о в и ко в В. А., К и н б е р Б. Е., англ., М., 1977; [3] Бо р о в ик о в В. А., К и н б е р Б. Е.,
Геометрическая теория дифракции, М., 1978. В. М. Бабич.

ЛЬЕНАРА УРАВНЕНИЕ - нелинейное обыкновенное дифференциальное уравнение 2-го порядка

\[
x^{\prime \prime}+f(x) x^{\prime}+x=0 .
\]

Это уравнение описывает динамику системы с одной степенью свободы при наличии линейной восстанавливающей силы и нелинейного затухания. Если функция $f(x)$ обладает следующим свойством:

\[
\begin{array}{ll}
f(x)<0 & \text { при малых }|x|, \\
f(x)>0 & \text { при больших }|x|,
\end{array}
\]

т. е. если при малых амплитудах система поглощает энергію, а при больших происходит диссипация, то в системе можно ожидать самовозбуждение колебаний (вознікновение автоколебаний). Впервые достаточные условия возникновения автоколебаний в системе (*) доказал А. Льенар [1].

Л. у. тесно связано с Рәлея уравнением. Важным частным случаем Л. у. является Ван дер Поля уравнение. Вместо уравнения (*) часто удобно рассматривать систему

\[
x^{\prime}=v, v^{\prime}=-x-f(x) v
\]

(автоколебательному процессу в системе (*) адекватен устойчивый предельный цикл на фазовой плоскости $x, v)$ или әквивалентное ей уравнение

\[
\frac{d v}{d x}=\frac{-x-f(x) v}{v} .
\]

Если ввести новую переменную $y=x^{\prime}+F(x)$, где $F(x)=$ $=\int_{0}^{x} f(\xi) d \xi$, то уравнение (*) переходит. в систему

\[
x^{\prime}=y-F(x), y^{\prime}=-x .
\]

Более общими, чем Л. у., являются уравнения

\[
\begin{gathered}
x^{\prime \prime}+f(x) x^{\prime}+g(x)=0, \\
x^{\prime \prime}+\varphi\left(x, x^{\prime}\right) x^{\prime}+g(x)=0 .
\end{gathered}
\]

Основной интерес представляет выяснение возможно более широких достаточных условий, при к-рых әти уравнения имеют единственное устойчивое периодич. решение. Подробно изучалось также неоднородное II. y.

\[
x^{\prime \prime}+f(x) x^{\prime}+x=e(t)
\]

и его обобщения.

Jum.: [1] L i é n a r d A., "Rev. gén. électr.", 1928, t. 23, p. 901-12, 946-54; [2] А н д р о н о в А. А., В и т т А. А., с о й е Д ж С. Э., Теория колебаний, 2 изд., М., 1959; [3] с а нс о н е Д ж., Обыкновенные дифференциальные уравнения, пер. pия дифференциальных уравнений, пер. с англ., М., 1961 ; венная теория нелинейных дифференциальных уравнений, пер. с нем., М., 1974 .

ЛЬЕНАРА - IIIПАРА КРИТЕРИЙ - модификация Рауса - Гурвица критерия, сводящая все вычисления в нем к вычислению главных миноров только четного (или только нечетного) порядка матрицы Гурвица.

Пусть дан многочлен

\[
f(x)=a_{0} x^{n}+a_{1} x^{n-1}+\ldots+a_{n}, \quad a_{0}>0,
\]

$H$ - его матрица Гурвица и $\Delta_{i}$ - ее главные миноры порядка $i, i=1,2, \ldots ., n$.

К р и т е р й из следующих четырех условий является необходимым и достаточным для того, чтобы все корни многочлена * с действительными коэфффциентами имеліи отрицательные действительные части:

1) $a_{n}>0, \quad a_{n-2}>0, \ldots, \Delta_{1}>0, \quad \Delta_{3}>0, \ldots$;

2) $a_{n}>0, \quad a_{n-2}>0, \ldots, \Delta_{2}>0, \quad \Delta_{4}>0, \ldots$;

3) $a_{n}>0, a_{n-1}>0, a_{n-3}>0, \ldots, \Delta_{1}>0$,

$\Delta_{3}>0, \ldots$;

4) $a_{n}>0, a_{n-1}>0, a_{n-3}>0, \ldots, \Delta_{2}>0$, $\Delta_{4}>0$, ...

Критерий установлен А. Льенаром и А. Шипаром [1].

Jum.: [1] L i é n a r d A., C h i p a r t H., "J. math. pures

![](https://cdn.mathpix.com/cropped/2023_07_08_58ac685803645f9d9b64g-1.jpg?height=39&width=826&top_left_y=680&top_left_x=995)

ЈНКСЕМБУРГА НОРМА - функция

\[
\|x\|_{(M)}=\inf \left\{\lambda: \lambda>0, \int_{G} M(\lambda-1 x(t) d t \leqslant 1\},\right.
\]

где $M(u)$ - четная выпуклая функция, возрастающая при положительных $U$,

\[
\lim _{u \rightarrow 0} u^{-1} M(u)=\lim u(M(u))^{-1}=0,
\]

$M(u)>0$ при $u>0, G$ - ограниченное замкнутое множество в $\mathbb{R}^{n}$. Свойства этой нормы были изучены В. Люксембургом [1]. Л. н. эквивалентна норме $\mathrm{Op}$ лича (см. Орлича пространство) и

\[
\|x\|_{(M)} \leqslant\|x\|_{M} \leqslant 2\|x\|_{(M)} .
\]

Если функции $M(u)$ и $N(u)$ дополнительны друг к другу (см. Орлича класс), то

\[
\|x\|_{M}=\sup \left\{\int_{G} x(t) y(t) d t:\|y\|_{(N)} \leqslant 1\right\} .
\]

Если $\chi_{E}(t)$ - характеристич. функция измеримого подмножества $E \subset G$, то

\[
\left\|\chi_{E}\right\|(M)=1 / M-1\left(\frac{1}{\operatorname{mes} E}\right)
\]

Jum.: [1] L u x e m b u r g W., Banach function spaces,

![](https://cdn.mathpix.com/cropped/2023_07_08_58ac685803645f9d9b64g-1.jpg?height=34&width=824&top_left_y=1469&top_left_x=997)
ки й Я. Б., Выпуклые функции и пространства Орлича, М.,
1958.

ЛЮРОТА ПРОБЛЕМА - проблема характеризации подполей поля рациональных функций.

В 1876 Ж. Люрот [1] (см. также [2]) доказал, что всякое подполе поля рациональных функций от одной переменной $k(x)$, содержащее поле $k$ и отличное от $k$, изоморфно полю $k(x)$ (т е о р е м а Л ю р о т а). Вопрос о том, верно ли аналогичное утверждение для подполей $R$ поля $k\left(x_{1}, \ldots, x_{n}\right), R \sqsupset k, R \neq k, n \geqslant 2$, известен как п р об л е м а Л ю р о т а.

Пусть $X$ - алгебраич. многообразие, являющееся моделью (см. Минимальная модель) поля $R$, тогда вложение $R=k(X) \subset k\left(x_{1}, \ldots, x_{n}\right)$ определяет рациональное отображение $f: P^{n} \rightarrow X$, образ к-рого плотен в $X$. Многообразия, для к-рых существует такое отображение на них проективного пространства, наз. у н и р ац и о на лі ьы ми. Р а ц и о на ль ны м и наз. многообразия, бирационально изоморфные $P^{m}$. На геометрич. языке Л. п. может быть сформулирована следующим образом: является ли всякое унирациональное многообразие $X$ рациональным? Без ограничения общности можно предполагать, что $\operatorname{dim} X=n$, т. е. что $\boldsymbol{R}$ имеет степень трансцендентности, равную $n$.

В случае $n=1$ положительное решение Л. п. для любого основного поля $k$ дает сформулированная выше теорема Люрота. Для $n=2$ и алгебраически замкнутого поля $k$ характеристики 0 проблема положи-