Функция $p(s, x, t, y)$ есть функция Грина уравнений (6) - (7), и первые известные способы построения диффузионных процессов были основаны на теоремах существования этой функции для диффференциальных уравнений (6) - (7). Для однородного по времени процесса оператор $L(s, x)=L(x)$ на гладких функциях совпадает с характеристич. оператором М. п. (см. Переходных операторов полугруппа).

Математич. ожидания различных функционалов от диффузионных процессов служат решениями соответствующих краевых задач для дифференциального уравнения (1). Пусть $\mathrm{E}_{s, x}(\cdot)-$ математич. ожидание по мере $\mathrm{P}_{s, x}$. Тогда функция $\mathrm{E}_{s, x} \varphi(X(T))=u_{1}(s, x)$ удовлетворяет прі $s<T$ уравнению (6) и условию $u_{1}(T, x)=\varphi(x)$.

Аналогично, функция

\[
u_{2}(s, x)=\mathrm{E}_{s, x} \int_{s}^{T} f(t, X(t)) d t
\]

удовлетворяет при $s<T$ уравнению

\[
\frac{\partial u_{2}}{\partial s}+L(s, x) u_{2}=-f(s, x)
\]

и условию $u_{2}(T, x)=0$.

Пусть $\tau-$ момент первого достижения границы $\partial D$ области $D \subset \mathbb{R}^{n}$ траекторией процесса $X(t), \quad \tau \wedge T=$ $=\min (\tau, T)$. Тогда при нек-рых условиях функция

\[
\begin{gathered}
u_{3}(s, x)=\mathrm{E}_{s, x} \int_{s}^{\tau \wedge T} f(t, X(t)) d t+ \\
+\mathrm{E}_{s, x}(\tau)(\tau \wedge T, X(\tau \wedge T))
\end{gathered}
\]

удовлетворяет уравнению

\[
\frac{\partial u}{\partial s}+L(s, x) u=-f
\]

и принимает значения $\varphi$ на множестве

\[
\Gamma=\{s<T, x \in \partial D\} \cup\{s=T, x \in D\} .
\]

Решение 1-ї краевоӥ задачи для общего линейного параболич. уравнения 2-го порядка

![](https://cdn.mathpix.com/cropped/2023_07_08_a41b4eb9aa245ed89faag-1.jpg?height=117&width=618&top_left_y=1348&top_left_x=217)

при довольно общих предположениях может быть записано в виде

\[
\begin{gathered}
u(s, x)=\mathrm{E}_{s, x} \int_{s}^{\tau \wedge T} \exp \left\{\int_{s}^{v} c(t, X(t)) d t\right\} \times \\
\times f(v, X(v)) d v+\mathrm{E}_{s, x}\left\{\exp \left\{\int_{s}^{\tau \wedge T} c(t, X(t)) d t\right\} \times\right. \\
\times \varphi(\tau \wedge T, X(\tau \wedge T))\} .
\end{gathered}
\]

В случае, когда оператор $L$ и функции $c, f$ не зависят от $s$, аналогичное (9) представление возможно и для решения линейного эллиптич. уравнения. Точнее, функция

\[
\begin{aligned}
u(x) & =\mathrm{E}_{x} \int_{0}^{\tau} \exp \left\{\int_{0}^{v} c(X(t)) d t\right\} f(X(v)) d v+ \\
& +\mathrm{E}_{x}\left\{\exp \left\{\int_{0}^{\tau} c(X(t)) d t\right\} \varphi(X(\tau))\right\}
\end{aligned}
\]

при нек-рых предіоложениях есть решение задачи

\[
L(x) u+c(x) u=-f(x),\left.\quad u\right|_{\partial D}=\varphi .
\]

В случае, когда оператор $L$ вырождается $(\operatorname{det} b(s, x)=0$ ) или граница $\partial D$ недостаточно "хорошая", граничные значения могут и не приниматься функциями (9), (10) в отдельных точках или на целых множествах. Понятие регулярной граничной точки для оператора $L$ имеет вероятностную интерпретацию. В регулярных точках границы граничные значения достигаются функциями (9), (10). Решение задач (8), (11) позволяет изучать свойства соответствующих диффузионных процессов и функционалов от них.

Существуют методы построения М. п., не опирающиеся на построение решений уравнений $(6),(7)$, напр. метод стохастических дибберенциальных уравненици, абсолютно непрерывная замена меры и др. Это обстоятельство вместе с формулами (9), (10) позволяет вероятностным путем строить и изучать свойства краевых задач для уравнения (8), а также свойства решений соответствующего эллиптич. уравнения.

Так как решение стохастического дифференциального уравнения нечувствительно к вырождению матрицы $b(s, x)$, то вероятностные методы применялись для построения решений вырождающихся әллиптическігх и параболических дифференциальных уравнений. Распространение принципа усреднения Н. М. Крылова и Н. Н. Боголюбова на стохастические дифференциальные уравнения позволило с помощью (9) получить соответствующие результаты для эллиптических II параболических диффференциальных уравнений. Нек-рые трудные задачи исследования свойств решений уравнений такого типа с малым параметром при старшей производной оказалось возможным решить с помощью вероятностных соображений. Вероятностный смысл имеет и решение 2-й краевой задачи для уравнения (6). Постановка краевых задач для неогрангченной области тесно связана с возвратностью соответствующего дифффузионного процесса.

В случае однородного по времени процесса ( $L$, не завислт от $s$ ) положительное решение уравнения $L * q=0$ с точностью до мультипликатівной постоянной совпадает при нек-рых предположениях со стационарноі́ плотностью распределения М. П. Вероятностные соображения оказываются полезными и при рассмотрении краевых задач для нелинейных параболич. уравнений.
Р. З. Хасъминский.

Лum.: [1] М а p к о в А. А., "Изв. физ.-мат. об-ва Казан.

![](https://cdn.mathpix.com/cropped/2023_07_08_a41b4eb9aa245ed89faag-1.jpg?height=50&width=831&top_left_y=1292&top_left_x=984)
"Ann. scient. Ecole norm. supér.», 1900, v. 17, p. $21-86 ;[3]$
K о л м о г о p o в A. H., "Math. Ann.", 1931, Bd $104, \mathrm{~S} .415]$ 458; рус. пер. "Успехи матем. наук», 1938, в. 5, с. 5-41; [4] ч ж у н $\mathbf{K}$ а й - л а й, Однородные цепи Маркова, пер. с англ., [6] Д ы н и н Е. Б., Ю Іі к е в и ч А. А., "Теория вероятн.

![](https://cdn.mathpix.com/cropped/2023_07_08_a41b4eb9aa245ed89faag-1.jpg?height=50&width=826&top_left_y=1434&top_left_x=981)
Марковские процессы и потенциалы, пер. с англ., М., 1962 ; [8] Д е л л а ш е ри К., Емкости и случайпые процессы, пер. с франц., М., 1975; [9] Д ы н к и н Е. Б., Основания теории марковских процессов, М., 1959; [10] е г о ж е, Марковские Теория случайных процессов, т. 2 , М., $1973 ;$ [12] $\Phi$ р е й дл и н М. И., в кн.: Итоги науки. Теория вероятностей, математическая статистика. - Теоретическая кибернетика. $1966, \mathbf{M}$. 1967 , с. 7-58; [13] Х а с ь м и н с к и й Р. 3., «Теория нероятн.

![](https://cdn.mathpix.com/cropped/2023_07_08_a41b4eb9aa245ed89faag-1.jpg?height=42&width=821&top_left_y=1676&top_left_x=989)
под действием малых случайных возмущений, M., 1979; [15] B l um e n t h a l R. M., G e t o o r R. K., Markov processes Markov processes: Ray processes and right processes, B., 1975 ; [17] К у н ец о в С. F., «Теория вероятн. и ее примен.»,

![](https://cdn.mathpix.com/cropped/2023_07_08_a41b4eb9aa245ed89faag-1.jpg?height=47&width=814&top_left_y=1832&top_left_x=990)
марковский процесс, являющийся стационарны.и случайным прочессом. М. с. П., отвечающий однородной марковской переходной функции, существует тогда и только тогда, когда существует стационарное начальное распределение $\mu(A)$, отвечающее этой функции, т. е. $\mu(A)$ удовлетворяет уравнению

\[
\mu(A)=\int_{X} \mathrm{P}(x, t, A) \mu(d x) .
\]

Если фазовое пространство процесса $X$ - конечное множество, то стационарное начальное распределение существует всегда, независимо от того, рассматривается процесс с дискретным $(t=0,1,2, \ldots)$ или непрерывным временем. Для процесса с дискретным временем и счетным множеством $X$ условие существования