Пусть $V-$ любая область внутри единичного круга $D=\{z:|z|<1\}$ плоскости комплексного переменного $z$, примыкающая к нек-рой дуге $\sigma$ единичной окружности $\Gamma=\{z:|z|=1\}$, a

\[
w=f(z)=\sum_{k=0}^{\infty} c_{k} z^{k}
\]

- регулярная аналитич. функция в D. Тогда, если́ площадь римановой поверхности, являющейся образом области $V$ при отображении $w=f(z)$, конечна, то ряд

\[
\sum_{k=0}^{\infty} c_{k} z^{k}
\]

сходится почти всюду на дуге $\sigma$.

В связи с этой теоремой Н. Н. Лузин сформулировал гипотезу, известную также как п р о б л е м а Л у з ин а. Точку $e^{i \theta_{0}} \in \Gamma$ наз. т оч к о й Л у з и на функции $w=f(z)$, если $w=f(z)$ отображает каждый круг, изнутри касающийся $\Gamma$ в точке $e^{i \theta_{0}}$, на область бесконечной площади на римановой поверхности функции $w=f(z)$. Гип о т е з а Л у з и на состоит в том, что сушествуют ограниченные аналитич. функции в $D$ такие, что каждая точка $\Gamma$ является для них точкой Лузина. Гипотеза Лузина впервые была подтверждена полностью в 1955 (см. [3]).

Лum.: [1] Л у з и н Н. Н., "Докл. АН ССCР", 1947, т. 56, № 5, c. 447-50; [2] е г о же, Собр. соч., т. 1, M., 1953, c. $318-30$; ский анализ, т. 10 , М., 1973 , с. $99-259$.

2) Л. Т. в бескриттной теории дололенцев. 2) Ј1. т. в дескриптивной теории множеств можно условно разбить на три цикла. Первый и основной цикл направлен на изучение әффективных множеств (аналитических, борелевских, лузинских (проективных) множеств). Сюда относится Лузина принципы отделимости и теорема о существовании Лузина множеств любого класса. Второй цикл представляет собой изучение задач, лежащих на пути к решению континуум-гипотезы и проблемы мощности $C A$-множеств. Здесь выделяется теорема Лузина-Серпиньского о разбиении отрезка на N1 борелевских множеств, к-рое определяется соответствующим Лузина решетом, а также JI. т. о покрытии: пусть $E$ и $A$ - непересекающиеся аналитич. множества и

\[
E \subset X \backslash A=\bigcup_{\alpha<\omega_{1}} A_{\alpha}
\]

- разложение множества $X \backslash A$ на конституанты, тогда существует такой индекс $\alpha_{0}<\omega_{1}$, что

\[
E \subset \cup_{\alpha<\alpha_{0}} A_{\alpha}
\]

Третий цикл содержит результаты, полученные с использованием аксиомы выбора. Сюда же примыкают философские работы по теории множеств. Здесь выдеЛяются Л. т. о существовании несчетного множества 1-й категории на всяком совершенном множестве, о разбиении интервала на несчетное множество неизмеримых множеств. Завершает этот цикЛ Л. т. о частях натурального ряда, отражающие нек-рые свойства нароста $\beta N \backslash N$ Cтоуна- Чеха бикомпактного расширения $\beta N$ натурального ряда $N$.

Лит.: [1] Л у з и н Н. Н., Собр. соч., т. 2, М., 1958.

ЛУЗИНА - ДАНЖУА ТЕОРЕМА - см. Аан Ефимов. Лузина теорема.

ЛУЗИНА - ПРИВАЛОВА ТЕОРЕМЫ в т е о р и и функций комплексного перемен ногоклассические результаты Н. Н. Лузина и И. И. Привалова, выясняющие характер граничного единственности свойства аналитич. функций (см. [1]).

1) Пусть $f(z)$ - мероморфная функция комплексного переменного $z$ в односвязной области $D$ со спрямляемой границей Г. Если $f(z)$ принимает угловые граничные значения нуль на множестве $E \subset \Gamma$ положительной меры Лебега на $\Gamma$, то $f(z) \equiv 0$ в $D$. Не существует мероморфной в $D$ функции, имеющей бесконечные угловые граничные значения на каком-либо множестве $E \subset \Gamma$ положительной меры.

2) Пусть $w=f(z)$ - мероморфная в единичном круге $D=\{z:|z|<1\}$ функция, отличная от константы и имеющая радиальные граничные значения (конечные или бесконечные) на множестве $E$, расположенном на дуге $\sigma$ единичной окружности $\Gamma=\{z:|z|=1\}, \quad$ метрически плотном и второй категории по Бәру на б. Тогда множество $W$ ее радиальных граничных значений на $E$ содержит по крайней мере две различные точки. $\mathrm{M}$ е тр иче с ка я п ло т ност ь $E$ на $\sigma$ означает, что любая порция $E$ на $\sigma$ пмеет положительную меру. Отсюда следует, что если радиальные граничные значения $f(z)$ на множестве $E$ указанного типа равны нулю, то $f(z) \equiv 0$ в $D$. Далее, не существует мероморфоой фуннции в единичном круге, принимающей бесконечные радиальные граничные значения на множестве $E$ указанного типа.

Н. Н. Лузин и И. И. Привалов (см. [1], [2]) построили примеры, показывающие, что условия метрич. плотности и 2-й категории по отдельности не являются достаточными для того, чтобы выполнялось утверждение теоремы 2.

См. также Граничные свойства аналитических функчий, Лузина примерь, Предельное множество, Привалова теорема, Риссов теорема.

Лит.: [1] Л у зин Н. Н., П р и в а ло в И. И., "Ann. sci. École norm. supér." (3), 1925, t. 42, p. 143-91; [2] П' р и в ал о в И. И., Граничные свойства аналитических функций, 2 изд., М. Л., 1950; [3] Л о в а т е р А., в сб.: Итоги науки и техники. Математический анализ, т. 10, М., 1973 , с. $99-259$.

ЛУПА - квазигруппа с единицей, т. е. с таким әлементом $e$, что $x e=e x=x$ для любого әлемента $x$ из квазигруппы. Значение Л. в теории квазигрупп определяется следующей теоремой: всякая квазигруппа изотопна (см. Изотопия) нек-рой Л. Поэтому одной из основных задач теории квазигрупп является описание Л., к-рым изотопны квазигруппы данного класса.

С каждой Л. связаны три ядра. Множество

\[
N_{l}=\{a \mid a x \cdot y=a \cdot x y, \text { для всех } x, y \in Q\}
\]

әлементов из Л. $Q(\cdot)$ наз. л е в ы м я д р о м. Аналогично определяются с р е д н е и п р а в о е ядра. Они всегда существуют в Л. Их пересечение наз. я др о м л у п ы. Каждое ядро - ассоциативная подлупа, т. е. подгруппа в $Q(\cdot)$. Соответственные ядра изотопных Л. изоморфын. Существуют Л. с любыми наперед заданными ядрами. Л. $Q(\cdot)$, изотопная группе $Q(\cdot)$, является сама группой и изоморфна группе $Q(\cdot)$ (т е ор е м а А л б е р т a). В частности, изотопные группы изоморфны. Нек-рые другие классы Л. также обладают этим свойством, напр. свободные лупы. Л. $Q(\cdot)$ наз. $G$ - л у п о й, если любая Л., изотопная $Q(\cdot)$, будет ей изоморфиа.

На Л. распространяются многие понятия и результаты теории групп. Однако нек-рые обычные свойства групп могут и не иметь места для Л. Так, в конечных Л. теорема Лагранжа (о том, что порядок подгруппы делит порядок группы), вообще говоря, не имеет места. Если тем не менее для Л. справедлива теорема Лагранжа, то такую Л. наз. Л а г р а н ж е в о ї. Если всякая подлупа Л. $Q(\cdot)$ лагранжева, то говорят, что $Q(\cdot)$ обладает с в о й с т в о м $L^{\prime}$. Необходимым и достаточным условием, чтобы Л. $Q(\cdot)$ обладала свойством $L^{\prime}$, является следующее: $Q(\cdot)$ должна обладать такой нормальной цепью

\[
Q=Q_{0} \sqsupset Q_{1} \supset Q_{2} \supset \ldots \supset Q_{n}=e,
\]

где $Q_{i}$ нормальная подлупа в $Q_{i-1}$, что $Q_{i-1} / Q_{i}$ для всех $i=1,2, \ldots, \quad n$ обладает свойством $L^{\prime}$.