для любого $i \in K$, где $\tau_{i}-$ время возвращения в состояние $i$ :

\[
\tau_{i i}=\min \{t>0: \xi(t)=i(\xi(0)=i)\}
\]

для цепей Маркова с дискретным временем и

$\tau_{i i}=\inf \{t>0: \xi(t)=i(\xi(0)=i, \xi(0+) \neq i)\}$

для цепей Маркова с непрерывным временем.

Как и в случае положительного класса состояний (когда (*) заменено условием $\mathrm{E} \tau_{i i}<\infty$ ), состояния, принадлежащие одному нулевому классу, обладают рядом общих свойств; напр., для любых состояний $i, j$ пз нулевого класса $K$

\[
\lim _{t \rightarrow \infty} p_{i j}(t)=0 .
\]

Примером цепи Маркова, множество состояний к-рой образует один нулевой класс, является симметричное случайное блуждание на множестве целых чисел:

\[
\xi(0)=0, \quad \xi(t)=\xi(t-1)+\eta(t), \quad t=1,2, \ldots,
\]

где $\eta(1), \eta(2), \ldots-$ независимые случайные величшны,

$\mathrm{P}\{\eta(i)=1\}=\mathrm{P}\{\eta(i)=-1\}=1 / 2, \quad i=1,2, \ldots$

JIит.: [1] Ч ж у н $\mathbf{K}$ а й - л а й, Однородные цепи Маркова, пер. с англ., М., 1964. A. М. Зубков.

МАРКОВА ЦЕПИ ПОЛОЖИТЕЛЬНЫЙ КЛАСС СОСТОЯНИЙ - такое множество $K$ состояний однородной цепи Маркова $\xi(t)$ с множеством состояний $S$, что для переходных вероятностей

\[
p_{i j}(t)=\mathbf{P}\{\xi(t)=j \mid \xi(0)=i\}
\]

цепи $\xi(t)$ выполняются условия:

\[
\sup _{t} p_{i j}(t)>0 \text { при любых } i, j \in K,
\]

$p_{i l}(t)=0$ при любых $i \in K, l \in S \backslash K, t>0$ и

\[
\mathrm{E} \tau_{i i}<\infty \text { при любом } i \in K,
\]

где $\tau_{i i}$ - время возвращения в состояние $i$ :

\[
\tau_{i i}=\min \{t>0: \xi(t)=i(\xi(0)=i)\}
\]

для цепей Маркова с дискретным временем и

\[
\tau_{i i}=\inf \{t>0: \xi(t)=i(\xi(0)=i, \xi(0+) \neq i)\}
\]

для цепей Маркова с непрерывным временем. В случае $\mathrm{E} \tau_{i i}=\infty$ класс $K$ наз. нулевым классом состояний. Состояния, принадлежащие одному и тому же положительному классу $K$, обладают рядом общих свойств. Напр., в случае дискретного времени при любых $i, j \in K$ существует

\[
\lim _{n \rightarrow \infty} n^{-1} \sum_{t=1}^{n} p_{i j}(t)=p_{j}^{*}>0
\]

если

\[
d_{i}=\max \left\{d: P\left\{\tau_{i i} \text { делится на } d_{1}\right\}=1\right\}
\]

- период состояния $i$, то $d_{i}=d_{j}=d$ для любых $i, j \in K$ и $d$ наз. п е р и о до м к ла с с а $K$; для любого $i \in K$ существует

\[
\lim _{t \rightarrow \infty} p_{i i}(t d)=d p_{i}^{*}>0 .
\]

Цепь Маркова с дискретным временем, все состояния к-рой образуют один положительный класс периода 1, является примером Маркова цепи әргодической.

Лит.: [1] Ч ж у н К а й - л а й, Однородные цепи Маркова пер. с англ., М., 1964; [2] Д у б Д ж., Вероятностные процессы,
пер. с англ., М., 1956.
A. М. Зубков.

МАРКОВА ЦЕПЬ - марковский процесс с конечным или счетным множеством состояний. Теория М. ц. возникла на основе исследований А. А. Маркова, к-рый в 1907 положил начало изучению последовательностей зависимых испытаний и связанных с ними сумм случайных величин [1]. Пусть пространство состояний - множество натуральных чисел $N$ или его конечное подмножество. Пусть $\xi(t)$ - состояние М. ц. в момент времени $t$. Основным для М. Ц. является марковское свойство, к-рое для М. ц. с дискретным временем (т. е. в случае, когда время $t$ принимает лишь целые неотрицательные значения) определяется следующим образом: для любых $t, j \in N$, любых целых неотрицательных $t_{1}<t_{2}<$ $<. .<t_{k}<t$ и любых натуральных $i_{1}, i_{2}, \ldots, i_{k}$ имеет место равенство

\[
\begin{aligned}
\mathbf{P}\{\xi(t) & \left.=j \mid \xi\left(t_{1}\right)=i_{1}, \ldots, \xi\left(t_{k}\right)=i_{k}\right\}= \\
& =\mathbf{P}\left\{\xi(t)=j \mid \xi\left(t_{k}\right)=i_{k}\right\} .
\end{aligned}
\]

Марковское свойство (1) можно переформулировать следующим образом. Момент времени $t$ и связанные с ним события вида $\{\xi(t)=j\}$ назовем «настоящим» процесса; события, определяемые значениями $\boldsymbol{\xi}(u)$ c $u<t$, - «прошлым» процесса; события, определяемые значениями $\xi(u)$ с $u>t,-$ «будущим» процесса. Тогда свойство (1) равносильно следующему: для любого $t \in N$ при фиксированном «настоящем» $\xi(t)=j$ любые «прошлое» $A$ и «будущее» $B$ события условно. независимы, т. е.

\[
\begin{gathered}
\mathbf{P}\{A \cap B \mid \xi(t)=j\}= \\
=\mathbf{P}\{A \mid \xi(t)=j\} \mathbf{P}\{B \mid \xi(t)=j\} .
\end{gathered}
\]

Для вероятностного описания М. ц. $\xi(t)$ большую роль играют переходные вероятности

\[
\mathrm{P}\{\xi(t+1)=j \mid \xi(t)=i\} .
\]

В случае, когда переходные вероятности (2) не зависят от $t$, М. ц. наз. о д н о р о д н й (во времени); в противном случае - не о д н о р о д н о й. Далее рассматриваются лишь однородные М. ц. Пусть

\[
p_{i j}=\mathbf{P}\{\xi(t+1)=j \mid \xi(t)=i\} .
\]

Матрица $\mathbf{P}=\left\|p_{i j}\right\|$ с әлементами $p_{i j}$ наз. м а т $\mathbf{p}$ и це й п е р е ходны х в е р я т нос т е й. Вероятность любой траектории $\xi(k)=i_{k}, k=0,1, \ldots, t$, выражается через переходные вероятности $p_{i j}$ и начальное распределение $\mathbf{P}\{\xi(0)=i\}$ следующим образом:

\[
\begin{aligned}
& \mathbf{P}\left\{\xi(k)=i_{k}, k=0,1, \ldots, t\right\}= \\
& =\mathbf{P}\left\{\xi(0)=i_{0}\right\} \prod_{k=1}^{t} p_{i_{k-1} i_{k}}
\end{aligned}
\]

Наряду с переходными вероятностями $p_{i j}$ в М. ц. рассматриваются также переходные вероятности $p_{i j}(t)$ за $t$ шагов:

\[
p_{i j}(t)=\mathbf{P}\left\{\xi\left(t_{0}+t\right)=j \mid \xi\left(t_{0}\right)=i\right\} .
\]

Эти переходные вероятности удовлетворяют Колмогорова-Чепмена уравнению

\[
p_{i j}\left(t_{1}+t_{\mathbf{2}}\right)=\sum_{k} p_{i k}\left(t_{1}\right) p_{k j}\left(t_{2}\right) .
\]

С помощью переходных вероятностей можно произвести следующую классификацию состояниї. Два состояния $i$ и $j$ наз. с о о б щ а ю щ им и с я, если найдутся такие $t_{1}>0, t_{2}>0$, что $p_{i j}\left(t_{1}\right)>0$ и $p_{j i}\left(t_{2}\right)>0$. Состояние $k$ наз. н е с у щ е с т в е н ны м, если найдется такое состояние $l$, что $p_{k l}\left(t_{1}\right)>0$ для нек-рого $t_{1} \geqslant 1$ и $p_{l k}(t) \equiv 0$ для всех $t \in N$. Все остальные состояния наз. с у е с т в е ны ми. Таким образом, все множество состояний М. ц. разбивается на несущественные и существенные состояния. Множество всех существенных состояний разбивается на непересекающиеся классы сообщающихся состояний так, что любые два состояния из одного класса сообщаются между собой, а для любых двух состояний $i$ и $j$ из разных классов $p_{i j}(t) \equiv 0, p_{j i}(t) \equiv 0$. М. ц., все состояния к-рой составляют один класс сообщающихся