2) Как уже отмечалось, другой возможной характеристикой состояния системы является виртуальное время $w(t)$ ожидания. Грубо говоря, әто- время, к-рое прождал бы начала своего обслуживания вызов, пришедший в момент $t$. Пусть $S(t)$ есть сумма времен обслуживания вызовов, поступивших в систему до момента времени $t, \quad \boldsymbol{X}(t)=S(t)-t$. Аналогом равенства (3) здесь является соотношение

\[
w(t)=X(t)-\inf _{0 \leqslant u \leqslant t}(0, X(u)) .
\]

Пусть $G_{I S}$ - класс процессов со стационарными в узком смысле приращениями и $G_{I I}$ - класс процессов с независимыми приращениями $\left(G_{I I}\right.$ и $G_{I S}$ здесь можно понимать и более узко; напр., можно считать, что $G_{I I}$ - класс обобщенных пуассоновских процессов с положительными скачками и сносом -1). Если процесс $\{X(t) ; t \geqslant 0\} \in G_{I S}$, то он может быть расширен до процесса $\{X(t) ;-\infty<t<\infty\}$, заданного на всей оси и также принадлежащего $G_{I S}$. случае существует

\[
\lim _{t \rightarrow \infty} \mathbf{P}\{w(t)>x\}=\mathbf{P}\{\bar{Y}>x\}
\]

где

\[
\bar{Y}=\sup _{u \geqslant 0} Y(t), \quad Y(t)=X(0)-X(-t) .
\]

Если, кроме того,

\[
\mathrm{E}(X(1)-X(0))=\mathrm{E}(Y(1)-Y(0))=a<0,
\]

то распределение процесса

\[
w_{t}(u)=\{w(t+u) ; u \geqslant 0\}
\]

сходится при $t \rightarrow \infty$ к распределению процесса

\[
w^{s}(u)=\sup _{v \leqslant u}(X(u)-X(v))
\]

к-рый является собственным стационарным процессом виртуального времени ожидания. Сходимость здесь имеет место в сильной форме:

\[
\mathrm{P}\left\{w_{t} \in B\right\} \longrightarrow \mathrm{P}\left\{w^{s} \in B\right\}
\]

для любого измеримого $B$.

Далее, если $\{X(t)\} \in G_{I S}$ и $a<0$, то существует условная функция восстановления $H_{0}(x)$ процесса $X(t)$ :

\[
\begin{aligned}
H_{0}(x)=\int_{0}^{\infty} & \mathrm{P}\{0 \leqslant X(u)-X(0)<x \mid X(0)= \\
& \left.=\inf _{v \leqslant 0} X(v)\right\} d u<\infty ;
\end{aligned}
\]

при әтом

\[
\left.\begin{array}{l}
\mathrm{P}\left\{w^{s}(u) \geqslant x\right\}=-a \frac{d H_{0}(x)}{d x}, \\
\mathrm{P}\left\{w^{s}(t)=0\right\}=-a .
\end{array}\right\}
\]

Приведенные формулы сохраняются и в случае $v_{j}^{e} \neq 1$. Для систем, у к-рых $\left\{\tau_{j}^{s}-\tau_{j}^{e}\right\} \in G_{I}, \quad$ существуют простые связи между распределениями $w^{k}$ и $w^{s}(t)$.

3) Эргодические теоремы для длины очереди могут быть получены с помощью соответствующих теорем для времени ожидания. Пусть, напр., последовательность $\left\{\tau_{j}^{e}, \tau_{j}^{s}\right\} \in G_{S}$ эргодична (метрически транзитивна). Если, кроме того, $\mathrm{E}\left(\tau_{j}^{s}-\tau_{j}^{e}\right)<0$, то существует предельное (стационарное) распределение $q_{n}$ такое, что

\[
\lim _{n \rightarrow \infty} P\left\{q_{n}>k\right\}=P\left\{w^{0}>\tau_{1}^{e}+\ldots+\tau_{k}^{e}\right\}
\]

Если же $\left\{\tau_{j}^{e}\right\} \in G_{I},\left\{\tau_{j}^{s}\right\} \in G_{I}$ и распределение $\tau_{j}^{e}$ нерешетчато, то существует

$\lim _{\tau \rightarrow \infty} \mathrm{P}\{q(t)>k+1\}=\mathrm{P}\left\{w^{0}>\tau_{1}^{e}+\ldots+\tau_{k}^{e}+\gamma\right\}, k \geqslant 0$,

\[
\lim _{\tau \rightarrow 0} \mathrm{P}\{q(t)=0\}=-a / \mathrm{E} \tau^{e},
\]

где все компоненты под знаком вероятности в правой части независимы, $\gamma$ имеет плотность, равную

\[
\mathbf{P}\left\{\tau_{j}^{e}>x\right\} / \mathrm{E \tau}^{e},
\]

\[
w^{0}=\sup \left(0, \xi_{0}, \xi_{0}+\xi_{-1}, \ldots\right), \quad \xi_{j}=\tau_{j}^{s}-\tau_{j}^{e} .
\]

Если $\left\{\tau_{j}^{\epsilon}\right\} \in E$, то предельные распределения $q_{n}$ и $q(t)$ совпадают.

4) Если $\left\{\tau_{j}^{e}\right\} \in E, \quad\left\{\tau_{j}^{s}\right\} \in G_{I}$ (допускается также, что $\left.v_{j}^{e} \neq 1,\left\{v_{j}^{e}\right\} \in G_{I}\right)$, то можно получить точные формулы и для допредель́ного распределения $w(t)$ :

\[
\mathrm{P}\{w(t)<x\}=\mathrm{P}\{Y(t)<x\}+
\]\[
+\frac{\partial}{\partial x} \int_{0}^{t} \mathrm{E}(Y(u) / u ; \quad Y(u)<0) \mathbf{P}\{Y(t-u)<x\} d u,
\]\[
\mathrm{P}\{w(t)=0\}=-\mathrm{E}(Y(t) / t, \quad Y(t)<0) .
\]

При $a<0$ и $t \rightarrow \infty$ имеет место фо р м у л а Х и нч и н а для стационарного распределения:

\[
\mathrm{E} e^{i \lambda \omega^{s}(u)}=\frac{1-\alpha \mathrm{E} \theta}{1-\alpha \frac{\varphi(\lambda)-1}{i \lambda}}, \quad \varphi(\lambda)=\mathrm{E} e^{i \lambda \theta},
\]

где $\theta$ - величина скачка процесса $X(t)\left(\theta=\tau_{j}^{s}\right.$, если $\left.v_{j}^{e} \equiv 1\right), \alpha$ - показатель распределения $\tau_{j}^{e}$.

Пусть $T_{j}, j=1,2, \ldots,-$ п е р и о ды 3 а н я т ос т и с и с т м м (т. е. длины интервалов времени в течение к-рых $w(t)>0)$. Тогда для рассматриваемых систем

\[
\mathrm{P}\left\{T_{j} \in(u, u+d u)\right\}=\frac{1}{\alpha u} \mathrm{P}\{X(u) \in(0, d u)\} .
\]

5) Для систем, у к-рых $\left\{\tau_{j}^{e}, \tau_{j}^{s}\right\} \in G_{I}$ (допускается, также $\left.v_{j}^{e} \neq 1,\left\{\tau_{j}^{e}, \tau_{j}^{\mathrm{s}}, v_{j}^{e}\right\} \in G_{I}\right)$ расгіределение $w^{k}$ совпадает с распределением величины

\[
Y=\sup \left(0, \xi_{1}, \xi_{1}+\xi_{2}, \ldots\right) .
\]

По известному распределению $\xi_{j}$ распределение $Y$ может быть найдено следующим образом. Если $\mathrm{P}\{Y<\infty\}=1$ (это всегда при $\mathrm{E} \xi_{j}<0$ ), то справедливо следующее факторизационное тождеств о

\[
1-\mathrm{E} e^{i \lambda \xi}=(1-p)\left(1-\mathrm{E} e^{i \lambda \chi}\right) / \mathrm{E} e^{i \lambda Y}, \quad \operatorname{Im} \lambda=0,
\]

где $p=\mathrm{P}\{Y>0\}, \chi \leqslant 0-$ величина первой неположительной суммы среди $\xi_{1}, \xi_{1}+\xi_{2}, \ldots$ Это соотношение позволяет отождествить с Ее $i \lambda Y_{\text {отнотение }} w_{+}(\lambda) / w_{+}(0)$ в любом тождестве

\[
1-\mathrm{E} e^{i \lambda \xi}=w_{-}(\lambda) / w_{+}(\lambda), \quad \operatorname{Im} \lambda=0,
\]

в к-ром функции $w_{ \pm}(\lambda)$ допускают представление

\[
w_{ \pm}(\lambda)=\int_{0}^{ \pm \infty} e^{i \lambda t} d V_{ \pm}(t)
\]

( $V_{ \pm}$- функции ограниченной вариации). Равенство

(5) осуществляет т. н. V-факторизацию функции $1-Е e^{i \lambda \xi}$. Оно позволяет указать следующие случаи, когда возможно отыскание Ееi $e^{i}$ в явном виде.

Предполагают, что $-\infty<E \xi<0$, и обозначают $f(\lambda)=\mathrm{E} e^{i \lambda \xi}, \quad f_{+}(\lambda)=e^{i \lambda \tau^{s}}, \quad f_{-}(\lambda)=e^{-i \lambda \tau^{e}}$, так что $f(\lambda)=f_{+}(\lambda) f_{-}(\lambda)$.

А) Если $f_{+}-$рациональная функция: $f_{+}=P_{m} / Q_{n}$, где $P_{m}$ и $Q_{n}$ - многочлены степеней $m$ и $n$ соответст-