наз. н е в ы р о ж д е н н о й, если $\operatorname{det} A \neq 0$. М. $A^{-1} \in$ $\in M_{n}(K)$ наз. о б р а т н о й к $A$, если $A A^{-1}=A^{-1} A=$ $=E_{n}$. Обратимость $A$ в $M_{n}(K)$ равносильна невырожденности и

\[
A^{-1}=\left\|c_{j}\right\|, \quad c_{i j}=\frac{A_{j i}}{\operatorname{det} A}
\]

где $A_{j i}$-алгебрачческое дополнение элемента $a_{j i}$; $\operatorname{det} A^{-1}=(\operatorname{det} A)^{-1}$. Для $A$ и $B$ из $M_{n}(K)$

\[
A B=E_{n} \Longleftrightarrow B A=E_{n}
\]

Совокупность всех обратимых $M$. из $M_{n}(K)$ образует группу относительно умножения, к-рая наз. П о лн о й л и н е й н о й г р у П П о й и обозначается $\mathrm{GL}(n, K)$. Степени М. $A$ определяются следующим обpazom:

\[
A^{0}=E_{n} ; A^{k}=A^{k-1} A
\]

для $k>0$, а если $A$ обратима, то $A^{-k}=\left(A^{-1}\right)^{k}$. Для многочлена

\[
f(x)=\alpha_{0}+\alpha_{1} x+\ldots+\alpha_{t} x^{t}, f(x) \in K[x],
\]

определяется матричный многочлен

\[
f(A)=\alpha_{0} E_{n}+\alpha_{1} A+\ldots+\alpha_{t} A^{t}
\]

Всякая М. из $M_{n}(K)$ задает нек-рое линейное преобразование $n$-мерного векторного пространства $V$ над $K$. Пусть $v_{1}, . ., v_{n}$ базис в $V$, а $\sigma: V \rightarrow V-$ линейное преобразование пространства $V$. Тогда $\sigma$ однозначно определяется последовательностьо векторов

\[
u_{1}=\sigma\left(v_{1}\right), \ldots, u_{n}=\sigma\left(v_{n}\right) \text {. }
\]

При этом

\[
\left.\begin{array}{l}
\sigma\left(v_{1}\right)=v_{1} a_{11}+\ldots+v_{n} a_{n 1}, \\
\cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot \cdot v_{n} a_{n n}
\end{array}\right\}
\]

где $a_{i j} \in K$. Матрица $A=\left\|a_{i j}\right\|$ наз. М. п р е о б р азо в а ни я $\sigma$ в базисе $v_{1}, \ldots, v_{n}$. При фиксированном базисе М. $A+B$ будет М. преобразования $\sigma+\tau$, а $A B-\mathrm{M}$. преобразования $\sigma \tau$, где $B-\mathrm{M}$. линейного преобразования $\tau$. Равенства (4) можно запıсать в виде

\[
\left[\sigma\left(v_{1}\right), \ldots, \sigma\left(v_{n}\right)\right]=\left[v_{1}, \ldots, v_{n}\right] A .
\]

Пусть $w_{1}, \ldots, w_{n}$ - тоже базис в $V$. Тогда $\left[w_{1}, \ldots\right.$, $\left.w_{n}\right]=\left[v_{1}, \ldots, v_{n}\right] T, \quad T \in \operatorname{GL}(n, K)$, a $T^{-1} A T-\dot{M} . \dot{\sigma}$ в базисе $w_{1}, \ldots, w_{n}$. М. $A$ и $B$ из $M_{n}(K)$ наз. п о д о бА Ы м, если в $\operatorname{GL}(n, K)$ найдется такая М. $T$, что $B=T^{-1} A T$. При этом $\operatorname{det} A=\operatorname{det} T^{-1} A T$ и ранги матриц $A$ и $B$ совпадают. Линейное преобразование $\sigma$ наз. н е в ы р о ж д е н ным, если $\sigma(V)=V ; \sigma$ тогда и только тогда невырождено, когда его М. невырождена. Если $V$ трактовать как пространство столбцов $M_{n, 1}(K)$, то линейное преобразование пространства $V$ представляет собой умножение столбцов $v \in V$ на $\mathrm{M}$. $A$ из $M_{n}(K)$ слева: $\sigma(v)=A v$, и М. преобразования $\sigma$ в базисе

\[
v_{1}=\left\|\begin{array}{l}
1 \\
0 \\
\cdot \\
\cdot \\
\cdot \\
0 \\
0
\end{array}\right\|, \ldots, v_{n}=\left\|\begin{array}{l}
0 \\
0 \\
\cdot \\
\cdot \\
\cdot \\
0 \\
1
\end{array}\right\|
\]

совпадает с $A$. М. $A \in M_{n}(K)$ тогда и только тогда вырождена, когда в $M_{n .1}(K)$ существует такой столбец $v \neq 0$, что $A v=0$.

Транспонирование и матрицы специального вида. Пусть $A=\left\|a_{i j}\right\| \in M_{m, n}(K)$. Тогда М. $A^{\top}=\left\|a_{i j}^{\top}\right\| \in$ $\in M_{n, \boldsymbol{m}}(K)$, где $a_{i j}^{\top}=a_{i j}$,наз. т р а н с п о н и р о в а нн о й к $A$. Матрица $A^{\top}$ обозначается также ${ }^{t} A$ и $A^{\prime}$. Пусть $A=\left\|a_{i j}\right\| \in M_{m, n}(\mathbb{C})$. Тогда $\mathrm{M} . \bar{A}=\left\|\overline{a_{i j}}\right\|$, где $\overline{a_{i j}}$ - число, комплексно-сопряженное с $a_{i j}$, наз. ко м п ле к сн о-с оп р я е нно й с $A$. Матрица $A *=\bar{A}^{\top}$, где $A \in M_{n}(\mathbb{C})$, наз. э р м и т о в ос о п р я ж н н о й с $A$. Многие М., используемые в приложениях, имеют специальные названия.

![](https://cdn.mathpix.com/cropped/2023_07_08_699ba998dc88e34769afg-1.jpg?height=526&width=841&top_left_y=476&top_left_x=984)

Полиномиальные матрицы. Пусть $K-$ поле, $K[x]-$ кольцо всех многочленов от $x$ с коэффициентами из $K$. М. над $K[x]$ наз. п о ли ном и а ль н о й. Для $\mathbf{~ и . ~}$ из кольца $M_{n}(K[x])$ вводятся эле ме н т а р ны е о п е р а ц и и: 1) умножение строки или столбца М. на ненулевой элемент поля $K, 2)$ прибавление к строке (столбцу) другой строки (столбца) М., умноженной на многочлен из $K[x]$. М. $A$ и $B$ из $M_{n}(K[x])$ наз. э кв і в а ле н т н ы м и $(A \sim B)$, если $B$ можно получить из $A$ с помощью конечного числа әлементарных операцıй.

Пусть

$N=\operatorname{diag}\left[f_{1}(x), \ldots, f_{r}(x), 0, \ldots, 0\right] \in M_{n}(K[x])$,

где: 1) $\left.f_{i}(x) \neq 0,2\right) f_{j}(x)$ делится на $f_{i}(x)$ при $j>i$, 3) коэффициенты старших членов многочленов $f_{i}(x)$ равны 1. Тогда $N$ наз. к а н о н и ч е с к о й п о л ин о м и а л ь о й М. В каждом классе әквивалентных М. кольца $M_{n}(K[x])$ содержится едннственная канонич. М. Многочлены

\[
f_{1}(x), \cdots, f_{r}(x),
\]

где

\[
N=\operatorname{diag}\left[f_{1}(x), \ldots, f_{r}(x), 0, \ldots, 0\right]
\]

- каноническая М., а $A \sim N$, наз. и н в а р и а н тны ми м н ж и т е л я м и М. $A$; число $r$ совпадает с рангом М. $A$. Матрица $A$ из $M_{n}(K[x])$ тогда и только тогда имеет обратную в $M_{n}(K[x])$, когда $A \sim E_{n}$. В свою очередь $A \sim E_{n} \Longleftrightarrow \operatorname{det} A \in K \backslash 0$. Матрицы $A$ и $B$ из $M_{n}(K[x])$ тогда и только тогда әквивалентны, когда

\[
\boldsymbol{B}=\boldsymbol{P} A Q,
\]

где $P, Q \in M_{n}(K[x]), \quad P \sim Q \sim E_{n}$.

Пусть $A \in M_{n}(K)$. Матрица

\[
x E_{n}-A \in M_{n}(K[x])
\]

наз. х а р ак т е ристическ ой мат рицей матрицы $A, \operatorname{adet}\left(x E_{n}-A\right)-$ х а р а к т е р и с т ич ес к и м м н о гоч л е но м М. А. Для любого многочлена вида

\[
f(x)=\alpha_{0}+\alpha_{1} x+\ldots+\alpha_{n-1} x^{n-1}+x^{n} \in K[x]
\]

в $M_{n}(K)$ существует M. $F$, для к-рой $\operatorname{det}\left(x E_{n}-F\right)=f(x)$.