ребру паросочетания $P$, наз. т р а н с в е р с а л ь ю. Множество $V$ и множество всех трансверсалей графа $G$ образуют т. н. т р а н с в е р с а лы ь ы й м а т р о и д. M. можно задать также множеством $V$ әлементов и семейством $C=\left\{C_{1}, C_{2}, \ldots\right\}$ непустых подмножеств $C_{i} \sqsubseteq V$, называемых ц ик л а м и и удовлетворяюших следующим аксиомам: никакое собственное подмножество цикла не является циклом; если $v \in C_{i} \cap C_{j}$, то $C_{i} \cup C_{j} \backslash\{v\}$ содержит цикл. Независимыми множествами этого М. являются подмножества $E \subseteq V$, не содержащие циклов.

Если $G$ - граф, то множество его ребер и семейство простых циклов образуют т. н. ц и к л и ч е с к й й м а т р о и д. Если в качестве циклов М. взять коциклы (разрезы, см. Графа связность) графа $G$, то полученный таким образом М. наз. к о ц и к лич е с к и м. М. двух последних типов наз. г р а фи ч е с к и ми. Понятие «М.» используется в теории графов и комбинаторике при доказательстве нек-рых утверждений о noкрытиях и упаковках, паросочетаниях.

Jum.: [1] W h i t n e y H., "Amer. J. Math.", 1935, v. 57, p. $509-33 ;[2]$ T u t t e w. T, «J. Res. Nat. Bur. Standards
Sec. B», 1965 , v. 69, № $1-2$, p. $1-47 ;$ [3] X a p и $\Phi$., Teopur графов, пер, англ. М., 1973.

МАТЬЁ ГРУППА - конечная группа, изоморфная одной из пяти групп, открытых Э. Матьё [1]. Серия М. г. состоіт из групп, обозначаемых

\[
M_{11}, M_{12}, M_{22}, M_{23}, M_{24} ;
\]

они представимы как группы подстановок на множествах из 11, 12, 22, 23, 24 әлемент ов соответственно. Группы $M_{12}$ и $M_{24}$ являются пятикратно транзитивными. $M_{11}$ реализуется естественным образом как стабилизатор в $M_{12}$ әлемента множества, на к-ром действует $M_{12}$, $M_{23}$ - как стабилизатор элемента в $M_{24}, M_{22}-$ как стабилизатор элемента в $M_{23}$. Порядки М. г. равны соответственно

$7920,95040,443520,10200960,244823040$.

При рассмотрении М. г. часто пользуются (см. [2]) представлением ее в виде группы автоморфизмов соответствующей с и с т е м Ы III т е й н е р а $S(l, m, n)$, т. е. множества из $n$ әлементов, в к-ром выделена система $\left(\begin{array}{l}n \\ l\end{array}\right) /\left(\begin{array}{c}m \\ l\end{array}\right)$ подмножеств, называемых блоками, состоящих из $m$ элементов множества, причем каждые $l$ элементов содержатся в одном и только в одном блоке. А в т о о о фи становка множества ее элементов, переводящая блок в блок. Группа $M_{11}$ является группой автоморфизмов системы IIтейнера $S(4,5,11)$, группа $M_{12}-$ системы $S(5,6,12)$, группа $M_{22}$ - системы $S(3,6,22)$, группа $M_{23}$ - системы $S(4,7,23)$, группа $M_{24}-$ системы $S(5,8,24)$.

М. г. были первыми (и на протяжении более 80 лет единственными) известными спорадическими конечными простыми группами.

![](https://cdn.mathpix.com/cropped/2023_07_08_1cd852eeb137da1690d1g-1.jpg?height=54&width=799&top_left_y=1784&top_left_x=151)
t. 6, p. 241-323;1873, t. 18, p. 25-46; [2] W i t t E., "Abhandl. [3] Итоги науки и техники. Алгебра. Топология. Геометрия, т. 14 , M., 1976 , с. 5-56. Алгеора. Топология. Геометрия, МАТЬЁ УРАВНЕНИЕ - обыкновенное линейное диффференцальное уравнение

\[
\frac{d^{2} u}{d z^{2}}+(a+b \cos 2 z) u=0, z \in \mathbb{R}
\]

с действительными коэффициентами. Введено Э. Матьё [1] при исследовании колебаний әллиптич. мембраны; частный случай Хилла уравнения.

Фундаментальная система решений М. у. имеет вид

\[
u_{1}(z)=e^{\alpha z} \varphi(z), u_{2}(z)=u_{1}(-z)
\]

при $\alpha \neq n i, n$-целое, где $\varphi(z)$ есть $\pi$-периодическая функтия, а Ляпунова характеристический показаmель $\alpha$ либо действительный, либо чисто мнимый. При $\operatorname{Im} \alpha=0$ одно из решений неограниченно возрастает, а другое стремится к нулю для $z \rightarrow+\infty$ (зоны неустойчивости на плоскости $a b$ параметров), при $\operatorname{Re} \alpha=0$ эти решения ограничены (зоны устойчивости). На границе этих зон (случай, исключенный в (*)) одна из функций фундаментальной системы решений М. у.

![](https://cdn.mathpix.com/cropped/2023_07_08_1cd852eeb137da1690d1g-1.jpg?height=35&width=821&top_left_y=362&top_left_x=989)
Матьё буукцией), а вторая получается из первой умножением на z. Зоны неустойчивости имеют вид криволинейных треугольников с вершинами в точках $\boldsymbol{a}=n^{2}$, $b=0, n=0,1,2$,...(см. [2], [4]).

M. у. имеет и другую форму (см. [3]).

Jum.: [1] M a thi e u E., Cours de physique mathématique, P., 1873; [2] C т p е т т M. Д.. О., Функции Јаме, Матье и родК а м к е Э., Справочник по обыкновенным дифференциальным уравнениям, пер. с нем., 5 изд., М., 1976; [4] Я к у б о в и ч В. А., С т а р ж и н с к и й В. М., Линейные дифференциальные уравнения с периодическими коәффициентами и их приложения, М.,
1972.
В. М. Старжинский.

![](https://cdn.mathpix.com/cropped/2023_07_08_1cd852eeb137da1690d1g-1.jpg?height=40&width=809&top_left_y=717&top_left_x=1012)
Матьё уравнения

\[
\frac{d^{2} u}{d z^{2}}+(a+16 q \cos 2 z) u=0, z \in \mathbb{R},
\]

к-рые существуют только тогда, гогда точка $(a, q)$ на плоскости параметров лежит на границе зон устойчивости. М. ф. четна или нечетна и единственна с точностью до множителя; второе линейно независимое решение линейно растет по $z$ при $|z| \rightarrow \infty$, если $q \neq 0$. Четные М. ф.- собственные функции интегрального уравнения

\[
G(z)=\lambda \int_{-\pi}^{\pi} e^{k \cos z \cos t} G(t) d t, k=\sqrt{32 q} .
\]

Аналогичное уравнение имеется для нечетных М. ф. Обозначения М. ф.:

$\mathrm{ce}_{\mathbf{0}}(z, q), \mathrm{ce}_{\mathbf{1}}(z, q), \ldots ; \mathbf{s e}_{\underline{1}}(z, q), \mathrm{se}_{\mathbf{2}}(z, q), \ldots$

При $q \rightarrow 0$ эти функции приводятся к тригонометрич. системе

\[
1, \cos z, \ldots ; \sin z, \sin 2 z, \ldots
\]

и обладают теми же свойствами ортогональности на интервале $(-\pi, \pi)$. М. ф. разлагаются в ряды Фурье, к-рые сходятся при малых $|q| \leqslant r_{n}$; коәффициенты рядов - сходящиеся ряды по степеням $q$, напр.

\[
\begin{aligned}
& \operatorname{ce}_{0}(z, q)=1+\sum_{n=1}^{\infty}\left[2^{n+1} q^{n} /(n !)^{2}-\right. \\
& \left.-\frac{n(3 n+4) 2^{n+3} q^{n+2}}{((n+1) !)^{2}}+O\left(q^{n+4}\right)\right] \cos 2 n z .
\end{aligned}
\]

Лum.: [1] уитте т е р Э.-Т., В а т с он Д.-Н., Курс современного анализа, пер. с англ., 2 изд., ч. 2, М., $1963 ;$ [2] Б е й т м е н Г., Э р д е й и А., Высшие трансцендентные функции. Эллиптические и автоморфные функции. Функции Ламе и Матье, пер. с англ., М., 1967; [3] С а н с о н е Д ж., Обыкновенные дифференциальные уравнения, пер. с итал., т. 1, М., 1953; [4] С т р е т т М. Д. О., Функции Јаме, Матье и родственные им в физике и технике, пер. с нем., Хар.-К., 1935; [5] М а к-Ј а хл а н Н. В., Теория и приложения функций Матье, пер. с англ., M., 1953.

МАУ РЕРА - КАРТАНА ФОРМА - левоинвариантная 1-форма на группе Ли $G$, т. е. диффференциальная форма $\omega$ степени 1 на $G$, удовлетворяющая условию $l_{a}^{*} \omega=\omega$ для любого левого сдвига $l_{g}: x \rightarrow g x, g, x \in G$. М. - К. ф. на $G$ находятся во взаимно однозначном соответствии с линейными формами на касательном пространстве $T_{e}(G)$ в точке $e$; точнее, соответствие, сопоставляющее каждой М.- К. ф. $\omega$ ее значение $\omega_{e}$ из $T_{e}(G)^{*}$, является изоморфизмом пространства М. 一 К. ф. на $T_{e}(G)^{*}$. Диффференциал М. - К. ф. есть левоинвариантная 2-форма на $G$, определяемая формулой

\[
d \omega(X, Y)=-\omega([X, Y])
\]