l6] shepherdson J. C., sturg i s H. E., "J. Assoc. Comput. Machinery", 1963, v. 10, ㅊo 2, p. 217-55. М. Марченков.

МАШИННО-ОРИЕНТИРОВАННЫЙ ЯЗЫК - ЯзЫК шрограммирования, позволяющий при составлении программ учитывать особенности системы команд и представления информации в объектной вычислительной машине. М.-о. я., в отличие от универсальных проблелно-ориентированных языков программирования, осуцествляющих отображение множества $P$ входных программ во множество $M$ машинных программ, стремятся отображатє. $P$ на $M$.

Простейшими М.-о. я. являются а с с е м б л е р ы, к-рые, полностью сохраняя структуру машинной программы, позволяют использовать символич. обозначения для команд и адресов памяти, а также собирать программы из нескольких отдельно написанных кусков. Дополнительные возможности по текстовым подстановкам и другим простым преобразованиям при сборке программного текста Іредоставляются макроассемблерами. М.-о. я. высокого уровня, аналогично универсальным языкам, имеют фразовую структуру, допуская составные объекты и определяемые операции, однако содержат дополнительно средства описания әлементарных объектов и базовых операций в терминах машинных конструкций.

Лum.: [1] Д ж е р м е й н К., Программирование на IBM/360, пер. с англ., 2 изд., М., 1973; [2] Б р а у н П., Макропроцессоры и мобильность программного обеспечения, пер. с англ., М., 1977;
[3] К а т к о В. Ј., Р а р А. Ф., Программирование на языке [3] К а т к о в В. Ј., Р a p А. Ф., Программирование на языке
ЭПСИЛО А, Новосиб., 1972.

МАЯТНИКА КӦЛЕБАНИИ УРАВНЕНИЕ - обЫкновенное дифференциальное уравнение вида

\[
\ddot{x}=-a \sin x,
\]

где $a$ - положительная константа. М. к. у. возникает при изучении свободных колебаний в поле тяжести математич. маятника - материальной точки, имеющей одну степень свободы и находящейся на конце непастяжимого и несжимаемого невесомого подвеса, другой конец, к-рого закреплен на шарнире, допускающем вращение маятника в вертикальной плоскости. Неизвестная функция $x(t)$ - это угол отклонения маятника в момент $t$ от нижнего положения равновесія, выраженный в радианах;

\[
a=g / l,
\]

где $l$ - длина подвеса, $g$ - ускорение свободного падения. Уравнение малых колебаний маятника около нижнего положения равновесия имеет вид:

\[
\ddot{x}=-a x \text {. }
\]

Качественное изучение М. к. У. производится с помощью закона сохранения энергии, связывающего положение и скорость маятника:

\[
\frac{\dot{x}^{2}}{2}-a \cos x=E,
\]

где $E=$ const - полная энергія маятника. Масштаб времени можно выбрать так, чтобы было $a=1$. При этом значению полної энергии $E<1$ соответствует колебательное движение маятника (скорость периодически меняет знак), а значению $E>1$ соответствует вращательное движение (скорость сохраняет знак). Решение $x(t)$ М. к. у. (*) с начальным условием $x(0)=0, \dot{x}(0)=\alpha$ пгри $E=\alpha^{2} / 2<1$ удовлетворяет соотношению

\[
\sin \frac{1}{2} x(t)=\frac{\alpha}{2} \operatorname{sn} t
\]

где Якоби эллиптическая бункция sn имеет модуль $\alpha / 2$.

Большое прикладное значение имеют уравнения, близкие к М. к. у. Наличие малого трения, зависящего от положения и скорости маятника, приводит к уравнению

\[
\ddot{x}=-a \sin x+\varepsilon f(x, \dot{x})
\]

малые колебания маятника $c$ трением описываются уравнением:

\[
\ddot{x}=-a x+\varepsilon f(x, \dot{x}),
\]

частным случаем к-рого является Ван дер По.я уравнение. Колебание маятника при периодич. изменении длины подвеса (двігжение качелей) описывается X илла уравнениеи, важный частный случай к-рого - Матьё уравнение.

Лит.: [1] А р н о л ь Д В. И., Обыкновенные дифференциальные уравнения, 2 изд., М., 1975; [2] К а м к е Э., Справочник по обыкновенным дифференциальным уравнениям, пер. с нем., 5 изд., М., 1976; [3] А н д р о н о в А. А., В и т т А. А., Х а йк и н С. Э., Теория колебаний, 2 изд., М., 1959.

МГНОВЕННОЕ СОСТОЯНИЕ для однородной цепи Маркова со счетным множеством состояний - состояние (напр., $i$ ), для к-рого плотность вероятности перехода

\[
a_{i i}=\lim _{h \downarrow 0} \frac{p_{i i}(h)-1}{h}
\]

где $p_{i i}(h)$ - вероятность перехода из $i$ в $i$ за время $h$, равна - $\infty$. В противном случае состояние $i$ наз. немгновенным, или задерживающим.

Лum.: [1] Г и х м а н И. И., С $\mathbf{k}$ о р о х о д А. В., Теория случайных процессов, т. 2, М., 1973. А. Н. Ширлев.

МЁБИУСА ЛИСТ - неориентируемая поверхность, у к-рой әйлерова характеристіка равна нулю, а край представляет собой замкнутую линию. М. л. может быть получен отождествлением двух противоположных сторон $A B$ и $C D$ прямоугольника $A B C D$ так, что точки $A$ и $B$ совме-

![](https://cdn.mathpix.com/cropped/2023_07_08_f8a3a7d17d311fd1fa0dg-1.jpg?height=233&width=458&top_left_y=1104&top_left_x=1369)
щаются соответственно с точками $C$ и $D$ (см. рис.). М. Л. в евклидовом пространстве $E^{3}$ является односторонней поверхностью (см. Односторонние и двусторонние поверхности).

М. л. был рассмотрен (в 1858-65) независимо друг от друга А. Мёбиусом (А. Möbius) и И. Листингом (I. Listing). А. Б. Иванов. МЁБИУСА ПЛОСКОСТЬ, К р у г о в а я п л о ско с т ь, ин ве р с н а я п л о ск о с т ь, - плоскость, элементы к-рой составляют два непересекаюпихся множества - множество точек и множество окружностей, с симметричным отношением инцидентности (связывающим точку и окружность). Отношение инцидентности удовлетворяет следующим аксиомам:

1) каждые три различные точки инцидентны одной и только одной окружности;

2) через точку, не инцидентную окружности, проходит одна и только одна окружность, пересекающая даннуюо окружность в данной точке;

3) суıцествугт по крайней мере четыре разлпчные точкі, не пнцидентные одной окружности. Каждая окружность инцидентна по крайней мере трем различным точкам.

Из М. п. можно получить афффинную плоскость, если назвать одну из точек М. П. Несобственной, а окружности, инцидентные этой точке, - прямыми.

В трехмерном проективном пространстве $\mathbb{P}_{3}$ точки овоида о и плоскости, пересекающей овоид в более чем одной точке, с тем же отношением инцидентності, что и в $\mathbb{P}_{3}$, образуют М. П. $M(o)$ (см. [1]). М. П. наз. овалоподоб̈ной, если она изоморфна $M(o)$ для нек-рого овоида о. Среди овалоподобных М. П. наиболее известна модель $M(S)$, где $S$ - сфера в трехмерном евклидовом