Естественным образом можно определить понятие случайной величины с бесконечным М. о. Типичным примером служат времена возвращения в нек-рых случайных блужданиях (см., напр., Бернулли блуждание). С помощью М. о. определяются многие числовые и функциональные характеристики распределения (как М. о. соответствующих функций от случайной величины), напр. производящая бункция, характеристическая бункция, моменты любого порядка, в частности дисперсия, ковариачия.

М. о. есть характеристика расположения значений случайной величины (среднее значение ее распределения). В этом качестве М. о. служит нек-рым «типичным» параметром распределения и его роль аналогична роли статич. момента - координаты центра тяжести распределения массы - в механике. От прочих характеристик расположения, с помощью к-рых распределение описывается в общих чертах,- медиан, мод, М. о. отличается тем большим значением, к-рое оно и соответствующая ему характеристика рассеяния - дисперсия имеют в предельных теоремах теории вероятностей. С наибольшей полнотой смысл М. о. раскрывается больших чисел законом (см. также Чебьцева неравенство) и больших чисел усиленным законом. В частности, для последовательности взаимно независимых и одинаково распределенных случайных величин $X_{1}, \ldots, X_{n}$ с конечными М. о. $a=\mathrm{E} X_{k}$ при $n \rightarrow \infty$ для любого $\varepsilon>0$

\[
P\left(\left|\frac{X_{1}+\ldots+X_{n}}{n}-a\right|>\varepsilon\right) \longrightarrow 0
\]

и, более того,

\[
\frac{X_{1}+\ldots+X_{n}}{n} \longrightarrow a \longrightarrow c \text { вероятностью единица. }
\]

Понятие М. о. как ожидаемого значения случайной величины впервые наметилось в 18 в. в связи с теорией азартных игр. Первоначально термин «М. о.» был введен как ожидаемый выигрыш игрока, равный $\sum x_{k} p_{k}$ для возможных выигрышей $x_{1}, \ldots ; x_{n}$ и соответствующих вероятностей $p_{1}, \ldots, p_{n}$. Особые заслуги в обобщении и использовании понятия М. о. в современном его значении имеет П. Л. Чебышев.

Лum.: [1] К о л м о г o p o в А. Н., Основные понятия теории вероятностей, 2 изд., М., 1974; [2] Ф е л л е р В., Введение в теорию вероятностей и ее приложения, пер. с англ., 2 изд., тт. 1-2, М., 1967; [3] Л о ә в М., Теория вероятностей, пер. с англ., М., 1962; [4] К $\mathbf{p}$ a м е p Г., Математические методы статистики, пер. с англ., 2 изд., М., 1975 . А. В. Прохоров.

МАТЕМАТИЧЕСКОЕ ПРОГРАММИРОВАНИЕ - математическая дисциплина, посвященная теории и методам решения задач о нахождении әкстремумов функций на множествах конечномерного векторного пространства, определяемых линейными и нелинейными ограничениями (равенствами и неравенствами). М. П.раздел науки об исследовании операций, охватывающий широкий класс задач управления, математич. моделями к-рых являются конечномерные әкстремальныө задачи. Задачи М. п. находят применение в различных областях человеческой деятельности, где необходим выбор одного из возможных образов действий, напр. при решении многочисленных проблем управления и планирования производственных процессов, в задачах проектирования и перспективного планирования. Наименование «М. п.» связано с тем, что целью решения задач является выбор п р о г р а м м ы действий.

Математич. формулировка задачи М. П.: минимизировать скалярную функцию векторного аргумента $\varphi(x)$ на множестве

\[
\begin{gathered}
X=\left\{x: q_{i}(x) \geqslant 0, i=1,2, \ldots, k ;\right. \\
\left.h_{j}(x)=0, j=1,2, \ldots, m\right\},
\end{gathered}
\]

где $q_{i}(x)$ и $h_{j}(x)$ - скалярные функции. Функцию $\varphi(x)$ наз. це ле в о й ф у н ци е й, ф у н цци е й ц е л и, а также к р и т е р и е м качества, множество $\boldsymbol{X}$ - допу у т и мым мно же с т во м, или множ е с т в о м п л а н о в, решение $x^{*}$ задачи М. П.о п т и м а л ь о о й точ к о й (вектором), т о ч о й г л о б а ль но го миним ума, а также о п тима ль ным пл а ном.

В М. П. принято выделять следующие разделы. Линейное програмиирование: целевая функция $\varphi(x)$ и ограничения $q_{i}(x)$ и $h_{j}(x)$ линейны; квадратичное проәрамжирование: целевая функция квадратична и выпукла, допустимое множество определяется линейными равенствами и неравенствами; в ы п у к л.о е п р ог р а м м и о в а н и е: целевая функция и допустимое множество выпуклы; дискретное программирование: решение пщется лишь в дискретных, напр. целочисленных, точках множества $X ;$ с т о х а с тическо е програм м и ро в а іне: в отличие от детерминированных задач здесь входная информация носит әлемент неопределенности. Напр., в стохастич. задачах о минимизации линейной функции

\[
\sum_{j=1}^{n} c_{j} x_{j}
\]

при линейных ограничениях

\[
\sum_{j=1}^{n} a_{i j} x_{j} \geqslant b_{i}, \quad i=1,2, \ldots,
\]

либо все величины $c_{j}, a_{i j}, b_{i}$, либо часть из них случайны. Задачи линейного, квадратичного и выпуклого программирования обладают общим свойством: всякая точка локального минимума является оптимальной точкой. Значительно более сложными и менее изученными являются так. наз. многоәкстремальные задачи задачи, для к-рых указанное свойство не выполняется.

В основе теории выпуклого программирования, и. в частности линейного и квадратичного, лежит т е ор е м а $K$ у н а - T а к е $\mathbf{p}$ а необходимых и достаточных условия существования оптимальной точкї $x^{*}$ : для того чтобы точка $x^{*}$ была оптимальной, т. е.

\[
\begin{gathered}
\varphi\left(x^{*}\right)=\min _{x \in X} \varphi(x), \\
X=\left\{x: f_{i}(x) \geqslant 0, \quad i=1,2, \ldots, k\right\},
\end{gathered}
\]

необходимо и достаточно, чтобы существовала такая точка $y^{*}=\left(y_{1}^{*}, y_{2}^{*}, \ldots ., y_{k}^{*}\right)$, чтобы пара точек $x^{*}, y^{*}$ образовывала седло функции Лагранґка

\[
L(x, y)=\varphi(x)+\sum_{i=1}^{k} y_{i} f_{i}(x) .
\]

Последнее означает, что

\[
L\left(x^{*}, y\right) \leqslant L\left(x^{*}, y^{*}\right) \leqslant L\left(x, y^{*}\right)
\]

для любых $x$ и всех $y \geqslant 0$. Если ограничения $f_{i}(x)$ нелинейны, то теорема справедлива при нек-рых дополнительных предположениях о допустимом множестве, напр. в предположении существования такой точки $x \in X$, что $f_{i}(x)>0, i=1,2, \ldots, k,-$ у с л о в и я р е-

![](https://cdn.mathpix.com/cropped/2023_07_08_7d6ab638eb8b65e9fdeag-1.jpg?height=39&width=513&top_left_y=1841&top_left_x=989)

Если функции $\varphi(x)$ и $f_{i}(x)$ диффиеренцируемы, то следующие соотношения определяют седловую точку $\frac{\partial L}{\partial x_{j}} \geqslant 0, \quad j=1,2, \ldots, n$

\[
\begin{gathered}
\sum_{j=1}^{n} \frac{\partial L}{\partial x_{j}} x_{j}=0 ; \quad \frac{\partial L}{\partial y_{i}} \leqslant 0, \quad i=1,2, \ldots, k \\
\sum_{i=1}^{k} \frac{\partial L}{\partial y_{i}} y_{i}=0 ; \quad y_{i} \geqslant 0, \quad i=1,2, \ldots, k .
\end{gathered}
\]

Таким образом, задача выпуклого программирования сводится к решению системы уравнений и неравенств.

На основе теоремы Куна - Такера разработаны различные итерационные методы минимизации, сводящиеся к поиску седловой точки функции Лагранжа.