Функция $J(z)$ наз. также а б с о л ю т ны м и н в ар и а н т о м. Она регулярна в верхней полуплоскости, а внутри фундаментальной области $G$ принимает каждое конечное значение, кроме 0 и 1 , в точности один раз; кроме того, $J(-1 / 2+i \sqrt{3} / 2)=0, J(i)=1$.

В теории эллиптич. функций М. Ф. $J(z)$ играет важную роль, позволяя по заданным вейерштрассовым относительным инвариантам $a=g_{2}, b=g_{3}, a^{3}-27 b^{2} \neq 0$, определить периоды $2 \omega_{1}, 2 \omega_{3}$, а следовательно, и построить все эллиптич. функции Вейерштрасса. Если $\tau$ - единственное в фундаментальной области решение уравнения

\[
J(\tau)=a^{3} /\left(a^{3}-27 b^{2}\right),
\]

то при $a \neq 0, b \neq 0$ имеем $\omega_{1}^{2}=a / b, \omega_{3}=\omega_{1} \tau ;$ при $a=0$ имеем $\tau=-1 / 2+i \sqrt{3 / 2}$ и и $\omega_{1}$ определяется из уравнения

\[
\omega_{1}^{6}=\frac{140}{b} \sum_{m_{1}, m_{2} \in \mathbb{Z}}^{*} \frac{1}{\left(m_{1}+m_{2} \tau\right)^{6}}, \quad \omega_{3}=\omega_{1} \tau
\]

при $b=0$ имеем $\tau=i$, и $\omega_{1}$ определяется из уравнения

\[
\omega_{1}^{4}=\frac{60}{a} \sum_{m_{1}}^{*}, m_{2} \in \mathbb{Z}^{\frac{1}{\left(m_{1}+m_{2} \tau\right)^{4}}}, \quad \omega_{3}=\omega_{1} \tau .
\]

Для построения Якоби эллиптических функций удобнее, вместо $J(z)$, функция

$\lambda(z)=k^{2}(z)=1-\Pi_{n=1}^{\infty}\left(\frac{1-h^{2 n-1}}{1+h^{2 n+1}}\right)^{8}, \quad h=e^{\pi i z}$

также называемая М. Ф. На самом деле $\lambda(z)$ является автоморфной функцией только относительно подгруппы $\Gamma_{2}$ модулярной группы $\Gamma$, причем к $\Gamma_{2}$ относятся все те преобразования вида (1), у к-рых (в качестве до-

![](https://cdn.mathpix.com/cropped/2023_07_08_9d0bc4ed4e76198d8e83g-1.jpg?height=382&width=327&top_left_y=1211&top_left_x=117)
шолнительного условия) $\boldsymbol{a}$ и $d-$ нечетные числа, $b$ и $c$ - четные. Фундаментальная область $G_{2}$ группы $\Gamma_{2}$ изображена на рис. 2 ; это - криволинейный четырехугольник $A B O C A$ с вершинами $A(\infty), B(-1), 0, C(1)$, две стороны к-рого $A B$ и $C A$ - отрезки прямых соответственно $x=-1$ и $x=1$, а $B O$ и $O C$ - дуги окружностей соответственно $|z+1 / 2|=1 / 2$ и $|z-1 / 2|=1 / 2$. Участки границы слеРис. 2. $\quad G_{2}$, а $O C$ и $C A$ не включаются. $G_{2}$, а $O C$ и $C A$ не включаются.
Функция $\lambda(z)$ также регулярна в верхней полуплоскости $\operatorname{Im} z>0$. Внутри области $G_{2}$ она принимает каждое конечное значение, кроме 0 и 1 , в точности один раз; кроме того, $\lambda(\infty)=0$ и $\lambda(0)=1$. При заданном модуле әллиптич. функций Якоби $k$ для их построения необходима величина $\tau=\omega_{3} / \omega_{1}$ или $h=e^{\pi i \tau}$, к-рая однозначно определяется из уравнения $\lambda(\tau)=k^{2}$. Практически, в нормальном случае $0<k<1$ определяют сначала $\varepsilon=\left(1-\sqrt{k^{\prime}}\right) / 2\left(1+\sqrt{k^{\prime}}\right)$, где $k^{\prime}=\sqrt{1-k^{2}}$, а затем строят решение этого уравнения в виде ряда $h=\varepsilon+2 \varepsilon^{5}+15 \varepsilon^{9}+150 \varepsilon^{13}+O\left(\varepsilon^{17}\right)$. M. ф. $\lambda=\lambda(z)$ и $\boldsymbol{J}(z)$ связаны формулой

\[
J(z)=\frac{4}{27} \cdot \frac{\lambda^{2}-\lambda+1}{\lambda^{2}(1-\lambda)^{2}}
\]

M. ф. $w=J(z)$ дает наиболее удобное представление конформных классов римановых поверхностей әллиптич. функций, когда род $g=1$ и эйлерова характеристика $\chi=0$. Каждому значению $w$ соответствует решение $\tau=\omega_{3} / \omega_{1}$ уравнения $J(\tau)=w$, определяющее конформный класс и соответствующее поле әллиптич. функций. Напр., $w=0$ соответствует параллелограмм периодов в виде ромба с углами $120^{\circ}$ и $60^{\circ}$, а $w=1$ - квадрат. М. Ф. применяются также при изучении конформных отображений, граничных свойств аналитических функчий и предельных множеств. М. ф. $w=J(z)$ дает конформное отображение левой половины фундаментальной области $G$ (рис. 1), т. е. криволинейного треугольника $A B C A$, на верхнюю полуплоскость Im $w>0$, причем точки $B, C, A$ переходят соответственно в 0,1 , $\infty$. М. ф. $w=\lambda(z)$ отображает конформно криволинейный треугольник $A B O A$ (рис. 2) на верхнюю полуплоскость, причем точки $B, O, A$ переходят соответственно в $0,1, \infty$.

В геометрич. вопросах часто удобнее принять за область определения М. ф. единичный круг. При әтом модулярная группа (1) переходит в модулярную группу автоморфизмов единичного круга. Напр., удобно применить дробно-линейное преобразование

\[
\zeta=\zeta(z)=\frac{i\left(z-e^{i \pi / 3}\right)}{z-e^{-i \pi / 3}}
\]

переводящее верхнюю полуплоскость $\operatorname{Im} z>0$ в единичный круг $|\zeta|<1$, причем точки $0,1, \infty$ переходят соответственно в точки $A\left(e^{-i 5 \pi / 6}\right), B\left(e^{-i \pi / 6}\right), \quad C(i)$ на единичной окружности $|\zeta|=1$ (рис. 3). Тогда сложная функция $w=\mu(\xi)=\lambda(z(\xi))$ есть М. ф., регулярная в единичном круге и принимающая в нем все значения, кроме 0 , $1, \infty$. Она отображает конформно криволинейный треугольник $A B C A$ (рис. 3) на верхнюю полуплоскость $\operatorname{Im} z>$ $>0 . \cdot$ Именно эта М. ф. $\mu(\zeta)$ используется при доказательстве Пикара теорем и в ряде других геометрических вопро-

![](https://cdn.mathpix.com/cropped/2023_07_08_9d0bc4ed4e76198d8e83g-1.jpg?height=382&width=360&top_left_y=851&top_left_x=1467)

Puc. 3 . сов.

лит.: [1] г у р в и и А., К у р а н т Р., Теория функций, пер. [с нем.], м., 1968; [2] А х и е з е р Н. И., Элементы теории эллиптических функций, 2 изд., М., 1970; [3] Ф о p Д P., АвтоF r i c $\mathrm{k}$ e R., Vorlesungen über die Theorie der elliptischen Modulfunktionen, Bd 1-2, Lpz., 1890-92. Е. Д. Соломенчев.

МОДУЛЯРНЫЙ ИДЕАЛ - правый (левый) идеал $J$ кольца $R$, обладающий следующим свойством: в кольце $R$ найдется хотя бы один такой әлемент $e$, что для всех $x$ из $R$ разность $x-e x$ принадлежит $J$ (соответственно $x-x e \in J)$. Әлемент $e$ наз. л е в о й (п р аво й е Динице й по мод у ли иде а ла $\boldsymbol{J}$ и. В кольце с единицей всякий идеал является модулярным. Всякий собственный модулярный правый (левый) идеал можно вложить в максималыный правый (левый) идеал, к-рый автоматически будет модулярным. Пересечение всех максималыных модулярных правых идеалов ассоциативного кольца совпадает с пересечением всех максимальных левых идеалов модулярных и является Джекобсона радикалом этого кольца. М. и. иногда наз. также р е г у л я р ны м и и д е ал а М И.

Лит.: [1] Д ж е к о б с о н Н., Строение колец, пер. с англ., M., 1961 . МОДУС ПОНЕНС (modus ponens), п р а в и Л о о тд е л е н и я, - вывода правило в формальных логич. системах. Правило М. П. записывается в виде схемы

\[
\frac{A \supset B}{B},
\]

где $A$ и $B$ - обозначения для формул формальной логич. системы, а $\supset-$ логич. связка импликации. M. п. разрешает выводить $B$ из посылок $A$ (м а л а я п о сыл к а) и $A \supset B$ (б оль ш а я посы л к а). Если в нек-рой интерпретации формальной системы формулы $A$ и $A \supset B$ истинны, то по смыслу пмпликации истинна формула $B$. М. п. вместе с другими правилами