содержательных соображений нек-рых минималыных допустимых значений $f_{i}^{0}$ и в последующем нахождении допустимого $x$, максимıзирующего $\prod_{i=1}^{n}\left(f_{i}(x)-f_{i}^{0}\right)$ (см. также Арбитражная схема).

М. З. можно рассматривать как игру (см. Иәр пеория) и подходить к ее решению на основе различных теоретико-игровых методов. Напр., если допустимое решение $x$ выбирается с целью максимизировать оцну из целевых функций $f_{1}, \ldots, f_{n}$, но какую именно - для принимающего решение субъекта неизвестно, то можно воспользоваться взвешенной суммой этих функций, взяв в качестве весов компоненты смешанной стратегии «природы». Возможны трактовки М. 3. как бескоалиционной игры, в том числе с позиций кооперативной теории (см. Кооперативная игра), и применения связанных с этим принципов оптимальности.

![](https://cdn.mathpix.com/cropped/2023_07_08_dafb71528f9ff4ebc74ag-1.jpg?height=38&width=794&top_left_y=672&top_left_x=154)
пер. с англ., М., 1961 .

МНОГОЛИСТНАЯ ОБЛАСТБ - область $S$ римановой поверхности $R$, рассматриваемой как накрывающая поверхность над плоскостью комплексного переменного $\mathbb{C}$, такая, что над каждої точкой ее проекции $D \subset \mathbb{C}$ расположены не менее двух точек $S$; ветвления точк $\boldsymbol{R} \boldsymbol{R}$ порядка $k-1$ считается при этом за $k$ точек. Наір., аналитич. функция $w=z^{2}$ отображает взаимно оцнозначно круг $D=\{z \in \mathbb{C}:|z|<1\}$ на двулистную область (двулистный круг) $S=\{w \in R:|w|<1\}$ римановой поверхности $\boldsymbol{R}$ этой функции; всюду, кроме начала координат, это отображение конформно.

Для аналитич. функций многих комплексных переменных также возникают многолистные римановы области над комплексным пространством $\mathbb{C}^{n}$.

Е. Д. Соломенчев.

МНОГОЛИСТНАЯ ФУНКЦИЯ - понятие, естественным образом обобщающее понятіе однолистной бункции. Функция $f(z)$, регулярная или мероморфная в области $D$ комплексной плоскости $z$, наз. $p$-л ІІ с т- $^{-}$ н о й в $D(p=1,2, \ldots)$, если она принимает в этой области каждое свое значение не более $p$ раз, т. е. если число корней уравнения $f(z)=w$ в. области $D$ при любом $w$ не превосходит $p$. Геометрически это означает, что над каждой точкой плоскости $w$ лежит не более $p$ точек римановой поверхности, на к-рую функция $w=$ $=f(z)$ отображает область $D$. При $p=1$ функция $f(z)$ является однолистной в области $D$.

Наряду с этим простейшим классом р-листных функций большую роль в теории М. Ф. играют функции, p-листные в нек-ром обобщенном смысле, "p-листные в среднем». Пусть функция $f(z)$ регулярна или мероморфна в области $D$ плоскости $z, n(w)$ - число корней уравнения $f(z)=w$ в $D$ и $p$ - положительное число. Функция $f(z)$ наз. $p-л$ и с т н о й в с р е д н е м п о о к р у ж н о т и в $D$, если для всех $R>0$ выполняется условие:

\[
\frac{1}{2 \pi} \int_{0}^{2 \pi} n\left(R e^{i \varphi}\right) d \varphi \leqslant p
\]

Геометрически это означает, что линейная мера дуг, принадлежащих римановой поверхности, на к-рую функция $w=f(z)$ отображает область $D$, и проектирующихся в любую окружность $|w|=R$, не превосходит $p$ длин таких окружностей. Функція $f(z)$ наз. $p$-л и с тно й в с р е дем по пло щ а п в $D$, если

\[
\int_{0}^{R}\left(\int_{0}^{2 \pi} n\left(\rho e^{i \varphi}\right) d \varphi\right) \rho d \rho \leqslant p . \pi R^{2}
\]

для всех $\boldsymbol{R}>0$. Геометрически это означает, что площадь проектирующейся в любой круг $|w|<R$ части римановой поверхности, на к-рую функция $w=f(z)$ отображает область $D$, не превосходит $p$ площадей таких кругов. Из этих определений следует, что функция, $p$-листная в нек-рой области, является в ней и $p$-листной в сред- нем по окружности, а функция, р-листная в среднем по окружності, являстся $p$-листной в среднем по площади. Функция, $p$-листная в среднем, может оказаться бесконечнолистной.

М. Ф., как и однолистные, изучаются в разлічных направлениях: с точки зрения характеристики искажения области при ее отображениях этими функциями, оценки коэффициентов рядов, представляющих эти функции, и т. д. Они обладают многими әкстремальными свойствами, аналогичными әкстремальным свойствам однолистных функций. Напр., имеются следующие обобщения на случай $p$-листных функций двух классич. результатов теориі однолистных функций - площадей принципа и оценкі второго коэффициента (см. Бибербаха гипотеза).

Если функция

$F(\zeta)=\sum_{m=1}^{p} \alpha_{m} \zeta^{m}+\sum_{n=0}^{\infty} \frac{a_{n}}{\xi^{n}}, \alpha_{p} \neq 0,|\zeta|>1$,

$p^{\text {-листна и регулярна в области }|\zeta|>1 \text {, за пссключением }}$ полюса в точке $\zeta=\infty$, то

\[
\sum_{n=1}^{\infty} n\left|a_{n}\right|^{2} \leqslant \sum_{m=1}^{p} m\left|\alpha_{m}\right|^{2}
\]

Если функция

\[
f(z)=z^{p}+a_{p+1} z^{p+1}+\ldots
\]

регулярна іг $p$-листна в круге $|z|<1$, то

\[
\left|a_{p+1}\right| \leqslant 2 p
\]

Неравенства (2) и (4) не могут быть улучшены. Эти два результата относятся к наиболее ранним основным результатам теории $p$-листных функций. Неравенство (2) доказано также для функций вида (1), $p$-листных в среднем по площади в $|\zeta|>1$, а неравенство (4) - для функций вида (3), р-листных в среднем по площади в $|z|<1$

Значительно продвинуть исследование класса $p$-лістных функций позволило рассмотрение его как подкласса функций, $p$-листных в среднем. Получены для $p$-лшстных функций и точные аналоги основных теорем пскаженія и покрытия, шзвестных для однолистных функций (см. Искажения теоремы, Покрытия теоремь), именно: для функций $f(z)$ вида (3), p-листных в среднем по окружности в круге $|z|<1$, верны точные оценки:

\[
\begin{gathered}
\frac{|z|^{p}}{(1+|z|)^{2 p}} \leqslant|f(z)| \leqslant \frac{|z|^{p}}{(1-i z \mid)^{2 p}}, \\
\left|f^{\prime}(z)\right|<p|z|^{p-1} \cdot \frac{1+|z|}{(1-z \mid)^{2 p+1}},|z|<1 ;
\end{gathered}
\]

функция $f(z)$ принимает в $|z|<1$ каждое значение $w$ c $|w|<1 / 4^{p}$ ровно $p$ раз (прямой аналог теоремы покрытия Кёбе). Этим последним свойством обладают и функции $f(z)$ вида (3), p-листные в среднем по площади в $|z|<1$. Для функций, $p$-листных в среднем по окружности, получен ряд неулучшаемых результатов, характеризующих рост их коәффициентов. Так, для функции вида

\[
f(z)=\sum_{n=0}^{\infty} a_{n} z^{n}
\]

$p$-листной в среднем по окружности в круге $|z|<1$, $p>0$, существует, и притом конечный, предел

\[
\alpha=\lim _{r \rightarrow 1-0}(1-r)^{2 p} \max _{|z|=r}|f(z)|
\]

II

\[
\lim _{n \rightarrow \infty}\left|a_{n}\right| / n^{2 p-1}=\alpha / \Gamma(2 p)
\]

при $p>1 / 4$. Всякий раз, когда получается оценка для $\alpha$, отсюда следует и соответствующая точная оценка