с заданными (однородными) краевыми условиями на границе области изменения переменных $(x, t)$ наз. функция $G(x, t ; \xi, \tau)$, удовлетворяющая при каждом $(\xi, \tau)$ из этой области уравнению

\[
L(x, t ; D) G(x, t ; \xi, \tau)=\delta(x-\xi, t-\tau) .
\]

В физич. ситуациях функция Грина $G(x, t ; \xi$, $\tau)$ описывает возмущение от точечного (в точке $\xi$ ) мгновенного (в момент $\tau$ ) источника интенсивности 1 (с учетом неоднородности среды и краевого эффекта). В случае шостоянных коәффициентов и отсутствия границы функция Грина при $\boldsymbol{\xi}=0$ и $\tau=0$ наз. ф у нд а ме н т а л ьны м $\mathrm{p}$ е ше н и е м и обозначается $E(x, t)$,

\[
L(D) E(x, t)=\delta(x, t) \text {. }
\]

Доказано существование фундаментального решения из $D^{\prime}$ и $S^{\prime}$ для любого оператора $L(D) \neq 0$.

П им е ры фу у д а мента льных решен и ї. Волновое уравнение

\[
\begin{gathered}
E_{1}(x, t)=\frac{\theta(a t-|x|)}{2 a}, \quad E_{2}(x, t)=\frac{\theta(a t-|x|)}{2 \pi a \sqrt{a^{2} t^{2}-|x|^{2}}}, \\
E_{3}(x, t)=\frac{1}{2 \pi a} \delta_{+}\left(a^{2} t^{2}-|x|^{2}\right),
\end{gathered}
\]

где $\theta(t)$ - функция Хевисайда: $\theta(t)=0$ ври $t<0$; $\theta(t)=1$ при $t \geqslant 0$.

Уравнение теплопроводности:

\[
E_{n}(x, t)=\frac{\theta(t)}{\left(2 a V^{\prime} \overline{\pi t}\right)^{n}} e^{-|x|^{2} / 4 a^{2} t}
\]

Уравнение Лапласа:

$E_{1}(x)=\frac{1}{2}|x|, \quad E_{2}(x)=\frac{1}{2 \pi} \ln |x|, \quad E_{3}(x)=-\frac{1}{4 \pi|x|}$.

С помощью фундаментального решения $E(x, t)$ решение $u(x, t)$ уравнения

\[
L(D) u=F(x, t)
\]

с произвольной правой частью $F \in D^{\prime}$ выражается во всем пространстве $\mathbb{R}^{n+1}$ сверткой

\[
u=F * E,
\]

если она существует в $D^{\prime}$.

В физпч. ситуациях смысл формулы (22) следующиї: это есть суммарное наложение әлементарных возмущений $F(\xi, \tau) E(x-\xi, t-\tau)$ от точечных источников $F(\xi, \tau) \delta(x-\xi, t-\tau)$, на к-рые разлагается источник $F(x, t)$ в силу тождества $F=F * \delta$. При этом свертка $F * E$ играет роль соответствующего потенциала с источником (Плотностьо) $F$. В этом состоит сущность метода точечного источника решения линейных задач математич. физики.

В частности, решения обобщенной задачи Коши для волнового уравнения (и уравнения теплопроводности) выражается в о л н о в м ( т е пло в ы м) по те нц и а ло м

\[
u=F * E_{n} .
\]

Из формулы $\left(22^{\prime}\right)$ при надлежащих предположениях о гладкості источника

\[
F(x, t)=u_{0}(x) \delta^{\prime}(t)+u_{1}(x) \delta(t)+f(x, t)
\]

следуют классич. формулы решения задач Коши. Напр., для волнового уравнения в пространстве

Кирхаоба формула:

\[
\begin{aligned}
u(x, t)= & \frac{1}{4 \pi a^{2}} \int_{|x-\xi|<a t} f\left(\xi, t-\frac{|x-\xi|}{a}\right) \frac{d \xi}{|x-\xi|}+ \\
& +\frac{1}{4 \pi a^{2} t} \int_{|x-\xi|=a t} u_{1}(\xi) d S+ \\
& +\frac{1}{4 \pi a^{2}} \frac{\partial}{\partial t}\left[\frac{1}{t} \int_{|x-\xi|=a t} u_{0}(\xi) d S\right] .
\end{aligned}
\]

Для уравнения теплопроводности - Пуассона формула: $u(x, t)=\int_{0}^{t} \int \frac{f(\xi, \tau)}{[2 a \sqrt{\pi(t-\tau)}]^{n}} e^{-|x-\xi|^{2} / 4 a^{2}(t-\tau)} d \xi d \tau+$

\[
+\frac{1}{(2 a \sqrt{\pi t})^{n}} \int u_{0}(\xi) e^{-|x-\xi|^{2} / 4 a^{2} t} d \xi .
\]

Таким же путем, строя функцию Грина для уравнения Лапласа для шара, получают решение внутренней задачи Дирихле для (трехмерного) шара $|x|<R$ в виде Пуассона интеграла:

\[
u(x)=\frac{1}{4 \pi R} \int_{|\xi|=R} \frac{R^{2}-|x|^{2}}{|x-\xi|^{3}} u_{0}(\xi) d S_{\xi} .
\]

Для исследования и приближенного решения сме-

![](https://cdn.mathpix.com/cropped/2023_07_08_914cf68816d6bd2d8c02g-1.jpg?height=38&width=834&top_left_y=616&top_left_x=992)
переменных) при условии, что коэффициенты в уравнении и в граничном условии не зависят от времени $t$. Идея метода, применительно, напр., к задаче (3), (10), (18) состоит в следующем: искомое решение $u(x, t)$ и правая часть $f(x, t)$ разлагаются в ряд Фурье по собственным функциям $\left\{u_{k}\right\}$ краевой задачи (17), (18) $u(x, t)=\sum_{k=1}^{\infty} b_{k}(t) u_{k}(x), f(x, t)=\sum_{k=1}^{\infty} c_{k}(t) u_{k}(x)$.

Подставляя формально эти ряды в уравнение (3), для неизвестных функций $b_{k}(t)$ получают уравнение:

\[
b_{k}^{\prime}(t)+\lambda_{k} b_{k}(t)=c_{k}(t), \quad k=1,2, \ldots
\]

При әтом, чтобы ряд (26) для $u$ удовлетворял начальному условию (10), необходимо положить

\[
b_{k}(0)=\int_{G} \rho(x) u_{0}(x) u_{k}(x) d x=a_{k} .
\]

Решая задачу Коши (27), (28), получают формальное решение задачи (3), (10), (18) в виде ряда:

$u(x, t)=\sum_{k=1}^{\infty}\left[a_{k} e^{-\lambda_{k} t}+\int_{0}^{t} e^{-\lambda_{k}(t-\tau)} c_{k}(\tau) d \tau\right] u_{k}(x)$.

Возникает задача обоснования метода Фурье: когда формальный ряд (29) даст классическое или обобщенное решение задачи (3), (10), (18)?

При обосновании метода Фурье и, вообще, при установлении корректности смешанной задачи для уравнения диффузии (3) используется максимума принцип.

Аналогично метод Фурье применяется и к смешанной задаче (1), (9), (18) для уравнения колебаний. В этом случае оказывается полезным метод энергии интеграла.

Метод разделения переменных находит применение также и для решения краевых задач для уравнения эллиптич. типа (5), в частности для вычисления собственных функций и собстзенных значений при условии, что область $G$ обладает достаточной симметрией.

Для исследования и приближенного решения краевых задач для уравнения (5) широко используются вариационные методы. Так, напр., для задачи на собственные значения (17), (18) (при $\rho=1)$ собственные значения $\lambda_{k}$ удовлетворяют вариационному принципу:

\[
\lambda_{k}=\inf _{\left(u, u_{i}\right)=0, i=1, \ldots, k-1} \frac{(L u, u)}{\|u\|^{2}},
\]

где функции сравнения $u(x)$ предполагаются из класса $C^{2}(\hat{G})$ и удовлетворяют граничному условию (18); при этом inf в (30) реализуется на любой собственной функции, соответствующей собственному значению $\lambda_{k}$, и только на них.

При исследовании краевых задач для уравнения (5) (в частности, для гармонич. функций) применяется принцип максимума.