ференциальных уравнений 1-го порядка:

\[
y^{\prime}=f(x, y), y(a)=b .
\]

В М. м. ІІспользуется конечноразностная формула:

\[
y_{i}-y_{i-2}=2 h f\left(x_{i-1}, y_{i-1}\right) \text {, }
\]

где

\[
x_{i}=a+i h, \quad i=0,1,2, \ldots
\]

Для вычисления по этой формуле необходимо какимліюо иным способом найти дополнительное начальное значение $y_{1} \approx y\left(x_{1}\right)$. М. М. пмеет 2 -й порядок точности, устойчив по Далквисту, т. е. все решения однородного разностного уравнения $y_{i}-y_{i-2}=0$ ограничены равномерно по $h$ при $i=0,1, \ldots,\left[\frac{A-a}{h}\right]$ для любого фиксированного отрезка $[a, A]$. Для устойчивости по Далквисту достаточно, чтобы простые корни характеристІч. многочлена левой части разностного уравнения не превосходили по модулю едіницы, а кратные -были по модулі строго меньше единищы. В данном случае характерістич. многочлен $\rho(\lambda)=\lambda^{2}-1$ имеет корни $\lambda= \pm 1$ и, следовательно, удовлетворяет указанному условию устойчивости. Однако при решении систем уравнений $y^{\prime}=A y$ с матрицей $A$, имеющей отрицательные собственные значения, происходит быстрый рост вычислительной погрешности.

П р е д ск а зы в а юоце - ІІ с пра в ля ю шй М. м. использует пару конечноразностных формул: предсказывающуіо

\[
\bar{y}_{i}=y_{i-4}+\frac{4 h}{3}\left(2 f_{i-3}+f_{i-2}+2 f_{i-1}\right), i=4,5, \ldots,
\]

и пгсправляющую

\[
\overline{\bar{y}}_{i}=y_{i-2}+\frac{h}{3}\left(f_{i}+4 f_{i-1}+f_{i-2}\right), i=4,5, \ldots,
\]

где

\[
f_{i}=f\left(x_{i}, y_{i}\right), \quad \bar{f}_{i}=f\left(x_{i}, \bar{y}_{i}\right) .
\]

В качестве приближенного выражения погрешности берется величина

\[
\varepsilon_{i}=\frac{1}{29}\left(\bar{y}_{i}-\bar{y}_{i}\right)
\]

Дополнительные начальные значения $y_{j} \approx y\left(x_{j}\right), j:=$ $=1,2,3$, вычисляютс я каким-либо иным способом, напр. методом Рунге - Кутта, имеющим четвертый порядок точности. Метод предложен в [3].

Лum.: [1] Б а х в а л о в Н. С., Численные методы, 2 изд., M., $1975 ;[2]$ Д е м и д о в и ч Б. П., М а р о н И. А., ШII., функций, дифференциальные уравнения, М., 1962; [3] М и л н Ф. Э., Численное решение дифференциальных уравнений, пер. с англ., М., 1955.

МИЛНА ПРОБЛЕМА - проблема теории переноса Іззучения о решении односкоростного кинетич. уравнения переноса квантов илі частиц для полупространства. Впервые интегральное уравнение М. П. с источником на бесконечности прг нулевом потоке падающего извне излучения было выведено Э. Милном [1] для случая изотропного рассеянія квантов, распространяюшихся без поглощения в звездной атмосфере.

У р а в не ние

\[
B(x)=\frac{1}{2} \int_{0}^{\infty} B(t) E_{1}(|x-t|) d t .
\]

Здесь $B(x)$ - плотность излучения (или частиц),

\[
E_{1}(x)=\int_{0}^{1} \frac{e^{-x / \mu}}{\mu} d \mu
\]

- интегро-показательная функция $\left(E_{1}(x)=-\mathrm{Ei}(-x)\right)$. В нейтронной физике М. п. используется для постановки приближенных гранічных условий при ре- шении уравнений диффузионного приближения в ограниченной области; при этом учитываются захват нейтронов в среде, анизотропия рассеяния и гривизна границы.

Здесь М. П. состоит в репении интегро-диффференціального уравнения

\[
\mu \frac{\partial \psi}{\partial x}+\psi(x, \mu)=\frac{c}{2} \int_{-1}^{+1} p\left(\mu, \mu^{\prime}\right) \psi\left(x, \mu^{\prime}\right) d \mu^{\prime}
\]

с краевым условием на границе полупространства, заполненного веществом, с вакуумом

\[
\psi(0, \mu)=0 \text { для } 0<\mu \leqslant 1 \text {, }
\]

где $c$ есть среднее число вторичных нейтронов, приходящееся на одно соударение с ядром $(c<1$ в рассеиваюцем и поглощающем нейтроны веществе), $p\left(\mu, \mu^{\prime}\right)$ индикатриса рассеяния $\left(p\left(\mu, \mu^{\prime}\right)=1\right.$ при изотропном рассеянии). Аналогично ставится сферическая или цилиндрическая М. п. о распределении нейтронов в пространстве вне поглощающей сферы или цилиндра.

Решение М. п. удобно проводить, применяя преобразование Лапласа к интегро-дифференциальному уравнению переноса (см. [3]) и используя для решения получающихся функциональных уравнений $B$ инераХопба метод.

Для решения М. п. было предложено использовать разложение по обобщенным собственным функциям и методы ретения сингулярных интегральных уравнений (см. [4]). Решение М. п. при $p\left(\mu, \mu^{\prime}\right)=1, c<1$ ищется в виде

\[
\psi(x, \mu)=\psi_{0-}(x, \mu)+a_{0+} \psi_{0+}(x, \mu)+\int_{0}^{1} A(v) \psi v(x, \mu) d v,
\]

где

\[
\begin{gathered}
\psi_{v}(x, \mu)=\varphi_{v}(\mu) e^{-x / v}, \\
\varphi_{v}(\mu)=(c v / 2) P \frac{1}{v-\mu}+\lambda(v) \delta(v-\mu)
\end{gathered}
\]

- собственные функции непрерывного спектра, $P$ символ главного значения по Коши, $\delta(v-\mu)$ есть $\delta$ фуукция Дирака,

\[
\lambda(v)=1-v c \text { Arth } v, \quad \psi_{0 \pm}=\varphi_{0 \pm}(\mu) e^{\mp x / v_{0}} .
\]

Дискретные собственные значения $\pm v_{0}$ суть корни характеристич. уравнения

\[
v c \operatorname{Arth} \frac{1}{v}=1 \text {, }
\]

- собственные функции дискретного спектра имеют вид

\[
\varphi_{0 \pm}(\mu)= \pm\left(\frac{c v_{0}}{2}\right) \frac{1}{ \pm v_{0}-\mu}
\]

Система собственных функций $\varphi_{0+}(\mu)$ и $\varphi_{v}(\mu), 0 \leqslant v \leqslant 1$, оказывается полной в пространстве обобщенных функций на отрезке $0 \leqslant \mu \leqslant 1$ и ортогональной с весом $W(\mu)$, к-рый находится как решение сингулярного интегрального уравнения (см. [4]).

Граничное условие (2) М. П. дает $(\mu \geqslant 0)$ :

\[
-\varphi_{0-}(\mu)=a_{0+} \varphi_{0+}(\mu)+\int_{0}^{1} A(v) \varphi_{v}(\mu) d v,
\]

то есть $a_{0+}$ и $A(v)$ определяются как коэффициенты разложения функции

\[
\varphi_{0}-(\mu)=\left(c v_{0} / 2\right) \frac{1}{v_{0}+\mu} .
\]

Асимптотич. плотность нейтронов

\[
\begin{gathered}
B_{a c}(x)=2 \pi \int_{-1}^{+1}\left[\psi_{0}-(x, \mu)+a_{0+} \psi_{0+}(x, \mu)\right] d \mu= \\
=4 \pi e^{-x_{0} / v_{0}} \operatorname{sh} \frac{x+x_{0}}{v_{0}}
\end{gathered}
\]