Для общего әллиптич. уравнения порядка $2 m$

\[
L u=\sum_{|\alpha| \leqslant 2 m} a_{\alpha}(x) \frac{\partial^{\alpha} u}{\partial x^{\alpha}}=f(x), x \in D,
\]

краевые условия могут задаваться с помощью линейных диффференциальных операторов

$\boldsymbol{B}_{j} u=\sum_{|\alpha| \leqslant m_{j}} b_{j \alpha}(y) \frac{\partial^{\alpha} u}{\partial x^{\alpha}}=\varphi_{j}(y), y \in S, 1 \leqslant j \leqslant m$,

порядка $m_{j}<2 m$ с коәффициентами, определенными на границе $S$ области $D$. Если операторы $L$ и $B_{j}$ удовлетворяют так наз. условию дополнительности, то производные порядка $2 m$ функции $u$, удовлетворяющей граничным условиям, можно оценить (в нек-рой норме) через норму $f$ в (5) и подходящие нормы граничных функций $\varphi_{j}$ в (6). К. з. такого типа наз. коәрцитивными К. 3. Другой тип К. з. представляют так наз. смешанные задачи, в к-рых на смежных участках границы задаются различные краевые условия.

Для эллиптич. уравнений характерно то, что краевые условия задаются на всей границе. Однако в полной мере это относится только к равномерно эллиптич. уравнениям. Если оператор $L$ в (3) эллиптичен внутри области и на части $S_{0} \subseteq S$ параболически вырождается, то в зависимости от характера вырождения участок $S_{0}$ от задания краевых условий может освобождаться. См. также Краевая задача для әллиптического уравнения.

Если уравнение (3) не принадлежит к әллиптич. типу, то часть границы от задания краевых условий, как правило, освобождается. Напр., для простейшего уравнения параболич. типа - уравнения теплопроводности

\[
L u=\frac{\partial^{2} u}{\partial x^{2}}-\frac{\partial u}{\partial t}=0
\]

задача Дирихле в области $D$, ограниченной прямыми $x= \pm 1, t= \pm 1$, состоит в задании граничных значений Функции $u$ на отрезках $\{t=-1,-1 \leqslant x \leqslant+1\}$ и $\{x= \pm 1$, $-1 \leqslant t \leqslant 1\}$.

Специальным образом ставятся $\mathbf{K}$. з. для уравнений смешанного әллиптико-гиперболич. типа.

Важное место занимают К. з. в теории аналитич. функций. Пусть $S$ - кусочно гладкая линия на плоскости, т. е. объединение конечного числа простых ориентируемых дуг. 3 а д а ч а л и н е й н о г о с оп р я ж е н и я заключается в определении аналитической вне $S$ функции $\varphi(z)$, имеющей предельные значения $\varphi^{ \pm}(t), t \in S$, с обеих сторон $S$ и удовлетворяющей краевому условию

\[
\varphi^{+}(t)-G(t) \varphi^{-}(t)=g(t), t \in S,
\]

где $G(t)$ и $g(t)$ - заданные функции. С помощью представлений аналитич. функций интегралами типа Коши при некоторых предположениях относительно функций $G, g$ и линии $S$ решения әтой задачи выписываются в явном виде. См. Граничные задачи теории аналитических бункций.

Для изучения К. з. предложен ряд методов. ІІ варца альтернирующий метод и связанные с ними выметания метод Пуанкаре и Перрона метод опираются на применение принципа максимума. Решение К. З. с помощью ивтегральных уравнений основано на различных интегральных представлениях решений. Исследование $\boldsymbol{K}$. 3. с помощью априорных оценок относится к функциональным методам. Широко применяется теория обобщенных функций. В практических приложениях значительное распространение получили различные конечноразностные методы.

![](https://cdn.mathpix.com/cropped/2023_07_08_7cd74e37440aac9a2c02g-1.jpg?height=39&width=792&top_left_y=2243&top_left_x=161)
пения с частными производными, пер. с англ., М., 1966; [2] Б и ц а д з е А. В., Краевые задачи для әллиптических урав- нений второго порядка, М., 1966; [3] К у р а н т Р., Уравнения с частными производными, пер. с англ., М., 1964; [4] J а д ыж е н с к а я О. А., Краевые задачи математической физики, ными әллиптического типа, пер. с итал., М., 1957: [6] М у с х ел и ші в и л и Н. И., Сингулярные интегральные уравнения, З изд., М., 1968; [7] Т и х о но в А. Н., С а м а р с к и й А. А., Уравнения математической физики, ч изд., М., 1972.
Урале

КРАЕВАЯ ЗАДАЧА д Л Я Ә Л Л И П Т И ч е с К о Г о у р а в н е н я - задача отыскания регулярного в области $D$ решения $u$ әллиптического уравнения

\[
\sum_{i, k=0}^{n} a_{i k} \frac{\partial^{2} u}{\partial x_{i} \partial x_{k}}+\sum_{i=0}^{n} b_{i} \frac{\partial u}{\partial x_{i}}+c u=f,
\]

удовлетворяющего нек-рым дополнительным условиям на границе $\Gamma$ области $D$.

Классические К. З. являются частными случаями следующей задачи: найти регулярное в области $D$ решение уравнения (1), удовлетворяющее на границе Г условию

\[
a \frac{d u}{d l}+b u=g
\]

где $d / d l$ - производная по нек-рому направлению; $a, b$ и $g$ - заданные непрерывные на Г функции, причем $|a|+|b|>0$ всюду на $\Gamma$ (см. [1]).

![](https://cdn.mathpix.com/cropped/2023_07_08_7cd74e37440aac9a2c02g-1.jpg?height=38&width=788&top_left_y=884&top_left_x=1030)
$a=1$ - задача с косой производной (см. Дифференчиальное уравнение $с$ частными производными; задача с косой производной), к-рая переходит в Неймана задачу, если направление $l$ совпадает с направлением конормали. Если $\Gamma=\bar{\Gamma}_{1} \cup \bar{\Gamma}_{2}$, где $\Gamma_{1}$ и $\Gamma_{2}=$ непересекающиеся открытые подмножества $\Gamma$, а $\bar{\Gamma}_{1} \cap \bar{\Gamma}_{2}$ либо является ( $n-2)$-мерным многообразием, либо пусто, и $\boldsymbol{a}=1$, $b=0$ на $\Gamma_{1}, a=0, b=1$ на $\Gamma_{2}$, то получается смешанная задача.

Задача (2) изучалась для эллиптич. уравнений с двумя независимыми переменными (см. [2]). Довольно полно исследованы задача Дирихле для әллиптич. уравнений с любым конечным числом независимых переменных (см. [1], [3], [4]) и задача с косой производной в том случае, когда направление $l$ ни в одной точке $\Gamma$ не выходит в касательную к Г плоскость. В этом случае задача с наклонной производной - фредгольмова и решение имеет такую же гладкость, как и поле направлений $l$ и функция $g$ (см. [1]). Изучался случай, когда $l$ выходит в касательную к $\Gamma$ плоскость в нек-рых точках $\Gamma$ (см. [3]). Были исследованы локальные свойства решений задачи с косой производной (см. [5]). В точках выхода поля $l$ в касательную к $\Gamma$ плоскость решение задачі менее гладкое, чем поле $l$ и функция $g$. На основании этого исследована задача в обобщенної постановке (см. [7], [8]).

Пусть краевое условие для регулярных в единичном шаре $\Sigma \subset \mathbb{R}^{3}$ гармонич. функций имеет вид

\[
a u_{x}+b u_{y}+c u_{z}=g
\]

$K$ - множество точек единичной сферы $S$, в к-рых обращается в нуль функция $\omega=a x+b y+c z$. Векторное поле $\boldsymbol{P}(a, b, c)$ по множеству $K$ выходит в касательную к единичной сфере $S$ плоскость. Пусть, кроме того, $K$ состоит из конечного числа непересекающихся кривых, $K^{+}$- подмножество $K$, состоящее из таких точек, в к-рых grad $\omega$ составляет острый угол с проекцией поля $\boldsymbol{P}$ на сферу $S$, и $K^{-}$- оставшаяся часть $K$. Обобщенная постановка задачи заключается в дополнительном задании значений $u$ на $K^{+}$, но на множестве $K^{-}$допускаются интегрируемые особенности у решения $u$. В случае, когда $K^{-}$пусто, за счет повышения гладкости дополнительных данных задачи можно сделать сколь угодно гладким решение обобщенной задачи. Решение смешанной задачи на множестве $\Gamma_{0}=\bar{\Gamma}_{1} \cap \bar{\Gamma}_{2}$, вообще говоря, имеет особенности (см. [1]). Для того чтобы это решение