ных чисел $\left\{a_{k}\right\}_{k=1}^{q}$ из расширенной комплексной плоскости имеет место соотношение

$\sum_{k=1}^{q} m\left(r, a_{k}, f\right) \leqslant 2 T(r, f)-N_{1}(r, f)+S(r, f)$,

где

\[
N_{1}(r, f)=2 N(r, \infty, f)-N\left(r, \infty, f^{\prime}\right),
\]

а величина $S(r, f)$ обладает следующими свойствами. 1) Если $R=\infty$, т. е. $f(\bar{c})$ мероморфна во всей открытой комплексной плоскости, то при $r \rightarrow \infty$

\[
S(r, f)=O(\ln (r \cdot T(r, f)))
\]

для всех значений $r$, за возможным искліочением некоторого множества $E$ такого, что

\[
\int_{E_{\cap}[1, \infty)} \frac{d r}{r}<\infty \text {. }
\]

2) Если $R<\infty$, то при $r \rightarrow R$

\[
S(r, f)=O\left(\ln \left(\frac{\boldsymbol{R}}{\boldsymbol{R}-r} T(r, f)\right)\right)
\]

для всех значений $r$, за возможным исключением некоторого множества $E$ такого, что

\[
\int_{E} \frac{d r}{R-r}<\infty
\]

Функция $N_{1}(r, f)$ не убывает с ростом $r$, поэтому правая часть в соотношении (2) при $r \rightarrow R$ вне нек-рого исключительного множества $E$ не может возрастать быстрее, чем $2 T(r, f)$.

Лum.: [1] Н е в а н л и н н а Р., Однозначные аналитические функции, пер. с нем., M.- JI., 1941; [2] N e v a n l i n n a R., phes, P., 1929; [3] W e y l H., W e y l J., Meromorphic functions and analytic curves, Princeton, $1943 ;[4]$ A h If o r s L., "Acta Soc. scient. fennica. Nova ser. A», 1941, v. 3, 스 4, p. 1-31; [5] C a r t a n H., "Mathematica" (Cluj), 1933 , v. 7, p. 5-31; [6] Г р и ф ф и т с Ф., К и н г Д ж., Теория Неванлинны и
голоморфные отображения алгебраических многообразий, пер. с англ., М., 1976; [7] ПI е т р е н к о В. П., Рост мероморфных функций, Хар., 1978.

НЕВАНЛИННЫІ - ПИКА ПРОБЛЕМА - проблема для класса 52 аналитич. функций в области $G$ комплексной плоскости (или, более общо, римановой поверхности), заключающцаяся в нахождении условий, необходимых п достаточных для разрешимости в классе функций $\mathfrak{S}_{2}$ интерполяционной задачи

\[
f\left(z_{\alpha}\right)=w_{\alpha}
\]

где $\left\{z_{\alpha}\right\}$ - подмножество точек области $G,\left\{w_{\alpha}\right\}-$ нек-рое множество комплексных чисел, а $\alpha$, как правило, пробегаст счетное (иногда конечное или даже несчетное) множество индексов. Классич. результат $\Gamma$. Пика [1] и Р. Неванлинны [2] (соответственно для конечных и счетных подмножеств $\left.\left\{z_{\alpha}\right\} \subset G\right)$ дает решение Н.-П. П., напр., для класса $B_{1}$ аналитич. функций в единичном круге, ограниченных по модулю единицей, в виде условия неотрицательности квадратичных форм

\[
\sum_{j, k=1}^{n} \frac{1-w_{j} \bar{w}_{k}}{1-z_{j} \bar{z}_{k}} \xi_{j} \xi_{k}, \quad n \in \mathbb{N}, \xi_{j} \in \mathbb{C} .
\]

Первоначальное доказательство этого, а также вполне аналогичных и сводящихся ғ нему результатов для ряда других классов функций $\mathfrak{2}$ (см. [3]) проводилось алгебрапческими и теоретико-функциональными методами. Более поздние доказательства, основывающиеся, напр., на сведении Н.-П. п. к нек-рой проблеме моментов (см. [4]) или же полученные с точки зрения теории гильбертовых пространств (см. [5]), позволили охватить случай несчетных подмножеств $\left\{z_{\alpha}\right\} \subset G$ и наметить пути возможных обобщений.

Естественным развитием Н. - П. П., потребовавшим привлечения функционально-аналитич. методов иссле- дования, явился вопрос о разрешимости интерполяционной задачи (1) на классе $W$ правых частей $\left\{w_{\alpha}\right\}$; в этом случае, как правило, $\left\{z_{\alpha}\right\}$ является счетным множеством (последовательностью) точек области $G$, а в качестве $W$ выступают различные пространства последовательностей комплексных чисел. Применительно к классу $H^{\infty}$ ограниченных аналитич. функций в единичном круге и пространству $l^{\infty}$ ограниченных последовательностей полное описание соответствующих последовательностей точек $\left\{z_{\alpha}\right\}$ (т. н. у н и в е р с ал ьные интерполяционыңе после доват е л ь н о с т и) было получено (см. [6]) в виде условия

\[
\prod_{j=1, j \neq k}^{\infty}\left|\frac{z_{j}-z_{k}}{1-z_{j} \bar{z}_{k}}\right| \geqslant \delta>0, \quad k \in \mathbb{N} .
\]

Этот результат сыграл важную роль в описании структуры пространства максимальных идеалов алгебры $H^{\infty}$ (см. [7]) и одновременно явился отправным моментом для многочисленных исследований Н.-П. П. (в указанной обобщенной постановке) для классов $\mathrm{X} \mathrm{ap} д и ~ H^{q}$ и пространств $l p$ (включая весовые пространства). Оказалось, что при $q=\infty$ решение Н.- П. П. не зависит от $p$ и дается условием (2), а при $q<\infty$ необходимо меняется при изменении $q$ и $p$ (см. [8]). Другое обобщение Н. - П. П. связано с интерполяционной задачей $\varphi_{\alpha}(f)=$ $=w_{\alpha}$, где $\left\{\varphi_{\alpha}\right\}$ - нек-рая система функционалов в классе $\mathfrak{5}$. Возникающую при этом задачу описания множества $\left\{\left\{\varphi_{\alpha}(f)\right\}: f \in \mathcal{5}\right\}$ можно рассматривать также как обобщение известной коэфбичиентов проблемы для классов аналитич. функций.

Jum.: [1] P i c k G., "Math. Ann.", 1916, Bd 77, S. 7-23; [2] N e v a n l i n n a R.. "Ann. Acad. sci. fenn. Ser. A", 1929,

![](https://cdn.mathpix.com/cropped/2023_07_08_81e7d6c83b879db6e272g-1.jpg?height=42&width=833&top_left_y=1140&top_left_x=990)
Проблема моментов Маркова и экстремальные задачи, М.,
$1973 ;$ [4] К р е й н М. Г., Р е х т м а н П. Г., "Тр. Одеского roc. Ун-та", 1938, т. 2, c.' 63-68; [5] S z- N a g y B., K o r án y i A., "Acta math. Acad. sci. hung.", 1956, v. 7. p. 295-303; 30; [7] е г о ж e, "Ann. Math.», 1962, v, 76, p. 547 - 59; [8] Ші в е д е н к о С. В., "Матем. заметки", 1977, т. 21, Nㅏ 4, с. $503-08$.

НЕВОЗМОЖНОЕ СОБЫТИЕ - событие, к-рое в рамках данных условий не осуществляется ни при каких обстоятельствах. Если $(\Omega, \mathcal{A}$, Р) - вероятностное пространство, то Н. с. - это событие $\varnothing \in \mathcal{A}$, не наступающее ни с одним из әлементарных исходов $\omega \in \Omega$ (пустое множество). Н. с. является дополнением к достоверному событию $\Omega$ в рассматриваемой вероятностной модели и поэтому Н. с. приписывают вероятность нуль: $\mathbf{P}(\varnothing)=0$.

НЕВЫРОЖДЕННАЯ МАТРИЦА, н е о с о б е н н а я м а т р и ц а,- квадратная матрица, определитель к-рой отличен от нуля. Для квадратной матрицы $A$ над полем невырожденность эквивалентна каждому из следующих условий: 1) $A$ - обратима; 2) строки (столбцы) матрицы $A$ линейно независимы; 3) әлементарными преобразованиями строк (столбцов) матрицу $A$ можно привести к единичной матрице.

НЕВЫРОЖДЕННОЕ ПРЕДСТАВЛЕНИЕ - ЛИНеЙное представление $\pi$ группы (кольца, алгебры, полугруппы) $X$ в векторном пространстве $E$ такое, что из равенства $\pi(x) \xi=0$ для нек-рого $\xi \in E$ и всех $x \in X$ следуст $\xi=0$.

А. И. Штерн.

НЕВЫЧЕТ с т е п е н и $n$ п о м о д у лю $m$ - число $a$, для к-рого сравнение $x^{n} \equiv a(\bmod m)$ не имеет решения; см. Вычет.

НЕВЯЗКА П р и бл и ж е н н о го р е ш е и и одна_из характеристик качества приближенного решения $\bar{u}$ ошераторного уравнения $\boldsymbol{P}(u)=0$ (напр., линейной алгебраич. спстемы, дифференциального уравнения). Н е в я з к о й наз. величину $\boldsymbol{P}(\bar{u})$ или нек-рую ее норму $\|P(\bar{u})\|_{2}$. Если известна оценка $\left\|u_{1}-u_{2}\right\|_{1} \leqslant C\left\|P\left(u_{1}\right)-P\left(u_{2}\right)\right\|_{2}$,