ч ен и я м и в $\mathscr{F}$. При этом $H^{0}(X, \mathscr{F})=\mathscr{F}(X)$. Если $\mathscr{F}-$ шучок ростков непрерывных отоб̈ражений со значениями в топологич. группе $G$, то $H^{1}(X, \mathscr{T})$ интерпретируется как множество классов изоморфных топологических главных расслоений над $X$ со структурной группой $G$. В аналогичных терминах получается классификация гладких и голоморфых главных расслоений. Таким же способом определяются Н. к. топологизированной категории; по поводу пх интерпретации см. Главный G-объект.

2) Пусть $G$ - нек-рая группа и $A$ - (не обязательно абелева) $G$-группа, т. е. операторная группа с группой операторов $G$. Пусть результат действия оператора $g \in G$ на әлемент $a \in A$ обозначается $a g$. Комплекс $C^{*}(G, A)$ определяется формулами:

\[
\begin{gathered}
C^{k}=\operatorname{Map}\left(G^{k}, A\right), k=0,1,2, \\
(\rho(a)(b))(g)=a b(g)\left(a^{g}\right)^{-1}, \\
(\sigma(a)(c))(g, h)=a^{g} c(g, h)\left(a^{g}\right)^{-1}, \\
\delta(b)(g, h)=b(g)^{-1} b(g h)\left(b(h)^{g}\right)^{-1}, \\
a \in C^{0}, b \in C^{1}, c \in C^{2}, g \in G .
\end{gathered}
\]

Группа $H^{0}(G, A)=H^{0}(C *(G, A))$ совпадает с подгруппой $A G$ неподвижных точек в $A$ относительно $G$, а множество $H^{\mathbf{1}}(G, A)=H^{\mathbf{1}}\left(C^{*}(G, A)\right)$ есть множество классов эквивалентных скрещенных гомоморфизмов $G \rightarrow A$ и интерпретируется как множество классов изоморфных әлаєных однородных пространств над $A$. По поводу приложений и конкретных вычислений Н. к. групп см. Галуа когомологии. Аналогічно определяются Н. к. категорий и полугрупп.

3) Пусть $X-$ гладкое многообразие, $G-$ группа Ли, $\mathfrak{x}$ - ее алгебра Ли. Н е а б е ле в к о м п л е к с д е $\mathrm{P}$ а м a $R_{G}^{*}(X)$ определяется следующим образом: $R_{G}^{0}(X)$ - группа всех гладких функций $X \rightarrow G$;

\[
R_{G}^{k}(X), \quad k=1,2,
\]

一пространство внешних $k$-форм на $X$ со значениями в $\mathfrak{g}$;

\[
\begin{gathered}
\rho(f)(\alpha)=d f \cdot f^{-1}+(\operatorname{Ad} f) \alpha ; \\
\sigma(f)(\beta)=(\operatorname{Ad} f) \beta, \\
\delta \alpha=d \alpha-\frac{1}{2}[\alpha, \alpha], \\
f \in R_{G}^{0}, \quad \alpha \in R_{G}^{1}, \beta \in R_{G}^{2} .
\end{gathered}
\]

Множество $H^{\mathbf{1}}\left(\boldsymbol{R}_{G}(X)\right)$ есть множество классов вполне интегрируемых уравнений вида $d f \cdot f^{-1}=\alpha, \quad \alpha=R_{G}^{1}$, относительно калибровочных преобразований. Аналог теоремы де Рама дает интерпретацию этого множества как нек-рого подмножества в множестве $H^{\mathbf{1}}\left(\pi_{1}(M), G\right)$ классов сопряженных гомоморфизмов $\pi_{1}(M) \rightarrow G$. В случае комплексного многообразия $M$ и комплексной групшы Ли $G$ определяются также неабелевы голоморфыый комплекс де Рама и комплекс Дольбо, тесно связанные с задачей классификации голоморфных расслоений [3]. Неабелевы комплексы дифференциальных форм являются также важным аппаратом в теории псевдогрупновых структур на многообразиях [7].

С каждым подкомплексом неабелева коцепного комплекса связана точная последовательность когомологий. Напр., для комплекса $C *(G, A)$ из примера 2) и его подкомплекса $C *(G, B)$, где $B$ есть $G$-инвариантная подгруппа в $A$, она имеет вид

$e \longrightarrow H^{0}(G, B) \longrightarrow H^{0}(G, A) \longrightarrow(A / B)^{G} \longrightarrow H^{1}(G, B) \longrightarrow$ $\longrightarrow H^{\mathbf{1}}(G, A)$.

Если $B$ - нормальный делитель в $A$, то последовательность можно продолжить до члена $H^{1}(G, A / B)$, а если $B$ лежит в центре, то - и до $H^{2}(G, A)$. Эта последовательность точна в категории множеств с отмеченными точ- ками. Кроме того, существует аппарат («подкручивание» или «скручивание" коцепного комплекса), позволяющий описывать прообразы всех, а не только отмеченных элементов (см. [1], [6], [3]). Можно построить также спектральную последовательность, связанную с двойным неабелевым комплексом, и соответствующую краевую точную последовательность [4].

Кроме описанных выше 0-мерных и 1-мерных, существуют также 2-мерные Н. к. Классич. примером являются 2-мерные когомологии группы $G$ со значениями в нек-рой группе $A$, к-рые определяются следующим образом. Через $\mathrm{z}^{2}(G, A)$ обозначается множество всех пар $(m, \varphi)$, где $m: G \times G \longrightarrow A, \varphi: G \longrightarrow$ Aut $A$ - такие отображения, что

\[
\varphi\left(g_{1}\right) \varphi\left(g_{2}\right) \varphi\left(g_{1} g_{2}\right)^{-1}=\operatorname{Int} m\left(g_{1}, g_{2}\right),
\]

$m\left(g_{1}, g_{2}\right) m\left(g_{1} g_{2}, g_{3}\right)=' \varphi\left(g_{1}\right)\left(m\left(g_{2}, g_{3}\right)\right) m\left(g_{1}, g_{2} g_{3}\right)$;

здесь Int $a$ - внутренний автоморфизм, порожденный әлементом $a \in A$. $\mathrm{B} \mathcal{Z}^{2}(G, A)$ определяется отношение эквивалентности: $(m, \varphi) \sim\left(m^{\prime}, \varphi^{\prime}\right)$, если существует такое отображение $h: G \rightarrow A$, что

\[
\varphi^{\prime}(g)=(\operatorname{Int} h(g)) \varphi(g)
\]

$m^{\prime}\left(g_{1}, g_{2}\right)=h\left(g_{1}\right)\left(\varphi\left(g_{1}\right)\left(h\left(g_{2}\right)\right)\right) m\left(g_{1}, g_{2}\right) h\left(g_{1}, g_{2}\right)^{-1}$.

Классы этой эквивалентности и составляют множество когомологий $\mathscr{H}^{2}(G, A)$. Они находятся во взаимно однозначном соответствии с классами эквивалентных расширений группы $A$ при помощи $G$ (см. Расширение г р у п п ы).

Соответствие $(m, \varphi) \rightarrow \varphi$ дает отображение $\theta$ множества $\mathscr{H}^{2}(G, A)$ в множество всех гомоморфизмов

\[
G \longrightarrow \text { Out } A=\text { Aut } A / \operatorname{lnt} A
\]

пусть $H_{\alpha}^{2}(G, A)=\theta^{-1}(\alpha)$ для $\alpha \in$ Out $A$. Если фиксировать $\alpha \in$ Out $A$, то на центре $Z(A)$ группы $A$ будет задана структура $G$-модуля и тем самым определены группы когомологий $H^{k}(G, Z(A))$. Оказывается, что непустота множества $H_{\alpha}^{2}(G, A)$ равносильна тривиальности нек-рого класса из $H^{3}(G, Z(A))$. Далее, при этом условии группа $H^{2}(G, Z(A))$ просто транзитивно действует на множестве $H_{\alpha}^{2}(G, A)$.

Это определение двумерных когомологий можно обобщить, перенеся его на топологизированные категории (см. [2], где даны также приложения этого понятия). Общая алгебраич. схема, приводящая к двумерным когомологиям, указана в [4]; так же, как и в описанном выше частном случае, их вычисление сводится к вычислению одномерных неабелевых и обычных абелевых когомологий.

Лum.: [1] C е p p ж.-П., Когомологии Галуа, пер. c фpaнц., M., 1968; [2] G i r a d d J., Cohomologie non abelienne, В.- Hdlb.- N. Y., 1971; [3] O н и щ и к А. Л., "Тр. Моск.
матем. об-ва", 1967, т. 17, с. 45-88; [4] То л п т о А. К., в сб.: Вопросы теории групп и гомологической алгебры, в. 1, Ярославль, 1977, c. 156-97; [5] D e d e c k e r P., B kH.: Category N. Y.. 1969, p. 32-64; [6] F r e n ke l J., "Bull. Soc. math. France», 1957, t. 85, № 2, p. 135-220; [7] G o l d s c h m i d t H., "Bull. Amer. Math. Soc.", 1978, v. 84, No 4, p. 531-46; [8] mathematics, Providence, v. 9, 1966, p. 164-82.

НЕАРХИМЕДОВА ГЕОМЕТРИЯ А. Лнuщић, А. К. Толпыго. метрич. предложений, вытекающих из групп аксиом: инцидентности, порядка, конгруэнтости и параллельности системы Гильберта аксиом евклидовой геометрии, и не связанных с аксиомами непрерывности (с аксиомами Архимеда и полноты). В узком смысле Н. г. описывает геометрич. свойства прямой, на к-рой не верна аксиома Архимеда (н е а р х и м д о в а п р я м а я).

Для исследования геометрич. соотношений в Н. г. вводится исчисление отрезков - неархимедова числовая система, рассматриваемая как специальная комп-