висимых функций на $[0,1]$ служат знаки двоичного разложения $\omega, 0 \leqslant \omega \leqslant 1$, или связанные с ними функции Радемахера

\[
r_{k}(\omega)=\operatorname{sign} \sin \left(2 \pi \cdot 2^{k-1} \omega\right), \quad k=1,2, \ldots
\]

Следует отметить, что существование к а к о г о-н иб у д в вероятностного пространства, на к-ром определены независимые случайные величины с заданными распределениями, вытекает из теоремы Колмогорова о вероятностях в бесконечномерных пространствах (см. [3] гл. III, § 4).

3) Независимы е случайны е ве ли-

![](https://cdn.mathpix.com/cropped/2023_07_08_a64aaae930ef812b9606g-1.jpg?height=35&width=833&top_left_y=536&top_left_x=122)
Пусть $Y_{0}, Y_{1}, Y_{2}, \ldots, Y_{n}, \ldots$. последовательность независимых случайных величин и $h(x, y)$ - (борелевская) функция двух переменных. Полагая

\[
\begin{gathered}
X_{1}=h\left(Y_{0}, Y_{1}\right), X_{2}=h\left(X_{1}, Y_{2}\right), \ldots, \\
X_{n}=h\left(X_{n-1}, Y_{n}\right), \ldots,
\end{gathered}
\]

получают последовательность случайных величин, образующих Маркова цепь. Подобным же образом можно получать марковские прочессы, напр. из винеровского процесса при помощи стохастических дифференциальных уравнений. Из гауссовских случайных мер с независимыми значениями можно, используя преобразование Фурье, построить гауссовские стационарные случайные процессы и т. д.

4) С лабая 3 а в и с и м о с ть. Асимптотич. законы теории вероятностей, установленные для последовательностей независпмых случайных величин, обычно могут быть распространены и на последовательности т. н. слабо зависимых величин, т. е. на последовательности $X_{1}, X_{2}, \ldots, X_{n}, \ldots$, где надлежащим образом измеренная зависимость между «удаленными» друг от друга отүезками последовательности «мала» (в простейших случаях это могут быль последовательности $m$-зависимых величин, где $X_{k}$ и $X_{l}$ при $|k-l|>m$ независимы, или последовательности величин, образующих Маркова цепь эргодическую, и т. Іі.). Один из основных приемов доказательства соответствующих теорем - сведение рассматриваемого случая к случаю $\mathrm{H}$.

5) Н е з а висимость в те о рии чи и с л. Пусть $p \geqslant 2$ и $q \geqslant 2$ - два взаимно простых натуральных числа. Пусть $N$ - натуральное число, и пусть наудачу выбирают одно из чисел от 1 до $N$ (вероятность для каждого счітают равной $1 / N)$. Пусть $A_{p}$ (соответственно $A_{q}$ ) событие, состоящее в том, что выбранное число делится нацело на $p$ (соответственно $q$ ). Тогда

\[
\begin{aligned}
& \mathrm{P}\left(A_{p}\right)=\frac{1}{N}\left[\frac{N}{p}\right], \mathrm{P}\left(A_{q}\right)=\frac{1}{N}\left[\frac{N}{q}\right], \\
& \mathrm{P}\left(A_{p} \cap A_{q}\right)=\frac{1}{N}\left[\frac{N}{p q}\right]
\end{aligned}
\]

и при $N \rightarrow \infty$ события $A_{p}$ и $A_{q}$ становятся «почти независимыми». Значительно более глубокий факт, состоящий в том, что при $N \rightarrow \infty$ можно выбрать $S=S_{N \rightarrow \infty}$ так, что события $A_{2}, A_{3}, \ldots, A_{p_{S}}\left(A_{j}\right.$ есть $j$-е простое число) в совокупности «почти независимы», служит основой для исследования распределения значений арифостич. функций, см. Чисел теория; вероятностные методы. Имеются и другие разделы теории чисел, где идея Н. явно или неявно присутствует.

6) О проверке гипотезы Н. по результатам наблюдений см. Статистических гипотез проверка.

Лит.: [1] М а р ко в А. А., Исчисление вероятностей, 4 изд., М., 1924; [2] К о л мо г о р о в А. Н., Основные понятия теории вероятностей, 2 изд., М., 1974; [3̉] е г о ж е, теория вероятностей, в кн.: Математика, ее содержание, методы и значения, М., 1956; [4] К а ц М., Статистическая независимость в теории вероятностей, анализе и теории чисел, пер. с англ., М., 1963; [5] Ф е л л е р В., Введение в теорию вероятностей и ее приложения, пер. с англ., 2 изд., М.. 1967. Ю. В. Прохоров. НЕЗАВИСИМОСТЬ СИСТЕМЫ АКСИОМ - свойство спстемы аксиом данной аксиоматич. теории, состоящее в том, что каждая аксиома является н е 3 а в ис и м о й, т. е. не является логическим следствием из множества остальных аксиом этой теории. Система аксиом, обладающая этим свойством, наз. н е 3 а в ис и м о й.

Независимость той или иной аксиомы данной аксиоматич. теории означает, что эту аксиому можно без противоречия заменить ее отрицанием. Иными словами, аксиома независима в том и только в том случае, если имеется интер претация, при к-рой эта аксиома ложна, а все остальные аксиомы данной теории истинны. Построение такой интерпретации является классич. методом доказательства независимости.

При построении аксиоматич. теории в виде борлальной системы, где отношение логич. следования формализуется в виде понятия выводимости, аксиома считается независимой, если она не может быть выведена из других аксиом с помощью правил вывода данной формальной системы. Для широкого класса формальных систем (т. н. теорий 1-го порядка) независимость относительно выводимости совпадает с независимостью относительно логич. следования.

По отношению к формальным системам и вообще исчислениям имеет смысл говорить о независимости правил вывода. Правило вывода наз. н е з а в и с и мы м, если существует теорема данного исчисления, которая не может быть выведена без использования этого правила.

Н. с. а. сама по себе не является обязательным свойством аксиоматич. теории. Она лишь свидетельствует о том, что совокупность исходных положений теории не является избыточной, и представляет нек-рые технич. удобства. Однако исследования, посвященные Н. с. а., и доказательства независимости способствуют лучшему пониманию изучаемой теории. Достаточно вспомнить, какое влияние на развитие математики оказал вопрос о независимости пятого постулата Евклида в системе аксиом геометрии.

Лит.: [1] Н о в и к о в П. С., Элементы математической

![](https://cdn.mathpix.com/cropped/2023_07_08_a64aaae930ef812b9606g-1.jpg?height=37&width=829&top_left_y=1391&top_left_x=992)
Основания математики. Јоогические исчисления и формализация

![](https://cdn.mathpix.com/cropped/2023_07_08_a64aaae930ef812b9606g-1.jpg?height=45&width=834&top_left_y=1436&top_left_x=987)
англ., М., 1966. П., Основания теорй множеств, Плиско.

НЕЗАВИСИМЫЕ ИЗМЕРИМЫЕ РАЗБИЕНИЯ п $\mathbf{p}$ с т р а с т в с но р м и о в ан но й ме ро й $\mu-$ такие два измеримых разбиения $\xi$ и $\eta$, что если $\boldsymbol{B}(\xi)$ и $\boldsymbol{B}(\eta)-$ булевы $\sigma$-алгебры измеримых множеств, целиком состоящие из элементов разбиений $\xi$ и $\eta$ соответственно, то әлементы одной из них независимы от әлементов другой в том смысле, как это понимается в теории вероятностей: $\quad \mu(A \cap B)=\mu(A) \mu(B) \quad$ при $A \in B(\xi), B \in B(\eta)$. Если при этом измеримое разбиение, являющееся подразбиением обоих разбиений $\xi$ и $\eta$, совпадает по mod 0 с разбиением на отдельные точки,

![](https://cdn.mathpix.com/cropped/2023_07_08_a64aaae930ef812b9606g-1.jpg?height=37&width=829&top_left_y=1842&top_left_x=992)
м и друг друга. Известны условия того, чтобы измеримое разбиение Лебега пространства имело независимое дополнение.

Jum.: [1] P о х л и н в. А., “Матем. сб.», 1949, т. 25, № 1, c. $107-50 ;[2]$ E p mі о в м. П., «Успехи матем. наук", 1977,

НЕЗАВИСИМЫЕ МЕРЫ - меры $\mu$ и $v$, определенные на локально компактном пространстве $T$ такие, что inf $(\mu, v)=0$

Для того чтобы две меры $\mu$ и $v$ были независимы, необходимо и достаточно, чтобы в $T$ существовали такие непересекающиеся множества $M$ и $N$, что $\mu$ сосредоточена на $M$, а $v$ на $N$.

Лит.: [1] Б у р б а к и Н., Интегрирование. Меры, интегрирование мер, пер. с франц., М., 1967. М. И. Войцеховский.