класс класса к р у г о в х о б л а с т е й, определяемых условием: вместе с каждой точкой $z^{0} \in D$ они содержат и все точки вида

$\left\{z=\left(z_{1}, \ldots, z_{n}\right): z=a+\left(z^{0}-a\right) e^{i \theta}, 0 \leq \theta<2 \pi\right\}$, т. е. все точки окружности с центром $a$ и радиусом $\left|z^{0}-a\right|=\left(\sum_{v=1}^{n}\left|z_{v}^{0}-a_{v}\right|^{2}\right)^{1 / 2}$, расположенной на комплексной прямой, проходящей через $a$ и $z^{0}$.

К. к. о. $D$ наз. п о л н о й к р а т н о к у у гово й о б л а с т ь ю, если вместе с каждой точкой $z^{0} \in D$ ей принадлежит поликруг

$\left\{z=\left(z_{1}, \ldots, z_{n}\right):\left|z_{v}-a_{v}\right| \leqslant\left|z_{v}^{0}-a_{v}\right|, \quad v=1, \ldots, n\right\}$.

Полная К. к. о. звездообразна относительно ее центpa $a$.

Примеры полных К. к. о.: шары п поликруги в $\mathbb{C}^{n}$. Круговая область $D$ наз. І о л о й к р у $\mathbf{0}$ о о й о б л а с т ь ю, если вместе с каждой точкой $z^{0} \in D$ она содержит и весь круг $\left\{z=a+\left(z^{0}-a\right) \zeta,|\zeta| \leqslant 1\right\}$.

К. к. о. $D$ наз. лог а р иф ми ч е с ки вы п у кло й к ратно кругов о й обла т тью, если образ $\lambda\left(D^{*}\right)$ множества

\[
D^{*}=\left\{z=\left(z_{1}, \ldots, z_{n}\right) \in D: z_{1} z_{2} \ldots z_{n} \neq 0\right\}
\]

при отображении

\[
\lambda: z \longrightarrow \lambda(z)=\left(\ln \left|z_{1}\right|, \ldots, \ln \left|z_{n}\right|\right)
\]

является выпуклым множеством в действительном пространстве $\mathbb{R} n$. Важное свойство логарифмически выпуклых полных $\kappa$. к. о. состоит в том, что каждая такая область в $\mathbb{C}^{n}$ есть внутренность множества точек абсолютной сходимости (т. е. область сходимости) нек-рого степенного ряда по переменным $z_{1}-a_{1}, \ldots$, $z_{n}-a_{n}$, и обратно: область сходимости любого степенного ряда по $z_{1}, \ldots, z_{n}$ есть логарифмически выпуклая полная К. к. о. с центром $a=0$.

Лum.: [1] В л а д и м и р о в В. С., Методы теории функпий многих комплексных переменных, M., 1964; [2] III a-
б а т Б. В., введение в комплексный анализ, 2 изд., M., 1976.

E. Д. Соломенцев.

КРАТНОГАРМОНИЧЕСКАЯ ФУНКЦИЯ - гармоническая функция, у к-рой операторы Лапласа по отдельным группам независимых переменных обрашаются в нуль. Точнее, функция $u=u\left(x_{1}, x_{2}, \ldots, x_{n}\right), n \geqslant 2$, класса $C^{2}$ в области $D$ евклидова пространства $\mathbb{R}^{n}$ наз. K. ф. в $D$, если существуют такие натуральные числа $n_{1}, n_{2}, \ldots, n_{k}, n_{1}+n_{2}+\ldots+n_{k}=n, n \geqslant k \geqslant 2$, что всюду в $D$ выполняются тождества:

\[
\sum_{v=1}^{n_{1}} \frac{\partial^{2} u}{\partial x_{v}^{2}}=0
\]

$\sum_{v=n_{1}+1}^{n_{1}+n_{2}} \frac{\partial^{2} u}{\partial x_{v}^{2}}=0, \ldots, \sum_{v=n_{1}+n_{2}+\ldots+n_{k-1}+1}^{n} \frac{\partial^{2} u}{\partial x_{v}^{2}}=0$.

Важный собственный подкласс класса $\kappa$. ф. составляют плюригарлонические бункции, для к-рых $n=2 m, n_{j}=2$, $j=1,2, \ldots, m$, т. е. $k=m$, и к-рые, кроме того, удовлетворяют нек-рым дополнительным условиям.

Лит.: [1] С т е й н И., В е й с Г., Введение в гармонический анализ на евклидовых пространствах, пер. с англ., М., 1974.

КРАТНОЕ н а т у р а ль но г о ч и с л а $а$ натуральное число, делящееся на $a$ без остатка. Число $n$, к-рое делится на каждое из чисел $a, b, \ldots, m$, наз. о б ш и м к а т ны м этих чисел. Из всех общих К. двух или нескольких чисел одно (не равное нулю) является наименьшим (н а и м е н в ш е к р а т н о е), а остальные будут К. этого наименьшего. Зная наибольший общий делитель $d$ двух чисел $a$ и $b$, находят наименьшее обшее $\mathrm{K}$. $m$ по формуле $m=a b / d$. КРАTHOCTb BECA M п р е д с т а в л е и я $\rho$ а лге бры Л и с т в е $V$ - размерность $n_{M}$ весового подпространства $V_{\text {M}} \subset V$, соответствующего весу М (см. Вес представления).

Пусть $\mathfrak{t}-$ Картана подалеебра полупростой алгебры Ли $\mathfrak{g}$ над алгебраически замкнутым полем нулевой характеристики, а $\rho$ - ограничение на t конечномерного представления $\sigma$ алгебры g. В этом случае пространство $V$ является прямой суммой весовых подпространств алгебры $t$, соответствующих различным весам. Эти веса и их кратности часто наз. весами и кратностями весов представления $\sigma$ алгебры $q$.

Пусть представление $\sigma$ неприводимо и $\dot{\Lambda}$ - его старший вес (см. Картана теорема о старшем векторе). Тогда $n_{\Lambda}=1$. Для весов, отличных от старшего, известно несколько способов вычисления их кратностей. Два из них являются классическими результатами теории представлений - формула Фрейденталя и формула Костанта.

1. Ф о р у л а Ф р е й де н та л я (см. [4], [1]). Пусть (,) - естественное скалярное произведение на сопряженном к t пространстве t*, индуцированное Киллинга бормой на t, $R$ - система корней алгебры $\mathfrak{g}$ относительно $\mathrm{t} \boldsymbol{\mathrm { u }}>-$ - отношение частичного порядка на $t^{*}$, определенное какой-либо фиксированной системой простых корней $\alpha_{1}, \ldots, \alpha_{r}$ в $R$. Тогда

\[
\begin{aligned}
& ((\Lambda+\delta, \Lambda+\delta)-(\mathrm{M}+\delta, \mathbf{M}+\delta)) n_{\mathbf{M}}= \\
= & 2 \sum_{\alpha \in R, \alpha>0} \sum_{k=1}^{\infty} n_{\mathbf{M}+k \alpha}(\mathrm{M}+k \alpha, \alpha),
\end{aligned}
\]

где $\delta=(1 / 2) \sum_{\alpha \in R, \alpha>0} \alpha$ и,по определению, $n_{N}=0$, если $N$ не вес представления $\sigma$. Для любого веса $\mathrm{M} \neq \Lambda$ множитель при $n_{M}$ в левой части формулы отличен от нуля. Әта формула имеет рекуррентный характер: она позволяет выразить $n_{\mathrm{M}}$ через $n_{N}$, если $N>$. Поскольку известно, что $n_{\Lambda}=1$, формула Фрейденталя дает әффективный способ нахождения кратностей $n_{\mathrm{M}}$.

2. Ф о р у ла К о с тант а (см. [5], [1]). Пусть $\Gamma=\left\{\mathrm{M} \in \mathrm{t}^{*} \mid 2\left(\mathrm{M}, \alpha_{i}\right) /\left(\alpha_{i}, \alpha_{i}\right) \in \mathbb{Z}\right.$ для всех $\left.i=1, \ldots, r\right\}$. Множество $\Gamma$ является подгруппой по сложению в $t^{*}$, инвариантной относительно группы Вейля $W$, к-рая действует в $t *$ естественным образом. Элемент $\delta$, a также все веса представления $\sigma$ лежат в Г. Пусть для каждого $\mathrm{M} \in \Gamma$ число $P(\mathrm{M})$ равно количеству способов записи М в виде суммы положительных корней, т. е. $P(\mathrm{M})$ - это число решений $\left\{k_{\alpha} \mid \alpha \in R, \alpha>0\right\}$ уравнения

\[
\mathrm{M}=\sum_{\alpha \in R, \alpha>0} k_{\alpha} \alpha
\]

где $k_{\alpha} \in \mathbb{Z}, k_{\alpha}>0$ при всех $\alpha$. Функция $P(\mathrm{M})$ на $\Gamma$

![](https://cdn.mathpix.com/cropped/2023_07_08_c3b173a5f7e84a8b3713g-1.jpg?height=53&width=715&top_left_y=1678&top_left_x=992)

\[
n_{\mathbf{M}}=\sum_{S \in W}(\operatorname{det} S) P(S(\Lambda+\delta)-(\mathbf{M}+\delta))
\]

Практическое использование приведенных выше формул связано с громоздкими вычислениями. Для полупростых алгебр ранга 2 имеются более удобные геометрические правила подсчета К. в. (см. [2]).

Лum.: [1] Д ж е к о б с о н Н., Алгебры Ји, пер. с англ., М., 1964; [2] Же е Л о б е н к о Д. П., Лекции по теории групі Ли, Дубна, 1965; [3] е г о же е, Компактные группы Jи и их
представления, М., 1970; [4] F r e d e n t h a l H., "IIndag. Math.", 1954, v. 16, p. 369-76, 487-91; 1956, v. 18, p., 511-14; [5] K o s t a n t B., "Trans. Amer. Math. Soc.", 1959, v. 93,
p. 53-73. КРАТНОСТЬ ОСОБОЙ ТочКИ а л г е б р а и ч ес кого многооб р а и я-целое число, измеряющее степень особенности многообразия в этой точке. Кратностью $\mu(X, x)$ многообразия $X$ в точке $x$ наз. кратность максимального идеала $\mathfrak{m}$ в локальном кольце $\hat{\sigma}_{x, x}$. Кратность $X$ в точке $x$ совпадает с кратностью касательного конуса $C(X, x)$ в вершине, а также со степенью специального слоя $\sigma^{-1}(x)$ раздутия $\sigma: X^{\prime} \rightarrow X$