НЕПОЛНАЯ БЕТА-ФУНКЦИЯ - функция, опре- $\mid$ Представление в виде ряда:

деляемая формулой

\[
\begin{aligned}
I_{x}(a, b) & =\frac{1}{\mathrm{~B}(a, b)} \int_{0}^{x} t^{a-1}(1-t)^{b-1} d t, \\
0 & \leqslant x \leqslant 1, a>0, b>0,
\end{aligned}
\]

где

\[
\mathrm{B}(a, b)=\int_{0}^{1} t^{a-1}(1-t)^{b-1} d t=\frac{\Gamma(a) \Gamma(b)}{\Gamma(a+b)}
\]

Если $a$ - целое, то

\[
\begin{gathered}
1-I_{x}(a, b)=\frac{(1-x)^{b}}{\mathrm{~B}(a, b)} \sum_{i=0}^{a-1}(-1)^{i} C_{a-1}^{i} \frac{(1-x)^{i}}{b+i}= \\
=(1-x)^{a+b-1} \sum_{i=0}^{a-1} C_{a+b-1}^{i}\left(\frac{x}{1-x}\right)^{i} .
\end{gathered}
\]

Представление в виде ряда:

\[
\begin{gathered}
I_{x}(a, b)=\frac{x^{a}(1-x)^{b}}{a \mathrm{~B}(a, b)}\left\{1+\sum_{n=0}^{\infty} \frac{\mathrm{B}(a+1, n+1)}{\mathrm{B}(a+b, n+1)} x^{n+1}\right\}, \\
0<x<1 ;
\end{gathered}
\]

в виде непрерывной дроби:

\[
I_{x}(a, b)=\frac{x^{a}(1-x)^{b}}{a \mathrm{~B}(a, b)}\left\{\frac{1}{1+} \frac{d_{1}}{1+} \frac{d_{2}}{1+\ldots}\right\},
\]

где

\[
d_{2 m+1}=-\frac{(a+m)(a+b+m) x}{(a+2 m)(a+2 m+1)}, \quad d_{2 m}=\frac{m(b-m) x}{(a+2 m-1)(a+2 m)} .
\]

Асимптотич. представление при больших $a$ и $b$

$I_{x}(a, b)=\Phi\left\{3 \frac{(b x)^{1 / 3}\left(1-\frac{1}{9 b}\right)-[a(1-x)]^{1 / 3}\left(1-\frac{1}{9 a}\right)}{\sqrt{[a(1-x)]^{2 / 3} / a+(b x)^{2 / 3 / b}}}\right\}+$

\[
+O\left(\frac{1}{\min (a, b)}\right)
\]

где

\[
\Phi(z)=\frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{z} e^{-t^{2} / 2} d t .
\]

Асимптотич. представление при больших $b$ и ограниченных $a$ :

\[
I_{x}(a, b)=I(x(2 b+a-1) /(2-x), a)+O\left(b^{-2}\right),
\]

где

\[
I(z, a)=\frac{1}{\Gamma(a)} \int_{0}^{z} e^{-t_{t} a-1} d t .
\]

Связь с гипергеометрич. Функцией:

\[
I_{x}(a, b)=\frac{x^{a}}{a \mathbf{B}(a, b)} F(a, 1-b ; a+1 ; x) .
\]

Рекуррентные соотношения:

$I_{x}(a, b)=1-I_{1-x}(b, a)$,

$I_{x}(a, b)=x I_{x}(a-1, b)+(1-x) I_{x}(a, b-1)$

$I_{x}(a, a)=\frac{1}{2} I_{1-y}\left(a, \frac{1}{2}\right), y=4\left(x-\frac{1}{2}\right)^{2}, 0<x \leqslant \frac{1}{2}$.

Лит.: [1] Справочник по специальным функциям, пер. с англ., М., 1979; [2] П и р с о н К., Таблицы неполной бета-
функции, пер. с англ., М., 1974.
М. Пагурова.

НЕПОЛНАЯ ГАММА-ФУНКЦИЯ - функция, определяемая формулой

\[
I(x, m)=\frac{1}{\Gamma(m)} \int_{0}^{x} e^{-t^{m-1}} d t, \quad x \geqslant 0, m>0,
\]

где

\[
\Gamma(m)=\int_{0}^{\infty} e^{-t} t^{m-1} d t-\text { гамма-функция. }
\]

Если $n \geqslant 0$ - целое, то

\[
I(x, n+1)=1-e^{-x} \sum_{m=0}^{n} \frac{x^{m}}{m !} .
\]

\[
I(x, m)=\frac{e^{-x_{x} m}}{\Gamma(m+1)}\left\{1+\sum_{k=1}^{\infty} \frac{x^{k}}{(m+1) \cdots(m+k)}\right\} ;
\]

в виде непрерывной дроби:

\[
I(x, m)=1-\frac{x^{m_{e}-x}}{\Gamma(m)}\left\{\frac{1}{x+} \frac{1-m}{1+} \frac{1}{x+} \frac{2-m}{1+} \frac{2}{x+} \ldots\right\} .
\]

Асимптотич. представление при больших $x$ :

\[
I(x, m)=
\]\[
=1-\frac{x^{m-1} e-x}{\Gamma(m)}\left\{\sum_{i=0}^{M-1} \frac{(-1)^{i} \Gamma(1-m+i)}{x^{i} \Gamma(1-m)}+O\left(x^{-M}\right)\right\} .
\]

Асимптотич. представление шри больших $m$ :

\[
\begin{gathered}
I(x, m)=\Phi(2 \sqrt{x}-\sqrt{m-1})+O\left(m^{-1 / 2}\right), \\
I(x, m)=\Phi\left[3 \sqrt{m}\left(\sqrt[3]{\frac{x}{m}}-1+\frac{1}{9 m}\right)\right]+O\left(m^{-1}\right),
\end{gathered}
\]

где

\[
\Phi(z)=\frac{1}{\sqrt{2 \pi}} \int_{-\infty}^{z} e^{-t^{2} / 2} d t .
\]

Связь с вырожденной гипергеометрич. функцией:

\[
I(x, m)=\frac{x^{m}}{\Gamma(m+1)}{ }_{1} F_{1}(m, m+1,-x) .
\]

Связь с многочленами Лагерра $L_{n}^{(\alpha)}(x)$ :

$\frac{\partial^{n+1}}{\partial x^{n+1}} I(x, n+\alpha)=(-1)^{n} n ! \frac{\Gamma(\alpha)}{\Gamma(n+\alpha)} x^{\alpha-1} e^{-x} L_{n}^{(\alpha)}(x)$.

Рекуррентное соотношение

\[
m I(x, m+1)+x I(x, m-1)=(x+m) I(x, m) .
\]

Лит.: [1] Справочник по специальным функциям, пер. с англ., М., 1979; [2] П а г у р о в а В. И., Таблицы неполной гамма-функции, М., 1963 . В. И. Пагурова.

НЕПРАВИЛЬНОСТИ КОЭФФИЦИЕНТЫ л И Н Й-

![](https://cdn.mathpix.com/cropped/2023_07_08_c2063a3ee6cbb281facfg-1.jpg?height=35&width=834&top_left_y=1290&top_left_x=987)
р е нц и а л ь н х у р а в н е н и й - неотрицательные функции $\sigma(A)$, равные нулю в том и только в том случае, если система

\[
\dot{x}=A(t) x,
\]

где $A(\cdot)$ - суммируемое на каждом отрезке отображение $\mathbb{R}^{+} \rightarrow \operatorname{Hom}\left(\mathbb{R}^{n}, \mathbb{R}^{n}\right)$ (или $\left.\mathbb{R}+\rightarrow \operatorname{Hom}\left(\mathbb{C}^{n}, \mathbb{C}^{n}\right)\right)$,правильная линейная система. Наиболее известны (и наиболее просто определяются) слепующие Н. к.

1) Ко ффф ициент не пр а в ильн о с ти Л я п у н о в а [1]

![](https://cdn.mathpix.com/cropped/2023_07_08_c2063a3ee6cbb281facfg-1.jpg?height=95&width=705&top_left_y=1649&top_left_x=1047)

где $\lambda_{i}(A)$ - Ляпунова характеристические показатели системы $(*)$, занумерованные в порядке невозрастания, $\mathrm{a} \operatorname{tr} A(t)$ - след отображения $A(t)$.

2) К о эффициент неправильности П е р р о н а [2]

\[
\sigma_{\Pi}(A)=\max _{1 \leqslant i \leqslant n}\left(\lambda_{i}(A)+\lambda_{n+1-i}\left(-A^{*}\right)\right),
\]

где $A *(t)$ - отображение, сопряженное к $A(t)$.

Если система $(*)$ есть система уравнений в варіациях гамильтоновой системы

\[
\left.\begin{array}{ll}
\dot{q}=\frac{\partial H}{\partial p}, & p \in \mathbb{R}^{k} \\
\dot{p}=-\frac{\partial H}{\partial q}, & q \in \mathbb{R}^{k}
\end{array}\right\}
\]

то $n=2 k$ и

\[
\lambda_{i}\left(-A^{*}\right)=\lambda_{i}(A), \quad i=1, \ldots, n ;
\]

поэтому для правильності системы уравнений в вариа-