Каждая категория состоит из әлементов пвух классов, наз. к ла с с ом о б ъ е к т о в к л а с с о м м о рф и з м о в соответственно. Класс 0 . катег ориі $\mathfrak{f}$ обычно обозначается $0 \mathrm{~b} \Re$. Любому объекту $A$ категории $\Re$ однозначно соответствует едингчный морфизм $1_{A}$, причем разным О. отвечают разные единичные морфизмы. Поэтому формально можно определить понятие категории только с помощью морфизмов. Однако термин «объект категории» является удобным языковым средством, к-рое практически всегда используется. Деление әлементов категории на 0 . и морфизмы имеет смысл только в пределах фиксированной категоршІ, так как О. одной категории могут быть морфизмами другой и наоборот. Благодаря наличию морфизмов между О. категории устанавливаются определенные взаимосвяви, что позволяет выделить специальные классы О.: интегральные объекты, нулевые объекты, малые объекты, проективные объекты, инъективные объекты и т. Д. М. ШІ.. Цаленко.

ОБЂем т p е х м е р н о г о т е л а - чісловая характеристика тела, равная в простейшем случае, когда тело можно разбить на конечное множество едіничных кубов (т. е. кубов с ребрами длины единица), чІслу этих кубов. О. трехмерных тел (т. е. множеств трехмерного евклидова пространства), для к-рых они определены, обладают свойствами, аналогічными свойствам плоцадей плоских фигур: 1) О. неотрицательны; 2) 0 . аддитивны: если для двух тел $P$ и $Q$, не имеющих общих внутренних точек, определены О. $v(P)$ и $v(Q)$, то О. их объединения равен сумме их О. $v(P \cup Q)=v(P)+$ $+v(Q) ; 3)$ O. инвариантны о' носительно перемещений: если для тел $\boldsymbol{P}$ и $Q$ определены O. Іі они конгруентны, то $v(P)=v(Q) ; 4)$ О. единичного куба равен единице. Из этих свойств следуют монотонность $\mathrm{O} .:$ если для тел $P$ и $Q$ огределены O. $v(P), v(Q)$ и $P \subset Q$, то выполняется неравенство $v(P) \leqslant v(Q), \quad$ и равенство отношения О. подобных тел кубу коэффициента подобия.

На множестве всех многогранников существует и притом единственная неотрицательная функция, удовлетворяющая свойствам 1) - 4). Однако если на плоскости два любых равновеликих (имеющих одинаковую площадь) многоугольника равносоставлены, т. е. каждый из них допускает разбиение на многоугольники, из к-рых можно составить другой, то в пространстве аналогичное свойство уже не имеет места: существуют равновеликие (имеющие равные О.), но не равносоставленные многогранники (см. Равновеликие и равносоставленные бизуры).

Понятие О. распространяется с сохранением свойств 1) - 4) при помощи предельного перехода с множества многогранников на более широкие классы тел, нашр. на тела с кусочно гладкой границей, в частності на шары, шаровые слои, шаровые сегменты и секторы, цилиндры, конусы и т. п. Если граница ограниченного тела $G$ является кусочно гладкой поверхностью, то его O. $v(G)$ определяется следующим образом. Рассматриваются всевозможные многогранники $P$, лежащие в теле $G$, и всевозможные многогранники $Q$, содержащие в себе тело $G: P \subset G \subset Q$. Тогда справедливо равенство

\[
\sup _{P \subset Q} v(P)=\inf _{Q \supset G} v(O)
\]

Это общее значение указанных нижней и верхней граней и наз. о б ъ е м о м $v(G)$ тела $G$. Аналогично случаю вычисления площадей плоских фигур для вычисления О. тел также применяется метод разбиения тела на части, для к-рых О. либо уже известен, либо может быть найден более простым путем. При этом для О. справедлив п р и ц и п К а в а лье ри : если два тела, для к-рых определен О., пересекаются каждой плоскостью, параллельной нек-рой заданной, по конгруэнтным плоским фигурам, то они равновелики. Об- щий метод вычисления О. дает интегральное исчисление: вычисление О. сводится к вычислению соответствующих кратных интегралов. Интегральное исчисление цает возможность обосновать и принцип Кавальери.

Распиирение понятия 0 . на еще более широкий класс подмножеств трехмерного евклидова пространства приводит к понятию трехмерной жордана меры и понятию кубируемого множества. Все упоминавшиеся выше тела являются кубируемыми множествами и потому для них определена мера Жордана.

Если $M^{3}$ - трехмерное непрерывно дифференцируемое многообразие с римановой метрикой

\[
d s^{2}=\sum_{i, j=1}^{3} g_{i j} d x^{i} d x^{j}
\]

и $g=\operatorname{det}\left|g_{i j}\right|$, то о б ьем о м м но же с т в а $E$, лежащего в многообразии $M^{3}$, наз. величина интеграла

\[
\iiint_{E}|g| d x^{1} d x^{2} d x^{3}
\]

Так определенный 0 . множества инвариантен относительно выбора локальных координат на рассматриваемом многообразіи.

Определение О. трехмерного тела обобщается на случай подмножества произвольного $n$-мерного евклгдова пространства $\mathbb{R} n ; \quad n-м$ е р ным о б ъ е м о также наз. Функцгя множества, удовлетворяющая условиям 1) - 4), если только под кубом понимать $n$-мерный куб. Вычисленіе О. множеств $n$-мерного пространства сводится к вычислению $n$-кратных интегралов.

Если $E$ есть $n$-мерный параллелепипед, натянутый на радиус-векторы $a_{1}, \ldots, a_{n}$, то

\[
v(E)=\sqrt{\left|\operatorname{det}\left\|a_{i}, a_{j}\right\|\right|}
\]

(под корнем столт абсолютная величина определителя Грама векторов $\left.a_{1}, \ldots, a_{n}\right)$.

O. подмножества $E$-мерного риманова многообразия с метрикой

\[
d s^{2}=\sum_{i, j=1}^{n} g_{i j} d x^{i} d x^{j}
\]

наз. величина интеграла

\[
\int \cdots \int_{E}|g| d x^{1} \ldots d x^{n}
\]

где $g=\operatorname{det}\left\|g_{i j}\right\|$.

Обобщением понятия О. является понятие керы. Иногда термины «О». и «мера» употребляются как синонимы.

Понятие О. рассматривается не только в евклидовых, но и в афффинных пространствах. Пусть $E$ - подмножество $n$-мерного аффинног п пространства $\mathbb{R}^{n}$ и пусть в $\mathbb{R}^{n}$ задана афффпнная система координат $\left(x^{1}, \ldots, x^{n}\right)$. Пусть

\[
V_{x}(E)=\int \ldots \int_{E} d x^{1} \ldots d x^{n} .
\]

Если $\left(y^{1}, \ldots, y^{n}\right)$ - другая система координат и $y^{i}=$ $=a_{j}^{i} x^{j}+b^{i}, \quad$ то

\[
V_{y}(E)=\left|\operatorname{det}\left\|a_{j}^{i}\right\|\right| V_{x}(E)
\]

т. е. интеграл $V_{x}(E)$ является знакогостоянным относительным инвариантом веса - 1 . Относительный инвариант $V_{x}(E)$ наз. а фф и н н ы м О. множества $E$. Афффиный О. не меняется при параллельном переносе. и если $E=E_{1} \cup E_{2}, \quad E_{1} \cap E_{2} \neq \varnothing$ и $V_{x}\left(E_{1}\right), V_{x}\left(E_{2}\right)$ определены, то $V_{x}(E)=V_{x}\left(E_{1}\right)+V_{x}\left(E_{2}\right)$. Аффинный О. обладает следующими свойствами, инвариантными относительно аффинного преобразования координат: 1) если О. двух тел равны в одной системе координат, то они равны и в другой; 2) если О. нек-рого множе-