имеет Н. р. с дисперсией, равной нулю). Для случайных элсментов со значениями из какого-либо векторного пространства $E$ это определение сохраняется с заменой $t$ на любой элемент $l$ сопряженного пространства $E^{*}$ и скалярного произведения $(t, X)$ на линейный функционал $l(X)$. Совместное распределение нескольких случайных величин $X_{1}, X_{2}, \ldots, X_{n}$ имеет характеристическую функцию

где

\[
\begin{gathered}
f(t)=\exp \left\{i \mathrm{E}(t, X)-\frac{1}{2} Q(t)\right\}, \\
t=\left(t_{1}, t_{2}, \ldots, t_{n}\right) \in \mathbb{R}^{n},
\end{gathered}
\]

$\mathrm{E}(t, X)=t_{1} \mathrm{E} X_{1}+t_{2} \mathrm{E} X_{2}+\ldots+t_{n} \mathrm{E} X_{n}$

- линейная форма,

\[
Q(t)=\mathrm{E}(t, X-\mathrm{E} X)^{2}=\sum_{k, l=1}^{n} \sigma_{k l} t_{k} t_{l}
\]

- неотрицательно определенная квадратичная форма и $\left\|\sigma_{k l}\right\|-$ ковариационная матрица вектора $X$. В случае положительной определенности соответствующее H. p. имеет плотность всроятности

\[
p\left(x_{1}, x_{2}, \ldots, x_{n}\right)=C \exp \left\{-Q^{-1}\left(x_{1}-a_{1}, x_{2}-a_{2}, \ldots,\right.\right.
\]

где $Q^{-1}$-- квадратичная форма, обратная $Q$, параметры $a_{1}, a_{2}, \ldots, a_{n}$ равны математич. ожиданиям $X_{1}, X_{2}$, $\cdots, X_{n}$ соответственно, а постоянная

\[
C=\frac{1}{(2 \pi)^{n / 2} \sqrt{\operatorname{det}\left\|\sigma_{k l}\right\|}}
\]

Общее количество параметров, задающих Н. р., равно

\[
(n+1)(n+2) / 2-1
\]

и быстро растет с ростом $n$ (оно равно 2 при $n=1$, 20 при $n=5$ и 65 при $n=10$ ). Многомерное Н. р. служит основной моделью многомерного статистицеского анализа. Оно исіользуется также в теории случайных процессов (где рассматриваются Н. р. в бесконечномерных шространствах, см. С.учайный әлемент, а также Винера мера, Винеровский прочесс, Гауссовский прочесс).

Из важных свойств Н. р. необходимо отметить следуюџџе. Сумма $X$ независимых случайных велитин $X_{1}$ и $X_{2}$, пмеющих H. р., имеет Н., р.; обратно, если $X=X_{1}+X_{2}$ имеет H. p. и $X_{1}$ и $X_{2}$ независимы, то $X_{1}$ и $X_{2}$ имеют H. р. (т е о р е м а свойство обладает определенной «устойчивостью»: если распределение $X$ «близко» к Н. р., то и распределения $X_{1}$ и $X_{2}$ «близки» к Н. p. С Н. р. связаны нек-рые другие важные распределения (см. Логариблически норлальное распределение, Неуентральное «хи-квадрат» распределение, Стьюденпа распределение, Уишарта распределение, Фишера z-распределение, Хотеллинаа $T^{2}$-распреоеление, "Хи-квадрат" распределение). Для приближенного представления распределений, близких к H. р., Ілироко применяются ряды типа Эджворта рядов и Грала - IIIарлье рядов.

О вопросах, связанных с оценкой параметров H. p. по результатам наблюдений, см. ст. Несмещенная оценка. О проверке гипотезы нормальносги см. Непараметрические методы статистики. См. также Вероятностиая бумага.

Лит.: [1] Б о л ь ші е в Л. Н., С м и р н о в Н. В., Таблицы математической статистики, 2 изд., М., 1968; [2] Таблицы нормального интеграла вероятностей, нормальной плотности и ее нормированных производных, М., 1960; [3] $\boldsymbol{\Gamma}$ н е д е н к о Б. В., Курс теории вероятностей, 5 изд., М., $1969 ;[4]$ К р ам е р Г., Математические методы статистики, пер. с англ., Теория распределений, пер. с англ., М., 1966; [6] и х ж е, Статистические выводы и связи, пер. с англ., М., 1973.

НОРМАЛЬНОЕ РАССЛОЕНИЕ П О П В $о$ Г $о 0 \%-$ р а зи я -- расслоение, состоящее из касательных век- торов к объемлющему многообразию, нормальных к подмногообразию. Если $X$ - риманово многообразие, $Y$ - его (погруженное) подмпогообразие, $T_{X}$ и $T_{Y}-$ касательные расслоения над $X$ и $Y$, то H. p. $N_{Y, X}$ подміогообразия $Y$ есть подрасслоение в $T_{X} \mid Y$, cocтавленное векторами $u \in T_{X, y}, y \in Y$, ортогональными к $T_{Y, y}$.

С помощью Н. р. строятся, напр., трубчатые окрестности подмногообразий. Н. р. над $Y$, рассматриваемое с точностью до эквивалентности, не зависит от выбора римановой метрики на $X$, поскольку может быть определено без помощи метрики как факторрасслоение $T_{X} \mid Y / T_{Y}$. Несколько более общей является конс грукция Н. р. произвольного погружения $f: Y \rightarrow X$ диффференцируемых многообразий:

\[
N_{Y / X}=f^{*} T_{X} / T_{Y}
\]

Аналогично определяе'ся ${ }^{X}$ H. p. $N_{Y I X}$ неособого алгебраич. подмногообразия $Y$ в неособом алгебраич. многообразии $\bar{X}$ или Н. р. аналитич. подмногообразия $Y$ в аналитпч. многообразии $X$; оно является алгебрапческим (соответственно аналитическим) векторным расслоением над $Y$, paнr к-рого есть codim $Y$. Если, в частности, codim $Y=1$, то расслоение $N_{Y / X}$ изоморфно ограничению на $Y$ расслоения над $X$, определяемого дивизором $\boldsymbol{Y}$.

В случае, когда $\boldsymbol{Y}$ - аналитич. подпространство аналитич. пространства $\left(X, O_{X}\right)$, H. p. подпространства $Y$ иногда называют аналитич. семейство векторных пространств $N_{Y / X} \rightarrow Y$, двойственное к конормальному пучку $N_{Y / X}^{*}$ (см. Норма.ıьный пучок). О прпложениях H. p. к вопросу о стягиваемости подмногообразий см. Исключительное аналитическое множество, Исключительное подмногообразие.

Лит.: [1] Итоги науки и техники. Алгебра. Топология. Геометрия, т. 15, М., 1977, с. 132-56; [2] М и л н о р Д ж., С т aIII е Ф Д Ж., Характеристические классы, пер. с англ., М.,
1979 ; [3] Р о л и н В. А., Ф у с д Д. Б., Начальный курс $1979 ;$ [3] Р о х л и н В. А., Ф у к с Д. Б., Начальный курс
топологии. Геометрические главы, М., 1977 ; [4] х и р ші М., топологии. Геометрические главы, М., 1977; [4] Х и р II 1 М., ф a p е в и ч И. Р., Основы алгебраической геометрии, м.,
1972 .
А. Онищик.

НОРМАЛЬНОЕ РАСШІРЕНИЕ п о л я - алгебраическое расширение $L$ поля $K$, удовлетворяющее одному из следующих эквивалентных условий:

1) любое вложение поля $L$ в алгебраич. замыкание $\bar{K}$ поля $K$ является автоморфизмом поля $L$;

2) $L$ - поле разложения нек-рого семейства многочленов с коэффициентами из $K$;

3) любой неприводимый над $K$ многочлен $f(x)$ с коэффициентами из $K$, имеющий корень в $L$, распадается в $L$ на линейные множители.

Для любого алгебраич. расширения $F / K$ существует максимальное промежуточное подиоле $L$, нормальное над $K$, причем $L=\bigcap^{\circ} F^{\sigma}$, где $\sigma-$ всевозможные вложения поля $F$ в $\bar{K}$. Существует также однозначно определенное минимальное Н. р. поля $K$, содержащее $F$. Это поле является композитом всех полей $F^{\sigma}$. Оно наз. н о р м а льны м з а мы ка ние м поля $F$ относительно $K$. Если $L_{1}$ и $L_{2}-$ нормальные расширения поля $K$, то пересечение $L_{1} \cap L_{2}$ и композит $L_{1} \cdot L_{2}$ снова нормальны над $K$. Однако даже еслй расппирения $L / K^{\prime}$ и $K^{\prime} / K$ нормальны, расширение $L / K$ может и не быть нормальным.

Для полей характеристики 0 любое нормальное расширение является расширением Галуа. В облем случае Н. р. является расширением Галуа тогда и только тогда, когда оно сепарабельно.

![](https://cdn.mathpix.com/cropped/2023_07_08_12552469845b30db8444g-1.jpg?height=49&width=798&top_left_y=2161&top_left_x=1025)

![](https://cdn.mathpix.com/cropped/2023_07_08_12552469845b30db8444g-1.jpg?height=49&width=839&top_left_y=2186&top_left_x=982)
968; [3] П о с т н к к в М. М., Теория Галуа, М., 1963 . НОРМАЛЬНОЕ СЕМЕЙСТВО а н а Л и т и ч $е$ с к и ф ун к ц й в о бл а с ти-такое семейство $S$ од-