изложение было дано Ф. Энрикесом (F. Enriques, о его результатах см. [2]; современное изложение в [3], [4], обобщение в [5]).

Jum.: [1] N öt h e r M., "Math. Ann.», 1880, Bd 17, S. 263-84; [2] B a b b a g e D. W., "J. London Math. Soc."), 1939, v. 14, № 4, p. $310-14 ;[3]$ S a in t-D o n a t B., "Math.
Ann.", 1973, Bd 206, S. 157-75; [4] III o k y p o B B. B.,

![](https://cdn.mathpix.com/cropped/2023_07_08_62bae0756977231ffe01g-1.jpg?height=45&width=834&top_left_y=347&top_left_x=119)
lo E., S e r n e s i E., "Invent. math.", 1978, v. 49, p. 99НЁТЕРОВ МОДУЛЬ - модуль, любой подмодуль к-рого обладает конечной системой образующшх. Эквивалентные условия: любая строго возрастающая цепочка подмодулей обрывается на конечном номере; любое непустое множество подмодулей, упорядоченное относительно включения, содержит максимальный әлемент. Подмодуль и фактормодуль Н. м. также нётеровы. Если в точной последовательности модулей

\[
0 \rightarrow M^{\prime} \rightarrow M \rightarrow M^{\prime \prime} \rightarrow 0
\]

модули $M^{\prime}$ и $M^{\prime \prime}$ нётеровы, то $M$ также нётеров. Модуль над нётеровыл кольцом нётеров тогда и только тогда, когда он имеет конечное число образующих.

Лит.: [1] Л е н г С., Алгебра, пер. с англ., М., 1968.

НЁTEPOB OПЕРАТОР - линейный оператор, одновременно $n$-нормальный и $d$-нормальный (см. Hopмально разрешимый оператор). Иначе говоря, Н. о. $A$ - это нормально разрешимый оператор с конечной $d$-характеристикой $(n(A)<+\infty, d(A)<+\infty)$. Индекс $\chi(A)$ Н. о. $A$ также является конечным числом. Простейший пример Н. о. - линейный оператор действующий из $\mathbb{R}^{k}$ в $\mathbb{R}^{l}$. Название по имени Ф. Нётера [1], с работ к-рого теория Н. о. развивается параллельно теории сингулярных интегральных уравнений. Линейные операторы, порождаемые общими краевыми задачами для әллиптич. уравневий, часто являются H. o.

На практике обычно удается проверить справедливость следующих предложений (т е о р е м ы Н ё т еp a):

1) либо уравнение $A x=0$ не имеет нетривиальных решений, либо оно имеет конетное число $n$ линейно независимых решений;

2) либо неолнородное уравнение $A x=y$ разрешимо при любой правой части $y$, либо для его разрешимости необходимо и достаточно, чтобы $\left\langle y, \psi_{i}\right\rangle=0, i=1, \ldots, m$, где $\left\{\psi_{i}\right\}^{m}$ - полная система линейно независимых решений союзного однородного уравнения или формально сопряженной однородной задачи.

Из 1), 2) следует, что $A$ - Н. о.

Свойство нётеровости устойчиво: если $A-$ Н. о., a $B$ - линейный оператор достаточно малой нормы или вполне непрерывный, то $A+B$ - также Н. о., при этом $\chi(A+B)=\chi(A)$.

Пусть $A \in L(X, Y)$, где $L(X, Y)$ - пространство линейных операторов из $\underset{X}{\boldsymbol{B}} \stackrel{Y}{\boldsymbol{Y}}$, и является Н. о. Тогда имеют место прямые разложения

\[
X=N(A)+\hat{X}, \quad Y=Z+R(A),
\]

где $N(A)$ - подпространство нулей $A, R(A)$ - область значений $A, \operatorname{dim} Z=d(A)$. Общее решение уравнения $A x=y, y \in R(A)$, имеет вид $x=\hat{A}^{-1} y+v$, где $\hat{A}=L(\hat{X}$, $R(A)), \hat{A}=A$ на $\hat{X}$ (сужение $A$ ), а $v \in N(A)-$ произвольно. Если $A$ - Н. о. с $d$-характеристикой $(n, m)$, то $A *$ H. о. с $d$-характерістикой $(m, n)$.

Jum.: [1] N o e th e r F., «Math. Ann.», 1921, Bd 82 S. $42-63 ;[2] \mathbf{K} \mathbf{p}$ е й н C. $\boldsymbol{\Gamma}$. , Јинейные уравнения в банаховом гространстве, М., $1971 ;$ [3] В а й н б е р $\mathbf{T}$ М. М., Т р е н огин
ний, А., Теория ветвления решений нелинейных уравне-
М., 1969.

НЁЕРОВА ГРУПIА, г р у п п а с у с л о в и е м

![](https://cdn.mathpix.com/cropped/2023_07_08_62bae0756977231ffe01g-1.jpg?height=42&width=836&top_left_y=2227&top_left_x=133)
группа, в к-рой любая строго возрастающая цепочка подгрупп обрывается на конечном номере. Названа в честь Э. Нётер (E. Noether), к-рая изучала кольца с условием максимальности для идеалов - нётеровы кольца. Подгруппа и факторгруппа Н. г. также обладают әтим свойством. Построены примеры Н. г., не являющихся конечными расширениями полициклически групі [1].

Лum.: [1] О л ь шा а н с к и й А. Ю., «Докл. АН СССР», 1979, т. 245, N․ 4, с. 785-87. В. Н. Ремесленникое

НЁТЕРОВА ИНДУКЦИЯ - принцип рассуждений, применимый к частично упорядоченному множеству, в к-ром любое непустое подмножество содержит минимальный әлемент, напр. к множеству замкнутых подмножеств в нек-ром нётеровом пространстве. Пусть $M$ - такое множество и $F$ - его подмножество, обладающее тем свойством, что для любого $a \in F$ найдется строго меньший элемент $b \in F$. Тогда $F$ пусто. Нашр., пусть $M$ - множество всех замкнутых подмножеств нек-рого нётерова пространства и $F$ - множество тех замкнутых подмножеств, к-рые нельзя представить в виде конечного объединения неприводимых компонент. Если $Y \subset F$, то $Y$ приводимо, т. е. $Y=Y_{1} \cup Y_{2}$, где $Y_{1}$, $Y_{2}$ замкнуты, оба строго содержатся в $Y$ и хоть одно из них принадлежит $F$. Следовательно $F$ пусто.

Обращение порядка позволяет применять Н. и. также к частично упоря доченным множествам, любое непустое подмножество которых содержит максимальный элемент, например к решетке идеалов в нётеровом кольце.

Лит.: [1] Б у р б а к и Н., Коммутативная алгебра, пер. с франц., М., 1971 . .Л. В. Кузьмит. HЁTEPOBА СХЕМА - схема, допускающая конечное открытое покрытие спектрами нёперовых колец. Афффиная Н. с. - в точности спектр нётерова кольца. Топологич. пространство Н. с. $X$ является нётеровым топологич. пространством, а все локальные кольца $\sigma_{x} x$ нётеровы. Если каждая точка схемы обладает открытой афৃфинной нётеровой окрестностью, схема наз. л о к а л ь н о н ё т е р о в о й. Квазикомпактная локально Н. с. есть Н. с. Примером Н. с. является схема конечного типа нал полем (алгебраич. многообразие) $\begin{array}{rlr}\text { или над любым нётеровым кольцом. } & \text { В. И. Данилов. } \\ \text { НЁТЕРОВО ИНТЕГРАЛЬНОЕ УРАВНЕНИЕ - ин- }\end{array}$ НЁТЕРОВО ИНТЕГРАЛЬНОЕ УРАВНЕНИЕ - интегральное уравнение, для к-рого справедливы теоремы
Нётера (см. ниже). Пусть $X$ - банахово пространство, $A$ - линейный ограниченный оператор (отображение), отображающий $X$ в себя: $A: X \rightarrow X, A *-$ сопряженный с $A$ оператор,

\[
A x=y
\]

- линейное уравнение, где $x$ - искомый, а $y$ - заданный элементы пространства $X$. Пусть, далее, $R(A)-$ совокупность всех $y \in X$, для к-рых уравнение (1) разрепимо (о б л а с т в 3 н а ч е н и ї о п е р а т ор а $A$ ), и $N(A)$ - совокупность всех решений соответствующего однородного уравнения

\[
A x=0
\]

(н у ль-п ро с т р а н с т в о, Іли я д ро о п е р ат о р а $A$ ). Отображение $A$ (уравнение (1)) наз. нётеровым оператором (нё т е р о в ы м у р а в н е н ие м), если выполняются следующие условия.

1) Определенный на всем банаховом пространстве оператор $A$ (уравнение (1)) является н о р м а л ь н о р а з р е ши и м ы м, т. е. уравнение (1) разрешимо тогда и только тогда, когда правая часть $y$ ортогональна всем решениям сопряженного однородного уравнения

\[
A^{*} \varphi=0, \varphi \in X^{*},
\]

т. е. $(\varphi, y)=0$ для любого $\varphi \in N(A *)$.

2) Однородные уравнения (2) пा (3) могут иметь лишь конечное число линейно незавпсимых решений; число

\[
x_{A}=k-k^{*}
\]