КРИСТАЛЛОГРАФИЯ МАТЕМАТИЧЕСКАЯ - coвокупность методов описания внешних форм крісталлов и их внутреннего пространственного строения. В основе К. м. лежит представление об упорядоченном трехмерно периодическом расположении в кристалле составляющих его частиц, к-рые образуют кристаллич. решетку. Выросшие в равновесных условиях кристаллы имеют форму правильных выпуклых многогранников той или иной симметрии. Группы симметрий классифицируют: по числу $n$ измерений пространства, в к-ром они определены; по числу $m$ измерений пространства, в к-рых объект периодичен (их соответственно обозначают $\left.G_{m}^{n}\right)$ и по нек-рым другим признакам. Для описания кристаллов используют различные группы сімметриІ, из к-рых важнейшшми являются пространственные группы $G_{3}^{3}$, описывающис атомную структуру кршсталлов, и точечные группы симметрии $G_{0}^{3}$, описывающие их внешнюю форму.

Операциями т о ч е ч н о й г р у п п ы симметрии являются: повороты вокруг оси симметрии порядка $N$ на $360^{\circ} / N$, отражение в плоскости симметрии (зеркальное отражение), инверсия $\bar{I}$ (симметрия относительно точки), инверсионные повороты $\bar{N}$ (комбинация поворота на $360^{\circ} / N$ с одновременной инверсией). Вместо инверсионных поворотов иногда рассматривают зеркальные повороты $\tilde{N}$. Число групп $G_{0}^{3}$ бесконечно. Однако в кристаллах ввиду наличия кристаллич. решетки возможны только операции и соответственно оси симметрий до 6-го порядка (кроме 5-го), к-рые обозначаются символами $1,2,3,4,6$, а также инверсионные оси: I (она же пснтр симметрии), $\overline{2}=m$ (она же плоскость симметрпи, $\overline{3}, \overline{4}, \overline{6})$. Количество точечных кристаллографич. групп, описывающих внешнюю форму кристаллов, огрангчено: 32 группы.

Группы, содержащие лишь повороты, описывают кристаллы, состоящие только из совместимо равных частей. Эти группы наз. группами 1-го рода. Группы, содержащие отражения, или инверсионные повороты, описывают кристаллы, в к-рых есть зеркально равные части (но могут быть и совместимо равные части). Эти группы наз. группами 2-го рода. Кристаллы, описываемые группами 1-го рода, могут кристаллизоваться в двух әнантиоморфных формах, условно наз. «правой» и «левой», каждая из них не содержит элементов симметрии 2-го рода, но они зеркально равны друг другу.

Многие свойства кристаллов, принадлежащих к опре деленным классам, описываются пр ед е ль ны м и точ еч ным и г р у п а м и, содержащимı оси симметрии бесконечного порядка. Наличие такой оси означает, что объект совмещается с собой при повороте на любой, в том числе бесконечно малый угол. Таких групп семь.

П р о с т р а с т в н н а я г р у п п а симметрий кристаллич. решетки описывается группами $G_{3}^{3}$. Хaрактерными для решетки операциями являются три некомпланарных переноса $\boldsymbol{a}, \boldsymbol{b}, \boldsymbol{c}$, к-рые отвечают трехмерной периодичности атомной структуры кристаллов.

Вследствие возможности комбинирования в решетке трансляций и операций точечной симметрии в группах $G_{3}^{3}$ возникают операции и соответствующие әлементы симметрии с трансляционной компонентой - винтовые оси различных порядков и плоскости скользящего отражения.

Всего известно 230 пространственных (федоровских) групп симметрии $G_{3}^{3}$, и любой кристалл относится к одной из этих групп. Трансляционные компоненты әлементов микросимметрии микроскопически не проявляются; поэтому каждая из 230 групп $G_{3}^{3}$ макроскопически сходственна с одной из 32 точечных групп. Сово- купность переносов, присущих данной пространственной группе, есть ее трансляционная подгруппа, иліп р еш е т к а Б р а в е; таких решеток существует 14. См. также Кристаллогра бическая группа.

![](https://cdn.mathpix.com/cropped/2023_07_08_342574b895d5e42284b2g-1.jpg?height=54&width=809&top_left_y=298&top_left_x=1017)
к и й $\Gamma$. Б., Основы кристашлографии, М.- г., 1940; [2] Ф е-
д о р о в Е.. С., Симметрия и структура кристаллов, [M.], 1949; [3] III а є к о ль с к а я М., Кристаллы, М., 1959.

из $Б C \vartheta-3$. КРИСТОФФЕЛЯ СИМВОЛ д и ф ф е р е н ц і а л ьно й к в а д р а т чин о й формы

\[
\sum_{r, s=1}^{n} g_{r s} d x^{r} d x^{s}
\]

- символ для сокращенного обозначения выражения

\[
\frac{1}{2}\left(\frac{\partial g_{i k}}{\partial x_{j}}+\frac{\partial g_{i k}}{\partial x_{i}}-\frac{\partial g_{i j}}{\partial x_{k}}\right) \equiv \Gamma_{k, i j}
\]

Символ $\Gamma_{k, i j}$ наз. К. с. 1-го рода, в отличіс от К. с. 2-го рода $\Gamma_{i j}^{k}$, определяемого соотношением

\[
\Gamma_{i j}^{k}=\sum_{t=1}^{n} g^{k t} \Gamma_{k, i j}
\]

где $g^{k t}$ определяется из равенств

\[
\sum_{k=1}^{n} g^{k t} g_{k s}=\left\{\begin{array}{l}
1, \text { если } t=s, \\
0, \text { если } t \neq s .
\end{array}\right.
\]

К. с. введен Э. Кристоффелем (Е. Christoffel, 1869).

КРИСТОФФЕЛЯ ЧИСЛА, К $p$ и с т о ф ф е л я к о э ф ф и ц и е н т ы, - коэффициенты $\lambda_{k}$ квадратурной формулы

\[
\int_{a}^{b} f(x) d \alpha(x) \approx \sum_{k=1}^{n} \lambda_{k} f\left(x_{k}\right)
\]

точной для алгебраич. многочленов степені $\leqslant 2 n-1$. Узлы $x_{k}$ такой квадратурной формулы являются нулями многочлена $p_{n}(x)$ степени $n$, ортогонального на $[a, b]$ относительно распределения $d \alpha(x)$ всем многочленам степени $n-1$; если $x_{1}<x_{2}<\ldots .<x_{n}$, то $\mathcal{K}$. ч. определяІотся однозначно. К. ч. $\lambda_{k}>0, \Sigma_{k=1}^{n} \lambda_{k}=\alpha(b)-\alpha(a)$ и

\[
\lambda_{k}=\int_{a}^{b}\left[\frac{p_{n}(x)}{p_{n}^{\prime}(x)\left(x-x_{k}\right)}\right]^{2} d \alpha(x), k=1,2, \ldots, n .
\]

Если многочлены $p_{n}(x)$ ортонормированны, то К. ч. представимы в виде

\[
\begin{gathered}
\lambda_{k}^{-1}=p_{0}\left(x_{k}\right)+p_{1}\left(x_{k}\right)+\ldots+p_{n}\left(x_{k}\right), \quad k=1,2, \ldots, n, \\
\lambda_{k}=-\frac{K_{n+1}}{K_{n}} \frac{1}{p_{n+1}\left(x_{k}\right) p_{n}^{\prime}\left(x_{k}\right)}= \\
=\frac{K_{n}}{K_{n-1}} \frac{1}{p_{n-1}\left(x_{k}\right) p_{n}^{\prime}\left(x_{k}\right)}, \quad k=1,2, \ldots, n,
\end{gathered}
\]

где $K_{n}$ - старший коэффициент многочлена $p_{n}(x)$. В случае $a=-1, b=1$ и $d \alpha(x)=d x p_{n}(x)$ являются жандра многочленами, а К.ч.

\[
\lambda_{k}=\frac{2}{\left(1-x_{k}^{2}\right)\left[p_{n}^{\prime}\left(x_{k}\right)\right]^{2}} .
\]

Эти выраженгя указаны Ә. Кристоффелем [1]. Для $n=1,2, \ldots, 7$ әти коэффициешты были вычислены К. Гауссом (C. Gauss). См. также Гаусса квадратурная боржула.

Jum.: [1] C h r is t of f e l E. B., "J. reine und angew.

![](https://cdn.mathpix.com/cropped/2023_07_08_342574b895d5e42284b2g-1.jpg?height=52&width=838&top_left_y=2142&top_left_x=985)
многочлены, пер. с англ., М., 1962; [3] Н а т а н с о н И. П.,
Конструктивная теория функций, М.- Л., 1949 .
Н. П. Корнейчук, В. П. Моторный.

КРИСТОФФЕЛЯ - ДАРБУ ФОРМУЛА для многочленов $\left\{P_{n}(x)\right\}$, ортонормированных с интегральным ве-