справедливо неравенство (см. [1] с. 135-39)

\[
\begin{aligned}
& \left.\left|\frac{z}{f(z)}+c_{2} z+1-\right| z\right|^{2}-2 \frac{\boldsymbol{E}(|z|)}{\boldsymbol{K}(|z|)} \mid \leqslant \\
& \quad \leqslant 2\left(1-\frac{\boldsymbol{E}(|z|)}{\boldsymbol{K}(|z|)}\right), \quad|z|<1,
\end{aligned}
\]

где $\boldsymbol{E}$ и $\boldsymbol{K}$ - полные эллиптические интеграль. Если $z$ фиксировано $(0<|z|<1)$, то это неравенство определяет область значений функционала $\frac{z}{f(z)}+c_{2} z$ в класce $S$. Получены усиления теорем искажения и доказаны теоремы об исказкении хорд в классах $\Sigma$ и $\Sigma(B)$ (см. Искажения теоремы и [1] с. 118-35).

См. также Контурного интегрирования метод, Площадей принцип.

3. Метод площадей. Пусть $\mathfrak{M}\left(a_{1}, \ldots, a_{n}\right)$ - класс систем функций $\left\{f_{k}(z)\right\}_{k=1}^{n}$, конформно и однолистно отображающих круг $\Delta=\{|z|<1\}$ на области $B^{k} \ni a_{k}$, попарно не пмеющие общих точек (неналегающие области), и нормированных условиями $f_{k}(0)=a_{k}$. С помоцью теоремы площадей в классе $\mathfrak{M}\left(\infty, a_{1}, \ldots, a_{n}\right)$, в частності, получены следующие результаты: 1) если

To

\[
\left\{f_{k}\right\}_{k=1}^{n} \in \mathfrak{M}\left(a_{1}, \ldots, a_{n}\right), a_{k} \neq \infty,
\]

\[
\begin{aligned}
& \prod_{k=1}^{n}\left|f_{k}^{\prime}(0)\right|^{\left|\gamma_{k}\right|^{2}} \leqslant
\end{aligned}
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_c1ccb328240649476170g-1.jpg?height=63&width=578&top_left_y=968&top_left_x=232)

\[
\begin{aligned}
& \sum_{k=1}^{n} \gamma_{k}=0
\end{aligned}
\]

это неравенство обобщает на случай комплексных $\gamma$ пзвестное ранее неравенство для действительных $\gamma_{k}$;

2) если $\left\{f_{0}, f_{1}\right\} \in \mathbb{M}(0, \infty)$, то

\[
\frac{1}{2 \pi} \int_{0}^{2 \pi}\left|f_{0}\left(e^{i t}\right)\right|^{2} d t \cdot \frac{1}{2 \pi} \int_{0}^{2 \pi}\left|f_{1}\left(e^{i t}\right)\right|^{-2} d t \leqslant 1 .
\]

Для Бибербаха - Эйленберга бункций

\[
f(z)=\sum_{k=1}^{\infty} a_{k} z^{k}
\]

отсюда следует неравенство

\[
\sum_{k=1}^{\infty}\left|a_{k}\right|^{2}=\frac{1}{2 \pi} \int_{0}^{2 \pi}\left|f\left(e^{i t}\right)\right|^{2} d t \leqslant 1 ;
\]

выяснены условия, при выполнении к-рых в (4) и (4') имеет место знак равенства.

C помощью теоремы площадей для неналегающих областей получена оценка приближения функции, регулярной на замкнутой многосвязной области, рациональной функцией, интерполирующей заданную функцию в узлах, равнорасположенных на границе области (см. [4] с. 143-54). Получена область значений ш в а р ц и а н а

\[
\{F(z), z\}=\left(\frac{F^{\prime \prime}(z)}{F^{\prime}(z)}\right)^{\prime}-\frac{1}{2}\left(\frac{F^{\prime \prime}(z)}{F^{\prime}(z)}\right)
\]

для $F \in \Sigma(B)$ и ряд других областей значений в класcaх функций, заданных в многосвязных областях (см. [4], [5]).

4. Метод Лёвнера. Сам К. Лёвнер (К. Löwner, 1923) получил точную оценку $\left|c_{3}\right| \leqslant 3$ для функций $f \in S$ II точные оценки коэффициентов разложения функции, обратной к $f$, в окрестности точки $w=0$. В частности, этим методом получена точная форма теоремы вращения в классе $S$ (см. Вращения теоремь). Доказана теорема: для $f \in S$ при заданных $z \in \Delta$ Іі $|f(z)|$ справедливо неравенство

\[
\left|f^{\prime}(z)\right| \leqslant \frac{1}{1-|z|^{2}}\left|\frac{f(z)}{z}\right|^{2}\left(1-x^{2}\right)^{2}\left|\frac{x}{z}\right|^{4 x^{2} /\left(1-x^{2}\right)},
\]

Неравенство (5) точное. Из (5) следуют точные неравенства в классе $S(0 \leqslant \theta \leqslant 2 \pi, 0 \leqslant r<1)$ :

\[
\left.\begin{array}{c}
\left|f\left(r e^{i \theta}\right)\right|+\left|f\left(-r e^{i \theta}\right)\right| \leqslant \frac{r}{(1-r)^{2}}+\frac{r}{(1+r)^{2}}, \\
\left|f^{\prime}\left(r e^{i \theta}\right)\right|+\left|f^{\prime}\left(-r e^{i \theta}\right)\right| \leqslant \frac{1+r}{(1-r)^{3}}+\frac{1-r}{(1+r)^{3}} .
\end{array}\right\}
\]

Был введен весьма широкий подкласс функций $f \in S$, представимых в виде

\[
f(z)=\left[(\alpha+i \beta) \int_{0}^{z} p(s) g(s)^{\alpha} s^{i \beta-1} d s\right]^{1 /(\alpha+i \beta)},
\]

где $g$ - звездообразная функция, $p-$ регулярная в $\Delta$ функция и такая, что $\operatorname{Re}\left\{e^{i \gamma_{p}(z)}\right\}>0$ для нек-рого $\gamma \in[-\pi / 2, \quad \pi / 2], \quad p(0)=1, \quad \alpha>0, \quad-\infty<\beta<+\infty \quad$ (cm. [6] c. 47).

С помощью теорем искажения было установлено, что функция Кёбе

\[
K_{\alpha}(z)=z\left(1-e^{i \alpha} z\right)^{-2} \in S
\]

( $\alpha$ - действительное) реализует максимум линейной меры покрытия окружности $|w|=\rho$ образом $B(r)$ круга $\Delta_{\boldsymbol{r}}=\{|z|<r<1\}$ при отображении функциями класса $S$, когда $\rho>e^{\pi / e} r$. Из этого свойства функций класса $S$ следуют оценки площади $\sigma(r)$ области $B(r)$, оценки среднего модуля функции и другие оценки в классе $S$, асимптотически точные при $r \rightarrow 1$ (см. [1] с. 561).

Была предложена нек-рая удобная редукция әкстремальных задач на классе $S$ и нек-рых его подклассах к определенным экстремальным задачам на более простом классе (см. Каратеодори класс), оказавшаяся применимой к решению ряда экстремальных задач, в частности к нахождению области значений системы функционалов $\left\{\ln \frac{f(z)}{z}, \ln f^{\prime}(z)\right\}$ (здесь $z, 0<|z|<1$, фиксировано) для $f \in S$ (см. [6] с. 115-58).

Метод Лёвнера успешно применялся к исследованию свойств линий уровня и к решению экстремальных задач на подклассе $S_{M}$ ограниченных функций $f \in S$ : $|f(z)| \leqslant M, \quad z \in \Delta(\mathrm{cm} .[6]$ c. $150-77)$.

См. также Лёвнера уравнение, Лёвнера метод, Параметрических представлений метод.

5. Вариационные методы. Граничные и внутренние вариации при решении әкстремальных задач приводят к дифференциальным уравнениям для границ әкстремальных областей и, соответственно, для әкстремальных функций. Левая часть этих уравнений, как правило, есть нек-рый квадратичный дифференциал. Различные качественные характеристики функций, реализующих экстремум, получаются при исследовании свойств соответствующих квадратичных дифференциалов. В частности, для большого числа экстремальных задач в классе $S$ (и в других классах) оказывается, что әкстремальная функция отображает круг $\Delta$ на всю плоскость с конечным числом аналитич. разрезов. Иногда дифференциальное уравнение для экстремальной функций удается проинтегрировать и тем самым получить величину экстремума в исследуемой задаче и все әкстремальные функции. Чаще удается лишь получить одно или несколько конечных уравнений для величины әкстремума. Нек-рые результаты, полученные вариационным методом, перечислены ниже.

Пусть $F \in \Sigma, w_{k}, k=1, \ldots ., n, n \geqslant 2$, не принадлежат образу области $\Delta^{\prime}=\{|z|>1\}$ при отображении $w=F(z)$ и пусть

\[
d_{n}(F)=\prod_{1 \leqslant k<l \leqslant n}\left|w_{k}-w_{l}\right|
\]

Доказано, что

\[
d_{3}(F)=\left|\left(w_{1}-w_{2}\right)\left(w_{2}-w_{3}\right)\left(w_{3}-w_{1}\right)\right| \leqslant 12 \sqrt{3}
\]

І знак равенства имеет место только для

\[
F(z)=z\left(1+e^{i \alpha} z^{-3}\right)^{2 / 3}
\]

где $\alpha$ - действительное (см. [1] с. 140-46).

\[
\left|\frac{f(x)}{z}\right|(1+x)^{2}\left|\frac{z}{x}\right|^{2 x /(1+x)}=1 \text {. }
\]