На Н. и. переносятся общие свойства интегралов: линейность, адцитивность относительно промежутков, по к-рым производится интегрирование, правило интегрирования неравенств, теоремы о среднем, интегрирование по частям и замены переменного, формула Ньютона - Лейбница. Напр., если функция $f$ почти всюду на $[a, b)$ совпадает с производной функции $F$, к-рая абсолютно непрерывна на каждом отрезке $[a, \eta], a<\eta<b$, To

\[
\int_{a}^{b} f(x) d x=F(b-0)-F(a) .
\]

Для выяснения сходимости Н. и. от знакопостоянных функций применяется п р и з в а к с р а в н е н и я: напр., для Н. и. вида (1) при выполнении условия

\[
f(x)=O(g(x)),
\]

$x \rightarrow b-0, f(x) \geqslant 0, g(x) \geqslant 0, x \in[a, b)$, из сходимости Н. и.

\[
\int_{a}^{b} g(x) d x
\]

следует сходимость Н. и.

\[
\int_{a}^{b} f(x) d x
\]

функция $g(x)$ наз. в этом случае ф у н к ц и е й с р а вн е н и я. В качестве функции сравнения для интегралов (1) в случае конечного предела интегрирования $b$ часто используются функции $1 /(b-x)^{\alpha}$; для интегралов вида (2) в случае конечности предела интегрирования $a$ - функции $1 /(x-a)^{\alpha}$, при наличии одного или двух бесконечных пределов интегрирования - функции $1 /|x| \alpha$. Из признака сравнения следует, напр., если для неотрицательной функции $f$, определенной при $x \geqslant a$, существует предел

\[
\lim _{x \rightarrow+\infty} x^{\alpha} f(x)=k,
\]

то при $\alpha>1$ и $0 \leqslant k<+\infty$ Н. и.

\[
\int_{a}^{+\infty} f(x) d x
\]

вида (1) сходится, а при $\alpha \leqslant 1$ и $0<k \leqslant+\infty$ Н. и. расходится.

Необходимое и достаточное условие сходимости Н. и. дает критерий Коши. Так, Н. и. вида (1) сходится тогда и только тогда, когда для любого $\varepsilon>0$ существует такое $\eta \in[a, b)$, что для всех $\eta^{\prime} \in(\eta, b), \eta^{\prime \prime} \in(\eta, b)$ выполняется неравенство

\[
\left|\int_{\eta^{\prime}}^{\eta^{\prime \prime}} f(x) d x\right|<\varepsilon
\]

H. и.

\[
\int_{a}^{b} f(x) d x
\]

наз. а б с о л тн о с $\mathbf{0}$ о д я щ м я я, если сходится Н. и.

\[
\int_{a}^{b}|f(x)| d x
\]

Если Н. и. абсолютно сходится, то он сходится и совпадает с интегралом Лебега. Существуют Н. и. сходящиеся, но не абсолютно. Напр., для конечного промежутка Н. и.:

\[
\int_{0}^{1} \frac{1}{x} \sin \frac{1}{x} d x
\]

a для бесконечного:

\[
\int_{1}^{+\infty} \frac{\sin x}{x} d x
\]

Существуют различные признаки для установления сходимости Н. и. Так, если функции $f$ и $g$ определены для $x \geqslant a$, функция $f$ имеет на полуоси $x \geqslant a$ ограниченную первообразную, a $g$ - монотонная функция, стремящаяся к нулю при $x \rightarrow+\infty$, то Н. и.

\[
\int_{a}^{+\infty} f(x) g(x) d x
\]

сходится. Другой признак: если Н. и.

\[
\int_{a}^{+\infty} f(x) d x
\]

сходится, а функция $g$ монотонна и ограничена при $x \geqslant a$, то Н. и.

\[
\int_{a}^{+\infty} f(x) g(x) d x
\]

сходится.

Сходимость Н. и. можно выразигь в терминах сходящихся рядов: напр., для того чтобы Н. и. (1) сходился, необходимо и достаточно, чтобы для любой последовательности $b_{n} \rightarrow b, a \leqslant b_{n}<b, n=0,1,2, \ldots \ldots$, сходился ряд

\[
\sum_{n=1}^{\infty} \int_{b_{n-1}}^{b_{n}} f(x) d x
\]

причем в случае его сходимости сумма ряда совпадает c Н. и. (1).

Понятие Н. и. обобщается для функций многих переменных. Пусть функция $f$ определена на открытом (ограниченном или неограниченном) множестве $G$-мерного евклидова пространства $\mathbb{R} n$ и интегрируема по Риману на любом измеримом по Жордану множестве $E, \bar{E} \subset G$. Функцию $f$ наз. и н т е г р и р у е м о й в не с об с т в нном смыс л е по множеству $G$, если для любой последовательности измеримых по Жордану множеств $E_{k}$ таких, что $\overline{E_{k}} \subset G, E_{k} \subset E_{k+1}, k=1$, $2, \ldots$, и $\bigcup_{k=1}^{\infty} E_{k}=G$, существует предел

\[
\lim _{k \rightarrow+\infty} \int_{E_{k}} f(x) d x
\]

не зависящий от выбора указанной последовательности $E_{k}$. Этот предел, если он сущеотвует, наз. Н. и.

\[
\int_{G} f(x) d x
\]

и, как в одномерном случае, говорят, что этот интеграл сходится. Oн существует тогда и только тогда, когда существует интеграл

\[
\int_{G}|f(x)| d x
\]

В этом случае Н. и.

\[
\int_{G} f(x) d G
\]

совпадает с интегралом Лебега. Әто обстоятельство связано с тем, что пріи $n=1$ и данном выше определении Н. и. переход к пределу осуществлялся по весьма специальному классу измеримых по Жордану множеств, а именно по отрезкам. В качестве же $E_{k}$ были взяты произвольные измеримые по Жордану множества. Впрочем, при $n \geqslant 2$.сделанное утверждение остается в силе и в том случае, когда в качестве множеств $E_{k}$ взяты только измеримые шо Жордану области. Таким образом, в этом случае понятие Н. и. не приводит к новому понятию по сравнению с интегралом Лебега.

Для Н. и. от функции многих переменных справедлив признак сравнения, аналогичный одномерному случаю. В качестве интегралов сравнения берут

\[
\int_{r \leqslant 1} \frac{d x}{r^{\alpha}} \text { и } \int_{r \geqslant 1} \frac{d x}{r^{\alpha}},
\]