с относительной погрешностью в величинах $Q$ и $v$, не превышающей $2,5 \%$. Штриховая окружность на номограмме соответствует решению числового примера (дано: $i=0,0005 ; b=2 \mathrm{~m} ; Q=2,2 \mathrm{~m}^{3} /$ сек; ответы: $\eta=\mathrm{C}, 5$ и $v=1,1 \mathrm{~m} /$ ceк).

В нек-рых случаях методы приближенного номографирования цают возможность представлять номограммами таблицы с несколькими входами.

Для номографирования данной зависимости ее приводят точно или приближенно к номографируемому виду и записывают уравненпя элементов номограммы в прямоугольной системе координат. Входяшие в эти уравнения параметры преобразования (а иногда и произвольные функции) попбирают так, чтобы придать номограмме удобный для пользования вид. Далее рассчитывают таблицы координат отдельных әлементов номограммы, а затем вычерчивают номограмму.

Получила развитие м а ш и н н а я н о м о г p aф и я (см. [4]): разработаны системы процедур и стандартных программ для автоматич. расчета и построения элементов номограмм с помощью ЭВМ и графопостроителя, а также стандартные программы для автоматич. конструирования, расчета и вычерчивания номограмм различных типов.

Основными проблемами теоретич. Н. являются проблемы представимости и единственности. Суть первой проблемы состонт в том, чтсбы выяснить, можно ли заданное уравнение или систему уравнений шривести к той или иной канонич. форме, и если возможно, то указать алгоритм такого приведения. Получены решения әтой проблемы для нек-рых канонич. форм. Они сложны и на практике не применяются. Суть второй проблемы заключается в том, чтобы выяснить, единственным ли способом приводится данная зависимость к канонич. форме, и если не единственным, то указать все возможные снособы и установить возможности преобразования номограмм в каждом из них.

Лuт.: [1] П е н т к о в с к и й М. В., Номография, М.-Л., $1949 ;$ [2] Н е в с к й й Б. А., Справочная книга по номографии, М.-Л., 1951; [3] Х о в а н с к и й Г. С., Основы номографии, М., 1976; [4] е г о ж е, Номография и ее возможно-
сти. М., 1977.

![](https://cdn.mathpix.com/cropped/2023_07_08_1b136daa1e98a3256d34g-1.jpg?height=45&width=811&top_left_y=1377&top_left_x=140)
пространства $X$ над полем действптелыных или комплексных чисел в совокупность действителыных чисел, подчиненное условиям:

$\|x\| \geqslant 0$, причем $\|x\|=0$ только при $x=0$;

\[
\|\lambda x\|=|\lambda| \cdot\|x\| \text { для каждого скаляра } \lambda \text {; }
\]

$\|x+y\| \leqslant\|x\|+\|y\|$ для всех $x, \quad y \in X \quad$ ( а к с и о м а т р е у г о л ь н и к а). При этом число $\|x\|$ и наз. н о рмо й эл е м е н т а $x$.

Векторное пространство $X$ с отмеченной Н. наз. в о рм и р о в а н ны м пр о с т р а н с т в о м. Н. индуцирует на $X$ метрикy по формуле $\operatorname{dist}(x, y)=\|x-y\|$, a следовательно и топологию, совместимую с этой метрикой. Тем самым нормированное пространство наделяется естественной структурой топологчческого векторного пространства. Нормированное пространство, полное относительно указанной метрики, наз. б а н aх о в ы м п р о с т р н с т в о м. Іаждое нормированное пространство обладает банаховым пополнением.

Отделимое (хаусдорфово) топологическое векторное пространство наз. н о р м и р у е м ы м, если его гопология совместима с нек-рой Н. Нормируемость равносильна существованию выпуклой ограниченной окрестности нуля (т е о р е м а H. в нормированном векторном пространстве $X$ гогда и только тогда порождается скалярным произведением (т. е. пространство $X$ изометрически иаоморфно предгильбертову пространству), когда для всех $x, y \in X$

\[
\|x+y\|^{2}+\|x-y\|^{2}=2\left(\|x\|^{2}+\|y\|^{2}\right) .
\]

Две Н. $\|\cdot\|_{1}$ и $\|\cdot\|_{2}$, заданные на одном и том же векторном пространстве $X$, наз. ә к в и в а л е н т н ы и, если они индуцируют одну и ту же топологию. Әто равносильно существованию таких констант $C_{1}$ и $C_{2}$, что

\[
\|x\|_{1} \leqslant C_{1}\|x\|_{2},\|x\|_{2} \leqslant C_{2}\|x\|_{1} \text { для всех } x \in X .
\]

Если пространство $X$ полно относительно обеих Н., то их эквивалентность является следствием согласованности. При этом согласованность означает, что выполнение предельных соотношений

\[
\left\|x_{n}-a\right\|_{1} \rightarrow 0, \quad\left\|x_{n}-b\right\|_{2} \rightarrow 0
\]

влечет за собой равенство $a=b$.

Не на каждом топологическом векторном пространстве, даже в предположении локальной выпуклости, существует непрерывная Н. Напр., непрерывной Н. нет на бесконечном произведении прямых с топојогией покоординатной сходимости. Отсутствие непрерывной Н. может служить очовидным препятствием к непрерывному погружению одних топологич. иространств в другие.

Если $Y$ - замкнутое подпространство в нормированном пространстве $\dot{X}$, то факторшространство $X ! Y$ классов смежности по $\boldsymbol{Y}$ наделяется $\mathbf{H}$.

\[
\|\tilde{x}\|=\inf \{\|x\|: x \in \tilde{x}\} \text {, }
\]

относительно к-рой оно становится нормированным пространством. H. образа элемента $x$ относительно естественной проекции $X \rightarrow X / Y$ наз. Ф а к т о р н о рм о й э л м е н т а $x$ по подиространству $Y$.

Совокупность $X^{*}$ непрерывных линейных функционалов $\Psi$ на нормированном пространстве $X$ образует банахово пространство относительно $\mathrm{H}$.

\[
\|\psi\|=\sup \{|\psi(x)|:\|x\| \leqslant 1\} .
\]

H. всех функционалов достигаются в подходящих точках единичного шара исходного пространства тогда и только тогда, когда пространство рефлексивно.

Совокупность $L(X, Y)$ линейных непрерывных (ограниченных) операторов $A$ из нормированного пространства $X$ в пормированное пространство $Y$ шревращается в нормированное пространство путем введения о п е р а т о р н о й но р мы:

\[
\|A\|=\sup \{\|A x\|:\|x\| \leqslant 1\} \text {. }
\]

Относительно этой Н. пространство $L(X, Y)$ полно, если полно $Y$. При полном $X=Y$ пространство $I,(X)=$ $=L(X, X)$ с умножением (сушерпозицией) операторов становится банаховой алгеброй, поскольку операторная Н. удовлетворяет условию

\[
\|A B\| \leqslant\|A\| \cdot\|B\|, \quad\|I\|=1,
\]

где $I$-. тождественный оператор (единица алгебры). Интересны и другие эквивалентные H. на $L(X)$, подчиненные тому же условию. Такие Н. наз. а л г е б р аи ч е с к и м и, или к о л ц е в м м. Алгебрапч. H. можно получить, эквивалентно перенормируя $X$ и беря соответствующую операторную Н., однако даже при $\operatorname{dim} X=2$ на этом пути получаются не все алгебраич. Н. на $L(X)$.

П р е пн о р м о й, или по лу но р м о й, на векторном пространстве $X$ наз. отображение $p$ со свойствами Н., кроме свойства невырожденности: равенство $p(x)=0$ не исключает $x \neq 0$. Если $\operatorname{dim} X<\infty$, то ненулевая преднорма $p$ на $L(X)$, подчиненная условию $p(A B) \leqslant p(A) p(B)$, фактически оказывается Н. (т. к. в этом случае $L(X)$ не имеет нетривиалыных пвусторонних пдеалов). С другой стороны, для бесконсчномерных нормированных пространств это уже не так. Если $X$ - банахова алгебра над $\mathbb{C}$, то спектральный радіус

\[
|x|=\lim _{n \rightarrow \infty}\left\|x^{n}\right\|^{1 / n}
\]