Тензор Римана имеет $n^{2}\left(n^{2}-1\right) / 12$ алгебраически независимых компонент. Справедливо так наз. т о ж д ес т в о Б ь я н к и для ковариантных производных тензора Римана

$\left(\nabla_{X} R\right)(Y, Z, U)+\left(\nabla_{Y} R\right)(Z, X, U)+\left(\nabla_{Z} R\right)(X, Y, U)=0$, где $\left(\Delta_{X} R\right)(Y, \quad Z, \quad U)$ - ковариантная производная $R(Y, Z) U$ по $X$. В локальных координатах әто тождество имеет вид

\[
\boldsymbol{R}_{i k l ; m}^{n}+\boldsymbol{R}_{i m k ; l}^{n}+\boldsymbol{R}_{i l m ; k}^{n}=0 .
\]

Иногда тензор Рімана определяго с обратным знаком.

Необходимым и достаточным условием локальной ізометричности ріманова пространства евклидову является равенство нулю его тензора Римана.

Используют и иной, эквивалентный подход к описанию свойств $K$. риманова пространства $M^{n}$. Пусть $\sigma-$ двумерное линейное пространство касательного пространства $T M^{n}$ к $M^{n}$ в точке $P$. Тогда с е к ц и о н н о й к $\mathrm{p}$ и в и 3 н о й $M^{n}$ в точке $\boldsymbol{P}$ в направлении $\sigma$ наз. величина

\[
K_{\sigma}=\frac{\langle\boldsymbol{R}(V, W) W, V\rangle}{\langle V, V\rangle\langle W, W\rangle-\langle V, W\rangle^{2}},
\]

где $V$ и $W$ - векторы, определяющие б. Одна и та же площадка $\sigma$ может определяться разными векторами $V$ I $W$, однако $K_{\sigma}$ не зависит от выбора различных векторов, определяющих одну и ту же площадку. Для двумерного риманова пространства секционная К. совпадает с гауссовой К. Тензор Римана может быть восстановлен по секционным кривизнам следующим образом: $\langle R(X, Y) Z, U\rangle=\frac{1}{6}\{R(X+U, Y+Z)-k(X+U, Y)-$ $-k(X+U, Z)-k(X, Y+Z)-k(U, Y+Z)+k(X, Z)+$ $+k(U, Y)-k(Y+U, X+Z)+k(Y+U, X)+$ $+k(Y+U, Z)+k(Y, Z+X)+$ $+k(U, Z+X)-k(Y, Z)-k(U, X)\}$,

где

\[
k(V, W)=K_{\sigma}\left(\langle V, V\rangle\langle W, W\rangle-\langle V, W\rangle^{2}\right) .
\]

Используют п менее детальные характеристики К. риманова пространства - т е н 3 о $\mathrm{p} \quad \mathrm{P}$ и ч ч и:

\[
R_{i k}=R_{i l k}^{l} \text {, }
\]

и с к а л я р нуюк ри в и 3 н у, или кр и в и 3 н у Р и ч ч и:

\[
R=g^{i k} R_{i k}
\]

Тензор Риччи симметричен: $R_{i k}=R_{k i}$.

Иногда для характеристики $\mathcal{K}$. употребляют и более сложные, в частности квадратичные, конструкции, построенные из тензора Римана. Одним из наиболее употребительных инвариантов такого рода является инвариант

\[
C=R_{k l m}^{i} R_{i}^{k l m},
\]

используемый при изучении поля тяготения Шварцшильда.

Для двумерного пространства тензор Римана имеет вид

\[
R(X, Y) Z=K(\langle Y, Z\rangle X-\langle X, Z\rangle Y),
\]

где $K-$ Гауссова К. В этом случае кривизна Риччи равна $K$. Для трехмерного пространства тензор Римана имеет вид

\[
\begin{gathered}
R_{i k l m}=R_{i l} g_{k m}-R_{i m} g_{k l}+R_{k m} g_{i l}-R_{k l} g_{i m}+ \\
+\frac{R}{2}\left(g_{i m} g_{k l}-g_{i l} g_{k m}\right),
\end{gathered}
\]

где $g_{i j}$ - метрический тензор, $R_{i j}-$ тензор Риччи, $R$ - кривізна Риччи. В том случае, если секционные К. не зависят ни от точки, ни от двумерного направления, пространство $M^{n}$ наз. п р о с т р а н с т в о по с т о ян н о й к р и в и з н ы; тензор Римана такого пространства имеет вид (3) (константа $K$ наз. к р и в и 3 н о й п р oс т р а н с т в а $M^{n}$ ). При $n>2$ оказывается, что если во всех точках К. не зависят от направления, то пространство $M^{n}$ является пространством постоянной $\mathrm{K}$. (т е о р е м а III у $\mathbf{p}$ a).

К ри визна подмн огообразий. Пусть $\Phi$ - регулярная поеерхность в $E^{3}, \gamma$ - кривая на $\Phi$, $\alpha_{P}$ - касательная плоскость к $\Phi$ в точке $P$, через к-рую проходит кривая $\gamma$. Пусть малая окрестность точки $P$ проектируется на плоскость $\alpha_{P}$ и пусть $\bar{\gamma}-$ проекция кривой $\gamma$ на плоскость $\alpha_{p}$. Геодезической кривизной $\chi$ кривой $\gamma$ в точке $P$ наз. число, равное по модулю $К$. кривой $\bar{\gamma}$ в точке $P$. Геодезическая К. считается положительной, если вращение касательной кривой $\bar{\gamma}$ при прохождении точки $\boldsymbol{P}$ образует с направлением нормали к поверхности правый винт. Геодезическая К. является объектом внутренней геометрии поверхности Ф. Геоде зическая К. может быть вычислена по формуле

\[
x=\frac{e_{i j}\left(\frac{d^{2} x^{i}}{d s^{2}} \frac{d^{2} x^{j}}{d s^{2}}+\Gamma_{k l}^{i} \frac{d x^{k}}{d s} \frac{d x^{l}}{d s} \frac{d x^{j}}{d s}\right)}{\left(g_{i j} \frac{d x^{i}}{d s} \frac{d x^{j}}{d s}\right)^{3 / 2}},
\]

где $x^{i}(s)$ - натуральное уравнение кривой $\gamma$ в локальных координатах $x^{i}$ на $\Phi, g_{i j}-$ компоненты метрич. тензора поверхности $\Phi$ в этих координатах, $\Gamma_{k l}^{i}-$ символы Кристоффеля, $e_{i j}$ - вполне дискриминантный тензор. С помощью формулы (4) вводится понятие геодезической $К$. для кривой на абстрактном двумерном римановом пространстве. Необходимым и достаточным условием того, что кривая на римановом многообразии совпадает с геодезическої или с ее отрезком, является тождественное равенство нулю геодезической $\nprec$.

Пусть Ф - двумерное подмногообразие трехмерного риманова пространства $M$. К определению К. для $\Phi$ можно подойти двумя способами. С одной стороны, можно рассматривать Ф как риманово пространство, метрика к-рого индуцирована метрикой $M$, и определить его К. по формуле (1). Полученная таким образом К. наз. в н у т р е н н е й к р и в и з н о й. С другой стороны, можно провести построеніе, приводящее к понятию К. для поверхности в евклидовом пространстве и для подмногообразия риманова пространства. В результате получается иное понятие К.; эта К. наз. в н е шн е ӥ к р и в и з н о й. Справедливо следующее соотношение:

\[
K_{i}=K_{e}+K_{\sigma},
\]

где $K_{\sigma}-$ К. пространства $M$ в направлении касательной плоскости к $\Phi$.

Понятия нормальной, внешней и внутренней К. допускают обобщение на размерности и коразмерности изучаемого подмногообразия.

Понятие тензора Римана обобщено на ряд пространств, имеющих менее сильные структуры, чем риманово пространство. Напр., тензоры Римана и Риччи зависят лишь от аффинной структуры риманова пространства и могут быть введены и для пространства аффинной связности (однако в этом случае тензоры Римана и Риччи обладают не всеми свойствами симметрии). Напр., $\boldsymbol{R}_{i k} \neq \boldsymbol{R}_{k i}$. Другими примерами такого рода являются тензор конформной К. и тензор проективной К.

Тензор кон формн ой крйвизны (тенз о р В е й л я) имеет вид

$c_{i k l m}=R_{i k l m}-R_{l[i} g_{k] m}+R_{m[i} g_{k] l}+\frac{1}{3} R_{l[i} g_{k] m}$, где квадратные скобки означают альтернацию по за-