может остаться неразветвленным в $k\left(\ell_{n}\right)$. $\mathfrak{h}$. p. поля алгебраич. чисел с группой Галуа $\Gamma$, изоморфной аддитивной группе целых $l$-адических чисел $Z_{l}$, наз. круговыми Г-расширениями (см. [2], [3], [4]). Такое Г-расширение в случае, когда $\zeta_{l} \in k$, имеет вид $k_{\infty}=\bigcup_{n} k_{n}$, где $k_{n}=k\left(\zeta_{l} n\right)$.

лит.: [1] ле н г С., Алгебра, пер. с англ., М., 1968; [2] III а ф а р е в и ч И. Р., Дзета-функция, М., 1969; [3] к у з ьc. 267-327; ' [4] I w a s a w a K., "Ann. Math.", 1973, v. 98, № 2, p. $246-326$. Л. В. Кузъмин.

КРУГОВОЙ МЕТОД - один из наиболее общпх методов аддитивної теории чисел. Пусть $X_{1}, X_{2}, \ldots$, $X_{k}$ - произвольные множества натуральных чисел, $N$ - натуральное число и $J_{k}(N)$ - число реппений уравнения

\[
n_{1}+n_{2}+\ldots+n_{k}=N
\]

где $n_{1} \in X_{1}, n_{2} \in X_{2}, \ldots, n_{k} \in X_{k}$. Изучением велпчин $J_{k}(N)$ занимается аддитивная теория чисел; напр., если доказать, что $J_{k}(N)$ больше нуля при всех $N$, то это будет означать, что любое натуральное число является суммой $k$ слагаемых чисел множеств $X_{1}, X_{2}, \ldots, X_{k}$. Пуусть, далес, $s$ - комплексное число, $|s|<1$, іг

\[
\begin{gathered}
g_{1}(s)=\sum_{n_{1} \in X_{1}} s^{n_{1}}, g_{2}(s)=\sum_{n_{2} \in X_{2}} s^{n_{2}}, \ldots \\
\ldots, g_{k}(s)=\sum_{n_{k} \in X_{k}} s^{n_{k}} .
\end{gathered}
\]

Тогда функция $g(s)$

\[
g(s)=g_{1}(s) g_{2}(s) \ldots g_{k}(s)=\sum_{N=1}^{\infty} J_{k}(N) s^{N}
\]

является производящей функцией величин $J_{k}(N)$. По формуле Коши

\[
J_{k}(N)=\frac{1}{2 \pi i} \int_{|s|=R<1} g(s) s^{-(N+1)} d s .
\]

Последний интеграл изучается при $R \rightarrow 1-0$. Окружность интегрирования $|s|=R$ разбивается на «большие» ı «малые» дуги, центрами к-рых являются рациональные числа. Для целого ряда аддитивных задач удается достаточно полно исследовать интегралы по «большим» дугам, к-рые дают «главную» часть величины $J_{k}(N)$, и оценить интегралы по «малым» дугам, к-рые дают «остаточный» член асимптотич. формулы для $J_{k}(N)$.

Введение И. М. Виноградовым в К. м. тригонометрич. сумм не только сильно упростило его применения, но и дало возможность единым способом решать широкий круг самых разных аддитивных задач. Основой К. м. в форме тригонометрич. сумм является следующая формула:

\[
\int_{0}^{1} e^{2 \pi i \alpha m} d \alpha= \begin{cases}1, & m=0, \\ 0, & m \neq 0,\end{cases}
\]

Из этой формулы следует, что

\[
J_{k}(N)=\int_{0}^{1} s_{1}(\alpha) s_{2}(\alpha) \ldots s_{k}(\alpha) e^{-2 \pi i \alpha N} d \alpha
\]

где

\[
s_{m}(\alpha)=\sum_{n \in X_{m}, n \leqslant N} e^{2 \pi_{i} \alpha n}, \quad m=1,2, \ldots, k .
\]

Конечные суммы $s_{m}(\alpha)$ наз. тригонометрическімі. Для исследования $J_{k}(N)$ отрезок интегрирования $[0,1] \mathrm{paz}^{-}$ бивается на «большие» и «малые» дуги - отрезкі с центрами в рациональных точках с «малыми» ІІ «большими» знаменателями. Для многих аддитівных задач удается с хорошеї точностью вычислить интегралы по «большим» дугам (тригонометрич. суммы для $\alpha$ из «больших» дуг близки і рациональным тригонометрич. суммам с малым знаменателем, хорошо вычнсляются и являются «большими»); на «малых» же дугах, к-рые содеряат основную долю точек отрезка [0, 1], тригоно- метрич. суммы «малы»; их удается нетривиально оценить (см. Тригонометрических сумм метод, Виноградова метод), что позволяет получить асимптотич. формулу для $J_{k}(N)$.

С помощью К. м. в форме тригонометрич. сумм и метода И. М. Виноградова оценок тригонометрич. сумм получены наиболее сильные результаты в аддитивної теории чисел (см. Варинга проблема, Гольдбаха проблема, Гольдбаха-Варинга проблема, Гильберта- Камке проблема).

Лит.: [1] В и н о г р а д о в И. М., Метод тригонометрических сумм в теории чисел, М., 1971; [2] х у а ЈІ о-г е н, Метод тригонометрических сумм и его применения в тсории чисел, пер. с нем., М., $1964 ;$; [3] К а р а ц у б а А. А., Основы анали-
тической теории чисел, М., 1975. A. Карачуба.

КРУГОВЫЕ ТОЧКИ, ц и к л п ч е с к и е т о ч ки, на плоскости, дополненной мнимымі и бесконеqно удаленными точками,- две мнимые бесконечно удаленные точки, однородные координаты $(1, i, 0)$ и $(1,-i, 0)$ к-рых удовлетворяют уравнению любой окружности. Прямые, проходящие через К. т., наз. и з о т р о пн Ы м п р я м ы м и.

КРУЛЛЯ КОЛЫЦО - коммутатпвное целостное кольцо $A$, для к-рого существует семейство $\left(v_{i}\right)_{i \in I}$ дискретных нормирований поля частных $K$ кольца $A$, удовлетворяющее следующим условиям: а) для любого $x \in K \backslash\{0\}$ и для всех $i$, исключая, быть может, конечное число, $v_{i}(x)=0$; б) для $x \in K \backslash\{0\}$ условие $x \in A$ эквівалентно тому, что $v_{i}(x) \geqslant 0$ для всех $i \in I$. Нөрмирования $v_{i}$ наз. при этом с у щ е с т в е н н ы ми.

К. к. были рассмотрены В. Круллем [1] под названием ко л ц г о нечно го дис к р е т но го г л а в н о г п о р я д к а. Они являются наиболее естественным классом колец, в к-рых существует теория дивизоров (см. также Дивизориальныи идеал, Классов дивизоров групnа). Упорядоченная группа дивизоров К. к. $A$ канонически изоморфна упорядоченной группе $\mathbb{Z}^{(I)}$. Существенные нормирования К. к. могут быть отождествлены с множеством простых идеалов высоты 1. К. к. вполне целозамкнуто. Любое целозамкнутое нётерово кольцо, в частности дедекиндово кольцо, является К. к. Кольцо $k\left[X_{1}, \ldots, X_{n}, \ldots\right]$ многочленов от бесконечного числа переменных - пример $К$. к., не являющегося нётеровым. Вообще, любое фактөриальное кольцо - К. к. Для того чтобы К. к. было факториально, необходимо и достаточно, чтобы любой его простой идеал высоты 1 был главным.

Класс К. к. замкнут относительно операций локализации, перехода к кольцу многочленов или формальных степенных рядов, а также целого замыкания в конечном расширении поля частных $\mathrm{F}$.

Jum.: [1] K r u l l W., "J. reine und angew. Math.», 1931 Bd 167, S. 160-96; [2] З а р и с с к и й О., С а м ю ә Ј ь П.,
Коммутативная алгебра, пер. с англ:, т. 2 , М., 1963 ; [3] Б у рб а к и Н., Коммутативная алгебра, пер. с франц., М., 1971.

КРУЛЛЯ - РЕМАКА - IIMИДТА ТЕОРЕМА группа утверждений, касающихся связи между прямыми разложениями группы или кольца. Теоретико-структурная форма әтого результата известна как теорема Opе (см. Дедекиндова решетка). Для группы $G$ с произвольной системой операторов имеет место т е о р е м а III м и д т а (Р. Ремак получил этот результат для конечных групп [2], а В. Крулль - для колец [1]): если такая группа обладает главныл рядом, то любые два ее разложения в прямое произведение с неразложимыми сомножителями центрально изоморфын, т. е. между множествами сомножителей каждого из этих разложений может быть установлено взаимно однозначное соответствие и, если $\boldsymbol{A}$ и $A^{\prime}$ - соответствующие друг другу сомножители, то существует такой изоморфизм $\varphi$ : $A \rightarrow A^{\prime}$, что $a^{-1} \varphi(a)$ для всякого $a \in A$ лежит в центре группы $G$ ([3], см. также [4]). А. Г. Курош установил,