всем $T^{n}$. Это означает, что подгруппа әлементов віда

\[
\sum_{i=1}^{m} q_{i}\left(a_{i}+\mathbb{Z}\right)^{n}
\]

где $q_{i} \in \mathbb{Z}$, плотна в $T^{n}$, а подгруппа векторов вида

\[
\sum_{i=1}^{m} q_{i} a_{i}+p
\]

где $p \in \mathbb{Z}^{n}$, плотна в $\mathbb{R}^{n}$. K. т. можно вывести пиз теории двойственности для коммутативных топологических групп [3].

В случае $m=1$ К. т. превращается в следующее утверждение: для того чтобы класс $\omega+\mathbb{Z}^{n}$, где $\omega=$ $=-\left(\omega_{1}, \ldots, \omega_{n}\right) \in \mathbb{R}^{n}$, порождал $T^{n}$ как топологич. группу, необходимо Іі достаточно, чтобы числа $1, \omega_{1}$, . . . , $\boldsymbol{\omega}_{n}$ были линсйно независимы над полем $\mathbb{Q}$ рациональных чисел. В частности, тор $T^{n}$ как топологич. группа м о н о те т и ч е н, т. е. порождается одним элементом.

JKum.: [1] K r o n e c k e r L., Werke, Bd 3, Halbbd 1, Lpz., 1899; [2] Б у р б а к и Н., Общая топология. Топологические группы. Числа и связанные с ними группы и пространства, пер. с франц., М., 1969; [3] П о н т р я г и н Л. С., Непрерывные КРРОНЕКЕРА ФОРМУЛА - формула, выражающая алгебраич. сумму значений нек-рой функціІі на множестве корней системы уравнений; установлена .І. Кронекером [1], [2]. Пусть $F^{t}\left(x^{1}, \ldots, x^{n}\right), t=0,1, \ldots, n$ $f\left(x^{1}, \ldots, x^{n}\right)$ - действительнозначные непрерывно диффференцируемые в $\mathbb{R}^{n}$ такие, что система уравнениї

\[
F^{s}\left(x^{1}, \ldots, x^{n}\right)=0, \quad s=1, \ldots, n,
\]

имеет конечное число корней. Пусть уравнепие

\[
F^{0}\left(x^{1}, \ldots, x^{n}\right)=0
\]

определяет замкнутую поверхность $P$, не проходящую через корни системы (1), и $F^{0}<0$ внутри $P$. Если функции $F^{s}, s=1, \ldots, n$, рассматриваются как компоненты векторного поля в пространстве $\mathbb{R}^{n}$, то его особые точки (по определению) соответствуіт корням системы (1). Пусть $x_{\alpha}$ - некоторый корень, а $\chi\left(x_{\alpha}\right)-$ Іиндекс этой особой точки. Тогда

\[
\begin{gathered}
\frac{1}{K^{n}} \sum_{\alpha} f\left(x_{\alpha}\right) \chi\left(x_{\alpha}\right)= \\
=\int_{F^{0}<0} \frac{\Lambda}{R^{n}} d V-\int_{F^{0}=0} \frac{f D}{Q R^{n}} d S
\end{gathered}
\]

(суммирование по всем корняч), где $K^{n}-$ объем едіничной сферы $S^{n-1}$,

\[
\begin{gathered}
R=\sqrt{\sum_{s=1}^{n}\left(F^{s}\right)^{2}}, Q=\sqrt{\sum_{i=1}^{n}\left(F_{i}^{0}\right)^{2}}, \\
\Lambda=\left|\begin{array}{llll}
0 & f_{1} & \ldots & f_{n} \\
F^{1} & F_{1}^{1} & \ldots & F_{n}^{1} \\
\ldots & \ldots & \ldots & \ldots \\
F^{n} & F_{1}^{n} & \ldots & F_{n}^{n}
\end{array}\right|, \quad D=\left|\begin{array}{cccc}
F^{0} & F_{1}^{0} & \ldots & F_{n}^{0} \\
F^{1} & F_{1}^{1} & \ldots & F_{n}^{1} \\
\ldots & \ldots & \ldots & \ldots \\
F^{n} & F_{1}^{n} & \ldots & F_{n}^{n}
\end{array}\right|,
\end{gathered}
\]

и для функции $\Phi$ через $\Phi_{i}$ обознатены ее производные $\partial \Phi / \partial x^{i}$. Формула (2) и есть Фо р м у л а К р о н ек е p a.

При $f \equiv 1$ пространственный интеграл в (2) исчезает, і получается выражение для суммы индексов $\chi_{F}$ особых точек векторного поля $\left\{F^{s}\right\}$, расположенных внутрй поверхности $P$, т. е. для степени отображения поверхности $\boldsymbol{P}$ в сферу $S^{n-1}$, определяемого как ограничение на множество $P$ отображения $\stackrel{\circ}{F}^{s}=F^{s} / R, s=1, \ldots, n$. При нек-рых дополнительных условиях величина $\chi_{F}$ равна так наз. характеристике Кронекера системы функций $F^{0}, F^{\mathbf{1}}, \ldots, F^{n}$ (см. [3]).

Jum.: [1] K r o n e c k e r L., "Monatsbericht», 1869, S.159193,688-98; [2] е r о ж е, там же, 1878, S. 95-121; [3] Ч ет а е в Н. Г., Устойчивость движения. Работы по аналитиче- ской механике, М., 1962 , с. $273-313$; [4] II у а н к а p e А., О кривых, определяемых дифференциальными уравнениями,
пер. с франц., М.-Л., 1947.

КРОНЕКЕРА - КАПЕЛЛИ ТЕОРЕМА, к р и т е-

![](https://cdn.mathpix.com/cropped/2023_07_08_7121c1c7112ba4f24f3ag-1.jpg?height=37&width=829&top_left_y=274&top_left_x=992)
у р а в н е н ІІ й: для совместности системы уравнений

\[
\begin{aligned}
& a_{11} x_{1}+a_{12} x_{2}+\ldots+a_{1 n} x_{n}=b_{1} \text {, } \\
& a_{21} x_{1}+a_{22} x_{2}+\ldots+a_{2 n} x_{n}=b_{2} \text {, } \\
& a_{s 1} x_{1}+a_{s 2} x_{2}+\ldots+a_{s n} x_{n}=b_{s}
\end{aligned}
\]

необходимо ї достаточно, чтобы ранг матрицы $A=$ $=\left\|a_{i j}\right\|$ ІІз коәффициентов при неизвестных был равен рангу расширенной матрицы $\bar{A}$, получающейся пзз матрицы $A$ добавлением столбца, свободных членов $b_{i}$.

У Л. Кронекера эта теорема содержится в его лекциях, читавшихся в Берлинском университете в $1883-$ 1891 (см. [1]). А. Капелли, по-видимому, впервые дал пріведенную выше формулировку теоремы с псппользованием термина "ранг матрицы» (см. [2]).

Jum.: [1] K r o n e c k e r L., Vorlesungen über die Theorie der Determinanten, Lpz., 1903; [2] C a p e l I i A., "Revista di Matematica», 1892, v. 2, p. $54-58 ;$ [3] К у p о ш А. Г., Курс

КРОНЕКЕРОВО ПРОИЗВЕДЕНИЕ К $о$ л $е$ Ц, а Лге б р - то жс, что их тензорное произведение.

КРУГ - часть плоскости, ограниченная окружностью и содержащая ее центр. Площадь К.: $S=\pi r^{2}$, где $r$ - радиус окружности.

КРУГ КРИВИЗНЫІ, о к р у жк н о с т Б к р Iі в и зны,- окружность, имеющая с кривой в данной точке соприкосновение не ниже 2-го порядка. Центр К. к. наз. If е н т р о к р и в ІІ 3 н ы кривой в точке соприкосновения, а рациус К. к.- р а д и у с о м кр и в и зн ы. К. к. располагается в сопрікасающейся плоскости кривог̈.

КРУг сХодИМости с т е п ен н о го р я д а

\[
f(z)=\sum_{k=0}^{\infty} c_{k}(z-a)^{k}
\]

- круг віда $\Delta=\{z:|z-a|<R\}, z \in \mathbb{C}$, в к-ром ряд (1) абсолютно сходится, а вне его, прІі $|z-a|>R$, расходится. Иными словами, К. с. $\Delta$ есть внутренность множества точек сходімости ряда (1). Радиус $\boldsymbol{R}$ К. с. наз. р а д и у с о м с х о д и м о с т и ряда (1). К. с. может вырождаться в точку $a$, когда $R=0$, и может совпадать со всей открытой плоскостью переменного $z$, когда $R=$ $=\infty$. Радиус сходімости $R$ равен расстояниіо от центра ряда $a$ до множества особых точек функции $f(z)$ (об опрсделении $\boldsymbol{R}$ по коэффициентам ряда $c_{k}$ см. Коши A дамара теореиа). Любой круг $\Delta=\{z:|z|<R\}, 0 \leqslant R \leqslant$ $\leqslant \infty$, на плоскостіг $z$ являетс я К. с. нек-рого степенного ряда.

В с.тучае степенного ряда

\[
\begin{gathered}
f(z)=f\left(z_{1}, \ldots, z_{n}\right)= \\
=\sum_{k_{1}, \ldots, k_{n}=0}^{\infty} c_{k_{1} \ldots k_{n}}\left(z_{1}-a_{1}\right)^{k_{1}} \ldots\left(z_{n}-a_{n}\right)^{k_{n}}
\end{gathered}
\]

по нссколькім комплексным переменным $z_{1}, \ldots, z_{n}$, $n>1$, полигругом сходимостіг ряда (2) наз. всякий поликруг

$\Delta_{n}=\left\{z=\left(z_{1}, \ldots, z_{n}\right):\left|z_{v}-a_{v}\right|<R_{v}, \quad v=1, \ldots, n\right\}$ такой, что во всех его точках ряд (2) абсолютно сходится, а в любом поликруге вида

$\left\{z=\left(z_{1}, \ldots, z_{n}\right):\left|z_{v}-a_{v}\right|<R_{v}^{\prime}, \quad v=1, \ldots, n\right\}$,

где $\boldsymbol{R}_{v}^{\prime} \geqslant \boldsymbol{R}_{v}$ й по крайней мере одно из последних неравенств строгое, найдется хотя бы одна точка, в к-рої ряд (2) расходится. Радиусы $R_{v}, v=1, \ldots, n, 0 \leqslant R_{v} \leqslant$ $\leqslant \infty$, поликруга сходимости наз. с о пр я ж е н н ы м и