Величшна $R=0,2\left|y^{1}-y^{2}\right|$ служит для оценки погрешности метода и для автоматического выбора шага интегрирования. ЕсліІ $\varepsilon$ - предписанная точность вычислений, то шаг интегрирования выбирается следующим образом. Берется нек-рый начальный шаг и производятся вычисления по формулам (2). Вычисляется величина $R$. Пріг $R>\varepsilon$ шаг интегрирования уменьшается в два раза. IIрII $R<\varepsilon / 64$ шаг увеличивается вдвое. Если же $\varepsilon / 64<$ $<R<\varepsilon$, то піаг считается выбранным правильно. После этого в качестве начальной точки $x_{0}$ берется точка $x_{0}+h$ іг весь процесс повторяется снова. В качестве приблигженного решения выступает величина $y^{2}$. Величінна $y^{1}$ носпт вспомогательный характер.

В связи с тем, что

$y^{2}\left(x_{0}+h\right)=y_{0}+\frac{1}{6} k_{1}+\frac{2}{3} k_{4}+\frac{1}{6} h f\left(x_{0}+h, y^{1}\left(x_{0}+h\right)\right)$, то есть формула для вычисления $y^{1}$ является как бы «вложенной» в формулу для вычисления $y^{2}$, описанный выше метод оценкі погрешности и выбора шага интегрированія наз. м е т о дом в ло же н н ы $\mathbf{x} ф$ о р м. Имеются стандартные программы К.- М. м. на языке алгос [1], [2].

'Tum.: [i] C h r is t i a n s e n J., "Numer. Mach.», 1970, Bd 14, S. 317-24: [2] L u k e h a r t P. M., "Communs Assoc. Comput. Math.», 1963, v. 6, № 12, p. 737-38; [3] F o x L., Numerical solution of ordinary and partial differential eguations, computers, 1960 . B. B. Ïocnesos.

КӘ.ЕРА МЕТРИКА, к ә л е р о в а м е т р и к а,әрлитова метрика на комплексном многообразии, фундаментальная форма $\omega$ к-рой вамкнута, т. е. удовлетворяет условію $d \omega=0$. П р и м е р ы К. м.: әрмитова метріка $\sum_{k=1}^{n}\left|d z_{k}\right|^{2}$ в пространстве $\mathbb{C}^{n}, \Phi$ ФбиниIII туди метрика в комплексном проективном пространстве $\mathbb{C} P^{n}$, метрика Бергмана (см. Бергмана кернфункция) в ограниченной области пространства $\mathbb{C}^{n}$. К. м. на комплексном многообразии индуцирует К. м. на ліобомі его подмногообразии. Всякая әрмітова метрика на одномерном многообразии кәлерова.

Понятіле К. м. было впервые рассмотрено Э. Кәлером [1]. В то же время в алгебрапч. геометрии систематическі пспользовалась метрика на проективных алгебраич. эногообразлях, индуцированная метрикой Фубині - IIIтуди (см. [5]). Эта метрика является м е т p II к о й Х о д ж а, т. е. ее фундаментальная форма имест целочісленные периоды.

Эрміттова метрікка $h$ на комплексном многообразиі является кәлеровой тогда и только тогда, когда она удовлетворяет любому из следующих условий: параллельныӥ перенос вдоль любой кривой (относительно связностіг Леві-Чивита) является комплексным линеїным отображеніем, т. е. перестановочен с оператором комплексной структуры; соответствующий метрике $h$ комплексный оператор Лапласа $\square$ на диффференциальных формах удовлетворяет условию $\bar{\square}=\square$, т. е. Jan. аaca onepaтор $\Delta$ совпадает с $2 \square$; в окрестности каждої точкі существуют локальные координаты, в к-рых матрица метрики $h$ совпадает с едіничной матрицей с точностью до бесконечно малых 2-го порядка (см. [3], [6]). Jum.: [1] K ä h le r E., "Abh. Math. Semin. Univ. Hamburg", 1933, Bd 9, S. 173-86; [2] В е й л ь А., Введение в теорию

![](https://cdn.mathpix.com/cropped/2023_07_08_da1f11ec11c9f4d1095fg-1.jpg?height=43&width=831&top_left_y=1993&top_left_x=120)
пер. с франц., М., $1960 ;[4]$ У э л і с Р., Дифференциа.пьное исчистение на комплексных многообразиях, пер. с англ., M.,
$1976 ;[5]$ H o d g e W. V. D.. The theory and applications of $1976 ;[5]$ H o d ge W. V. D.. The theory and applications of
harmonic integrals, 2 ed., Camb., $1952 ;[6] \Gamma$ и ф ф и т с $\Phi$. [и др.], “Усгехи матем. наук", 1977, т. 32, в. 3, с. $119 \frac{1}{2}$.

КӘЛЕРОВА ФОРМА - фундаментальная форма Кәлера метрики на комплексном многообразии. К. Ђ. является гармонической вещественной цифференциальпой формойі тіпа $(1,1)$. Дифференціальная форма $\omega$ на комплексном многообразии $M$ служит К. ф. для нек-роӥ кәлеровой метрики тогда и только тогда, когда $\omega$ в окрестности $U$ каждой точки $x \in M$ записывается в виде

\[
\omega=i \partial \bar{\partial} p=i \sum \frac{\partial^{2} p}{\partial z_{\alpha} \partial \bar{z}_{\beta}} d z_{\alpha} \wedge d \bar{z}_{\beta},
\]

где $p$ - строго плюрисубгармонич. функция в $U, z_{1}, \ldots$, $z_{n}$ - локальные комплексные координаты.

К. Ф. наз. ф о $\mathrm{p}$ м о й $\mathrm{X}$ о д ж а, если она соответствует метрике Ходжа, т. е. имеет целочисленные периоды или, что то же, определяет целочисленный класс когомологиї.

Лит.: [1] у ә л л с Р., Дифференциальное исчисление на комплексных многообразиях, пер. с англ., М., 1976.

КӘЛЕРОВО МНОГООБРАЗИЕ - комплексное многообразше, на к-ром можно ввести Кәлера метрику. Иногда такие многообразия наз. м н о г о о б р а 3 и ям и к ә л е р о в а т и п а, а термин «К. м.» оставляется пля многообразий, снабженных кэлеровой метрикой [1]. Всякое подмногообразие К. м. является K. м. В частности, все проективные комплексные алгебраич. многообразия без особых точек являются К. м., причем кәлерова метрика на них индуцируется $\Phi_{y}$ бини - III туди метрикой на комплексном проективном гространстве. Аналогично, всякое подмногообразие в аффинном пространстве $\mathbb{C}^{n}$ (в частности, всякое III тейна многообразие) является кәлеровым. Другие примеры К. м. получаются, если рассматривать факторпростраіство $M / \Gamma$ К. м. $M$ по діскретной группе аналитич. автоморфизмов $\Gamma$, сохраняющих кәлерову метрику. В частности, любой комплексный тор есть К. М. Всякое одномерное комплексное многообразие кәлерово.

Теория гармонич. форм на компактном К. м. дает следующие свойства групп когомологий де Рама и Дольбо на таком многообразии $M$ (см. [1], [2], а также [5], где эти свойства были впервые доказаны для проективных алгебраич. многообразий):

\[
\begin{gathered}
H^{r}(M, \mathbb{C}) \cong \bigoplus \sum_{p+q=r} H^{p, q}(M), \\
I^{p, q}(M) \cong H^{q, p}(M), \\
\operatorname{dim} H^{2 r+1}(M, \mathbb{C}) \text { четна, } \\
H^{2 r}(M, \mathbb{C}) \neq 0 \text { при } r=1,2, \ldots, \frac{1}{2} \operatorname{dim}_{\mathbb{C}} M .
\end{gathered}
\]

Голоморфные формы на компактном К. м. замкнуты. В частности,

\[
H^{1}(M, \mathbb{C}) \cong A^{1} \oplus \bar{A}^{1},
\]

где $A^{1}$ - пространство всех голоморфных 1-форорм на $M$. В случае $\operatorname{dim}_{\mathbb{C}} M=1$ число

\[
\operatorname{dim} A^{1}=\frac{1}{2} \operatorname{dim} H^{1}(M, \mathbb{C})
\]

есть род компактной римановой поверхности $M$. На указанных выше свойствах основано построение примеров некэлеровых компактных многообразий, простейпіим из к-рых является поверхность Хопфа, дифффеоморфная $S^{\mathbf{1}} \times S^{\mathbf{3}}$.

F. м. $M$ наз. мног о о б р а зие м Х од жа, если кэлерова метрика на $M$ является метрикої Ходжа. Всякое проективное алгебраич. многообразие без особых точек является многообразием Ходжа относительно метрики, индуцированной метрикой Фубині Штуди. Обратно, всякое компактное комплексное многообразие $M$, снабженное кәлерової метрикой Ходжа $\eta$, допускает биголоморфное вложение в комплексное проективное пространство, причем метрика на $M$, индуцированная метрикой Фубини - IIтудіг, имеет вид $k \eta$, где $k$ - натуральное число [1], [3] (т е о р е м а Код а ир Таким образом, компактное комплексное многообразие