3) I К. П. и II К. П. разрешимы в областях $D=$ $=D_{1} \times \ldots \times D_{n} \subset \mathbb{C}^{n}$, где $D_{j}$ - плоские области и все $D_{j}$, кроме, быть может, одной, односвязны. ч. 2. 1976; [3] ' в адене в комплексный анализ, 2 изд., ские функции многих комплексных переменных, пер. с англ., M., 1969.

КУММЕРА ГИПОТЕЗА - предположение о поведении кубической Гаусса суммы

\[
\tau(\chi)=\sum_{n=0}^{p-1} \chi(n, p) e^{\pi i n / p}
\]

где $\chi(n, p)=\exp (2 \pi i$ ind $n / 3)$ - кубический характер по модулю $p \equiv 1(\bmod 3)$, а $p-$ простое число. Известно, что

\[
\tau(\chi)=\sqrt{p} e^{i \arg \tau(\chi)}
\]

При этом $\arg \tau(\chi)$ лежит либо в первом, либо в третьем, либо в пятом секстанте. В соответствии с этим Э. Куммер (E. Kummer) разбил все простые числа $p \equiv 1(\bmod 3)$ на три класса $P_{1}, P_{3}$ и $P_{5}$. Согласно К. г. в каждом из классов $P_{1}, P_{5}$ и $P_{3}$ находится бесконечное множество простых чисел, причем әти классы имеют соответственно асимптотич. плотности $1 / 2,1 / 3$ и $1 / 6$. Существуют различные обобщения К. г. на характеры более высокого порядка, чем 3. K. г. доказана в модифиццированном виде (см. [3]).

Лuт.: [1] X а с с е Г., Лекции поо тсории чисел, пер. с нем., M., 1953; [2] Д ә в ен п о р т I', Мультипликативная теория чисел, mep. c ärJ., M., 1971; [3] H c a t h-B r own D. R., Patte rson S. I. "J. reine und angew. Math.", 1979, Bd
$130, \mathrm{~S} .111-30$.

КУММЕРА ПОВЕРХНОСТЬ - алгебраич. поверхность четвертого порядка и класса, сама себе взаимная, имеющая 16 двойных точек, из к-рых 16 групп (по 6 точек каждая) расположены в одной двойной касательной плоскости к поверхности (т. е. плоскости, касающейся поверхности по конич. сечению). Уравнение 16-й степені, определягоге двоӥной әлемент, приводится к одному уравнению 6-й стегени и нескольким квадратным. Найдена Э. Куммером (Е. K ummer, 1864). К. п. принадлежит классу КЗ-поверхностей и выјеляется среди них условисм существования на ней 16 неприводимых рациональных кривых.

Лum.: [1] К л е й н Ф., Лекции о развитии математики в XIX столетии, пер. с нем., М.- J., 1937; [2] H u d s o n R., Kummer's quartic surface, Camb., 1905; [3] En r i q u e s F.,

КУММЕРА ПРЕОБРАЗОВАНИЕ - одно из преобразований числовых рядов, улучшающее сходимость; предложено Ә. Куммером (Е. K ummer). Пусть

\[
\sum_{k=1}^{\infty} a_{k}=A \text { и } \sum_{k=1}^{\infty} b_{k}=B
\]

- сходящиеся ряды и пусть существует предел

\[
\lim _{n \rightarrow \infty} \frac{a_{n}}{b_{n}}=\gamma \neq 0
\]

Тогда

\[
\sum_{k=1}^{\infty} a_{k}=\gamma B+\sum_{k=1}^{\infty}\left(1-\gamma \frac{b_{k}}{a_{k}}\right) a_{k} .
\]

Если сумма $B$ известна, то К. п. может оказаться полезным при вычислениях, так как ряд в правой части сходится быстрее ряда в левой.

Лит.: [1] Фи х т е н г о льц Г. М., Курс диффференциального и интегрального исчисления, 7 изд., т. 2, М., 1970.

КУММЕРА ПРИЗНАК - общий признак Сенатов. мости рядов с положительными членами, предложенный Э. Куммером (Е. Kummer). Пусть дан ряд

\[
\sum_{n=1}^{\infty} a_{n}=a_{1}+a_{2}+\ldots+a_{n}+\ldots
\]

и $c_{1}, c_{2}, \ldots, c_{n}, \ldots$ произвольная последовательность положительных чисел такая, что ряд $\sum_{n=1}^{\infty} \frac{1}{c_{n}}$ расходится. Если для $n>N$ выполняется неравенство

\[
K_{n} \equiv c_{n} \frac{a_{n}}{a_{n+1}}-c_{n+1} \geqslant \delta
\]

где $\delta$ - постоянное положительное чісло, то ряд (*) сходится. Если $K_{n} \leqslant 0$ для $n>N$, то ряд (*) расходится.

В прецельної форме К. П. формулируется следующим образом: пусть

\[
\lim _{n \rightarrow \infty} K_{n}=K
\]

тогда при $K>0$ ряд $(*)$ сходится, при $K<0$ - расходится

Лит.: [1] Ф и х те н г о льц Г. М., Курс дифференциального и интегрального исчисления, 7 изд., т. 2 , М., 1970.

КУММЕРА РАСIIИРЕНИЕ - рас $k$ характеристики $p \geqslant 0$ впда - аасширение поля

\[
K=k\left(\sqrt[n]{\alpha_{1}}, \ldots, \sqrt[n]{\sqrt{\alpha_{t}}}\right)
\]

где $\alpha_{1}, \ldots, \alpha_{t} \in k, \quad n-$ некоторое натуральное число, причем предполагается, что поле $k$ содержит первообразный корень $\zeta_{n}$ из 1 степени $n$ (в частности, $n$ взаимно просто с $p$ при $p \neq 0$ ). К. р. названы по имени Ә. Куммера (Е. K ummer), впервые подробно рассмотревшего расширения вида $\mathbb{Q}\left(\zeta_{n} \sqrt[n]{\alpha}\right)$, где $\mathbb{Q}$ - поле рацпональных чисел и $\alpha \in \mathbb{Q}\left(\zeta_{n}\right)$.

Основной результат теориі К. р. состоит в том, что для поля $k$, содержащего первообразный корень $\zeta_{n}$, гонечное расширение $K / k$ является куммеровым (для данного $n$ ) тогда и только тогда, когда $K / k$ - пормальное абелево расширение и группа Галуа $G(K / k)$ имеет период $n$. Любое К. р. поля $k$ полностью характеризуется своей $г$ р у п по й $\mathrm{f}$ у м ме р а $A(K / k)=B / k^{*}$, где $k^{*}$ - мультипликативная группа поля $k$, а

\[
B=\left\{x \in K^{*} \mid x^{n} \in k^{*}\right\}
\]

Суцествует невырожденное с п а р и в а н и е Ғі у мм е р а, т. е. отображение

\[
G(K / k) \times A(K / k) \longrightarrow \mu(n)
\]

где $\mu(n)$ - подгруппа группы $k^{*}$, порожденная $\zeta_{n}$. Для $\sigma \in G(K / k)$ и $a \in A(K / k)$ это сіаривание задается формулой $(\sigma, a)=(\sqrt[n]{\sqrt{\alpha}})^{\sigma-1} \in \mu(n)$, где $\alpha \in k$, a $\sqrt[n]{\alpha \in}$ $\in B$ - некоторыї представитель элемента $a$. Это спаривание огределяет каноническіӥ пзоморфизм

\[
G(K / k) \stackrel{\varphi}{\simeq} \operatorname{Hom}(A(K / k), \mu(n)) .
\]

Другими словамі, всякий автоморфизм $\sigma \in G(K / k)$ определяется своим действием на корни $\sqrt[n]{\alpha_{i}}$ в (1), I это действие может быть прогзвольным, если только корни $\sqrt[n]{\alpha_{i}}$ независимы. В частності, если $G(K / k)-$ циклич. группа, то $K=k(\sqrt[n]{\alpha})$, где $\alpha \in k^{*}$.

Пусть $k$ - нормальное расширение поля $k_{0}$ II $K \subset k$. Поле $K$ тогда и только тогда нормально над $k_{0}$, когда $A(K / k)$ переходит в себя под действием $G\left(k / k_{0}\right)$.'В этом случае изоморфизм (2) являстся $G\left(k / k_{0}\right)$-операторным, т. е. если $\tau \in G\left(k / k_{0}\right), \quad \sigma \in G(K / k)$ и

\[
\varphi(\sigma)=\chi: A(K / k) \longrightarrow \mu(n),
\]

то $\varphi\left(\sigma^{\tau}\right)=\tau \chi$, где $(\tau \chi)(a)=\tau\left(\chi\left(\tau^{-1} a\right)\right)$. (Группа $G\left(k / k_{0}\right)$ действует на $G(K / k)$ с помощыо сопряжения в $G\left(K / k_{0}\right)$.) Это обстоятельство позволяет сводить многие вопросы об абелевых расширениях периода $n$ поля $k$ к теории К. р. даже в том случае, когда $\zeta_{n} \notin k$. А имен-