КЭМПБЕЛЛА - ХАУСДОРФА ФОРМУ ЛА - ФорМУла для вычисления выражения

\[
w=\ln \left(e^{u} e^{v}\right)
\]

в алгебре формальных степенных рядов от некоммутирующих ассоциативных $u$ и $v$. Более точно, пусть $A$ свободная ассоциативная алгебра с единицей над полем $\mathbf{Q}$ со свободными образующими $u$ и $v$, а $L-$ ее подалгебра Ли, порожденная әтими же элементами относительно операции коммутирования $[x, y]=x y-y x ; \quad$ и пусть $\hat{A}$ и $\widehat{L}$ - пополнения алгебр $A$ и $L$ степенными рядами әлементов из $A$ и $L$. Тогда отображение

\[
\exp : x \longrightarrow e^{x}=\sum_{n=0}^{\infty} \frac{x^{n}}{n !}
\]

является непрерывной биекцией алгебры $\widehat{A}$ на мультипликативную группу $1+\widehat{A}_{1}$, где $\widehat{A}_{1}--$ совокупность рядов без свободного члена. Обратным к этому отображению является отображение

$\ln : y \rightarrow \ln (y)=\sum_{n=1}^{\infty} \frac{(-1)^{n-1}}{n}(y-1)^{n}$.

Ограничение отображения $\exp$ на $\hat{L}$ является биекцией алгебры $\hat{A}$ на группу $1+\hat{L}$. Это позволяет ввести групповую операцию $x \circ y=\ln \left(e^{x} e^{y}\right)$ на множестве әлементов алгебры Ли $\widehat{L}$; причем в получаемой таким образом группе подгруппа, порожденная элементами $u$ и $v$, оказывается свободной. К.- Х. ф. дает выражение для $u \circ v$ в виде степенного ряда от $u$ и $v$ :

\[
\begin{aligned}
& \sum_{m} \sum_{p_{i} q_{i}} \frac{(-1)^{m-1}}{m\left(p_{i}+q_{i}\right)} \times
\end{aligned}
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_963152084ee68703f127g-1.jpg?height=111&width=680&top_left_y=1170&top_left_x=196)

или (в терминах присоединенного представления $(\operatorname{ad} x)(y)=[x, y])$ :

\[
w=\sum_{n=1}^{\infty} \frac{1}{n} \sum_{r+s=n, r, s \geqslant 0}\left(w_{r, s}^{\prime}+w_{r, s}^{\prime \prime}\right)
\]

где

\[
\begin{gathered}
w_{r, s}^{\prime}=\sum_{m \geqslant 1} \frac{(-1)^{m-1}}{m} \times \\
\times \sum^{*}\left(\left(\prod_{i=1}^{m-1} \frac{(\mathrm{ad} u)^{r} 1}{r_{i} !} \frac{(\mathrm{ad} v)^{s_{1}}}{s_{i} !}\right) \frac{(\mathrm{ad} u)^{r_{m}}}{r_{m} !}\right)(v), \\
w_{r, s}^{\prime \prime}=\sum_{m \geqslant 1} \frac{(-1)^{m-1}}{m} \times \\
\times \sum^{* *}\left(\prod_{i=1}^{m-1} \frac{(\mathrm{ad} u)^{r} i}{r_{i} !} \frac{(\mathrm{ad} v)^{s}}{s_{i} !}\right)(u) .
\end{gathered}
\]

Здесь $\Sigma *$ означает суммирование по $r_{1}+\ldots+r_{m}=r s_{1}+$ $\ldots+s_{m-1}=s-1, r_{1}+s_{1} \geqslant 1, . ., r_{m-1}+s_{m-1} \geqslant 1$, a $\Sigma^{* *}-$ суммирование по $r_{1}+\ldots+r_{m-1}=r-1, s_{1}+\ldots+$ $+s_{m-1}=s, \quad r_{1}+s_{1} \geqslant 1, . ., r_{m-1}+s_{m-1} \geqslant 1$.

Первым задачу о разыскании выражения $w$ рассмотрел Дж. Кәмпбелл [1]. Ф. Хаусдорф [2] доказал, что $w$ выражается через коммутаторы от әлементов $u$ и $v$, т. е. принадлежит алгебре Ли $\hat{L}$.

Если $\mathfrak{g}$ - нормированная алгебра Ли над полным недискретно нормированным полем $K$, то ряд (*), где $u, v \in \mathfrak{g}$, сходится в окрестности нуля. Это пөзволяет определить в окрестности нуля пространства $\mathfrak{g}$ структуру локальной банаховой группы Ли над $\dot{K}$ (в ультраметрическом случае - структуру банаховой группы Ли), алгеброй Ли к-рой является g. Этот факт дает одно из доказательств существования локальной группы Ли с заданной алгеброй Ли (3-я т е о р е м а Л и). Обратно, во всякой локальной группе Ли умножение в канонических координатах задается К.X. ф.

IIm.: [1] C a m p b e 1 l J. E., "Proc. London Math. Soc.», $1897, \mathrm{v} .28$, p. $381-90 ; 1898, \mathrm{v} .29$, p. $14-32 ;[2] \mathrm{H}$ a u sб o r f f F., "Lеipziger Ber.", 1906, Вd 58, S. 19-48; [3] Б у pгебры Ји и группы Ли, пер. с франц., М., 1976; [4] С е р р Ж.П., Алгебры Ји и группы Ји, пер. с франц., М., 1969; [5] Теория алгебр Ли. Топология групп Ли. Семинар "Софус Ли", пер. с т ә р Д., Комбинаторная теория групп, пер. с апгл., М., 1974. КЮННЕТА ФОРМУЛА - формула, выражающая гомологии (или когомологии) тензорного произведения комплексов или прямого произведения пространств через гомологии (когомологии) сомножителей.

Пусть $\Lambda$ - ассоциативное кольцо с единицей, $A$ и $C$ - цепные комплексы соответственно правых и левых $\Lambda$-модулей. Пусть $A \otimes C$ - комплекс, ассоциированный с тензорным произведениел комплексов $A$ и $C$ над $\Lambda$. Если

$\operatorname{Tor}_{1}(B(A), B(C))=\operatorname{Tor}_{1}\left(H_{*}(A), B(C)\right)=$

$=\operatorname{Tor}_{1}(B(A), Z(C))=\operatorname{Tor}_{1}\left(H_{*}(A), Z(C)\right)=0$,

то имеет место точная последовательность градуированных кодулей

\[
0 \longrightarrow H_{*}(A) \otimes H_{*}(C) \stackrel{\alpha}{\longrightarrow} H_{*}(A \otimes C) \stackrel{\beta}{\longrightarrow}
\]\[
\longrightarrow \operatorname{Tor}_{1}\left(H_{*}(A), H_{*}(C)\right) \longrightarrow 0
\]

где $\alpha$ - гомоморфизм степени 0 , а $\beta$ - стешени -1 (см. [2]). Для коцепных комплексов имеется аналогичная точная последовательность с гомоморфизмом $\beta$ степени +1 . Если $H_{*}\left(\operatorname{Tor}_{1}(A, C)\right)=0$ (напр., $A$ или $C-$ плоский $\Lambda$-модуль) и $\Lambda$ наследственно, то последовательность (1) существует и расщепляется [2], [3], так что

\[
\begin{gathered}
H_{n}(A \otimes C)=\sum_{p+q=n} H_{p}(A) \otimes H_{q}(C)+ \\
+\sum_{p+q=n-1} \operatorname{Tor}_{1}\left(H_{p}(A), H_{q}(C)\right) .
\end{gathered}
\]

Эта формула наз. ф о р м у л й К ю н ш е т а; иногда формулой, или с о о т но ше ни е м, К ю н е т а называют и точную последовательность (1). Имеет место обобщение формулы (1), в к-ром тензорное произведение заменяется произвольным двойным функтором $T(A, C)$ на категории $\Lambda$-модулей со значениями в той же категории, ковариантным по каждому аргументу. Рассматривается также случай функтора $T$, ковариантного по $A$ и контравариантного по $C$. В частности, функтор $T(A, C)=\operatorname{Hom}(A, C)$ приводит к формуле, выражающей когомологии $H^{*}(\operatorname{Hom}(A, C))$, где $A-$ правый цепной, а $C$ - левый коцепной комплексы над $\Lambda$, через $H_{*}(A)$ и $H^{*}(C)$, а именно, если $\Lambda$ наследственно и $H^{*}\left(\operatorname{Ext}^{1}(A, C)\right)=0$ (напр., $A$ свободен), то имеет место расщепляемая точная последовательность

$0 \longrightarrow \operatorname{Ext}^{1}\left(H_{*}(A), H^{*}(C)\right) \stackrel{\beta^{\prime}}{\longrightarrow} H^{*}(\operatorname{Hom}(A, C)) \stackrel{\alpha^{\prime}}{\longrightarrow}$

$\stackrel{\alpha^{\prime}}{\longrightarrow} \operatorname{Hom}\left(H_{*}(A), H^{*}(C)\right) \longrightarrow 0$,

где $\alpha^{\prime}$ - гомоморфизм степени 0 , а $\beta^{\prime}-$ сгепени +1 (cM. $[2],[3])$.

Пусть $X, \dot{Y}$ - топологич. пространства, а $L, M-$ модули над кольцом главных идеалов $\boldsymbol{R}$, причем $\operatorname{Tor}_{1}(L, M)=0$. Тогда сингулярные гомологии пространств $X, Y, X \times Y$ связаны следующей расщепляемой точной последовательностью

$0 \longrightarrow H_{*}(X, L) \otimes H_{*}(Y, M) \stackrel{\alpha}{\longrightarrow} H_{*}(X \times Y, L \otimes M) \stackrel{\beta}{\longrightarrow}$ $\stackrel{\beta}{\longrightarrow} \operatorname{Tor}_{1}\left(H_{*}(X, L), H_{*}(Y, M)\right) \longrightarrow 0$

где $\alpha$ - гомоморфизм степени 0 , а $\beta$ - степени - 1 . Если предположить дополнительно, что либо все $H_{k}(X, R)$ и $H_{k}(Y, R)$, либо все $H_{k}(Y, R)$ и $M$ конечно по-