$\mathbf{A Б} \mathbf{A K}$ - 1) Счетная доска, применявшіаяся для арифметич. вычислений в Древней Греции, Риме, затем в Зап. Европе - до 18 в. Доска разделялась на полосы, счет осуществлялся передвижением находяпихся в полосах счетных марок (костяшек, камней іл т. П.). В странах Дальнего Востока распространен китайский аналог A. - суан-пан, в России - счеты. 2) В номографии особый чертеж (т. н. сетчатая номограмма). БCЭ-з.

АБЕЛЕВ ДИФФЕРЕНЦИАЛ - голоморф̧ный или мероморфный дифференциал на комгактной, или замкнутой, римановой поверхности $S$ (см. Дифяеренциал на римановой поверхности).

Пусть $g$ - род поверхности $S ; a_{1} b_{1} a_{2} b_{2} \ldots a_{g} b_{g}-$ циклы канонич. базнса гомологий $S$. $\mathrm{B}$ зависимости от характера особенностей различают А. д. трех родов: I, II и III, причем имеют место строгие включения:

![](https://cdn.mathpix.com/cropped/2023_07_08_875b8f059e02a6f0ef7dg-1.jpg?height=36&width=826&top_left_y=496&top_left_x=30)
$S$ дифференциалы 1-го порядка, к-рые в окрестности $U$ каждой точки $P_{0} \in S$ имеют вид $\omega=p d z=p(z) d z$, где $z=x+i y-$ локальная униформизпрующая переменная в $U$, $d z=d x+i d y$, а $p(z)$ - голоморфиая, или регуляршая, аналитич. функция от $z$ в $U$. С.ложение А. д. и умножение на голоморфную функцию определяются естественными правилами: если

To

\[
\omega=p d z, \pi=q d z, a=a(z),
\]

\[
\omega+\pi=(p+q) d z, \quad a \omega=(a p) d z .
\]

![](https://cdn.mathpix.com/cropped/2023_07_08_875b8f059e02a6f0ef7dg-1.jpg?height=42&width=830&top_left_y=847&top_left_x=25)
мерности $g$. После введения скалярного пропзведения

\[
(\omega, \pi)=\iint_{S} \omega \approx \bar{\pi}
\]

где $\omega: \bar{\pi}-$ внешнее произведение $\omega$ на звездно сопряженный дифференциал $\bar{\pi}$, пространство $\mathfrak{Y}$ превращается в гильбертово пространство.

Пусть $A_{1}, B_{1}, A_{2}, B_{2}, \ldots, A_{g}, B_{g}$ суть $A$ - и $B$-периоды $A$. д. І рода $\omega$, т. е. интегралы

\[
A_{j}=\int_{a_{j}} \omega, \quad B_{j}=\int_{b_{j}} \omega, \quad j=1,2, \ldots, g .
\]

Тогда имеет место соотношение:

\[
\|\omega\|^{2}=i \sum_{j=1}^{g}\left(A_{j} \bar{B}_{j}-B_{j} \bar{A}_{j}\right) \geqslant 0 .
\]

Если $A_{1}^{\prime}, B_{1}^{\prime}, A_{2}^{\prime}, B_{2}^{\prime}, \ldots, A_{g}^{\prime}, B_{g}^{\prime}$ - периоды другого А. д. I рода $\pi$, то

\[
i(\omega, \bar{\pi})=\sum_{j=1}^{g}\left(A_{j} B_{j}^{\prime}-B_{j} A_{j}^{\prime}\right)=0 .
\]

Соотношения (1) и (2) наз. 6 и ли и е й ны м и с о о тно ше ния я и Р има на для А. д. I рода. Канонич. 6 а з и с А. д. I рода, т. е. канонич. базис $\varphi_{1}$, $\varphi_{2}, \ldots, \varphi_{g}$ пространства $\mathfrak{A}$, выбирается таким образом, पTO

\[
A_{i j}=\int_{a_{i}} \varphi_{i}=\delta_{i j}
\]

где $\delta_{i i}=1$ и $\delta_{i j}=0$ ири $j \neq i$. При этом матрица $\left(B_{i j}\right)$, $i, j=1,2, \ldots, g, B$-периодов

\[
B_{i j}=\int_{b_{j}} \varphi_{i}
\]